### PR TITLE
HADOOP-19056. Highlight RBF features and improvements targeting version 3.4.

### PR DESCRIPTION
**Pull request by tasanuma**
### Description of PR

JIRA: HADOOP-19056

A large number of developers from various companies have contributed to RBF, and I want to highlight recent RBF features and improvements.

- Support observer node from Router-Based Federation
- Enhanced IPC throughput between Router and NameNode
- Improved isolation for downstream name nodes.

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?

### CODE REVIEW

**Comment by tasanuma** [comment]
@slfan1989 I'm really sorry for being late, but if there is a chance to incorporate changes into 3.4.0, could you consider including this PR? If RC1 has already been created, perhaps it would be best for us to simply merge this into the trunk.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 33s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  42m 56s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 25s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  76m 17s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 13s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 15s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  32m 25s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 36s |  |  The patch does not generate ASF License warnings.  |
|  |   | 114m 14s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6512/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6512 |
| Optional Tests | dupname asflicense mvnsite codespell detsecrets |
| uname | Linux 7409fb68ea70 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 62806a983ede08f694ca7830bdf7b3cb8abce17b |
| Max. process+thread count | 718 (vs. ulimit of 5500) |
| modules | C: hadoop-project U: hadoop-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6512/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by slfan1989 — APPROVED** [review]

**Comment by slfan1989** [comment]
> @slfan1989 I'm really sorry for being late, but if there is a chance to incorporate changes into 3.4.0, could you consider including this PR? If RC1 has already been created, perhaps it would be best for us to simply merge this into the trunk.

@tasanuma Thank you very much for providing the RBF Highlight. We can add this part of the content to Hadoop-3.4.0 RC2. Hadoop-3.4.0-RC1 has been packaged and voting will begin soon.

cc: @Hexiaoqiao

**Comment by tasanuma** [comment]
@slfan1989 I understand. Thank you!

**Comment by brahmareddybattula** [comment]
@tasanuma thanks for reporting this and collecting all these jira's. 
are  these part of hadoop-3.3 itself..?

**Comment by tasanuma** [comment]
@brahmareddybattula Thanks for your review.
In the JIRA issues I highlighted, only HADOOP-13144 has been released in 3.3.5. However, I included it because HADOOP-13144, along with HDFS-13274 and HDFS-15757, are a set that enhances the IPC throughput for RBF.

**Comment by slfan1989** [comment]
@tasanuma Thanks for the contribution! merged into trunk.

**Comment by tasanuma** [comment]
Thanks for merging it, @slfan1989.

**Comment by slfan1989** [comment]
@tasanuma Hadoop-3.4.0-RC1 and Hadoop-Thirdparty-1.2.0-RC0 voting has started.  I kindly request your assistance in reviewing and providing some suggestions. Thank you very much!

[VOTE] Release Apache Hadoop 3.4.0 (RC1)
https://lists.apache.org/thread/gzx1tr0x57oh7q88fh8hd0917jl00mf6

[VOTE] Release Apache Hadoop Thirdparty 1.2.0 (RC0)
https://lists.apache.org/thread/s5n58oqgnjkljo2xj8tsdm1h5jw59w06

cc: @Hexiaoqiao

**Pull request merged**
