### PR TITLE
HDDS-1876. hadoop27 acceptance test cannot be run

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Rename leftover file that was missed in cleanup (a42d4b1082c) after merge to `ozone-0.4.1` (fc3bfdc5352).

https://issues.apache.org/jira/browse/HDDS-1876

## How was this patch tested?

```
$ cd hadoop-ozone/dist/target/ozone-0.4.1-SNAPSHOT/compose/ozone-mr/hadoop27
$ ./test.sh
...
hadoop27-createmrenv :: Create directories required for MR test       | PASS |
...
hadoop27-hadoopo3fs :: Test ozone fs with hadoopfs                    | PASS |
...
hadoop27-mapreduce :: Execute MR jobs                                 | PASS |
...
```

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 141 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ ozone-0.4.1 Compile Tests _ |
| +1 | mvninstall | 946 | ozone-0.4.1 passed |
| +1 | compile | 381 | ozone-0.4.1 passed |
| +1 | mvnsite | 0 | ozone-0.4.1 passed |
| +1 | shadedclient | 2270 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 172 | ozone-0.4.1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 561 | the patch passed |
| +1 | compile | 371 | the patch passed |
| +1 | javac | 371 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 726 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 167 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 383 | hadoop-hdds in the patch failed. |
| -1 | unit | 1957 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 43 | The patch does not generate ASF License warnings. |
| | | 6998 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.ozone.TestStorageContainerManager |
|   | hadoop.hdds.scm.pipeline.TestSCMPipelineManager |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |
|   | hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.hdds.scm.pipeline.TestRatisPipelineCreateAndDestory |
|   | hadoop.ozone.client.rpc.TestMultiBlockWritesWithDnFailures |
|   | hadoop.ozone.client.rpc.TestWatchForCommit |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1191/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1191 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient |
| uname | Linux 49474aa47094 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | ozone-0.4.1 / 14df46b |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1191/1/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1191/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1191/1/testReport/ |
| Max. process+thread count | 4260 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/dist U: hadoop-ozone/dist |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1191/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by adoroszlai** [comment]
@anuengineer please review

(Acceptance test is stuck in CI because it tries to run `.../ozone-0.5.0-SNAPSHOT/compose/test-all.sh` after building `ozone-0.4.1-SNAPSHOT`...)

**Comment by elek** [comment]
> (Acceptance test is stuck in CI because it tries to run .../ozone-0.5.0-SNAPSHOT/compose/test-all.sh after building ozone-0.4.1-SNAPSHOT...)

This will be fixed with in the new test executor: https://github.com/elek/argo-ozone

**Pull request closed without merging**
