### PR TITLE
HDFS-16270.Improve NNThroughputBenchmark#printUsage() related to block size.

### PR DESCRIPTION
**Pull request by jianghuazhu**
### Description of PR
When NNThroughputBenchmark#printUsage() is executed, some configurations are verified first, and the correct prompts are printed.

### How was this patch tested?
This is to print some information, the test pressure is not great.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 58s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  34m 16s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   1m 24s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |   1m 15s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  checkstyle  |   1m  1s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 20s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   0m 56s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   1m 26s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |   3m 14s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  24m 12s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 14s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 17s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |   1m 17s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  8s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |   1m  8s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  1s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 53s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 16s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 47s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   1m 18s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |   3m 20s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  23m 54s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 383m 26s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3547/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 54s |  |  The patch does not generate ASF License warnings.  |
|  |   | 487m  4s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestHDFSFileSystemContract |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3547/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3547 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux b9993f782838 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 4b3a9d7e04fd7e7d55e1af93e07691b379e8d8c7 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3547/1/testReport/ |
| Max. process+thread count | 2009 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3547/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by jianghuazhu** [comment]
In the results of jenkins, there are some exceptions, such as:
TestHDFSFileSystemContract
TestLeaseRecovery
TestFileTruncate
TestBlockTokenWithDFSStriped
TestViewDistributedFileSystemWithMountLinks
After analysis, it does not seem to have much connection with the code I submitted.

@tomscut  @prasad-acit , would you like to spend some time to help review this pr.
Thank you very much.

**Comment by tomscut** [comment]
> In the results of jenkins, there are some exceptions, such as: TestHDFSFileSystemContract TestLeaseRecovery TestFileTruncate TestBlockTokenWithDFSStriped TestViewDistributedFileSystemWithMountLinks After analysis, it does not seem to have much connection with the code I submitted.
> 
> @tomscut @prasad-acit , would you like to spend some time to help review this pr. Thank you very much.

Hi @jianghuazhu , sorry for the late reply. 

IMO, there's nothing wrong with this hint.

Because when you specify the remote namenode with ```-fs```, if you do not set ```dfs.namenode.fs-limits.min-block-size=16``` (because default ```BLOCK_SIZE = 16```), the default value of ```dfs.namenode.fs-limits.min-block-size``` on remote namenode will be 1024*1024 -> 1048576, and which will causes the following exception.

nn-benchmark

**Review by tomscut — COMMENTED** [review]
Hi @jianghuazhu , sorry for the late reply.

IMO, there's nothing wrong with this hint.

Because when you specify the remote namenode with -fs, if you do not set dfs.namenode.fs-limits.min-block-size=16 (because default BLOCK_SIZE = 16), the default value of dfs.namenode.fs-limits.min-block-size on remote namenode will be 1024*1024 -> 1048576, and which will causes the following exception.

nn-benchmark

**Comment by jianghuazhu** [comment]
@tomscut, thank you very much for your comment.
When connecting to a remote namenode, by default, if you do not set dfs.namenode.fs-limits.min-block-size, we will get the exception you listed. I agree with this point.

But when I test a failed scenario, I will get some additional information.
The scenario I tested was like this:
conf.setInt(DFSConfigKeys.DFS_NAMENODE_MIN_BLOCK_SIZE_KEY, 16);
    conf.setInt(DFSConfigKeys.DFS_BLOCK_SIZE_KEY, 16);
To access the remote namenode, "-fs=hdfs://xxxx, op=xxxx", where op is an undefined operation.
At this point, I still get the following prompt:
'If connecting to a remote NameNode with -fs option, dfs.namenode.fs-limits.min-block-size should be set to 16.'
Because the values ​​of'dfs.namenode.fs-limits.min-block-size' and'dfs.block.size' have been set in advance above, it still prompts'dfs.namenode.fs-limits.min-block-size should be set to 16.'.
I think the prompt here should make a judgment. If the value of'dfs.block.size' is equal to 16, the above information should not be obtained.
This is my idea. @tomscut Welcome to continue to communicate.

**Comment by tomscut** [comment]
> ### Description of PR
> When NNThroughputBenchmark#printUsage() is executed, some configurations are verified first, and the correct prompts are printed.
> 
> ### How was this patch tested?
> This is to print some information, the test pressure is not great.



> @tomscut, thank you very much for your comment. When connecting to a remote namenode, by default, if you do not set dfs.namenode.fs-limits.min-block-size, we will get the exception you listed. I agree with this point.
> 
> But when I test a failed scenario, I will get some additional information. The scenario I tested was like this: conf.setInt(DFSConfigKeys.DFS_NAMENODE_MIN_BLOCK_SIZE_KEY, 16); conf.setInt(DFSConfigKeys.DFS_BLOCK_SIZE_KEY, 16); To access the remote namenode, "-fs=hdfs://xxxx, op=xxxx", where op is an undefined operation. At this point, I still get the following prompt: 'If connecting to a remote NameNode with -fs option, dfs.namenode.fs-limits.min-block-size should be set to 16.' Because the values ​​of'dfs.namenode.fs-limits.min-block-size' and'dfs.block.size' have been set in advance above, it still prompts'dfs.namenode.fs-limits.min-block-size should be set to 16.'. I think the prompt here should make a judgment. If the value of'dfs.block.size' is equal to 16, the above information should not be obtained. This is my idea. @tomscut Welcome to continue to communicate.

```
conf.setInt(DFSConfigKeys.DFS_NAMENODE_MIN_BLOCK_SIZE_KEY, 16);
```
Did you set this on remote namenode?

**Comment by jianghuazhu** [comment]
@tomscut, thanks for your comment.
Yes, I call the remote node through a program.
Here are some important points:
image

Here are some logs seen on the remote namenode:
2021-10-15 14:59:08,571 INFO org.apache.hadoop.hdfs.server.namenode.NameNode: Reported DataNode version '3.4.0-SNAPSHOT' of DN DatanodeRegistration(xxx.xxx.xxx.xxx:1, datanodeUuid=b54b63de-c160-4128-9aa2-a870f4abc547, infoPort=9864, infoSecurePort=9865, ipcPort=9867, storageInfo=lv=-67;cid=CID-19e9fbae-7dc0-40e3-8a6f-9c624238ce3b;nsid=1602871543;c=1629600549198) does not match NameNode version ‘xxxx’. Note: This is normal during a rolling upgrade.
2021-10-15 14:59:08,571 INFO org.apache.hadoop.hdfs.server.namenode.NameNode: BLOCK* registerDatanode: xxx.xxx.xxx.xxx:1
2021-10-15 14:59:08,571 INFO org.apache.hadoop.net.NetworkTopology: Removing a node: /default-rack/xxx.xxx.xxx.xxx:1
2021-10-15 14:59:08,572 INFO org.apache.hadoop.net.NetworkTopology: Adding a new node: /default-rack/xxx.xxx.xxx.xxx:1
2021-10-15 14:59:08,572 INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockReportLeaseManager: Registered DN b54b63de-c160-4128-9aa2-a870f4abc547 (xxx.xxx.xxx.xxx:1).
2021-10-15 14:59:08,692 INFO org.apache.hadoop.hdfs.server.blockmanagement.DatanodeDescriptor: Adding new storage ID DS-cde7d026-de8f-4bfb-a0a0-73790657c01f for DN xxx.xxx.xxx.xxx:1
2021-10-15 14:59:09,137 INFO org.apache.hadoop.hdfs.server.namenode.NameNode: Reported DataNode version '3.4.0-SNAPSHOT' of DN DatanodeRegistration(xxx.xxx.xxx.xxx:2, datanodeUuid=5e71d8d7-3c86-43a0-88a4-32fdef269cea, infoPort=9864, infoSecurePort=9865, ipcPort=9867, storageInfo=lv=-67;cid=CID-19e9fbae-7dc0-40e3-8a6f-9c624238ce3b;nsid=1602871543;c=1629600549198) does not match NameNode version ‘xxxx’. Note: This is normal during a rolling upgrade.
2021-10-15 14:59:09,137 INFO org.apache.hadoop.hdfs.server.namenode.NameNode: BLOCK* registerDatanode: xxx.xxx.xxx.xxx:2
2021-10-15 14:59:09,138 INFO org.apache.hadoop.net.NetworkTopology: Removing a node: /default-rack/xxx.xxx.xxx.xxx:2
2021-10-15 14:59:09,138 INFO org.apache.hadoop.net.NetworkTopology: Adding a new node: /default-rack/xxx.xxx.xxx.xxx:2
2021-10-15 14:59:09,138 INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockReportLeaseManager: Registered DN 5e71d8d7-3c86-43a0-88a4-32fdef269cea (xxx.xxx.xxx.xxx:2).

By the way, this is a normal visit.
When the exception occurred, I also visited the same remote node.

@tomscut Welcome to continue to communicate.

**Comment by tomscut** [comment]
> @tomscut, thanks for your comment. Yes, I call the remote node through a program. Here are some important points: image
> 
> Here are some logs seen on the remote namenode: 2021-10-15 14:59:08,571 INFO org.apache.hadoop.hdfs.server.namenode.NameNode: Reported DataNode version '3.4.0-SNAPSHOT' of DN DatanodeRegistration(xxx.xxx.xxx.xxx:1, datanodeUuid=b54b63de-c160-4128-9aa2-a870f4abc547, infoPort=9864, infoSecurePort=9865, ipcPort=9867, storageInfo=lv=-67;cid=CID-19e9fbae-7dc0-40e3-8a6f-9c624238ce3b;nsid=1602871543;c=1629600549198) does not match NameNode version ‘xxxx’. Note: This is normal during a rolling upgrade. 2021-10-15 14:59:08,571 INFO org.apache.hadoop.hdfs.server.namenode.NameNode: BLOCK* registerDatanode: xxx.xxx.xxx.xxx:1 2021-10-15 14:59:08,571 INFO org.apache.hadoop.net.NetworkTopology: Removing a node: /default-rack/xxx.xxx.xxx.xxx:1 2021-10-15 14:59:08,572 INFO org.apache.hadoop.net.NetworkTopology: Adding a new node: /default-rack/xxx.xxx.xxx.xxx:1 2021-10-15 14:59:08,572 INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockReportLeaseManager: Registered DN b54b63de-c160-4128-9aa2-a870f4abc547 (xxx.xxx.xxx.xxx:1). 2021-10-15 14:59:08,692 INFO org.apache.hadoop.hdfs.server.blockmanagement.DatanodeDescriptor: Adding new storage ID DS-cde7d026-de8f-4bfb-a0a0-73790657c01f for DN xxx.xxx.xxx.xxx:1 2021-10-15 14:59:09,137 INFO org.apache.hadoop.hdfs.server.namenode.NameNode: Reported DataNode version '3.4.0-SNAPSHOT' of DN DatanodeRegistration(xxx.xxx.xxx.xxx:2, datanodeUuid=5e71d8d7-3c86-43a0-88a4-32fdef269cea, infoPort=9864, infoSecurePort=9865, ipcPort=9867, storageInfo=lv=-67;cid=CID-19e9fbae-7dc0-40e3-8a6f-9c624238ce3b;nsid=1602871543;c=1629600549198) does not match NameNode version ‘xxxx’. Note: This is normal during a rolling upgrade. 2021-10-15 14:59:09,137 INFO org.apache.hadoop.hdfs.server.namenode.NameNode: BLOCK* registerDatanode: xxx.xxx.xxx.xxx:2 2021-10-15 14:59:09,138 INFO org.apache.hadoop.net.NetworkTopology: Removing a node: /default-rack/xxx.xxx.xxx.xxx:2 2021-10-15 14:59:09,138 INFO org.apache.hadoop.net.NetworkTopology: Adding a new node: /default-rack/xxx.xxx.xxx.xxx:2 2021-10-15 14:59:09,138 INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockReportLeaseManager: Registered DN 5e71d8d7-3c86-43a0-88a4-32fdef269cea (xxx.xxx.xxx.xxx:2).
> 
> By the way, this is a normal visit. When the exception occurred, I also visited the same remote node.
> 
> @tomscut Welcome to continue to communicate.


I think the hint means that ```conf.setInt(DFSConfigKeys.DFS_NAMENODE_MIN_BLOCK_SIZE_KEY, 16)``` should be set on remote namenode, it takes effect on the server side.

After I set ```dfs.namenode.fs-limits.min-block-size=16``` on remote namenode, NNBenchmark can be submitted.
nnbenchmark

**Comment by jianghuazhu** [comment]
Thanks @tomscut for the comment and review.

**Pull request closed without merging**
