### PR TITLE
Fix winutils typos

### PR DESCRIPTION
**Pull request by GauthamBanasandra**
### Description of PR
Fixed some typos in winutils.

### How was this patch tested?
Not needed.

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  35m 16s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  1s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  12m 57s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  22m 49s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  19m 54s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 11s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  77m 53s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 15s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 40s |  |  the patch passed  |
| -1 :x: |  cc  |  19m 40s | [/results-compile-cc-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3484/1/artifact/out/results-compile-cc-root.txt) |  root generated 39 new + 166 unchanged - 39 fixed = 205 total (was 205)  |
| +1 :green_heart: |  golang  |  19m 40s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  19m 40s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   2m 13s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  20m 36s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |  19m 34s | [/patch-unit-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3484/1/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt) |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |  34m 42s |  |  hadoop-hdfs-native-client in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 53s |  |  The patch does not generate ASF License warnings.  |
|  |   | 212m  6s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.crypto.TestCryptoStreamsWithOpensslSm4CtrCryptoCodec |
|   | hadoop.crypto.TestCryptoCodec |
|   | hadoop.service.launcher.TestServiceInterruptHandling |
|   | hadoop.fs.TestLocalFSCopyFromLocal |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3484/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3484 |
| Optional Tests | dupname asflicense compile cc mvnsite javac unit codespell golang |
| uname | Linux 973f0d43552c 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 4c0c45ca1f1a6c2722414ad63fe17db982b0dac5 |
| Default Java | Red Hat, Inc.-1.8.0_302-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3484/1/testReport/ |
| Max. process+thread count | 1408 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs-native-client U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3484/1/console |
| versions | git=2.9.5 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 38s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 22s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  22m 35s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  18m 46s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 22s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  75m 48s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 12s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m  0s |  |  the patch passed  |
| -1 :x: |  cc  |  18m  0s | [/results-compile-cc-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3484/2/artifact/out/results-compile-cc-root.txt) |  root generated 25 new + 180 unchanged - 25 fixed = 205 total (was 205)  |
| +1 :green_heart: |  golang  |  18m  0s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  18m  0s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   2m 17s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  20m 34s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |  17m 37s | [/patch-unit-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3484/2/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt) |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |  32m 10s |  |  hadoop-hdfs-native-client in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  0s |  |  The patch does not generate ASF License warnings.  |
|  |   | 169m 19s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.crypto.TestCryptoStreamsWithOpensslSm4CtrCryptoCodec |
|   | hadoop.crypto.TestCryptoCodec |
|   | hadoop.service.launcher.TestServiceInterruptHandling |
|   | hadoop.fs.TestLocalFSCopyFromLocal |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3484/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3484 |
| Optional Tests | dupname asflicense compile cc mvnsite javac unit codespell golang |
| uname | Linux 403f4a0da2a2 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 9835ad229c1cac79fd66fd389fd690f86b89e734 |
| Default Java | Red Hat, Inc.-1.8.0_302-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3484/2/testReport/ |
| Max. process+thread count | 3158 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs-native-client U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3484/2/console |
| versions | git=2.9.5 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by GauthamBanasandra** [comment]
The test failed here is irrelevant to this PR since it's just a typo fix.

**Review by goiri — APPROVED** [review]

**Comment by goiri** [comment]
The PR didn't include the JIRA HADOOP-17931; I've reverted this.
@GauthamBanasandra can you provide a new PR?

**Comment by GauthamBanasandra** [comment]
Sure @goiri, really sorry for the trouble . Here's the new PR - https://github.com/apache/hadoop/pull/3490.

**Pull request merged**
