### PR TITLE
HADOOP-17752. Remove lock contention in REGISTRY of Configuration

### PR DESCRIPTION
**Pull request by liangxs**
JIRA: [HADOOP-17752](https://issues.apache.org/jira/browse/HADOOP-17752)

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 53s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  33m 27s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  22m 37s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |  19m 19s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  checkstyle  |   1m  3s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 30s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   1m  1s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   1m 33s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |   2m 24s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  18m 19s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 55s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  21m 55s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |  21m 55s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 12s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |  19m 12s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   1m  1s | [/results-checkstyle-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3085/1/artifact/out/results-checkstyle-hadoop-common-project_hadoop-common.txt) |  hadoop-common-project/hadoop-common: The patch generated 7 new + 249 unchanged - 3 fixed = 256 total (was 252)  |
| +1 :green_heart: |  mvnsite  |   1m 28s |  |  the patch passed  |
| -1 :x: |  javadoc  |   0m 58s | [/results-javadoc-javadoc-hadoop-common-project_hadoop-common-jdkUbuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3085/1/artifact/out/results-javadoc-javadoc-hadoop-common-project_hadoop-common-jdkUbuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04.txt) |  hadoop-common-project_hadoop-common-jdkUbuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 generated 1 new + 98 unchanged - 1 fixed = 99 total (was 99)  |
| +1 :green_heart: |  javadoc  |   1m 35s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |   2m 39s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  18m 22s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  16m 46s |  |  hadoop-common in the patch passed.  |
| -1 :x: |  asflicense  |   0m 49s | [/results-asflicense.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3085/1/artifact/out/results-asflicense.txt) |  The patch generated 2 ASF License warnings.  |
|  |   | 187m 30s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3085/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3085 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux b0a8788e3d80 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 2715828674e865a2e8875f7945d2ff33e81b50eb |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3085/1/testReport/ |
| Max. process+thread count | 2400 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3085/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
I was worried about a simple move to ConcurrentHashMap keeping references around, but this looks like it's addressing this. It is however, going to need review by people who can follow this problem better. I'll ask on common-dev

**Comment by liangxs** [comment]
@steveloughran Thanks for you comment.

The only problem may occur as follows

0. REGISTRY contains two configurations: `conf_b` and `conf_c`

1. Thread t1 is reloading all Configurations of REGISTRY, the state and the map iterator order are
    [`conf_b`(reloaded💚) **->** `conf_c`(_reloading_)]

2. Meanwhile, another thread t2 creates `conf_a` and then creates `conf_d`, which are both put into REGISTRY.

3. Thread t1 continues and completes reload operation.

3. Now the state may be 
    [`conf_a`(**not_reload**⚠️) **->** `conf_b`(reloaded💚) **->**`conf_c`(reloaded💚) **->** `conf_d`(reloaded💚)]

For thread t2, `conf_a` is happen-before `conf_d`, but `conf_a` is not reloaded and `conf_d` is reloaded.


I think this is ok, because configurations are not very frequently reloaded.

If this is a concern, I can add a ReentrantReadWriteLock to prevent it.
The reload operation can be guard by WriteLock, because configurations are not very frequently reloaded.
The put operations can be guard by ReadLock, which gain performance from parallel.

**Comment by liangxs** [comment]
>  ...
> I think this is ok, because configurations are not very frequently reloaded.
> 

For newly created conf, `Configuration#properties` is null, which will trigger reload operation when access. So I think it is
 not a problem.

**Comment by steveloughran** [comment]
> configurations are not very frequently reloaded.

generally only when a new shared resource (mapred-default.xml + mapred-site.xml) etc are added. This is can be a PITA in its own way, as it can overwrite changed stuff, at least in my test runs. (HADOOP-16626)

**Pull request closed without merging**
