### PR TITLE
Branch 2.5.0

### PR DESCRIPTION
**Pull request by s-bolz**
extended distcp to create a file containing all files that would be / have been deleted from the target using the -delete flag

### CODE REVIEW

**Comment by oza** [comment]
@s-bolz thank you for your contribution. Please use Hadoop's JIRA to contribute Hadoop project.

https://issues.apache.org/jira/browse/HADOOP
http://wiki.apache.org/hadoop/HowToContribute

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by aajisaka** [comment]
GitHub PR is now accepted, but you need to create an issue in ASF jira first and create a pull request for trunk instead of branch-2.5.0.
https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

**Comment by aajisaka** [comment]
branch-2.5.0 is EoL. closing.

**Pull request closed without merging**
