### PR TITLE
HADOOP-16085: S3Guard versioning: get ITestS3ARemoteFileChanged to work consistently

### PR DESCRIPTION
**Pull request by steveloughran**
HADOOP-16085: S3Guard versioning: get ITestS3ARemoteFileChanged to work consistently

this is #794 with 1+ extra patch on to be merged in

* clear auth mode flag from FS config, so there is a metastore check before rename(file), ensuring that the values passed to the mock are consistent everywhere
* change error in ChangeDetectionPolicy to make clear when an error is coming on the client for a getObjectMetadata call even when the copy policy is "server"
* and fix up ITestS3ARemoteFileChanged to use the constant string defined in ChangeDetectionPolicy precisely to stop tests being brittle against changes in the text.
* new tests in ITestS3ARemoteFileChanged to not lose stack traces when examining causes/inner causes of exceptions, just to throw new assertions with nested causes.
* deleted a couple of unused imports
* moved from two spaces after a "." to one. Sorry.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 25 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 21 | Maven dependency ordering for branch |
| +1 | mvninstall | 1079 | trunk passed |
| +1 | compile | 1086 | trunk passed |
| +1 | checkstyle | 138 | trunk passed |
| +1 | mvnsite | 129 | trunk passed |
| +1 | shadedclient | 1027 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 97 | trunk passed |
| 0 | spotbugs | 68 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 197 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 21 | Maven dependency ordering for patch |
| +1 | mvninstall | 90 | the patch passed |
| +1 | compile | 1210 | the patch passed |
| +1 | javac | 1210 | the patch passed |
| -0 | checkstyle | 141 | root: The patch generated 37 new + 70 unchanged - 4 fixed = 107 total (was 74) |
| +1 | mvnsite | 125 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 3 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 708 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 94 | the patch passed |
| +1 | findbugs | 207 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 579 | hadoop-common in the patch passed. |
| +1 | unit | 302 | hadoop-aws in the patch passed. |
| +1 | asflicense | 61 | The patch does not generate ASF License warnings. |
| | | 7379 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-824/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/824 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml findbugs checkstyle |
| uname | Linux eb106d1c9d2e 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / de01422 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-824/1/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-824/1/testReport/ |
| Max. process+thread count | 1346 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-824/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
tested: s3 london, versioned store, s3guard auth mode.

Also tested versioning tests against us-west + unguarded; outcome there was those tests which require versioning were skipped (i.e. probes for versioning work)

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 53 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 2 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 25 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 63 | Maven dependency ordering for branch |
| +1 | mvninstall | 1027 | trunk passed |
| +1 | compile | 1073 | trunk passed |
| +1 | checkstyle | 138 | trunk passed |
| +1 | mvnsite | 132 | trunk passed |
| +1 | shadedclient | 991 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 106 | trunk passed |
| 0 | spotbugs | 67 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 188 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for patch |
| +1 | mvninstall | 81 | the patch passed |
| +1 | compile | 992 | the patch passed |
| +1 | javac | 992 | the patch passed |
| -0 | checkstyle | 135 | root: The patch generated 21 new + 70 unchanged - 4 fixed = 91 total (was 74) |
| +1 | mvnsite | 110 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 3 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 614 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 83 | the patch passed |
| +1 | findbugs | 197 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 507 | hadoop-common in the patch passed. |
| +1 | unit | 285 | hadoop-aws in the patch passed. |
| +1 | asflicense | 39 | The patch does not generate ASF License warnings. |
| | | 6840 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-824/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/824 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml findbugs checkstyle |
| uname | Linux 7c3e9714ab5b 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c183bd8 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-824/3/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-824/3/testReport/ |
| Max. process+thread count | 1573 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-824/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 25 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 61 | Maven dependency ordering for branch |
| +1 | mvninstall | 1124 | trunk passed |
| +1 | compile | 1178 | trunk passed |
| +1 | checkstyle | 135 | trunk passed |
| +1 | mvnsite | 126 | trunk passed |
| +1 | shadedclient | 1030 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 128 | trunk passed |
| 0 | spotbugs | 79 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 223 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 24 | Maven dependency ordering for patch |
| +1 | mvninstall | 96 | the patch passed |
| +1 | compile | 1609 | the patch passed |
| +1 | javac | 1609 | the patch passed |
| -0 | checkstyle | 158 | root: The patch generated 37 new + 70 unchanged - 4 fixed = 107 total (was 74) |
| +1 | mvnsite | 135 | the patch passed |
| +1 | whitespace | 1 | The patch has no whitespace issues. |
| +1 | xml | 3 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 799 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 108 | the patch passed |
| +1 | findbugs | 234 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 633 | hadoop-common in the patch passed. |
| +1 | unit | 297 | hadoop-aws in the patch passed. |
| +1 | asflicense | 57 | The patch does not generate ASF License warnings. |
| | | 8240 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-824/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/824 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml findbugs checkstyle |
| uname | Linux b3dbd74efbba 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c183bd8 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-824/2/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-824/2/testReport/ |
| Max. process+thread count | 1346 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-824/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
merged into #794

**Pull request closed without merging**
