### PR TITLE
HADOOP-13868. [s3a] New default for S3A multi-part configuration

### PR DESCRIPTION
**Pull request by mackrorysd**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 65 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for branch |
| +1 | mvninstall | 1162 | trunk passed |
| +1 | compile | 1033 | trunk passed |
| +1 | checkstyle | 154 | trunk passed |
| +1 | mvnsite | 128 | trunk passed |
| +1 | shadedclient | 1091 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 105 | trunk passed |
| 0 | spotbugs | 81 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 223 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 26 | Maven dependency ordering for patch |
| +1 | mvninstall | 97 | the patch passed |
| +1 | compile | 1059 | the patch passed |
| +1 | javac | 1059 | the patch passed |
| +1 | checkstyle | 191 | the patch passed |
| +1 | mvnsite | 132 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 737 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 96 | the patch passed |
| +1 | findbugs | 214 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 546 | hadoop-common in the patch failed. |
| +1 | unit | 310 | hadoop-aws in the patch passed. |
| +1 | asflicense | 54 | The patch does not generate ASF License warnings. |
| | | 7454 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.security.TestFixKerberosTicketOrder |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1125/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1125 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml findbugs checkstyle |
| uname | Linux eb09206b2aa1 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / d545f9c |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1125/1/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1125/1/testReport/ |
| Max. process+thread count | 1345 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1125/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by mackrorysd** [comment]
Common unit test failure is unrelated - not even changing common or anything it depends on. Not including other tests because this is a performance tuning. See JIRA for numbers from performance testing. Identical patch was +1'd on JIRA - will merge in 12 hours if I don't hear otherwise.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 37 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 1 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 66 | Maven dependency ordering for branch |
| +1 | mvninstall | 1052 | trunk passed |
| +1 | compile | 1098 | trunk passed |
| +1 | checkstyle | 143 | trunk passed |
| +1 | mvnsite | 119 | trunk passed |
| +1 | shadedclient | 976 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 92 | trunk passed |
| 0 | spotbugs | 74 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 199 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 25 | Maven dependency ordering for patch |
| +1 | mvninstall | 84 | the patch passed |
| +1 | compile | 1082 | the patch passed |
| +1 | javac | 1082 | the patch passed |
| +1 | checkstyle | 147 | the patch passed |
| +1 | mvnsite | 125 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 653 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 92 | the patch passed |
| +1 | findbugs | 205 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 575 | hadoop-common in the patch passed. |
| +1 | unit | 290 | hadoop-aws in the patch passed. |
| +1 | asflicense | 41 | The patch does not generate ASF License warnings. |
| | | 7093 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1125/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1125 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml findbugs checkstyle |
| uname | Linux 48f6bd105893 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 4e66cb9 |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1125/2/testReport/ |
| Max. process+thread count | 1447 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1125/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
+1; makes sense to backport to earlier versions too

**Pull request merged**
