### PR TITLE
HADOOP-19069. Use hadoop-thirdparty 1.2.0. (#6533)

### PR DESCRIPTION
**Pull request by steveloughran**
PR #6533 applied to branch-3.3

Contributed by Shilun Fan

Reviewed-by: He Xiaoqiao <hexiaoqiao@apache.org>

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  10m 49s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 57s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  35m 29s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m 32s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   3m 20s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   2m 17s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  | 108m 33s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 42s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 58s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 51s |  |  the patch passed  |
| -1 :x: |  javac  |  17m 51s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6541/1/artifact/out/results-compile-javac-root.txt) |  root generated 103 new + 1435 unchanged - 367 fixed = 1538 total (was 1802)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   3m 14s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 11s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  41m 27s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 34s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |  18m  0s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 13s |  |  hadoop-yarn-api in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 57s |  |  The patch does not generate ASF License warnings.  |
|  |   | 206m 38s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6541/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6541 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint |
| uname | Linux a9b9771922ab 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 4fedde537116201808e99bdf99a64a42cc26e434 |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~18.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6541/1/testReport/ |
| Max. process+thread count | 1335 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6541/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
There are lot of deprecation warnings here; mostly about PARSER
```
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DataTransferProtos.java:1300:90:[deprecation] PARSER in CipherOptionProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DataTransferProtos.java:9531:90:[deprecation] PARSER in DatanodeInfoProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DataTransferProtos.java:11986:90:[deprecation] PARSER in DatanodeInfoProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DataTransferProtos.java:16419:82:[deprecation] PARSER in TokenProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ClientNamenodeProtocolProtos.java:13582:96:[deprecation] PARSER in BlockStoragePolicyProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ClientNamenodeProtocolProtos.java:19109:90:[deprecation] PARSER in DatanodeInfoProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ClientNamenodeProtocolProtos.java:21826:90:[deprecation] PARSER in DatanodeInfoProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ClientNamenodeProtocolProtos.java:21839:90:[deprecation] PARSER in DatanodeInfoProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ClientNamenodeProtocolProtos.java:25642:90:[deprecation] PARSER in LocatedBlockProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ClientNamenodeProtocolProtos.java:37401:101:[deprecation] PARSER in BatchedDirectoryListingProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ClientNamenodeProtocolProtos.java:50305:90:[deprecation] PARSER in DatanodeInfoProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ClientNamenodeProtocolProtos.java:51727:91:[deprecation] PARSER in StorageReportProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ClientNamenodeProtocolProtos.java:56123:90:[deprecation] PARSER in DatanodeInfoProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ClientNamenodeProtocolProtos.java:100318:88:[deprecation] PARSER in DatanodeIDProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/HdfsProtos.java:21236:82:[deprecation] PARSER in TokenProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ErasureCodingProtos.java:2062:97:[deprecation] PARSER in ErasureCodingPolicyProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ErasureCodingProtos.java:5328:97:[deprecation] PARSER in ErasureCodingPolicyProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/ErasureCodingProtos.java:6124:108:[deprecation] PARSER in AddErasureCodingPolicyResponseProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs-client/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/InotifyProtos.java:8418:84:[deprecation] PARSER in XAttrProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/target/generated-sources/java/org/apache/hadoop/hdfs/server/namenode/FsImageProto.java:22849:85:[deprecation] PARSER in BlockProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/target/generated-sources/java/org/apache/hadoop/hdfs/server/namenode/FsImageProto.java:30265:97:[deprecation] PARSER in ErasureCodingPolicyProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/EditLogProtos.java:1566:84:[deprecation] PARSER in XAttrProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DatanodeProtocolProtos.java:5686:83:[deprecation] PARSER in BlockProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DatanodeProtocolProtos.java:5699:91:[deprecation] PARSER in DatanodeInfosProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DatanodeProtocolProtos.java:5712:90:[deprecation] PARSER in StorageUuidsProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DatanodeProtocolProtos.java:5725:90:[deprecation] PARSER in StorageTypesProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DatanodeProtocolProtos.java:8381:99:[deprecation] PARSER in RecoveringBlockProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DatanodeProtocolProtos.java:10886:112:[deprecation] PARSER in BlockECReconstructionInfoProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DatanodeProtocolProtos.java:14747:91:[deprecation] PARSER in StorageReportProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DatanodeProtocolProtos.java:29696:90:[deprecation] PARSER in LocatedBlockProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/target/generated-sources/java/org/apache/hadoop/hdfs/protocol/proto/DatanodeProtocolProtos.java:31378:88:[deprecation] PARSER in DatanodeIDProto has been deprecated
hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/tools/offlineImageViewer/OfflineImageReconstructor.java:494:22:[deprecation] printToString(MessageOrBuilder) in TextFormat has been deprecated
hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/tools/offlineImageViewer/OfflineImageReconstructor.java:1728:22:[deprecation] printToString(MessageOrBuilder) in TextFormat has been deprecated
hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/tools/offlineImageViewer/OfflineImageReconstructor.java:1742:22:[deprecation] printToString(MessageOrBuilder) in TextFormat has been deprecated
hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/tools/offlineImageViewer/OfflineImageReconstructor.java:1808:20:[deprecation] printToString(MessageOrBuilder) in TextFormat has been deprecated
```

But 367 have fixed.

All the deprecations are in generated source, so not something we can do anything about. Only the `OfflineImageReconstructor` warnings are in our own source

**Comment by steveloughran** [comment]
Merging this; all the warnings are just warnings of a future -in generated code, pretty meaningless

**Comment by steveloughran** [comment]
reviewing tests, only hadoop-common tests were executed, no failures.

going to +1 this.

**Pull request merged**
