### PR TITLE
HADOOP-16768: DO NOT MERGE Test x86 and arm fail tests

### PR DESCRIPTION
**Pull request by bzhaoopenstack**
## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 23s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 4 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   1m  8s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  20m 52s |  trunk passed  |
| +1 :green_heart: |  compile  |  18m 18s |  trunk passed  |
| +1 :green_heart: |  checkstyle  |   2m 51s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 54s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  19m 39s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 51s |  trunk passed  |
| +0 :ok: |  spotbugs  |   0m 44s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 51s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 21s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 10s |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 29s |  the patch passed  |
| +1 :green_heart: |  javac  |  17m 29s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m 52s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 53s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  14m  2s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 52s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   3m  5s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   9m 30s |  hadoop-common in the patch passed.  |
| -1 :x: |  unit  |  21m 58s |  hadoop-yarn-applications-distributedshell in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 47s |  The patch does not generate ASF License warnings.  |
|  |   | 145m 45s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.yarn.applications.distributedshell.TestDistributedShell |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1767/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1767 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 1c3fa7ea84e7 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 2408066 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1767/1/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-applications_hadoop-yarn-applications-distributedshell.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1767/1/testReport/ |
| Max. process+thread count | 1716 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1767/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  34m 25s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 5 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   1m  6s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  23m 45s |  trunk passed  |
| +1 :green_heart: |  compile  |  21m  9s |  trunk passed  |
| +1 :green_heart: |  checkstyle  |   3m  4s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 37s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  21m 13s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 22s |  trunk passed  |
| +0 :ok: |  spotbugs  |   1m  5s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m 57s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 22s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 40s |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 14s |  the patch passed  |
| +1 :green_heart: |  javac  |  19m 14s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m 52s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m 33s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  13m 46s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 22s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   4m 12s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   9m 29s |  hadoop-common in the patch passed.  |
| -1 :x: |  unit  |  21m 59s |  hadoop-yarn-applications-distributedshell in the patch failed.  |
| +1 :green_heart: |  unit  |   0m 45s |  hadoop-yarn-csi in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 45s |  The patch does not generate ASF License warnings.  |
|  |   | 192m 55s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.yarn.applications.distributedshell.TestDistributedShell |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1767/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1767 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 007ca9291fa0 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 92c8962 |
| Default Java | 1.8.0_232 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1767/2/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-applications_hadoop-yarn-applications-distributedshell.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1767/2/testReport/ |
| Max. process+thread count | 1731 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell hadoop-yarn-project/hadoop-yarn/hadoop-yarn-csi U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1767/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 32s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 7 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 28s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  21m 47s |  trunk passed  |
| +1 :green_heart: |  compile  |  22m 18s |  trunk passed  |
| +1 :green_heart: |  checkstyle  |   3m  0s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 38s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  20m 49s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 19s |  trunk passed  |
| +0 :ok: |  spotbugs  |   1m  6s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   4m  3s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 50s |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 40s |  the patch passed  |
| +1 :green_heart: |  javac  |  19m 40s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m 50s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m 33s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  13m 47s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 21s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   4m 13s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   9m 27s |  hadoop-common in the patch passed.  |
| -1 :x: |  unit  |  22m 23s |  hadoop-yarn-applications-distributedshell in the patch failed.  |
| +1 :green_heart: |  unit  |   0m 43s |  hadoop-yarn-csi in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 48s |  The patch does not generate ASF License warnings.  |
|  |   | 159m  9s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.yarn.applications.distributedshell.TestDistributedShell |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1767/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1767 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 2b1950dda83d 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 7b93575 |
| Default Java | 1.8.0_232 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1767/3/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-applications_hadoop-yarn-applications-distributedshell.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1767/3/testReport/ |
| Max. process+thread count | 1606 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell hadoop-yarn-project/hadoop-yarn/hadoop-yarn-csi U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1767/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
This issue has been fixed by #2003. Closing.

**Pull request closed without merging**
