### PR TITLE
HADOOP-13386. Upgrade Avro to 1.9.2 (#3990)

### PR DESCRIPTION
**Pull request by steveloughran**
#3990 on branch-3.3

### CODE REVIEW

**Comment by xkrogen** [comment]
Can you please clarify: the PR description says `branch-3` (indicating this would be targeted for the next 3.X minor release) but the PR seems to be filed against `branch-3.3` (indicating this would be targeted for the next 3.3.X maintenance release).

I assume you were intending the latter (3.3.X maintenance release). If so, I'm -1 on this for the reasons outlined in [this comment](https://github.com/apache/hadoop/pull/4580#issuecomment-1187715602) on #4580.

**Comment by steveloughran** [comment]
i want to see how well this goes into 3.3; if it can't, it can't. but we do need a story here.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 34s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 20s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  23m 44s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m  1s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m 18s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  20m 25s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   7m 13s |  |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   0m 35s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  55m 46s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 37s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  27m  5s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 35s |  |  the patch passed  |
| -1 :x: |  javac  |  17m 35s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4579/1/artifact/out/results-compile-javac-root.txt) |  root generated 3 new + 1864 unchanged - 4 fixed = 1867 total (was 1868)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   3m 11s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  20m  1s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   7m 10s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 34s |  |  hadoop-project has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  58m 50s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 684m 58s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4579/1/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m 47s |  |  The patch does not generate ASF License warnings.  |
|  |   | 994m  0s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |
|   | hadoop.hdfs.server.federation.router.TestRouterRpcMultiDestination |
|   | hadoop.hdfs.server.federation.router.TestRouterRpc |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4579/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4579 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets xmllint shellcheck shelldocs |
| uname | Linux 82581586ec18 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 074b83748641b424fbff1953d9c105f3c0c5666b |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4579/1/testReport/ |
| Max. process+thread count | 3447 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests hadoop-mapreduce-project . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4579/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
closing as too traumatic

**Pull request closed without merging**
