### PR TITLE
HADOOP-17354. Move Jenkinsfile outside of the root directory.

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/HADOOP-17354

The Jenkinsfile is placed under the project root directory, so when the Jenkinsfile is changed, all the Hadoop unit tests will run and it wastes a lot of time and resources. Let's move the file outside of the root directory.

If approved, I'll commit this to all the active branches and update the config of hadoop-multibranch job to specify the new location of the Jenkinsfile.

### CODE REVIEW

**Review by ayushtkn — COMMENTED** [review]
Makes sense, but not sure why the Jenkins job didn't run for this PR?

**Comment by aajisaka** [comment]
The hadoop-multibranch job first searches `./Jenkinsfile` but failed to find it because it is moved to `./dev-support/Jenkinsfile`. That way the job didn't run.

**Review by ayushtkn — APPROVED** [review]
Thanx @aajisaka for confirming. I guess that we can change, Do give a check once you merge this.

**Comment by aajisaka** [comment]
Thank you @ayushtkn

**Pull request merged**
