### PR TITLE
MAPREDUCE-7377. Remove unused imports in MapReduce project

### PR DESCRIPTION
**Pull request by hotcodemacha**
### Description of PR
Remove unused Imports in Hadoop MAP/REDUCE project
* JIRA: MAPREDUCE-7377

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?

### CODE REVIEW

**Comment by slfan1989** [comment]
Hi，@[ashutoshcipher](https://github.com/ashutoshcipher), I found unused import in yarn router moudle and yarn server moudle,
[PR-4276](https://github.com/apache/hadoop/pull/4276) has been submitted, please do not submit again, Thanks for contributing to the code.

**Comment by hotcodemacha** [comment]
@slfan1989. Thanks for your comment. My PR is different from yours. I am checking in complete Hadoop MAP/REDUCE project and not in `yarn router module and yarn server module` in this PR. 

Also I have created a separate JIRA YARN-11142 to check unused imports in complete Hadoop YARN project. When I will raise the PR, I will make sure that I am adding the new changes and not that are already done in you PR https://github.com/apache/hadoop/pull/4276

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 56s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 21 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  16m 30s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  28m 49s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   3m  4s |  |  trunk passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  compile  |   2m 35s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  checkstyle  |   1m 23s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   5m 10s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   4m 26s |  |  trunk passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |   4m  4s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  spotbugs  |   7m 41s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  22m 47s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 23s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m 36s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 48s |  |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| -1 :x: |  javac  |   2m 48s | [/results-compile-javac-hadoop-mapreduce-project-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4299/1/artifact/out/results-compile-javac-hadoop-mapreduce-project-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt) |  hadoop-mapreduce-project-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 generated 2 new + 288 unchanged - 2 fixed = 290 total (was 290)  |
| +1 :green_heart: |  compile  |   2m 21s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| -1 :x: |  javac  |   2m 21s | [/results-compile-javac-hadoop-mapreduce-project-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4299/1/artifact/out/results-compile-javac-hadoop-mapreduce-project-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt) |  hadoop-mapreduce-project-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 generated 2 new + 274 unchanged - 2 fixed = 276 total (was 276)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m  6s |  |  hadoop-mapreduce-project: The patch generated 0 new + 711 unchanged - 132 fixed = 711 total (was 843)  |
| +1 :green_heart: |  mvnsite  |   3m 50s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   3m  2s |  |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |   2m 50s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  spotbugs  |   7m 31s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  22m 33s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   6m 23s |  |  hadoop-mapreduce-client-core in the patch passed.  |
| -1 :x: |  unit  |   1m  5s | [/patch-unit-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4299/1/artifact/out/patch-unit-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-common.txt) |  hadoop-mapreduce-client-common in the patch passed.  |
| +1 :green_heart: |  unit  |   8m 30s |  |  hadoop-mapreduce-client-app in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 22s |  |  hadoop-mapreduce-client-hs in the patch passed.  |
| +1 :green_heart: |  unit  | 133m 32s |  |  hadoop-mapreduce-client-jobclient in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 57s |  |  hadoop-mapreduce-client-nativetask in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 57s |  |  hadoop-mapreduce-examples in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 48s |  |  The patch does not generate ASF License warnings.  |
|  |   | 310m 12s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.mapred.TestLocalDistributedCacheManager |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4299/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4299 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 9173bc9c3606 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 3560f6b144ec30493bdccb8077a1718d6e1f2159 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4299/1/testReport/ |
| Max. process+thread count | 1198 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-common hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-hs hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-nativetask hadoop-mapreduce-project/hadoop-mapreduce-examples U: hadoop-mapreduce-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4299/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hotcodemacha** [comment]
@aajisaka @ayushtkn @steveloughran , Can you please review this? Thanks.

**Review by aajisaka — APPROVED** [review]
LGTM

**Comment by aajisaka** [comment]
> hadoop-mapreduce-project: The patch generated 0 new + 711 unchanged - 132 fixed = 711 total (was 843)

The number of Checkstyle warnings are greatly reduced. Thank you.

**Comment by aajisaka** [comment]
TestLocalDistributedCacheManager is failing but is not related to the patch. Filed MAPREDUCE-7380 to fix the test failure.

**Pull request merged**
