### PR TITLE
HDFS-15719. [Hadoop 3] Both NameNodes can crash simultaneously due to the short JN socket timeout	

### PR DESCRIPTION
**Pull request by jojochuang**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  26m 20s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 43s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  20m 48s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  20m  2s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  compile  |  17m 16s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  checkstyle  |   2m 41s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m  8s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  23m 13s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 36s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   2m  6s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +0 :ok: |  spotbugs  |   2m 35s |  |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   0m 33s |  |  branch/hadoop-project no findbugs output file (findbugsXml.xml)  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 59s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 12s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  22m 58s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javac  |  22m 58s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  20m  6s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  javac  |  20m  6s |  |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   3m 30s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m 17s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| -1 :x: |  shadedclient  |  20m 17s |  |  patch has errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 37s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   2m 10s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +0 :ok: |  findbugs  |   0m 31s |  |  hadoop-project has no data from findbugs  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 28s |  |  hadoop-project in the patch passed.  |
| -1 :x: |  unit  |  10m 43s | [/patch-unit-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2533/1/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt) |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 56s |  |  The patch does not generate ASF License warnings.  |
|  |   | 224m  2s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.metrics2.source.TestJvmMetrics |
|   | hadoop.ha.TestZKFailoverController |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2533/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2533 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml |
| uname | Linux 3e550b4a690c 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / aaf9e3d320a |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2533/1/testReport/ |
| Max. process+thread count | 1601 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2533/1/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.0.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by ayushtkn** [comment]
Thanx @jojochuang for the work here.
The PR seems to include two Jira's, I think the timeout stuff is sufficient alone, If so, Can you update the PR

**Comment by sodonnel** [comment]
Changing this idle timeout seems like a good idea to me. As @ayushtkn mentioned, I think you have accidentally included "Bump Jetty Version" too in this PR.

Do we also need to update the various *-site.xml files? I see this parameter mentioned here, and always as 1 second:

```
$ grep -R -A1 "hadoop.http.idle_timeout.ms" *
hadoop-common-project/hadoop-common/src/main/resources/core-default.xml:    <name>hadoop.http.idle_timeout.ms</name>
hadoop-common-project/hadoop-common/src/main/resources/core-default.xml-    <value>1000</value>
--
hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/http/HttpServer2.java:      "hadoop.http.idle_timeout.ms";
hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/http/HttpServer2.java-  public static final int HTTP_IDLE_TIMEOUT_MS_DEFAULT = 10000;
--
hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeysPublic.java:      "hadoop.http.idle_timeout.ms";
hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeysPublic.java-  public static final int HADOOP_HTTP_IDLE_TIMEOUT_MS_DEFAULT = 1000;
--
hadoop-common-project/hadoop-kms/src/main/resources/kms-default.xml:    <name>hadoop.http.idle_timeout.ms</name>
hadoop-common-project/hadoop-kms/src/main/resources/kms-default.xml-    <value>1000</value>
--
hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/resources/httpfs-default.xml:    <name>hadoop.http.idle_timeout.ms</name>
hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/resources/httpfs-default.xml-    <value>1000</value>
```

Note it is also mentioned on CommonConfigurationKeysPublic.java and HttpServer2.java as well as the *-site.xml file. Its a bit confusing for it to be mentioned in so many places.

Should HttpServer2 reference the constant and default in CommonConfigurationKeysPublic instead?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 36s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 49s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  21m 14s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  19m 59s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  compile  |  17m 18s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  checkstyle  |   2m 46s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   3m 44s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  22m 24s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 59s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   3m 28s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +0 :ok: |  spotbugs  |   0m 59s |  |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   0m 38s |  |  branch/hadoop-project no findbugs output file (findbugsXml.xml)  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 55s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 11s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javac  |  19m 11s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 18s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  javac  |  17m 18s |  |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m 39s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   3m 40s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  6s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  15m 28s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 59s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   3m 29s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +0 :ok: |  findbugs  |   0m 35s |  |  hadoop-project has no data from findbugs  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 35s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |   9m 35s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 41s |  |  hadoop-kms in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 40s |  |  hadoop-hdfs-httpfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 55s |  |  The patch does not generate ASF License warnings.  |
|  |   | 204m 59s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2533/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2533 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml |
| uname | Linux e91ad82fb7b3 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 4c033bafa02 |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2533/2/testReport/ |
| Max. process+thread count | 1600 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common hadoop-common-project/hadoop-kms hadoop-hdfs-project/hadoop-hdfs-httpfs U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2533/2/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.0.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by sodonnel** [comment]
This change LGTM +1

**Comment by jojochuang** [comment]
Thanks Ayush and Stephen!

**Pull request merged**
