### PR TITLE
HADOOP-17615. ADLS Gen1: Update adls SDK to 2.3.9

### PR DESCRIPTION
**Pull request by bilaharith**
Test results are observed to be the same before and after the change.

[ERROR] Errors: 
[ERROR]   TestAdlContractGetFileStatusLive>AbstractContractGetFileStatusTest.testComplexDirActions:153->AbstractContractGetFileStatusTest.checkListStatusIteratorComplexDir:196 » NoClassDefFound
[ERROR]   TestAdlContractGetFileStatusLive>AbstractContractGetFileStatusTest.testListStatusIteratorFile:363->AbstractContractGetFileStatusTest.validateListingForFile:384 » NoClassDefFound
[ERROR]   TestAdlContractRootDirLive>AbstractContractRootDirectoryTest.testSimpleRootListing:251 » NoClassDefFound
[INFO] 
[ERROR] Tests run: 886, Failures: 0, Errors: 3, Skipped: 3

### CODE REVIEW

**Review by vinaysbadami — APPROVED** [review]

**Review by snvijaya — APPROVED** [review]
+1

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  26m 22s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  33m  0s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |   0m 24s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   0m 28s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   0m 25s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  49m 36s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 26s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 18s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 18s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 20s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 17s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  16m 16s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 54s |  |  hadoop-azure-datalake in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 33s |  |  The patch does not generate ASF License warnings.  |
|  |   |  96m 37s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2842/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2842 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml |
| uname | Linux b12850835bc6 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 301f71feb96edc53efcaddaca9a6f4e82eddfe0a |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~18.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2842/1/testReport/ |
| Max. process+thread count | 581 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-azure-datalake U: hadoop-tools/hadoop-azure-datalake |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2842/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by vinaysbadami — APPROVED** [review]

**Comment by steveloughran** [comment]
what's causing the test failures?

**Comment by bilaharith** [comment]
image

The testcases are from the hadoop-common module. The asserj dependency is present in the hadoop-common pom.
I tried adding the dependency into hadoop-azure-datalake pom but that didn't help.

**Comment by surendralilhore** [comment]
Triggered build again

**Comment by steveloughran** [comment]
> Triggered build again

how did you do that? I normally do a rebase.

I'd like to get this in to the 3.3.1 release so we should try to get this wrapped up asap

**Comment by surendralilhore** [comment]
> how did you do that? I normally do a rebase.

I trigger the old PR build some time it works, but here it is failing, Will ask @bilaharith  to rebase.

**Comment by steveloughran** [comment]
OK, let's declare those CNFEs as unrelated, caused by #2354 by the look of things. (i.e. by one @steveloughran )

+1, merging, creating a followup jira for the test failures.

**Comment by surendralilhore** [comment]
Thanks @steveloughran

**Pull request merged**
