### PR TITLE
HDDS-1613. Opening of rocksDB in datanode fails with No locks available. Contributed by Mukul Kumar Singh.

### PR DESCRIPTION
**Pull request by mukul1987**
This problem occurs because in the current container cache, if an eviction is being requested on an entry with a reference, the entry is removed from the map while reference is still held onto the rocksdb. This reference also has acquired the lock as well.

When another consumer tries to fetch the rockdb from the cache, it does not find the entry and now tries to acquire the lock, this step will fail as the other reference is holding the lock.

Tested this on MiniOzoneChaosCluster after the fix.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 26 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 515 | trunk passed |
| +1 | compile | 282 | trunk passed |
| +1 | checkstyle | 78 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 973 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 158 | trunk passed |
| 0 | spotbugs | 332 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 547 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 496 | the patch passed |
| +1 | compile | 293 | the patch passed |
| +1 | javac | 293 | the patch passed |
| +1 | checkstyle | 85 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 731 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 161 | the patch passed |
| +1 | findbugs | 745 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 169 | hadoop-hdds in the patch failed. |
| -1 | unit | 1240 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 84 | The patch does not generate ASF License warnings. |
| | | 6741 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.container.ozoneimpl.TestOzoneContainer |
|   | hadoop.hdds.scm.pipeline.TestSCMPipelineManager |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-876/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/876 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux f963c23aace1 4.4.0-139-generic #165~14.04.1-Ubuntu SMP Wed Oct 31 10:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / f1552f6 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-876/1/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-876/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-876/1/testReport/ |
| Max. process+thread count | 4854 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/container-service U: hadoop-hdds/container-service |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-876/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by bshashikant** [comment]
The changes look good to me. There is a test failure reported related to this change. Can you please check?

**Comment by mukul1987** [comment]
Thanks for the review @bshashikant, TestBCSID is passing locally.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 24 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 506 | trunk passed |
| +1 | compile | 266 | trunk passed |
| +1 | checkstyle | 76 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 926 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 148 | trunk passed |
| 0 | spotbugs | 320 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 532 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 476 | the patch passed |
| +1 | compile | 301 | the patch passed |
| +1 | javac | 301 | the patch passed |
| -0 | checkstyle | 37 | hadoop-hdds: The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0) |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 805 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 160 | the patch passed |
| +1 | findbugs | 542 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 238 | hadoop-hdds in the patch passed. |
| -1 | unit | 1181 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 49 | The patch does not generate ASF License warnings. |
| | | 6484 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-876/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/876 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 39599861d086 4.4.0-139-generic #165~14.04.1-Ubuntu SMP Wed Oct 31 10:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e49162f |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-876/2/artifact/out/diff-checkstyle-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-876/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-876/2/testReport/ |
| Max. process+thread count | 5138 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/container-service U: hadoop-hdds/container-service |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-876/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by bshashikant** [comment]
Thanks @mukul1987 for updating the patch. There is a checkstyle issue which can be addressed while committing. I am +1 on this change.

**Comment by nandakumar131** [comment]
I will fix the checkstyle issue while committing.

**Pull request closed without merging**
