### PR TITLE
HDDS-1910. Cannot build hadoop-hdds-config from scratch in IDEA

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

`ConfigFileGenerator` is both defined (`.java` source) and configured to be used (by reference in `META-INF`) in `hadoop-hdds-config` module's `main` source.  Maven build is configured to work around this by explicit `-proc:none` compiler arg, applied only to `main` compilation, but not to `test` compilation.  Since the annotation processor is only used in tests in this module, this works fine.

It seems IDEA does not respect this compiler configuration (and cannot even be configured differently for `main` and `test` compilation).

This change configures the processor for use in `config/test` and `common/main`.  Thus dependent modules still inherit it for main source processing, while the `config` module can be properly compiled without the hack.

https://issues.apache.org/jira/browse/HDDS-1910

## How was this patch tested?

1. Verified that `hadoop-hdds/config` can be compiled from scratch in IDEA.  To confirm, try to run eg. `TestConfigFileAppender` unit test.
2. Verified that full Maven build still generates the same Ozone config based on existing annotations:
```
  926 hadoop-hdds/common/target/test-classes/ozone-default-generated.xml
 1060 hadoop-hdds/config/target/test-classes/ozone-default-generated.xml
 1192 hadoop-hdds/server-scm/target/classes/ozone-default-generated.xml
  504 hadoop-ozone/common/target/classes/ozone-default-generated.xml
 1194 hadoop-ozone/csi/target/classes/ozone-default-generated.xml
  504 hadoop-ozone/ozonefs-lib-current/target/classes/ozone-default-generated.xml
  504 hadoop-ozone/ozonefs-lib-legacy/target/classes/libs/ozone-default-generated.xml
  504 hadoop-ozone/ozonefs-lib-legacy/target/classes/ozone-default-generated.xml
```

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 43 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 25 | Maven dependency ordering for branch |
| +1 | mvninstall | 603 | trunk passed |
| +1 | compile | 376 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1789 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 160 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 25 | Maven dependency ordering for patch |
| +1 | mvninstall | 553 | the patch passed |
| +1 | compile | 375 | the patch passed |
| +1 | javac | 375 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 3 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 675 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 164 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 281 | hadoop-hdds in the patch passed. |
| -1 | unit | 2240 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 59 | The patch does not generate ASF License warnings. |
| | | 6581 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestMultiBlockWritesWithDnFailures |
|   | hadoop.hdds.scm.pipeline.TestRatisPipelineCreateAndDestory |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.client.rpc.TestCommitWatcher |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1268/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1268 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 01d2fedea183 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / fba222a |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1268/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1268/1/testReport/ |
| Max. process+thread count | 4867 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/config hadoop-hdds/common U: hadoop-hdds |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1268/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by avijayanhwx** [comment]
LGTM +1

**Comment by anuengineer** [comment]
Thank you for the contribution. I have committed this to the trunk.

**Pull request closed without merging**
