### PR TITLE
MAPREDUCE-7285. Junit class missing from hadoop-mapreduce-client-jobclient-*-tests jar.

### PR DESCRIPTION
**Pull request by iwasakims**

### CODE REVIEW

**Comment by iwasakims** [comment]
The fix worked on my local.
```
[centos@centos7 hadoop-3.4.0-SNAPSHOT]$ bin/hadoop jar share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-*-tests.jar sleep -mt 1 -rt 1 -m 1 -r 1
2020-07-15 11:12:13,657 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2020-07-15 11:12:14,670 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
2020-07-15 11:12:15,259 INFO mapreduce.JobResourceUploader: Disabling Erasure Coding for path: /tmp/hadoop-yarn/staging/centos/.staging/job_1594777964233_0002
2020-07-15 11:12:16,806 INFO mapreduce.JobSubmitter: number of splits:1
2020-07-15 11:12:17,456 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1594777964233_0002
2020-07-15 11:12:17,456 INFO mapreduce.JobSubmitter: Executing with tokens: []
2020-07-15 11:12:17,713 INFO conf.Configuration: resource-types.xml not found
2020-07-15 11:12:17,713 INFO resource.ResourceUtils: Unable to find 'resource-types.xml'.
2020-07-15 11:12:17,790 INFO impl.YarnClientImpl: Submitted application application_1594777964233_0002
2020-07-15 11:12:17,832 INFO mapreduce.Job: The url to track the job: http://localhost:8088/proxy/application_1594777964233_0002/
2020-07-15 11:12:17,833 INFO mapreduce.Job: Running job: job_1594777964233_0002
2020-07-15 11:12:26,114 INFO mapreduce.Job: Job job_1594777964233_0002 running in uber mode : false
2020-07-15 11:12:26,115 INFO mapreduce.Job:  map 0% reduce 0%
2020-07-15 11:12:32,220 INFO mapreduce.Job:  map 100% reduce 0%
2020-07-15 11:12:37,281 INFO mapreduce.Job:  map 100% reduce 100%
2020-07-15 11:12:38,326 INFO mapreduce.Job: Job job_1594777964233_0002 completed successfully
...
```

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  6s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  21m 31s |  trunk passed  |
| +1 :green_heart: |  compile  |   0m 33s |  trunk passed with JDK Ubuntu-11.0.7+10-post-Ubuntu-2ubuntu218.04  |
| +1 :green_heart: |  compile  |   0m 29s |  trunk passed with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09  |
| +1 :green_heart: |  checkstyle  |   0m 24s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 31s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  16m 31s |  branch has no errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 21s |  hadoop-mapreduce-client-jobclient in trunk failed with JDK Ubuntu-11.0.7+10-post-Ubuntu-2ubuntu218.04.  |
| +1 :green_heart: |  javadoc  |   0m 20s |  trunk passed with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09  |
| +0 :ok: |  spotbugs  |   0m 42s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   0m 39s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 29s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 27s |  the patch passed with JDK Ubuntu-11.0.7+10-post-Ubuntu-2ubuntu218.04  |
| +1 :green_heart: |  javac  |   0m 27s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 23s |  the patch passed with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09  |
| +1 :green_heart: |  javac  |   0m 23s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 18s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 25s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 16s |  patch has no errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 19s |  hadoop-mapreduce-client-jobclient in the patch failed with JDK Ubuntu-11.0.7+10-post-Ubuntu-2ubuntu218.04.  |
| +1 :green_heart: |  javadoc  |   0m 17s |  the patch passed with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09  |
| +1 :green_heart: |  findbugs  |   0m 45s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 125m 12s |  hadoop-mapreduce-client-jobclient in the patch passed.  |
| -1 :x: |  asflicense  |   0m 37s |  The patch generated 1 ASF License warnings.  |
|  |   | 188m 52s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.mapreduce.lib.input.TestCombineFileInputFormat |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-2139/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2139 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux d1451cfbc80a 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 317fe4584a5 |
| Default Java | Private Build-1.8.0_252-8u252-b09-1~18.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.7+10-post-Ubuntu-2ubuntu218.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_252-8u252-b09-1~18.04-b09 |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-2139/1/artifact/out/branch-javadoc-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-jobclient-jdkUbuntu-11.0.7+10-post-Ubuntu-2ubuntu218.04.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-2139/1/artifact/out/patch-javadoc-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-jobclient-jdkUbuntu-11.0.7+10-post-Ubuntu-2ubuntu218.04.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-2139/1/artifact/out/patch-unit-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-jobclient.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-2139/1/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-2139/1/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 1178 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient U: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-2139/1/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
+1, JUnit 3 dependency must be removed.

hadoop.mapreduce.lib.input.TestCombineFileInputFormat is fixed by #2136

**Comment by iwasakims** [comment]
Thanks, @aajisaka. I merged this.

**Pull request merged**
