### PR TITLE
HDDS-1478. Provide k8s resources files for prometheus and performance tests

### PR DESCRIPTION
**Pull request by elek**
Similar to HDDS-1412 we can further improve the available k8s resources with providing example resources to:

1) install prometheus
2) execute freon test and check the results.

See: https://issues.apache.org/jira/browse/HDDS-1478

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 21 | Docker mode activated. |
||| _ Prechecks _ |
| 0 | yamllint | 1 | yamllint was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 57 | Maven dependency ordering for branch |
| +1 | mvninstall | 1132 | trunk passed |
| +1 | compile | 117 | trunk passed |
| +1 | mvnsite | 90 | trunk passed |
| +1 | shadedclient | 743 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 62 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 14 | Maven dependency ordering for patch |
| -1 | mvninstall | 20 | dist in the patch failed. |
| +1 | compile | 106 | the patch passed |
| +1 | javac | 106 | the patch passed |
| +1 | hadolint | 2 | There were no new hadolint issues. |
| +1 | mvnsite | 55 | the patch passed |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 16 | The patch generated 0 new + 104 unchanged - 132 fixed = 104 total (was 236) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 815 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 56 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 39 | common in the patch passed. |
| +1 | unit | 24 | dist in the patch passed. |
| +1 | asflicense | 30 | The patch does not generate ASF License warnings. |
| | | 3591 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-783/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/783 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  xml  hadolint  shellcheck  shelldocs  yamllint  |
| uname | Linux 0e21472b3b47 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 1cef194 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-783/1/artifact/out/patch-mvninstall-hadoop-ozone_dist.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-783/1/testReport/ |
| Max. process+thread count | 340 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/common hadoop-ozone/dist U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-783/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 20 | Docker mode activated. |
||| _ Prechecks _ |
| 0 | yamllint | 1 | yamllint was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 39 | Maven dependency ordering for branch |
| +1 | mvninstall | 1182 | trunk passed |
| +1 | compile | 118 | trunk passed |
| +1 | mvnsite | 90 | trunk passed |
| +1 | shadedclient | 721 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 63 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 14 | Maven dependency ordering for patch |
| -1 | mvninstall | 22 | dist in the patch failed. |
| +1 | compile | 105 | the patch passed |
| +1 | javac | 105 | the patch passed |
| +1 | hadolint | 1 | There were no new hadolint issues. |
| +1 | mvnsite | 56 | the patch passed |
| +1 | shellcheck | 2 | There were no new shellcheck issues. |
| +1 | shelldocs | 16 | The patch generated 0 new + 104 unchanged - 132 fixed = 104 total (was 236) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 3 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 823 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 57 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 39 | common in the patch passed. |
| +1 | unit | 23 | dist in the patch passed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 3606 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-783/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/783 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  xml  hadolint  shellcheck  shelldocs  yamllint  |
| uname | Linux aabcb57ed666 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / dead9b4 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-783/2/artifact/out/patch-mvninstall-hadoop-ozone_dist.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-783/2/testReport/ |
| Max. process+thread count | 307 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/common hadoop-ozone/dist U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-783/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 22 | Docker mode activated. |
||| _ Prechecks _ |
| 0 | yamllint | 0 | yamllint was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 34 | Maven dependency ordering for branch |
| +1 | mvninstall | 1130 | trunk passed |
| +1 | compile | 117 | trunk passed |
| +1 | mvnsite | 91 | trunk passed |
| +1 | shadedclient | 739 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 64 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 14 | Maven dependency ordering for patch |
| -1 | mvninstall | 22 | dist in the patch failed. |
| +1 | compile | 114 | the patch passed |
| +1 | javac | 114 | the patch passed |
| +1 | hadolint | 2 | There were no new hadolint issues. |
| +1 | mvnsite | 57 | the patch passed |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 14 | The patch generated 0 new + 104 unchanged - 132 fixed = 104 total (was 236) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 3 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 818 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 55 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 37 | common in the patch passed. |
| +1 | unit | 25 | dist in the patch passed. |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 3561 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-783/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/783 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  xml  hadolint  shellcheck  shelldocs  yamllint  |
| uname | Linux f85d3129398c 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 4877f0a |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-783/3/artifact/out/patch-mvninstall-hadoop-ozone_dist.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-783/3/testReport/ |
| Max. process+thread count | 340 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/common hadoop-ozone/dist U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-783/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by anuengineer** [comment]
+1, thank you for getting this done. Please feel free to commit.

**Pull request closed without merging**
