### PR TITLE
HDDS-2117. ContainerStateMachine#writeStateMachineData times out.

### PR DESCRIPTION
**Pull request by bshashikant**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| -1 | mvninstall | 32 | hadoop-ozone in trunk failed. |
| -1 | compile | 21 | hadoop-ozone in trunk failed. |
| +1 | checkstyle | 67 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 821 | branch has no errors when building and testing our client artifacts. |
| -1 | javadoc | 18 | hadoop-hdds in trunk failed. |
| -1 | javadoc | 19 | hadoop-ozone in trunk failed. |
| 0 | spotbugs | 148 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| -1 | findbugs | 26 | hadoop-ozone in trunk failed. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 35 | hadoop-ozone in the patch failed. |
| -1 | compile | 24 | hadoop-ozone in the patch failed. |
| -1 | javac | 24 | hadoop-ozone in the patch failed. |
| -0 | checkstyle | 32 | hadoop-hdds: The patch generated 3 new + 208 unchanged - 0 fixed = 211 total (was 208) |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 667 | patch has no errors when building and testing our client artifacts. |
| -1 | javadoc | 16 | hadoop-hdds in the patch failed. |
| -1 | javadoc | 17 | hadoop-ozone in the patch failed. |
| -1 | findbugs | 24 | hadoop-ozone in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 131 | hadoop-hdds in the patch failed. |
| -1 | unit | 27 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 35 | The patch does not generate ASF License warnings. |
| | | 2772 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.container.keyvalue.TestKeyValueContainer |
|   | hadoop.ozone.container.ozoneimpl.TestOzoneContainer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1430 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux a21aa1c207e6 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 4852a90 |
| Default Java | 1.8.0_222 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/branch-mvninstall-hadoop-ozone.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/branch-compile-hadoop-ozone.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/branch-javadoc-hadoop-hdds.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/branch-javadoc-hadoop-ozone.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/branch-findbugs-hadoop-ozone.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/patch-mvninstall-hadoop-ozone.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/patch-compile-hadoop-ozone.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/patch-compile-hadoop-ozone.txt |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/diff-checkstyle-hadoop-hdds.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/patch-javadoc-hadoop-hdds.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/patch-javadoc-hadoop-ozone.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/patch-findbugs-hadoop-ozone.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/testReport/ |
| Max. process+thread count | 432 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/container-service U: hadoop-hdds/container-service |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1430/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by lokeshj1703** [comment]
@bshashikant Thanks for updating the PR! The changes look good to me. +1. Pending jenkins. The yetus build seems to have an issue.

**Comment by lokeshj1703** [comment]
@bshashikant Thanks for working on the PR! I have merged the commit to trunk.

**Pull request merged**
