### PR TITLE
HDFS-17381. Distcp of EC files should not be limited to DFS.

### PR DESCRIPTION
**Pull request by sadanand48**
### Description of PR
Backport of HDFS-17381 from trunk to branch-3.4

### How was this patch tested?
Unit tests added

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  17m 44s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-3.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 19s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  45m 28s |  |  branch-3.4 passed  |
| +1 :green_heart: |  compile  |  19m 31s |  |  branch-3.4 passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  compile  |  18m  7s |  |  branch-3.4 passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  checkstyle  |   4m 53s |  |  branch-3.4 passed  |
| +1 :green_heart: |  mvnsite  |   3m 40s |  |  branch-3.4 passed  |
| +1 :green_heart: |  javadoc  |   2m 56s |  |  branch-3.4 passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javadoc  |   2m 28s |  |  branch-3.4 passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| -1 :x: |  spotbugs  |   2m 52s | [/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-client-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/1/artifact/out/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-client-warnings.html) |  hadoop-hdfs-project/hadoop-hdfs-client in branch-3.4 has 1 extant spotbugs warnings.  |
| +1 :green_heart: |  shadedclient  |  40m 37s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 33s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m  9s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 45s |  |  the patch passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javac  |  18m 45s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 47s |  |  the patch passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  javac  |  17m 47s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   4m 44s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/1/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 5 new + 93 unchanged - 0 fixed = 98 total (was 93)  |
| +1 :green_heart: |  mvnsite  |   3m 33s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 52s |  |  the patch passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javadoc  |   2m 29s |  |  the patch passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  spotbugs  |   6m 58s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  39m 21s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  19m 23s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 40s |  |  hadoop-hdfs-client in the patch passed.  |
| +1 :green_heart: |  unit  |  16m 21s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  2s |  |  The patch does not generate ASF License warnings.  |
|  |   | 310m 15s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/7083 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux cc863140c0ef 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.4 / 71a32007748d09732cace9215aa3d5bdb2e4d519 |
| Default Java | Private Build-1.8.0_422-8u422-b05-1~20.04-b05 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_422-8u422-b05-1~20.04-b05 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/1/testReport/ |
| Max. process+thread count | 1263 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs-client hadoop-tools/hadoop-distcp U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  11m 47s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-3.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 39s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  41m 46s |  |  branch-3.4 passed  |
| +1 :green_heart: |  compile  |  17m 40s |  |  branch-3.4 passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  compile  |  16m 35s |  |  branch-3.4 passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  checkstyle  |   4m 21s |  |  branch-3.4 passed  |
| +1 :green_heart: |  mvnsite  |   3m 43s |  |  branch-3.4 passed  |
| +1 :green_heart: |  javadoc  |   2m 57s |  |  branch-3.4 passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javadoc  |   2m 31s |  |  branch-3.4 passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| -1 :x: |  spotbugs  |   2m 45s | [/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-client-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/2/artifact/out/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-client-warnings.html) |  hadoop-hdfs-project/hadoop-hdfs-client in branch-3.4 has 1 extant spotbugs warnings.  |
| +1 :green_heart: |  shadedclient  |  34m 34s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 34s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 15s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 56s |  |  the patch passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javac  |  16m 56s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 28s |  |  the patch passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  javac  |  16m 28s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  1s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   4m 23s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/2/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 5 new + 97 unchanged - 0 fixed = 102 total (was 97)  |
| +1 :green_heart: |  mvnsite  |   3m 43s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 53s |  |  the patch passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javadoc  |   2m 37s |  |  the patch passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  spotbugs  |   2m 44s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  spotbugs  |   2m 56s |  |  hadoop-hdfs-project/hadoop-hdfs-client generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  spotbugs  |   1m 14s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  shadedclient  |  34m 51s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  19m 41s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 47s |  |  hadoop-hdfs-client in the patch passed.  |
| +1 :green_heart: |  unit  |  15m 22s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  5s |  |  The patch does not generate ASF License warnings.  |
|  |   | 282m 33s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/7083 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 0d8f4f2b6331 5.15.0-117-generic #127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.4 / b9ec09c76758f17fe9d44bc34fa17ce368f18faf |
| Default Java | Private Build-1.8.0_422-8u422-b05-1~20.04-b05 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_422-8u422-b05-1~20.04-b05 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/2/testReport/ |
| Max. process+thread count | 3152 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs-client hadoop-tools/hadoop-distcp U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/2/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 50s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-3.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 18s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  46m 49s |  |  branch-3.4 passed  |
| +1 :green_heart: |  compile  |  19m 41s |  |  branch-3.4 passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  compile  |  17m 47s |  |  branch-3.4 passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  checkstyle  |   4m 44s |  |  branch-3.4 passed  |
| +1 :green_heart: |  mvnsite  |   3m 44s |  |  branch-3.4 passed  |
| +1 :green_heart: |  javadoc  |   2m 54s |  |  branch-3.4 passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javadoc  |   2m 25s |  |  branch-3.4 passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| -1 :x: |  spotbugs  |   2m 46s | [/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-client-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/3/artifact/out/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-client-warnings.html) |  hadoop-hdfs-project/hadoop-hdfs-client in branch-3.4 has 1 extant spotbugs warnings.  |
| +1 :green_heart: |  shadedclient  |  39m 20s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 33s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 11s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 47s |  |  the patch passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javac  |  18m 47s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 57s |  |  the patch passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  javac  |  17m 57s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   4m 52s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/3/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 5 new + 98 unchanged - 0 fixed = 103 total (was 98)  |
| +1 :green_heart: |  mvnsite  |   3m 39s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 52s |  |  the patch passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javadoc  |   2m 32s |  |  the patch passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  spotbugs  |   2m 46s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  spotbugs  |   3m  5s |  |  hadoop-hdfs-project/hadoop-hdfs-client generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  spotbugs  |   1m 11s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  shadedclient  |  39m 29s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  19m 24s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 41s |  |  hadoop-hdfs-client in the patch passed.  |
| +1 :green_heart: |  unit  |  16m 13s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  5s |  |  The patch does not generate ASF License warnings.  |
|  |   | 293m 27s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/7083 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 1880521fbff2 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.4 / cdeb8dfe7da2e6a34d6b40a61e308057122f80d8 |
| Default Java | Private Build-1.8.0_422-8u422-b05-1~20.04-b05 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_422-8u422-b05-1~20.04-b05 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/3/testReport/ |
| Max. process+thread count | 3137 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs-client hadoop-tools/hadoop-distcp U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7083/3/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by sadanand48** [comment]
@steveloughran could you please review and merge this backport?
Regarding` "hadoop-hdfs-project/hadoop-hdfs-client in branch-3.4 has 1 extant spotbugs warnings."` , I have cherry-picked the commit here itself to fix the spotbugs warning, although I think the check doesn't use code from PR which is why it fails. I tried creating separate PR to see if it made a difference but apparently not.

**Review by jojochuang — APPROVED** [review]
+1. will merge later.

There are checkstyle warnings but I suppose they are carried over from the original commit, so I'm not going to change it and make future backports tricky.

Ideally we should have contract tests for the new FileSystem interface (like what we did in HADOOP-18671/ #5553

**Comment by sadanand48** [comment]
> There are checkstyle warnings but I suppose they are carried over from the original commit

Thanks @jojochuang , These are not from the original commit but due to HDFS-17461 missing on branch-3.4 . I have cherry-picked that change (not part of the original commit) in this same PR in this [commit](https://github.com/apache/hadoop/pull/7083/commits/cdeb8dfe7da2e6a34d6b40a61e308057122f80d8) but somehow the CI still shows this warning.

**Comment by jojochuang** [comment]
Pushed locally to github branch-3.4.
Thanks @sadanand48

**Comment by jojochuang** [comment]
(I pushed locally to preserve commit history. otherwise I'd be forced to squash the two commits)

**Pull request closed without merging**
