### PR TITLE
HDDS-1182. Pipeline Rule where atleast one datanode is reported in the pipeline.

### PR DESCRIPTION
**Pull request by bharatviswa504**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 24 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 30 | Maven dependency ordering for branch |
| +1 | mvninstall | 983 | trunk passed |
| +1 | compile | 76 | trunk passed |
| +1 | checkstyle | 32 | trunk passed |
| +1 | mvnsite | 77 | trunk passed |
| +1 | shadedclient | 760 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 110 | trunk passed |
| +1 | javadoc | 61 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 12 | Maven dependency ordering for patch |
| +1 | mvninstall | 76 | the patch passed |
| +1 | compile | 67 | the patch passed |
| +1 | javac | 67 | the patch passed |
| +1 | checkstyle | 24 | the patch passed |
| +1 | mvnsite | 62 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 739 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 121 | the patch passed |
| +1 | javadoc | 57 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 70 | common in the patch failed. |
| +1 | unit | 137 | server-scm in the patch passed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 3593 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.security.x509.certificate.client.TestDefaultCertificateClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-528/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/528 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  xml  |
| uname | Linux 561cb5a46c9b 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 1779fc5 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-528/1/artifact/out/patch-unit-hadoop-hdds_common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-528/1/testReport/ |
| Max. process+thread count | 543 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-hdds/server-scm U: hadoop-hdds |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-528/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 25 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 34 | Maven dependency ordering for branch |
| +1 | mvninstall | 1186 | trunk passed |
| +1 | compile | 76 | trunk passed |
| +1 | checkstyle | 29 | trunk passed |
| +1 | mvnsite | 71 | trunk passed |
| +1 | shadedclient | 809 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 111 | trunk passed |
| +1 | javadoc | 58 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 11 | Maven dependency ordering for patch |
| +1 | mvninstall | 74 | the patch passed |
| +1 | compile | 72 | the patch passed |
| +1 | javac | 72 | the patch passed |
| +1 | checkstyle | 24 | the patch passed |
| +1 | mvnsite | 62 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 793 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 140 | the patch passed |
| +1 | javadoc | 66 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 89 | common in the patch failed. |
| +1 | unit | 143 | server-scm in the patch passed. |
| +1 | asflicense | 28 | The patch does not generate ASF License warnings. |
| | | 3958 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.security.x509.certificate.client.TestDefaultCertificateClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-528/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/528 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  xml  |
| uname | Linux a90d96c64096 4.4.0-138-generic #164~14.04.1-Ubuntu SMP Fri Oct 5 08:56:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 0feba43 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-528/2/artifact/out/patch-unit-hadoop-hdds_common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-528/2/testReport/ |
| Max. process+thread count | 477 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-hdds/server-scm U: hadoop-hdds |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-528/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 26 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 27 | Maven dependency ordering for branch |
| +1 | mvninstall | 989 | trunk passed |
| +1 | compile | 76 | trunk passed |
| +1 | checkstyle | 31 | trunk passed |
| +1 | mvnsite | 73 | trunk passed |
| +1 | shadedclient | 735 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 100 | trunk passed |
| +1 | javadoc | 52 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 9 | Maven dependency ordering for patch |
| +1 | mvninstall | 65 | the patch passed |
| +1 | compile | 65 | the patch passed |
| +1 | javac | 65 | the patch passed |
| +1 | checkstyle | 21 | the patch passed |
| +1 | mvnsite | 58 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 663 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 113 | the patch passed |
| +1 | javadoc | 48 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 68 | common in the patch failed. |
| +1 | unit | 123 | server-scm in the patch passed. |
| +1 | asflicense | 23 | The patch does not generate ASF License warnings. |
| | | 3401 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.security.x509.certificate.client.TestDefaultCertificateClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-528/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/528 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  xml  |
| uname | Linux de32c33a8a2a 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / eae3db9 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-528/3/artifact/out/patch-unit-hadoop-hdds_common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-528/3/testReport/ |
| Max. process+thread count | 537 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-hdds/server-scm U: hadoop-hdds |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-528/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by bharatviswa504** [comment]
Thank You @arp7 for review.
Test failures are not related to the patch.
Ran tests locally and they passed.
I will commit this shortly.

**Pull request merged**
