### PR TITLE
YARN-11369. Commons.compress throws an IllegalArgumentException with …

### PR DESCRIPTION
**Pull request by ghost**
…large uids after 1.21.

### Description of PR

Encountering [COMPRESS-587](https://issues.apache.org/jira/browse/COMPRESS-587) with large uids/gids in hadoop-mapreduce-client-uploader/src/main/java/org/apache/hadoop/mapred/uploader/FrameworkUploader.java:

22/09/13 06:39:05 INFO uploader.FrameworkUploader: Adding /cs/cloudera/opt/cloudera/cm/lib/plugins/event-publish-7.7.1-shaded.jar
Exception in thread "main" java.lang.IllegalArgumentException: group id '5049047' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit

A workaround is to specifically set bignumber mode to BIGNUMBER_POSIX or BIGNUMBER_STAR on the instance.

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 55s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  42m 34s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   0m 32s |  |  trunk passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  compile  |   0m 31s |  |  trunk passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  checkstyle  |   0m 33s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 35s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   0m 39s |  |  trunk passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   0m 28s |  |  trunk passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  spotbugs  |   0m 58s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  23m 40s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 21s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 21s |  |  the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javac  |   0m 21s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 19s |  |  the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |   0m 19s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 15s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 22s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 19s |  |  the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   0m 18s |  |  the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  spotbugs  |   0m 43s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  23m 17s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 35s |  |  hadoop-mapreduce-client-uploader in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 39s |  |  The patch does not generate ASF License warnings.  |
|  |   | 100m 50s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5116/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5116 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux a88e553e2d68 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / b570a6faf08f4c1808ecb16f0954f38545f522b0 |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5116/1/testReport/ |
| Max. process+thread count | 592 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-uploader U: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-uploader |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5116/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by hotcodemacha — CHANGES_REQUESTED** [review]
Thanks @bteke for your contribution. I have couple of comments -
1. Can you please add a UT to check that while using large uids, it throws IllegalArgumentException and with your fix it is working fine.
2. Please tick the relevant boxes only

```
Does the title or this PR starts with the corresponding JIRA issue id (e.g. '[HADOOP-17799](https://issues.apache.org/jira/browse/HADOOP-17799). Your PR title ...')?
Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
If applicable, have you updated the LICENSE, LICENSE-binary, NOTICE-binary files?
```
 which in your case seem to be just 1st one.

**Comment by brumi1024** [comment]
@ashutoshcipher do you have a specific way in mind? The behaviour change introduced in 1.21 was that if someone with a large UID creates some files and tries to use the lib with no BigNumberMode set to compress them, it throws an IllegalArgumentException, as opposed to setting the owner id/group to 0. Now to properly reproduce this we would need to create a file with a large enough user ID as owner, call the lib, and [let it copy](https://github.com/apache/commons-compress/blob/master/src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveOutputStream.java#L600) the tar details, but this all seems to me like testing an external lib in a unit test, not to mention that at this stage we're using the local file system, so no owner change is possible to non-existent large UID users. 

What we could do instead is to create a large enough file and test if the compress lib allows that in the header. What do you think?

**Comment by szilard-nemeth** [comment]
> @ashutoshcipher do you have a specific way in mind? The behaviour change introduced in 1.21 was that if someone with a large UID creates some files and tries to use the lib with no BigNumberMode set to compress them, it throws an IllegalArgumentException, as opposed to setting the owner id/group to 0. Now to properly reproduce this we would need to create a file with a large enough user ID as owner, call the lib, and [let it copy](https://github.com/apache/commons-compress/blob/master/src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveOutputStream.java?rgh-link-date=2022-11-14T17%3A36%3A24Z#L600) the tar details, but this all seems to me like testing an external lib in a unit test, not to mention that at this stage we're using the local file system, so no owner change is possible to non-existent large UID users.
> 
> What we could do instead is to create a large enough file and test if the compress lib allows that in the header. What do you think?

I do agree with @brumi1024, that it seems quite complicated to test this in the UT-scope, moreover as @brumi1024 mentioned this is more of a library testing and not testing how the FrameworkUploader behaves. 
In this case, I would be fine without adding a new UT case.

**Comment by hotcodemacha** [comment]
I agree with both of you @szilard-nemeth and @bteke. I can understand its complicated to test this in the UT-scope and its more related library testing.

I am +1 on this.

**Review by hotcodemacha — APPROVED** [review]

**Comment by szilard-nemeth** [comment]
Thanks @brumi1024 for your contribution.
+1, committed to trunk.
Thanks @ashutoshcipher for your review.

**Pull request closed without merging**
