### PR TITLE
HADOOP-17950. Provide replacement for deprecated APIs of commons-io IOUtils

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  12m 25s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 10 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  13m  9s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  22m 13s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  23m 14s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |  20m 24s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  checkstyle  |   3m 51s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   7m 53s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   6m 42s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   7m 22s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |  12m 39s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  19m 36s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 54s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  22m 48s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |  22m 48s |  |  root-jdkUbuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 generated 0 new + 1892 unchanged - 28 fixed = 1892 total (was 1920)  |
| +1 :green_heart: |  compile  |  20m 32s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |  20m 32s |  |  root-jdkPrivateBuild-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 generated 0 new + 1768 unchanged - 28 fixed = 1768 total (was 1796)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   3m 55s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   7m 50s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   6m 37s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   7m 30s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |  14m  4s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  19m 48s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 34s |  |  hadoop-maven-plugins in the patch passed.  |
| +1 :green_heart: |  unit  |  17m 42s |  |  hadoop-common in the patch passed.  |
| -1 :x: |  unit  | 238m 47s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3515/3/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 22s |  |  hadoop-yarn-common in the patch passed.  |
| +1 :green_heart: |  unit  | 124m 56s |  |  hadoop-mapreduce-client-jobclient in the patch passed.  |
| +1 :green_heart: |  unit  |  20m 59s |  |  hadoop-yarn-services-core in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  3s |  |  hadoop-mapreduce-client-uploader in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 29s |  |  hadoop-archive-logs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 16s |  |  The patch does not generate ASF License warnings.  |
|  |   | 675m 35s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.blockmanagement.TestBlockTokenWithDFSStriped |
|   | hadoop.hdfs.TestReconstructStripedFileWithRandomECPolicy |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3515/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3515 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 4e321dd7b1ab 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 0090084350cf3e0eeafe8b6a6fb14927846e4ca0 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3515/3/testReport/ |
| Max. process+thread count | 3005 (vs. ulimit of 5500) |
| modules | C: hadoop-maven-plugins hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services/hadoop-yarn-services-core hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-uploader hadoop-tools/hadoop-archive-logs U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3515/3/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  12m 23s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 10 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  17m 58s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  21m 54s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  23m 48s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |  20m  5s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  checkstyle  |   3m 53s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   8m  9s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   6m 26s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   7m 20s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |  12m 36s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  19m 32s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m  2s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  23m  2s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |  23m  2s |  |  root-jdkUbuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 generated 0 new + 1888 unchanged - 28 fixed = 1888 total (was 1916)  |
| +1 :green_heart: |  compile  |  20m  5s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |  20m  5s |  |  root-jdkPrivateBuild-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 generated 0 new + 1763 unchanged - 28 fixed = 1763 total (was 1791)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   3m 49s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   7m 52s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   6m 35s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   7m 19s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |  13m 55s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  19m 47s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 35s |  |  hadoop-maven-plugins in the patch passed.  |
| +1 :green_heart: |  unit  |  17m 37s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  | 238m 39s |  |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 15s |  |  hadoop-yarn-common in the patch passed.  |
| +1 :green_heart: |  unit  | 124m 11s |  |  hadoop-mapreduce-client-jobclient in the patch passed.  |
| +1 :green_heart: |  unit  |  21m  2s |  |  hadoop-yarn-services-core in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  3s |  |  hadoop-mapreduce-client-uploader in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 33s |  |  hadoop-archive-logs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 18s |  |  The patch does not generate ASF License warnings.  |
|  |   | 678m 55s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3515/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3515 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 01d8de83ffad 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 0090084350cf3e0eeafe8b6a6fb14927846e4ca0 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3515/2/testReport/ |
| Max. process+thread count | 3456 (vs. ulimit of 5500) |
| modules | C: hadoop-maven-plugins hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services/hadoop-yarn-services-core hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-uploader hadoop-tools/hadoop-archive-logs U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3515/2/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
@tasanuma @aajisaka could you please review? Thanks

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  8s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 10 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  12m 58s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  23m 50s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  22m 59s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |  19m 30s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  checkstyle  |   3m 59s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   6m 59s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   5m 34s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   6m 28s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |  11m 38s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  22m 23s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 22s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 39s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  22m 11s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |  22m 11s |  |  root-jdkUbuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 generated 0 new + 1888 unchanged - 28 fixed = 1888 total (was 1916)  |
| +1 :green_heart: |  compile  |  19m 31s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |  19m 31s |  |  root-jdkPrivateBuild-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 generated 0 new + 1763 unchanged - 28 fixed = 1763 total (was 1791)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   3m 48s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   7m  1s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   5m 29s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   6m 25s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |  13m 11s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  22m 37s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 32s |  |  hadoop-maven-plugins in the patch passed.  |
| +1 :green_heart: |  unit  |  17m 11s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  | 337m 59s |  |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 53s |  |  hadoop-yarn-common in the patch passed.  |
| +1 :green_heart: |  unit  | 130m 29s |  |  hadoop-mapreduce-client-jobclient in the patch passed.  |
| +1 :green_heart: |  unit  |  21m  1s |  |  hadoop-yarn-services-core in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 52s |  |  hadoop-mapreduce-client-uploader in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 21s |  |  hadoop-archive-logs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  4s |  |  The patch does not generate ASF License warnings.  |
|  |   | 762m 54s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3515/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3515 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 6f0c949e6702 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 0090084350cf3e0eeafe8b6a6fb14927846e4ca0 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3515/1/testReport/ |
| Max. process+thread count | 2210 (vs. ulimit of 5500) |
| modules | C: hadoop-maven-plugins hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services/hadoop-yarn-services-core hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-uploader hadoop-tools/hadoop-archive-logs U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3515/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by aajisaka — CHANGES_REQUESTED** [review]
Thank you for your patch. In Hadoop, `StandardCharsets.UTF_8` should be used instead of the default charset.

**Comment by virajjasani** [comment]
Thanks @aajisaka. As of today, the default implementation that we are using is default charset only. For instance:
```
    @Deprecated
    public static List<String> readLines(final InputStream input) throws IOException {
        return readLines(input, Charset.defaultCharset());
    }
```

```
    @Deprecated
    public static void copy(final InputStream input, final Writer output)
            throws IOException {
        copy(input, output, Charset.defaultCharset());
    }
```
Hence, I thought we should stick to it. Although default is going to use "UTF-8" underneath, if we use `StandardCharsets.UTF_8` right away, isn't it an incompatible change in the behaviour of these APIs?

**Comment by virajjasani** [comment]
@aajisaka Thoughts on above? Is it good to maintain the compatibility?

**Comment by aajisaka** [comment]
Thank you @virajjasani. Using the default charset has some potential issues, so it is fixed when it found (e.g. HADOOP-11379, HADOOP-11389). However, given the change is not compatible, I agreed to merge this PR in the active branches. In the next step, I think we need to create a separate issue to fix the encoding issue only in trunk.

**Review by aajisaka — APPROVED** [review]

**Comment by virajjasani** [comment]
Thanks @aajisaka, this makes sense.

> I agreed to merge this PR in the active branches. In the next step, I think we need to create a separate issue to fix the encoding issue only in trunk.

For trunk, shall we replace all default encoding usages (in addition to what we have in this PR) and replace all with UTF-8?

**Comment by aajisaka** [comment]
> For trunk, shall we replace all default encoding usages (in addition to what we have in this PR) and replace all with UTF-8?

Yes.

**Pull request merged**
