### PR TITLE
HDDS-1492. Generated chunk size name too long.

### PR DESCRIPTION
**Pull request by bshashikant**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 36 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 6 | Maven dependency ordering for branch |
| -1 | mvninstall | 9 | hadoop-hdds in trunk failed. |
| -1 | mvninstall | 9 | hadoop-ozone in trunk failed. |
| -1 | compile | 8 | hadoop-hdds in trunk failed. |
| +1 | checkstyle | 75 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 832 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 165 | trunk passed |
| 0 | spotbugs | 309 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 510 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 75 | Maven dependency ordering for patch |
| +1 | mvninstall | 431 | the patch passed |
| +1 | compile | 262 | the patch passed |
| -1 | javac | 94 | hadoop-hdds generated 14 new + 0 unchanged - 0 fixed = 14 total (was 0) |
| -0 | checkstyle | 32 | hadoop-hdds: The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0) |
| +1 | mvnsite | 0 | the patch passed |
| -1 | whitespace | 0 | The patch has 116 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| -1 | whitespace | 1 | The patch 1800  line(s) with tabs. |
| +1 | shadedclient | 642 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 148 | the patch passed |
| -1 | findbugs | 79 | hadoop-ozone in the patch failed. |
||| _ Other Tests _ |
| +1 | unit | 276 | hadoop-hdds in the patch passed. |
| -1 | unit | 53 | hadoop-ozone in the patch failed. |
| -1 | asflicense | 35 | The patch generated 1 ASF License warnings. |
| | | 4282 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1084 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 17acb20d2ff5 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / f9fab9f |
| Default Java | 1.8.0_212 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/artifact/out/branch-mvninstall-hadoop-hdds.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/artifact/out/branch-mvninstall-hadoop-ozone.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/artifact/out/branch-compile-hadoop-hdds.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/artifact/out/diff-compile-javac-hadoop-hdds.txt |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/artifact/out/diff-checkstyle-hadoop-hdds.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/artifact/out/whitespace-eol.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/artifact/out/whitespace-tabs.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/artifact/out/patch-findbugs-hadoop-ozone.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 476 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/client hadoop-ozone/client U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by bshashikant** [comment]
The updated patch addresses checkstyle issues. I have also verified the name of chunk file in dn.

**Comment by bshashikant** [comment]
The updated patch addresses checkstyle issues. I have also verified the name of chunk file in dn.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 35 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 75 | Maven dependency ordering for branch |
| +1 | mvninstall | 548 | trunk passed |
| +1 | compile | 251 | trunk passed |
| +1 | checkstyle | 65 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 811 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 161 | trunk passed |
| 0 | spotbugs | 316 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 519 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 29 | Maven dependency ordering for patch |
| +1 | mvninstall | 466 | the patch passed |
| +1 | compile | 271 | the patch passed |
| +1 | javac | 271 | the patch passed |
| +1 | checkstyle | 82 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 676 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 165 | the patch passed |
| +1 | findbugs | 531 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 298 | hadoop-hdds in the patch failed. |
| -1 | unit | 2260 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 58 | The patch does not generate ASF License warnings. |
| | | 7485 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.scm.container.placement.algorithms.TestSCMContainerPlacementRackAware |
|   | hadoop.ozone.client.rpc.TestCloseContainerHandlingByClient |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.client.rpc.TestFailureHandlingByClient |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1084 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 2f64705f1436 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / f77d54c |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/2/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/2/testReport/ |
| Max. process+thread count | 5387 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/client hadoop-ozone/client U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1084/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
