### PR TITLE
HADOOP-17753. Keep restrict-imports-enforcer-rule for Guava Lists in top level hadoop-main pom

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Comment by virajjasani** [comment]
FYI @tasanuma. Since individual sub-modules are taken care of, this is for keeping enforcer rule at top level pom.
Local build looks good, let's see if we can get full QA result (unless build is aborted after 20 hr).
Thanks

**Comment by tasanuma** [comment]
+1, pending QA.

**Comment by tasanuma** [comment]
QA had run over 20h and failed due to timeout. I created HADOOP-17756 to suggest extending the timeout.

**Comment by virajjasani** [comment]
Sure, Thanks. Exactly, this timeout keeps happening quite often. I was surprised to see full QA getting completed in 17+ hr in the first run on #3049 :)

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 33s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  13m  0s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  20m 17s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  20m 48s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |  18m 12s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  checkstyle  |   3m 45s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |  24m 18s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   7m 31s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   7m 32s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +0 :ok: |  spotbugs  |   0m 27s |  |  branch/hadoop-cloud-storage-project/hadoop-cloud-storage no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  44m 46s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 41s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  36m 23s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  20m 38s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |  20m 38s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 19s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |  18m 19s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   3m 43s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  20m 18s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m 25s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   7m 30s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   7m 41s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +0 :ok: |  spotbugs  |   0m 28s |  |  hadoop-cloud-storage-project/hadoop-cloud-storage has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  44m 48s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 771m 14s |  |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 42s |  |  The patch does not generate ASF License warnings.  |
|  |   | 1174m 56s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3087/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3087 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux 054b60f681cc 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 89e961b20d08edec96845dda43f5bc07c4813019 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3087/5/testReport/ |
| Max. process+thread count | 3662 (vs. ulimit of 5500) |
| modules | C: hadoop-maven-plugins hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-httpfs hadoop-hdfs-project/hadoop-hdfs-nfs hadoop-yarn-project/hadoop-yarn hadoop-mapreduce-project/hadoop-mapreduce-client hadoop-tools/hadoop-distcp hadoop-hdfs-project/hadoop-hdfs-rbf hadoop-mapreduce-project/hadoop-mapreduce-examples hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-workload hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-infra hadoop-tools/hadoop-aws hadoop-tools/hadoop-kafka hadoop-tools/hadoop-azure hadoop-cloud-storage-project/hadoop-cos hadoop-cloud-storage-project/hadoop-huaweicloud hadoop-cloud-storage-project/hadoop-cloud-storage . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3087/5/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by tasanuma — APPROVED** [review]
Somehow QA ran again, and it finished within 20 hours. The result looks good. +1.

**Comment by tasanuma** [comment]
Merged. Thanks for all your work, @virajjasani!

**Comment by virajjasani** [comment]
Thanks @tasanuma. I triggered 5 builds and fortunately 1 of them finished on time.

**Pull request merged**
