### PR TITLE
HADOOP-16707. NPE in UGI.getCurrentUser in ITestAbfsIdentityTransformer setup.

### PR DESCRIPTION
**Pull request by steveloughran**
Contributed by Steve Loughran.

Change-Id: I38fdba2fa70e534d78b15e61de19368912588b0c

Tested: azure wales

### CODE REVIEW

**Comment by steveloughran** [comment]
reviews requested from @lmccay @DadanielZ 
Although the problem surfaced in test setup in the ABFS tests (and went away with this patch), the root cause is that's not all paths into UGI make sure that it is fully initialised, and if a test resets it, things can fail.

This fixes the production code rather than the symptoms of the failure.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 2122 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1092 | trunk passed |
| +1 | compile | 1023 | trunk passed |
| +1 | checkstyle | 50 | trunk passed |
| +1 | mvnsite | 83 | trunk passed |
| +1 | shadedclient | 889 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 91 | trunk passed |
| 0 | spotbugs | 123 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 122 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 49 | the patch passed |
| +1 | compile | 971 | the patch passed |
| +1 | javac | 971 | the patch passed |
| +1 | checkstyle | 50 | the patch passed |
| +1 | mvnsite | 79 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 762 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 90 | the patch passed |
| +1 | findbugs | 131 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 551 | hadoop-common in the patch passed. |
| +1 | asflicense | 54 | The patch does not generate ASF License warnings. |
| | | 8307 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1723/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1723 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux cf45d71082d0 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 34cb595 |
| Default Java | 1.8.0_222 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1723/1/testReport/ |
| Max. process+thread count | 1374 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1723/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by DadanielZ** [comment]
Hi @steveloughran could you help to refresh my memory of the ABFS tests setup mentioned here?

**Comment by steveloughran** [comment]
no new tests as I verified that the failures in ITestAbfsIdentityTransformer went away.

**Comment by steveloughran** [comment]
thanks!

**Pull request merged**
