### PR TITLE
HADOOP-16527. Add a whitelist of endpoints to skip Kerberos authentication

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/HADOOP-16527

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 10 | Maven dependency ordering for branch |
| +1 | mvninstall | 1088 | trunk passed |
| +1 | compile | 1066 | trunk passed |
| +1 | checkstyle | 39 | trunk passed |
| +1 | mvnsite | 94 | trunk passed |
| +1 | shadedclient | 771 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 78 | trunk passed |
| 0 | spotbugs | 114 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 147 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 10 | Maven dependency ordering for patch |
| +1 | mvninstall | 63 | the patch passed |
| +1 | compile | 1014 | the patch passed |
| +1 | javac | 1014 | the patch passed |
| -0 | checkstyle | 41 | hadoop-common-project: The patch generated 1 new + 4 unchanged - 0 fixed = 5 total (was 4) |
| +1 | mvnsite | 93 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 641 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 84 | the patch passed |
| +1 | findbugs | 173 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 187 | hadoop-auth in the patch passed. |
| +1 | unit | 529 | hadoop-common in the patch passed. |
| +1 | asflicense | 39 | The patch does not generate ASF License warnings. |
| | | 6281 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1336/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1336 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml |
| uname | Linux bed6038e8bc8 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / ee7c261 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1336/1/artifact/out/diff-checkstyle-hadoop-common-project.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1336/1/testReport/ |
| Max. process+thread count | 1361 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-common U: hadoop-common-project |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1336/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 90 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 11 | Maven dependency ordering for branch |
| +1 | mvninstall | 1250 | trunk passed |
| +1 | compile | 1096 | trunk passed |
| +1 | checkstyle | 50 | trunk passed |
| +1 | mvnsite | 120 | trunk passed |
| +1 | shadedclient | 956 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 100 | trunk passed |
| 0 | spotbugs | 149 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 197 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 11 | Maven dependency ordering for patch |
| +1 | mvninstall | 71 | the patch passed |
| +1 | compile | 1036 | the patch passed |
| +1 | javac | 1036 | the patch passed |
| -0 | checkstyle | 51 | hadoop-common-project: The patch generated 1 new + 4 unchanged - 0 fixed = 5 total (was 4) |
| +1 | mvnsite | 115 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 761 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 93 | the patch passed |
| +1 | findbugs | 188 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 218 | hadoop-auth in the patch passed. |
| +1 | unit | 561 | hadoop-common in the patch passed. |
| +1 | asflicense | 42 | The patch does not generate ASF License warnings. |
| | | 7073 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1336/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1336 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml |
| uname | Linux 169032f59ede 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / b69ac57 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1336/2/artifact/out/diff-checkstyle-hadoop-common-project.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1336/2/testReport/ |
| Max. process+thread count | 1384 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-common U: hadoop-common-project |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1336/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 38 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 14 | Maven dependency ordering for branch |
| +1 | mvninstall | 1030 | trunk passed |
| +1 | compile | 962 | trunk passed |
| +1 | checkstyle | 52 | trunk passed |
| +1 | mvnsite | 121 | trunk passed |
| +1 | shadedclient | 865 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 106 | trunk passed |
| 0 | spotbugs | 121 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 167 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 14 | Maven dependency ordering for patch |
| +1 | mvninstall | 70 | the patch passed |
| +1 | compile | 929 | the patch passed |
| +1 | javac | 929 | the patch passed |
| -0 | checkstyle | 53 | hadoop-common-project: The patch generated 1 new + 4 unchanged - 0 fixed = 5 total (was 4) |
| +1 | mvnsite | 117 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 667 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 108 | the patch passed |
| +1 | findbugs | 186 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 200 | hadoop-auth in the patch passed. |
| +1 | unit | 563 | hadoop-common in the patch passed. |
| +1 | asflicense | 51 | The patch does not generate ASF License warnings. |
| | | 6379 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1336/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1336 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml |
| uname | Linux 59f179510f57 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3329257 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1336/3/artifact/out/diff-checkstyle-hadoop-common-project.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1336/3/testReport/ |
| Max. process+thread count | 1377 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-common U: hadoop-common-project |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1336/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by tasanuma** [comment]
+1. Will merge it.

**Pull request merged**
