### PR TITLE
HDDS-1476. Fix logIfNeeded logic in EndPointStateMachine.

### PR DESCRIPTION
**Pull request by swagle**

### CODE REVIEW

**Comment by arp7** [comment]
+1 pending Jenkins. Thanks for fixing this @swagle

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 49 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1040 | trunk passed |
| +1 | compile | 50 | trunk passed |
| +1 | checkstyle | 27 | trunk passed |
| +1 | mvnsite | 37 | trunk passed |
| +1 | shadedclient | 741 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 54 | trunk passed |
| +1 | javadoc | 32 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 35 | the patch passed |
| +1 | compile | 28 | the patch passed |
| +1 | javac | 28 | the patch passed |
| +1 | checkstyle | 16 | the patch passed |
| +1 | mvnsite | 31 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 747 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 58 | the patch passed |
| +1 | javadoc | 27 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 66 | container-service in the patch failed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 3154 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.container.common.statemachine.commandhandler.TestCloseContainerCommandHandler |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-779/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/779 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux b0e160296f07 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 43b2a4b |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-779/1/artifact/out/patch-unit-hadoop-hdds_container-service.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-779/1/testReport/ |
| Max. process+thread count | 468 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/container-service U: hadoop-hdds/container-service |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-779/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by swagle** [comment]
Failure seems unrelated to change.

**Pull request merged**
