### PR TITLE
HDDS-1357. ozone s3 shell command has confusing subcommands

### PR DESCRIPTION
**Pull request by elek**
Let's check the potential subcommands of ozone sh:

{code}
[hadoop@om-0 keytabs]$ ozone sh
Incomplete command
Usage: ozone sh [-hV] [--verbose] [-D=<String=String>]... [COMMAND]
Shell for Ozone object store
      --verbose   More verbose output. Show the stack trace of the errors.
  -D, --set=<String=String>

  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  volume, vol  Volume specific operations
  bucket       Bucket specific operations
  key          Key specific operations
  token        Token specific operations
{code}

This is fine, but for ozone s3:

{code}
[hadoop@om-0 keytabs]$ ozone s3
Incomplete command
Usage: ozone s3 [-hV] [--verbose] [-D=<String=String>]... [COMMAND]
Shell for S3 specific operations
      --verbose   More verbose output. Show the stack trace of the errors.
  -D, --set=<String=String>

  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  getsecret    Returns s3 secret for current user
  path         Returns the ozone path for S3Bucket
  volume, vol  Volume specific operations
  bucket       Bucket specific operations
  key          Key specific operations
  token        Token specific operations
{code}

This list should contain only the getsecret/path commands and not the volume/bucket/key subcommands.

See: https://issues.apache.org/jira/browse/HDDS-1357

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 28 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 57 | Maven dependency ordering for branch |
| +1 | mvninstall | 1082 | trunk passed |
| +1 | compile | 125 | trunk passed |
| +1 | checkstyle | 34 | trunk passed |
| +1 | mvnsite | 124 | trunk passed |
| +1 | shadedclient | 647 | branch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 104 | trunk passed |
| +1 | javadoc | 100 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 18 | Maven dependency ordering for patch |
| +1 | mvninstall | 110 | the patch passed |
| +1 | compile | 101 | the patch passed |
| +1 | javac | 101 | the patch passed |
| -0 | checkstyle | 24 | hadoop-ozone: The patch generated 10 new + 0 unchanged - 0 fixed = 10 total (was 0) |
| +1 | mvnsite | 85 | the patch passed |
| +1 | shellcheck | 27 | There were no new shellcheck issues. |
| +1 | shelldocs | 13 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 703 | patch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 120 | the patch passed |
| +1 | javadoc | 86 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 38 | common in the patch passed. |
| +1 | unit | 47 | ozone-manager in the patch passed. |
| -1 | unit | 655 | integration-test in the patch failed. |
| +1 | asflicense | 30 | The patch does not generate ASF License warnings. |
| | | 4537 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-663/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/663 |
| Optional Tests |  dupname  asflicense  mvnsite  unit  shellcheck  shelldocs  compile  javac  javadoc  mvninstall  shadedclient  findbugs  checkstyle  |
| uname | Linux 41bd104bbfd8 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 6186ed9 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
| findbugs | v3.1.0-RC1 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-663/1/artifact/out/diff-checkstyle-hadoop-ozone.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-663/1/artifact/out/patch-unit-hadoop-ozone_integration-test.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-663/1/testReport/ |
| Max. process+thread count | 4084 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/common hadoop-ozone/ozone-manager hadoop-ozone/integration-test U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-663/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by bharatviswa504** [comment]
LGTM, once Jenkins reported issues are fixed.

**Comment by ajayydv** [comment]
+1 with checkstyle and 1 NIT addressed.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 27 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 62 | Maven dependency ordering for branch |
| +1 | mvninstall | 1067 | trunk passed |
| +1 | compile | 106 | trunk passed |
| +1 | checkstyle | 34 | trunk passed |
| +1 | mvnsite | 115 | trunk passed |
| +1 | shadedclient | 648 | branch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 112 | trunk passed |
| +1 | javadoc | 94 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 16 | Maven dependency ordering for patch |
| +1 | mvninstall | 108 | the patch passed |
| +1 | compile | 99 | the patch passed |
| +1 | javac | 99 | the patch passed |
| +1 | checkstyle | 26 | the patch passed |
| +1 | mvnsite | 89 | the patch passed |
| +1 | shellcheck | 26 | There were no new shellcheck issues. |
| +1 | shelldocs | 16 | The patch generated 0 new + 104 unchanged - 132 fixed = 104 total (was 236) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 726 | patch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 116 | the patch passed |
| +1 | javadoc | 73 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 36 | common in the patch passed. |
| +1 | unit | 44 | ozone-manager in the patch passed. |
| -1 | unit | 602 | integration-test in the patch failed. |
| +1 | asflicense | 35 | The patch does not generate ASF License warnings. |
| | | 4441 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-663/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/663 |
| Optional Tests |  dupname  asflicense  mvnsite  unit  shellcheck  shelldocs  compile  javac  javadoc  mvninstall  shadedclient  findbugs  checkstyle  |
| uname | Linux 8221beffdade 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / d9e9e56 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
| findbugs | v3.1.0-RC1 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-663/2/artifact/out/patch-unit-hadoop-ozone_integration-test.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-663/2/testReport/ |
| Max. process+thread count | 4051 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/common hadoop-ozone/ozone-manager hadoop-ozone/integration-test U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-663/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by bharatviswa504** [comment]
+1 LGTM. I will commit this shortly.

**Pull request merged**
