### PR TITLE
HDDS-1846. Default value for checksum bytes is different in ozone-site.xml and code.

### PR DESCRIPTION
**Pull request by bharatviswa504**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 38 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 616 | trunk passed |
| +1 | compile | 365 | trunk passed |
| +1 | checkstyle | 65 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 846 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 153 | trunk passed |
| 0 | spotbugs | 416 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 614 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 526 | the patch passed |
| +1 | compile | 348 | the patch passed |
| +1 | javac | 348 | the patch passed |
| +1 | checkstyle | 69 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 628 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 149 | the patch passed |
| +1 | findbugs | 615 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 292 | hadoop-hdds in the patch passed. |
| -1 | unit | 2149 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 38 | The patch does not generate ASF License warnings. |
| | | 7665 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.TestStorageContainerManager |
|   | hadoop.ozone.container.common.statemachine.commandhandler.TestCloseContainerByPipeline |
|   | hadoop.ozone.om.snapshot.TestOzoneManagerSnapshotProvider |
|   | hadoop.ozone.client.rpc.TestCloseContainerHandlingByClient |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1139/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1139 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 6a4ed0a81fce 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c533b79 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1139/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1139/1/testReport/ |
| Max. process+thread count | 4346 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common U: hadoop-hdds/common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1139/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by arp7** [comment]
Why are there so many test failures?

**Comment by bharatviswa504** [comment]
Test failures are not related to this patch.
Most of the tests are broken in trunk also and I see similar test failures in other PR's also.

**Comment by anuengineer** [comment]
> Why are there so many test failures?

These are failing in the trunk too .. I know off around 27 cases which are failing in the trunk. We are going to address all of them and port the changes to 0.4.1. I think they are due to:

1. Originally due to ACL changes and Topology 
2. Since we had some regular failures, a set of changes went in. Now we have failures in other parts of the code since ACL and Topology issues are completely fixed.

So we are in this hole where there is a large number of failures, the RPC client failure is a consistent failure even on local runs. I am working on these issues.

**Comment by anuengineer** [comment]
For checkstyle, it was a commit I made yesterday night, and we fixed the issue today morning. So please ignore that.

**Comment by bharatviswa504** [comment]
Thank You @anuengineer for the review and commit and @arp7 for the review.
Closing this, as it is committed.

**Comment by anuengineer** [comment]
@bharatviswa504  Thanks for the contribution. @arp7  Thanks for the comments. I have committed this to trunk and ozone-0.4.1 branches.

**Pull request closed without merging**
