### PR TITLE
HDFS-15728. Update description of dfs.datanode.handler.count in hdfs-default.xml

### PR DESCRIPTION
**Pull request by liuyanpunk**
updated to a more precise definition to dfs.datanode.handler.count description

https://issues.apache.org/jira/browse/HDFS-15728

### CODE REVIEW

**Comment by ayushtkn** [comment]
Please create a jira first, There is a comment above with NOTICE is big letters, you need to follow the instructions over there.

In case you face any issue doing so, let me know

**Comment by liuyanpunk** [comment]
Hello Ayush Saxena

  Thanks for the direction and I have updated the Title with corresponding Jira number

**Review by jojochuang — APPROVED** [review]

**Review by ayushtkn — APPROVED** [review]
+1

**Comment by ayushtkn** [comment]
Merged to trunk.
@liuyanpunk Thanx for the contribution and next time please raise a PR against trunk branch not master. Anyway this time I have sorted it out.
Thanx @jojochuang for the review!!!

**Pull request merged**
