### PR TITLE
HADOOP-18049. Pin python lazy-object-proxy to 1.6.0 in Docker file as newer versions are incompatible with python2.7

### PR DESCRIPTION
**Pull request by dbadaya1**
### How was this patch tested?
`./start-build-env.sh` executes without failure.

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3813/1/console in case of problems.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 59s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-2.10 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 27s |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |   6m  5s |  root in branch-2.10 failed.  |
| +1 :green_heart: |  mvnsite  |   0m  0s |  branch-2.10 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 33s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m  0s |  the patch passed  |
| +1 :green_heart: |  hadolint  |   0m  3s |  There were no new hadolint issues.  |
| +1 :green_heart: |  mvnsite  |   0m  0s |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 15s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 28s |  The patch does not generate ASF License warnings.  |
|  |   |  14m 12s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3813/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3813 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs mvnsite unit |
| uname | Linux ae6808d80dc8 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / 7d88a54 |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3813/1/artifact/out/branch-mvninstall-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3813/1/testReport/ |
| Max. process+thread count | 93 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3813/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.3.7 hadolint=1.11.1-0-g0e692dd |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by aajisaka — APPROVED** [review]
LGTM

**Comment by aajisaka** [comment]
Merged. Thank you @dbadaya1

**Pull request merged**
