### PR TITLE
HDFS-17544. [ARR] The router client rpc protocol PB supports asynchrony.

### PR DESCRIPTION
**Pull request by KeeProMise**
### Description of PR
Please see :  https://issues.apache.org/jira/browse/HDFS-17544

**NOTE**: 
This is a sub-pull request (PR) related to [HDFS-17531](https://issues.apache.org/jira/browse/HDFS-17531)(Asynchronous router RPC). For more details or context, please refer to the main issue [HDFS-17531](https://issues.apache.org/jira/browse/HDFS-17531)
More detailed documentation: [HDFS-17531](https://issues.apache.org/jira/browse/HDFS-17531) Router asynchronous rpc implementation.pdf and Aynchronous router.pdf

### How was this patch tested?
new UTs:

1.TestAsyncRpcProtocolPBUtil
2.TestRouterClientSideTranslatorPB

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hfutatzhanghb** [comment]
@KeeProMise Hi, sir. The code in this PR contains HDFS-17543's change.  Can we seperate them for better reviewing.

**Comment by KeeProMise** [comment]
> @KeeProMise Hi, sir. The code in this PR contains [HDFS-17543](https://issues.apache.org/jira/browse/HDFS-17543)'s change. Can we seperate them for better reviewing.

@hfutatzhanghb Hi, It does include HDFS-17543. The main reason is that this PR needs to use AsyncUtil of HDFS-17543. We should first review and merge HDFS-17543 and then review this PR. Before HDFS-17543 is merged, this PR is only used as an example of subsequent use of AsyncUtil.

**Comment by KeeProMise** [comment]
@goiri @simbadzina @Hexiaoqiao @sjlee @ayushtkn
Hi, if you have time, please help to take a look at this PR, thanks!

**Comment by KeeProMise** [comment]
Modifications related to ipc.client, please see to [HADOOP-19235](https://issues.apache.org/jira/browse/HADOOP-19235) .https://github.com/apache/hadoop/pull/6888

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m  0s |  |  Docker mode activated.  |
| -1 :x: |  patch  |   0m 20s |  |  https://github.com/apache/hadoop/pull/6870 does not apply to HDFS-17531. Rebase required? Wrong Branch? See https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/6870 |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6870/13/console |
| versions | git=2.34.1 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   6m 46s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 5 new or modified test files.  |
|||| _ HDFS-17531 Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 59s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  19m 41s |  |  HDFS-17531 passed  |
| +1 :green_heart: |  compile  |   2m 55s |  |  HDFS-17531 passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2  |
| +1 :green_heart: |  compile  |   2m 49s |  |  HDFS-17531 passed with JDK Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08  |
| +1 :green_heart: |  checkstyle  |   0m 44s |  |  HDFS-17531 passed  |
| +1 :green_heart: |  mvnsite  |   0m 56s |  |  HDFS-17531 passed  |
| +1 :green_heart: |  javadoc  |   0m 56s |  |  HDFS-17531 passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2  |
| +1 :green_heart: |  javadoc  |   0m 50s |  |  HDFS-17531 passed with JDK Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08  |
| +1 :green_heart: |  spotbugs  |   2m 12s |  |  HDFS-17531 passed  |
| +1 :green_heart: |  shadedclient  |  20m  8s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 22s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 47s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 49s |  |  the patch passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2  |
| +1 :green_heart: |  javac  |   2m 49s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 41s |  |  the patch passed with JDK Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08  |
| +1 :green_heart: |  javac  |   2m 41s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   0m 36s | [/results-checkstyle-hadoop-hdfs-project.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6870/16/artifact/out/results-checkstyle-hadoop-hdfs-project.txt) |  hadoop-hdfs-project: The patch generated 2 new + 22 unchanged - 1 fixed = 24 total (was 23)  |
| +1 :green_heart: |  mvnsite  |   0m 48s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 41s |  |  the patch passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2  |
| +1 :green_heart: |  javadoc  |   0m 42s |  |  the patch passed with JDK Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08  |
| +1 :green_heart: |  spotbugs  |   2m 13s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  20m 39s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 44s |  |  hadoop-hdfs-client in the patch passed.  |
| -1 :x: |  unit  |  27m 23s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs-rbf.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6870/16/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs-rbf.txt) |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 26s |  |  The patch does not generate ASF License warnings.  |
|  |   | 135m 25s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.federation.router.TestRouterRpcMultiDestination |
|   | hadoop.hdfs.server.federation.router.TestRouterRpc |
|   | hadoop.hdfs.server.federation.router.TestRouterMultiRack |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.46 ServerAPI=1.46 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6870/16/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6870 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux aff8b889771a 5.15.0-106-generic #116-Ubuntu SMP Wed Apr 17 09:17:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | HDFS-17531 / c311ab602a44936d5ed9f7efdf5c5bc8e65aeb88 |
| Default Java | Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6870/16/testReport/ |
| Max. process+thread count | 3709 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs-rbf U: hadoop-hdfs-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6870/16/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 21s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  1s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 5 new or modified test files.  |
|||| _ HDFS-17531 Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 23s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  20m 11s |  |  HDFS-17531 passed  |
| +1 :green_heart: |  compile  |   2m 50s |  |  HDFS-17531 passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2  |
| +1 :green_heart: |  compile  |   2m 46s |  |  HDFS-17531 passed with JDK Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08  |
| +1 :green_heart: |  checkstyle  |   0m 44s |  |  HDFS-17531 passed  |
| +1 :green_heart: |  mvnsite  |   1m  2s |  |  HDFS-17531 passed  |
| +1 :green_heart: |  javadoc  |   0m 54s |  |  HDFS-17531 passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2  |
| +1 :green_heart: |  javadoc  |   0m 48s |  |  HDFS-17531 passed with JDK Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08  |
| +1 :green_heart: |  spotbugs  |   2m 10s |  |  HDFS-17531 passed  |
| +1 :green_heart: |  shadedclient  |  20m 11s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 21s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 50s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 50s |  |  the patch passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2  |
| +1 :green_heart: |  javac  |   2m 50s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 39s |  |  the patch passed with JDK Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08  |
| +1 :green_heart: |  javac  |   2m 39s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 37s |  |  hadoop-hdfs-project: The patch generated 0 new + 22 unchanged - 1 fixed = 22 total (was 23)  |
| +1 :green_heart: |  mvnsite  |   0m 51s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 41s |  |  the patch passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2  |
| +1 :green_heart: |  javadoc  |   0m 43s |  |  the patch passed with JDK Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08  |
| +1 :green_heart: |  spotbugs  |   2m 15s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  20m 13s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 45s |  |  hadoop-hdfs-client in the patch passed.  |
| +1 :green_heart: |  unit  |  26m 56s |  |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 26s |  |  The patch does not generate ASF License warnings.  |
|  |   | 128m 59s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.46 ServerAPI=1.46 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6870/17/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6870 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux fe27c75d2ac5 5.15.0-106-generic #116-Ubuntu SMP Wed Apr 17 09:17:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | HDFS-17531 / 21a1b1acfb2ef00ded98839bea0bcac3d44f7497 |
| Default Java | Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6870/17/testReport/ |
| Max. process+thread count | 3684 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs-rbf U: hadoop-hdfs-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6870/17/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by KeeProMise** [comment]
@goiri @simbadzina @Hexiaoqiao @sjlee @ayushtkn @haiyang1987 @ZanderXu 
Hi, if you have time, please help to take a look at this PR, thanks!

**Review by Hexiaoqiao — APPROVED** [review]
LGTM

**Comment by KeeProMise** [comment]
> LGTM

Hi, if no comments here, please help to merge it, thanks!

**Comment by Hexiaoqiao** [comment]
Committed to HDFS-17531, Thanks @KeeProMise !

**Comment by KeeProMise** [comment]
> Committed to [HDFS-17531](https://issues.apache.org/jira/browse/HDFS-17531), Thanks @KeeProMise !

@Hexiaoqiao Thank you for your review and merge!

**Pull request merged**
