### PR TITLE
HDDS-1916. Only contract tests are run in ozonefs module

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Add default Surefire inclusion patterns in addition to the custom one for contract tests.

https://issues.apache.org/jira/browse/HDDS-1916

## How was this patch tested?

Verified that the remaining 6 test classes are also run by Maven:

```
[INFO] --- maven-surefire-plugin:3.0.0-M1:test (default-test) @ hadoop-ozone-filesystem ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.fs.ozone.contract.ITestOzoneContractGetFileStatus
[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.763 s - in org.apache.hadoop.fs.ozone.contract.ITestOzoneContractGetFileStatus
[INFO] Running org.apache.hadoop.fs.ozone.contract.ITestOzoneContractSeek
[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.517 s - in org.apache.hadoop.fs.ozone.contract.ITestOzoneContractSeek
[INFO] Running org.apache.hadoop.fs.ozone.contract.ITestOzoneContractDelete
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.624 s - in org.apache.hadoop.fs.ozone.contract.ITestOzoneContractDelete
[INFO] Running org.apache.hadoop.fs.ozone.contract.ITestOzoneContractRootDir
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.872 s - in org.apache.hadoop.fs.ozone.contract.ITestOzoneContractRootDir
[INFO] Running org.apache.hadoop.fs.ozone.contract.ITestOzoneContractMkdir
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.223 s - in org.apache.hadoop.fs.ozone.contract.ITestOzoneContractMkdir
[INFO] Running org.apache.hadoop.fs.ozone.contract.ITestOzoneContractRename
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.569 s - in org.apache.hadoop.fs.ozone.contract.ITestOzoneContractRename
[INFO] Running org.apache.hadoop.fs.ozone.contract.ITestOzoneContractDistCp
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 35.582 s - in org.apache.hadoop.fs.ozone.contract.ITestOzoneContractDistCp
[INFO] Running org.apache.hadoop.fs.ozone.contract.ITestOzoneContractCreate
[WARNING] Tests run: 11, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 21.074 s - in org.apache.hadoop.fs.ozone.contract.ITestOzoneContractCreate
[INFO] Running org.apache.hadoop.fs.ozone.contract.ITestOzoneContractOpen
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.094 s - in org.apache.hadoop.fs.ozone.contract.ITestOzoneContractOpen
[INFO] Running org.apache.hadoop.fs.ozone.TestFilteredClassLoader
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.21 s - in org.apache.hadoop.fs.ozone.TestFilteredClassLoader
[INFO] Running org.apache.hadoop.fs.ozone.TestOzoneFileInterfaces
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 140.386 s - in org.apache.hadoop.fs.ozone.TestOzoneFileInterfaces
[INFO] Running org.apache.hadoop.fs.ozone.TestOzoneFileSystemWithMocks
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.05 s - in org.apache.hadoop.fs.ozone.TestOzoneFileSystemWithMocks
[INFO] Running org.apache.hadoop.fs.ozone.TestOzoneFsRenameDir
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.711 s - in org.apache.hadoop.fs.ozone.TestOzoneFsRenameDir
[INFO] Running org.apache.hadoop.fs.ozone.TestOzoneFileSystem
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 77.904 s - in org.apache.hadoop.fs.ozone.TestOzoneFileSystem
[INFO] Running org.apache.hadoop.fs.ozone.TestOzoneFSInputStream
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 48.962 s - in org.apache.hadoop.fs.ozone.TestOzoneFSInputStream
[INFO]
[INFO] Results:
[INFO]
[WARNING] Tests run: 117, Failures: 0, Errors: 0, Skipped: 2
```

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 40 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 600 | trunk passed |
| +1 | compile | 360 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1712 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 147 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 556 | the patch passed |
| +1 | compile | 365 | the patch passed |
| +1 | javac | 365 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 673 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 166 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 307 | hadoop-hdds in the patch passed. |
| -1 | unit | 168 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 40 | The patch does not generate ASF License warnings. |
| | | 4363 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.om.ratis.TestOzoneManagerDoubleBufferWithDummyResponse |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1235/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1235 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux e7332f856877 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 2662e20 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1235/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1235/1/testReport/ |
| Max. process+thread count | 1363 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/ozonefs U: hadoop-ozone/ozonefs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1235/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 63 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 671 | trunk passed |
| +1 | compile | 438 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1990 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 192 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 655 | the patch passed |
| +1 | compile | 458 | the patch passed |
| +1 | javac | 458 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 688 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 160 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 336 | hadoop-hdds in the patch passed. |
| -1 | unit | 3292 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 53 | The patch does not generate ASF License warnings. |
| | | 8056 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.hdds.scm.pipeline.TestRatisPipelineCreateAndDestory |
|   | hadoop.ozone.client.rpc.TestMultiBlockWritesWithDnFailures |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.TestMiniOzoneCluster |
|   | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1235/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1235 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 8e39febe6de2 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3cc0ace |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1235/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1235/2/testReport/ |
| Max. process+thread count | 4935 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/ozonefs U: hadoop-ozone/ozonefs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1235/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 72 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 629 | trunk passed |
| +1 | compile | 370 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1886 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 178 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 580 | the patch passed |
| +1 | compile | 392 | the patch passed |
| +1 | javac | 392 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 741 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 185 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 355 | hadoop-hdds in the patch passed. |
| -1 | unit | 404 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 37 | The patch does not generate ASF License warnings. |
| | | 5003 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.recon.api.TestContainerKeyService |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1235/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1235 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 051595a36ff1 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 00b5a27 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1235/3/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1235/3/testReport/ |
| Max. process+thread count | 1328 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/ozonefs U: hadoop-ozone/ozonefs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1235/3/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by anuengineer** [comment]
@adoroszlai  Thanks for the contribution. @bharatviswa504  Thanks for the review. I have committed this to the trunk.

**Comment by adoroszlai** [comment]
Thanks @bharatviswa504 for the review, and @anuengineer for commiting it.

**Pull request closed without merging**
