### PR TITLE
HDDS-1653. Add option to "ozone scmcli printTopology" to order the ou…

### PR DESCRIPTION
**Pull request by xiaoyuyao**
…tput acccording to topology layer. Contributed by Xiaoyu Yao.

### CODE REVIEW

**Comment by xiaoyuyao** [comment]
Attach a sample output:
bash-4.2$ ozone scmcli printTopology
State = HEALTHY
 10.5.0.7(datanode_4.ozone-topology_net)    /rack2
 10.5.0.5(datanode_2.ozone-topology_net)    /rack1
 10.5.0.6(datanode_3.ozone-topology_net)    /rack1
 10.5.0.4(datanode_1.ozone-topology_net)    /rack1
bash-4.2$ ozone scmcli printTopology -o
State = HEALTHY
Location: /rack1
 10.5.0.4(datanode_1.ozone-topology_net)
 10.5.0.5(datanode_2.ozone-topology_net)
 10.5.0.6(datanode_3.ozone-topology_net)
Location: /rack2
 10.5.0.7(datanode_4.ozone-topology_net)

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 31 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 479 | trunk passed |
| +1 | compile | 256 | trunk passed |
| +1 | checkstyle | 73 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 852 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 159 | trunk passed |
| 0 | spotbugs | 320 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 508 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 450 | the patch passed |
| +1 | compile | 250 | the patch passed |
| +1 | javac | 250 | the patch passed |
| +1 | checkstyle | 81 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 679 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 161 | the patch passed |
| +1 | findbugs | 522 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 286 | hadoop-hdds in the patch passed. |
| -1 | unit | 1751 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 37 | The patch does not generate ASF License warnings. |
| | | 6725 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.om.TestOzoneManagerHA |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.client.rpc.TestFailureHandlingByClient |
|   | hadoop.hdds.scm.pipeline.TestRatisPipelineCreateAndDestory |
|   | hadoop.ozone.client.rpc.TestCommitWatcher |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestWatchForCommit |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.TestMiniChaosOzoneCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1067/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1067 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 940da1eaf7a1 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 993dc87 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1067/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1067/1/testReport/ |
| Max. process+thread count | 5231 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/tools U: hadoop-hdds/tools |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1067/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by ChenSammi** [comment]
@xiaoyuyao , with uuid as network name, here is output,
ozone scmcli printTopology
State = HEALTHY
 10.5.0.5(ozone-topology_datanode_2_1.ozone-topology_net)    /rack1
 10.5.0.6(ozone-topology_datanode_3_1.ozone-topology_net)    /rack1
 10.5.0.4(ozone-topology_datanode_1_1.ozone-topology_net)    /rack1

ozone scmcli printTopology -o
State = HEALTHY
Location: /rack1
 2a2e4f1a-47a8-4c9f-8368-d719aab3057b
 2c6478ae-dbba-4349-8759-7c803e2e6617
 a803fa42-291c-42b3-8577-719f5746980b

I would suggest add Ipaddress & hostname in "-o" options.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 76 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 1 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 71 | Maven dependency ordering for branch |
| +1 | mvninstall | 518 | trunk passed |
| +1 | compile | 315 | trunk passed |
| +1 | checkstyle | 88 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 871 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 183 | trunk passed |
| 0 | spotbugs | 342 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 558 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 41 | Maven dependency ordering for patch |
| +1 | mvninstall | 497 | the patch passed |
| +1 | compile | 321 | the patch passed |
| +1 | javac | 321 | the patch passed |
| +1 | checkstyle | 93 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | shellcheck | 1 | There were no new shellcheck issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 814 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 218 | the patch passed |
| +1 | findbugs | 653 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 125 | hadoop-hdds in the patch failed. |
| -1 | unit | 2095 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 51 | The patch does not generate ASF License warnings. |
| | | 7870 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.lock.TestLockManager |
|   | hadoop.ozone.client.rpc.TestMultiBlockWritesWithDnFailures |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestFailureHandlingByClient |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.client.rpc.TestCloseContainerHandlingByClient |
|   | hadoop.ozone.container.server.TestSecureContainerServer |
|   | hadoop.ozone.client.rpc.TestWatchForCommit |
|   | hadoop.ozone.container.ozoneimpl.TestSecureOzoneContainer |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.hdds.scm.pipeline.TestRatisPipelineCreateAndDestory |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1067/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1067 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle shellcheck shelldocs |
| uname | Linux 7fc322282b06 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 9838a47 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1067/2/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1067/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1067/2/testReport/ |
| Max. process+thread count | 4862 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/tools hadoop-ozone/dist U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1067/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by ChenSammi** [comment]
+1, will commit shortly.

**Pull request merged**
