### PR TITLE
HADOOP-18442. Remove openstack support

### PR DESCRIPTION
**Pull request by steveloughran**
### Description of PR

Remove all hadoop-openstack code, tests, references in the XML files, docs.

Retain the JAR so that it can still be published to maven, which can ensure that
projects importing the jar explicitly still build.

### How was this patch tested?

Removed the source; rebuilt module.

### For code changes:

- [X] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [X] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by steveloughran** [comment]
openstack test endpoint: none!

**Review by iwasakims — APPROVED** [review]
LGTM.

```
$ mvn clean install -DskipTests -Pdist
$ find hadoop-dist/target/hadoop-3.4.0-SNAPSHOT -iname '*openstack*'
```

**Review by hotcodemacha — APPROVED** [review]
LGTM

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 51s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  1s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  1s |  |  xmllint was not available.  |
| +0 :ok: |  markdownlint  |   0m  1s |  |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 39 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 54s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  28m 21s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  25m 40s |  |  trunk passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  compile  |  22m 13s |  |  trunk passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  checkstyle  |   4m 28s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   5m 59s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   5m 18s |  |  trunk passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   4m 40s |  |  trunk passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +0 :ok: |  spotbugs  |   0m 59s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 45s |  |  branch/hadoop-tools/hadoop-tools-dist no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 44s |  |  branch/hadoop-cloud-storage-project/hadoop-cloud-storage no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  23m 24s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 43s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  24m 32s |  |  the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javac  |  24m 32s |  |  root-jdkUbuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 generated 0 new + 2843 unchanged - 10 fixed = 2843 total (was 2853)  |
| +1 :green_heart: |  compile  |  21m 58s |  |  the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |  21m 58s |  |  root-jdkPrivateBuild-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 generated 0 new + 2643 unchanged - 7 fixed = 2643 total (was 2650)  |
| -1 :x: |  blanks  |   0m  0s | [/blanks-eol.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4855/1/artifact/out/blanks-eol.txt) |  The patch has 1 line(s) that end in blanks. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  checkstyle  |   4m 17s |  |  root: The patch generated 0 new + 1 unchanged - 473 fixed = 1 total (was 474)  |
| +1 :green_heart: |  mvnsite  |   5m 50s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 44s |  |  hadoop-project in the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04.  |
| +1 :green_heart: |  javadoc  |   1m 16s |  |  hadoop-common in the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04.  |
| +1 :green_heart: |  javadoc  |   0m 49s |  |  hadoop-distcp in the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04.  |
| +1 :green_heart: |  javadoc  |   0m 44s |  |  hadoop-tools-dist in the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04.  |
| +1 :green_heart: |  javadoc  |   0m 44s |  |  hadoop-tools_hadoop-openstack-jdkUbuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 generated 0 new + 0 unchanged - 22 fixed = 0 total (was 22)  |
| +1 :green_heart: |  javadoc  |   0m 44s |  |  hadoop-cloud-storage in the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04.  |
| +1 :green_heart: |  javadoc  |   0m 42s |  |  hadoop-project in the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07.  |
| +1 :green_heart: |  javadoc  |   0m 59s |  |  hadoop-common in the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07.  |
| +1 :green_heart: |  javadoc  |   0m 47s |  |  hadoop-distcp in the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07.  |
| +1 :green_heart: |  javadoc  |   0m 43s |  |  hadoop-tools-dist in the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07.  |
| +1 :green_heart: |  javadoc  |   0m 42s |  |  hadoop-tools_hadoop-openstack-jdkPrivateBuild-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 generated 0 new + 0 unchanged - 22 fixed = 0 total (was 22)  |
| +1 :green_heart: |  javadoc  |   0m 43s |  |  hadoop-cloud-storage in the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07.  |
| +0 :ok: |  spotbugs  |   0m 42s |  |  hadoop-project has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 44s |  |  hadoop-tools/hadoop-tools-dist has no data from spotbugs  |
| -1 :x: |  spotbugs  |   0m 57s | [/patch-spotbugs-hadoop-tools_hadoop-openstack.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4855/1/artifact/out/patch-spotbugs-hadoop-tools_hadoop-openstack.txt) |  hadoop-tools/hadoop-openstack cannot run convertXmlToText from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 44s |  |  hadoop-cloud-storage-project/hadoop-cloud-storage has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  23m 43s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 43s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |  18m 28s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |  45m  2s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 45s |  |  hadoop-tools-dist in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 44s |  |  hadoop-openstack in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 44s |  |  hadoop-cloud-storage in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 11s |  |  The patch does not generate ASF License warnings.  |
|  |   | 317m 15s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4855/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4855 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint markdownlint spotbugs checkstyle |
| uname | Linux 78d0d1b7e122 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / ccc51f87f6fbc143aed508f68bc3e7b511109f2a |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4855/1/testReport/ |
| Max. process+thread count | 2983 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common hadoop-tools/hadoop-distcp hadoop-tools/hadoop-tools-dist hadoop-tools/hadoop-openstack hadoop-cloud-storage-project/hadoop-cloud-storage U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4855/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 46s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  3s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  1s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  1s |  |  xmllint was not available.  |
| +0 :ok: |  markdownlint  |   0m  1s |  |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 39 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  15m  7s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  25m 32s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  23m 10s |  |  trunk passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  compile  |  20m 47s |  |  trunk passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  checkstyle  |   4m 12s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   7m 17s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   6m 52s |  |  trunk passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   5m 56s |  |  trunk passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +0 :ok: |  spotbugs  |   1m  8s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 55s |  |  branch/hadoop-tools/hadoop-tools-dist no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 54s |  |  branch/hadoop-cloud-storage-project/hadoop-cloud-storage no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  21m  4s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m  4s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  22m 19s |  |  the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javac  |  22m 19s |  |  root-jdkUbuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 generated 0 new + 2843 unchanged - 10 fixed = 2843 total (was 2853)  |
| +1 :green_heart: |  compile  |  20m 39s |  |  the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |  20m 39s |  |  root-jdkPrivateBuild-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 generated 0 new + 2643 unchanged - 7 fixed = 2643 total (was 2650)  |
| -1 :x: |  blanks  |   0m  0s | [/blanks-eol.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4855/2/artifact/out/blanks-eol.txt) |  The patch has 1 line(s) that end in blanks. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  checkstyle  |   4m 11s |  |  root: The patch generated 0 new + 1 unchanged - 473 fixed = 1 total (was 474)  |
| +1 :green_heart: |  mvnsite  |   7m  5s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 54s |  |  hadoop-project in the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04.  |
| +1 :green_heart: |  javadoc  |   1m 22s |  |  hadoop-common in the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04.  |
| +1 :green_heart: |  javadoc  |   1m 11s |  |  hadoop-distcp in the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04.  |
| +1 :green_heart: |  javadoc  |   0m 53s |  |  hadoop-tools-dist in the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04.  |
| +1 :green_heart: |  javadoc  |   0m 54s |  |  hadoop-tools_hadoop-openstack-jdkUbuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 generated 0 new + 0 unchanged - 22 fixed = 0 total (was 22)  |
| +1 :green_heart: |  javadoc  |   1m  0s |  |  hadoop-cloud-storage in the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04.  |
| +1 :green_heart: |  javadoc  |   0m 59s |  |  hadoop-project in the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07.  |
| +1 :green_heart: |  javadoc  |   1m  8s |  |  hadoop-common in the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07.  |
| +1 :green_heart: |  javadoc  |   0m 55s |  |  hadoop-distcp in the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07.  |
| +1 :green_heart: |  javadoc  |   0m 50s |  |  hadoop-tools-dist in the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07.  |
| +1 :green_heart: |  javadoc  |   0m 50s |  |  hadoop-tools_hadoop-openstack-jdkPrivateBuild-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 generated 0 new + 0 unchanged - 22 fixed = 0 total (was 22)  |
| +1 :green_heart: |  javadoc  |   1m  6s |  |  hadoop-cloud-storage in the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07.  |
| +0 :ok: |  spotbugs  |   0m 51s |  |  hadoop-project has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 51s |  |  hadoop-tools/hadoop-tools-dist has no data from spotbugs  |
| -1 :x: |  spotbugs  |   1m  6s | [/patch-spotbugs-hadoop-tools_hadoop-openstack.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4855/2/artifact/out/patch-spotbugs-hadoop-tools_hadoop-openstack.txt) |  hadoop-tools/hadoop-openstack cannot run convertXmlToText from spotbugs  |
| +0 :ok: |  spotbugs  |   1m  0s |  |  hadoop-cloud-storage-project/hadoop-cloud-storage has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  21m 30s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 54s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |  18m 52s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |  21m 51s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  1s |  |  hadoop-tools-dist in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 52s |  |  hadoop-openstack in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 10s |  |  hadoop-cloud-storage in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 20s |  |  The patch does not generate ASF License warnings.  |
|  |   | 291m 16s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4855/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4855 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint markdownlint spotbugs checkstyle |
| uname | Linux 353fc27bef7a 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 7a6c2ac13085552d562cb4908884649e2f0d56ef |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4855/2/testReport/ |
| Max. process+thread count | 1263 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common hadoop-tools/hadoop-distcp hadoop-tools/hadoop-tools-dist hadoop-tools/hadoop-openstack hadoop-cloud-storage-project/hadoop-cloud-storage U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4855/2/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by aajisaka — APPROVED** [review]
+1

**Pull request merged**
