### PR TITLE
HDFS-15659. Set dfs.namenode.redundancy.considerLoad to false in MiniDFSCluster

### PR DESCRIPTION
**Pull request by amahussein**
## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  9s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |   |   0m  0s | [test4tests](test4tests) |  The patch appears to include 24 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  36m 14s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   1m 20s |  |  trunk passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  compile  |   1m 12s |  |  trunk passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  checkstyle  |   0m 56s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 20s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  19m 10s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 53s |  |  trunk passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javadoc  |   1m 21s |  |  trunk passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +0 :ok: |  spotbugs  |   3m 17s |  |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m 14s |  |  trunk passed  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 13s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 14s |  |  the patch passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javac  |   1m 14s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  7s |  |  the patch passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  javac  |   1m  7s |  |  the patch passed  |
| -0 :warning: |  checkstyle  |   0m 50s | [/diff-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/1/artifact/out/diff-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs-project/hadoop-hdfs: The patch generated 1 new + 585 unchanged - 0 fixed = 586 total (was 585)  |
| +1 :green_heart: |  mvnsite  |   1m 12s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  16m  9s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 48s |  |  the patch passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javadoc  |   1m 18s |  |  the patch passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  findbugs  |   3m 14s |  |  the patch passed  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 113m 41s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 37s |  |  The patch does not generate ASF License warnings.  |
|  |   | 209m 54s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.balancer.TestBalancer |
|   | hadoop.hdfs.TestRollingUpgrade |
|   | hadoop.hdfs.TestFileChecksum |
|   | hadoop.hdfs.TestErasureCodingMultipleRacks |
|   | hadoop.hdfs.server.mover.TestMover |
|   | hadoop.hdfs.server.namenode.TestNameNodeMXBean |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2435 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 53bb116c9604 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 2cb9e8f66a3 |
| Default Java | Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/1/testReport/ |
| Max. process+thread count | 2857 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/1/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.1.3 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m 11s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  7s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  pathlen  |   0m  0s | [/pathlen.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/2/artifact/out/pathlen.txt) |  The patch appears to contain 1 files with names longer than 240  |
| +1 :green_heart: |   |   0m  0s | [test4tests](test4tests) |  The patch appears to include 411 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 42s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  22m 55s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  21m 23s |  |  trunk passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  compile  |  18m 12s |  |  trunk passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  checkstyle  |   4m 28s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |  11m 39s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  32m 50s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   9m 29s |  |  trunk passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javadoc  |   9m 51s |  |  trunk passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +0 :ok: |  spotbugs  |   0m 44s |  |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   0m 26s |  |  branch/hadoop-hdfs-project/hadoop-hdfs-native-client no findbugs output file (findbugsXml.xml)  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 22s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   8m 51s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  23m  9s |  |  the patch passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javac  |  23m  9s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  19m  5s |  |  the patch passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  javac  |  19m  5s |  |  the patch passed  |
| -0 :warning: |  checkstyle  |   4m 27s | [/diff-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/2/artifact/out/diff-checkstyle-root.txt) |  root: The patch generated 180 new + 6030 unchanged - 40 fixed = 6210 total (was 6070)  |
| +1 :green_heart: |  mvnsite  |  11m 54s |  |  the patch passed  |
| -1 :x: |  whitespace  |   0m  0s | [/whitespace-tabs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/2/artifact/out/whitespace-tabs.txt) |  The patch 2 line(s) with tabs.  |
| +1 :green_heart: |  shadedclient  |  16m 43s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   9m 27s |  |  the patch passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javadoc  |  10m 23s |  |  the patch passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +0 :ok: |  findbugs  |   0m 27s |  |  hadoop-hdfs-project/hadoop-hdfs-native-client has no data from findbugs  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 121m 56s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/2/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   8m 36s |  |  hadoop-hdfs-native-client in the patch passed.  |
| -1 :x: |  unit  |  10m 21s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs-rbf.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/2/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs-rbf.txt) |  hadoop-hdfs-rbf in the patch passed.  |
| -1 :x: |  unit  | 109m 12s | [/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/2/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt) |  hadoop-yarn-server-resourcemanager in the patch passed.  |
| +1 :green_heart: |  unit  |  26m 46s |  |  hadoop-yarn-client in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 17s |  |  hadoop-yarn-server-timeline-pluginstorage in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 48s |  |  hadoop-yarn-server-timelineservice-hbase-client in the patch passed.  |
| -1 :x: |  unit  |  25m 34s | [/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-applications_hadoop-yarn-applications-distributedshell.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/2/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-applications_hadoop-yarn-applications-distributedshell.txt) |  hadoop-yarn-applications-distributedshell in the patch passed.  |
| +1 :green_heart: |  unit  |   7m  7s |  |  hadoop-mapreduce-client-core in the patch passed.  |
| +1 :green_heart: |  unit  |   8m 24s |  |  hadoop-mapreduce-client-app in the patch passed.  |
| +1 :green_heart: |  unit  |   4m  0s |  |  hadoop-mapreduce-client-hs in the patch passed.  |
| +1 :green_heart: |  unit  |  19m 43s |  |  hadoop-yarn-services-core in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 12s |  |  hadoop-yarn-services-api in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 47s |  |  hadoop-mapreduce-client-uploader in the patch passed.  |
| +1 :green_heart: |  unit  |  12m 54s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 44s |  |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 46s |  |  hadoop-fs2img in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 12s |  |  The patch does not generate ASF License warnings.  |
|  |   | 653m 22s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.blockmanagement.TestBlockTokenWithDFSStriped |
|   | hadoop.hdfs.server.balancer.TestBalancerWithMultipleNameNodes |
|   | hadoop.hdfs.server.balancer.TestBalancer |
|   | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |
|   | hadoop.hdfs.TestFileChecksumCompositeCrc |
|   | hadoop.hdfs.TestGetFileChecksum |
|   | hadoop.hdfs.server.federation.router.TestRouterRpcMultiDestination |
|   | hadoop.yarn.server.resourcemanager.security.TestDelegationTokenRenewer |
|   | hadoop.yarn.applications.distributedshell.TestDistributedShell |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2435 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 4c025c4eda6a 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 7e52c0975f7 |
| Default Java | Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/2/testReport/ |
| Max. process+thread count | 3555 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-native-client hadoop-hdfs-project/hadoop-hdfs-rbf hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timeline-pluginstorage hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase/hadoop-yarn-server-timelineservice-hbase-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-hs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services/hadoop-yarn-services-core hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services/hadoop-yarn-services-api hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-uploader hadoop-tools/hadoop-distcp hadoop-tools/hadoop-aws hadoop-tools/hadoop-fs2img U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/2/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.1.3 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by ayushtkn — COMMENTED** [review]
Thanx @amahussein for taking this up.
I thought it would be just change in the `MiniDfsCluster`, where we can make this ignore load conf set, and may be add an additional flag, which enables it for the tests, which requires it to be true.
Can you explain me the reason of change in `HdfsConfiguration`?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m 19s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  6s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  pathlen  |   0m  0s | [/pathlen.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/3/artifact/out/pathlen.txt) |  The patch appears to contain 1 files with names longer than 240  |
| +1 :green_heart: |   |   0m  0s | [test4tests](test4tests) |  The patch appears to include 425 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 20s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  23m 12s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  21m 31s |  |  trunk passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  compile  |  18m  5s |  |  trunk passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  checkstyle  |   4m 35s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |  12m  9s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  33m 38s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   9m 54s |  |  trunk passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javadoc  |  10m 28s |  |  trunk passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +0 :ok: |  spotbugs  |   0m 44s |  |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   0m 27s |  |  branch/hadoop-hdfs-project/hadoop-hdfs-native-client no findbugs output file (findbugsXml.xml)  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 23s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   8m 59s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  20m 47s |  |  the patch passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javac  |  20m 47s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m  5s |  |  the patch passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  javac  |  18m  5s |  |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   4m 26s |  |  root: The patch generated 0 new + 6131 unchanged - 84 fixed = 6131 total (was 6215)  |
| +1 :green_heart: |  mvnsite  |  12m  7s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  16m 35s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   9m 57s |  |  the patch passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javadoc  |  10m 26s |  |  the patch passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +0 :ok: |  findbugs  |   0m 27s |  |  hadoop-hdfs-project/hadoop-hdfs-native-client has no data from findbugs  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 132m 46s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/3/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   9m 32s |  |  hadoop-hdfs-native-client in the patch passed.  |
| +1 :green_heart: |  unit  |  11m  3s |  |  hadoop-hdfs-rbf in the patch passed.  |
| -1 :x: |  unit  | 101m 54s | [/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/3/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt) |  hadoop-yarn-server-resourcemanager in the patch passed.  |
| +1 :green_heart: |  unit  |  27m 48s |  |  hadoop-yarn-client in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 15s |  |  hadoop-yarn-server-timeline-pluginstorage in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 46s |  |  hadoop-yarn-server-timelineservice-hbase-client in the patch passed.  |
| -1 :x: |  unit  |  25m 31s | [/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-applications_hadoop-yarn-applications-distributedshell.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/3/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-applications_hadoop-yarn-applications-distributedshell.txt) |  hadoop-yarn-applications-distributedshell in the patch passed.  |
| +1 :green_heart: |  unit  |   7m  9s |  |  hadoop-mapreduce-client-core in the patch passed.  |
| +1 :green_heart: |  unit  |   8m 23s |  |  hadoop-mapreduce-client-app in the patch passed.  |
| +1 :green_heart: |  unit  |   4m  3s |  |  hadoop-mapreduce-client-hs in the patch passed.  |
| +1 :green_heart: |  unit  |  19m 55s |  |  hadoop-yarn-services-core in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 15s |  |  hadoop-yarn-services-api in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 46s |  |  hadoop-mapreduce-client-uploader in the patch passed.  |
| +1 :green_heart: |  unit  |   6m 21s |  |  hadoop-streaming in the patch passed.  |
| +1 :green_heart: |  unit  |  12m 45s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 44s |  |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 47s |  |  hadoop-fs2img in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  6s |  |  The patch does not generate ASF License warnings.  |
|  |   | 660m 31s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.balancer.TestBalancerWithMultipleNameNodes |
|   | hadoop.hdfs.server.namenode.ha.TestHAMetrics |
|   | hadoop.hdfs.server.namenode.ha.TestStandbyCheckpoints |
|   | hadoop.hdfs.server.namenode.ha.TestBootstrapAliasmap |
|   | hadoop.hdfs.server.blockmanagement.TestReplicationPolicyConsiderLoad |
|   | hadoop.yarn.server.resourcemanager.scheduler.capacity.TestCapacityScheduler |
|   | hadoop.yarn.applications.distributedshell.TestDistributedShell |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2435 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux dac86f44498e 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 4b312810ae0 |
| Default Java | Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/3/testReport/ |
| Max. process+thread count | 2687 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-native-client hadoop-hdfs-project/hadoop-hdfs-rbf hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timeline-pluginstorage hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase/hadoop-yarn-server-timelineservice-hbase-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-hs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services/hadoop-yarn-services-core hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services/hadoop-yarn-services-api hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-uploader hadoop-tools/hadoop-streaming hadoop-tools/hadoop-distcp hadoop-tools/hadoop-aws hadoop-tools/hadoop-fs2img U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2435/3/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.1.3 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by amahussein** [comment]
> Thanx @amahussein for taking this up.
> I thought it would be just change in the `MiniDfsCluster`, where we can make this ignore load conf set, and may be add an additional flag, which enables it for the tests, which requires it to be true.
> Can you explain me the reason of change in `HdfsConfiguration`?

Thanks @ayushtkn for taking a look at the patch.
I did not change the `HdfsConfiguration`. I added two methods `DFSTestUtil.newHDFSConfiguration()` and `DFSTestUtil.newConfiguration()`. Then inside Test code, I replaced all calls of `new Configurations()` and `new HDFSConfiguration()`.
This implementation maintains the same flow adopted in all the Junit tests. 1- Create a new configuration Object; 2- Set the configuration needed for the test; 3- pass the configuration to MiniDFSCluster builder.
Overriding the value inside the MiniDFSCluster breaks that common sequence.

My intuition was that setting this flag in the MiniDFSCluster:

- may not work on the long run when, later, this flag needs to be enabled on the cluster.
- overriding the flag in the miniDFSCluster may confuse developers who may not expect the flag to be overriden during the initialization of the cluster.
- design wise, this implementation maintains the concept of OOP with `newConfiguration()` and `newHDFSConfiguration()` doing the construction and the default initialization of the configuration.

Let me know WDYT.

**Comment by amahussein** [comment]
@ayushtkn let me know if you are ok with my reasoning. Then I will take a look at the Junits to see if they broke because of my changes.

**Comment by ayushtkn** [comment]
This change actually is leading to a lot of changes, though that is straightforward, but touching all the testcases....I think I have hard feelings for it(Folks would bug us, if that test fails for any other reason too). If in any case we want to go with the present approach I think other folks should also consider these many changes necessary. More over most of the people would not know or care to bother they have to use new configuration that you have introduced and they would directly spawn up a MiniDfsCluster, Thus in long run we might land up at the same problem, and again we have to to do this same exercise.

If we just enable it in `MiniDfsCluster`, the change would be minimal and we can provide a flag, if enabled the config won't be bothered. I won't say the current approach is wrong in any way. It is completely correct, there can be multiple ways to do one thing. Just that I prefer keeping it in `MiniDfsCluster`, That was something the Jira tittle also......

**Comment by amahussein** [comment]
> This change actually is leading to a lot of changes, though that is straightforward, but touching all the testcases....I think I have hard feelings for it(Folks would bug us, if that test fails for any other reason too). If in any case we want to go with the present approach I think other folks should also consider these many changes necessary. More over most of the people would not know or care to bother they have to use new configuration that you have introduced and they would directly spawn up a MiniDfsCluster, Thus in long run we might land up at the same problem, and again we have to to do this same exercise.
> 
> If we just enable it in `MiniDfsCluster`, the change would be minimal and we can provide a flag, if enabled the config won't be bothered. I won't say the current approach is wrong in any way. It is completely correct, there can be multiple ways to do one thing. Just that I prefer keeping it in `MiniDfsCluster`, That was something the Jira tittle also......

This is a good perspective. Taking into consideration the current stability of Yetus, your approach should be wiser for the time being.
We can always work on refactoring later when things are more stable.

I will make another branch with the easy simple approach.
Thanks @ayushtkn , I appreciate your feedback.

**Comment by amahussein** [comment]
closing the PR, favoring a more straightforward solution.

**Pull request closed without merging**
