### PR TITLE
[HDFS-15786] - Minor improvement use isEmpty

### PR DESCRIPTION
**Pull request by arturobernalg**
## NOTICE

Use isEmpty instead size() > o.
size() can be O(1) or O(N), depending on the data structure; .isEmpty() is never O(N).
No need new test. It's just improvement

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  35m 48s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |   |   0m  0s | [test4tests](test4tests) |  The patch appears to include 11 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 20s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  34m 13s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  20m  5s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  compile  |  17m 27s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  checkstyle  |   3m 27s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |  19m 12s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  38m 36s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |  16m 24s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |  17m 18s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +0 :ok: |  spotbugs  |   0m 54s |  |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |  28m 11s |  |  trunk passed  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 29s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  12m 26s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 33s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javac  |  19m 33s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 23s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  javac  |  17m 23s |  |  the patch passed  |
| -0 :warning: |  checkstyle  |   3m 22s | [/diff-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/1/artifact/out/diff-checkstyle-root.txt) |  root: The patch generated 8 new + 1849 unchanged - 9 fixed = 1857 total (was 1858)  |
| +1 :green_heart: |  mvnsite  |  18m 44s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  16m 55s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |  16m 16s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |  17m 20s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  findbugs  |  31m 33s |  |  the patch passed  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   3m 24s |  |  hadoop-auth in the patch passed.  |
| +1 :green_heart: |  unit  |   9m 43s |  |  hadoop-common in the patch passed.  |
| -1 :x: |  unit  | 100m 29s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 49s |  |  hadoop-hdfs-httpfs in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 31s |  |  hadoop-yarn-common in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 12s |  |  hadoop-yarn-server-common in the patch passed.  |
| +1 :green_heart: |  unit  |   4m  3s |  |  hadoop-yarn-server-applicationhistoryservice in the patch passed.  |
| -1 :x: |  unit  |  94m 12s | [/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/1/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt) |  hadoop-yarn-server-resourcemanager in the patch passed.  |
| +1 :green_heart: |  unit  |  22m 57s |  |  hadoop-yarn-server-nodemanager in the patch passed.  |
| +1 :green_heart: |  unit  |   7m 20s |  |  hadoop-mapreduce-client-core in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 30s |  |  hadoop-mapreduce-client-common in the patch passed.  |
| +1 :green_heart: |  unit  |   9m 13s |  |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  0s |  |  hadoop-yarn-server-timelineservice-hbase-common in the patch passed.  |
| +1 :green_heart: |  unit  |  22m 42s |  |  hadoop-yarn-applications-distributedshell in the patch passed.  |
| +1 :green_heart: |  unit  |   6m 50s |  |  hadoop-streaming in the patch passed.  |
| -1 :x: |  unit  |   0m 57s | [/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-infra.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/1/artifact/out/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-infra.txt) |  hadoop-dynamometer-infra in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 58s |  |  hadoop-rumen in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  2s |  |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 53s |  |  hadoop-aliyun in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 20s |  |  hadoop-azure-datalake in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 51s |  |  hadoop-cos in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 51s |  |  hadoop-huaweicloud in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  7s |  |  The patch does not generate ASF License warnings.  |
|  |   | 676m 54s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.balancer.TestBalancer |
|   | hadoop.hdfs.TestMaintenanceState |
|   | hadoop.hdfs.server.blockmanagement.TestBlockTokenWithDFSStriped |
|   | hadoop.hdfs.server.namenode.ha.TestUpdateBlockTailing |
|   | hadoop.hdfs.server.namenode.TestDecommissioningStatusWithBackoffMonitor |
|   | hadoop.yarn.server.resourcemanager.security.TestDelegationTokenRenewer |
|   | hadoop.tools.dynamometer.TestDynamometerInfra |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2643 |
| JIRA Issue | HDFS-15786 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux df9c3665479d 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 91d4ba57c5b |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/1/testReport/ |
| Max. process+thread count | 4408 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-httpfs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-common hadoop-hdfs-project/hadoop-hdfs-rbf hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase/hadoop-yarn-server-timelineservice-hbase-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell hadoop-tools/hadoop-streaming hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-infra hadoop-tools/hadoop-rumen hadoop-tools/hadoop-azure hadoop-tools/hadoop-aliyun hadoop-tools/hadoop-azure-datalake hadoop-cloud-storage-project/hadoop-cos hadoop-cloud-storage-project/hadoop-huaweicloud U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/1/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.0.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 31s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |   |   0m  0s | [test4tests](test4tests) |  The patch appears to include 11 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  14m  1s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  25m 33s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  28m 33s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  compile  |  22m 22s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  checkstyle  |   3m 26s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |  18m  3s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  37m 18s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |  15m 19s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |  16m 10s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +0 :ok: |  spotbugs  |   0m 57s |  |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |  27m 56s |  |  trunk passed  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  14m 32s |  |  the patch passed  |
| -1 :x: |  compile  |   2m 13s | [/patch-compile-root-jdkUbuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-compile-root-jdkUbuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04.txt) |  root in the patch failed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04.  |
| -1 :x: |  javac  |   2m 14s | [/patch-compile-root-jdkUbuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-compile-root-jdkUbuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04.txt) |  root in the patch failed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04.  |
| -1 :x: |  compile  |   0m 25s | [/patch-compile-root-jdkPrivateBuild-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-compile-root-jdkPrivateBuild-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01.txt) |  root in the patch failed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01.  |
| -1 :x: |  javac  |   0m 25s | [/patch-compile-root-jdkPrivateBuild-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-compile-root-jdkPrivateBuild-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01.txt) |  root in the patch failed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01.  |
| -0 :warning: |  checkstyle  |   0m 23s | [/buildtool-patch-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/buildtool-patch-checkstyle-root.txt) |  The patch fails to run checkstyle in root  |
| -1 :x: |  mvnsite  |   0m 24s | [/patch-mvnsite-hadoop-common-project_hadoop-auth.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-common-project_hadoop-auth.txt) |  hadoop-auth in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 25s | [/patch-mvnsite-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-common-project_hadoop-common.txt) |  hadoop-common in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 25s | [/patch-mvnsite-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 24s | [/patch-mvnsite-hadoop-hdfs-project_hadoop-hdfs-httpfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-hdfs-project_hadoop-hdfs-httpfs.txt) |  hadoop-hdfs-httpfs in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 24s | [/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-common.txt) |  hadoop-yarn-common in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 25s | [/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-common.txt) |  hadoop-yarn-server-common in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 24s | [/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-applicationhistoryservice.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-applicationhistoryservice.txt) |  hadoop-yarn-server-applicationhistoryservice in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 24s | [/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt) |  hadoop-yarn-server-resourcemanager in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 25s | [/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-nodemanager.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-nodemanager.txt) |  hadoop-yarn-server-nodemanager in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 25s | [/patch-mvnsite-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-core.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-core.txt) |  hadoop-mapreduce-client-core in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 25s | [/patch-mvnsite-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-common.txt) |  hadoop-mapreduce-client-common in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 25s | [/patch-mvnsite-hadoop-hdfs-project_hadoop-hdfs-rbf.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-hdfs-project_hadoop-hdfs-rbf.txt) |  hadoop-hdfs-rbf in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 26s | [/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-timelineservice-hbase_hadoop-yarn-server-timelineservice-hbase-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-timelineservice-hbase_hadoop-yarn-server-timelineservice-hbase-common.txt) |  hadoop-yarn-server-timelineservice-hbase-common in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 25s | [/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-applications_hadoop-yarn-applications-distributedshell.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-applications_hadoop-yarn-applications-distributedshell.txt) |  hadoop-yarn-applications-distributedshell in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 25s | [/patch-mvnsite-hadoop-tools_hadoop-streaming.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-tools_hadoop-streaming.txt) |  hadoop-streaming in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 25s | [/patch-mvnsite-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-infra.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-infra.txt) |  hadoop-dynamometer-infra in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 24s | [/patch-mvnsite-hadoop-tools_hadoop-rumen.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-tools_hadoop-rumen.txt) |  hadoop-rumen in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 26s | [/patch-mvnsite-hadoop-tools_hadoop-azure.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-tools_hadoop-azure.txt) |  hadoop-azure in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 24s | [/patch-mvnsite-hadoop-tools_hadoop-aliyun.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-tools_hadoop-aliyun.txt) |  hadoop-aliyun in the patch failed.  |
| -1 :x: |  mvnsite  |   0m 25s | [/patch-mvnsite-hadoop-tools_hadoop-azure-datalake.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-mvnsite-hadoop-tools_hadoop-azure-datalake.txt) |  hadoop-azure-datalake in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  19m 28s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |  10m 35s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |  11m  8s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  findbugs  |  25m 33s |  |  the patch passed  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   3m  7s |  |  hadoop-auth in the patch passed.  |
| +1 :green_heart: |  unit  |   9m 25s |  |  hadoop-common in the patch passed.  |
| -1 :x: |  unit  |  99m 27s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 30s |  |  hadoop-hdfs-httpfs in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 15s |  |  hadoop-yarn-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 54s |  |  hadoop-yarn-server-common in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 47s |  |  hadoop-yarn-server-applicationhistoryservice in the patch passed.  |
| +1 :green_heart: |  unit  |  94m  3s |  |  hadoop-yarn-server-resourcemanager in the patch passed.  |
| +1 :green_heart: |  unit  |  22m 32s |  |  hadoop-yarn-server-nodemanager in the patch passed.  |
| +1 :green_heart: |  unit  |   7m  3s |  |  hadoop-mapreduce-client-core in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 12s |  |  hadoop-mapreduce-client-common in the patch passed.  |
| +1 :green_heart: |  unit  |   8m 51s |  |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 40s |  |  hadoop-yarn-server-timelineservice-hbase-common in the patch passed.  |
| +1 :green_heart: |  unit  |  22m 22s |  |  hadoop-yarn-applications-distributedshell in the patch passed.  |
| +1 :green_heart: |  unit  |   6m 33s |  |  hadoop-streaming in the patch passed.  |
| -1 :x: |  unit  |   0m 39s | [/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-infra.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-infra.txt) |  hadoop-dynamometer-infra in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 42s |  |  hadoop-rumen in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 42s |  |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 32s |  |  hadoop-aliyun in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  7s |  |  hadoop-azure-datalake in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 34s |  |  hadoop-cos in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 35s |  |  hadoop-huaweicloud in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 48s |  |  The patch does not generate ASF License warnings.  |
|  |   | 586m 57s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |
|   | hadoop.tools.dynamometer.TestDynamometerInfra |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2643 |
| JIRA Issue | HDFS-15786 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux a78e61679238 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 91d4ba57c5b |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/testReport/ |
| Max. process+thread count | 4311 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-httpfs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-common hadoop-hdfs-project/hadoop-hdfs-rbf hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase/hadoop-yarn-server-timelineservice-hbase-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell hadoop-tools/hadoop-streaming hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-infra hadoop-tools/hadoop-rumen hadoop-tools/hadoop-azure hadoop-tools/hadoop-aliyun hadoop-tools/hadoop-azure-datalake hadoop-cloud-storage-project/hadoop-cos hadoop-cloud-storage-project/hadoop-huaweicloud U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2643/3/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.0.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by goiri** [comment]
Let's do a JIRA for HDFS, one for YARN and one for the rest.
Otherwise this will be massive.
Use this PR just for HDFS.

**Comment by arturobernalg** [comment]
> Let's do a JIRA for HDFS, one for YARN and one for the rest.
> Otherwise this will be massive.
> Use this PR just for HDFS.

Hi @goiri 

Agree. Thank you

**Pull request closed without merging**
