### PR TITLE
Hadoop-18519. Backport HDFS-15383 and HADOOP-17835 to branch-3.3

### PR DESCRIPTION
**Pull request by melissayou**
### Description of PR
As part of [HADOOP-18518](https://issues.apache.org/jira/browse/HADOOP-18518), this is the second PR to fix deprecation of PathChildrenCache/TreeCache in new ZK. It's a clean cherry pick from HDFS-15383 and HADOOP-17835. 

### How was this patch tested?
 `mvn clean install -Pdist -Dtar -DskipTests -Dmaven.javadoc.skip` build success

### For code changes:

- [X] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  10m 48s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  15m  3s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  24m  9s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m  1s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m 21s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   4m 15s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   3m 48s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   5m 47s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  26m  0s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 31s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 13s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 23s |  |  the patch passed  |
| -1 :x: |  javac  |  17m 23s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5112/1/artifact/out/results-compile-javac-root.txt) |  root generated 2 new + 1871 unchanged - 11 fixed = 1873 total (was 1882)  |
| -1 :x: |  blanks  |   0m  0s | [/blanks-eol.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5112/1/artifact/out/blanks-eol.txt) |  The patch has 5 line(s) that end in blanks. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| -0 :warning: |  checkstyle  |   3m  0s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5112/1/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 3 new + 18 unchanged - 26 fixed = 21 total (was 44)  |
| +1 :green_heart: |  mvnsite  |   4m  6s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   3m 35s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   6m  5s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  26m  8s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  18m  8s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 43s |  |  hadoop-registry in the patch passed.  |
| +1 :green_heart: |  unit  |  18m 12s |  |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 19s |  |  The patch does not generate ASF License warnings.  |
|  |   | 216m 44s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5112/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5112 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux ed203fb1fc91 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / d6a246deda6fdbe1bddce94558ed701734b806b5 |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5112/1/testReport/ |
| Max. process+thread count | 2053 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-hdfs-project/hadoop-hdfs-rbf U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5112/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  1s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  15m  8s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  24m 43s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m  9s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m  8s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   4m  8s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   3m 47s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   5m 57s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  26m  0s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 32s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 11s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 33s |  |  the patch passed  |
| -1 :x: |  javac  |  17m 33s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5112/2/artifact/out/results-compile-javac-root.txt) |  root generated 2 new + 1871 unchanged - 11 fixed = 1873 total (was 1882)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   2m 53s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5112/2/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 3 new + 18 unchanged - 26 fixed = 21 total (was 44)  |
| +1 :green_heart: |  mvnsite  |   4m 22s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   3m 48s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   6m 20s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  26m 27s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  18m 25s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 56s |  |  hadoop-registry in the patch passed.  |
| +1 :green_heart: |  unit  |  20m 19s |  |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 29s |  |  The patch does not generate ASF License warnings.  |
|  |   | 211m 35s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5112/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5112 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 18e8f3c6eac5 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / a989b86be03e31f48f0e8b8b08e177eb2029a0f9 |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5112/2/testReport/ |
| Max. process+thread count | 2060 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-hdfs-project/hadoop-hdfs-rbf U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5112/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by virajith** [comment]
Thanks for the backport @melissayou . The changes look good to me - I expect the deprecated method will be addressed by [HADOOP-18520](https://issues.apache.org/jira/browse/HADOOP-18520). The other failures exist in trunk as well - fixing the checkstyles will not make this a clean cherry-pick.

**Comment by virajith** [comment]
I'll merge this in the next hour.

**Pull request merged**
