### PR TITLE
HADOOP-17394. [JDK 11] mvn package -Pdocs fails

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/HADOOP-17394

Manually tested. The following command passed with AdoptOpenJDK 11.0.9:
```
$ mvn clean package -Pdist,docs -DskipTests -DskipShade
```

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  24m 19s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 26s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  37m 25s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  26m 38s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  compile  |  22m  0s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  mvnsite  |   9m 49s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  | 128m 33s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   6m  2s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   4m 59s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   8m 44s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  25m 37s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javac  |  25m 37s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  22m 32s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  javac  |  22m 32s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   9m 49s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  7s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  18m  4s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   5m 31s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   5m 26s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 15s |  |  hadoop-project-dist in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 31s |  |  hadoop-auth in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 16s |  |  hadoop-hdfs-httpfs in the patch passed.  |
| -1 :x: |  unit  | 232m 13s | [/patch-unit-hadoop-yarn-project_hadoop-yarn.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2488/1/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn.txt) |  hadoop-yarn in the patch passed.  |
| +1 :green_heart: |  unit  | 152m 19s |  |  hadoop-mapreduce-client in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  0s |  |  The patch does not generate ASF License warnings.  |
|  |   | 659m  1s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.yarn.server.router.webapp.TestRouterWebServicesREST |
|   | hadoop.yarn.server.resourcemanager.security.TestDelegationTokenRenewer |
|   | hadoop.yarn.applications.distributedshell.TestDistributedShell |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2488/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2488 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux cbd1d3d77154 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / c4ba0ab7dfc |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2488/1/testReport/ |
| Max. process+thread count | 1200 (vs. ulimit of 5500) |
| modules | C: hadoop-project-dist hadoop-common-project/hadoop-auth hadoop-hdfs-project/hadoop-hdfs-httpfs hadoop-yarn-project/hadoop-yarn hadoop-mapreduce-project/hadoop-mapreduce-client U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2488/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
The failed tests are not related to the patch:
- TestRouterWebServicesREST: https://issues.apache.org/jira/browse/YARN-10499
- TestDelegationTokenRenewer: https://issues.apache.org/jira/browse/YARN-10500
- TestDistributedShell: https://issues.apache.org/jira/browse/YARN-9587

**Review by tasanuma — APPROVED** [review]
LGTM, +1. Thanks for your work.

**Comment by aajisaka** [comment]
Thank you @tasanuma !

**Pull request merged**
