### PR TITLE
HADOOP-18354. Upgrade reload4j to 1.22.2 due to XXE vulnerability (#4607).

### PR DESCRIPTION
**Pull request by steveloughran**
Contributed by PJ Fanning.

### CODE REVIEW

**Comment by steveloughran** [comment]
#4607 on 3.3.4

**Review by jojochuang — APPROVED** [review]
+1 pending Jenkins.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 41s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  shelldocs  |   0m  1s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   5m  4s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  31m 24s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  compile  |  17m 53s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  mvnsite  |  25m  2s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  javadoc  |   8m 22s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  shadedclient  |  31m 17s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 35s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  21m 39s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 31s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  17m 31s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  20m 48s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   8m  2s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  32m 54s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 693m 26s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4635/1/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m 14s |  |  The patch does not generate ASF License warnings.  |
|  |   | 903m 24s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.yarn.csi.client.TestCsiClient |
|   | hadoop.yarn.applications.distributedshell.TestDistributedShell |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4635/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4635 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml shellcheck shelldocs |
| uname | Linux 781d416aff13 4.15.0-169-generic #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3.4 / 46ed9260f0ad62cf8f6cb0c8871244d1502d3c02 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4635/1/testReport/ |
| Max. process+thread count | 3556 (vs. ulimit of 5500) |
| modules | C: hadoop-project . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4635/1/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
manually merged and pushed up; closing this

**Pull request closed without merging**
