### PR TITLE
HADOOP-17939. Support building on `Apple Silicon`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### Description of PR

Since there is no `protoc` for `Apple Silicon` until 3.17.3, Apache Hadoop compilation fails to download it.
- https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.17.3/

This PR aims to support building on `Apple Silicon` by fallback to Intel x86_64 architecture in order to take advantage of MacOS Rosetta2.

### How was this patch tested?

Test on Apple M1 MacMini.

**BEFORE**
```
$ mvn compile
...
[INFO] --- protobuf-maven-plugin:0.5.1:compile (src-compile-protoc) @ hadoop-common ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Hadoop Main 3.4.0-SNAPSHOT:
[INFO]
[INFO] Apache Hadoop Main ................................. SUCCESS [  0.160 s]
[INFO] Apache Hadoop Build Tools .......................... SUCCESS [  0.517 s]
[INFO] Apache Hadoop Project POM .......................... SUCCESS [  0.292 s]
[INFO] Apache Hadoop Annotations .......................... SUCCESS [  0.392 s]
[INFO] Apache Hadoop Project Dist POM ..................... SUCCESS [  0.029 s]
[INFO] Apache Hadoop Assemblies ........................... SUCCESS [  0.028 s]
[INFO] Apache Hadoop Maven Plugins ........................ SUCCESS [  1.381 s]
[INFO] Apache Hadoop MiniKDC .............................. SUCCESS [  0.224 s]
[INFO] Apache Hadoop Auth ................................. SUCCESS [  1.018 s]
[INFO] Apache Hadoop Auth Examples ........................ SUCCESS [  0.143 s]
[INFO] Apache Hadoop Common ............................... FAILURE [  0.183 s]
[INFO] Apache Hadoop NFS .................................. SKIPPED
[INFO] Apache Hadoop KMS .................................. SKIPPED
[INFO] Apache Hadoop Registry ............................. SKIPPED
[INFO] Apache Hadoop Common Project ....................... SKIPPED
[INFO] Apache Hadoop HDFS Client .......................... SKIPPED
[INFO] Apache Hadoop HDFS ................................. SKIPPED
[INFO] Apache Hadoop HDFS Native Client ................... SKIPPED
[INFO] Apache Hadoop HttpFS ............................... SKIPPED
[INFO] Apache Hadoop HDFS-NFS ............................. SKIPPED
[INFO] Apache Hadoop YARN ................................. SKIPPED
[INFO] Apache Hadoop YARN API ............................. SKIPPED
[INFO] Apache Hadoop YARN Common .......................... SKIPPED
[INFO] Apache Hadoop YARN Server .......................... SKIPPED
[INFO] Apache Hadoop YARN Server Common ................... SKIPPED
[INFO] Apache Hadoop YARN ApplicationHistoryService ....... SKIPPED
[INFO] Apache Hadoop YARN Timeline Service ................ SKIPPED
[INFO] Apache Hadoop YARN Web Proxy ....................... SKIPPED
[INFO] Apache Hadoop YARN ResourceManager ................. SKIPPED
[INFO] Apache Hadoop YARN NodeManager ..................... SKIPPED
[INFO] Apache Hadoop YARN Server Tests .................... SKIPPED
[INFO] Apache Hadoop YARN Client .......................... SKIPPED
[INFO] Apache Hadoop MapReduce Client ..................... SKIPPED
[INFO] Apache Hadoop MapReduce Core ....................... SKIPPED
[INFO] Apache Hadoop MapReduce Common ..................... SKIPPED
[INFO] Apache Hadoop MapReduce Shuffle .................... SKIPPED
[INFO] Apache Hadoop MapReduce App ........................ SKIPPED
[INFO] Apache Hadoop MapReduce HistoryServer .............. SKIPPED
[INFO] Apache Hadoop MapReduce JobClient .................. SKIPPED
[INFO] Apache Hadoop Distributed Copy ..................... SKIPPED
[INFO] Apache Hadoop Mini-Cluster ......................... SKIPPED
[INFO] Apache Hadoop Federation Balance ................... SKIPPED
[INFO] Apache Hadoop HDFS-RBF ............................. SKIPPED
[INFO] Apache Hadoop HDFS Project ......................... SKIPPED
[INFO] Apache Hadoop YARN SharedCacheManager .............. SKIPPED
[INFO] Apache Hadoop YARN Timeline Plugin Storage ......... SKIPPED
[INFO] Apache Hadoop YARN TimelineService HBase Backend ... SKIPPED
[INFO] Apache Hadoop YARN TimelineService HBase Common .... SKIPPED
[INFO] Apache Hadoop YARN TimelineService HBase Client .... SKIPPED
[INFO] Apache Hadoop YARN TimelineService HBase Servers ... SKIPPED
[INFO] Apache Hadoop YARN TimelineService HBase Server 1.2  SKIPPED
[INFO] Apache Hadoop YARN TimelineService HBase tests ..... SKIPPED
[INFO] Apache Hadoop YARN Router .......................... SKIPPED
[INFO] Apache Hadoop YARN TimelineService DocumentStore ... SKIPPED
[INFO] Apache Hadoop YARN Applications .................... SKIPPED
[INFO] Apache Hadoop YARN DistributedShell ................ SKIPPED
[INFO] Apache Hadoop YARN Unmanaged Am Launcher ........... SKIPPED
[INFO] Apache Hadoop YARN Services ........................ SKIPPED
[INFO] Apache Hadoop YARN Services Core ................... SKIPPED
[INFO] Apache Hadoop YARN Services API .................... SKIPPED
[INFO] Apache Hadoop YARN Application Catalog ............. SKIPPED
[INFO] Apache Hadoop YARN Application Catalog Webapp ...... SKIPPED
[INFO] Apache Hadoop YARN Application Catalog Docker Image  SKIPPED
[INFO] Apache Hadoop YARN Application MaWo ................ SKIPPED
[INFO] Apache Hadoop YARN Application MaWo Core ........... SKIPPED
[INFO] Apache Hadoop YARN Site ............................ SKIPPED
[INFO] Apache Hadoop YARN Registry ........................ SKIPPED
[INFO] Apache Hadoop YARN UI .............................. SKIPPED
[INFO] Apache Hadoop YARN CSI ............................. SKIPPED
[INFO] Apache Hadoop YARN Project ......................... SKIPPED
[INFO] Apache Hadoop MapReduce HistoryServer Plugins ...... SKIPPED
[INFO] Apache Hadoop MapReduce NativeTask ................. SKIPPED
[INFO] Apache Hadoop MapReduce Uploader ................... SKIPPED
[INFO] Apache Hadoop MapReduce Examples ................... SKIPPED
[INFO] Apache Hadoop MapReduce ............................ SKIPPED
[INFO] Apache Hadoop MapReduce Streaming .................. SKIPPED
[INFO] Apache Hadoop Client Aggregator .................... SKIPPED
[INFO] Apache Hadoop Dynamometer Workload Simulator ....... SKIPPED
[INFO] Apache Hadoop Dynamometer Cluster Simulator ........ SKIPPED
[INFO] Apache Hadoop Dynamometer Block Listing Generator .. SKIPPED
[INFO] Apache Hadoop Dynamometer Dist ..................... SKIPPED
[INFO] Apache Hadoop Dynamometer .......................... SKIPPED
[INFO] Apache Hadoop Archives ............................. SKIPPED
[INFO] Apache Hadoop Archive Logs ......................... SKIPPED
[INFO] Apache Hadoop Rumen ................................ SKIPPED
[INFO] Apache Hadoop Gridmix .............................. SKIPPED
[INFO] Apache Hadoop Data Join ............................ SKIPPED
[INFO] Apache Hadoop Extras ............................... SKIPPED
[INFO] Apache Hadoop Pipes ................................ SKIPPED
[INFO] Apache Hadoop OpenStack support .................... SKIPPED
[INFO] Apache Hadoop Amazon Web Services support .......... SKIPPED
[INFO] Apache Hadoop Kafka Library support ................ SKIPPED
[INFO] Apache Hadoop Azure support ........................ SKIPPED
[INFO] Apache Hadoop Aliyun OSS support ................... SKIPPED
[INFO] Apache Hadoop Scheduler Load Simulator ............. SKIPPED
[INFO] Apache Hadoop Resource Estimator Service ........... SKIPPED
[INFO] Apache Hadoop Azure Data Lake support .............. SKIPPED
[INFO] Apache Hadoop Image Generation Tool ................ SKIPPED
[INFO] Apache Hadoop Tools Dist ........................... SKIPPED
[INFO] Apache Hadoop Tools ................................ SKIPPED
[INFO] Apache Hadoop Client API ........................... SKIPPED
[INFO] Apache Hadoop Client Runtime ....................... SKIPPED
[INFO] Apache Hadoop Client Packaging Invariants .......... SKIPPED
[INFO] Apache Hadoop Client Test Minicluster .............. SKIPPED
[INFO] Apache Hadoop Client Packaging Invariants for Test . SKIPPED
[INFO] Apache Hadoop Client Packaging Integration Tests ... SKIPPED
[INFO] Apache Hadoop Distribution ......................... SKIPPED
[INFO] Apache Hadoop Client Modules ....................... SKIPPED
[INFO] Apache Hadoop Tencent COS Support .................. SKIPPED
[INFO] Apache Hadoop OBS support .......................... SKIPPED
[INFO] Apache Hadoop Cloud Storage ........................ SKIPPED
[INFO] Apache Hadoop Cloud Storage Project ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.222 s
[INFO] Finished at: 2021-09-26T12:43:12-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.1:compile (src-compile-protoc) on project hadoop-common: Missing:
[ERROR] ----------
[ERROR] 1) com.google.protobuf:protoc:exe:osx-aarch_64:3.7.1
[ERROR]
[ERROR]   Try downloading the file manually from the project website.
[ERROR]
[ERROR]   Then, install it using the command:
[ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.7.1 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file
[ERROR]
[ERROR]   Alternatively, if you host your own repository you can deploy the file there:
[ERROR]       mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.7.1 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR]
[ERROR]   Path to dependency:
[ERROR]   	1) org.apache.hadoop:hadoop-common:jar:3.4.0-SNAPSHOT
[ERROR]   	2) com.google.protobuf:protoc:exe:osx-aarch_64:3.7.1
[ERROR]
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR]
[ERROR] for artifact:
[ERROR]   org.apache.hadoop:hadoop-common:jar:3.4.0-SNAPSHOT
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR]   apache.snapshots.https (https://repository.apache.org/content/repositories/snapshots, releases=true, snapshots=true),
[ERROR]   repository.jboss.org (https://repository.jboss.org/nexus/content/groups/public/, releases=true, snapshots=false),
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :hadoop-common
```

**AFTER**
```
$ $ mvn package -DskipTests
...
[INFO] Reactor Summary for Apache Hadoop Main 3.4.0-SNAPSHOT:
[INFO]
[INFO] Apache Hadoop Main ................................. SUCCESS [  0.524 s]
[INFO] Apache Hadoop Build Tools .......................... SUCCESS [  0.500 s]
[INFO] Apache Hadoop Project POM .......................... SUCCESS [  0.383 s]
[INFO] Apache Hadoop Annotations .......................... SUCCESS [  0.587 s]
[INFO] Apache Hadoop Project Dist POM ..................... SUCCESS [  0.027 s]
[INFO] Apache Hadoop Assemblies ........................... SUCCESS [  0.043 s]
[INFO] Apache Hadoop Maven Plugins ........................ SUCCESS [  1.258 s]
[INFO] Apache Hadoop MiniKDC .............................. SUCCESS [  0.243 s]
[INFO] Apache Hadoop Auth ................................. SUCCESS [  1.546 s]
[INFO] Apache Hadoop Auth Examples ........................ SUCCESS [  0.430 s]
[INFO] Apache Hadoop Common ............................... SUCCESS [ 11.563 s]
[INFO] Apache Hadoop NFS .................................. SUCCESS [  0.612 s]
[INFO] Apache Hadoop KMS .................................. SUCCESS [  0.691 s]
[INFO] Apache Hadoop Registry ............................. SUCCESS [  0.743 s]
[INFO] Apache Hadoop Common Project ....................... SUCCESS [  0.017 s]
[INFO] Apache Hadoop HDFS Client .......................... SUCCESS [  6.956 s]
[INFO] Apache Hadoop HDFS ................................. SUCCESS [ 11.962 s]
[INFO] Apache Hadoop HDFS Native Client ................... SUCCESS [  0.173 s]
[INFO] Apache Hadoop HttpFS ............................... SUCCESS [  0.828 s]
[INFO] Apache Hadoop HDFS-NFS ............................. SUCCESS [  0.366 s]
[INFO] Apache Hadoop YARN ................................. SUCCESS [  0.019 s]
[INFO] Apache Hadoop YARN API ............................. SUCCESS [  4.323 s]
[INFO] Apache Hadoop YARN Common .......................... SUCCESS [  3.226 s]
[INFO] Apache Hadoop YARN Server .......................... SUCCESS [  0.014 s]
[INFO] Apache Hadoop YARN Server Common ................... SUCCESS [  2.383 s]
[INFO] Apache Hadoop YARN ApplicationHistoryService ....... SUCCESS [  1.230 s]
[INFO] Apache Hadoop YARN Timeline Service ................ SUCCESS [  0.557 s]
[INFO] Apache Hadoop YARN Web Proxy ....................... SUCCESS [  0.462 s]
[INFO] Apache Hadoop YARN ResourceManager ................. SUCCESS [  5.786 s]
[INFO] Apache Hadoop YARN NodeManager ..................... SUCCESS [  3.174 s]
[INFO] Apache Hadoop YARN Server Tests .................... SUCCESS [  1.038 s]
[INFO] Apache Hadoop YARN Client .......................... SUCCESS [  1.509 s]
[INFO] Apache Hadoop MapReduce Client ..................... SUCCESS [  0.122 s]
[INFO] Apache Hadoop MapReduce Core ....................... SUCCESS [  1.932 s]
[INFO] Apache Hadoop MapReduce Common ..................... SUCCESS [  1.555 s]
[INFO] Apache Hadoop MapReduce Shuffle .................... SUCCESS [  1.115 s]
[INFO] Apache Hadoop MapReduce App ........................ SUCCESS [  1.395 s]
[INFO] Apache Hadoop MapReduce HistoryServer .............. SUCCESS [  0.832 s]
[INFO] Apache Hadoop MapReduce JobClient .................. SUCCESS [  1.643 s]
[INFO] Apache Hadoop Distributed Copy ..................... SUCCESS [  1.016 s]
[INFO] Apache Hadoop Mini-Cluster ......................... SUCCESS [  0.389 s]
[INFO] Apache Hadoop Federation Balance ................... SUCCESS [  0.441 s]
[INFO] Apache Hadoop HDFS-RBF ............................. SUCCESS [  2.282 s]
[INFO] Apache Hadoop HDFS Project ......................... SUCCESS [  0.013 s]
[INFO] Apache Hadoop YARN SharedCacheManager .............. SUCCESS [  0.436 s]
[INFO] Apache Hadoop YARN Timeline Plugin Storage ......... SUCCESS [  0.484 s]
[INFO] Apache Hadoop YARN TimelineService HBase Backend ... SUCCESS [  0.013 s]
[INFO] Apache Hadoop YARN TimelineService HBase Common .... SUCCESS [  0.579 s]
[INFO] Apache Hadoop YARN TimelineService HBase Client .... SUCCESS [  0.846 s]
[INFO] Apache Hadoop YARN TimelineService HBase Servers ... SUCCESS [  0.015 s]
[INFO] Apache Hadoop YARN TimelineService HBase Server 1.2  SUCCESS [  0.954 s]
[INFO] Apache Hadoop YARN TimelineService HBase tests ..... SUCCESS [  1.058 s]
[INFO] Apache Hadoop YARN Router .......................... SUCCESS [  0.668 s]
[INFO] Apache Hadoop YARN TimelineService DocumentStore ... SUCCESS [  0.387 s]
[INFO] Apache Hadoop YARN Applications .................... SUCCESS [  0.013 s]
[INFO] Apache Hadoop YARN DistributedShell ................ SUCCESS [  0.490 s]
[INFO] Apache Hadoop YARN Unmanaged Am Launcher ........... SUCCESS [  0.359 s]
[INFO] Apache Hadoop YARN Services ........................ SUCCESS [  0.015 s]
[INFO] Apache Hadoop YARN Services Core ................... SUCCESS [  1.580 s]
[INFO] Apache Hadoop YARN Services API .................... SUCCESS [  0.524 s]
[INFO] Apache Hadoop YARN Application Catalog ............. SUCCESS [  0.013 s]
[INFO] Apache Hadoop YARN Application Catalog Webapp ...... SUCCESS [ 18.729 s]
[INFO] Apache Hadoop YARN Application Catalog Docker Image  SUCCESS [  0.024 s]
[INFO] Apache Hadoop YARN Application MaWo ................ SUCCESS [  0.016 s]
[INFO] Apache Hadoop YARN Application MaWo Core ........... SUCCESS [  0.401 s]
[INFO] Apache Hadoop YARN Site ............................ SUCCESS [  0.016 s]
[INFO] Apache Hadoop YARN Registry ........................ SUCCESS [  0.205 s]
[INFO] Apache Hadoop YARN UI .............................. SUCCESS [  0.014 s]
[INFO] Apache Hadoop YARN CSI ............................. SUCCESS [  2.723 s]
[INFO] Apache Hadoop YARN Project ......................... SUCCESS [  0.405 s]
[INFO] Apache Hadoop MapReduce HistoryServer Plugins ...... SUCCESS [  0.311 s]
[INFO] Apache Hadoop MapReduce NativeTask ................. SUCCESS [  0.459 s]
[INFO] Apache Hadoop MapReduce Uploader ................... SUCCESS [  0.351 s]
[INFO] Apache Hadoop MapReduce Examples ................... SUCCESS [  0.494 s]
[INFO] Apache Hadoop MapReduce ............................ SUCCESS [  0.118 s]
[INFO] Apache Hadoop MapReduce Streaming .................. SUCCESS [  0.534 s]
[INFO] Apache Hadoop Client Aggregator .................... SUCCESS [  0.348 s]
[INFO] Apache Hadoop Dynamometer Workload Simulator ....... SUCCESS [  0.561 s]
[INFO] Apache Hadoop Dynamometer Cluster Simulator ........ SUCCESS [  0.563 s]
[INFO] Apache Hadoop Dynamometer Block Listing Generator .. SUCCESS [  0.393 s]
[INFO] Apache Hadoop Dynamometer Dist ..................... SUCCESS [  0.341 s]
[INFO] Apache Hadoop Dynamometer .......................... SUCCESS [  0.012 s]
[INFO] Apache Hadoop Archives ............................. SUCCESS [  0.270 s]
[INFO] Apache Hadoop Archive Logs ......................... SUCCESS [  0.321 s]
[INFO] Apache Hadoop Rumen ................................ SUCCESS [  0.549 s]
[INFO] Apache Hadoop Gridmix .............................. SUCCESS [  0.531 s]
[INFO] Apache Hadoop Data Join ............................ SUCCESS [  0.320 s]
[INFO] Apache Hadoop Extras ............................... SUCCESS [  0.351 s]
[INFO] Apache Hadoop Pipes ................................ SUCCESS [  0.013 s]
[INFO] Apache Hadoop OpenStack support .................... SUCCESS [  0.317 s]
[INFO] Apache Hadoop Amazon Web Services support .......... SUCCESS [  2.749 s]
[INFO] Apache Hadoop Kafka Library support ................ SUCCESS [  0.294 s]
[INFO] Apache Hadoop Azure support ........................ SUCCESS [  1.280 s]
[INFO] Apache Hadoop Aliyun OSS support ................... SUCCESS [  0.339 s]
[INFO] Apache Hadoop Scheduler Load Simulator ............. SUCCESS [  0.746 s]
[INFO] Apache Hadoop Resource Estimator Service ........... SUCCESS [  0.421 s]
[INFO] Apache Hadoop Azure Data Lake support .............. SUCCESS [  0.261 s]
[INFO] Apache Hadoop Image Generation Tool ................ SUCCESS [  0.356 s]
[INFO] Apache Hadoop Tools Dist ........................... SUCCESS [  0.301 s]
[INFO] Apache Hadoop Tools ................................ SUCCESS [  0.012 s]
[INFO] Apache Hadoop Client API ........................... SUCCESS [01:00 min]
[INFO] Apache Hadoop Client Runtime ....................... SUCCESS [01:08 min]
[INFO] Apache Hadoop Client Packaging Invariants .......... SUCCESS [  0.100 s]
[INFO] Apache Hadoop Client Test Minicluster .............. SUCCESS [01:52 min]
[INFO] Apache Hadoop Client Packaging Invariants for Test . SUCCESS [  0.072 s]
[INFO] Apache Hadoop Client Packaging Integration Tests ... SUCCESS [  0.025 s]
[INFO] Apache Hadoop Distribution ......................... SUCCESS [  0.114 s]
[INFO] Apache Hadoop Client Modules ....................... SUCCESS [  0.012 s]
[INFO] Apache Hadoop Tencent COS Support .................. SUCCESS [  0.292 s]
[INFO] Apache Hadoop OBS support .......................... SUCCESS [  0.499 s]
[INFO] Apache Hadoop Cloud Storage ........................ SUCCESS [  0.219 s]
[INFO] Apache Hadoop Cloud Storage Project ................ SUCCESS [  0.011 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:04 min
[INFO] Finished at: 2021-09-26T12:56:05-07:00
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @sunchao , @steveloughran

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 42s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  32m 13s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   0m 23s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |   0m 23s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  mvnsite  |   0m 28s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   0m 25s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   0m 23s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  shadedclient  |  52m 57s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 14s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 14s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |   0m 14s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 13s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |   0m 13s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 16s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 14s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   0m 15s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  shadedclient  |  19m 15s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 18s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 34s |  |  The patch does not generate ASF License warnings.  |
|  |   |  76m 32s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3486/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3486 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml |
| uname | Linux c835c5e0ac98 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 6eb8f5d62cf00197a304b6c3ea0cf66aba7f6b9e |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3486/1/testReport/ |
| Max. process+thread count | 752 (vs. ulimit of 5500) |
| modules | C: hadoop-project U: hadoop-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3486/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
hey, you're going to have to send me an M1-based laptop to test this :)

**Review by steveloughran — APPROVED** [review]
+1, approved.

I don't see it having any adverse consequences on x86 models, or go near anything else, and I'll believe you when you say you've tested it

**Comment by dongjoon-hyun** [comment]
Thank you, @steveloughran ! 😄

**Pull request merged**
