### PR TITLE
HDFS-16631. Enable dfs.datanode.lockmanager.trace In Test.

### PR DESCRIPTION
**Pull request by slfan1989**
JIRA:HDFS-16631. Enable dfs.datanode.lockmanager.trace In Test.

In Jira [HDFS-16600](https://issues.apache.org/jira/browse/HDFS-16600). Fix deadlock on DataNode side. We discussed the issue of deadlock, this is a very meaningful discussion, I was reading the log and found the following:

PR:https://github.com/apache/hadoop/pull/4367

```
2022-05-27 07:39:47,890 [Listener at localhost/36941] WARN datanode.DataSetLockManager (DataSetLockManager.java:lockLeakCheck(261)) -
 not open lock leak check func.
```

Looking at the code, I found that there is such a parameter:
```
<property>
    <name>dfs.datanode.lockmanager.trace</name>
    <value>false</value>
    <description>
      If this is true, after shut down datanode lock Manager will print all leak
      thread that not release by lock Manager. Only used for test or trace dead lock
      problem. In produce default set false, because it's have little performance loss.
    </description>
  </property> 
```

I think this parameter should be added in the test environment, so that if there is a DN deadlock, the cause can be quickly located.

If my understanding is correct, if a thread needs both read locks and write locks, if this parameter is true, relevant thread information can be printed.

### CODE REVIEW

**Comment by slfan1989** [comment]
@Hexiaoqiao @MingXiangLi @ZanderXu please help me review the code.

**Comment by MingXiangLi** [comment]
DataSetLockManager only print lock trace when invoke DataNode.shutdown() or dataSetLockManager.lockLeakCheck().So I doubt it will work in all UT.

**Comment by MingXiangLi** [comment]
Ans should we throw Exception ? Most of user will ignore if just print the log.

**Comment by slfan1989** [comment]
> DataSetLockManager only print lock trace when invoke DataNode.shutdown() or dataSetLockManager.lockLeakCheck().So I doubt it will work in all UT.

Thanks for the suggestion, I think this parameter can cover scenarios like HDFS-16600, DN shutdown will definitely be called in Junit Test, I personally feel that if there is an error in the junit test of DN and if we suspect a deadlock, we can see this print message.

**Comment by slfan1989** [comment]
> Ans should we throw Exception ? Most of user will ignore if just print the log.

If a thread obtains a read lock (write lock) and needs to obtain a write lock (read lock), will an exception be thrown directly?
My understanding is that once a deadlock occurs, the code will definitely report an error, and there is no need to throw an exception directly. I personally feel that printing is enough. of course, we can also throw exceptions directly.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 55s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  39m 16s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  61m 55s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 23s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  shadedclient  |  22m 19s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 28s |  |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 44s |  |  The patch does not generate ASF License warnings.  |
|  |   |  91m 20s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4438/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4438 |
| Optional Tests | dupname asflicense unit codespell detsecrets xmllint |
| uname | Linux cd4c75a4e6c9 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / a9933a117854461fbc1900ed6a2344e7b6d947f1 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4438/1/testReport/ |
| Max. process+thread count | 520 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4438/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ZanderXu** [comment]
@slfan1989 It's a good idea. But I personally feel that it would be nice to thrown exception directly in the test environment when there is a lock leak.

**Comment by slfan1989** [comment]
@MingXiangLi @ZanderXu @Hexiaoqiao Thanks for helping to review the code, can I make the following changes?

```
public void lockLeakCheck() throws Exception {
    if (!openLockTrace) {
      LOG.warn("not open lock leak check func");
      return;
    }
    if (threadCountMap.isEmpty()) {
      LOG.warn("all lock has release");
      return;
    }
    setLastException(new Exception("lock Leak"));
    threadCountMap.forEach((name, trackLog) -> trackLog.showLockMessage());
    // throw exception ?
    throw new Exception("lock Leak");
  }
```

**Comment by Hexiaoqiao** [comment]
From my side, I do not think enable lock trace only is good idea for tests as @MingXiangLi has mentioned above. The only INFO level log will not help to debug or test. IMO, if there are some cases we would like to cover and need to collect locks information, it is better to add some inject logic. FYI.

**Comment by slfan1989** [comment]
> From my side, I do not think enable lock trace only is good idea for tests as @MingXiangLi has mentioned above. The only INFO level log will not help to debug or test. IMO, if there are some cases we would like to cover and need to collect locks information, it is better to add some inject logic. FYI.

Thank you very much for your suggestion, I will think about how to collect lock information!

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 54s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  1s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  1s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  40m 27s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  62m 57s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 26s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  shadedclient  |  21m 45s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 26s |  |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 44s |  |  The patch does not generate ASF License warnings.  |
|  |   |  92m  8s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4438/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4438 |
| Optional Tests | dupname asflicense unit codespell detsecrets xmllint |
| uname | Linux e09f249c6203 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 438879f0d576fdb1e7f823b592daf3cfa0215d2a |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4438/2/testReport/ |
| Max. process+thread count | 522 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4438/2/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 53s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  39m 28s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  61m 49s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 25s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  shadedclient  |  21m 58s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 27s |  |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 45s |  |  The patch does not generate ASF License warnings.  |
|  |   |  91m 14s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4438/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4438 |
| Optional Tests | dupname asflicense unit codespell detsecrets xmllint |
| uname | Linux 2672a54c0019 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 30bf6edc6e886f5ec0c6bf24e62a0a5bce4e838a |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4438/3/testReport/ |
| Max. process+thread count | 550 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4438/3/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by slfan1989** [comment]
readLock
```
getVolume(final ExtendedBlock b)
getStoredBlock(String bpid, long blkid)
Set<? extends Replica> deepCopyReplica(String bpid)
getBlockInputStream(ExtendedBlock b, long seekOffset)
moveBlockAcrossStorage(ExtendedBlock block, StorageType targetStorageType, String targetStorageId)
moveBlockAcrossVolumes(ExtendedBlock block, FsVolumeSpi destination)
ReplicaHandler createRbw(StorageType storageType, String storageId, ExtendedBlock b, boolean allowLazyPersist)
Map<DatanodeStorage, BlockListAsLongs> getBlockReports(String bpid)
public List<ReplicaInfo> getFinalizedBlocks(String bpid)
public boolean contains(final ExtendedBlock block)
public String getReplicaString(String bpid, long blockId)
public long getReplicaVisibleLength(final ExtendedBlock block)
public BlockLocalPathInfo getBlockLocalPathInfo(ExtendedBlock block)
```

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 51s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  47m 25s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  69m 45s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 23s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  shadedclient  |  22m 31s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 26s |  |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 44s |  |  The patch does not generate ASF License warnings.  |
|  |   |  99m 33s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4438/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4438 |
| Optional Tests | dupname asflicense unit codespell detsecrets xmllint |
| uname | Linux f79c1a23757e 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 5dac9ee7e1a8bd62849eba4ec2813f5f8921bb87 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4438/4/testReport/ |
| Max. process+thread count | 524 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4438/4/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
