### PR TITLE
HDFS-15458. TestNameNodeRetryCacheMetrics fails intermittently

### PR DESCRIPTION
**Pull request by ferhui**
## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by ferhui** [comment]
- Create no HA cluster.

- Remove uselese client

- cluster.waitActive() is useless, it's in MiniDFSCluster#startDataNodes

**Comment by ferhui** [comment]
Failed tests are unrelated. TestNameNodeRetryCacheMetrics#testRetryCacheMetrics with the fix pass stably.
@goiri @ayushtkn Please review again. Thanks!

**Comment by ferhui** [comment]
Test result is https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2356/2/testReport/

**Comment by ferhui** [comment]
and https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2356/2/Yetus_20Report/

**Review by ayushtkn — APPROVED** [review]
LGTM

**Review by goiri — APPROVED** [review]

**Comment by ferhui** [comment]
@goiri @ayushtkn Could you please help to merge this? Because i don't have  no write access now. Thanks

**Pull request merged**
