### PR TITLE
HDDS-1448 : RatisPipelineProvider should only consider open pipeline …

### PR DESCRIPTION
**Pull request by avijayanhwx**
…while excluding dn for pipeline allocation.

While allocation pipelines, Ratis pipeline provider considers all the pipelines irrespective of the state of the pipeline. This can lead to case where all the datanodes are up but the pipelines are in closing state in SCM.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 24 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 61 | Maven dependency ordering for branch |
| +1 | mvninstall | 1035 | trunk passed |
| +1 | compile | 962 | trunk passed |
| +1 | checkstyle | 135 | trunk passed |
| +1 | mvnsite | 107 | trunk passed |
| +1 | shadedclient | 976 | branch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 50 | trunk passed |
| +1 | javadoc | 60 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 24 | Maven dependency ordering for patch |
| +1 | mvninstall | 64 | the patch passed |
| +1 | compile | 925 | the patch passed |
| +1 | javac | 925 | the patch passed |
| +1 | checkstyle | 139 | the patch passed |
| +1 | mvnsite | 88 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 685 | patch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 58 | the patch passed |
| +1 | javadoc | 66 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 117 | server-scm in the patch failed. |
| -1 | unit | 1289 | integration-test in the patch failed. |
| +1 | asflicense | 54 | The patch does not generate ASF License warnings. |
| | | 6953 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.scm.block.TestBlockManager |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |
|   | hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures |
|   | hadoop.ozone.client.rpc.TestCommitWatcher |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.hdds.scm.pipeline.TestSCMRestart |
|   | hadoop.hdds.scm.safemode.TestSCMSafeModeWithPipelineRules |
|   | hadoop.ozone.client.rpc.TestCloseContainerHandlingByClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-786/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/786 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux fb760c7a563b 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 7fbaa7d |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/1/artifact/out/patch-unit-hadoop-hdds_server-scm.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/1/artifact/out/patch-unit-hadoop-ozone_integration-test.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/1/testReport/ |
| Max. process+thread count | 5402 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/server-scm hadoop-ozone/integration-test U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by avijayanhwx** [comment]
We also have to add the pipelines in ALLOCATED state to the set of DNs being excluded. The reason is that when the SCMPipelineManager initializes the set of pipelines from the pipeline store (RocksDB) in the ALLOCATED state. Hence, when the background pipeline creator gets the current pipeline list for creating pipelines pro-actively, if we fail to exclude these "ALLOCATED" pipelines which may soon transition to "OPEN", we can end up creating duplicate pipelines in the same DN ring. 

If the ALLOCATED state becomes OPEN, then it remains a NO-Op and if it transitions to CLOSED, the background pipeline will automatically start using the DNs in the next creation. 

cc @mukul1987 / @nandakumar131 / @arp7 Can you comment if the above makes sense?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 31 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for branch |
| +1 | mvninstall | 410 | trunk passed |
| +1 | compile | 196 | trunk passed |
| +1 | checkstyle | 51 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 778 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 118 | trunk passed |
| 0 | spotbugs | 310 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 488 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for patch |
| +1 | mvninstall | 381 | the patch passed |
| +1 | compile | 194 | the patch passed |
| +1 | javac | 194 | the patch passed |
| -0 | checkstyle | 24 | hadoop-hdds: The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0) |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 614 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 123 | the patch passed |
| +1 | findbugs | 432 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 129 | hadoop-hdds in the patch failed. |
| -1 | unit | 688 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 36 | The patch does not generate ASF License warnings. |
| | | 4940 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.om.TestOzoneManager |
|   | hadoop.ozone.om.TestOzoneManagerRestInterface |
|   | hadoop.ozone.om.TestOMDbCheckpointServlet |
|   | hadoop.ozone.client.rpc.TestContainerStateMachineFailures |
|   | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.ozone.scm.TestXceiverClientMetrics |
|   | hadoop.ozone.TestMiniChaosOzoneCluster |
|   | hadoop.ozone.scm.TestGetCommittedBlockLengthAndPutKey |
|   | hadoop.ozone.ozShell.TestOzoneShell |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.container.common.statemachine.commandhandler.TestCloseContainerByPipeline |
|   | hadoop.hdds.scm.pipeline.TestNode2PipelineMap |
|   | hadoop.ozone.web.TestOzoneWebAccess |
|   | hadoop.ozone.scm.TestContainerSmallFile |
|   | hadoop.ozone.client.rpc.TestContainerStateMachine |
|   | hadoop.ozone.container.common.statemachine.commandhandler.TestCloseContainerHandler |
|   | hadoop.ozone.container.ozoneimpl.TestOzoneContainer |
|   | hadoop.hdds.scm.pipeline.TestSCMPipelineManager |
|   | hadoop.ozone.TestMiniOzoneCluster |
|   | hadoop.ozone.client.rpc.TestBlockOutputStream |
|   | hadoop.ozone.client.rpc.TestCommitWatcher |
|   | hadoop.ozone.ozShell.TestOzoneDatanodeShell |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.hdds.scm.safemode.TestSCMSafeModeWithPipelineRules |
|   | hadoop.ozone.scm.pipeline.TestSCMPipelineMetrics |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-786/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/786 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 40b3a335432a 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 7a3188d |
| Default Java | 1.8.0_191 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/2/artifact/out/diff-checkstyle-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/2/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/2/testReport/ |
| Max. process+thread count | 4041 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/server-scm hadoop-ozone/integration-test U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 33 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 72 | Maven dependency ordering for branch |
| +1 | mvninstall | 452 | trunk passed |
| +1 | compile | 209 | trunk passed |
| +1 | checkstyle | 48 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 819 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 127 | trunk passed |
| 0 | spotbugs | 251 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 449 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 28 | Maven dependency ordering for patch |
| +1 | mvninstall | 424 | the patch passed |
| +1 | compile | 210 | the patch passed |
| +1 | javac | 210 | the patch passed |
| +1 | checkstyle | 58 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 645 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 118 | the patch passed |
| +1 | findbugs | 433 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 128 | hadoop-hdds in the patch failed. |
| -1 | unit | 834 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 32 | The patch does not generate ASF License warnings. |
| | | 5299 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.container.ozoneimpl.TestOzoneContainer |
|   | hadoop.ozone.scm.pipeline.TestSCMPipelineMetrics |
|   | hadoop.hdds.scm.pipeline.TestSCMPipelineManager |
|   | hadoop.ozone.web.client.TestKeys |
|   | hadoop.ozone.container.TestContainerReplication |
|   | hadoop.ozone.scm.TestGetCommittedBlockLengthAndPutKey |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |
|   | hadoop.ozone.TestMiniOzoneCluster |
|   | hadoop.ozone.om.TestMultipleContainerReadWrite |
|   | hadoop.ozone.TestMiniChaosOzoneCluster |
|   | hadoop.ozone.web.TestOzoneWebAccess |
|   | hadoop.hdds.scm.pipeline.TestRatisPipelineUtils |
|   | hadoop.ozone.web.TestOzoneVolumes |
|   | hadoop.ozone.web.client.TestBuckets |
|   | hadoop.ozone.web.client.TestOzoneClient |
|   | hadoop.hdds.scm.pipeline.TestNode2PipelineMap |
|   | hadoop.ozone.web.client.TestVolume |
|   | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.ozone.client.rpc.TestContainerStateMachine |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.ozShell.TestOzoneShell |
|   | hadoop.ozone.scm.TestXceiverClientManager |
|   | hadoop.ozone.web.client.TestKeysRatis |
|   | hadoop.hdds.scm.pipeline.TestPipelineClose |
|   | hadoop.ozone.ozShell.TestOzoneDatanodeShell |
|   | hadoop.ozone.om.TestContainerReportWithKeys |
|   | hadoop.ozone.web.TestOzoneRestWithMiniCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-786/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/786 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 5a464a4f4007 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / d6b7609 |
| Default Java | 1.8.0_191 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/3/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/3/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/3/testReport/ |
| Max. process+thread count | 3220 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/server-scm hadoop-ozone/integration-test U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-786/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
