### PR TITLE
HADOOP-17343. Upgrade AWS SDK to 1.11.901

### PR DESCRIPTION
**Pull request by steveloughran**
Upgrade the AWS SDK to the latest release

Includes the changes to the manual steps of the regression testing needed to test directory marker support

Tested AWS London (v4 signing only, BTW)

* Integration tests ( -Dparallel-tests -DtestsThreadCount=4 -Dmarkers=keep -Ds3guard -Ddynamo  -Dfs.s3a.directory.marker.audit=true) with review of all output files. 
* Downstream spark build and run through spark-cloud-integration suite
* Manual commands from the testing document

### CODE REVIEW

**Comment by steveloughran** [comment]
@dongjoon-hyun @sunchao

**Review by risdenk — APPROVED** [review]

**Comment by steveloughran** [comment]
Here's the cloud storage dependencies BTW
```
[INFO] +- org.apache.hadoop:hadoop-aws:jar:3.4.0-SNAPSHOT:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-bundle:jar:1.11.901:compile
[INFO] |  \- org.wildfly.openssl:wildfly-openssl:jar:1.0.7.Final:compile
```

I think we should consider downgrading that openssl dependency in the hadoop-aws pom from "runtime" to "test". It's clearly creeping in downstream and we don't need that.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m 20s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  15m  3s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  27m 35s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  23m 55s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  compile  |  18m 35s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  mvnsite  |  26m 11s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  17m 26s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   7m 26s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   7m 39s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 39s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  24m  4s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  21m 12s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javac  |  21m 12s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 34s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  javac  |  18m 34s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  22m 55s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 14s |  |  There were no new shelldocs issues.  |
| -1 :x: |  whitespace  |   0m  0s | [/whitespace-eol.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/1/artifact/out/whitespace-eol.txt) |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  2s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  19m 14s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   7m 47s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   7m 47s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 614m 20s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/1/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 29s |  |  The patch does not generate ASF License warnings.  |
|  |   | 887m  9s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.mapred.gridmix.TestGridmixSubmission |
|   | hadoop.tools.dynamometer.TestDynamometerInfra |
|   | hadoop.fs.azure.TestNativeAzureFileSystemContractMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemFileNameCheck |
|   | hadoop.fs.azure.TestNativeAzureFileSystemMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemConcurrency |
|   | hadoop.fs.azure.TestOutOfBandAzureBlobOperations |
|   | hadoop.fs.azure.TestNativeAzureFileSystemOperationsMocked |
|   | hadoop.fs.azure.TestBlobMetadata |
|   | hadoop.fs.azure.TestWasbFsck |
|   | hadoop.yarn.server.timelineservice.storage.TestTimelineWriterHBaseDown |
|   | hadoop.yarn.server.resourcemanager.scheduler.capacity.TestCapacitySchedulerAutoCreatedQueuePreemption |
|   | hadoop.yarn.server.resourcemanager.reservation.TestCapacityOverTimePolicy |
|   | hadoop.yarn.server.router.webapp.TestRouterWebServicesREST |
|   | hadoop.yarn.service.TestYarnNativeServices |
|   | hadoop.yarn.applications.distributedshell.TestDistributedShell |
|   | hadoop.hdfs.TestViewDistributedFileSystem |
|   | hadoop.hdfs.TestDecommission |
|   | hadoop.hdfs.server.namenode.TestAddOverReplicatedStripedBlocks |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2468 |
| Optional Tests | dupname asflicense shellcheck shelldocs compile javac javadoc mvninstall mvnsite unit shadedclient xml markdownlint |
| uname | Linux 645a7afb9aaf 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / b57f04cd5bf |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/1/testReport/ |
| Max. process+thread count | 2786 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-tools/hadoop-aws . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/1/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by dongjoon-hyun** [comment]
Thank you so much for taking over, @steveloughran !

**Comment by steveloughran** [comment]
merge conflict due to me committing something I shouldn't have. will revert

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   2m  5s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 21s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  31m 29s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  21m 44s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  compile  |  18m 25s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  mvnsite  |  26m 23s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  17m 10s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   7m 26s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   7m 35s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| -0 :warning: |  patch  |  32m 32s |  |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 50s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  23m 43s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  21m  0s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javac  |  21m  0s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 21s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  javac  |  18m 21s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  20m 59s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  1s |  |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 15s |  |  There were no new shelldocs issues.  |
| -1 :x: |  whitespace  |   0m  0s | [/whitespace-eol.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/2/artifact/out/whitespace-eol.txt) |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  17m 18s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   7m 21s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   7m 42s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 602m 58s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/2/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| -1 :x: |  asflicense  |   1m 32s | [/patch-asflicense-problems.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/2/artifact/out/patch-asflicense-problems.txt) |  The patch generated 2 ASF License warnings.  |
|  |   | 873m 22s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.tools.dynamometer.TestDynamometerInfra |
|   | hadoop.fs.azure.TestNativeAzureFileSystemContractMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemFileNameCheck |
|   | hadoop.fs.azure.TestNativeAzureFileSystemMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemConcurrency |
|   | hadoop.fs.azure.TestOutOfBandAzureBlobOperations |
|   | hadoop.fs.azure.TestNativeAzureFileSystemOperationsMocked |
|   | hadoop.fs.azure.TestBlobMetadata |
|   | hadoop.fs.azure.TestWasbFsck |
|   | hadoop.yarn.server.resourcemanager.scheduler.fair.TestFairSchedulerOvercommit |
|   | hadoop.yarn.server.resourcemanager.reservation.TestCapacityOverTimePolicy |
|   | hadoop.yarn.server.router.webapp.TestRouterWebServicesREST |
|   | hadoop.yarn.applications.distributedshell.TestDistributedShell |
|   | hadoop.hdfs.server.namenode.TestFSImage |
|   | hadoop.hdfs.server.datanode.fsdataset.impl.TestFsDatasetImpl |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2468 |
| Optional Tests | dupname asflicense shellcheck shelldocs compile javac javadoc mvninstall mvnsite unit shadedclient xml markdownlint |
| uname | Linux 833a55f75706 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 34aa6137bd8 |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/2/testReport/ |
| Max. process+thread count | 2992 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-tools/hadoop-aws . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/2/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m 24s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 15s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  21m 13s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  19m 56s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  compile  |  17m 26s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  mvnsite  |  25m 28s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  15m 44s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   7m 10s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   7m 26s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 45s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  21m 22s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 24s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javac  |  19m 24s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 23s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  javac  |  17m 23s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  20m  8s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 18s |  |  There were no new shelldocs issues.  |
| -1 :x: |  whitespace  |   0m  0s | [/whitespace-eol.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/3/artifact/out/whitespace-eol.txt) |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  15m 23s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   7m 12s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   7m 30s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 611m 45s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/3/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| -1 :x: |  asflicense  |   1m 52s | [/patch-asflicense-problems.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/3/artifact/out/patch-asflicense-problems.txt) |  The patch generated 2 ASF License warnings.  |
|  |   | 858m 51s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.balancer.TestBalancerWithMultipleNameNodes |
|   | hadoop.hdfs.TestMultipleNNPortQOP |
|   | hadoop.hdfs.server.namenode.TestFSImage |
|   | hadoop.yarn.service.TestYarnNativeServices |
|   | hadoop.yarn.applications.distributedshell.TestDistributedShell |
|   | hadoop.yarn.server.router.webapp.TestRouterWebServicesREST |
|   | hadoop.yarn.server.resourcemanager.reservation.TestCapacityOverTimePolicy |
|   | hadoop.yarn.server.resourcemanager.security.TestDelegationTokenRenewer |
|   | hadoop.tools.dynamometer.TestDynamometerInfra |
|   | hadoop.fs.azure.TestBlobMetadata |
|   | hadoop.fs.azure.TestNativeAzureFileSystemFileNameCheck |
|   | hadoop.fs.azure.TestNativeAzureFileSystemOperationsMocked |
|   | hadoop.fs.azure.TestWasbFsck |
|   | hadoop.fs.azure.TestOutOfBandAzureBlobOperations |
|   | hadoop.fs.azure.TestNativeAzureFileSystemMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemConcurrency |
|   | hadoop.fs.azure.TestNativeAzureFileSystemContractMocked |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2468 |
| Optional Tests | dupname asflicense shellcheck shelldocs compile javac javadoc mvninstall mvnsite unit shadedclient xml markdownlint |
| uname | Linux 264ee8ff4825 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 34aa6137bd8 |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/3/testReport/ |
| Max. process+thread count | 3758 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-tools/hadoop-aws . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2468/3/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
test failures unrelated (wasb fix in progress, license fix for the lz4 files in).

@sunchao -want to look/approve this?

**Review by sunchao — APPROVED** [review]
LGTM. Checked test failures and they are not related. Thanks @steveloughran for pinging.

**Pull request merged**
