### PR TITLE
HDFS-14492. Snapshot memory leak. Contributed by Wei-Chiu Chuang.

### PR DESCRIPTION
**Pull request by jojochuang**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1069 | trunk passed |
| +1 | compile | 65 | trunk passed |
| +1 | checkstyle | 52 | trunk passed |
| +1 | mvnsite | 70 | trunk passed |
| +1 | shadedclient | 796 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 58 | trunk passed |
| 0 | spotbugs | 162 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 159 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 62 | the patch passed |
| +1 | compile | 55 | the patch passed |
| +1 | javac | 56 | the patch passed |
| -0 | checkstyle | 44 | hadoop-hdfs-project/hadoop-hdfs: The patch generated 3 new + 199 unchanged - 0 fixed = 202 total (was 199) |
| +1 | mvnsite | 63 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 736 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 54 | the patch passed |
| +1 | findbugs | 162 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 5191 | hadoop-hdfs in the patch failed. |
| +1 | asflicense | 40 | The patch does not generate ASF License warnings. |
| | | 8782 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestFileChecksumCompositeCrc |
|   | hadoop.hdfs.server.namenode.snapshot.TestRenameWithSnapshots |
|   | hadoop.hdfs.web.TestWebHDFS |
|   | hadoop.hdfs.TestReadStripedFileWithDNFailure |
|   | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |
|   | hadoop.hdfs.TestErasureCodingPolicies |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1370 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 1672890bb667 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 6f2226a |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/1/artifact/out/diff-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/1/testReport/ |
| Max. process+thread count | 5413 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by bshashikant** [comment]
Thanks @jojochuang for working on this. The changes look good to me. I am +1 on the change once the checkstyle issues are addressed.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 49 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1369 | trunk passed |
| +1 | compile | 74 | trunk passed |
| +1 | checkstyle | 59 | trunk passed |
| +1 | mvnsite | 85 | trunk passed |
| +1 | shadedclient | 983 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 66 | trunk passed |
| 0 | spotbugs | 210 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 207 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 75 | the patch passed |
| +1 | compile | 71 | the patch passed |
| +1 | javac | 71 | the patch passed |
| -0 | checkstyle | 50 | hadoop-hdfs-project/hadoop-hdfs: The patch generated 3 new + 199 unchanged - 0 fixed = 202 total (was 199) |
| +1 | mvnsite | 78 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 907 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 60 | the patch passed |
| +1 | findbugs | 203 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 5787 | hadoop-hdfs in the patch failed. |
| +1 | asflicense | 41 | The patch does not generate ASF License warnings. |
| | | 10229 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestErasureCodingExerciseAPIs |
|   | hadoop.hdfs.TestErasureCodingPoliciesWithRandomECPolicy |
|   | hadoop.hdfs.web.TestFSMainOperationsWebHdfs |
|   | hadoop.hdfs.server.namenode.snapshot.TestRenameWithSnapshots |
|   | hadoop.hdfs.web.TestWebHDFS |
|   | hadoop.hdfs.TestReconstructStripedFileWithRandomECPolicy |
|   | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |
|   | hadoop.hdfs.TestErasureCodingPolicies |
|   | hadoop.hdfs.server.namenode.TestFsck |
|   | hadoop.hdfs.server.balancer.TestBalancer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1370 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux fc6b548c7e6e 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 915cbc9 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/2/artifact/out/diff-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/2/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/2/testReport/ |
| Max. process+thread count | 5361 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 56 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1120 | trunk passed |
| +1 | compile | 62 | trunk passed |
| +1 | checkstyle | 50 | trunk passed |
| +1 | mvnsite | 72 | trunk passed |
| +1 | shadedclient | 813 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 63 | trunk passed |
| 0 | spotbugs | 206 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 204 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 73 | the patch passed |
| +1 | compile | 66 | the patch passed |
| +1 | javac | 66 | the patch passed |
| +1 | checkstyle | 50 | the patch passed |
| +1 | mvnsite | 67 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 875 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 60 | the patch passed |
| +1 | findbugs | 209 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 5888 | hadoop-hdfs in the patch failed. |
| +1 | asflicense | 43 | The patch does not generate ASF License warnings. |
| | | 9844 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestDFSStripedOutputStreamWithFailure |
|   | hadoop.hdfs.server.namenode.TestNamenodeCapacityReport |
|   | hadoop.hdfs.TestFileChecksumCompositeCrc |
|   | hadoop.hdfs.server.namenode.sps.TestStoragePolicySatisfierWithStripedFile |
|   | hadoop.hdfs.server.namenode.snapshot.TestRenameWithSnapshots |
|   | hadoop.hdfs.TestDatanodeDeath |
|   | hadoop.hdfs.TestDistributedFileSystemWithECFileWithRandomECPolicy |
|   | hadoop.hdfs.TestReadStripedFileWithDNFailure |
|   | hadoop.hdfs.TestReconstructStripedFileWithRandomECPolicy |
|   | hadoop.hdfs.server.namenode.TestBackupNode |
|   | hadoop.hdfs.TestErasureCodingPolicies |
|   | hadoop.hdfs.TestDFSInotifyEventInputStreamKerberized |
|   | hadoop.hdfs.TestAppendSnapshotTruncate |
|   | hadoop.hdfs.server.mover.TestMover |
|   | hadoop.hdfs.server.namenode.TestFileTruncate |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1370 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux fb3485836809 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 1ae7759 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/3/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/3/testReport/ |
| Max. process+thread count | 4781 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1370/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
Checkstyle was addressed. @bshashikant i believe this is good. 
Test failures look unrelated.

**Comment by bshashikant** [comment]
Thanks @jojochuang for updating the patch. I am +1 on the change.

**Pull request merged**
