### PR TITLE
HADOOP-18832. Upgrade aws-java-sdk to 1.12.499

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Comment by virajjasani** [comment]
us-west-2

```
$ mvn clean verify -Dparallel-tests -DtestsThreadCount=8 -Dscale -Dprefetch

[INFO] --- maven-failsafe-plugin:3.0.0-M1:integration-test (default-integration-test) @ hadoop-aws ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------

[INFO] Results:
[INFO] 
[WARNING] Tests run: 1170, Failures: 0, Errors: 0, Skipped: 148


[INFO] --- maven-failsafe-plugin:3.0.0-M1:integration-test (sequential-integration-tests) @ hadoop-aws ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------

[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ITestS3AContractRootDir>AbstractContractRootDirectoryTest.testRecursiveRootListing:266 » TestTimedOut
[INFO] 
[ERROR] Tests run: 135, Failures: 0, Errors: 1, Skipped: 10


[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  29:35 min
[INFO] Finished at: 2023-07-30T14:54:18-07:00
[INFO] ------------------------------------------------------------------------

```

**Comment by virajjasani** [comment]
With encryption enabled:

```
$ mvn clean verify -Dparallel-tests -DtestsThreadCount=8 -Dscale -Dprefetch

[INFO] --- maven-failsafe-plugin:3.0.0-M1:integration-test (default-integration-test) @ hadoop-aws ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------

[INFO] Results:
[INFO] 
[WARNING] Tests run: 1170, Failures: 0, Errors: 0, Skipped: 143


[INFO] --- maven-failsafe-plugin:3.0.0-M1:integration-test (sequential-integration-tests) @ hadoop-aws ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------

[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ITestS3AContractRootDir>AbstractContractRootDirectoryTest.testRecursiveRootListing:266 » TestTimedOut
[INFO] 
[ERROR] Tests run: 135, Failures: 0, Errors: 1, Skipped: 10


[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33:28 min
[INFO] Finished at: 2023-07-30T16:57:05-07:00
[INFO] ------------------------------------------------------------------------

```

**Comment by steveloughran** [comment]
you've seen the "qualifying an update" section of the testing docs, right?

**Comment by virajjasani** [comment]
yes, assumed role test coverage is pending

**Comment by virajjasani** [comment]
`AbstractSTestS3AHugeFiles` is successful with `SSE-KMS`, will run assumed role tests now

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 49s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 35s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  35m 47s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  18m 36s |  |  trunk passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1  |
| +1 :green_heart: |  compile  |  17m 32s |  |  trunk passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09  |
| +1 :green_heart: |  mvnsite  |  20m  8s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   9m 15s |  |  trunk passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1  |
| +1 :green_heart: |  javadoc  |   7m 29s |  |  trunk passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09  |
| +1 :green_heart: |  shadedclient  |  55m  5s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 47s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  34m 28s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m  3s |  |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1  |
| +1 :green_heart: |  javac  |  18m  3s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 55s |  |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09  |
| +1 :green_heart: |  javac  |  16m 55s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  15m  7s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   8m 52s |  |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1  |
| +1 :green_heart: |  javadoc  |   7m 33s |  |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09  |
| +1 :green_heart: |  shadedclient  |  55m 43s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 788m 18s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5908/1/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 40s |  |  The patch does not generate ASF License warnings.  |
|  |   | 1098m 19s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.yarn.server.timelineservice.security.TestTimelineAuthFilterForV2 |
|   | hadoop.mapreduce.v2.TestMRJobs |
|   | hadoop.mapreduce.v2.TestUberAM |
|   | hadoop.mapreduce.v2.TestMRJobsWithProfiler |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5908/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5908 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint shellcheck shelldocs |
| uname | Linux 79d428c7e96f 4.15.0-212-generic #223-Ubuntu SMP Tue May 23 13:09:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 9aaf50cb325dc3bbfb90c6c00b82067927a41263 |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5908/1/testReport/ |
| Max. process+thread count | 2368 (vs. ulimit of 5500) |
| modules | C: hadoop-project . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5908/1/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
re-ran the tests with assume role and encryption enabled:

the only tests that are getting ignored are:
- contract tests that don't apply to s3a (e.g. `fs.capability.etags.preserved.in.rename`)
- `ITestS3AContractSeek`: `Tests run: 72, Failures: 0, Errors: 0, Skipped: 24, Time elapsed: 198.155 s - in org.apache.hadoop.fs.contract.s3a.ITestS3AContractSeek` 24 tests getting skipped because they need native hadoop lib:
```
    if (this.sslChannelMode == OpenSSL) {
      assumeTrue(NativeCodeLoader.isNativeCodeLoaded() &&
          NativeCodeLoader.buildSupportsOpenssl());
    }
```

everything else is passing.
all testing done against us-west-2 endpoint.

**Comment by virajjasani** [comment]
load tests are passing:
```
[INFO] Running org.apache.hadoop.fs.s3a.scale.ILoadTestS3ABulkDeleteThrottling
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 80.192 s - in org.apache.hadoop.fs.s3a.scale.ILoadTestS3ABulkDeleteThrottling
[INFO] Running org.apache.hadoop.fs.s3a.auth.delegation.ILoadTestSessionCredentials
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 69.606 s - in org.apache.hadoop.fs.s3a.auth.delegation.ILoadTestSessionCredentials
[INFO] Running org.apache.hadoop.fs.s3a.auth.delegation.ILoadTestRoleCredentials
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 72.61 s - in org.apache.hadoop.fs.s3a.auth.delegation.ILoadTestRoleCredentials
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by steveloughran** [comment]
to confirm: you've 
[ ] run the CLI tests on a full build
[ ] looked in all the logs of the test runs for new messages
[ ] reviewed the dependencies of the bundle to see if something else is now referenced which we need to exclude?

**Comment by virajjasani** [comment]
> [ ] run the CLI tests on a full build

done, by using the various combination of (encryption + assumed role + full s3 access) credentials, all tests are passing

> [ ] looked in all the logs of the test runs for new messages

no surprises so far, scanned logs for many of the long running scale tests

> [ ] reviewed the dependencies of the bundle to see if something else is now referenced which we need to exclude?

this was pending until today, i just scanned the dependencies and we seem good, no need to exclude anything other than `io.netty:*` that is already present

```
com.amazonaws:aws-java-sdk-bundle:jar:1.12.499
\- com.amazonaws:aws-java-sdk:jar:1.12.499:compile
   +- com.amazonaws:aws-java-sdk-appfabric:jar:1.12.499:compile
   |  \- com.amazonaws:jmespath-java:jar:1.12.499:compile
   +- com.amazonaws:aws-java-sdk-verifiedpermissions:jar:1.12.499:compile
   +- com.amazonaws:aws-java-sdk-codegurusecurity:jar:1.12.499:compile
...
...
...
   +- com.amazonaws:aws-java-sdk-iotjobsdataplane:jar:1.12.499:compile
   +- com.amazonaws:aws-java-sdk-sagemakerruntime:jar:1.12.499:compile
   +- com.amazonaws:aws-java-sdk-kinesisvideo:jar:1.12.499:compile
   |  +- io.netty:netty-codec-http:jar:4.1.94.Final:compile
   |  |  +- io.netty:netty-common:jar:4.1.94.Final:compile
   |  |  +- io.netty:netty-buffer:jar:4.1.94.Final:compile
   |  |  +- io.netty:netty-transport:jar:4.1.94.Final:compile
   |  |  \- io.netty:netty-codec:jar:4.1.94.Final:compile
   |  \- io.netty:netty-handler:jar:4.1.94.Final:compile
   |     +- io.netty:netty-resolver:jar:4.1.94.Final:compile
   |     \- io.netty:netty-transport-native-unix-common:jar:4.1.94.Final:compile
   +- com.amazonaws:aws-java-sdk-appsync:jar:1.12.499:compile
   +- com.amazonaws:aws-java-sdk-guardduty:jar:1.12.499:compile
...
...
...
   +- com.amazonaws:aws-java-sdk-workdocs:jar:1.12.499:compile
   +- com.amazonaws:aws-java-sdk-core:jar:1.12.499:compile
   |  +- commons-logging:commons-logging:jar:1.1.3:compile
   |  +- commons-codec:commons-codec:jar:1.15:compile
   |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
   |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
   |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
   |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.7.1:compile
   |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.7:compile
   |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.12.7:compile
   |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.12.6:compile
   |  \- joda-time:joda-time:jar:2.8.1:compile
   +- com.amazonaws:aws-java-sdk-models:jar:1.12.499:compile
   \- com.amazonaws:aws-java-sdk-swf-libraries:jar:1.11.22:compile

```

**Comment by virajjasani** [comment]
i have repeated above steps for both `-Dscale -Dprefetch` as well as `-Dscale` and confirmed above 3 points for both rounds

**Review by steveloughran — APPROVED** [review]
LGTM
+1

**Pull request merged**
