### PR TITLE
HDDS-1296. Fix checkstyle issue from Nightly run. Contributed by Xiao…

### PR DESCRIPTION
**Pull request by xiaoyuyao**
…yu Yao.

### CODE REVIEW

**Comment by xiaoyuyao** [comment]
Thanks @bharatviswa504 for the review. Just found and fix remaining issues based on another report.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 28 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 991 | trunk passed |
| +1 | compile | 53 | trunk passed |
| +1 | checkstyle | 20 | trunk passed |
| +1 | mvnsite | 31 | trunk passed |
| +1 | shadedclient | 702 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 43 | trunk passed |
| +1 | javadoc | 22 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 33 | the patch passed |
| +1 | compile | 24 | the patch passed |
| +1 | javac | 24 | the patch passed |
| +1 | checkstyle | 16 | hadoop-ozone/ozone-manager: The patch generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2) |
| +1 | mvnsite | 27 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 741 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 48 | the patch passed |
| +1 | javadoc | 21 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 40 | ozone-manager in the patch passed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 2954 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-616/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/616 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux 427c430d1bb7 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 926d548 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-616/1/testReport/ |
| Max. process+thread count | 445 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/ozone-manager U: hadoop-ozone/ozone-manager |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-616/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 26 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 60 | Maven dependency ordering for branch |
| +1 | mvninstall | 998 | trunk passed |
| +1 | compile | 98 | trunk passed |
| +1 | checkstyle | 28 | trunk passed |
| +1 | mvnsite | 72 | trunk passed |
| +1 | shadedclient | 766 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 102 | trunk passed |
| +1 | javadoc | 60 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for patch |
| +1 | mvninstall | 71 | the patch passed |
| +1 | compile | 91 | the patch passed |
| +1 | javac | 91 | the patch passed |
| +1 | checkstyle | 23 | hadoop-ozone: The patch generated 0 new + 0 unchanged - 4 fixed = 0 total (was 4) |
| +1 | mvnsite | 57 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 721 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 103 | the patch passed |
| +1 | javadoc | 48 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 34 | common in the patch passed. |
| +1 | unit | 37 | ozone-manager in the patch passed. |
| +1 | asflicense | 24 | The patch does not generate ASF License warnings. |
| | | 3472 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-616/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/616 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux 721477a7323c 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 926d548 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-616/2/testReport/ |
| Max. process+thread count | 412 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/common hadoop-ozone/ozone-manager U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-616/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by ajayydv** [comment]
+1

**Pull request merged**
