### PR TITLE
HADOOP-16735. Make it clearer in config default that EnvironmentVariableCredentialsProvider supports AWS_SESSION_TOKEN

### PR DESCRIPTION
**Pull request by liuml07**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 35s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  18m  6s |  trunk passed  |
| +1 :green_heart: |  compile  |  16m 56s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 14s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  50m 56s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 11s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 20s |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 19s |  the patch passed  |
| +1 :green_heart: |  javac  |  16m 19s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m 12s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  12m 22s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 10s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   9m  7s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 32s |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 53s |  The patch does not generate ASF License warnings.  |
|  |   | 103m 15s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1733/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1733 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml markdownlint |
| uname | Linux 194f0bb04e6d 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 44f7b91 |
| Default Java | 1.8.0_222 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1733/1/testReport/ |
| Max. process+thread count | 1521 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1733/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  9s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   1m  5s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  20m 35s |  trunk passed  |
| +1 :green_heart: |  compile  |  18m  0s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m  2s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  55m 46s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 55s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 20s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 22s |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 10s |  the patch passed  |
| +1 :green_heart: |  javac  |  17m 10s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m  3s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  13m 55s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 57s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   8m 51s |  hadoop-common in the patch failed.  |
| +1 :green_heart: |  unit  |   1m 33s |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 46s |  The patch does not generate ASF License warnings.  |
|  |   | 109m 41s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.security.TestFixKerberosTicketOrder |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1733/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1733 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml markdownlint |
| uname | Linux 6f55f0b64175 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 44f7b91 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1733/2/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1733/2/testReport/ |
| Max. process+thread count | 1346 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1733/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
+1, commit at your leisure

**Comment by liuml07** [comment]
Thanks @steveloughran . So our way of committing PR at GitHub is to merge the PR from this Web UI, or still go back to the git command line and following the [HowtoCommit](https://cwiki.apache.org/confluence/display/HADOOP2/HowToCommit) wiki? If the former, I don't have write access to this repository so I can merge PR. If the latter, shall I mention this PR number in the commit message so this will close this PR automatically?

**Comment by steveloughran** [comment]
multiple ways

* through the UI. Can lose the author info. Make sure the commit message you get to fill-in includes the contributor name. (github signs these BTW, so add its key to your keychain)

* Yetus smart-apply patch. Works well for trunk, mostly. As it applys the entire chain sometimes it has some problems.

```
dev-support/bin/smart-apply-patch  --project=hadoop  GH:1711
```

Unless you use the option to commit the chain of patches (I don't) things are uncommitted. You should do the final commit yourself, ideally with a --author attribute to give the contributor credit across github, -S to GPG sign.

* your own work: git diff, git apply etc. I do this sometimes when things are complex.

Download the .patch file by adding .patch to the PR URL; apply

```
http -F https://github.com/apache/hadoop/pull/1388.patch > 1388.patch
git apply < 1388.patch
git add ... 
git commit -S --author "someone"
```

Then commit manually.

For back porting I check out locally and then cherry pick.

As this is your own work, just hit the squash and merge button and see how it goes. Except: why don't you have write access?

Try from the command line with smart-apply-patch instead

**Comment by steveloughran** [comment]
oh, and then manually close the PR & JIRA. Some people include the commit #; I don't

**Comment by liuml07** [comment]
Thanks @steveloughran . I don't have write access to this GitHub repo, and I have sent an email to ask about this. Not sure why.

At the meantime, I have committed via command line using the tips you provided. One nit is that, I enabled the `git config commit.gpgsign true` so I don't have to remember using the `git commit -S ` option when committing. It's now showing the signature is "verified".

I will update the wiki page with the above tips, and maybe you can review that later. Will let you know.

**Comment by liuml07** [comment]
@steveloughran I don't have write access to the wiki page at https://cwiki.apache.org/confluence/display/HADOOP2, do you have admin access to add me there? Thanks

**Comment by steveloughran** [comment]
I don't seem allowed to edit that page either

**Pull request closed without merging**
