### PR TITLE
HDDS-1559. Include committedBytes to determine Out of Space in VolumeChoosingPolicy. Contributed by Supratim Deka

### PR DESCRIPTION
**Pull request by supratimdeka**
https://issues.apache.org/jira/browse/HDDS-1559

This patch improves the space availability check in chooseVolume by inclusion of committed space(committedBytes in HddsVolume) in the equation. Container create fails with Exception if there isn't sufficient available space.

The handling/management of the exception in Ratis is not modified in this patch. That will be scoped separately as part of Datanode IO Failure handling work.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 58 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 517 | trunk passed |
| +1 | compile | 256 | trunk passed |
| +1 | checkstyle | 65 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 793 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 138 | trunk passed |
| 0 | spotbugs | 276 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 459 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 457 | the patch passed |
| +1 | compile | 250 | the patch passed |
| +1 | javac | 250 | the patch passed |
| -0 | checkstyle | 34 | hadoop-hdds: The patch generated 3 new + 0 unchanged - 0 fixed = 3 total (was 0) |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 621 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 130 | the patch passed |
| +1 | findbugs | 483 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 168 | hadoop-hdds in the patch failed. |
| -1 | unit | 1447 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 42 | The patch does not generate ASF License warnings. |
| | | 9379 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures |
|   | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.ozone.container.TestContainerReplication |
|   | hadoop.hdds.scm.pipeline.TestSCMPipelineManager |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-841/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/841 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux f0ec570eed49 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / a85451c |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/1/artifact/out/diff-checkstyle-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/1/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/1/testReport/ |
| Max. process+thread count | 4442 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/container-service U: hadoop-hdds/container-service |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 45 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 550 | trunk passed |
| +1 | compile | 293 | trunk passed |
| +1 | checkstyle | 81 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 923 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 153 | trunk passed |
| 0 | spotbugs | 318 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 522 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 579 | the patch passed |
| +1 | compile | 378 | the patch passed |
| +1 | javac | 378 | the patch passed |
| +1 | checkstyle | 104 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 834 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 180 | the patch passed |
| +1 | findbugs | 647 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 243 | hadoop-hdds in the patch failed. |
| -1 | unit | 2716 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 67 | The patch does not generate ASF License warnings. |
| | | 11241 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.container.common.statemachine.commandhandler.TestBlockDeletion |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.ozone.client.rpc.TestContainerStateMachineFailures |
|   | hadoop.ozone.client.rpc.TestCloseContainerHandlingByClient |
|   | hadoop.ozone.om.TestOzoneManagerHA |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-841/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/841 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 6d98e23362c8 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 9dff6ef |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/2/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/2/testReport/ |
| Max. process+thread count | 4161 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/container-service U: hadoop-hdds/container-service |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by arp7** [comment]
+1 for the patch. @supratimdeka can you look at the merge conflicts?

**Comment by arp7** [comment]
+1 pending the pre-commit run.

**Comment by supratimdeka** [comment]
the checkstyle errors reported here are not a part of this patch. these were introduced in SCMContainerPlacementRackAware.java by HDDS-700 and got submitted into trunk yesterday.

I think we can ignore these checkstyle errors reported for this patch because they already exist on the main branch. Right?

**Comment by supratimdeka** [comment]
pushed another merge(with trunk) to pull in fixes for existing checkstyle errors and UT failures on trunk.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 37 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 531 | trunk passed |
| +1 | compile | 269 | trunk passed |
| +1 | checkstyle | 75 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 915 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 151 | trunk passed |
| 0 | spotbugs | 328 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 546 | trunk passed |
| -0 | patch | 377 | Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 503 | the patch passed |
| +1 | compile | 287 | the patch passed |
| +1 | javac | 287 | the patch passed |
| +1 | checkstyle | 80 | the patch passed |
| +1 | mvnsite | 1 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 702 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 150 | the patch passed |
| +1 | findbugs | 560 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 183 | hadoop-hdds in the patch failed. |
| -1 | unit | 1271 | hadoop-ozone in the patch failed. |
| -1 | asflicense | 48 | The patch generated 17 ASF License warnings. |
| | | 6514 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.web.client.TestKeys |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |
|   | hadoop.ozone.client.rpc.TestBCSID |
|   | hadoop.ozone.client.rpc.TestFailureHandlingByClient |
|   | hadoop.ozone.container.common.impl.TestContainerPersistence |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-841/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/841 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux e16e0182751c 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 4a692bc |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/7/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/7/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/7/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/7/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 5316 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/container-service U: hadoop-hdds/container-service |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-841/7/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
