### PR TITLE
HADOOP-17036. TestFTPFileSystem failing as ftp server dir already exists

### PR DESCRIPTION
**Pull request by mpryahin**
Fixes a regression causing unit tests to fail as ftp server dir already exists

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  39m 53s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  31m  7s |  trunk passed  |
| +1 :green_heart: |  compile  |  27m  5s |  trunk passed  |
| +1 :green_heart: |  checkstyle  |   0m 55s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 39s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  20m 35s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 20s |  trunk passed  |
| +0 :ok: |  spotbugs  |   3m 10s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m  6s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 23s |  the patch passed  |
| +1 :green_heart: |  compile  |  22m 10s |  the patch passed  |
| +1 :green_heart: |  javac  |  22m 10s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 45s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 36s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  16m 11s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  3s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   3m 33s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  12m 10s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 26s |  The patch does not generate ASF License warnings.  |
|  |   | 187m 18s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ipc.TestRPC |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-2009/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2009 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 9ea060ff3a82 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 4c53fb9ce10 |
| Default Java | Private Build-1.8.0_252-8u252-b09-1~18.04-b09 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-2009/1/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-2009/1/testReport/ |
| Max. process+thread count | 2861 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-2009/1/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by mpryahin** [comment]
the following test fails now
```
java.lang.AssertionError: Expected exactly one metric for name RpcServerExceptionNumOps expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.apache.hadoop.test.MetricsAsserts.checkCaptured(MetricsAsserts.java:278)
	at org.apache.hadoop.test.MetricsAsserts.getLongCounter(MetricsAsserts.java:237)
	at org.apache.hadoop.test.MetricsAsserts.assertCounter(MetricsAsserts.java:231)
	at org.apache.hadoop.ipc.TestRPC.testCallsInternal(TestRPC.java:510)
	at org.apache.hadoop.ipc.TestRPC.testCalls(TestRPC.java:428)
```

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 11s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  21m 25s |  trunk passed  |
| +1 :green_heart: |  compile  |  18m  1s |  trunk passed  |
| +1 :green_heart: |  checkstyle  |   0m 45s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 21s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  17m 35s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 56s |  trunk passed  |
| +0 :ok: |  spotbugs  |   2m  9s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m  6s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 49s |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 20s |  the patch passed  |
| +1 :green_heart: |  javac  |  17m 20s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 44s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 22s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 32s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 55s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   2m 15s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   9m  9s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 45s |  The patch does not generate ASF License warnings.  |
|  |   | 113m 15s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.security.TestRaceWhenRelogin |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-2009/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2009 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 55abdb811bc0 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 743c2e9071f |
| Default Java | Private Build-1.8.0_252-8u252-b09-1~18.04-b09 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-2009/2/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-2009/2/testReport/ |
| Max. process+thread count | 2196 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-2009/2/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 38s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  20m 52s |  trunk passed  |
| +1 :green_heart: |  compile  |  18m  1s |  trunk passed  |
| +1 :green_heart: |  checkstyle  |   0m 48s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 30s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  16m  4s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 58s |  trunk passed  |
| +0 :ok: |  spotbugs  |   2m  9s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m  7s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 54s |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 49s |  the patch passed  |
| +1 :green_heart: |  javac  |  19m 49s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 57s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 45s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  18m 31s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  5s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   2m 51s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  10m 48s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 53s |  The patch does not generate ASF License warnings.  |
|  |   | 119m 36s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-2009/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2009 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 60e079b5e251 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 1958cb7c2be |
| Default Java | Private Build-1.8.0_252-8u252-b09-1~18.04-b09 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-2009/3/testReport/ |
| Max. process+thread count | 3092 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-2009/3/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
+1, merged.

thanks for a timely followup!

**Pull request merged**
