### PR TITLE
HADOOP-15410

### PR DESCRIPTION
**Pull request by lqjack**
change scope

### CODE REVIEW

**Comment by sunchao** [comment]
Just left some comment on the JIRA - can you submit a patch and attach to the JIRA? that's the standard process of contributing to Hadoop (rather than PR).

**Comment by lqjack** [comment]
@sunchao how can I associated with patch in comment ?

**Comment by sunchao** [comment]
I've already attached the patch for you in https://issues.apache.org/jira/browse/HADOOP-15410. So it's fine now.

**Comment by lqjack** [comment]
@sunchao  thanks a lot.

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Pull request merged**
