### PR TITLE
HADOOP-18929. Exclude commons-compress module-info.class

### PR DESCRIPTION
**Pull request by pjfanning**
### Description of PR

https://issues.apache.org/jira/browse/HADOOP-18929

I can create a separate PR for trunk

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by mukund-thakur** [comment]
Let's wait for Yetus to run and then we can commit this.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   5m 20s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  16m  1s |  |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |  22m 28s | [/branch-mvninstall-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6169/1/artifact/out/branch-mvninstall-root.txt) |  root in branch-3.3 failed.  |
| +1 :green_heart: |  compile  |   0m 22s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   0m 45s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   0m 43s |  |  branch-3.3 passed  |
| -1 :x: |  shadedclient  |  62m 57s |  |  branch has errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  11m  4s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 22s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 22s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 31s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 26s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  23m 35s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 17s |  |  hadoop-client-runtime in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 17s |  |  hadoop-client-minicluster in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 28s |  |  The patch does not generate ASF License warnings.  |
|  |   | 108m  1s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6169/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6169 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint |
| uname | Linux e37499fffb15 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 4f908e2a475c394ac4011a34713ff48746a5fa4e |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~18.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6169/1/testReport/ |
| Max. process+thread count | 680 (vs. ulimit of 5500) |
| modules | C: hadoop-client-modules/hadoop-client-runtime hadoop-client-modules/hadoop-client-minicluster U: hadoop-client-modules |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6169/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by pjfanning** [comment]
@mukund-thakur the 'patch' build seems to have worked ok - do you think this is safe to merge to branch-3.3?

**Comment by mukund-thakur** [comment]
I have actually merged this https://github.com/apache/hadoop/commits/branch-3.3 just now.

**Pull request closed without merging**
