### PR TITLE
HDFS-15389. DFSAdmin should close filesystem and dfsadmin -setBalancerBandwidth should work with ViewFSOverloadScheme.

### PR DESCRIPTION
**Pull request by ayushtkn**
https://issues.apache.org/jira/browse/HDFS-15389

### CODE REVIEW

**Comment by umamaheswararao** [comment]
Thanks @ayushtkn for reporting it. LGTM.
However I have one point, can we add a note about balancer bandwidth command with overloadScheme when they need to pass -fs? 
I think we have other commands to cover as well https://issues.apache.org/jira/browse/HDFS-15329.
How about we will just add a note down to the section of "dfsadmin with ViewFsOverloadScheme"
Something like this "Note: -setbanalcerbandwidth, (later with HDFS-15329: cacheadmin,ECadmin etc) would work in similar way, that user needs to pass -fs option to run on child filesystems" 

Or we can keep a heading "HDFS commands with ViewFSOverloadScheme" then sub heading should be: dfsadmin, -setbalancerbandwidth etc? 
I am ok either way. As we already updated guide, do you mind covering in doc? 
Code changes looks fine to me.

**Comment by ayushtkn** [comment]
Thanx @umamaheswararao will update the document, just a minor doubt on this. got little confused
bq. Or we can keep a heading "HDFS commands with ViewFSOverloadScheme" then sub heading should be: dfsadmin, -setbalancerbandwidth etc?

Why -setbalancerbandwidth should be a separate sub-heading from dfsadmin, -setbalancerbandwidth is also part of dfsadmin only? Or do you mean to say add it as sub heading of dfsadmin?

   `* Usage: hdfs dfsadmin -setBalancerBandwidth bandwidth`

**Comment by umamaheswararao** [comment]
@ayushtkn, you are right. -setBalancerBancdwidthNeed need not be a separate sub heading. You can just add note in dfsadmin itself. Later I will add remaining commands(cacehadmin..etc) doc update.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 45s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  19m 54s |  trunk passed  |
| +1 :green_heart: |  compile  |   1m 14s |  trunk passed  |
| +1 :green_heart: |  checkstyle  |   1m  1s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 30s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  19m 10s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 51s |  trunk passed  |
| +0 :ok: |  spotbugs  |   3m 49s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m 46s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 23s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 17s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 17s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 48s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 22s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  17m 32s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 44s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   3m 48s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 133m 53s |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 41s |  The patch does not generate ASF License warnings.  |
|  |   | 210m 44s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.datanode.TestDirectoryScanner |
|   | hadoop.hdfs.TestClientReportBadBlock |
|   | hadoop.hdfs.server.namenode.TestNameNodeRetryCacheMetrics |
|   | hadoop.hdfs.server.namenode.ha.TestHAAppend |
|   | hadoop.hdfs.security.token.block.TestBlockToken |
|   | hadoop.hdfs.TestDecommissionWithStripedBackoffMonitor |
|   | hadoop.hdfs.TestDFSStripedOutputStreamWithFailure |
|   | hadoop.hdfs.TestHDFSFileSystemContract |
|   | hadoop.hdfs.TestReconstructStripedFile |
|   | hadoop.hdfs.tools.offlineEditsViewer.TestOfflineEditsViewer |
|   | hadoop.hdfs.TestReconstructStripedFileWithRandomECPolicy |
|   | hadoop.hdfs.TestDistributedFileSystem |
|   | hadoop.hdfs.TestFileCreation |
|   | hadoop.hdfs.TestDFSInotifyEventInputStream |
|   | hadoop.hdfs.TestGetBlocks |
|   | hadoop.hdfs.TestBlocksScheduledCounter |
|   | hadoop.hdfs.TestStripedFileAppend |
|   | hadoop.hdfs.TestFileChecksum |
|   | hadoop.hdfs.TestDFSStripedOutputStreamWithRandomECPolicy |
|   | hadoop.hdfs.TestEncryptionZones |
|   | hadoop.hdfs.TestDFSFinalize |
|   | hadoop.hdfs.TestBatchedListDirectories |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-2057/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2057 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 6e0883103965 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 76fa0222f0d |
| Default Java | Private Build-1.8.0_252-8u252-b09-1~18.04-b09 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-2057/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-2057/1/testReport/ |
| Max. process+thread count | 3583 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-2057/1/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by umamaheswararao** [comment]
Most of these tests failed with the OOM errors. Could you please confirm the failed tests are running fine? Thank you

**Comment by ayushtkn** [comment]
Thanx, the test failures aren't related

**Pull request merged**
