### PR TITLE
HADOOP-16669. TestRawLocalFileSystemContract.testPermission fails if no native library

### PR DESCRIPTION
**Pull request by steveloughran**
Catches the first error and converts to a skip;
stack traces retained for the curious.

Change-Id: Id2fed3cde6fa86acf36f0e78766f707b2b3c2c5b

## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by steveloughran** [comment]
@bgaborg - this is get hadoop-common test to complete

**Comment by ayushtkn** [comment]
Thanx @steveloughran .
Can we do something like this 
`    assumeTrue(NativeCodeLoader.isNativeCodeLoaded());` in the first line itself. rather than executing half test and then ignoring?

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1083 | trunk passed |
| +1 | compile | 1037 | trunk passed |
| +1 | checkstyle | 44 | trunk passed |
| +1 | mvnsite | 84 | trunk passed |
| +1 | shadedclient | 901 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 90 | trunk passed |
| 0 | spotbugs | 125 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 123 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 48 | the patch passed |
| +1 | compile | 1017 | the patch passed |
| +1 | javac | 1017 | the patch passed |
| +1 | checkstyle | 46 | the patch passed |
| +1 | mvnsite | 80 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 774 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 88 | the patch passed |
| +1 | findbugs | 137 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 566 | hadoop-common in the patch passed. |
| +1 | asflicense | 49 | The patch does not generate ASF License warnings. |
| | | 6306 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1676/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1676 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux ad7f02c69119 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / ac6b6a6 |
| Default Java | 1.8.0_222 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1676/1/testReport/ |
| Max. process+thread count | 1470 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1676/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by bgaborg** [comment]
> Thanx @steveloughran .
> Can we do something like this
> ` assumeTrue(NativeCodeLoader.isNativeCodeLoaded());` in the first line itself. rather than executing half test and then ignoring?

Good idea, if there's a way to check it other than catching an exception we should do that.

**Comment by steveloughran** [comment]
makes sense -done

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 38 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1194 | trunk passed |
| +1 | compile | 1076 | trunk passed |
| +1 | checkstyle | 47 | trunk passed |
| +1 | mvnsite | 89 | trunk passed |
| +1 | shadedclient | 962 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 90 | trunk passed |
| 0 | spotbugs | 133 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 131 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 48 | the patch passed |
| +1 | compile | 1011 | the patch passed |
| +1 | javac | 1011 | the patch passed |
| +1 | checkstyle | 47 | the patch passed |
| +1 | mvnsite | 84 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 780 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 94 | the patch passed |
| +1 | findbugs | 132 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 565 | hadoop-common in the patch passed. |
| +1 | asflicense | 50 | The patch does not generate ASF License warnings. |
| | | 6540 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1676/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1676 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 8dbb507abc41 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / d5e9971 |
| Default Java | 1.8.0_222 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1676/2/testReport/ |
| Max. process+thread count | 1506 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1676/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
thanks - will merge

**Comment by steveloughran** [comment]
thanks, committed to 3.1+

**Pull request closed without merging**
