### PR TITLE
HDDS-2050. Error while compiling ozone-recon-web

### PR DESCRIPTION
**Pull request by vivekratnavel**
The following error was seen while compiling ozone-recon-web

```
[INFO] Running 'yarn install' in /Users/nvadivelu/codebase/apache/hadoop/hadoop-ozone/ozone-recon/src/main/resources/webapps/recon/ozone-recon-web
[INFO] yarn install v1.9.2
[INFO] [1/4] Resolving packages...
[INFO] [2/4] Fetching packages...
[ERROR] (node:31190) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[INFO] [3/4] Linking dependencies...
[ERROR] warning " > less-loader@5.0.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
[INFO] [4/4] Building fresh packages...
[ERROR] warning Error running install script for optional dependency: "/Users/nvadivelu/codebase/apache/hadoop/hadoop-ozone/ozone-recon/src/main/resources/webapps/recon/ozone-recon-web/node_modules/fsevents: Command failed.
[ERROR] Exit code: 1
[ERROR] Command: node install
[ERROR] Arguments:
[ERROR] Directory: /Users/nvadivelu/codebase/apache/hadoop/hadoop-ozone/ozone-recon/src/main/resources/webapps/recon/ozone-recon-web/node_modules/fsevents
[ERROR] Output:
[ERROR] node-pre-gyp info it worked if it ends with ok
[INFO] info This module is OPTIONAL, you can safely ignore this error
[ERROR] node-pre-gyp info using node-pre-gyp@0.12.0
[ERROR] node-pre-gyp info using node@12.1.0 | darwin | x64
[ERROR] node-pre-gyp WARN Using request for node-pre-gyp https download
[ERROR] node-pre-gyp info check checked for \"/Users/nvadivelu/codebase/apache/hadoop/hadoop-ozone/ozone-recon/src/main/resources/webapps/recon/ozone-recon-web/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" (not found)
[ERROR] node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.8/fse-v1.2.8-node-v72-darwin-x64.tar.gz
[ERROR] node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.8/fse-v1.2.8-node-v72-darwin-x64.tar.gz
[ERROR] node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.8/fse-v1.2.8-node-v72-darwin-x64.tar.gz
[ERROR] node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.8 and node@12.1.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
[ERROR] node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.8/fse-v1.2.8-node-v72-darwin-x64.tar.gz
[ERROR] node-pre-gyp ERR! build error
[ERROR] node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
[ERROR] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/nvadivelu/codebase/apache/hadoop/hadoop-ozone/ozone-recon/src/main/resources/webapps/recon/ozone-recon-web/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
[ERROR] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
[ERROR] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[ERROR] node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:431:16)
[ERROR] node-pre-gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:17)
[ERROR] node-pre-gyp ERR! System Darwin 18.5.0
[ERROR] node-pre-gyp ERR! command \"/Users/nvadivelu/codebase/apache/hadoop/hadoop-ozone/ozone-recon/target/node/node\" \"/Users/nvadivelu/codebase/apache/hadoop/hadoop-ozone/ozone-recon/src/main/resources/webapps/recon/ozone-recon-web/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
[ERROR] node-pre-gyp ERR! cwd /Users/nvadivelu/codebase/apache/hadoop/hadoop-ozone/ozone-recon/src/main/resources/webapps/recon/ozone-recon-web/node_modules/fsevents
[ERROR] node-pre-gyp ERR! node -v v12.1.0
[ERROR] node-pre-gyp ERR! node-pre-gyp -v v0.12.0
[ERROR] node-pre-gyp ERR! not ok
[ERROR] Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)"
[INFO] Done in 102.54s.
```

I fixed these node-pre-gyp and fsevents install errors by rebuilding yarn cache and yarn lock file and updating the dependencies to latest versions.

Tested in both ozone-0.4.1 and trunk branches and verified that these errors are not thrown during ozone-recon-web compilation.

### CODE REVIEW

**Comment by vivekratnavel** [comment]
@anuengineer @elek @nandakumar131 Please review

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 575 | trunk passed |
| +1 | compile | 369 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1713 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 172 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 578 | the patch passed |
| +1 | compile | 376 | the patch passed |
| +1 | javac | 376 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 657 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 171 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 315 | hadoop-hdds in the patch passed. |
| -1 | unit | 1733 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 52 | The patch does not generate ASF License warnings. |
| | | 6041 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.TestStorageContainerManager |
|   | hadoop.ozone.TestSecureOzoneCluster |
|   | hadoop.ozone.TestOzoneConfigurationFields |
|   | hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientForAclAuditLog |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1374/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1374 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient |
| uname | Linux af45cbac3b03 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 872cdf4 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1374/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1374/1/testReport/ |
| Max. process+thread count | 4836 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/ozone-recon U: hadoop-ozone/ozone-recon |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1374/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
