### PR TITLE
HDDS-1178. Healthy pipeline Chill Mode Rule.

### PR DESCRIPTION
**Pull request by bharatviswa504**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 25 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 24 | Maven dependency ordering for branch |
| +1 | mvninstall | 1008 | trunk passed |
| +1 | compile | 75 | trunk passed |
| -0 | checkstyle | 26 | The patch fails to run checkstyle in hadoop-hdds |
| -1 | mvnsite | 20 | server-scm in trunk failed. |
| +1 | shadedclient | 743 | branch has no errors when building and testing our client artifacts. |
| -1 | findbugs | 18 | server-scm in trunk failed. |
| -1 | javadoc | 18 | server-scm in trunk failed. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 12 | Maven dependency ordering for patch |
| -1 | mvninstall | 12 | server-scm in the patch failed. |
| +1 | compile | 68 | the patch passed |
| +1 | javac | 68 | the patch passed |
| -0 | checkstyle | 18 | The patch fails to run checkstyle in hadoop-hdds |
| -1 | mvnsite | 13 | server-scm in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 741 | patch has no errors when building and testing our client artifacts. |
| -1 | findbugs | 16 | server-scm in the patch failed. |
| -1 | javadoc | 16 | server-scm in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 73 | common in the patch failed. |
| -1 | unit | 16 | server-scm in the patch failed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 3366 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.security.x509.certificate.client.TestDefaultCertificateClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/518 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux 970154b15eab 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / a6ab371 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/artifact/out//testptch/patchprocess/maven-branch-checkstyle-hadoop-hdds.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/artifact/out/branch-mvnsite-hadoop-hdds_server-scm.txt |
| findbugs | v3.1.0-RC1 |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/artifact/out/branch-findbugs-hadoop-hdds_server-scm.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/artifact/out/branch-javadoc-hadoop-hdds_server-scm.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/artifact/out/patch-mvninstall-hadoop-hdds_server-scm.txt |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/artifact/out//testptch/patchprocess/maven-patch-checkstyle-hadoop-hdds.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/artifact/out/patch-mvnsite-hadoop-hdds_server-scm.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/artifact/out/patch-findbugs-hadoop-hdds_server-scm.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/artifact/out/patch-javadoc-hadoop-hdds_server-scm.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/artifact/out/patch-unit-hadoop-hdds_common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/artifact/out/patch-unit-hadoop-hdds_server-scm.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/testReport/ |
| Max. process+thread count | 436 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-hdds/server-scm U: hadoop-hdds |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by anuengineer** [comment]
A couple of comments:
1. Why is it 10% isn't that too low?
2. I see that for each pipeline report arrival, we check the pipeline manager for the state -- to check if the pipeline is in healthy. Isn't there a race condition here?  How do we guarantee that this check and the pipeline report update does not race each other?

**Comment by bharatviswa504** [comment]
Thank You @anuengineer  for the review.
1. Low 10% is, as this rule main purpose is once we are out of chill mode, we have atleast few pipelines for writes to succeed. (As other rules like container chill mode rule, pipeline rule with at least one datanode reported by the time these completed, we might have more pipelines, this rule is more like a conservative side.) Let me know if you want to change it to any other default value.
2. Thanks for catching it. done.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 26 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 65 | Maven dependency ordering for branch |
| +1 | mvninstall | 1000 | trunk passed |
| +1 | compile | 928 | trunk passed |
| +1 | checkstyle | 176 | trunk passed |
| -1 | mvnsite | 20 | server-scm in trunk failed. |
| -1 | mvnsite | 28 | integration-test in trunk failed. |
| +1 | shadedclient | 973 | branch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| -1 | findbugs | 18 | server-scm in trunk failed. |
| -1 | javadoc | 21 | server-scm in trunk failed. |
| -1 | javadoc | 16 | integration-test in trunk failed. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 21 | Maven dependency ordering for patch |
| -1 | mvninstall | 10 | server-scm in the patch failed. |
| -1 | mvninstall | 11 | integration-test in the patch failed. |
| +1 | compile | 858 | the patch passed |
| +1 | javac | 858 | the patch passed |
| +1 | checkstyle | 176 | the patch passed |
| -1 | mvnsite | 16 | server-scm in the patch failed. |
| -1 | mvnsite | 17 | integration-test in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 597 | patch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| -1 | findbugs | 16 | server-scm in the patch failed. |
| -1 | javadoc | 20 | server-scm in the patch failed. |
| -1 | javadoc | 18 | integration-test in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 67 | common in the patch failed. |
| -1 | unit | 17 | server-scm in the patch failed. |
| -1 | unit | 16 | integration-test in the patch failed. |
| +1 | asflicense | 33 | The patch does not generate ASF License warnings. |
| | | 5491 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.security.x509.certificate.client.TestDefaultCertificateClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/518 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux a181993c2126 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c6ea28c |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/branch-mvnsite-hadoop-hdds_server-scm.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/branch-mvnsite-hadoop-ozone_integration-test.txt |
| findbugs | v3.1.0-RC1 |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/branch-findbugs-hadoop-hdds_server-scm.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/branch-javadoc-hadoop-hdds_server-scm.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/branch-javadoc-hadoop-ozone_integration-test.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/patch-mvninstall-hadoop-hdds_server-scm.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/patch-mvninstall-hadoop-ozone_integration-test.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/patch-mvnsite-hadoop-hdds_server-scm.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/patch-mvnsite-hadoop-ozone_integration-test.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/patch-findbugs-hadoop-hdds_server-scm.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/patch-javadoc-hadoop-hdds_server-scm.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/patch-javadoc-hadoop-ozone_integration-test.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/patch-unit-hadoop-hdds_common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/patch-unit-hadoop-hdds_server-scm.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/artifact/out/patch-unit-hadoop-ozone_integration-test.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/testReport/ |
| Max. process+thread count | 411 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-hdds/server-scm hadoop-ozone/integration-test U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 23 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 22 | Maven dependency ordering for branch |
| +1 | mvninstall | 965 | trunk passed |
| +1 | compile | 906 | trunk passed |
| +1 | checkstyle | 177 | trunk passed |
| -1 | mvnsite | 18 | server-scm in trunk failed. |
| -1 | mvnsite | 24 | integration-test in trunk failed. |
| +1 | shadedclient | 907 | branch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| -1 | findbugs | 27 | server-scm in trunk failed. |
| -1 | javadoc | 28 | server-scm in trunk failed. |
| -1 | javadoc | 28 | integration-test in trunk failed. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 22 | Maven dependency ordering for patch |
| -1 | mvninstall | 10 | server-scm in the patch failed. |
| -1 | mvninstall | 12 | integration-test in the patch failed. |
| +1 | compile | 881 | the patch passed |
| +1 | javac | 881 | the patch passed |
| +1 | checkstyle | 170 | the patch passed |
| -1 | mvnsite | 20 | server-scm in the patch failed. |
| -1 | mvnsite | 20 | integration-test in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 600 | patch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| -1 | findbugs | 16 | server-scm in the patch failed. |
| -1 | javadoc | 18 | server-scm in the patch failed. |
| -1 | javadoc | 17 | integration-test in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 76 | common in the patch failed. |
| -1 | unit | 17 | server-scm in the patch failed. |
| -1 | unit | 16 | integration-test in the patch failed. |
| +1 | asflicense | 32 | The patch does not generate ASF License warnings. |
| | | 5385 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.security.x509.certificate.client.TestDefaultCertificateClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/518 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux cc6ae75c04dd 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c6ea28c |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/branch-mvnsite-hadoop-hdds_server-scm.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/branch-mvnsite-hadoop-ozone_integration-test.txt |
| findbugs | v3.1.0-RC1 |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/branch-findbugs-hadoop-hdds_server-scm.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/branch-javadoc-hadoop-hdds_server-scm.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/branch-javadoc-hadoop-ozone_integration-test.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/patch-mvninstall-hadoop-hdds_server-scm.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/patch-mvninstall-hadoop-ozone_integration-test.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/patch-mvnsite-hadoop-hdds_server-scm.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/patch-mvnsite-hadoop-ozone_integration-test.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/patch-findbugs-hadoop-hdds_server-scm.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/patch-javadoc-hadoop-hdds_server-scm.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/patch-javadoc-hadoop-ozone_integration-test.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/patch-unit-hadoop-hdds_common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/patch-unit-hadoop-hdds_server-scm.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/artifact/out/patch-unit-hadoop-ozone_integration-test.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/testReport/ |
| Max. process+thread count | 445 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-hdds/server-scm hadoop-ozone/integration-test U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by elek** [comment]
One test failure seems to be related:

```
java.lang.AssertionError: class org.apache.hadoop.ozone.OzoneConfigKeys class org.apache.hadoop.hdds.scm.ScmConfigKeys class org.apache.hadoop.ozone.om.OMConfigKeys class org.apache.hadoop.hdds.HddsConfigKeys class org.apache.hadoop.ozone.s3.S3GatewayConfigKeys has 1 variables missing in ozone-default.xml Entries:   hdds.scm.chillmode.healthy.pipelie.pct expected:<0> but was:<1>
```

ozone-default.xml should be updated with the new configuration.

**Comment by anuengineer** [comment]
+1, Thanks for the update. Looks good to me.

**Comment by anuengineer** [comment]
sorry, is this failure related to this patch? 
hdds.scm.chillmode.healthy.pipelie.pct expected:<0> but was:<1>
if so, can we please add this field to the ozone-default.xml before we commit this? thanks

**Comment by bharatviswa504** [comment]
Thank You @anuengineer  and @elek  for the review.
I have fixed the test failure.

**Comment by anuengineer** [comment]
:+1: , feel free to commit once we get a Jenkins run. Thanks for taking care of this.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 23 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 22 | Maven dependency ordering for branch |
| +1 | mvninstall | 968 | trunk passed |
| +1 | compile | 949 | trunk passed |
| +1 | checkstyle | 233 | trunk passed |
| +1 | mvnsite | 157 | trunk passed |
| +1 | shadedclient | 1062 | branch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 113 | trunk passed |
| +1 | javadoc | 90 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 21 | Maven dependency ordering for patch |
| +1 | mvninstall | 101 | the patch passed |
| +1 | compile | 884 | the patch passed |
| +1 | javac | 884 | the patch passed |
| +1 | checkstyle | 188 | the patch passed |
| +1 | mvnsite | 123 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 704 | patch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 122 | the patch passed |
| +1 | javadoc | 83 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 69 | common in the patch failed. |
| +1 | unit | 97 | server-scm in the patch passed. |
| -1 | unit | 537 | integration-test in the patch failed. |
| +1 | asflicense | 38 | The patch does not generate ASF License warnings. |
| | | 6442 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.security.x509.certificate.client.TestDefaultCertificateClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-518/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/518 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  xml  |
| uname | Linux ae75be440e0a 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 9192f71 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/4/artifact/out/patch-unit-hadoop-hdds_common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/4/artifact/out/patch-unit-hadoop-ozone_integration-test.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/4/testReport/ |
| Max. process+thread count | 3556 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-hdds/server-scm hadoop-ozone/integration-test U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-518/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by elek** [comment]
Thanks @anuengineer the review and @bharatviswa504 the PR. I am pushing it to the trunk. 

I checked the remaining unit tests and they are not related.

**Pull request closed without merging**
