### PR TITLE
HDDS-1662.Missing test resources of integrataion-test project in targ…

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/HDDS-1662

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 523 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 539 | trunk passed |
| +1 | compile | 290 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1632 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 163 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 454 | the patch passed |
| +1 | compile | 296 | the patch passed |
| +1 | javac | 296 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 679 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 157 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 136 | hadoop-hdds in the patch failed. |
| -1 | unit | 1220 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 55 | The patch does not generate ASF License warnings. |
| | | 5521 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.container.common.impl.TestHddsDispatcher |
|   | hadoop.ozone.TestMiniOzoneCluster |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-933/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/933 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 4f1455e21b77 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / fcfe7a3 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-933/1/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-933/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-933/1/testReport/ |
| Max. process+thread count | 4888 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/integration-test U: hadoop-ozone/integration-test |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-933/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by ChenSammi** [comment]
The failed UTs are irrelevant.

**Comment by xiaoyuyao** [comment]
+1 pending CI.

**Comment by ChenSammi** [comment]
@elek , thanks for the approve. Without reference the ${basedir}/../../hadoop-hdds/common/src/main/resources, many unit tests will pass in IDE, but fail with "mvn test -Dtest=testClass". The root cause is  Thread.currentThread().getContextClassLoader().getResource("filename").toURI() will not return a normal URI  if the specified file is packaged in a jar file.

**Comment by elek** [comment]
Thanks the information @ChenSammi 

In the mean time I found that the smoketest are also failed because a similar problem: scm can't be started as the default network topology file can't be loaded from the classpath.

I think it can be fixed with using the `classloader.getResourceAsStream` instead of `classloader.getResource().toURI()`. See #946 about my proposal. Can you please review it?

**Comment by ChenSammi** [comment]
@elek,  You are right. We can use getResourceAsStream instead.  Thanks for improve the code to solve the issue. 
I base in Shanghai. Sorry for miss the review.

**Comment by elek** [comment]
No problem. Sorry to not wait for enough time. Usually I prefer to wait at least one day to give the chance to all the time zones to comment it (I am GMT+1/+2)

But this was a small fix and it's blocked my CI comments. And I am ready to improve it if you have any further comments....

**Pull request closed without merging**
