### PR TITLE
HADOOP-18209. Fix links to DataNodes in NameNode UI to support IPv6

### PR DESCRIPTION
**Pull request by prasad-acit**
…

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by prasad-acit** [comment]
@brahmareddybattula @hemanthboyina ,
Please review the MR when you get time. Thank you.

**Review by liuml07 — APPROVED** [review]

**Comment by liuml07** [comment]
As there is no test, could you upload a screenshot with this fix? Thanks,

**Comment by prasad-acit** [comment]
Thanks @liuml07 for quick review & feedback.
Updated the snapshot of the fix, please review.

**Comment by liuml07** [comment]
@prasad-acit Just noticed that your PR is against a feature branch `HADOOP-17800`. Was that intentional? For changes like this I assume it's safe to get in to `trunk` and active release versions directly. @brahmareddybattula thoughs?

**Comment by prasad-acit** [comment]
Thank you @liuml07 ,
HADOOP-17800 got branched out from trunk recently & started merging from older IPv6 branch (HADOOP-11890).
Yes, @brahmareddybattula can clarify it further.

**Comment by prasad-acit** [comment]
> Thank you @liuml07 , [HADOOP-17800](https://issues.apache.org/jira/browse/HADOOP-17800) got branched out from trunk recently & started merging from older IPv6 branch ([HADOOP-11890](https://issues.apache.org/jira/browse/HADOOP-11890)). Yes, @brahmareddybattula can clarify it further.

@hemanthboyina Do you have any thought on this?

**Pull request merged**
