### PR TITLE
HADOOP-17627. Backport to branch-3.2 HADOOP-17371, HADOOP-17621, HADOOP-17625 to update Jetty to 9.4.39.

### PR DESCRIPTION
**Pull request by jojochuang**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  10m  6s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 26s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  24m 21s |  |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |  16m 16s |  |  branch-3.2 passed  |
| +1 :green_heart: |  checkstyle  |   2m 26s |  |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |   4m 57s |  |  branch-3.2 passed  |
| +1 :green_heart: |  javadoc  |   4m 23s |  |  branch-3.2 passed  |
| +0 :ok: |  spotbugs  |   0m 31s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 30s |  |  branch/hadoop-client-modules/hadoop-client-minicluster no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  15m 51s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 40s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   7m 33s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 28s |  |  the patch passed  |
| -1 :x: |  javac  |  17m 28s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/1/artifact/out/results-compile-javac-root.txt) |  root generated 1 new + 1547 unchanged - 0 fixed = 1548 total (was 1547)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m 52s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   5m 20s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  4s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   3m 58s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 27s |  |  hadoop-project has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 25s |  |  hadoop-client-modules/hadoop-client-minicluster has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  13m 39s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 23s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |   3m  4s |  |  hadoop-auth in the patch passed.  |
| -1 :x: |  unit  |  16m 22s | [/patch-unit-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/1/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt) |  hadoop-common in the patch failed.  |
| -1 :x: |  unit  |   3m 39s | [/patch-unit-hadoop-common-project_hadoop-kms.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/1/artifact/out/patch-unit-hadoop-common-project_hadoop-kms.txt) |  hadoop-kms in the patch failed.  |
| -1 :x: |  unit  | 177m 17s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  unit  |   0m 31s |  |  hadoop-client-minicluster in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 54s |  |  The patch does not generate ASF License warnings.  |
|  |   | 354m 40s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.io.compress.snappy.TestSnappyCompressorDecompressor |
|   | hadoop.io.compress.TestCompressorDecompressor |
|   | hadoop.crypto.key.kms.server.TestKMS |
|   | hadoop.hdfs.server.namenode.TestRedudantBlocks |
|   | hadoop.hdfs.server.namenode.TestAddOverReplicatedStripedBlocks |
|   | hadoop.hdfs.server.datanode.TestBlockRecovery |
|   | hadoop.hdfs.server.namenode.TestFsck |
|   | hadoop.hdfs.TestRollingUpgrade |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2879 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux cfebb026e758 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / 26dd37ae2040f7659994b494b0219eec43af157f |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~18.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/1/testReport/ |
| Max. process+thread count | 2611 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-common hadoop-common-project/hadoop-kms hadoop-hdfs-project/hadoop-hdfs hadoop-client-modules/hadoop-client-minicluster U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
TestKMS failure is unrelated, due to HADOOP-17608

**Comment by jojochuang** [comment]
The rest of test failures are flaky. Not reproducible locally.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  16m 12s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 24s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  31m 20s |  |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |  20m 59s |  |  branch-3.2 passed  |
| +1 :green_heart: |  checkstyle  |   3m  5s |  |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |   6m  2s |  |  branch-3.2 passed  |
| +1 :green_heart: |  javadoc  |   4m 33s |  |  branch-3.2 passed  |
| +0 :ok: |  spotbugs  |   0m 31s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 26s |  |  branch/hadoop-client-modules/hadoop-client-minicluster no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  17m 25s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 49s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  10m  4s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  29m  4s |  |  the patch passed  |
| -1 :x: |  javac  |  29m  4s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/2/artifact/out/results-compile-javac-root.txt) |  root generated 1 new + 1547 unchanged - 0 fixed = 1548 total (was 1547)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   4m 50s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   8m  4s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  8s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   5m 33s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 42s |  |  hadoop-project has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 34s |  |  hadoop-client-modules/hadoop-client-minicluster has no data from spotbugs  |
| -1 :x: |  shadedclient  |  16m 42s |  |  patch has errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 40s | [/patch-unit-hadoop-project.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/2/artifact/out/patch-unit-hadoop-project.txt) |  hadoop-project in the patch failed.  |
| -1 :x: |  unit  |   0m 40s | [/patch-unit-hadoop-common-project_hadoop-auth.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/2/artifact/out/patch-unit-hadoop-common-project_hadoop-auth.txt) |  hadoop-auth in the patch failed.  |
| -1 :x: |  unit  |  13m 27s | [/patch-unit-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/2/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt) |  hadoop-common in the patch failed.  |
| -1 :x: |  unit  |   1m 31s | [/patch-unit-hadoop-common-project_hadoop-kms.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/2/artifact/out/patch-unit-hadoop-common-project_hadoop-kms.txt) |  hadoop-kms in the patch failed.  |
| -1 :x: |  unit  |   0m 36s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/2/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  unit  |   0m 37s |  |  hadoop-client-minicluster in the patch passed.  |
| -1 :x: |  asflicense  |   1m  7s | [/results-asflicense.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/2/artifact/out/results-asflicense.txt) |  The patch generated 12 ASF License warnings.  |
|  |   | 219m 37s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.util.TestDataChecksum |
|   | hadoop.io.compress.TestCompressorDecompressor |
|   | hadoop.fs.TestTrash |
|   | hadoop.io.compress.snappy.TestSnappyCompressorDecompressor |
|   | hadoop.crypto.key.kms.server.TestKMS |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2879 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux b944e5dfc8e2 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / 26dd37ae2040f7659994b494b0219eec43af157f |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~18.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/2/testReport/ |
| Max. process+thread count | 307 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-common hadoop-common-project/hadoop-kms hadoop-hdfs-project/hadoop-hdfs hadoop-client-modules/hadoop-client-minicluster U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
Lots of unrelated OOM errors. Trigger the build again.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m 21s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 18s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  27m  1s |  |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |  16m 50s |  |  branch-3.2 passed  |
| +1 :green_heart: |  checkstyle  |   2m 41s |  |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |   4m 34s |  |  branch-3.2 passed  |
| +1 :green_heart: |  javadoc  |   3m 57s |  |  branch-3.2 passed  |
| +0 :ok: |  spotbugs  |   0m 28s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 26s |  |  branch/hadoop-client-modules/hadoop-client-minicluster no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  16m 33s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 33s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   7m 20s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  15m 40s |  |  the patch passed  |
| -1 :x: |  javac  |  15m 40s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/3/artifact/out/results-compile-javac-root.txt) |  root generated 1 new + 1547 unchanged - 0 fixed = 1548 total (was 1547)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m 44s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   4m 30s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  4s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   3m 46s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 25s |  |  hadoop-project has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 26s |  |  hadoop-client-modules/hadoop-client-minicluster has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  14m  7s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 23s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 18s |  |  hadoop-auth in the patch passed.  |
| -1 :x: |  unit  |  15m 19s | [/patch-unit-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/3/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt) |  hadoop-common in the patch failed.  |
| +1 :green_heart: |  unit  |   3m 38s |  |  hadoop-kms in the patch passed.  |
| -1 :x: |  unit  | 189m  4s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/3/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  unit  |   0m 32s |  |  hadoop-client-minicluster in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 51s |  |  The patch does not generate ASF License warnings.  |
|  |   | 355m 46s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.io.compress.TestCompressorDecompressor |
|   | hadoop.io.compress.snappy.TestSnappyCompressorDecompressor |
|   | hadoop.hdfs.server.namenode.TestEditLogRace |
|   | hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2879 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux e482e7a5b1f1 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / 26dd37ae2040f7659994b494b0219eec43af157f |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~18.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/3/testReport/ |
| Max. process+thread count | 2072 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-common hadoop-common-project/hadoop-kms hadoop-hdfs-project/hadoop-hdfs hadoop-client-modules/hadoop-client-minicluster U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2879/3/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
Merging it. I confirmed none of the tests is reproducible locally.

**Pull request merged**
