### PR TITLE
HDFS-14835. RBF: Secured Router should not run when it can't initialize DelegationTokenSecretManager

### PR DESCRIPTION
**Pull request by tasanuma**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1033 | trunk passed |
| +1 | compile | 33 | trunk passed |
| +1 | checkstyle | 25 | trunk passed |
| +1 | mvnsite | 37 | trunk passed |
| +1 | shadedclient | 751 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 40 | trunk passed |
| 0 | spotbugs | 66 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 65 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 29 | the patch passed |
| +1 | compile | 26 | the patch passed |
| +1 | javac | 26 | the patch passed |
| +1 | checkstyle | 18 | the patch passed |
| +1 | mvnsite | 30 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 754 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 38 | the patch passed |
| +1 | findbugs | 66 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 1421 | hadoop-hdfs-rbf in the patch failed. |
| +1 | asflicense | 30 | The patch does not generate ASF License warnings. |
| | | 4560 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.federation.router.TestRouterWithSecureStartup |
|   | hadoop.hdfs.server.federation.security.TestRouterHttpDelegationToken |
|   | hadoop.hdfs.server.federation.router.TestRouterFaultTolerant |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1414/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1414 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 6b8b7431aac9 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 60af879 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1414/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs-rbf.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1414/1/testReport/ |
| Max. process+thread count | 1604 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-rbf U: hadoop-hdfs-project/hadoop-hdfs-rbf |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1414/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by goiri** [comment]
Thanks @tasanuma for the patch.
I think it makes sense.
@chittshota would you mind taking a look too?

**Comment by chittshota** [comment]
@tasanuma Thanks for reporting this. 
@goiri  Thanks for tagging me.

While working on this area earlier I was aware of this issue.
I am not quite certain with this change. Tokens are just one way to authenticate against routers. Hence failing it to start when secret manager is broken may not always make sense. In instances where kerberos is sufficient, admins will be forced to set up secret managers.

**Comment by tasanuma** [comment]
@goiri @chittshota Thanks for your reviews.

In this PR, the error occurs only when the authentication method is kerberos. Given that YARN uses delegation tokens to communicate with HDFS when the authentication method is  kerberos, I think kerberized router should fail to start if secret manager is broken.

**Comment by chittshota** [comment]
@tasanuma That's a good point. I was checking namenode to see if it does throw any exceptions if secret manager could not be successfully initialized. Namenode DOES fail if secret manager is not initialized correctly so yes then router failing should be fine.

 ```
 private void startSecretManager() {
    if (dtSecretManager != null) {
      try {
        dtSecretManager.startThreads();
      } catch (IOException e) {
        // Inability to start secret manager
        // can't be recovered from.
        throw new RuntimeException(e);
      }
    }
  }

```

LGTM. +1

**Comment by tasanuma** [comment]
@chittshota Thanks for your confirmation! I will merge it soon.

**Pull request merged**
