### PR TITLE
HDFS-15301. statfs function in hdfs-fuse not working - fixed.

### PR DESCRIPTION
**Pull request by aryangupta1998**
statfs function in hdfs-fuse is not working. It gives error like:

could not find method org/apache/hadoop/fs/FsStatus from class org/apache/hadoop/fs/FsStatus with signature getUsed

hdfsGetUsed: FsStatus#getUsed error:

NoSuchMethodError: org/apache/hadoop/fs/FsStatusjava.lang.NoSuchMethodError: org/apache/hadoop/fs/FsStatus

Problem: Incorrect passing of parameters in invokeMethod function.
invokeMethod(env, &jVal, INSTANCE, fss, JC_FS_STATUS,
HADOOP_FSSTATUS,"getUsed", "()J");

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 16s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  23m 37s |  trunk passed  |
| +1 :green_heart: |  compile  |   2m 10s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 22s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  42m  6s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 59s |  the patch passed  |
| +1 :green_heart: |  cc  |   1m 59s |  the patch passed  |
| +1 :green_heart: |  golang  |   1m 59s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 59s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 30s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   8m  5s |  hadoop-hdfs-native-client in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 35s |  The patch does not generate ASF License warnings.  |
|  |   |  72m 29s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1980/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1980 |
| Optional Tests | dupname asflicense compile cc mvnsite javac unit golang |
| uname | Linux 87418467664c 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 18d7dfbf355 |
| Default Java | Private Build-1.8.0_252-8u252-b09-1~18.04-b09 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1980/1/testReport/ |
| Max. process+thread count | 307 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-native-client U: hadoop-hdfs-project/hadoop-hdfs-native-client |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1980/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
Thanks for the patch. It's a shame such a simple error exists.
Have you verified the fix? Do you think it's possible to add a test?

**Comment by aryangupta1998** [comment]
> Thanks for the patch. It's a shame such a simple error exists.
> Have you verified the fix? Do you think it's possible to add a test?

Yeah I have verified the fix, it’s working fine.

**Comment by fapifta** [comment]
Changes looks good to me, especially based on the error message. Nice catch @aryangupta1998 an thank you for the PR.

One thing I would like to be taken care of is indentation, as I see in the patch the fixed line lost the indentation along with the used constant, it would be great to fix it, and then I am +1 to commit the change (non-binding).

**Comment by aryangupta1998** [comment]
> Changes looks good to me, especially based on the error message. Nice catch @aryangupta1998 an thank you for the PR.
> 
> One thing I would like to be taken care of is indentation, as I see in the patch the fixed line lost the indentation along with the used constant, it would be great to fix it, and then I am +1 to commit the change (non-binding).

Indentation fixed

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 10s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  23m 22s |  trunk passed  |
| +1 :green_heart: |  compile  |   2m  4s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 21s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  41m 29s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m  0s |  the patch passed  |
| +1 :green_heart: |  cc  |   2m  0s |  the patch passed  |
| +1 :green_heart: |  golang  |   2m  0s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m  0s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 39s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   8m  9s |  hadoop-hdfs-native-client in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 34s |  The patch does not generate ASF License warnings.  |
|  |   |  72m 14s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1980/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1980 |
| Optional Tests | dupname asflicense compile cc mvnsite javac unit golang |
| uname | Linux 1c0d4fe74dae 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 5e0eda5d5f6 |
| Default Java | Private Build-1.8.0_252-8u252-b09-1~18.04-b09 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1980/2/testReport/ |
| Max. process+thread count | 306 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-native-client U: hadoop-hdfs-project/hadoop-hdfs-native-client |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1980/2/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
