### PR TITLE
HADOOP-18829. S3A prefetch LRU cache eviction metrics (#5893)

### PR DESCRIPTION
**Pull request by virajjasani**
branch-3.3 backport of PR #5893

### CODE REVIEW

**Comment by virajjasani** [comment]
Testing in progress.

FYI @mehakmeet

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   7m 32s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 4 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 43s |  |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |  35m 32s | [/branch-mvninstall-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6111/1/artifact/out/branch-mvninstall-root.txt) |  root in branch-3.3 failed.  |
| +1 :green_heart: |  compile  |  19m  4s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   2m 53s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   2m 52s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   1m 52s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   4m  9s |  |  branch-3.3 passed  |
| -1 :x: |  shadedclient  |  37m 36s |  |  branch has errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 33s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 43s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 37s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  18m 37s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m 42s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m 52s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 45s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   4m 23s |  |  the patch passed  |
| -1 :x: |  shadedclient  |  38m 40s |  |  patch has errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  18m 31s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 55s |  |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  8s |  |  The patch does not generate ASF License warnings.  |
|  |   | 225m 38s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6111/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6111 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 3acb0ff4d744 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / e9679a2161cfb9d327254555850828f9cb6fe5b2 |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~18.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6111/1/testReport/ |
| Max. process+thread count | 3137 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6111/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
Tested against `us-west-2`:
`mvn clean verify -Dparallel-tests -DtestsThreadCount=8 -Dscale -Dprefetch`

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 26s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 4 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  15m  0s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  22m 40s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  12m  8s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   2m 10s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   2m  5s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   1m 24s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   2m 45s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  23m 55s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 10s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  11m 33s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  11m 33s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m 40s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m  0s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 20s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   2m 58s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  24m  1s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  15m 41s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 25s |  |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 50s |  |  The patch does not generate ASF License warnings.  |
|  |   | 150m 25s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6111/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6111 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 9ad6cea68418 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / e9679a2161cfb9d327254555850828f9cb6fe5b2 |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~18.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6111/2/testReport/ |
| Max. process+thread count | 2482 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6111/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
@mehakmeet could you please help with this backport PR?

**Comment by mehakmeet** [comment]
Sorry, missed this one. Merged now. Thanks.

**Comment by virajjasani** [comment]
Thanks @mehakmeet

**Pull request merged**
