### PR TITLE
YARN-11245. Upgrade JUnit from 4 to 5 in hadoop-yarn-csi

### PR DESCRIPTION
**Pull request by hotcodemacha**
### Description of PR

Upgrade JUnit from 4 to 5 in hadoop-yarn-csi

JIRA - YARN-11245

### For code changes:

- [X] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by slfan1989** [comment]
@ashutoshcipher @aajisaka From my personal point of view, this change is valuable, but can we provide some suggestions to developers, such as which methods we should use in junit5. Forcibly changing the habits of developers is not very friendly. 

@ashutoshcipher Thanks a lot for your contribution, but it's better to let the developers know the best practices in junit5.

**Comment by hotcodemacha** [comment]
@slfan1989 - We are not forcing the developers to change any habits. This upgrade is required for `Java 11 compile support`. 

Please feel to check online for best practices in junit5. I am sure you will get many links. Also `best-practices` are very much subjective.

**Comment by slfan1989** [comment]
> Please feel to check online for best practices in junit5. I am sure you will get many links. Also `best-practices` are very much subjective.

I think the responsible approach is that the community should give a guide, such as which methods of junit4 are replaced with which methods of junit5, rather than encouraging developers to search the Internet.

**Comment by slfan1989** [comment]
> We are not forcing the developers to change any habits. This upgrade is required for `Java 11 compile support`.

@ashutoshcipher This is very necessary, I can recognize the value of this, and thank you very much for your contribution, but it is better to give a guide first.

**Comment by hotcodemacha** [comment]
@slfan1989 - To know which methods of junit4 are replaced with which methods of junit5. You can see previous PRs - they will be very much informative to know such things :)

**Comment by slfan1989** [comment]
> @slfan1989 - To know which methods of junit4 are replaced with which methods of junit5. You can see previous PRs - they will be very much informative to know such things :)

I still feel that this is not very friendly, let's look at other partners' suggestions.

**Comment by hotcodemacha** [comment]
>I think the responsible approach is that the community should give a guide

I feel community is already busy with so many things. I am atleast personally not expecting from someone to sit and write down best practices for upgrading Junit 4 to Junit 5 for me. But if someone want/can do it, I am very much happy :)

We are all learners and its upto us to decide how we want to learn :) 

FYI - Currently, This is being followed - https://github.com/openrewrite/rewrite-docs/tree/b187223ddcbf369a77a86efd6950e924fd91f00d/reference/recipes/java/testing/junit5

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 51s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 6 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  38m 25s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   0m 52s |  |  trunk passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  compile  |   0m 50s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  checkstyle  |   0m 47s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 55s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   0m 56s |  |  trunk passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |   0m 44s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  spotbugs  |   1m 32s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  20m 54s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 35s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 35s |  |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javac  |   0m 35s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 32s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |   0m 32s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 22s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 35s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 29s |  |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |   0m 28s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  spotbugs  |   1m  9s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  20m 14s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 55s |  |  hadoop-yarn-csi in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 51s |  |  The patch does not generate ASF License warnings.  |
|  |   |  95m  7s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4778/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4778 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint spotbugs checkstyle |
| uname | Linux 225547b1df51 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / e8e42a8a9f34816ed0e7ffb24bc2a9c827bee02c |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4778/1/testReport/ |
| Max. process+thread count | 699 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-csi U: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-csi |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4778/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by aajisaka — APPROVED** [review]

**Comment by aajisaka** [comment]
@slfan1989 @ashutoshcipher Thank you for the discussion

> I feel community is already busy with so many things. I am atleast personally not expecting from someone to sit and write down best practices for upgrading Junit 4 to Junit 5 for me. But if someone want/can do it, I am very much happy :)

+1 to write down best practices. In this case, now I like using AssertJ APIs as they are more fluent and their error messages are user-friendly, but I think we can continue to use JUnit 5 APIs because it's the similar experience as existing JUnit 4 APIs and it's more easier to use for the upgrade rather than replacing all the APIs with AssertJ.

**Pull request merged**
