### PR TITLE
HDDS-1832 : Improve logging for PipelineActions handling in SCM and datanode.

### PR DESCRIPTION
**Pull request by avijayanhwx**
Added logging.

### CODE REVIEW

**Comment by vivekratnavel** [comment]
+1 LGTM (non-binding).

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 107 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for branch |
| +1 | mvninstall | 633 | trunk passed |
| +1 | compile | 399 | trunk passed |
| +1 | checkstyle | 77 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1031 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 166 | trunk passed |
| 0 | spotbugs | 433 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 631 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 21 | Maven dependency ordering for patch |
| +1 | mvninstall | 559 | the patch passed |
| +1 | compile | 374 | the patch passed |
| +1 | javac | 374 | the patch passed |
| +1 | checkstyle | 78 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 736 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 186 | the patch passed |
| +1 | findbugs | 719 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 362 | hadoop-hdds in the patch failed. |
| -1 | unit | 1965 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 41 | The patch does not generate ASF License warnings. |
| | | 8262 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.client.rpc.TestWatchForCommit |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.hdds.scm.pipeline.TestPipelineClose |
|   | hadoop.hdds.scm.pipeline.TestRatisPipelineCreateAndDestory |
|   | hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures |
|   | hadoop.ozone.client.rpc.TestMultiBlockWritesWithDnFailures |
|   | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1200/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1200 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 52369254f8ef 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / b008072 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1200/1/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1200/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1200/1/testReport/ |
| Max. process+thread count | 3922 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/container-service hadoop-hdds/server-scm U: hadoop-hdds |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1200/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 71 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 11 | Maven dependency ordering for branch |
| +1 | mvninstall | 628 | trunk passed |
| +1 | compile | 370 | trunk passed |
| +1 | checkstyle | 70 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 968 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 171 | trunk passed |
| 0 | spotbugs | 480 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 692 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 22 | Maven dependency ordering for patch |
| +1 | mvninstall | 572 | the patch passed |
| +1 | compile | 379 | the patch passed |
| +1 | javac | 379 | the patch passed |
| +1 | checkstyle | 79 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 751 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 182 | the patch passed |
| +1 | findbugs | 692 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 345 | hadoop-hdds in the patch failed. |
| -1 | unit | 2127 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 56 | The patch does not generate ASF License warnings. |
| | | 8337 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.scm.block.TestBlockManager |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestWatchForCommit |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.ozone.client.rpc.TestMultiBlockWritesWithDnFailures |
|   | hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |
|   | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.hdds.scm.pipeline.TestRatisPipelineProvider |
|   | hadoop.ozone.client.rpc.TestCommitWatcher |
|   | hadoop.hdds.scm.pipeline.TestRatisPipelineCreateAndDestory |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1200/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1200 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 14a028e78af8 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / f86de6f |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1200/2/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1200/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1200/2/testReport/ |
| Max. process+thread count | 5317 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/container-service hadoop-hdds/server-scm U: hadoop-hdds |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1200/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by bshashikant** [comment]
Thanks @avijayanhwx for working on this. The change looks good to me. +1

**Pull request merged**
