### PR TITLE
HADOOP-19310. Add JPMS options required by Java 17+

### PR DESCRIPTION
**Pull request by pan3793**
HADOOP-19310. Add JPMS options required by Java 17+

### Description of PR

This PR adds JPMS args to both maven surefire plugin and `hadoop-functions.sh`, to fix issues like the below that happen with JDK 17+, for all of the modules in the Hadoop project.

```
module java.base does not "opens java.lang" to unnamed module @7ee7980d
```

This is the next step of HADOOP-19219, which fixes the JPMS issues for `hadoop-common`.

### How was this patch tested?

Test environment: x86 Ubuntu 22.04, Zulu JDK 17.0.8, Maven 3.9.8

Run all tests except for
1. native tests -further native libraries setup steps are required that I'm not familiar with.
2. an [exclude-tests.txt](https://github.com/pan3793/hadoop/blob/trunk-java17/dev-support/java-17/exclude-tests.txt) list that failed on JDK 17 due to other reasons that need to be addressed independently.
3. `hadoop-yarn-server-timelineservice-hbase-tests` -surefire runs in non-fork mode thus JPMS args do not take effect.

```
mvn clean install --fail-at-end \
  -Dsurefire.excludesFile=$PWD/dev-support/java-17/exclude-tests.txt
```

The whole UT takes around 18-24 hours to finish, for developers who want to contribute to Java 17 support, please focus on the [exclude-tests.txt](https://github.com/pan3793/hadoop/blob/trunk-java17/dev-support/java-17/exclude-tests.txt), and I will update the list timely.

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by slfan1989** [comment]
LGTM

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 20s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +0 :ok: |  xmllint  |   0m  1s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 56s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  19m  3s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   9m  9s |  |  trunk passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  compile  |   8m 30s |  |  trunk passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  mvnsite  |   3m 35s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   3m 12s |  |  trunk passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javadoc  |   2m 55s |  |  trunk passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  shadedclient  |  26m  7s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 22s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 43s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   8m 43s |  |  the patch passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javac  |   8m 43s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   8m 24s |  |  the patch passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  javac  |   8m 24s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   3m 26s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  2s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   3m  4s |  |  the patch passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javadoc  |   2m 56s |  |  the patch passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  shadedclient  |  27m 33s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 25s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |  16m 35s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  3s |  |  hadoop-registry in the patch passed.  |
| +1 :green_heart: |  unit  |  24m 42s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  8s |  |  hadoop-federation-balance in the patch passed.  |
| +1 :green_heart: |  unit  |   9m 12s |  |  hadoop-yarn-server-timelineservice-hbase-tests in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 43s |  |  The patch does not generate ASF License warnings.  |
|  |   | 187m 43s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7114/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/7114 |
| Optional Tests | dupname asflicense mvnsite unit codespell detsecrets shellcheck shelldocs compile javac javadoc mvninstall shadedclient xmllint |
| uname | Linux 22007f6a3931 5.15.0-117-generic #127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 85f5859968daaf51b1bcd43f84331a0e2f5442fe |
| Default Java | Private Build-1.8.0_422-8u422-b05-1~20.04-b05 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_422-8u422-b05-1~20.04-b05 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7114/1/testReport/ |
| Max. process+thread count | 3150 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-tools/hadoop-distcp hadoop-tools/hadoop-federation-balance hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7114/1/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by slfan1989 — APPROVED** [review]

**Comment by slfan1989** [comment]
@adoroszlai Can you help review this PR? Thank you very much!

**Review by adoroszlai — APPROVED** [review]
Thansk @pan3793 for the patch, LGTM.

**Comment by slfan1989** [comment]
@pan3793 Thanks for the contribution! @adoroszlai Thanks for the review!

@pan3793 Could you help submit a PR for branch-3.4?

**Pull request merged**
