### PR TITLE
HADOOP-14208. Fix typo in the top page in branch-2.8

### PR DESCRIPTION
**Pull request by wenxinhe**

### CODE REVIEW

**Comment by aajisaka** [comment]
Would you target branch-2.8 instead of branch-2.8.1?

**Comment by wenxinhe** [comment]
OK, I'll try immediately.

**Comment by aajisaka** [comment]
Would you close this PR?

**Comment by wenxinhe** [comment]
I closed it, @aajisaka, Thanks for your remind.

**Pull request closed without merging**
