### PR TITLE
HDFS-16457.Make fs.getspaceused.classname reconfigurable (apache#4069)

### PR DESCRIPTION
**Pull request by singer-bin**
Cherry-pick https://github.com/apache/hadoop/pull/4069 to branch-3.3.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   6m 55s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  35m 57s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |   1m 16s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   0m 54s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   1m 23s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   1m 36s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   3m 22s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  26m  1s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 13s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  3s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  3s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 41s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 10s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 24s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 10s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  25m 12s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 187m 21s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4156/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 51s |  |  The patch does not generate ASF License warnings.  |
|  |   | 296m 54s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.ha.TestHAAppend |
|   | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |
|   | hadoop.hdfs.tools.offlineImageViewer.TestOfflineImageViewer |
|   | hadoop.hdfs.server.namenode.ha.TestStandbyCheckpoints |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4156/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4156 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 69ab364732ba 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 3fe04d35a361b838f4e39906e32b0d3de4683531 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4156/1/testReport/ |
| Max. process+thread count | 3703 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4156/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by singer-bin** [comment]
apache#4069 has been submitted to branch-3.3, please review, the error doesn't seem to be related to my code. @tasanuma

**Review by tasanuma — APPROVED** [review]

**Comment by tasanuma** [comment]
@singer-bin Thanks for your contribution!

**Comment by singer-bin** [comment]
Also thanks to @tasanuma  for the review and suggestion, thank you.
I also have a jira [16525](https://issues.apache.org/jira/browse/HDFS-16525) I don't know if you are interested in taking a look?

**Pull request merged**
