### PR TITLE
HADOOP-16109. Parquet reading S3AFileSystem causes EOF

### PR DESCRIPTION
**Pull request by steveloughran**
HADOOP-16109. Parquet reading S3AFileSystem causes EOF

Nobody gets seek right. No matter how many times they think they have.

Reproducible test from:  Dave Christianson
Fixed seek() logic: Steve Loughran

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 7 | https://github.com/apache/hadoop/pull/535 does not apply to s3/HADOOP-16109-parquet-eof-s3a-seek. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/535 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-535/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
hey, @aw-was-here , yetus is bouncing all my PRs....

**Comment by steveloughran** [comment]
S3 testing: AWS Ireland + s3guard

**Comment by aw-was-here** [comment]
> hey, @aw-was-here , yetus is bouncing all my PRs....

"#535 does not apply to s3/HADOOP-16109-parquet-eof-s3a-seek"

Yetus knows when your parent repo is a branch.

**Comment by steveloughran** [comment]
I think I've been doing stupid things with sourcetree pushing stuff back up to apache. I used to have the source tree I did my coding on read-only, to stop me ever accidentally pushing up my private stuff and now there's confusion. Fix: edit the git remote list to not have a valid push url for apache, resubmit this

**Pull request closed without merging**
