### PR TITLE
HADOOP-17224. Install Intel ISA-L library in Dockerfile.

### PR DESCRIPTION
**Pull request by tasanuma**
## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2243/1/console in case of problems.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   3m  4s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  shadedclient  |  19m 48s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| -1 :x: |  hadolint  |   0m  3s |  The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 14s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  17m 56s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 45s |  The patch does not generate ASF License warnings.  |
|  |   |  47m 32s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2243/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2243 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs |
| uname | Linux 017dd1b7ba5c 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / c0492962355 |
| hadolint | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2243/1/artifact/out/diff-patch-hadolint.txt |
| Max. process+thread count | 420 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2243/1/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 hadolint=1.11.1-0-g0e692dd |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by tasanuma** [comment]
hadoop checknative with the change
```
$ ./start-build-env.sh
...
tasanuma@696fff23ee3a:~/hadoop$ mvn clean package -Pdist,native -Dtar -DskipTests
...
tasanuma@696fff23ee3a:~/hadoop$ ./hadoop-dist/target/hadoop-3.4.0-SNAPSHOT/bin/hadoop checknative
2020-08-25 09:54:47,466 INFO bzip2.Bzip2Factory: Successfully loaded & initialized native-bzip2 library system-native
2020-08-25 09:54:47,470 INFO zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
2020-08-25 09:54:47,589 INFO nativeio.NativeIO: The native code was built without PMDK support.
Native library checking:
hadoop:  true /home/tasanuma/hadoop/hadoop-dist/target/hadoop-3.4.0-SNAPSHOT/lib/native/libhadoop.so.1.0.0
zlib:    true /lib/x86_64-linux-gnu/libz.so.1
zstd  :  true /usr/lib/x86_64-linux-gnu/libzstd.so.1
snappy:  true /usr/lib/x86_64-linux-gnu/libsnappy.so.1
lz4:     true revision:10301
bzip2:   true /lib/x86_64-linux-gnu/libbz2.so.1
openssl: true /usr/lib/x86_64-linux-gnu/libcrypto.so
ISA-L:   true /usr/lib/libisal.so.2
PMDK:    false The native code was built without PMDK support.
```

**Comment by tasanuma** [comment]
I also confirmed that `mvn test` in the environment doesn't skip the unit tests using ISA-L library.
```
tasanuma@696fff23ee3a:~/hadoop$ mvn test -Dtest=TestNativeRSRawCoder,TestNativeXORRawCoder
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.io.erasurecode.rawcoder.TestNativeXORRawCoder
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.517 s - in org.apache.hadoop.io.erasurecode.rawcoder.TestNativeXORRawCoder
[INFO] Running org.apache.hadoop.io.erasurecode.rawcoder.TestNativeRSRawCoder
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/tasanuma/hadoop/hadoop-common-project/hadoop-common/target/surefire-reports/2020-08-25T09-59-38_459-jvmRun1.dumpstream
[INFO] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.274 s - in org.apache.hadoop.io.erasurecode.rawcoder.TestNativeRSRawCoder
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 25, Failures: 0, Errors: 0, Skipped: 0
...
```

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2243/2/console in case of problems.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   3m 58s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 19s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  shadedclient  |  18m 32s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  hadolint  |   0m  3s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 12s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 45s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   |  44m 19s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2243/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2243 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs |
| uname | Linux f0961d531061 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / cc641534dcb |
| Max. process+thread count | 414 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2243/2/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 hadolint=1.11.1-0-g0e692dd |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by iwasakims — APPROVED** [review]
+1. start-build-env.sh then build worked for me too.

**Comment by tasanuma** [comment]
@iwasakims Thanks for your review! I will merge it.

**Pull request merged**
