### PR TITLE
HADOOP-16166. TestRawLocalFileSystemContract fails with build Docker …

### PR DESCRIPTION
**Pull request by mattf-apache**
…container running on Mac.  Also provided similar fix for Windows.

As noted in the Jira, this problem was discovered when working on a Mac, in the docker container created by `start-build-env.sh`. In that environment, this unit test fails, because it doesn't take into account that a Linux process may be mounting a Mac's case-insensitive filesystem.  This patch adds recognition of that circumstance for both Mac and Windows.

Yetus testing will not see any change.  I manually tested it in the `start-build-env.sh` environment on both Mac and Win 10 Pro.  No new unit test, as this is a fix to an existing unit test.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 27 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 997 | trunk passed |
| +1 | compile | 947 | trunk passed |
| +1 | checkstyle | 45 | trunk passed |
| +1 | mvnsite | 70 | trunk passed |
| +1 | shadedclient | 709 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 93 | trunk passed |
| +1 | javadoc | 59 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 46 | the patch passed |
| +1 | compile | 893 | the patch passed |
| +1 | javac | 893 | the patch passed |
| -0 | checkstyle | 47 | hadoop-common-project/hadoop-common: The patch generated 8 new + 1 unchanged - 0 fixed = 9 total (was 1) |
| +1 | mvnsite | 66 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 603 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 100 | the patch passed |
| +1 | javadoc | 55 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 505 | hadoop-common in the patch passed. |
| +1 | asflicense | 37 | The patch does not generate ASF License warnings. |
| | | 5357 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-580/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/580 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux 2b5cb7636682 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c072458 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-580/1/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-580/1/testReport/ |
| Max. process+thread count | 1493 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-580/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 38 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1096 | trunk passed |
| +1 | compile | 992 | trunk passed |
| +1 | checkstyle | 56 | trunk passed |
| +1 | mvnsite | 75 | trunk passed |
| +1 | shadedclient | 827 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 98 | trunk passed |
| +1 | javadoc | 62 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 47 | the patch passed |
| +1 | compile | 940 | the patch passed |
| +1 | javac | 940 | the patch passed |
| +1 | checkstyle | 56 | hadoop-common-project/hadoop-common: The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
| +1 | mvnsite | 73 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 706 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 114 | the patch passed |
| +1 | javadoc | 62 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 599 | hadoop-common in the patch passed. |
| +1 | asflicense | 53 | The patch does not generate ASF License warnings. |
| | | 5964 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-580/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/580 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux e34aeb6b3ba8 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c072458 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-580/2/testReport/ |
| Max. process+thread count | 1346 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-580/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
+1, commit at your leisure

**Comment by mattf-apache** [comment]
Committed to trunk as SHA1 f74159c8fc5.
Thanks for the help, @steveloughran .

**Pull request closed without merging**
