### PR TITLE
fix bug which the iMax is not work in MutableRatesWithAggregation

### PR DESCRIPTION
**Pull request by ZanderXu**
IMax and IMin is not work in MutableRatesWithAggregation.

### CODE REVIEW

**Comment by ZanderXu** [comment]
[HDFS-14214](https://issues.apache.org/jira/browse/HDFS-14214)

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 86 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1217 | trunk passed |
| +1 | compile | 1123 | trunk passed |
| +1 | checkstyle | 43 | trunk passed |
| +1 | mvnsite | 82 | trunk passed |
| +1 | shadedclient | 872 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 64 | trunk passed |
| 0 | spotbugs | 126 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 124 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 52 | the patch passed |
| +1 | compile | 1035 | the patch passed |
| +1 | javac | 1035 | the patch passed |
| -0 | checkstyle | 44 | hadoop-common-project/hadoop-common: The patch generated 7 new + 26 unchanged - 0 fixed = 33 total (was 26) |
| +1 | mvnsite | 81 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 754 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 67 | the patch passed |
| +1 | findbugs | 136 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 574 | hadoop-common in the patch passed. |
| +1 | asflicense | 46 | The patch does not generate ASF License warnings. |
| | | 6464 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-468/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/468 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 064d800f019d 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / cd967c7 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/1/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/1/testReport/ |
| Max. process+thread count | 1724 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 49 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1060 | trunk passed |
| +1 | compile | 1056 | trunk passed |
| +1 | checkstyle | 49 | trunk passed |
| +1 | mvnsite | 84 | trunk passed |
| +1 | shadedclient | 813 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 64 | trunk passed |
| 0 | spotbugs | 124 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 121 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 48 | the patch passed |
| +1 | compile | 994 | the patch passed |
| +1 | javac | 994 | the patch passed |
| -0 | checkstyle | 48 | hadoop-common-project/hadoop-common: The patch generated 7 new + 26 unchanged - 0 fixed = 33 total (was 26) |
| +1 | mvnsite | 80 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 688 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 70 | the patch passed |
| +1 | findbugs | 130 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 533 | hadoop-common in the patch passed. |
| +1 | asflicense | 53 | The patch does not generate ASF License warnings. |
| | | 6017 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-468/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/468 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 348c463e6f7c 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c7c7a88 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/2/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/2/testReport/ |
| Max. process+thread count | 1313 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 85 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1192 | trunk passed |
| -1 | compile | 745 | root in trunk failed. |
| +1 | checkstyle | 44 | trunk passed |
| +1 | mvnsite | 82 | trunk passed |
| +1 | shadedclient | 871 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 66 | trunk passed |
| 0 | spotbugs | 136 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 133 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 57 | the patch passed |
| +1 | compile | 1098 | the patch passed |
| -1 | javac | 1098 | root generated 194 new + 1276 unchanged - 0 fixed = 1470 total (was 1276) |
| -0 | checkstyle | 43 | hadoop-common-project/hadoop-common: The patch generated 7 new + 26 unchanged - 0 fixed = 33 total (was 26) |
| +1 | mvnsite | 85 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 741 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 62 | the patch passed |
| +1 | findbugs | 148 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 597 | hadoop-common in the patch passed. |
| +1 | asflicense | 44 | The patch does not generate ASF License warnings. |
| | | 6161 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-468/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/468 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux b56d1dcdfbc8 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c2d00c8 |
| Default Java | 1.8.0_212 |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/3/artifact/out/branch-compile-root.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/3/artifact/out/diff-compile-javac-root.txt |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/3/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/3/testReport/ |
| Max. process+thread count | 1493 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1118 | trunk passed |
| +1 | compile | 1157 | trunk passed |
| +1 | checkstyle | 39 | trunk passed |
| +1 | mvnsite | 73 | trunk passed |
| +1 | shadedclient | 723 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 59 | trunk passed |
| 0 | spotbugs | 122 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 121 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 48 | the patch passed |
| +1 | compile | 1095 | the patch passed |
| +1 | javac | 1095 | the patch passed |
| -0 | checkstyle | 39 | hadoop-common-project/hadoop-common: The patch generated 7 new + 26 unchanged - 0 fixed = 33 total (was 26) |
| +1 | mvnsite | 74 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 611 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 58 | the patch passed |
| +1 | findbugs | 124 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 555 | hadoop-common in the patch passed. |
| +1 | asflicense | 50 | The patch does not generate ASF License warnings. |
| | | 6054 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-468/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/468 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 47219373d32c 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / b0131bc |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/4/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/4/testReport/ |
| Max. process+thread count | 1598 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/4/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 111 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1284 | trunk passed |
| +1 | compile | 1087 | trunk passed |
| +1 | checkstyle | 41 | trunk passed |
| +1 | mvnsite | 78 | trunk passed |
| +1 | shadedclient | 875 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 61 | trunk passed |
| 0 | spotbugs | 124 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 122 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 49 | the patch passed |
| +1 | compile | 1077 | the patch passed |
| +1 | javac | 1077 | the patch passed |
| -0 | checkstyle | 44 | hadoop-common-project/hadoop-common: The patch generated 7 new + 26 unchanged - 0 fixed = 33 total (was 26) |
| +1 | mvnsite | 80 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 752 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 69 | the patch passed |
| +1 | findbugs | 137 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 549 | hadoop-common in the patch passed. |
| +1 | asflicense | 45 | The patch does not generate ASF License warnings. |
| | | 6541 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-468/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/468 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux cf239c8f5bb9 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e356e4f |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/5/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/5/testReport/ |
| Max. process+thread count | 1341 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/5/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 38 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1100 | trunk passed |
| +1 | compile | 1135 | trunk passed |
| +1 | checkstyle | 38 | trunk passed |
| +1 | mvnsite | 70 | trunk passed |
| +1 | shadedclient | 752 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 59 | trunk passed |
| 0 | spotbugs | 111 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 110 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 42 | the patch passed |
| +1 | compile | 981 | the patch passed |
| +1 | javac | 981 | the patch passed |
| -0 | checkstyle | 36 | hadoop-common-project/hadoop-common: The patch generated 7 new + 26 unchanged - 0 fixed = 33 total (was 26) |
| +1 | mvnsite | 65 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 587 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 55 | the patch passed |
| +1 | findbugs | 118 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 528 | hadoop-common in the patch passed. |
| +1 | asflicense | 41 | The patch does not generate ASF License warnings. |
| | | 5806 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-468/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/468 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux ac7ac5762345 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 094d736 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/6/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/6/testReport/ |
| Max. process+thread count | 1606 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/6/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 65 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1056 | trunk passed |
| +1 | compile | 1133 | trunk passed |
| +1 | checkstyle | 35 | trunk passed |
| +1 | mvnsite | 67 | trunk passed |
| +1 | shadedclient | 743 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 57 | trunk passed |
| 0 | spotbugs | 120 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 117 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 47 | the patch passed |
| +1 | compile | 1160 | the patch passed |
| +1 | javac | 1160 | the patch passed |
| -0 | checkstyle | 38 | hadoop-common-project/hadoop-common: The patch generated 7 new + 26 unchanged - 0 fixed = 33 total (was 26) |
| +1 | mvnsite | 70 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 635 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 55 | the patch passed |
| +1 | findbugs | 126 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 523 | hadoop-common in the patch passed. |
| +1 | asflicense | 43 | The patch does not generate ASF License warnings. |
| | | 6036 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-468/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/468 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 8e13127ea060 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 69ddb36 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/7/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/7/testReport/ |
| Max. process+thread count | 1391 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/7/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1087 | trunk passed |
| +1 | compile | 1068 | trunk passed |
| +1 | checkstyle | 49 | trunk passed |
| +1 | mvnsite | 84 | trunk passed |
| +1 | shadedclient | 809 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 69 | trunk passed |
| 0 | spotbugs | 122 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 120 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 51 | the patch passed |
| +1 | compile | 1026 | the patch passed |
| +1 | javac | 1026 | the patch passed |
| -0 | checkstyle | 44 | hadoop-common-project/hadoop-common: The patch generated 7 new + 26 unchanged - 0 fixed = 33 total (was 26) |
| +1 | mvnsite | 83 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 662 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 74 | the patch passed |
| +1 | findbugs | 130 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 593 | hadoop-common in the patch passed. |
| +1 | asflicense | 51 | The patch does not generate ASF License warnings. |
| | | 6115 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-468/8/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/468 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 90ecada0b8b2 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3329257 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/8/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/8/testReport/ |
| Max. process+thread count | 1378 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/8/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 51 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1274 | trunk passed |
| +1 | compile | 1123 | trunk passed |
| +1 | checkstyle | 46 | trunk passed |
| +1 | mvnsite | 83 | trunk passed |
| +1 | shadedclient | 828 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 72 | trunk passed |
| 0 | spotbugs | 125 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 123 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 52 | the patch passed |
| +1 | compile | 997 | the patch passed |
| +1 | javac | 997 | the patch passed |
| -0 | checkstyle | 48 | hadoop-common-project/hadoop-common: The patch generated 7 new + 26 unchanged - 0 fixed = 33 total (was 26) |
| +1 | mvnsite | 82 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 722 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 69 | the patch passed |
| +1 | findbugs | 138 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 560 | hadoop-common in the patch passed. |
| +1 | asflicense | 51 | The patch does not generate ASF License warnings. |
| | | 6415 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-468/9/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/468 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 59597ce173d4 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 915cbc9 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/9/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/9/testReport/ |
| Max. process+thread count | 1664 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-468/9/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
