### PR TITLE
MAPREDUCE-7076 TestNNBench#testNNBenchCreateReadAndDelete failing in …

### PR DESCRIPTION
**Pull request by pingsutw**
…our internal build

### CODE REVIEW

**Comment by jojochuang** [comment]
Great catch! The fix makes sense to me. +1
This is arguably a HDFS issue rather than MAPREDUCE issue. But that's fine.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 38 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1092 | trunk passed |
| +1 | compile | 32 | trunk passed |
| +1 | checkstyle | 22 | trunk passed |
| +1 | mvnsite | 37 | trunk passed |
| +1 | shadedclient | 695 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 16 | trunk passed |
| 0 | spotbugs | 51 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 49 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 31 | the patch passed |
| +1 | compile | 28 | the patch passed |
| +1 | javac | 28 | the patch passed |
| +1 | checkstyle | 17 | the patch passed |
| +1 | mvnsite | 30 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 683 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 19 | the patch passed |
| +1 | findbugs | 51 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 7354 | hadoop-mapreduce-client-jobclient in the patch failed. |
| -1 | asflicense | 34 | The patch generated 1 ASF License warnings. |
| | | 10298 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.mapred.TestMROpportunisticMaps |
|   | hadoop.mapreduce.v2.TestUberAM |
|   | hadoop.mapreduce.TestLargeSort |
|   | hadoop.mapreduce.v2.TestMRJobs |
|   | hadoop.mapred.TestMiniMRChildTask |
|   | hadoop.mapred.TestJobSysDirWithDFS |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1089/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1089 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux ef7c8c38451d 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 4e66cb9 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1089/1/artifact/out/patch-unit-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-jobclient.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1089/1/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-1089/1/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 1391 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient U: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1089/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
+1

**Comment by aajisaka** [comment]
Thanks @pingsutw and @jojochuang !

**Comment by aajisaka** [comment]
Hi @pingsutw , do you have an ASF JIRA ID? I'd like to assign you to https://issues.apache.org/jira/browse/MAPREDUCE-7076

**Comment by pingsutw** [comment]
@aajisaka my JIRA iID is pingsutw as well, and thanks for your help.

**Comment by aajisaka** [comment]
Assigned. Thanks.

**Comment by wsu13** [comment]
This modification makes `barrier()` always returns true, and makes `NNbench_reports.log`'s "maps that missed the barrier" metric always be zero.

In a large test configuration with thousands of mappers, Yarn takes more than 2 minutes(the default barrier time) to start up all the mappers.  The `barrier()` function is important to make the results meaningful.
@aajisaka
I think we should revisit this commit.

**Pull request closed without merging**
