### PR TITLE
HADOOP-17244. S3A directory delete tombstones dir markers prematurely.

### PR DESCRIPTION
**Pull request by steveloughran**
This changes directory tree deletion so that only files are incrementally deleted
from S3Guard after the objects are deleted; the directories are left alone
until   metadataStore.deleteSubtree(path) is invoked

This avoids directory tombstones being added above files/child directories,
which stop that subtree operation from actually finishing.

Also:

* callback to delete objects splits files and dirs so that
any problems deleting the dirs doesn't trigger s3guard updates
* new statistic to measure #of objects deleted, alongside request count.
* callback listFilesAndEmptyDirectories renamed listFilesAndDirectoryMarkers
  to clarify behavior.
Test enhancements in ITestDirectoryOperationCost, but I didn't manage to
replicate it there (didn't quite understand the cause); the FileContext
test works for regression testing.

Change-Id: I8f96536bc6ffaf548b3da1068b9bfc897d34a993

### CODE REVIEW

**Comment by steveloughran** [comment]
Tests in progress

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  28m 34s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 4 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 28s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  26m 37s |  trunk passed  |
| +1 :green_heart: |  compile  |  19m 30s |  trunk passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  compile  |  17m  0s |  trunk passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +1 :green_heart: |  checkstyle  |   2m 46s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 23s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  19m 52s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 15s |  trunk passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  javadoc  |   2m 17s |  trunk passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +0 :ok: |  spotbugs  |   1m 15s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m 28s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 22s |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 49s |  the patch passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  javac  |  18m 49s |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 58s |  the patch passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +1 :green_heart: |  javac  |  16m 58s |  the patch passed  |
| -0 :warning: |  checkstyle  |   2m 42s |  root: The patch generated 2 new + 171 unchanged - 0 fixed = 173 total (was 171)  |
| +1 :green_heart: |  mvnsite  |   2m 21s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  14m  8s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 13s |  the patch passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  javadoc  |   2m 19s |  the patch passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +1 :green_heart: |  findbugs  |   3m 47s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   9m 32s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 35s |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 55s |  The patch does not generate ASF License warnings.  |
|  |   | 203m 41s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.fs.TestLocalFSFileContextMainOperations |
|   | hadoop.fs.viewfs.TestFcMainOperationsLocalFs |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2280/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2280 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 8ed0a65527dd 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / ac7d4623aef |
| Default Java | Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01 |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2280/1/artifact/out/diff-checkstyle-root.txt |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2280/1/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2280/1/testReport/ |
| Max. process+thread count | 2745 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2280/1/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.0.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
broke the local fs tests
```
[ERROR] Failures: 
[ERROR]   TestLocalFSFileContextMainOperations>FileContextMainOperationsBaseTest.testRenameDirectoryAsEmptyDirectory:1192 Expected exception was not thrown
[ERROR]   TestLocalFSFileContextMainOperations>FileContextMainOperationsBaseTest.testRenameDirectoryAsFile:1241 Expected exception was not thrown
[ERROR]   TestLocalFSFileContextMainOperations>FileContextMainOperationsBaseTest.testRenameDirectoryAsNonEmptyDirectory:1216 Expected exception was not thrown
[ERROR]   TestLocalFSFileContextMainOperations>FileContextMainOperationsBaseTest.testRenameDirectoryToItself:1112 Renamed directory to itself
[ERROR]   TestLocalFSFileContextMainOperations>FileContextMainOperationsBaseTest.testRenameDirectoryToNonExistentParent:1135 Expected exception was not thrown
[ERROR]   TestLocalFSFileContextMainOperations>FileContextMainOperationsBaseTest.testRenameFileAsExistingDirectory:1093 Expected exception was not thrown
[ERROR]   TestLocalFSFileContextMainOperations>FileContextMainOperationsBaseTest.testRenameFileAsExistingFile:1072 Expected exception was not thrown
[ERROR]   TestLocalFSFileContextMainOperations>FileContextMainOperationsBaseTest.testRenameFileToDestinationWithParentFile:1018 Expected exception was not thrown
[ERROR]   TestLocalFSFileContextMainOperations>FileContextMainOperationsBaseTest.testRenameFileToItself:1047 Renamed file to itself
[ERROR]   TestLocalFSFileContextMainOperations>FileContextMainOperationsBaseTest.testRenameFileToNonExistentDirectory:994 Expected exception was not thrown
[ERROR]   TestLocalFSFileContextMainOperations>FileContextMainOperationsBaseTest.testRenameNonExistentPath:971 Should throw FileNotFoundException
[ERROR]   TestFcMainOperationsLocalFs>FileContextMainOperationsBaseTest.testRenameDirectoryAsEmptyDirectory:1192 Expected exception was not thrown
[ERROR]   TestFcMainOperationsLocalFs>FileContextMainOperationsBaseTest.testRenameDirectoryAsFile:1241 Expected exception was not thrown
[ERROR]   TestFcMainOperationsLocalFs>FileContextMainOperationsBaseTest.testRenameDirectoryAsNonEmptyDirectory:1216 Expected exception was not thrown
[ERROR]   TestFcMainOperationsLocalFs>FileContextMainOperationsBaseTest.testRenameDirectoryToItself:1112 Renamed directory to itself
[ERROR]   TestFcMainOperationsLocalFs>FileContextMainOperationsBaseTest.testRenameDirectoryToNonExistentParent:1135 Expected exception was not thrown
[ERROR]   TestFcMainOperationsLocalFs>FileContextMainOperationsBaseTest.testRenameFileAsExistingDirectory:1093 Expected exception was not thrown
[ERROR]   TestFcMainOperationsLocalFs>FileContextMainOperationsBaseTest.testRenameFileAsExistingFile:1072 Expected exception was not thrown
[ERROR]   TestFcMainOperationsLocalFs>FileContextMainOperationsBaseTest.testRenameFileToDestinationWithParentFile:1018 Expected exception was not thrown
[ERROR]   TestFcMainOperationsLocalFs>FileContextMainOperationsBaseTest.testRenameFileToItself:1047 Renamed file to itself
[ERROR]   TestFcMainOperationsLocalFs>FileContextMainOperationsBaseTest.testRenameFileToNonExistentDirectory:994 Expected exception was not thrown
[ERROR]   TestFcMainOperationsLocalFs>FileContextMainOperationsBaseTest.testRenameNonExistentPath:971 Should throw FileNotFoundException
[INFO] 
[ERROR] Tests run: 4439, Failures: 22, Errors: 0, Skipped: 165
```

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 41s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 5 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 20s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  30m 39s |  trunk passed  |
| +1 :green_heart: |  compile  |  24m 17s |  trunk passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  compile  |  20m 30s |  trunk passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +1 :green_heart: |  checkstyle  |   2m 43s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 24s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  19m 49s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 15s |  trunk passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  javadoc  |   2m 11s |  trunk passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +0 :ok: |  spotbugs  |   1m 21s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m 34s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 25s |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 21s |  the patch passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  javac  |  19m 21s |  the patch passed  |
| +1 :green_heart: |  compile  |  17m  6s |  the patch passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +1 :green_heart: |  javac  |  17m  6s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m 44s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m 23s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  14m  9s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 13s |  the patch passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  javadoc  |   2m 20s |  the patch passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +1 :green_heart: |  findbugs  |   3m 47s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   9m 42s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 39s |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 56s |  The patch does not generate ASF License warnings.  |
|  |   | 189m 12s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2280/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2280 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux b43739be005f 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 0d855159f09 |
| Default Java | Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2280/2/testReport/ |
| Max. process+thread count | 1554 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2280/2/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.0.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
Note: I ran the hdfs contract tests in my IDE to verify it was happy too; all good.

**Review by bgaborg — APPROVED** [review]
LGTM, +1 pending on integration test results, and which endpoint you tested against.

**Comment by steveloughran** [comment]
repeatedly tested against london with options showing the error and the -Dkeep option *and unguarded*. Some transient failures related to local network issues, addressed in HADOOP-17181.

**Comment by steveloughran** [comment]
This patch is incomplete. Reverted and will create a new one.  

Issues
* cleanup on a multipart fail will tombstone everything; no information at that point as to what is/isn't a dir
* delete needs more coverage

I think I may want to push this delete/no-delete logic into s3guard -it can do the check rather than relying on the layer above. But: we will need to pass down for each path whether a path is a dir or a file, so that s3guard doesn't do a DDB query on every single path entry to work that out for itself

**Pull request merged**
