### PR TITLE
HADOOP-17743. Replace Guava Lists usage by Hadoop's own Lists in hadoop-common, hadoop-tools and cloud-storage projects

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 59s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 22 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  16m 14s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  20m 12s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  21m  1s |  |  trunk passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  compile  |  18m  6s |  |  trunk passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  checkstyle  |   3m 44s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   9m 29s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   8m  6s |  |  trunk passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   8m 33s |  |  trunk passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +0 :ok: |  spotbugs  |   0m 40s |  |  branch/hadoop-cloud-storage-project/hadoop-cloud-storage no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  13m 57s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 28s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m  3s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  20m 10s |  |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javac  |  20m 10s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 17s |  |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  javac  |  18m 17s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   3m 43s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   9m 25s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m 14s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   8m  2s |  |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   8m 37s |  |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +0 :ok: |  spotbugs  |   0m 40s |  |  hadoop-cloud-storage-project/hadoop-cloud-storage has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  14m  2s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  17m 11s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 27s |  |  hadoop-registry in the patch passed.  |
| +1 :green_heart: |  unit  |  42m 35s |  |  hadoop-distcp in the patch passed.  |
| -1 :x: |  unit  |   1m  6s | [/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-workload.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3072/1/artifact/out/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-workload.txt) |  hadoop-dynamometer-workload in the patch passed.  |
| -1 :x: |  unit  |   3m 54s | [/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-infra.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3072/1/artifact/out/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-infra.txt) |  hadoop-dynamometer-infra in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 44s |  |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 48s |  |  hadoop-kafka in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 24s |  |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 45s |  |  hadoop-cos in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 46s |  |  hadoop-huaweicloud in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 41s |  |  hadoop-cloud-storage in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  3s |  |  The patch does not generate ASF License warnings.  |
|  |   | 316m 56s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.tools.dynamometer.workloadgenerator.TestWorkloadGenerator |
|   | hadoop.tools.dynamometer.TestDynamometerInfra |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3072/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3072 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux 8069a5d5ec26 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 9902138e5d9d20d23901c11edb03e439e235fa0b |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3072/1/testReport/ |
| Max. process+thread count | 1267 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-tools/hadoop-distcp hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-workload hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-infra hadoop-tools/hadoop-aws hadoop-tools/hadoop-kafka hadoop-tools/hadoop-azure hadoop-cloud-storage-project/hadoop-cos hadoop-cloud-storage-project/hadoop-huaweicloud hadoop-cloud-storage-project/hadoop-cloud-storage U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3072/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 51s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 22 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  16m 10s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  20m  8s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  20m 46s |  |  trunk passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  compile  |  18m  5s |  |  trunk passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  checkstyle  |   3m 48s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   9m 26s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   8m  4s |  |  trunk passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   8m 38s |  |  trunk passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +0 :ok: |  spotbugs  |   0m 39s |  |  branch/hadoop-cloud-storage-project/hadoop-cloud-storage no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  14m 10s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m  3s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  20m 15s |  |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javac  |  20m 15s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m  9s |  |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  javac  |  18m  9s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   3m 43s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   9m 18s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m 14s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   8m  8s |  |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   8m 37s |  |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +0 :ok: |  spotbugs  |   0m 40s |  |  hadoop-cloud-storage-project/hadoop-cloud-storage has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  13m 59s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  17m 11s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 28s |  |  hadoop-registry in the patch passed.  |
| +1 :green_heart: |  unit  |  42m 21s |  |  hadoop-distcp in the patch passed.  |
| -1 :x: |  unit  |   1m  7s | [/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-workload.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3072/2/artifact/out/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-workload.txt) |  hadoop-dynamometer-workload in the patch passed.  |
| -1 :x: |  unit  |   1m 33s | [/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-infra.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3072/2/artifact/out/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-infra.txt) |  hadoop-dynamometer-infra in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 46s |  |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 46s |  |  hadoop-kafka in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 24s |  |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 45s |  |  hadoop-cos in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 46s |  |  hadoop-huaweicloud in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 41s |  |  hadoop-cloud-storage in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  3s |  |  The patch does not generate ASF License warnings.  |
|  |   | 313m 56s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.tools.dynamometer.workloadgenerator.TestWorkloadGenerator |
|   | hadoop.tools.dynamometer.TestDynamometerInfra |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3072/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3072 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux 0c07b26ddb0d 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 9902138e5d9d20d23901c11edb03e439e235fa0b |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3072/2/testReport/ |
| Max. process+thread count | 1267 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-tools/hadoop-distcp hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-workload hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-infra hadoop-tools/hadoop-aws hadoop-tools/hadoop-kafka hadoop-tools/hadoop-azure hadoop-cloud-storage-project/hadoop-cos hadoop-cloud-storage-project/hadoop-huaweicloud hadoop-cloud-storage-project/hadoop-cloud-storage U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3072/2/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by tasanuma — APPROVED** [review]
LGTM.

**Comment by tasanuma** [comment]
The failed tests are not related. HDFS-16050 is addressing the issue.

**Comment by tasanuma** [comment]
Merged. Thanks for your contribution, @virajjasani!

**Comment by steveloughran** [comment]
is there a plan to get this into branch-3.3? backporting past this change is getting hard.
at the very least, we should add the new list class, so that cherrypicking works

**Comment by virajjasani** [comment]
Sure @steveloughran, will create 3.3 backport PR of #3061, it should be directly applicable to branch-3.3 and 3.2 without any conflicts.

**Comment by steveloughran** [comment]
I pulled in the declaration of the Lists class, so new code can go back without problems

**Pull request merged**
