### PR TITLE
Fix FileSystem.listStatus javadoc

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 37 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1086 | trunk passed |
| +1 | compile | 1041 | trunk passed |
| +1 | checkstyle | 39 | trunk passed |
| +1 | mvnsite | 71 | trunk passed |
| +1 | shadedclient | 759 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 58 | trunk passed |
| 0 | spotbugs | 120 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 118 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 48 | the patch passed |
| +1 | compile | 996 | the patch passed |
| +1 | javac | 996 | the patch passed |
| +1 | checkstyle | 36 | the patch passed |
| +1 | mvnsite | 75 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 645 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 59 | the patch passed |
| +1 | findbugs | 121 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 526 | hadoop-common in the patch passed. |
| +1 | asflicense | 43 | The patch does not generate ASF License warnings. |
| | | 5836 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-350/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/350 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 5146ea88315b 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 7f1b76c |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/1/testReport/ |
| Max. process+thread count | 1361 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 63 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1138 | trunk passed |
| +1 | compile | 1041 | trunk passed |
| +1 | checkstyle | 38 | trunk passed |
| +1 | mvnsite | 76 | trunk passed |
| +1 | shadedclient | 749 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 56 | trunk passed |
| 0 | spotbugs | 124 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 122 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 50 | the patch passed |
| +1 | compile | 1001 | the patch passed |
| +1 | javac | 1001 | the patch passed |
| +1 | checkstyle | 35 | the patch passed |
| +1 | mvnsite | 71 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 607 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 57 | the patch passed |
| +1 | findbugs | 123 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 507 | hadoop-common in the patch passed. |
| +1 | asflicense | 42 | The patch does not generate ASF License warnings. |
| | | 5826 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-350/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/350 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 0e3de8374a6f 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c01e137 |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/2/testReport/ |
| Max. process+thread count | 1390 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 46 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1117 | trunk passed |
| +1 | compile | 1090 | trunk passed |
| +1 | checkstyle | 40 | trunk passed |
| +1 | mvnsite | 75 | trunk passed |
| +1 | shadedclient | 762 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 60 | trunk passed |
| 0 | spotbugs | 127 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 124 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 54 | the patch passed |
| +1 | compile | 1111 | the patch passed |
| +1 | javac | 1111 | the patch passed |
| +1 | checkstyle | 43 | the patch passed |
| +1 | mvnsite | 78 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 653 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 65 | the patch passed |
| +1 | findbugs | 142 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 566 | hadoop-common in the patch failed. |
| +1 | asflicense | 39 | The patch does not generate ASF License warnings. |
| | | 6130 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ha.TestZKFailoverController |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-350/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/350 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux ce6eac378a31 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e872ceb |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/3/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/3/testReport/ |
| Max. process+thread count | 1461 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 34 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1198 | trunk passed |
| +1 | compile | 1059 | trunk passed |
| +1 | checkstyle | 46 | trunk passed |
| +1 | mvnsite | 82 | trunk passed |
| +1 | shadedclient | 868 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 65 | trunk passed |
| 0 | spotbugs | 125 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 123 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 47 | the patch passed |
| +1 | compile | 992 | the patch passed |
| +1 | javac | 992 | the patch passed |
| +1 | checkstyle | 45 | the patch passed |
| +1 | mvnsite | 75 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 719 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 61 | the patch passed |
| +1 | findbugs | 133 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 554 | hadoop-common in the patch passed. |
| +1 | asflicense | 44 | The patch does not generate ASF License warnings. |
| | | 6199 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-350/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/350 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 81b565a45137 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 00b5a27 |
| Default Java | 1.8.0_222 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/4/testReport/ |
| Max. process+thread count | 1369 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/4/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1074 | trunk passed |
| +1 | compile | 1139 | trunk passed |
| +1 | checkstyle | 39 | trunk passed |
| +1 | mvnsite | 78 | trunk passed |
| +1 | shadedclient | 800 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 61 | trunk passed |
| 0 | spotbugs | 120 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 118 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 51 | the patch passed |
| +1 | compile | 1116 | the patch passed |
| +1 | javac | 1116 | the patch passed |
| +1 | checkstyle | 42 | the patch passed |
| +1 | mvnsite | 71 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 677 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 62 | the patch passed |
| +1 | findbugs | 135 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 560 | hadoop-common in the patch failed. |
| +1 | asflicense | 44 | The patch does not generate ASF License warnings. |
| | | 6165 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.util.TestDiskCheckerWithDiskIo |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-350/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/350 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux d249303bf832 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e356e4f |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/5/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/5/testReport/ |
| Max. process+thread count | 1429 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/5/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 69 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1231 | trunk passed |
| +1 | compile | 1436 | trunk passed |
| +1 | checkstyle | 46 | trunk passed |
| +1 | mvnsite | 90 | trunk passed |
| +1 | shadedclient | 810 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 64 | trunk passed |
| 0 | spotbugs | 131 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 129 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 51 | the patch passed |
| +1 | compile | 1283 | the patch passed |
| +1 | javac | 1283 | the patch passed |
| +1 | checkstyle | 50 | the patch passed |
| +1 | mvnsite | 81 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 789 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 69 | the patch passed |
| +1 | findbugs | 155 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 622 | hadoop-common in the patch failed. |
| +1 | asflicense | 45 | The patch does not generate ASF License warnings. |
| | | 7069 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ha.TestZKFailoverController |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-350/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/350 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 428b277f812a 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 094d736 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/6/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/6/testReport/ |
| Max. process+thread count | 1374 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/6/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1060 | trunk passed |
| +1 | compile | 1125 | trunk passed |
| +1 | checkstyle | 36 | trunk passed |
| +1 | mvnsite | 67 | trunk passed |
| +1 | shadedclient | 770 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 53 | trunk passed |
| 0 | spotbugs | 110 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 107 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 44 | the patch passed |
| +1 | compile | 1031 | the patch passed |
| +1 | javac | 1031 | the patch passed |
| +1 | checkstyle | 39 | the patch passed |
| +1 | mvnsite | 72 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 661 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 56 | the patch passed |
| +1 | findbugs | 121 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 541 | hadoop-common in the patch passed. |
| +1 | asflicense | 38 | The patch does not generate ASF License warnings. |
| | | 5932 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-350/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/350 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 5deb9f9a49f5 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 61b2df2 |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/7/testReport/ |
| Max. process+thread count | 1361 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/7/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 80 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1253 | trunk passed |
| +1 | compile | 1101 | trunk passed |
| +1 | checkstyle | 48 | trunk passed |
| +1 | mvnsite | 83 | trunk passed |
| +1 | shadedclient | 880 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 72 | trunk passed |
| 0 | spotbugs | 152 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 149 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 52 | the patch passed |
| +1 | compile | 1072 | the patch passed |
| +1 | javac | 1072 | the patch passed |
| +1 | checkstyle | 44 | the patch passed |
| +1 | mvnsite | 80 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 791 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 82 | the patch passed |
| +1 | findbugs | 171 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 596 | hadoop-common in the patch failed. |
| +1 | asflicense | 62 | The patch does not generate ASF License warnings. |
| | | 6697 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.security.TestRaceWhenRelogin |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-350/8/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/350 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux a1993e5134ee 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3329257 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/8/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/8/testReport/ |
| Max. process+thread count | 1342 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/8/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1094 | trunk passed |
| +1 | compile | 1024 | trunk passed |
| +1 | checkstyle | 48 | trunk passed |
| +1 | mvnsite | 84 | trunk passed |
| +1 | shadedclient | 837 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 67 | trunk passed |
| 0 | spotbugs | 124 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 122 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 48 | the patch passed |
| +1 | compile | 962 | the patch passed |
| +1 | javac | 962 | the patch passed |
| +1 | checkstyle | 48 | the patch passed |
| +1 | mvnsite | 81 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 657 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 68 | the patch passed |
| +1 | findbugs | 128 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 560 | hadoop-common in the patch passed. |
| +1 | asflicense | 53 | The patch does not generate ASF License warnings. |
| | | 5996 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-350/9/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/350 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 6893ea287441 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 915cbc9 |
| Default Java | 1.8.0_222 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/9/testReport/ |
| Max. process+thread count | 1508 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-350/9/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
