### PR TITLE
YARN-9375. Use Configured in GpuDiscoverer and FpgaDiscoverer

### PR DESCRIPTION
**Pull request by adamantal**
Recreated a PR, hope this time yetus will pick it up.

The change is straightforward, check [upstream jira](https://issues.apache.org/jira/browse/YARN-9375).

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 37 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1045 | trunk passed |
| +1 | compile | 67 | trunk passed |
| +1 | checkstyle | 24 | trunk passed |
| +1 | mvnsite | 41 | trunk passed |
| +1 | shadedclient | 695 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 27 | trunk passed |
| 0 | spotbugs | 80 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 79 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 39 | the patch passed |
| +1 | compile | 59 | the patch passed |
| +1 | javac | 59 | the patch passed |
| -0 | checkstyle | 20 | hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager: The patch generated 1 new + 6 unchanged - 1 fixed = 7 total (was 7) |
| +1 | mvnsite | 35 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 687 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 21 | the patch passed |
| +1 | findbugs | 76 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 1266 | hadoop-yarn-server-nodemanager in the patch passed. |
| +1 | asflicense | 26 | The patch does not generate ASF License warnings. |
| | | 4322 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1131/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1131 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 7d1fe2970c0e 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 4e66cb9 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1131/1/artifact/out/diff-checkstyle-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-nodemanager.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1131/1/testReport/ |
| Max. process+thread count | 411 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager U: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1131/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 40 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1045 | trunk passed |
| +1 | compile | 67 | trunk passed |
| +1 | checkstyle | 27 | trunk passed |
| +1 | mvnsite | 43 | trunk passed |
| +1 | shadedclient | 718 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 29 | trunk passed |
| 0 | spotbugs | 83 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 80 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 37 | the patch passed |
| +1 | compile | 58 | the patch passed |
| +1 | javac | 58 | the patch passed |
| -0 | checkstyle | 20 | hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager: The patch generated 1 new + 6 unchanged - 1 fixed = 7 total (was 7) |
| +1 | mvnsite | 39 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 706 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 24 | the patch passed |
| +1 | findbugs | 85 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 1269 | hadoop-yarn-server-nodemanager in the patch passed. |
| +1 | asflicense | 27 | The patch does not generate ASF License warnings. |
| | | 4374 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1131/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1131 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 7e3c96557339 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / aebac6d |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1131/2/artifact/out/diff-checkstyle-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-nodemanager.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1131/2/testReport/ |
| Max. process+thread count | 447 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager U: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1131/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by adamantal** [comment]
There are no tests for this, since it's a refactor. 

Could you have some time to review this @szilard-nemeth?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1257 | trunk passed |
| +1 | compile | 77 | trunk passed |
| +1 | checkstyle | 25 | trunk passed |
| +1 | mvnsite | 47 | trunk passed |
| +1 | shadedclient | 786 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 26 | trunk passed |
| 0 | spotbugs | 83 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 81 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 40 | the patch passed |
| +1 | compile | 67 | the patch passed |
| +1 | javac | 67 | the patch passed |
| -0 | checkstyle | 25 | hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager: The patch generated 1 new + 6 unchanged - 1 fixed = 7 total (was 7) |
| +1 | mvnsite | 43 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 858 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 28 | the patch passed |
| +1 | findbugs | 92 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 1309 | hadoop-yarn-server-nodemanager in the patch passed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 4902 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1131/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1131 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 8b4663a5f02a 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / d086d05 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1131/3/artifact/out/diff-checkstyle-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-nodemanager.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1131/3/testReport/ |
| Max. process+thread count | 307 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager U: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1131/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by szilard-nemeth** [comment]
Hi @adamantal !
+1 for this patch. Committing.

**Comment by adamantal** [comment]
Thanks @szilard-nemeth!

**Pull request merged**
