### PR TITLE
HDDS-1965. Compile error due to leftover ScmBlockLocationTestIngClient file

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Typo in class name of `ScmBlockLocationTestingClient` was fixed in 5a248de5115, but the original file is still present in the repo, causing compile error.

https://issues.apache.org/jira/browse/HDDS-1965

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 67 | Docker mode activated. |
||| _ Prechecks _ |
| -1 | dupname | 0 | The patch has 1  duplicated filenames that differ only in case. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1293/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1293 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux f65e4a4ae90b 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 0e4b757 |
| dupname | https://builds.apache.org/job/hadoop-multibranch/job/PR-1293/1/artifact/out/dupnames.txt |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1293/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by adoroszlai** [comment]
@nandakumar131 please review

**Comment by adoroszlai** [comment]
Thanks @nandakumar131 for quick review and commit.

**Pull request merged**
