### PR TITLE
Add bswap support for LoongArch

### PR DESCRIPTION
**Pull request by zhaixiaojuan**
### Description of PR
This PR adds bswap support for LoongArch.

The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.
Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:
https://loongson.github.io/LoongArch-Documentation/README-EN.html

### How was this patch tested?
mvn package -Pdist,native -DskipTests  -Dtar

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  43m 58s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  47m 19s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   0m 54s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 29s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  73m 50s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 25s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 47s |  |  the patch passed  |
| +1 :green_heart: |  cc  |   0m 47s |  |  the patch passed  |
| +1 :green_heart: |  golang  |   0m 47s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 47s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 20s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  25m 24s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 42s |  |  hadoop-mapreduce-client-nativetask in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 35s |  |  The patch does not generate ASF License warnings.  |
|  |   | 149m 28s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5357/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5357 |
| Optional Tests | dupname asflicense compile cc mvnsite javac unit codespell detsecrets golang |
| uname | Linux 381e8fc25580 4.15.0-197-generic #208-Ubuntu SMP Tue Nov 1 17:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 7a254b781432484628d00476b6b330f4d65f3d88 |
| Default Java | Red Hat, Inc.-1.8.0_362-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5357/1/testReport/ |
| Max. process+thread count | 616 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-nativetask U: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-nativetask |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5357/1/console |
| versions | git=2.9.5 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Hexiaoqiao** [comment]
@zhaixiaojuan Thanks for your works. Please follow this guide to submit new PR. https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

**Comment by zhaixiaojuan** [comment]
@Hexiaoqiao 
Hi xiaoqiao, When I send a jira application to private@hadoop.org, the email keeps getting bounced, and my local firewall has been closed. And I tried to send it multiple times, but it was returned.

**Comment by Hexiaoqiao** [comment]
> When I send a jira application to [private@hadoop.org](mailto:private@hadoop.org), the email keeps getting bounced, and my local firewall has been closed. And I tried to send it multiple times, but it was returned.

@zhaixiaojuan  Sorry, I am sure the mail address was mistake, just update at wiki, and you should send information(as wiki mentioned) to private#hadoop.apache.org (Please replace '#' to '@' here).

**Pull request closed without merging**
