### PR TITLE
Create REad.me

### PR DESCRIPTION
**Pull request by kholoud1234**
thank u

### CODE REVIEW

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 36 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| +1 | shadedclient | 754 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 760 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| -1 | asflicense | 29 | The patch generated 1 ASF License warnings. |
| | | 1695 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-358/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/358 |
| Optional Tests | dupname asflicense |
| uname | Linux b32df9f9b3da 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 7f1b76c |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/1/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 444 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 91 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| +1 | shadedclient | 841 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 857 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| -1 | asflicense | 28 | The patch generated 1 ASF License warnings. |
| | | 1911 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-358/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/358 |
| Optional Tests | dupname asflicense |
| uname | Linux 90e6487e588d 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c7c7a88 |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/2/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 306 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 40 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| +1 | shadedclient | 704 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 724 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| -1 | asflicense | 28 | The patch generated 1 ASF License warnings. |
| | | 1581 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-358/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/358 |
| Optional Tests | dupname asflicense |
| uname | Linux 53983d784a82 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e872ceb |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/3/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 412 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/3/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 43 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| +1 | shadedclient | 695 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 715 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| -1 | asflicense | 27 | The patch generated 1 ASF License warnings. |
| | | 1572 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-358/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/358 |
| Optional Tests | dupname asflicense |
| uname | Linux 804df37218f4 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 00b5a27 |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/4/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 446 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/4/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 78 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| +1 | shadedclient | 844 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 882 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| -1 | asflicense | 30 | The patch generated 1 ASF License warnings. |
| | | 1932 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-358/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/358 |
| Optional Tests | dupname asflicense |
| uname | Linux 8377c3c39a41 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e356e4f |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/5/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 308 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/5/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 43 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| +1 | shadedclient | 736 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 731 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| -1 | asflicense | 29 | The patch generated 1 ASF License warnings. |
| | | 1624 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-358/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/358 |
| Optional Tests | dupname asflicense |
| uname | Linux 7e7f3ca1f9ef 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 094d736 |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/6/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 448 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/6/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 43 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| +1 | shadedclient | 715 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 673 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| -1 | asflicense | 25 | The patch generated 1 ASF License warnings. |
| | | 1536 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-358/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/358 |
| Optional Tests | dupname asflicense |
| uname | Linux e813b63d40e3 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 61b2df2 |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/7/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 447 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/7/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 40 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| +1 | shadedclient | 752 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 756 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| -1 | asflicense | 29 | The patch generated 1 ASF License warnings. |
| | | 1675 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-358/8/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/358 |
| Optional Tests | dupname asflicense |
| uname | Linux d7a537f8f953 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3329257 |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/8/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 446 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/8/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| +1 | shadedclient | 770 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 782 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| -1 | asflicense | 31 | The patch generated 1 ASF License warnings. |
| | | 1725 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-358/9/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/358 |
| Optional Tests | dupname asflicense |
| uname | Linux 75e6a5bdff1b 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 915cbc9 |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/9/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 441 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-358/9/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
README.txt already exists. Closing this.

**Pull request closed without merging**
