### PR TITLE
HADOOP-18088. Replace log4j 1.x with reload4j.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/HADOOP-18088

This is backport to branch-2.10 of HADOOP-18088.

### CODE REVIEW

**Comment by iwasakims** [comment]
```
$ mvn clean install -DskipTests -Pnative -Pdist
$ find hadoop-dist/target/hadoop-2.10.2-SNAPSHOT -name '*log4j*.jar'
$ find hadoop-dist/target/hadoop-2.10.2-SNAPSHOT -name '*reload4j*.jar'
hadoop-dist/target/hadoop-2.10.2-SNAPSHOT/share/hadoop/common/lib/reload4j-1.2.18.3.jar
hadoop-dist/target/hadoop-2.10.2-SNAPSHOT/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar
hadoop-dist/target/hadoop-2.10.2-SNAPSHOT/share/hadoop/hdfs/lib/reload4j-1.2.18.3.jar
hadoop-dist/target/hadoop-2.10.2-SNAPSHOT/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/reload4j-1.2.18.3.jar
hadoop-dist/target/hadoop-2.10.2-SNAPSHOT/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/slf4j-reload4j-1.7.36.jar
hadoop-dist/target/hadoop-2.10.2-SNAPSHOT/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/reload4j-1.2.18.3.jar
hadoop-dist/target/hadoop-2.10.2-SNAPSHOT/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/slf4j-reload4j-1.7.36.jar
hadoop-dist/target/hadoop-2.10.2-SNAPSHOT/share/hadoop/yarn/lib/reload4j-1.2.18.3.jar
hadoop-dist/target/hadoop-2.10.2-SNAPSHOT/share/hadoop/mapreduce/lib/reload4j-1.2.18.3.jar
hadoop-dist/target/hadoop-2.10.2-SNAPSHOT/share/hadoop/tools/lib/reload4j-1.2.18.3.jar
```

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   8m 17s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-2.10 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 52s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  13m 48s |  |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |  13m 18s |  |  branch-2.10 passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  compile  |  10m 45s |  |  branch-2.10 passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  checkstyle  |   2m  6s |  |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |  10m 46s |  |  branch-2.10 passed  |
| -1 :x: |  javadoc  |   0m 45s | [/branch-javadoc-root-jdkAzulSystems,Inc.-1.7.0_262-b10.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/1/artifact/out/branch-javadoc-root-jdkAzulSystems,Inc.-1.7.0_262-b10.txt) |  root in branch-2.10 failed with JDK Azul Systems, Inc.-1.7.0_262-b10.  |
| +1 :green_heart: |  javadoc  |   5m 12s |  |  branch-2.10 passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +0 :ok: |  spotbugs  |   0m 39s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 18s |  |  branch/hadoop-assemblies no spotbugs output file (spotbugsXml.xml)  |
| -1 :x: |  spotbugs  |  22m 32s | [/branch-spotbugs-root-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/1/artifact/out/branch-spotbugs-root-warnings.html) |  root in branch-2.10 has 4 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   1m 38s | [/branch-spotbugs-hadoop-common-project_hadoop-common-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/1/artifact/out/branch-spotbugs-hadoop-common-project_hadoop-common-warnings.html) |  hadoop-common-project/hadoop-common in branch-2.10 has 2 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   2m  4s | [/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/1/artifact/out/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-warnings.html) |  hadoop-hdfs-project/hadoop-hdfs in branch-2.10 has 1 extant spotbugs warnings.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 29s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  23m  4s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  13m 19s |  |  the patch passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javac  |  13m 19s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  11m  0s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  javac  |  11m  0s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m  2s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  10m 54s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m 31s |  |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 26s | [/patch-javadoc-root-jdkAzulSystems,Inc.-1.7.0_262-b10.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/1/artifact/out/patch-javadoc-root-jdkAzulSystems,Inc.-1.7.0_262-b10.txt) |  root in the patch failed with JDK Azul Systems, Inc.-1.7.0_262-b10.  |
| +1 :green_heart: |  javadoc  |   5m 17s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +0 :ok: |  spotbugs  |   0m 16s |  |  hadoop-project has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 17s |  |  hadoop-assemblies has no data from spotbugs  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 432m 56s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/1/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| -1 :x: |  asflicense  |   1m 20s | [/results-asflicense.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/1/artifact/out/results-asflicense.txt) |  The patch generated 2 ASF License warnings.  |
|  |   | 667m 10s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.io.compress.TestCompressorDecompressor |
|   | hadoop.util.TestClassUtil |
|   | hadoop.io.compress.snappy.TestSnappyCompressorDecompressor |
|   | hadoop.fs.sftp.TestSFTPFileSystem |
|   | hadoop.contrib.bkjournal.TestBookKeeperHACheckpoints |
|   | hadoop.yarn.sls.appmaster.TestAMSimulator |
|   | hadoop.fs.azure.TestBlobMetadata |
|   | hadoop.fs.azure.TestNativeAzureFileSystemConcurrency |
|   | hadoop.fs.azure.TestNativeAzureFileSystemFileNameCheck |
|   | hadoop.fs.azure.TestWasbFsck |
|   | hadoop.fs.azure.TestNativeAzureFileSystemOperationsMocked |
|   | hadoop.fs.azure.TestOutOfBandAzureBlobOperations |
|   | hadoop.fs.azure.TestNativeAzureFileSystemContractMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemMocked |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4151 |
| Optional Tests | dupname asflicense codespell compile javac javadoc mvninstall mvnsite unit shadedclient xml spotbugs checkstyle |
| uname | Linux fb7c007a87de 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / f241a09c30a7091f182217b6346a540e4330551a |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_262-b10 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/1/testReport/ |
| Max. process+thread count | 3935 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-assemblies hadoop-common-project/hadoop-minikdc hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-auth-examples hadoop-common-project/hadoop-common hadoop-common-project/hadoop-nfs hadoop-common-project/hadoop-kms hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-httpfs hadoop-hdfs-project/hadoop-hdfs-nfs hadoop-hdfs-project/hadoop-hdfs-rbf hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell hadoop-mapreduce-project/hadoop-mapreduce-client hadoop-mapreduce-project hadoop-tools/hadoop-azure . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by iwasakims** [comment]
The failure of TestClassUtil is relevant. I missed to include the change on backporting.

**Comment by iwasakims** [comment]
Test failures related to wasb are reproducible even without the patch. I could not reproduce other failures on my local.

**Comment by iwasakims** [comment]
I got no issue on manual testing on my local security-enabled-pseudo-distributed cluster including kms and httpfs.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 40s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-2.10 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 55s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  14m 30s |  |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |  13m 57s |  |  branch-2.10 passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  compile  |  11m 46s |  |  branch-2.10 passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  checkstyle  |   2m 15s |  |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |  12m 35s |  |  branch-2.10 passed  |
| -1 :x: |  javadoc  |   0m 47s | [/branch-javadoc-root-jdkAzulSystems,Inc.-1.7.0_262-b10.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/2/artifact/out/branch-javadoc-root-jdkAzulSystems,Inc.-1.7.0_262-b10.txt) |  root in branch-2.10 failed with JDK Azul Systems, Inc.-1.7.0_262-b10.  |
| +1 :green_heart: |  javadoc  |   5m 49s |  |  branch-2.10 passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +0 :ok: |  spotbugs  |   0m 39s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 18s |  |  branch/hadoop-assemblies no spotbugs output file (spotbugsXml.xml)  |
| -1 :x: |  spotbugs  |  27m 28s | [/branch-spotbugs-root-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/2/artifact/out/branch-spotbugs-root-warnings.html) |  root in branch-2.10 has 4 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   1m 58s | [/branch-spotbugs-hadoop-common-project_hadoop-common-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/2/artifact/out/branch-spotbugs-hadoop-common-project_hadoop-common-warnings.html) |  hadoop-common-project/hadoop-common in branch-2.10 has 2 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   2m 20s | [/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/2/artifact/out/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-warnings.html) |  hadoop-hdfs-project/hadoop-hdfs in branch-2.10 has 1 extant spotbugs warnings.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  21m  3s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  13m  5s |  |  the patch passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javac  |  13m  5s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  10m 59s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  javac  |  10m 59s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m  5s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  10m 54s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m 32s |  |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 26s | [/patch-javadoc-root-jdkAzulSystems,Inc.-1.7.0_262-b10.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/2/artifact/out/patch-javadoc-root-jdkAzulSystems,Inc.-1.7.0_262-b10.txt) |  root in the patch failed with JDK Azul Systems, Inc.-1.7.0_262-b10.  |
| +1 :green_heart: |  javadoc  |   5m 24s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +0 :ok: |  spotbugs  |   0m 14s |  |  hadoop-project has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 14s |  |  hadoop-assemblies has no data from spotbugs  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 435m 36s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/2/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| -1 :x: |  asflicense  |   1m 20s | [/results-asflicense.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/2/artifact/out/results-asflicense.txt) |  The patch generated 2 ASF License warnings.  |
|  |   | 671m 20s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.io.compress.TestCompressorDecompressor |
|   | hadoop.io.compress.snappy.TestSnappyCompressorDecompressor |
|   | hadoop.fs.sftp.TestSFTPFileSystem |
|   | hadoop.contrib.bkjournal.TestBookKeeperHACheckpoints |
|   | hadoop.fs.azure.TestBlobMetadata |
|   | hadoop.fs.azure.TestNativeAzureFileSystemConcurrency |
|   | hadoop.fs.azure.TestNativeAzureFileSystemFileNameCheck |
|   | hadoop.fs.azure.TestWasbFsck |
|   | hadoop.fs.azure.TestNativeAzureFileSystemOperationsMocked |
|   | hadoop.fs.azure.TestOutOfBandAzureBlobOperations |
|   | hadoop.fs.azure.TestNativeAzureFileSystemContractMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemMocked |
|   | hadoop.yarn.client.api.impl.TestAMRMProxy |
|   | hadoop.mapreduce.v2.app.rm.TestRMContainerAllocator |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4151 |
| Optional Tests | dupname asflicense codespell compile javac javadoc mvninstall mvnsite unit shadedclient xml spotbugs checkstyle |
| uname | Linux a370bd1143fa 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / 4ead943c6037027811d2b8816e23743c3190671d |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_262-b10 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/2/testReport/ |
| Max. process+thread count | 3937 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-assemblies hadoop-common-project/hadoop-minikdc hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-auth-examples hadoop-common-project/hadoop-common hadoop-common-project/hadoop-nfs hadoop-common-project/hadoop-kms hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-httpfs hadoop-hdfs-project/hadoop-hdfs-nfs hadoop-hdfs-project/hadoop-hdfs-rbf hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell hadoop-mapreduce-project/hadoop-mapreduce-client hadoop-mapreduce-project hadoop-tools/hadoop-azure . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4151/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by iwasakims** [comment]
Warnings about javadoc, spotbugs and asflicense are not related (as expected since this is backport of #4084). I will merge this shortly.

**Pull request merged**
