### PR TITLE
HDFS-16449. Fix hadoop web site release notes and changelog not available

### PR DESCRIPTION
**Pull request by GuoPhilipse**
image
image

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 57s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  yamllint  |   0m  0s |  |  yamllint was not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  12m 27s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  26m 49s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |  34m  2s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  96m 22s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  25m 43s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  21m 45s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  44m 17s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 38s |  |  The patch does not generate ASF License warnings.  |
|  |   | 169m 51s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3967/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3967 |
| Optional Tests | dupname asflicense codespell yamllint mvnsite markdownlint |
| uname | Linux 3a54dcc56a67 4.15.0-162-generic #170-Ubuntu SMP Mon Oct 18 11:38:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / c801493f102bcdb5b51de9b1088bccdd0deba216 |
| Max. process+thread count | 575 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3967/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by aajisaka — APPROVED** [review]
LGTM

**Review by ayushtkn — APPROVED** [review]
+1

**Comment by aajisaka** [comment]
Merged. Thank you @GuoPhilipse and @ayushtkn

**Pull request merged**
