### PR TITLE
HDDS-1487. Bootstrap React framework for Recon UI

### PR DESCRIPTION
**Pull request by vivekratnavel**
Bootstrap React with Typescript, Ant, LESS and other necessary libraries for Recon UI. 

This PR also adds necessary changes to recon pom.xml to bring React UI up when starting recon server

Screen Shot 2019-05-16 at 3 42 51 PM

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 31 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 398 | trunk passed |
| +1 | compile | 202 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1018 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 127 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 536 | the patch passed |
| -1 | jshint | 2427 | The patch generated 15 new + 0 unchanged - 7061 fixed = 15 total (was 7061) |
| +1 | compile | 264 | the patch passed |
| +1 | javac | 264 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 622 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 141 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 138 | hadoop-hdds in the patch failed. |
| -1 | unit | 1439 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 46 | The patch does not generate ASF License warnings. |
| | | 7312 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.container.common.statemachine.commandhandler.TestBlockDeletion |
|   | hadoop.ozone.om.TestScmSafeMode |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-831/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/831 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml jshint |
| uname | Linux eecc757b3f47 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c183bd8 |
| Default Java | 1.8.0_212 |
| jshint | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/1/artifact/out/diff-patch-jshint.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/1/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/1/testReport/ |
| Max. process+thread count | 4563 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/ozone-recon U: hadoop-ozone/ozone-recon |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/1/console |
| versions | git=2.7.4 maven=3.3.9 jshint=2.10.2 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 32 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 399 | trunk passed |
| +1 | compile | 197 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 962 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 114 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 506 | the patch passed |
| -1 | jshint | 2527 | The patch generated 16 new + 0 unchanged - 7061 fixed = 16 total (was 7061) |
| +1 | compile | 265 | the patch passed |
| +1 | javac | 265 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 640 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 139 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 151 | hadoop-hdds in the patch failed. |
| -1 | unit | 1514 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 43 | The patch does not generate ASF License warnings. |
| | | 7420 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.container.ozoneimpl.TestOzoneContainer |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-831/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/831 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml jshint |
| uname | Linux ca20bb919b7c 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 0d1d7c8 |
| Default Java | 1.8.0_212 |
| jshint | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/2/artifact/out/diff-patch-jshint.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/2/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/2/testReport/ |
| Max. process+thread count | 4272 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/ozone-recon U: hadoop-ozone/ozone-recon |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/2/console |
| versions | git=2.7.4 maven=3.3.9 jshint=2.10.2 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by anuengineer** [comment]
@jiwq  Thanks for the review. @vivekratnavel  Thanks for the contribution, I will commit this to the trunk.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 30 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for branch |
| +1 | mvninstall | 383 | trunk passed |
| +1 | compile | 206 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1021 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 117 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 14 | Maven dependency ordering for patch |
| +1 | mvninstall | 521 | the patch passed |
| -1 | jshint | 2530 | The patch generated 16 new + 0 unchanged - 7061 fixed = 16 total (was 7061) |
| +1 | compile | 253 | the patch passed |
| +1 | javac | 253 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 616 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 140 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 136 | hadoop-hdds in the patch failed. |
| -1 | unit | 1108 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 39 | The patch does not generate ASF License warnings. |
| | | 8947 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.ozone.TestMiniOzoneCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-831/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/831 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml jshint |
| uname | Linux 2b365b517b45 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 24c53e0 |
| Default Java | 1.8.0_212 |
| jshint | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/3/artifact/out/diff-patch-jshint.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/3/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/3/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/3/testReport/ |
| Max. process+thread count | 4533 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone hadoop-ozone/ozone-recon U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-831/3/console |
| versions | git=2.7.4 maven=3.3.9 jshint=2.10.2 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
