### PR TITLE
YARN-10814 3.1 backport

### PR DESCRIPTION
**Pull request by tomicooler**
## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   9m 21s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  24m 40s |  |  branch-3.1 passed  |
| -1 :x: |  compile  |   1m  2s | [/branch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/1/artifact/out/branch-compile-root.txt) |  root in branch-3.1 failed.  |
| +1 :green_heart: |  checkstyle  |   0m 22s |  |  branch-3.1 passed  |
| +1 :green_heart: |  mvnsite  |   0m 31s |  |  branch-3.1 passed  |
| +1 :green_heart: |  javadoc  |   0m 24s |  |  branch-3.1 passed  |
| +1 :green_heart: |  spotbugs  |   0m 44s |  |  branch-3.1 passed  |
| +1 :green_heart: |  shadedclient  |  12m 40s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 24s |  |  the patch passed  |
| -1 :x: |  compile  |   0m 53s | [/patch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/1/artifact/out/patch-compile-root.txt) |  root in the patch failed.  |
| -1 :x: |  javac  |   0m 53s | [/patch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/1/artifact/out/patch-compile-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 14s |  |  hadoop-common-project/hadoop-auth: The patch generated 0 new + 149 unchanged - 1 fixed = 149 total (was 150)  |
| +1 :green_heart: |  mvnsite  |   0m 23s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 17s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   0m 46s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  13m 50s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 53s |  |  hadoop-auth in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 31s |  |  The patch does not generate ASF License warnings.  |
|  |   |  71m 16s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3286 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 2965ec84da28 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.1 / f053c5f3517820b94ce2f2748585b767d50a2dd1 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/1/testReport/ |
| Max. process+thread count | 411 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-auth U: hadoop-common-project/hadoop-auth |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 45s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  26m 35s |  |  branch-3.1 passed  |
| -1 :x: |  compile  |   1m  1s | [/branch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/3/artifact/out/branch-compile-root.txt) |  root in branch-3.1 failed.  |
| +1 :green_heart: |  checkstyle  |   0m 23s |  |  branch-3.1 passed  |
| +1 :green_heart: |  mvnsite  |   0m 31s |  |  branch-3.1 passed  |
| +1 :green_heart: |  javadoc  |   0m 24s |  |  branch-3.1 passed  |
| +1 :green_heart: |  spotbugs  |   0m 44s |  |  branch-3.1 passed  |
| +1 :green_heart: |  shadedclient  |  12m 54s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 26s |  |  the patch passed  |
| -1 :x: |  compile  |   0m 57s | [/patch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/3/artifact/out/patch-compile-root.txt) |  root in the patch failed.  |
| -1 :x: |  javac  |   0m 57s | [/patch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/3/artifact/out/patch-compile-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 14s |  |  hadoop-common-project/hadoop-auth: The patch generated 0 new + 149 unchanged - 1 fixed = 149 total (was 150)  |
| +1 :green_heart: |  mvnsite  |   0m 23s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 16s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   0m 45s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  13m 54s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 52s |  |  hadoop-auth in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 30s |  |  The patch does not generate ASF License warnings.  |
|  |   |  64m 43s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3286 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux d1944765cdf5 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.1 / 443de25331ada47854559a90c46a1fb542920c39 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/3/testReport/ |
| Max. process+thread count | 411 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-auth U: hadoop-common-project/hadoop-auth |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/3/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/4/console in case of problems.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m 58s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  32m 33s |  |  branch-3.1 passed  |
| +1 :green_heart: |  compile  |  19m 32s |  |  branch-3.1 passed  |
| +1 :green_heart: |  checkstyle  |   0m 39s |  |  branch-3.1 passed  |
| +1 :green_heart: |  mvnsite  |   0m 50s |  |  branch-3.1 passed  |
| +1 :green_heart: |  javadoc  |   0m 40s |  |  branch-3.1 passed  |
| +1 :green_heart: |  spotbugs  |   1m  8s |  |  branch-3.1 passed  |
| +1 :green_heart: |  shadedclient  |  16m 47s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 28s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 55s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  17m 55s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 35s |  |  hadoop-common-project/hadoop-auth: The patch generated 0 new + 149 unchanged - 1 fixed = 149 total (was 150)  |
| +1 :green_heart: |  hadolint  |   0m  2s |  |  No new issues.  |
| +1 :green_heart: |  mvnsite  |   0m 45s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   0m 41s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   1m 16s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  14m  4s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   3m 16s |  |  hadoop-auth in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 59s |  |  The patch does not generate ASF License warnings.  |
|  |   | 116m 28s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3286 |
| Optional Tests | dupname asflicense codespell hadolint shellcheck shelldocs compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle |
| uname | Linux efa4280bbe3d 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.1 / e48843a06df75474ab053834554e0f795f282fd4 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/4/testReport/ |
| Max. process+thread count | 442 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-auth U: hadoop-common-project/hadoop-auth |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/4/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 spotbugs=4.2.2 hadolint=1.11.1-0-g0e692dd |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
@tomicooler branch-3.1 is already EoL, and 3.1.5 release will never happen. Would you still want to backport it into branch-3.1?

**Comment by tomicooler** [comment]
> @tomicooler branch-3.1 is already EoL, and 3.1.5 release will never happen. Would you still want to backport it into branch-3.1?

I did not know about the EoL, sorry.

The build environment fix is already merged to branch 3.1, so this could be too. But I am OK with abandoning the PR as well.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 40s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  26m 29s |  |  branch-3.1 passed  |
| +1 :green_heart: |  compile  |  14m  4s |  |  branch-3.1 passed  |
| +1 :green_heart: |  checkstyle  |   0m 35s |  |  branch-3.1 passed  |
| +1 :green_heart: |  mvnsite  |   0m 43s |  |  branch-3.1 passed  |
| +1 :green_heart: |  javadoc  |   0m 35s |  |  branch-3.1 passed  |
| +1 :green_heart: |  spotbugs  |   0m 55s |  |  branch-3.1 passed  |
| +1 :green_heart: |  shadedclient  |  13m  1s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 25s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  13m 26s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  13m 26s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 32s |  |  hadoop-common-project/hadoop-auth: The patch generated 0 new + 149 unchanged - 1 fixed = 149 total (was 150)  |
| +1 :green_heart: |  mvnsite  |   0m 42s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 34s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   1m  4s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  13m  0s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   3m  6s |  |  hadoop-auth in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 49s |  |  The patch does not generate ASF License warnings.  |
|  |   |  92m 39s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3286 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux f7a8b3d85bab 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.1 / 12bd9f50b1a7fe2877ed76bbe976a032be2dcd4f |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/5/testReport/ |
| Max. process+thread count | 428 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-auth U: hadoop-common-project/hadoop-auth |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3286/5/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by szilard-nemeth** [comment]
> @tomicooler branch-3.1 is already EoL, and 3.1.5 release will never happen. Would you still want to backport it into branch-3.1?

Thanks for bringing this in. I didn't know about making the 3.1 line EoL, either. Was there an "official" communication about this? If so, seems like I just missed it :S

**Comment by tomicooler** [comment]
Closing the pull request. Thanks for the feedback.

**Pull request closed without merging**
