### PR TITLE
HADOOP-18574. Changing log level of IOStatistics increment to make the DEBUG logs less noisy.

### PR DESCRIPTION
**Pull request by mehakmeet**
### Description of PR

Backport to #5223.

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   9m 59s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  39m 31s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m 40s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   0m 53s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   1m 32s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   0m 46s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   2m 41s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  27m 57s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 58s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 59s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  17m 59s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  1s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 47s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 30s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 37s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   2m 37s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  27m 19s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  17m 34s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 52s |  |  The patch does not generate ASF License warnings.  |
|  |   | 171m 12s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5225/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5225 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux c17663f0b86d 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / adbf323dd12f50d91aa3fca8b46c2d8bcc9a3a7e |
| Default Java | Private Build-1.8.0_352-8u352-ga-1~18.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5225/1/testReport/ |
| Max. process+thread count | 3137 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5225/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by mehakmeet** [comment]
Seems @steveloughran has already backported the change to 3.3.5. closing this PR.

**Comment by steveloughran** [comment]
yeah, just cherrypicked

**Comment by mehakmeet** [comment]
> yeah, just cherrypicked

Thanks. I need to set that up first thing once I'm back from vacation 😄

**Pull request closed without merging**
