### PR TITLE
HADOOP-15455. Incorrect debug message in KMSACL#hasAccess

### PR DESCRIPTION
**Pull request by phstudy**
Fix debug message.

### CODE REVIEW

**Comment by jojochuang** [comment]
+1
it appears you don't have a Apache Jira account. If you have one, let me know and I can assign the jira to you.

**Comment by phstudy** [comment]
@jojochuang My Apache Jira username is `study`. Thanks.

**Comment by jamestalcup** [comment]
Nice

**Comment by adipan** [comment]
@jojochuang this PR looks good to me too. +1

**Comment by aajisaka** [comment]
@phstudy Would you close this PR?
This commit was pushed to trunk. https://github.com/apache/hadoop/commit/438ef4951a38171f193eaf2631da31d0f4bc3c62

**Pull request closed without merging**
