### PR TITLE
HDFS-17098. DatanodeManager does not handle null storage type properly.

### PR DESCRIPTION
**Pull request by Hexiaoqiao**
### Description of PR
1. From https://github.com/apache/hadoop/pull/6035 which contributed by @teamconfx.
2. Fix checkstyle and try to trigger Yetus again.

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by Hexiaoqiao** [comment]
Any update about Jenkins? Why always fail here?

**Review by slfan1989 — APPROVED** [review]

**Comment by slfan1989** [comment]
I have noticed some issues with the CI, as some prs are not running complete checks. I remember we were adjusting the 'hadoop on windows' feature, which should have involved modifying the CI. Is there any progress on this matter?

@GauthamBanasandra 

cc: @ayushtkn @steveloughran

**Comment by GauthamBanasandra** [comment]
@slfan1989 I only disabled the [Apache Hadoop Multibranch pipeline for Windows 10](https://ci-hadoop.apache.org/view/Hadoop/job/hadoop-multibranch-windows-10/) -

image


I didn't touch the [CI for Linux](https://ci-hadoop.apache.org/view/Hadoop/job/hadoop-multibranch/) and it's enabled.

**Comment by slfan1989** [comment]
> @slfan1989 I only disabled the [Apache Hadoop Multibranch pipeline for Windows 10](https://ci-hadoop.apache.org/view/Hadoop/job/hadoop-multibranch-windows-10/) -
> 
> image
> 
> I didn't touch the [CI for Linux](https://ci-hadoop.apache.org/view/Hadoop/job/hadoop-multibranch/) and it's enabled.

Thank you for your reply! After discussion, we have found the cause of CI failure, which should be related to upgrading surefire (#6664), and the related pr has been rolled back.

**Comment by Hexiaoqiao** [comment]
Thanks all. Try to trigger CI again and let's wait what it will say.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 21s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  32m 27s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   0m 42s |  |  trunk passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2  |
| +1 :green_heart: |  compile  |   0m 37s |  |  trunk passed with JDK Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08  |
| +1 :green_heart: |  checkstyle  |   0m 40s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 42s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   0m 40s |  |  trunk passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2  |
| +1 :green_heart: |  javadoc  |   1m  5s |  |  trunk passed with JDK Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08  |
| +1 :green_heart: |  spotbugs  |   1m 43s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  20m 42s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 37s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 36s |  |  the patch passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2  |
| +1 :green_heart: |  javac  |   0m 36s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 32s |  |  the patch passed with JDK Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08  |
| +1 :green_heart: |  javac  |   0m 32s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 28s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 37s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 30s |  |  the patch passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2  |
| +1 :green_heart: |  javadoc  |   1m  1s |  |  the patch passed with JDK Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08  |
| +1 :green_heart: |  spotbugs  |   1m 38s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  20m 42s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 211m  8s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6840/4/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 28s |  |  The patch does not generate ASF License warnings.  |
|  |   | 297m 30s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.datanode.fsdataset.impl.TestFsDatasetImpl |
|   | hadoop.hdfs.server.blockmanagement.TestDatanodeManager |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.45 ServerAPI=1.45 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6840/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6840 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 620c1788bd6e 5.15.0-106-generic #116-Ubuntu SMP Wed Apr 17 09:17:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 97e987746192b3dd5e9b1c5ae91773a30bc6b32a |
| Default Java | Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu120.04.2 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_412-8u412-ga-1~20.04.1-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6840/4/testReport/ |
| Max. process+thread count | 4528 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6840/4/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Hexiaoqiao** [comment]
Failed unit tests are not related to this PR. Merged to trunk. Thanks @slfan1989 and also @teamconfx .

**Comment by ayushtkn** [comment]
@Hexiaoqiao / @slfan1989  looks like ``TestDatanodeManager`` is related, it is failing in the daily jobs. If I revert this locally the test passes for me.
Can you check once, I created [HDFS-17571](https://issues.apache.org/jira/browse/HDFS-17571). before I started investigating

**Comment by Hexiaoqiao** [comment]
@ayushtkn Thanks for your reminder. https://github.com/apache/hadoop/pull/6919 try to follow and fix it.

**Pull request merged**
