### PR TITLE
HADOOP-15014: KMS should capture the originating IP address

### PR DESCRIPTION
**Pull request by gzsombor**
. and log it in case of error, with a test

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 25 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1098 | trunk passed |
| +1 | compile | 1029 | trunk passed |
| +1 | checkstyle | 23 | trunk passed |
| +1 | mvnsite | 33 | trunk passed |
| +1 | shadedclient | 702 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 38 | trunk passed |
| +1 | javadoc | 24 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 22 | the patch passed |
| +1 | compile | 997 | the patch passed |
| +1 | javac | 997 | the patch passed |
| +1 | checkstyle | 23 | the patch passed |
| +1 | mvnsite | 32 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 644 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 43 | the patch passed |
| +1 | javadoc | 23 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 239 | hadoop-kms in the patch passed. |
| +1 | asflicense | 37 | The patch does not generate ASF License warnings. |
| | | 5142 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-680/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/680 |
| JIRA Issue | HADOOP-15014 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux f76aa7e57f7b 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / bfc90bd |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-680/1/testReport/ |
| Max. process+thread count | 464 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-kms U: hadoop-common-project/hadoop-kms |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-680/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 12 | https://github.com/apache/hadoop/pull/680 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/680 |
| JIRA Issue | HADOOP-15014 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-680/2/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 12 | https://github.com/apache/hadoop/pull/680 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/680 |
| JIRA Issue | HADOOP-15014 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-680/3/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 10 | https://github.com/apache/hadoop/pull/680 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/680 |
| JIRA Issue | HADOOP-15014 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-680/4/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 8 | https://github.com/apache/hadoop/pull/680 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/680 |
| JIRA Issue | HADOOP-15014 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-680/5/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
Close this one. Since the it was committed using the patch attached to the jira.

**Pull request closed without merging**
