### PR TITLE
HDFS-15975. Use LongAdder instead of AtomicLong for branch-3.3

### PR DESCRIPTION
**Pull request by tomscut**
JIRA: [HDFS-15975](https://issues.apache.org/jira/browse/HDFS-15975)

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  18m 25s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 32s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  20m 38s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  17m  9s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   2m 45s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   4m 10s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   4m  8s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   8m  2s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  18m 41s |  |  branch has no errors when building and testing our client artifacts.  |
| -0 :warning: |  patch  |  19m  5s |  |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 49s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 35s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  16m 35s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   2m 36s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2940/1/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 5 new + 243 unchanged - 5 fixed = 248 total (was 248)  |
| +1 :green_heart: |  mvnsite  |   4m  8s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   4m  8s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   8m 40s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  18m 34s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  17m 35s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 29s |  |  hadoop-hdfs-client in the patch passed.  |
| -1 :x: |  unit  | 185m 34s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2940/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  7s |  |  The patch does not generate ASF License warnings.  |
|  |   | 370m 55s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.TestAddStripedBlockInFBR |
|   | hadoop.hdfs.server.datanode.TestBPOfferService |
|   | hadoop.hdfs.TestReconstructStripedFile |
|   | hadoop.hdfs.TestReconstructStripedFileWithRandomECPolicy |
|   | hadoop.hdfs.TestReconstructStripedFileWithValidator |
|   | hadoop.hdfs.TestStripedFileAppend |
|   | hadoop.hdfs.qjournal.server.TestJournalNodeRespectsBindHostKeys |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2940/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2940 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 5e9773e8c1f5 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / c9772e37b331850419680bc45fa693b3d1c965ce |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~18.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2940/1/testReport/ |
| Max. process+thread count | 3557 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2940/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by tasanuma** [comment]
Could rebase on branch-3.3 and force-push it to clean commit log?

**Comment by tomscut** [comment]
> Could rebase on branch-3.3 and force-push it to clean commit log?

Hi @tasanuma . I'm sorry, I just saw the message today. I have rebase and commit it.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  21m 12s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  15m  0s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  20m 43s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  17m 17s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   2m 40s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   4m 11s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   4m  9s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   8m  5s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  18m 41s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 28s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 51s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 37s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  16m 37s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   2m 39s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2940/2/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 5 new + 243 unchanged - 5 fixed = 248 total (was 248)  |
| +1 :green_heart: |  mvnsite  |   4m 10s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   4m 11s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   8m 43s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  18m 44s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |  17m  8s | [/patch-unit-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2940/2/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt) |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 33s |  |  hadoop-hdfs-client in the patch passed.  |
| -1 :x: |  unit  | 187m 22s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2940/2/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  8s |  |  The patch does not generate ASF License warnings.  |
|  |   | 377m 14s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.fs.ftp.TestFTPFileSystem |
|   | hadoop.hdfs.TestReconstructStripedFile |
|   | hadoop.hdfs.TestReconstructStripedFileWithRandomECPolicy |
|   | hadoop.hdfs.TestReconstructStripedFileWithValidator |
|   | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |
|   | hadoop.hdfs.server.namenode.ha.TestStandbyCheckpoints |
|   | hadoop.hdfs.qjournal.server.TestJournalNodeRespectsBindHostKeys |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2940/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2940 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 0806822b7565 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / c4c0469cbef81be6268bbac9a840009619e2d6b0 |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~18.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2940/2/testReport/ |
| Max. process+thread count | 3759 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2940/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by tasanuma** [comment]
The failed tests are not related. (TestReconstructStripedFile#testErasureCodingWorkerXmitsWeight fails with/without this PR. I will cherry-pick HDFS-15378.)

**Review by tasanuma — APPROVED** [review]
+1.

**Comment by tasanuma** [comment]
Merged. Thanks for your work, @tomscut!

**Comment by tomscut** [comment]
> The failed tests are not related. (TestReconstructStripedFile#testErasureCodingWorkerXmitsWeight fails with/without this PR. I will cherry-pick [HDFS-15378](https://issues.apache.org/jira/browse/HDFS-15378).)

I also founded this problem, but I haven't had time to analyze why. Thanks @tasanuma for you help.

**Pull request merged**
