### PR TITLE
Hadoop 18712. upgrade to jetty 9.4.51 due to cve

### PR DESCRIPTION
**Pull request by pjfanning**
### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  10m 37s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  1s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  1s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  1s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 53s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  23m 47s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  17m 50s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  25m 17s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   7m  1s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  29m 57s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 58s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  21m 42s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 20s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  17m 20s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  20m 52s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   6m 47s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  30m 38s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 741m  2s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5585/1/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 36s |  |  The patch does not generate ASF License warnings.  |
|  |   | 961m  1s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.qjournal.server.TestJournalNodeSync |
|   | hadoop.hdfs.tools.TestDFSAdmin |
|   | hadoop.yarn.server.nodemanager.containermanager.logaggregation.TestLogAggregationService |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5585/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5585 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint shellcheck shelldocs |
| uname | Linux 3fae56a1bd80 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / ce803ef58b4b8627502593244abcc3e751ee5a82 |
| Default Java | Private Build-1.8.0_362-8u362-ga-0ubuntu1~18.04.1-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5585/1/testReport/ |
| Max. process+thread count | 3336 (vs. ulimit of 5500) |
| modules | C: hadoop-project . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5585/1/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ayushtkn** [comment]
It isn't letting me access the test results, something broken for this run, neither it is letting me retrigger, @pjfanning can you rebase and push once?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 50s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  16m  8s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  24m  2s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  17m 51s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  25m 56s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   7m  1s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  29m 48s |  |  branch has no errors when building and testing our client artifacts.  |
| -0 :warning: |  patch  |  30m  8s |  |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   1m  1s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  21m 50s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 14s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  17m 14s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  20m 47s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   6m 47s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  30m 23s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 734m 30s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5585/2/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 36s |  |  The patch does not generate ASF License warnings.  |
|  |   | 945m 40s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.fs.contract.router.web.TestRouterWebHDFSContractCreate |
|   | hadoop.yarn.client.api.impl.TestAMRMClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5585/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5585 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint shellcheck shelldocs |
| uname | Linux 76386fd69d2f 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 0587ca8924c70b4718453f2798c42c66b9e420f9 |
| Default Java | Private Build-1.8.0_362-8u362-ga-0ubuntu1~18.04.1-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5585/2/testReport/ |
| Max. process+thread count | 3186 (vs. ulimit of 5500) |
| modules | C: hadoop-project . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5585/2/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by pjfanning** [comment]
@ayushtkn I did a new run - there was a merge conflict that needed fixing

**Comment by ayushtkn** [comment]
Failing tests passed locally
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.fs.contract.router.web.TestRouterWebHDFSContractCreate
[WARNING] Tests run: 16, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 15.47 s - in org.apache.hadoop.fs.contract.router.web.TestRouterWebHDFSContractCreate
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 16, Failures: 0, Errors: 0, Skipped: 2
[INFO] Running org.apache.hadoop.yarn.client.api.impl.TestAMRMClient
[WARNING] Tests run: 63, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 447.736 s - in org.apache.hadoop.yarn.client.api.impl.TestAMRMClient
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 63, Failures: 0, Errors: 0, Skipped: 1
```

Merging, Thanx @pjfanning

**Pull request merged**
