### PR TITLE
YARN-9455. SchedulerInvalidResoureRequestException has a typo in its class (and file) name

### PR DESCRIPTION
**Pull request by vietanh85**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 25 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 43 | Maven dependency ordering for branch |
| +1 | mvninstall | 1135 | trunk passed |
| +1 | compile | 586 | trunk passed |
| +1 | checkstyle | 88 | trunk passed |
| +1 | mvnsite | 103 | trunk passed |
| +1 | shadedclient | 852 | branch has no errors when building and testing our client artifacts. |
| -1 | findbugs | 88 | hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager in trunk has 2 extant Findbugs warnings. |
| +1 | javadoc | 69 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 17 | Maven dependency ordering for patch |
| +1 | mvninstall | 86 | the patch passed |
| +1 | compile | 583 | the patch passed |
| +1 | javac | 583 | the patch passed |
| -0 | checkstyle | 87 | hadoop-yarn-project/hadoop-yarn: The patch generated 1 new + 210 unchanged - 2 fixed = 211 total (was 212) |
| +1 | mvnsite | 91 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 720 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 184 | the patch passed |
| +1 | javadoc | 69 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 47 | hadoop-yarn-api in the patch passed. |
| +1 | unit | 4875 | hadoop-yarn-server-resourcemanager in the patch passed. |
| +1 | asflicense | 46 | The patch does not generate ASF License warnings. |
| | | 9910 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-705/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/705 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux 2095f770d2f4 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 0d47d28 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/1/artifact/out/branch-findbugs-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager-warnings.html |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/1/artifact/out/diff-checkstyle-hadoop-yarn-project_hadoop-yarn.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/1/testReport/ |
| Max. process+thread count | 861 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager U: hadoop-yarn-project/hadoop-yarn |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 94 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 19 | Maven dependency ordering for branch |
| +1 | mvninstall | 1385 | trunk passed |
| +1 | compile | 641 | trunk passed |
| +1 | checkstyle | 85 | trunk passed |
| +1 | mvnsite | 106 | trunk passed |
| +1 | shadedclient | 1009 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 72 | trunk passed |
| 0 | spotbugs | 113 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 217 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 16 | Maven dependency ordering for patch |
| +1 | mvninstall | 81 | the patch passed |
| +1 | compile | 587 | the patch passed |
| +1 | javac | 587 | the patch passed |
| -0 | checkstyle | 88 | hadoop-yarn-project/hadoop-yarn: The patch generated 1 new + 211 unchanged - 2 fixed = 212 total (was 213) |
| +1 | mvnsite | 109 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 824 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 70 | the patch passed |
| +1 | findbugs | 234 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 55 | hadoop-yarn-api in the patch passed. |
| -1 | unit | 4688 | hadoop-yarn-server-resourcemanager in the patch failed. |
| +1 | asflicense | 48 | The patch does not generate ASF License warnings. |
| | | 10453 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.yarn.server.resourcemanager.webapp.TestRMWebappAuthentication |
|   | hadoop.yarn.server.resourcemanager.TestApplicationMasterServiceCapacity |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesDelegationTokenAuthentication |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServiceAppsNodelabel |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesHttpStaticUserPermissions |
|   | hadoop.yarn.server.resourcemanager.rmcontainer.TestRMContainerImpl |
|   | hadoop.yarn.server.resourcemanager.TestLeaderElectorService |
|   | hadoop.yarn.webapp.TestRMWithXFSFilter |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesConfigurationMutation |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesApps |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesSchedulerActivities |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesForCSWithPartitions |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesCapacitySched |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesAppsCustomResourceTypes |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebAppFairScheduler |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesNodes |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesContainers |
|   | hadoop.yarn.server.resourcemanager.webapp.fairscheduler.TestRMWebServicesFairScheduler |
|   | hadoop.yarn.server.resourcemanager.TestCapacitySchedulerMetrics |
|   | hadoop.yarn.server.resourcemanager.TestRMHAForNodeLabels |
|   | hadoop.yarn.server.resourcemanager.TestRMHAForAsyncScheduler |
|   | hadoop.yarn.server.resourcemanager.webapp.fairscheduler.TestRMWebServicesFairSchedulerCustomResourceTypes |
|   | hadoop.yarn.webapp.TestRMWithCSRFFilter |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServices |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesSchedulerActivitiesWithMultiNodesEnabled |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesAppCustomResourceTypes |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesReservation |
|   | hadoop.yarn.server.resourcemanager.TestRMHAMetrics |
|   | hadoop.yarn.server.resourcemanager.TestRMTimelineService |
|   | hadoop.yarn.server.resourcemanager.reservation.TestReservationSystem |
|   | hadoop.yarn.server.resourcemanager.TestResourceTrackerService |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesAppsModification |
|   | hadoop.yarn.server.resourcemanager.webapp.dao.TestFairSchedulerQueueInfo |
|   | hadoop.yarn.server.resourcemanager.TestRMRestart |
|   | hadoop.yarn.server.resourcemanager.TestReservationSystemWithRMHA |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesDelegationTokens |
|   | hadoop.yarn.server.resourcemanager.TestRMHATimelineCollectors |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesNodeLabels |
|   | hadoop.yarn.server.resourcemanager.TestOpportunisticContainerAllocatorAMService |
|   | hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesAppAttempts |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-705/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/705 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux b1717a2aae70 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / cd967c7 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/2/artifact/out/diff-checkstyle-hadoop-yarn-project_hadoop-yarn.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/2/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/2/testReport/ |
| Max. process+thread count | 5325 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager U: hadoop-yarn-project/hadoop-yarn |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 61 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for branch |
| +1 | mvninstall | 1197 | trunk passed |
| +1 | compile | 642 | trunk passed |
| +1 | checkstyle | 76 | trunk passed |
| +1 | mvnsite | 107 | trunk passed |
| +1 | shadedclient | 883 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 66 | trunk passed |
| 0 | spotbugs | 120 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 228 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 16 | Maven dependency ordering for patch |
| +1 | mvninstall | 82 | the patch passed |
| +1 | compile | 658 | the patch passed |
| +1 | javac | 658 | the patch passed |
| -0 | checkstyle | 75 | hadoop-yarn-project/hadoop-yarn: The patch generated 1 new + 210 unchanged - 2 fixed = 211 total (was 212) |
| +1 | mvnsite | 98 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 732 | patch has no errors when building and testing our client artifacts. |
| -1 | javadoc | 35 | hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager generated 8 new + 4 unchanged - 0 fixed = 12 total (was 4) |
| -1 | findbugs | 35 | hadoop-yarn-server-resourcemanager in the patch failed. |
||| _ Other Tests _ |
| +1 | unit | 57 | hadoop-yarn-api in the patch passed. |
| -1 | unit | 35 | hadoop-yarn-server-resourcemanager in the patch failed. |
| +1 | asflicense | 41 | The patch does not generate ASF License warnings. |
| | | 5311 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-705/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/705 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 4569736ba251 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c0a0c35 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/3/artifact/out/diff-checkstyle-hadoop-yarn-project_hadoop-yarn.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/3/artifact/out/diff-javadoc-javadoc-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/3/artifact/out/patch-findbugs-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/3/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/3/testReport/ |
| Max. process+thread count | 414 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager U: hadoop-yarn-project/hadoop-yarn |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 47 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 42 | Maven dependency ordering for branch |
| +1 | mvninstall | 1267 | trunk passed |
| +1 | compile | 614 | trunk passed |
| +1 | checkstyle | 72 | trunk passed |
| +1 | mvnsite | 107 | trunk passed |
| +1 | shadedclient | 822 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 65 | trunk passed |
| 0 | spotbugs | 109 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 212 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for patch |
| +1 | mvninstall | 79 | the patch passed |
| +1 | compile | 617 | the patch passed |
| +1 | javac | 617 | the patch passed |
| -0 | checkstyle | 80 | hadoop-yarn-project/hadoop-yarn: The patch generated 1 new + 210 unchanged - 2 fixed = 211 total (was 212) |
| +1 | mvnsite | 115 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 762 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 81 | the patch passed |
| +1 | findbugs | 264 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 59 | hadoop-yarn-api in the patch passed. |
| -1 | unit | 5147 | hadoop-yarn-server-resourcemanager in the patch failed. |
| +1 | asflicense | 46 | The patch does not generate ASF License warnings. |
| | | 10531 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.yarn.server.resourcemanager.scheduler.capacity.TestIncreaseAllocationExpirer |
|   | hadoop.yarn.server.resourcemanager.scheduler.capacity.TestContainerResizing |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-705/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/705 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 508b19312aeb 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / a7371a7 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/5/artifact/out/diff-checkstyle-hadoop-yarn-project_hadoop-yarn.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/5/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/5/testReport/ |
| Max. process+thread count | 925 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager U: hadoop-yarn-project/hadoop-yarn |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/5/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by szilard-nemeth** [comment]
Test failures are due to https://issues.apache.org/jira/browse/YARN-7387 and https://issues.apache.org/jira/browse/YARN-8959. Committing this soon!

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for branch |
| +1 | mvninstall | 1045 | trunk passed |
| +1 | compile | 590 | trunk passed |
| +1 | checkstyle | 70 | trunk passed |
| +1 | mvnsite | 98 | trunk passed |
| +1 | shadedclient | 855 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 92 | trunk passed |
| 0 | spotbugs | 118 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 237 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 20 | Maven dependency ordering for patch |
| +1 | mvninstall | 82 | the patch passed |
| -1 | compile | 618 | hadoop-yarn in the patch failed. |
| -1 | javac | 618 | hadoop-yarn in the patch failed. |
| -0 | checkstyle | 63 | hadoop-yarn-project/hadoop-yarn: The patch generated 1 new + 210 unchanged - 2 fixed = 211 total (was 212) |
| -1 | mvnsite | 32 | hadoop-yarn-server-resourcemanager in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 674 | patch has no errors when building and testing our client artifacts. |
| -1 | javadoc | 32 | hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager generated 8 new + 4 unchanged - 0 fixed = 12 total (was 4) |
| -1 | findbugs | 37 | hadoop-yarn-server-resourcemanager in the patch failed. |
||| _ Other Tests _ |
| +1 | unit | 47 | hadoop-yarn-api in the patch passed. |
| -1 | unit | 33 | hadoop-yarn-server-resourcemanager in the patch failed. |
| +1 | asflicense | 40 | The patch does not generate ASF License warnings. |
| | | 4941 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-705/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/705 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux a57782a75305 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e20b195 |
| Default Java | 1.8.0_212 |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/6/artifact/out/patch-compile-hadoop-yarn-project_hadoop-yarn.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/6/artifact/out/patch-compile-hadoop-yarn-project_hadoop-yarn.txt |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/6/artifact/out/diff-checkstyle-hadoop-yarn-project_hadoop-yarn.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/6/artifact/out/patch-mvnsite-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/6/artifact/out/diff-javadoc-javadoc-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/6/artifact/out/patch-findbugs-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/6/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/6/testReport/ |
| Max. process+thread count | 445 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager U: hadoop-yarn-project/hadoop-yarn |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-705/6/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by szilard-nemeth** [comment]
Hi @vietanh85 !
This class is in the hadoop-yarn-api project so we would like to keep backward compatibility.
Even though we have annotations on the class: 
@InterfaceAudience.Private
@InterfaceStability.Unstable, 
if the class name changes, any application that imported this class, it won't compile if the app is upgraded to a newer Hadoop version.
Closing this PR and jira as Won't do.

**Pull request closed without merging**
