### PR TITLE
HDFS-13771. Fix enableManagedDfsDirsRedundancy typo in creating MiniDFSCluster

### PR DESCRIPTION
**Pull request by wilderchen**
fix wrong parameter while calling initNameNodeConf issue

### CODE REVIEW

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by wilderchen** [comment]
> Can one of the admins verify this patch?

Hi elek,

I can't see details of those check failed, but I am quite sure that it's a bug inside the hadoop project.

Here is the link of the jira issue: https://issues.apache.org/jira/browse/HDFS-13771

Thanks

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1075 | trunk passed |
| +1 | compile | 61 | trunk passed |
| +1 | checkstyle | 38 | trunk passed |
| +1 | mvnsite | 67 | trunk passed |
| +1 | shadedclient | 753 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 48 | trunk passed |
| 0 | spotbugs | 163 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 160 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 58 | the patch passed |
| +1 | compile | 54 | the patch passed |
| +1 | javac | 54 | the patch passed |
| +1 | checkstyle | 40 | the patch passed |
| +1 | mvnsite | 60 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 677 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 42 | the patch passed |
| +1 | findbugs | 160 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 4962 | hadoop-hdfs in the patch failed. |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 8392 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.ha.TestFailoverWithBlockTokensEnabled |
|   | hadoop.hdfs.server.namenode.ha.TestDNFencing |
|   | hadoop.hdfs.web.TestWebHdfsTimeouts |
|   | hadoop.hdfs.server.namenode.ha.TestHASafeMode |
|   | hadoop.hdfs.server.namenode.ha.TestPipelinesFailover |
|   | hadoop.hdfs.server.datanode.TestDirectoryScanner |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-404/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/404 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 2b0bb5fbfa43 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / cd967c7 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/1/testReport/ |
| Max. process+thread count | 4093 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 49 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1057 | trunk passed |
| +1 | compile | 59 | trunk passed |
| +1 | checkstyle | 39 | trunk passed |
| +1 | mvnsite | 65 | trunk passed |
| +1 | shadedclient | 734 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 58 | trunk passed |
| 0 | spotbugs | 165 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 163 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 55 | the patch passed |
| +1 | compile | 56 | the patch passed |
| +1 | javac | 56 | the patch passed |
| +1 | checkstyle | 38 | the patch passed |
| +1 | mvnsite | 60 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 688 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 52 | the patch passed |
| +1 | findbugs | 165 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 5170 | hadoop-hdfs in the patch failed. |
| -1 | asflicense | 55 | The patch generated 1 ASF License warnings. |
| | | 8637 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestErasureCodingPolicyWithSnapshotWithRandomECPolicy |
|   | hadoop.hdfs.server.namenode.TestReencryption |
|   | hadoop.hdfs.TestMultipleNNPortQOP |
|   | hadoop.hdfs.server.namenode.TestCacheDirectives |
|   | hadoop.hdfs.TestDFSStripedOutputStreamWithRandomECPolicy |
|   | hadoop.hdfs.server.namenode.TestReencryptionWithKMS |
|   | hadoop.hdfs.server.namenode.TestListCorruptFileBlocks |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-404/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/404 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 5c26c76da6e6 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c7c7a88 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/2/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/2/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/2/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 5062 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 83 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1309 | trunk passed |
| +1 | compile | 69 | trunk passed |
| +1 | checkstyle | 51 | trunk passed |
| +1 | mvnsite | 75 | trunk passed |
| +1 | shadedclient | 866 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 59 | trunk passed |
| 0 | spotbugs | 201 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 197 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 74 | the patch passed |
| +1 | compile | 67 | the patch passed |
| +1 | javac | 67 | the patch passed |
| +1 | checkstyle | 47 | the patch passed |
| +1 | mvnsite | 78 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 859 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 55 | the patch passed |
| +1 | findbugs | 198 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 6515 | hadoop-hdfs in the patch failed. |
| +1 | asflicense | 33 | The patch does not generate ASF License warnings. |
| | | 10690 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestPersistBlocks |
|   | hadoop.hdfs.server.datanode.TestLargeBlockReport |
|   | hadoop.hdfs.server.datanode.TestDataNodeRollingUpgrade |
|   | hadoop.hdfs.server.datanode.TestDataNodeErasureCodingMetrics |
|   | hadoop.hdfs.server.namenode.TestDecommissioningStatus |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-404/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/404 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux ad9cce0d49b2 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e872ceb |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/3/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/3/testReport/ |
| Max. process+thread count | 2761 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 104 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1257 | trunk passed |
| +1 | compile | 58 | trunk passed |
| +1 | checkstyle | 45 | trunk passed |
| +1 | mvnsite | 74 | trunk passed |
| +1 | shadedclient | 828 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 52 | trunk passed |
| 0 | spotbugs | 188 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 187 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 69 | the patch passed |
| +1 | compile | 55 | the patch passed |
| +1 | javac | 55 | the patch passed |
| +1 | checkstyle | 42 | the patch passed |
| +1 | mvnsite | 62 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 776 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 53 | the patch passed |
| +1 | findbugs | 171 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 6529 | hadoop-hdfs in the patch failed. |
| -1 | asflicense | 35 | The patch generated 3 ASF License warnings. |
| | | 10450 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.datanode.TestLargeBlockReport |
|   | hadoop.hdfs.TestDFSStripedOutputStreamWithFailure |
|   | hadoop.hdfs.server.namenode.snapshot.TestSnapRootDescendantDiff |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-404/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/404 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 7fbb09e07fa7 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 00b5a27 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/4/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/4/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/4/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 2662 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/4/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 56 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1126 | trunk passed |
| +1 | compile | 58 | trunk passed |
| +1 | checkstyle | 43 | trunk passed |
| +1 | mvnsite | 71 | trunk passed |
| +1 | shadedclient | 764 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 52 | trunk passed |
| 0 | spotbugs | 162 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 160 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 63 | the patch passed |
| +1 | compile | 58 | the patch passed |
| +1 | javac | 58 | the patch passed |
| +1 | checkstyle | 40 | the patch passed |
| +1 | mvnsite | 62 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 693 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 47 | the patch passed |
| +1 | findbugs | 168 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 5005 | hadoop-hdfs in the patch failed. |
| -1 | asflicense | 32 | The patch generated 4 ASF License warnings. |
| | | 8543 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting |
|   | hadoop.hdfs.server.balancer.TestBalancer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-404/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/404 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 3a06fb134529 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e356e4f |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/5/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/5/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/5/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 4702 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/5/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 46 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1066 | trunk passed |
| +1 | compile | 54 | trunk passed |
| +1 | checkstyle | 39 | trunk passed |
| +1 | mvnsite | 59 | trunk passed |
| +1 | shadedclient | 720 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 45 | trunk passed |
| 0 | spotbugs | 165 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 162 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 71 | the patch passed |
| +1 | compile | 58 | the patch passed |
| +1 | javac | 58 | the patch passed |
| +1 | checkstyle | 38 | the patch passed |
| +1 | mvnsite | 57 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 678 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 43 | the patch passed |
| +1 | findbugs | 159 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 4933 | hadoop-hdfs in the patch failed. |
| -1 | asflicense | 29 | The patch generated 1 ASF License warnings. |
| | | 8311 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.TestReconstructStripedBlocks |
|   | hadoop.hdfs.tools.TestWebHDFSStoragePolicyCommands |
|   | hadoop.hdfs.server.namenode.TestFsck |
|   | hadoop.hdfs.TestLargeBlock |
|   | hadoop.hdfs.server.namenode.TestNameNodeMetadataConsistency |
|   | hadoop.hdfs.TestReadStripedFileWithDecodingCorruptData |
|   | hadoop.hdfs.TestReadStripedFileWithMissingBlocks |
|   | hadoop.hdfs.TestWriteReadStripedFile |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-404/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/404 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux f2c479c527aa 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 094d736 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/6/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/6/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/6/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 4198 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/6/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 40 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1078 | trunk passed |
| +1 | compile | 59 | trunk passed |
| +1 | checkstyle | 47 | trunk passed |
| +1 | mvnsite | 66 | trunk passed |
| +1 | shadedclient | 771 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 51 | trunk passed |
| 0 | spotbugs | 161 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 159 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 62 | the patch passed |
| +1 | compile | 58 | the patch passed |
| +1 | javac | 58 | the patch passed |
| +1 | checkstyle | 42 | the patch passed |
| +1 | mvnsite | 64 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 746 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 48 | the patch passed |
| +1 | findbugs | 170 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 4906 | hadoop-hdfs in the patch failed. |
| +1 | asflicense | 33 | The patch does not generate ASF License warnings. |
| | | 8455 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.blockmanagement.TestBlockTokenWithDFSStriped |
|   | hadoop.hdfs.qjournal.server.TestJournalNodeRespectsBindHostKeys |
|   | hadoop.hdfs.web.TestWebHDFS |
|   | hadoop.hdfs.qjournal.server.TestJournalNodeSync |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-404/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/404 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux e716c67b3d44 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 69ddb36 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/7/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/7/testReport/ |
| Max. process+thread count | 4032 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/7/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 92 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1287 | trunk passed |
| +1 | compile | 62 | trunk passed |
| +1 | checkstyle | 51 | trunk passed |
| +1 | mvnsite | 76 | trunk passed |
| +1 | shadedclient | 864 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 59 | trunk passed |
| 0 | spotbugs | 188 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 186 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 65 | the patch passed |
| +1 | compile | 58 | the patch passed |
| +1 | javac | 58 | the patch passed |
| +1 | checkstyle | 43 | the patch passed |
| +1 | mvnsite | 66 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 802 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 52 | the patch passed |
| +1 | findbugs | 184 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 6191 | hadoop-hdfs in the patch passed. |
| +1 | asflicense | 35 | The patch does not generate ASF License warnings. |
| | | 10217 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-404/8/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/404 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux f568cdd12a8d 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3329257 |
| Default Java | 1.8.0_222 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/8/testReport/ |
| Max. process+thread count | 2897 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/8/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by wilderchen** [comment]
Seems all tests haven been passed.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 10 | https://github.com/apache/hadoop/pull/404 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-404/9/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
