### PR TITLE
HADOOP-16672 : adding null check for ticket.doAs() while setting up I…

### PR DESCRIPTION
**Pull request by virajjasani**
…OStreams

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1188 | trunk passed |
| +1 | compile | 1097 | trunk passed |
| +1 | checkstyle | 50 | trunk passed |
| +1 | mvnsite | 85 | trunk passed |
| +1 | shadedclient | 1052 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 100 | trunk passed |
| 0 | spotbugs | 142 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 139 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 61 | the patch passed |
| +1 | compile | 1235 | the patch passed |
| +1 | javac | 1235 | the patch passed |
| +1 | checkstyle | 51 | the patch passed |
| +1 | mvnsite | 86 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 910 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 100 | the patch passed |
| +1 | findbugs | 150 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 599 | hadoop-common in the patch passed. |
| +1 | asflicense | 50 | The patch does not generate ASF License warnings. |
| | | 7097 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1681/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1681 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux d493ea4898b6 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 7be5508 |
| Default Java | 1.8.0_222 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1681/1/testReport/ |
| Max. process+thread count | 1509 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1681/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
Please review @xkrogen

**Comment by xkrogen** [comment]
Hi @virajjasani , thanks for the ping. I'm not really familiar with this area of the codebase. It seems like a sensible change, but I don't know if it's safe from a security perspective to skip that whole block if no `ticket` is found. Can you try to get input from someone else who has worked in this area?

**Comment by virajjasani** [comment]
Thanks @xkrogen 
Agree that entire block might not need to be skipped ideally but if ticket is not found, we will anyways encounter NPE which is not caught anywhere ultimately.

Sure, let me try if I can find someone who has contributed in this area.
Thanks

**Comment by jojochuang** [comment]
Do you know when the ticket is null? Can you post a stack trace so that it's easier to tell why. 
Looking at a few callers, the ticket is usually obtained via UGI#getCurrentUser() which never returns null.

To me the client should raise and exception and abort if the ticket is null when SASL is on. In any case the connection will fail (because of lack of SASL negotiation) so why not fail early.

**Comment by virajjasani** [comment]
@jojochuang we seem to have null check for ticket everywhere but here for this method hence I thought of adding it.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 33s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  21m  8s |  trunk passed  |
| +1 :green_heart: |  compile  |  20m 35s |  trunk passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  compile  |  17m 28s |  trunk passed with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09  |
| +1 :green_heart: |  checkstyle  |   0m 50s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 25s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  16m 25s |  branch has no errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 43s |  hadoop-common in trunk failed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.  |
| +1 :green_heart: |  javadoc  |   1m  2s |  trunk passed with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09  |
| +0 :ok: |  spotbugs  |   2m 18s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 14s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 51s |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 27s |  the patch passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  javac  |  19m 27s |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 10s |  the patch passed with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09  |
| +1 :green_heart: |  javac  |  18m 10s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 49s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 25s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  14m 25s |  patch has no errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 39s |  hadoop-common in the patch failed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.  |
| +1 :green_heart: |  javadoc  |   1m  3s |  the patch passed with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09  |
| +1 :green_heart: |  findbugs  |   2m 20s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   9m 50s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 47s |  The patch does not generate ASF License warnings.  |
|  |   | 154m  3s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-1681/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1681 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux b4fae28fda8e 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e756fe35909 |
| Default Java | Private Build-1.8.0_252-8u252-b09-1~18.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_252-8u252-b09-1~18.04-b09 |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-1681/3/artifact/out/branch-javadoc-hadoop-common-project_hadoop-common-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-1681/3/artifact/out/patch-javadoc-hadoop-common-project_hadoop-common-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-1681/3/testReport/ |
| Max. process+thread count | 1576 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-1681/3/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.0.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
