### PR TITLE
HADOOP-16610. Upgrade to yetus 0.11.0 and use emoji vote on github pre…

### PR DESCRIPTION
**Pull request by Apache9**
… commit

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |  34m 20s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :blue_heart: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| :green_heart: |  shadedclient  |  14m 41s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedclient  |  14m 37s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   |  66m  4s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1527/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1527 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux f5c5cd411896 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 606e341 |
| Max. process+thread count | 307 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1527/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ayushtkn** [comment]
IMO That +1 -1 are more descriptive and looks better as compared to this Hearts

**Comment by ayushtkn** [comment]
IMO That +1 -1 are more descriptive and looks better as compared to this Hearts

**Comment by steveloughran** [comment]
could we do emoji and text?

no app should use nothing but red and green to distinguish state as red/green colour blindness is actually the most common form of colour blindness. 

I do like the little hearts, but at the very least they'll need clear differentiating shapes as well as colours. 
⚠️❌⛔️...

**Comment by Apache9** [comment]
It has different shapes, this is the broken heart 💔 . 
Of course it is not very clear for color blindness, will file an issue for yetus, to use different shapes for different votes.
So the decision here is to just upgrade to yetus 0.11.0 and fix the wrong parameter(skip-dir ->skip-dirs), and wait for yetus 0.12.0?

**Comment by Apache9** [comment]
https://github.com/apache/yetus/pull/73

**Comment by steveloughran** [comment]
ok, go for it as is and then we can go with the later changes

+1

**Comment by Apache9** [comment]
So yetus 0.11.1 is out and now we keep the original +1/-1 in the vote table with emoji in different shapes.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 14s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  shadedclient  |  15m 18s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 10s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   |  34m  6s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1527/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1527 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 761b1fb864bf 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 42fc888 |
| Max. process+thread count | 367 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1527/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
+1

**Comment by ayushtkn** [comment]
Thanx Everyone Merging this!!!

**Pull request merged**
