### PR TITLE
HADOOP-16905. Update jackson-databind to 2.10.3 to relieve us from th…

### PR DESCRIPTION
**Pull request by aajisaka**
…e endless CVE patches. (#1876)

(cherry picked from commit 69faaa1d58ad7de18a8dfa477531653a2c061568)

 Conflicts:
	hadoop-project/pom.xml

### Description of PR

PR for testing by Jenkins. Backport HADOOP-16905 to branch-3.2. I'll backport HADOOP-17534 next.

### How was this patch tested?

Not tested.

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  11m 15s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 24s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  26m 17s |  |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |  15m 50s |  |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |   0m 53s |  |  branch-3.2 passed  |
| +1 :green_heart: |  javadoc  |   0m 48s |  |  branch-3.2 passed  |
| +1 :green_heart: |  shadedclient  |  61m 50s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 37s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 41s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  14m 53s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  14m 53s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 50s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  2s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 48s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  15m 31s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 23s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 23s |  |  hadoop-client-runtime in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 44s |  |  The patch does not generate ASF License warnings.  |
|  |   | 111m 21s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3748/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3748 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml |
| uname | Linux 96e20edbf7cc 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / d3e00a58556a535a0edb49fff7422a60da21f552 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3748/1/testReport/ |
| Max. process+thread count | 306 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-client-modules/hadoop-client-runtime U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3748/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
@brahmareddybattula Would you take a look?

**Comment by virajjasani** [comment]
Good to update some file in the top tree (outside of all modules) to trigger the full QA (e.g. adding a line etc)? Once full QA is done, we can revert that change.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   8m 10s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 41s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  23m 33s |  |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |  15m  9s |  |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |  15m 42s |  |  branch-3.2 passed  |
| +1 :green_heart: |  javadoc  |   6m 10s |  |  branch-3.2 passed  |
| +1 :green_heart: |  shadedclient  |  78m  2s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 49s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  22m 33s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  15m  4s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  15m  4s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  13m  1s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  4s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   5m 51s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  20m 35s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 237m 43s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3748/2/artifact/out/patch-unit-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m  2s |  |  The patch does not generate ASF License warnings.  |
|  |   | 398m 53s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestBlockStoragePolicy |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3748/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3748 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml |
| uname | Linux b5b5a9316c5c 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / 4aedade38a9061b7cd3c4476d5472b4520302678 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3748/2/testReport/ |
| Max. process+thread count | 2995 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-client-modules/hadoop-client-runtime . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3748/2/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
Thank you @virajjasani for your comment. Updated the pom.xml to run the full unit tests. This precommit job didn't run all the tests because there is a test failure in hadoo-hdfs module and stopped testing.

**Comment by aajisaka** [comment]
Filed HADOOP-18035 to run all the unit tests.

**Comment by virajjasani** [comment]
The changelist available as part of build#2 is:
```
1. Modify a file to trigger the full QA (details / githubweb)
2. Revert "Modify a file to trigger the full QA" (details / githubweb)
```
Hence, looks like revert commit was also part of the build and that's why full QA was not triggered (as per logs). Hopefully test failure in one module would not prevent full QA based on what I have seen in recent PRs but it's still strange that full QA was not triggered. Maybe because after applying revert commit, build did not recognize any changed on the main pom file.

@aajisaka would you like to keep new line change in hadoop-main pom file for a while (~24 hr)? Once we get full QA results, we can revert it. Sounds good?

**Comment by virajjasani** [comment]
For instance, two build results had multiple test failures (including hadoop-hdfs modules), still hadoop-yarn modules tests were executed (PR #3749). Let me dig-in bit more to understand this behaviour on the current PR.

**Comment by aajisaka** [comment]
@virajjasani

> Hence, looks like revert commit was also part of the build and that's why full QA was not triggered (as per logs).

It is not the reason why full QA was not triggered. I commented in HADOOP-18035 why the subsequent modules were not executed in branch-3.2 and branch-2.10.

**Comment by virajjasani** [comment]
I see, thanks @aajisaka

**Comment by aajisaka** [comment]
Now HADOOP-18040 is merged. Let me run the full QA again.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 41s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 43s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  24m 41s |  |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |  15m 52s |  |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |  16m 25s |  |  branch-3.2 passed  |
| +1 :green_heart: |  javadoc  |   6m 14s |  |  branch-3.2 passed  |
| +1 :green_heart: |  shadedclient  |  80m 50s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 50s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  22m 33s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  14m 59s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  14m 59s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  13m 36s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  4s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   6m 16s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  21m 10s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 647m 53s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3748/3/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| -1 :x: |  asflicense  |   1m 23s | [/results-asflicense.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3748/3/artifact/out/results-asflicense.txt) |  The patch generated 1 ASF License warnings.  |
|  |   | 805m 55s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestBlockStoragePolicy |
|   | hadoop.hdfs.server.namenode.ha.TestRetryCacheWithHA |
|   | hadoop.hdfs.server.datanode.TestBPOfferService |
|   | hadoop.yarn.sls.TestSLSRunner |
|   | hadoop.yarn.server.timelineservice.security.TestTimelineAuthFilterForV2 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3748/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3748 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml |
| uname | Linux 0bca3edce3d8 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / 4aedade38a9061b7cd3c4476d5472b4520302678 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3748/3/testReport/ |
| Max. process+thread count | 2489 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-client-modules/hadoop-client-runtime . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3748/3/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
If `TestSLSRunner` and `TestTimelineAuthFilterForV2` failures are not relevant, QA results look good IMHO.

**Comment by aajisaka** [comment]
Thanks. TestSLSRunner passed on my local. TestTimelineAuthFilterForV2 is always failing with and without the patch. I think it's okay to merge without binding +1 because this is a backport.

**Comment by virajjasani** [comment]
> TestSLSRunner passed on my local. TestTimelineAuthFilterForV2 is always failing with and without the patch.

Sounds good. Otherwise it looks good anyways. +1 (non-binding)

**Comment by aajisaka** [comment]
Merged. Thank you @virajjasani for your review!

**Pull request merged**
