### PR TITLE
HADOOP-17164. UGI loginUserFromKeytab doesn't set the last login time

### PR DESCRIPTION
**Pull request by sguggilam**
See #2178 for related change for Hadoop 3.x

### CODE REVIEW

**Comment by sguggilam** [comment]
@liuml07 Please review the PR for 2.10 branch

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  11m 14s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-2.10 Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 15s |  root in branch-2.10 failed.  |
| -1 :x: |  compile  |   0m 14s |  root in branch-2.10 failed.  |
| -0 :warning: |  checkstyle  |   0m 12s |  The patch fails to run checkstyle in hadoop-common  |
| -1 :x: |  mvnsite  |   0m 13s |  hadoop-common in branch-2.10 failed.  |
| -1 :x: |  javadoc  |   0m 13s |  hadoop-common in branch-2.10 failed.  |
| +0 :ok: |  spotbugs  |   0m 55s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| -1 :x: |  findbugs  |   0m 13s |  hadoop-common in branch-2.10 failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 12s |  hadoop-common in the patch failed.  |
| -1 :x: |  compile  |   0m 14s |  root in the patch failed.  |
| -1 :x: |  javac  |   0m 14s |  root in the patch failed.  |
| -0 :warning: |  checkstyle  |   0m 12s |  The patch fails to run checkstyle in hadoop-common  |
| -1 :x: |  mvnsite  |   0m 12s |  hadoop-common in the patch failed.  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| -1 :x: |  javadoc  |   0m 13s |  hadoop-common in the patch failed.  |
| -1 :x: |  findbugs  |   0m 12s |  hadoop-common in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 12s |  hadoop-common in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 27s |  The patch does not generate ASF License warnings.  |
|  |   |  16m 56s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2194 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux a1818f25ba1a 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | branch-2.10 / c84ae8f |
| Default Java | Oracle Corporation-1.7.0_95-b00 |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/branch-compile-root.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/buildtool-branch-checkstyle-hadoop-common-project_hadoop-common.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/branch-mvnsite-hadoop-common-project_hadoop-common.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/branch-javadoc-hadoop-common-project_hadoop-common.txt |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/branch-findbugs-hadoop-common-project_hadoop-common.txt |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/patch-mvninstall-hadoop-common-project_hadoop-common.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/patch-compile-root.txt |
| javac | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/patch-compile-root.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/buildtool-patch-checkstyle-hadoop-common-project_hadoop-common.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/patch-mvnsite-hadoop-common-project_hadoop-common.txt |
| whitespace | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/whitespace-eol.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/patch-javadoc-hadoop-common-project_hadoop-common.txt |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/patch-findbugs-hadoop-common-project_hadoop-common.txt |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/testReport/ |
| Max. process+thread count | 37 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by liuml07** [comment]
@sguggilam I'm not sure if this is because the QA fails on GitHub only, or it fails in JIRA as well. Do you mind uploading the patch to JIRA? The patch file name will be `HADOOP-17164-branch-2.10.000.patch` or something alike.

**Comment by sguggilam** [comment]
@liuml07  Uploaded the patch to JIRA , shall keep an eye on the QA run

**Comment by liuml07** [comment]
@sguggilam Could you merge/rebase from `branch-2.10` and push again? I think #2195 should have fixed this.

**Comment by sguggilam** [comment]
@liuml07 Rebased and pushed the latest code. Also uploaded the patch to JIRA for the QA run

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 11s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-2.10 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  16m 25s |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |  13m 11s |  branch-2.10 passed  |
| +1 :green_heart: |  checkstyle  |   0m 41s |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |   1m 30s |  branch-2.10 passed  |
| +1 :green_heart: |  javadoc  |   1m 27s |  branch-2.10 passed  |
| +0 :ok: |  spotbugs  |   3m 33s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m 28s |  branch-2.10 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 13s |  the patch passed  |
| +1 :green_heart: |  compile  |  14m 46s |  the patch passed  |
| +1 :green_heart: |  javac  |  14m 46s |  the patch passed  |
| -0 :warning: |  checkstyle  |   0m 35s |  hadoop-common-project/hadoop-common: The patch generated 1 new + 95 unchanged - 0 fixed = 96 total (was 95)  |
| +1 :green_heart: |  mvnsite  |   1m 22s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   1m 21s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   3m 11s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  11m 48s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 58s |  The patch does not generate ASF License warnings.  |
|  |   |  77m  8s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2194 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 38d7253d5bf0 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | branch-2.10 / 8d5821b |
| Default Java | Oracle Corporation-1.7.0_95-b00 |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/2/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/2/testReport/ |
| Max. process+thread count | 1568 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 43s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-2.10 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  20m 24s |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |  16m 41s |  branch-2.10 passed  |
| +1 :green_heart: |  checkstyle  |   0m 48s |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |   1m 49s |  branch-2.10 passed  |
| +1 :green_heart: |  javadoc  |   1m 29s |  branch-2.10 passed  |
| +0 :ok: |  spotbugs  |   3m 15s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m 11s |  branch-2.10 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 11s |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 36s |  the patch passed  |
| +1 :green_heart: |  javac  |  16m 36s |  the patch passed  |
| -0 :warning: |  checkstyle  |   0m 50s |  hadoop-common-project/hadoop-common: The patch generated 1 new + 95 unchanged - 0 fixed = 96 total (was 95)  |
| +1 :green_heart: |  mvnsite  |   1m 56s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   1m 29s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   3m 35s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  11m 48s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  0s |  The patch does not generate ASF License warnings.  |
|  |   |  87m 45s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2194 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 6cc565a20bee 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | branch-2.10 / 8d5821b |
| Default Java | Oracle Corporation-1.7.0_95-b00 |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/3/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/3/testReport/ |
| Max. process+thread count | 1352 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2194/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
