### PR TITLE
HDFS-15639. [JDK 11] Fix Javadoc errors in hadoop-hdfs-client.

### PR DESCRIPTION
**Pull request by tasanuma**
## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by aajisaka** [comment]
+1 pending Jenkins. Thanks.

**Comment by hemanthboyina** [comment]
+1 , will wait for jenkins result

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  3s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   6m  3s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  27m 22s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  21m 25s |  |  trunk passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  compile  |  17m 58s |  |  trunk passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +1 :green_heart: |  checkstyle  |   2m 49s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 29s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  22m 20s |  |  branch has no errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 44s | [/branch-javadoc-hadoop-hdfs-project_hadoop-hdfs-client-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2394/1/artifact/out/branch-javadoc-hadoop-hdfs-project_hadoop-hdfs-client-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.txt) |  hadoop-hdfs-client in trunk failed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.  |
| +1 :green_heart: |  javadoc  |   2m  7s |  |  trunk passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +0 :ok: |  spotbugs  |   2m 38s |  |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   4m 53s |  |  trunk passed  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 22s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 41s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  20m 41s |  |  the patch passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  javac  |  20m 41s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m  6s |  |  the patch passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +1 :green_heart: |  javac  |  18m  6s |  |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m 48s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m 25s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  16m 29s |  |  patch has no errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 44s | [/diff-javadoc-javadoc-hadoop-hdfs-project_hadoop-hdfs-client-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2394/1/artifact/out/diff-javadoc-javadoc-hadoop-hdfs-project_hadoop-hdfs-client-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.txt) |  hadoop-hdfs-project_hadoop-hdfs-client-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1 with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1 generated 99 new + 0 unchanged - 101 fixed = 99 total (was 101)  |
| +1 :green_heart: |  javadoc  |   2m  7s |  |  the patch passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +1 :green_heart: |  findbugs  |   5m  7s |  |  the patch passed  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   9m 54s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 23s |  |  hadoop-hdfs-client in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 46s |  |  The patch does not generate ASF License warnings.  |
|  |   | 193m 13s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2394/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2394 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 2cecdf09df09 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 4c651103f2a |
| Default Java | Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2394/1/testReport/ |
| Max. process+thread count | 2245 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs-client U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2394/1/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.1.3 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by tasanuma** [comment]
@aajisaka @hemanthboyina Thanks for your reviews.

The result of javadoc build failed, but it doesn't seem to include this PR change. Can we merge it?

**Comment by hemanthboyina** [comment]
HDFS-15567 caused a java doc error in Hdfs.java:162 , so can we fix this as part of this jira ?

**Comment by aajisaka** [comment]
+1

> [/branch-javadoc-hadoop-hdfs-project_hadoop-hdfs-client-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2394/1/artifact/out/branch-javadoc-hadoop-hdfs-project_hadoop-hdfs-client-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.txt)

```
[ERROR] /home/jenkins/jenkins-home/workspace/hadoop-multibranch_PR-2394/src/hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/fs/Hdfs.java:159: error: self-closing element not allowed
[ERROR]    * <p/>In HA the client synchronizes its state with the Active NameNode
[ERROR]      ^
[ERROR] /home/jenkins/jenkins-home/workspace/hadoop-multibranch_PR-2394/src/hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java:1772: error: self-closing element not allowed
[ERROR]    * <p/>In HA the client synchronizes its state with the Active NameNode
[ERROR]      ^
```
The above output is before applying the patch. Therefore the errors are expected.

javadoc succeeded after applying the patch: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2394/1/artifact/out/patch-javadoc-hadoop-hdfs-project_hadoop-hdfs-client-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.txt

**Review by aajisaka — APPROVED** [review]

**Comment by tasanuma** [comment]
Thanks for your reviews, @aajisaka and @hemanthboyina!

**Pull request merged**
