### PR TITLE
HADOOP-17341. Upgrade commons-codec to 1.15

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to upgrade `commons-codec` to 1.15. 
- https://commons.apache.org/proper/commons-codec/changes-report.html#a1.15

### CODE REVIEW

**Review by jojochuang — COMMENTED** [review]
Looks good. Do you have a target version in mind?

**Comment by dongjoon-hyun** [comment]
Thank you, @jojochuang . Since the previous one, [HADOOP-17033](https://issues.apache.org/jira/browse/HADOOP-17033) , has a target version `3.4.0` and is not released yet, can we have this at `3.4.0`?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  5s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  36m  6s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   0m 16s |  |  trunk passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  compile  |   0m 16s |  |  trunk passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  mvnsite  |   0m 20s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  54m  3s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 19s |  |  trunk passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javadoc  |   0m 19s |  |  trunk passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 11s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 11s |  |  the patch passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javac  |   0m 11s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 11s |  |  the patch passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  javac  |   0m 11s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 13s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  16m 20s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  |  the patch passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javadoc  |   0m 14s |  |  the patch passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 13s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 29s |  |  The patch does not generate ASF License warnings.  |
|  |   |  76m 43s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2428/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2428 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 5d2e55d75333 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 0461a07c018 |
| Default Java | Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2428/1/testReport/ |
| Max. process+thread count | 308 (vs. ulimit of 5500) |
| modules | C: hadoop-project U: hadoop-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2428/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by dongjoon-hyun** [comment]
Could you review this too, @sunchao ?

**Review by sunchao — APPROVED** [review]
LGTM. Thanks @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you, @sunchao !

**Comment by dongjoon-hyun** [comment]
Gentle ping, @sunchao and @jojochuang ~

**Comment by jojochuang** [comment]
Done. Thanks both!

**Comment by dongjoon-hyun** [comment]
Thank you so much!

**Pull request merged**
