### PR TITLE
HADOOP-18488. Cherrypick HADOOP-11245 to branch-3.3

### PR DESCRIPTION
**Pull request by hotcodemacha**
### Description of PR

Cherrypick HADOOP-11245 to branch-3.3 - f41a368c146ab5ebea770017621256d3ff526046

JIRA - HADOOP-18488

### For code changes:

- [X] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Review by jojochuang — COMMENTED** [review]
this is a clean cherrypick. +1 pending Jenkins.

**Review by jojochuang — APPROVED** [review]

**Comment by hotcodemacha** [comment]
Thanks @jojochuang

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  11m 33s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 5 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 54s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  26m 47s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  19m  1s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m 12s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   1m 46s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   1m 41s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   2m 22s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  26m 27s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 52s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 18s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  18m 18s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   3m  6s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4997/1/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 19 new + 139 unchanged - 7 fixed = 158 total (was 146)  |
| +1 :green_heart: |  mvnsite  |   1m 42s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 35s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   2m 34s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  26m 50s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m  6s |  |  hadoop-nfs in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 13s |  |  hadoop-hdfs-nfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  8s |  |  The patch does not generate ASF License warnings.  |
|  |   | 173m 18s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4997/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4997 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint spotbugs checkstyle |
| uname | Linux 9988f816889d 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 55d9acf94dd6c5d06821dd98fae7fe19a3281fd7 |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4997/1/testReport/ |
| Max. process+thread count | 523 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-nfs hadoop-hdfs-project/hadoop-hdfs-nfs U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4997/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
Thanks Merged. Checkstyle is unrelated.

**Pull request merged**
