### PR TITLE
YARN-10472. [branch-3.2] Backport YARN-10314. YarnClient throws NoClassDefFoundError for WebSocketException with only shaded client jars

### PR DESCRIPTION
**Pull request by smengcl**
https://issues.apache.org/jira/browse/YARN-10314

This PR aims to backport YARN-10314 to branch-3.2.

### CODE REVIEW

**Review by jojochuang — COMMENTED** [review]
Thanks for doing this. Can you also run 'mvn verify' to make sure minicluster runs with this change?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  17m  5s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 17s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  23m 50s |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |   0m 19s |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |   0m 41s |  branch-3.2 passed  |
| +1 :green_heart: |  shadedclient  |  40m 22s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 39s |  branch-3.2 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   7m 19s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 30s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  3s |  The patch has no ill-formed XML file.  |
| -1 :x: |  shadedclient  |  15m 53s |  patch has errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 49s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 16s |  hadoop-client-runtime in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 16s |  hadoop-client-minicluster in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   |  86m 45s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2412/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2412 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux e3c7f4bc0691 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / 87666e2 |
| Default Java | Private Build-1.8.0_265-8u265-b01-0ubuntu2~16.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2412/1/testReport/ |
| Max. process+thread count | 411 (vs. ulimit of 5500) |
| modules | C: hadoop-client-modules/hadoop-client-runtime hadoop-client-modules/hadoop-client-minicluster U: hadoop-client-modules |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2412/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by jojochuang — CHANGES_REQUESTED** [review]
There's shading error, please take a look.

**Comment by smengcl** [comment]
> Thanks for doing this. Can you also run 'mvn verify' to make sure minicluster runs with this change?

I left `mvn verify` running on a CentOS 6 rig. But hit some seemingly unrelated failures in `Hadoop Common`:

```
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestRawLocalFileSystemContract.testMTimeAtime:188 expected:<1603822297817> but was:<1603822297000>
[ERROR] Errors:
[ERROR]   TestIPC.testAuxiliaryPorts:367 » Bind Problem binding to [0.0.0.0:9000] java.n...
```

btw did you run only `Apache Hadoop Mini-Cluster`?

**Comment by smengcl** [comment]
> There's shading error, please take a look.

Yes. We have another `NoClassDefFoundError`. This time it is `org/apache/hadoop/shaded/org/eclipse/jetty/http/HttpField`.

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.example.ITUseMiniCluster
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 3.502 s <<< FAILURE! - in org.apache.hadoop.example.ITUseMiniCluster
[ERROR] useWebHDFS(org.apache.hadoop.example.ITUseMiniCluster)  Time elapsed: 2.767 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/hadoop/shaded/org/eclipse/jetty/http/HttpField
	at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:561)
	at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:117)
...
```
```
[ERROR] useHdfsFileSystem(org.apache.hadoop.example.ITUseMiniCluster)  Time elapsed: 0.627 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/hadoop/shaded/org/eclipse/jetty/http/HttpField
	at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:561)
	at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:117)
	at org.apache.hadoop.http.HttpServer2$Builder.build(HttpServer2.java:448)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeHttpServer.start(NameNodeHttpServer.java:165)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.startHttpServer(NameNode.java:909)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:731)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:977)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:950)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1716)
	at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNode(MiniDFSCluster.java:1337)
```

**Comment by smengcl** [comment]
I ran `mvn verify -pl :hadoop-client-minicluster` on the latest commit. It passed

```
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing /home/systest/verify/YARN-10314-branch-3.2/hadoop-client-modules/hadoop-client-minicluster/target/hadoop-client-minicluster-3.2.3-SNAPSHOT.jar with /home/systest
/verify/YARN-10314-branch-3.2/hadoop-client-modules/hadoop-client-minicluster/target/hadoop-client-minicluster-3.2.3-SNAPSHOT-shaded.jar
[INFO] Dependency-reduced POM written at: /home/systest/verify/YARN-10314-branch-3.2/hadoop-client-modules/hadoop-client-minicluster/dependency-reduced-pom.xml
[INFO]
[INFO] --- license-maven-plugin:1.10:update-file-header (update-pom-license) @ hadoop-client-minicluster ---
[INFO] Will search files to update from root /home/systest/verify/YARN-10314-branch-3.2/hadoop-client-modules/hadoop-client-minicluster
[INFO] Scan 1 file header done in 20.565ms.
[INFO]
 * add header on 1 file.
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.16:check (signature-check) @ hadoop-client-minicluster ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java18:1.0
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (depcheck) @ hadoop-client-minicluster ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:28 min
[INFO] Finished at: 2020-10-28T23:48:53-07:00
[INFO] ------------------------------------------------------------------------
```

Pending CI.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  16m 43s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 16s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  24m 23s |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |   0m 21s |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |   0m 44s |  branch-3.2 passed  |
| +1 :green_heart: |  shadedclient  |  41m 52s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 40s |  branch-3.2 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 22s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 33s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 30s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  3s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  13m 20s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 34s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 17s |  hadoop-client-runtime in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 16s |  hadoop-client-minicluster in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 31s |  The patch does not generate ASF License warnings.  |
|  |   |  83m 18s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2412/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2412 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 3c72a683739b 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / 14a4606 |
| Default Java | Private Build-1.8.0_272-8u272-b10-0ubuntu1~16.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2412/2/testReport/ |
| Max. process+thread count | 426 (vs. ulimit of 5500) |
| modules | C: hadoop-client-modules/hadoop-client-runtime hadoop-client-modules/hadoop-client-minicluster U: hadoop-client-modules |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2412/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by smengcl** [comment]
CI shadedclient also passed. Please kindly take another look @jojochuang at the patch.

**Review by jojochuang — APPROVED** [review]

**Comment by smengcl** [comment]
Thanks @jojochuang for reviewing. Will merge this shortly.

**Pull request merged**
