### PR TITLE
HADOOP-16910: ABFS Streams to update FileSystem.Statistics counters on IO.

### PR DESCRIPTION
**Pull request by mehakmeet**
Contributed by Mehakmeet Singh

## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by mehakmeet** [comment]
test run : mvn -T 1C -Dparallel-tests=abfs clean verify
Region : East US, West US

related to previous PR #1881

**Comment by mehakmeet** [comment]
Full test results(error is container based) :
```
[INFO] Results:
[INFO]
[INFO] Tests run: 52, Failures: 0, Errors: 0, Skipped: 0
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ITestGetNameSpaceEnabled.testFailedRequestWhenCredentialsNotCorrect:91->AbstractAbfsIntegrationTest.getFileSystem:229 » InvalidConfigurationValue
[INFO]
[ERROR] Tests run: 416, Failures: 0, Errors: 1, Skipped: 62
[INFO] Results:
[INFO]
[WARNING] Tests run: 206, Failures: 0, Errors: 0, Skipped: 29

**Comment by mukund-thakur** [comment]
Amend the commit and put jira Id.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  25m 21s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 3 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  19m  7s |  trunk passed  |
| +1 :green_heart: |  compile  |   0m 32s |  trunk passed  |
| +1 :green_heart: |  checkstyle  |   0m 25s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 34s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  15m  5s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 27s |  trunk passed  |
| +0 :ok: |  spotbugs  |   0m 51s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   0m 50s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 28s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 24s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 24s |  the patch passed  |
| -0 :warning: |  checkstyle  |   0m 16s |  hadoop-tools/hadoop-azure: The patch generated 2 new + 1 unchanged - 0 fixed = 3 total (was 1)  |
| +1 :green_heart: |  mvnsite  |   0m 27s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  13m 38s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 23s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   0m 53s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 25s |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   |  82m 23s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1918/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1918 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 60dc896cabb0 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / cbe71ea |
| Default Java | 1.8.0_242 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1918/1/artifact/out/diff-checkstyle-hadoop-tools_hadoop-azure.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1918/1/testReport/ |
| Max. process+thread count | 414 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-azure U: hadoop-tools/hadoop-azure |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1918/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 47s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 3 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  21m 30s |  trunk passed  |
| +1 :green_heart: |  compile  |   0m 28s |  trunk passed  |
| +1 :green_heart: |  checkstyle  |   0m 20s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 30s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  16m 14s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 22s |  trunk passed  |
| +0 :ok: |  spotbugs  |   0m 50s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   0m 47s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 27s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 21s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 21s |  the patch passed  |
| -0 :warning: |  checkstyle  |   0m 15s |  hadoop-tools/hadoop-azure: The patch generated 2 new + 1 unchanged - 0 fixed = 3 total (was 1)  |
| +1 :green_heart: |  mvnsite  |   0m 25s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 35s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 19s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   0m 54s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 22s |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 28s |  The patch does not generate ASF License warnings.  |
|  |   |  63m 38s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1918/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1918 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 5101f156126f 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / cbe71ea |
| Default Java | 1.8.0_242 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1918/2/artifact/out/diff-checkstyle-hadoop-tools_hadoop-azure.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1918/2/testReport/ |
| Max. process+thread count | 309 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-azure U: hadoop-tools/hadoop-azure |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1918/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 10s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 3 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  21m 28s |  trunk passed  |
| +1 :green_heart: |  compile  |   0m 29s |  trunk passed  |
| +1 :green_heart: |  checkstyle  |   0m 19s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 30s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  17m  7s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 23s |  trunk passed  |
| +0 :ok: |  spotbugs  |   0m 59s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   0m 56s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 30s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 23s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 23s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 14s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 27s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 13s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 21s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   0m 55s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 21s |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 28s |  The patch does not generate ASF License warnings.  |
|  |   |  63m 48s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1918/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1918 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 30c2b98812c4 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / cbe71ea |
| Default Java | 1.8.0_242 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1918/3/testReport/ |
| Max. process+thread count | 311 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-azure U: hadoop-tools/hadoop-azure |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1918/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by bgaborg** [comment]
+1 from @steveloughran on https://github.com/apache/hadoop/pull/1881, and the compile error is fixed now.
Merging.

**Comment by steveloughran** [comment]
thanks

**Comment by amarnathkarthik** [comment]
@mehakmeet Integration test fails when running against ABS East US.

**Command:** `mvn -T 1C -Dparallel-tests=abfs clean verify`

`[INFO] Tests run: 63, Failures: 0, Errors: 0, Skipped: 0`
```
[ERROR] Failures: 
[ERROR]   ITestAbfsStreamStatistics.testAbfsStreamOps:92->assertReadWriteOps:154->Assert.assertEquals:645->Assert.failNotEquals:834->Assert.fail:88 Mismatch in read operations expected:<2> but was:<3>
**[ERROR] Tests run: 424, Failures: 1, Errors: 0, Skipped: 267**
```

`[WARNING] Tests run: 206, Failures: 0, Errors: 0, Skipped: 29`

CC: @steveloughran

**Comment by mehakmeet** [comment]
@amarnathkarthik it fails when you run it alone too ?
```
mvn -T 1C -Dparallel-tests=abfs clean verify -Dtest=none -Dit.test=ITestAbfsStreamStatistics
```
Never failed for me, Either way I'll look into it. Thank you.

**Comment by steveloughran** [comment]
this sounds intermittent or configuration related

**Comment by mehakmeet** [comment]
stack trace for the error:
```
2020-04-28 15:49:04,106 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:execute(133)) - First execution of REST operation - GetAcl
2020-04-28 15:49:04,151 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(175)) - Signing request with shared key
2020-04-28 15:49:08,430 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(223)) - HttpRequest: 404,,cid=1a653b2f-8796-4c5d-ab72-f04bb1296d08,rid=8026b894-a01f-005a-6846-1d2ad8000000,sent=0,recv=0,HEAD,https://mehakmeetdata.dfs.core.windows.net/abfs-testcontainer-ce1153dd-6c16-402b-91c8-099051333a12//?upn=false&action=getAccessControl&timeout=90
2020-04-28 15:49:08,446 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:execute(133)) - First execution of REST operation - CreateFileSystem
2020-04-28 15:49:08,446 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(175)) - Signing request with shared key
2020-04-28 15:49:08,752 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(223)) - HttpRequest: 201,,cid=494b1081-ddfc-4f7f-8b58-ff93ef1e1813,rid=8026b896-a01f-005a-6a46-1d2ad8000000,sent=0,recv=0,PUT,https://mehakmeetdata.dfs.core.windows.net/abfs-testcontainer-ce1153dd-6c16-402b-91c8-099051333a12?resource=filesystem
2020-04-28 15:49:08,774 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:execute(133)) - First execution of REST operation - GetAcl
2020-04-28 15:49:08,775 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(175)) - Signing request with shared key
2020-04-28 15:49:09,019 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(223)) - HttpRequest: 200,,cid=8b51c94e-53d6-4bf9-95ae-a220452926d3,rid=8026b8a9-a01f-005a-7d46-1d2ad8000000,sent=0,recv=0,HEAD,https://mehakmeetdata.dfs.core.windows.net/abfs-testcontainer-ce1153dd-6c16-402b-91c8-099051333a12//?upn=false&action=getAccessControl&timeout=90
2020-04-28 15:49:09,020 INFO  [JUnit-testAbfsStreamOps]: azurebfs.AbstractAbfsTestWithTimeout (AbstractAbfsTestWithTimeout.java:describe(88)) - 

testAbfsStreamOps: Test to see correct population of read and write operations in Abfs

2020-04-28 15:49:09,035 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:execute(133)) - First execution of REST operation - CreatePath
2020-04-28 15:49:09,035 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(175)) - Signing request with shared key
2020-04-28 15:49:09,300 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(223)) - HttpRequest: 201,,cid=eb705c96-722d-4775-9100-161c64f11145,rid=8026b8be-a01f-005a-1246-1d2ad8000000,sent=0,recv=0,PUT,https://mehakmeetdata.dfs.core.windows.net/abfs-testcontainer-ce1153dd-6c16-402b-91c8-099051333a12/user/mehakmeet.singh/testOneReadWriteOps?resource=file&timeout=90
2020-04-28 15:49:09,319 DEBUG [pool-2-thread-1]: services.AbfsClient (AbfsRestOperation.java:execute(133)) - First execution of REST operation - Append
2020-04-28 15:49:09,319 DEBUG [pool-2-thread-1]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(175)) - Signing request with shared key
2020-04-28 15:49:09,565 DEBUG [pool-2-thread-1]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(223)) - HttpRequest: 202,,cid=b7680b95-e3d0-42dd-9a2f-2fe33652d4ba,rid=8026b8c8-a01f-005a-1c46-1d2ad8000000,sent=9,recv=0,PUT,https://mehakmeetdata.dfs.core.windows.net/abfs-testcontainer-ce1153dd-6c16-402b-91c8-099051333a12/user/mehakmeet.singh/testOneReadWriteOps?action=append&position=0&timeout=90
2020-04-28 15:49:09,571 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:execute(133)) - First execution of REST operation - Flush
2020-04-28 15:49:09,571 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(175)) - Signing request with shared key
2020-04-28 15:49:09,825 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(223)) - HttpRequest: 200,,cid=e8dad7d3-4f4a-4b87-90a4-81ced45fa71b,rid=8026b8d9-a01f-005a-2c46-1d2ad8000000,sent=0,recv=0,PUT,https://mehakmeetdata.dfs.core.windows.net/abfs-testcontainer-ce1153dd-6c16-402b-91c8-099051333a12/user/mehakmeet.singh/testOneReadWriteOps?action=flush&retainUncommittedData=false&position=9&close=false&timeout=90
2020-04-28 15:49:09,826 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:execute(133)) - First execution of REST operation - GetPathStatus
2020-04-28 15:49:09,827 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(175)) - Signing request with shared key
2020-04-28 15:49:10,573 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(223)) - HttpRequest: 200,,cid=f0b7fda3-ae2a-4a74-811c-4d7647f773a6,rid=8026b8e9-a01f-005a-3c46-1d2ad8000000,sent=0,recv=0,HEAD,https://mehakmeetdata.dfs.core.windows.net/abfs-testcontainer-ce1153dd-6c16-402b-91c8-099051333a12/user/mehakmeet.singh/testOneReadWriteOps?upn=false&timeout=90
2020-04-28 15:49:10,644 DEBUG [ABFS-prefetch-4]: services.AbfsClient (AbfsRestOperation.java:execute(133)) - First execution of REST operation - ReadFile
2020-04-28 15:49:10,646 DEBUG [ABFS-prefetch-4]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(175)) - Signing request with shared key
2020-04-28 15:49:11,389 DEBUG [ABFS-prefetch-4]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(223)) - HttpRequest: 206,,cid=fe0d1b0b-3f46-41fd-8611-5f8fa7c75564,rid=8026b8f0-a01f-005a-4346-1d2ad8000000,sent=0,recv=9,GET,https://mehakmeetdata.dfs.core.windows.net/abfs-testcontainer-ce1153dd-6c16-402b-91c8-099051333a12/user/mehakmeet.singh/testOneReadWriteOps?timeout=90
2020-04-28 15:49:11,389 INFO  [JUnit-testAbfsStreamOps]: azurebfs.ITestAbfsStreamStatistics (ITestAbfsStreamStatistics.java:testAbfsStreamOps(85)) - Result of Read operation : 9
2020-04-28 15:49:11,389 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:execute(133)) - First execution of REST operation - Flush
2020-04-28 15:49:11,390 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(175)) - Signing request with shared key
2020-04-28 15:49:12,132 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(223)) - HttpRequest: 200,,cid=cb07f1b1-6067-4547-8fce-e5b18d8c8ef7,rid=8026b8fc-a01f-005a-4f46-1d2ad8000000,sent=0,recv=0,PUT,https://mehakmeetdata.dfs.core.windows.net/abfs-testcontainer-ce1153dd-6c16-402b-91c8-099051333a12/user/mehakmeet.singh/testOneReadWriteOps?action=flush&retainUncommittedData=false&position=9&close=true&timeout=90
2020-04-28 15:49:12,134 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:execute(133)) - First execution of REST operation - DeleteFileSystem
2020-04-28 15:49:12,134 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(175)) - Signing request with shared key
2020-04-28 15:49:13,179 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(223)) - HttpRequest: 202,,cid=f8fb143a-f007-4d1e-9fe1-b74ed981bbb8,rid=8026b948-a01f-005a-1b46-1d2ad8000000,sent=0,recv=0,DELETE,https://mehakmeetdata.dfs.core.windows.net/abfs-testcontainer-ce1153dd-6c16-402b-91c8-099051333a12?resource=filesystem&timeout=90
2020-04-28 15:49:13,196 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:execute(133)) - First execution of REST operation - GetFileSystemProperties
2020-04-28 15:49:13,197 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(175)) - Signing request with shared key
2020-04-28 15:49:13,439 DEBUG [JUnit-testAbfsStreamOps]: services.AbfsClient (AbfsRestOperation.java:executeHttpOperation(223)) - HttpRequest: 404,,cid=0b9689d7-970f-4817-b153-54d906ee5d64,rid=8026b95c-a01f-005a-2f46-1d2ad8000000,sent=0,recv=0,HEAD,https://mehakmeetdata.dfs.core.windows.net/abfs-testcontainer-ce1153dd-6c16-402b-91c8-099051333a12?resource=filesystem&timeout=90

java.lang.AssertionError: Mismatch in read operations 
Expected :2
Actual   :3
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.apache.hadoop.fs.azurebfs.ITestAbfsStreamStatistics.assertReadWriteOps(ITestAbfsStreamStatistics.java:154)
	at org.apache.hadoop.fs.azurebfs.ITestAbfsStreamStatistics.testAbfsStreamOps(ITestAbfsStreamStatistics.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
http 404 error seems interesting here.

**Comment by amarnathkarthik** [comment]
Standalone and parallel fails with same error. Also i'd try to run at least multiple (10) times and failed every single time.

`mvn -T 1C -Dparallel-tests=abfs clean verify -Dtest=none -Dit.test=ITestAbfsStreamStatistics`

**Stack trace:**
```[INFO] Running org.apache.hadoop.fs.azurebfs.ITestAbfsStreamStatistics
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.261 s <<< FAILURE! - in org.apache.hadoop.fs.azurebfs.ITestAbfsStreamStatistics
[ERROR] testAbfsStreamOps(org.apache.hadoop.fs.azurebfs.ITestAbfsStreamStatistics)  Time elapsed: 2.003 s  <<< FAILURE!
java.lang.AssertionError: Mismatch in read operations expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.apache.hadoop.fs.azurebfs.ITestAbfsStreamStatistics.assertReadWriteOps(ITestAbfsStreamStatistics.java:154)
	at org.apache.hadoop.fs.azurebfs.ITestAbfsStreamStatistics.testAbfsStreamOps(ITestAbfsStreamStatistics.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mehakmeet** [comment]
Ok, that is not the case with my configurations maybe. I am getting random fails and the test failed like 1/20 times for me.
It doesn't break consecutively this much for me. 
Test result for a test I ran just now:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.fs.azurebfs.ITestAbfsStreamStatistics
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 469.869 s - in org.apache.hadoop.fs.azurebfs.ITestAbfsStreamStatistics
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
```
I have opened up this Jira regarding this issue.
https://issues.apache.org/jira/browse/HADOOP-17018

I'll try to get the PR up for this issue and get it merged as soon as possible. Thank you.

**Comment by mehakmeet** [comment]
@amarnathkarthik Can you tell me if you've changed any specific configurations and then run the tests or maybe share what you are using in your auth-keys.xml to run the tests? 
Just want to pin-point why all your tests are failing because they are not failing for me.

**Comment by mehakmeet** [comment]
PR #1990 has been opened regarding this and contains the reasoning of intermittent test failures.

**Comment by amarnathkarthik** [comment]
> @amarnathkarthik Can you tell me if you've changed any specific configurations and then run the tests or maybe share what you are using in your auth-keys.xml to run the tests?
> Just want to pin-point why all your tests are failing because they are not failing for me.

@mehakmeet There is no custom configuration change on storage side, i'd run with both with hierarchical namespace enabled and disabled. Let me know if you need further details.

**Pull request merged**
