### PR TITLE
HADOOP-10225

### PR DESCRIPTION
**Pull request by lewismc**
Hi Folks,
This PR is an attempt to address https://issues.apache.org/jira/browse/HADOOP-10225.
The patch can be tested by running

```
mvn release:clean release:prepare -DautoVersionSubmodules=true -DdryRun=true
```

Please let me know once it has been tested and I can squash commits into one.

### CODE REVIEW

**Comment by lewismc** [comment]
@umbrant CC

**Comment by lewismc** [comment]
Just squashed all the commits so it is much cleaner.

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by lewismc** [comment]
Wow this is a blast. I'm not sure how Hadoop is even released anymore. HADOOP-10225 is still open and unresolved. It might just be best to close this ticket... I am disappointed that no-one else on the committer team thought publishing javadoc and sources with the release was important... oh well.

**Pull request closed without merging**
