### PR TITLE
HADOOP-16336. finish variable is unused in ZStandardCompressor

### PR DESCRIPTION
**Pull request by cxorm**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 51 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1410 | trunk passed |
| +1 | compile | 1533 | trunk passed |
| +1 | checkstyle | 57 | trunk passed |
| +1 | mvnsite | 95 | trunk passed |
| +1 | shadedclient | 982 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 67 | trunk passed |
| 0 | spotbugs | 165 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 162 | trunk passed |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 39 | hadoop-common in the patch failed. |
| -1 | compile | 61 | root in the patch failed. |
| -1 | javac | 61 | root in the patch failed. |
| +1 | checkstyle | 37 | the patch passed |
| -1 | mvnsite | 36 | hadoop-common in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| -1 | shadedclient | 40 | patch has errors when building and testing our client artifacts. |
| +1 | javadoc | 62 | the patch passed |
| -1 | findbugs | 35 | hadoop-common in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 34 | hadoop-common in the patch failed. |
| +1 | asflicense | 30 | The patch does not generate ASF License warnings. |
| | | 4751 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-935/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/935 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 5832cc2c2388 4.4.0-144-generic #170~14.04.1-Ubuntu SMP Mon Mar 18 15:02:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / fcfe7a3 |
| Default Java | 1.8.0_212 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-935/1/artifact/out/patch-mvninstall-hadoop-common-project_hadoop-common.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-935/1/artifact/out/patch-compile-root.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-935/1/artifact/out/patch-compile-root.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-935/1/artifact/out/patch-mvnsite-hadoop-common-project_hadoop-common.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-935/1/artifact/out/patch-findbugs-hadoop-common-project_hadoop-common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-935/1/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-935/1/testReport/ |
| Max. process+thread count | 304 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-935/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
The change looks legit, but it doesn't compile. @cxorm any idea?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 48 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1151 | trunk passed |
| +1 | compile | 1060 | trunk passed |
| +1 | checkstyle | 41 | trunk passed |
| +1 | mvnsite | 78 | trunk passed |
| +1 | shadedclient | 849 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 62 | trunk passed |
| 0 | spotbugs | 129 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 127 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 51 | the patch passed |
| +1 | compile | 1106 | the patch passed |
| +1 | javac | 1106 | the patch passed |
| +1 | checkstyle | 42 | the patch passed |
| +1 | mvnsite | 82 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 731 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 62 | the patch passed |
| +1 | findbugs | 135 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 569 | hadoop-common in the patch passed. |
| +1 | asflicense | 45 | The patch does not generate ASF License warnings. |
| | | 6307 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-935/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/935 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 8ae6fa4d22ff 4.4.0-144-generic #170~14.04.1-Ubuntu SMP Mon Mar 18 15:02:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / fcfe7a3 |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-935/2/testReport/ |
| Max. process+thread count | 1397 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-935/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by cxorm** [comment]
> The change looks legit, but it doesn't compile. @cxorm any idea?

Cause in the first commit, I didn't notice the abstract function using the variable and I didn't delete the line.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1123 | trunk passed |
| +1 | compile | 1044 | trunk passed |
| +1 | checkstyle | 44 | trunk passed |
| +1 | mvnsite | 78 | trunk passed |
| +1 | shadedclient | 860 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 62 | trunk passed |
| 0 | spotbugs | 125 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 124 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 46 | the patch passed |
| +1 | compile | 991 | the patch passed |
| +1 | javac | 991 | the patch passed |
| +1 | checkstyle | 43 | the patch passed |
| +1 | mvnsite | 73 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 734 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 63 | the patch passed |
| +1 | findbugs | 128 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 520 | hadoop-common in the patch passed. |
| +1 | asflicense | 45 | The patch does not generate ASF License warnings. |
| | | 6079 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-935/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/935 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux b0bdcc04c76d 4.4.0-141-generic #167~14.04.1-Ubuntu SMP Mon Dec 10 13:20:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 101d5b5 |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-935/3/testReport/ |
| Max. process+thread count | 1493 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-935/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
+1

**Comment by jojochuang** [comment]
See the corresponding jira. I reverted this commit.

**Comment by cxorm** [comment]
> See the corresponding jira. I reverted this commit.

Thanks for pointing out it

**Pull request merged**
