### PR TITLE
HADOOP-17338 Intermittent S3AInputStream failures: Premature end of C…

### PR DESCRIPTION
**Pull request by yzhangal**
…ontent-Length delimited message body etc

## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by yzhangal** [comment]
HI @steveloughran ,

Thanks for reviewing and merging HADOOP-16767.  This is the PR for HADOOPs-17338 on branch-2.10, the test was done previously together with HADOOP-16767:
https://github.com/apache/hadoop/pull/2685#issuecomment-774878069

Would you please help taking a look?

Thanks.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  11m 15s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-2.10 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  16m 14s |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |   0m 33s |  branch-2.10 passed  |
| +1 :green_heart: |  checkstyle  |   0m 24s |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |   0m 45s |  branch-2.10 passed  |
| +1 :green_heart: |  javadoc  |   0m 29s |  branch-2.10 passed  |
| +0 :ok: |  spotbugs  |   1m  6s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   1m  3s |  branch-2.10 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 33s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 28s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 28s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 17s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 37s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 20s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   1m  6s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 38s |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 28s |  The patch does not generate ASF License warnings.  |
|  |   |  38m  6s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2692/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2692 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 4f9cd9d5dd80 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / 7b4034c |
| Default Java | Oracle Corporation-1.7.0_95-b00 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2692/1/testReport/ |
| Max. process+thread count | 196 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-aws U: hadoop-tools/hadoop-aws |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2692/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
+1, merged.

**Comment by yzhangal** [comment]
Really appreciate your quick response and help Steve!

**Pull request merged**
