### PR TITLE
HDFS-17691. [FGL] Move FSNamesystemLockMode to org.apache.hadoop.hdfs.util package

### PR DESCRIPTION
**Pull request by ZanderXu**
```
package org.apache.hadoop.hdfs.util;

import org.apache.hadoop.hdfs.server.namenode.fgl.FSNamesystemLockMode;

/** Read-write lock interface for FSNamesystem. */
public interface RwLock {
  /** Acquire read lock. */
  default void readLock() {
    readLock(FSNamesystemLockMode.GLOBAL);
  }
 ...
} 
```

This dependency is not ideal. The `FSNamesystemLockMode` should be relocated to the same package as `RwLock`.

### CODE REVIEW

**Review by ferhui — APPROVED** [review]

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 48s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  1s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 46 new or modified test files.  |
|||| _ HDFS-17384 Compile Tests _ |
| +0 :ok: |  mvndep  |   6m 32s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  35m 37s |  |  HDFS-17384 passed  |
| +1 :green_heart: |  compile  |  18m 48s |  |  HDFS-17384 passed with JDK Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04  |
| +1 :green_heart: |  compile  |  16m 49s |  |  HDFS-17384 passed with JDK Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga  |
| +1 :green_heart: |  checkstyle  |   4m 57s |  |  HDFS-17384 passed  |
| +1 :green_heart: |  mvnsite  |   3m 10s |  |  HDFS-17384 passed  |
| +1 :green_heart: |  javadoc  |   3m  1s |  |  HDFS-17384 passed with JDK Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   3m 14s |  |  HDFS-17384 passed with JDK Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga  |
| +1 :green_heart: |  spotbugs  |   5m 47s |  |  HDFS-17384 passed  |
| +1 :green_heart: |  shadedclient  |  37m 32s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 31s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 55s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 54s |  |  the patch passed with JDK Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04  |
| +1 :green_heart: |  javac  |  17m 54s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  21m 38s |  |  the patch passed with JDK Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga  |
| +1 :green_heart: |  javac  |  21m 38s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   5m 16s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7232/2/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 1 new + 1015 unchanged - 7 fixed = 1016 total (was 1022)  |
| +1 :green_heart: |  mvnsite  |   2m 55s |  |  the patch passed  |
| -1 :x: |  javadoc  |   1m 24s | [/patch-javadoc-hadoop-hdfs-project_hadoop-hdfs-jdkUbuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7232/2/artifact/out/patch-javadoc-hadoop-hdfs-project_hadoop-hdfs-jdkUbuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04.txt) |  hadoop-hdfs in the patch failed with JDK Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04.  |
| -1 :x: |  javadoc  |   1m 52s | [/results-javadoc-javadoc-hadoop-hdfs-project_hadoop-hdfs-jdkPrivateBuild-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7232/2/artifact/out/results-javadoc-javadoc-hadoop-hdfs-project_hadoop-hdfs-jdkPrivateBuild-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga.txt) |  hadoop-hdfs-project_hadoop-hdfs-jdkPrivateBuild-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga with JDK Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga generated 1 new + 1 unchanged - 0 fixed = 2 total (was 1)  |
| +1 :green_heart: |  spotbugs  |   6m 29s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  37m 57s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 261m 25s |  |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |  31m 28s |  |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 55s |  |  hadoop-fs2img in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 12s |  |  The patch does not generate ASF License warnings.  |
|  |   | 538m 48s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7232/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/7232 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux d94d00f66a3a 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | HDFS-17384 / cbfdcc3da69c0951c10fe47f7267897a4e519826 |
| Default Java | Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7232/2/testReport/ |
| Max. process+thread count | 3194 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-rbf hadoop-tools/hadoop-fs2img U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7232/2/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ferhui** [comment]
Please fix the checkstyle issue

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  17m 36s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 46 new or modified test files.  |
|||| _ HDFS-17384 Compile Tests _ |
| +0 :ok: |  mvndep  |   5m 48s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  35m  5s |  |  HDFS-17384 passed  |
| +1 :green_heart: |  compile  |  18m 45s |  |  HDFS-17384 passed with JDK Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04  |
| +1 :green_heart: |  compile  |  17m  2s |  |  HDFS-17384 passed with JDK Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga  |
| +1 :green_heart: |  checkstyle  |   4m 47s |  |  HDFS-17384 passed  |
| +1 :green_heart: |  mvnsite  |   3m 10s |  |  HDFS-17384 passed  |
| +1 :green_heart: |  javadoc  |   3m  1s |  |  HDFS-17384 passed with JDK Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   3m 18s |  |  HDFS-17384 passed with JDK Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga  |
| +1 :green_heart: |  spotbugs  |   5m 49s |  |  HDFS-17384 passed  |
| +1 :green_heart: |  shadedclient  |  40m 38s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 32s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 56s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 53s |  |  the patch passed with JDK Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04  |
| +1 :green_heart: |  javac  |  17m 53s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 10s |  |  the patch passed with JDK Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga  |
| +1 :green_heart: |  javac  |  17m 10s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   4m 35s |  |  root: The patch generated 0 new + 1015 unchanged - 7 fixed = 1015 total (was 1022)  |
| +1 :green_heart: |  mvnsite  |   3m  4s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 54s |  |  the patch passed with JDK Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   3m 14s |  |  the patch passed with JDK Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga  |
| +1 :green_heart: |  spotbugs  |   6m 16s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  38m 34s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 264m 51s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7232/3/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| -1 :x: |  unit  |  31m 24s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs-rbf.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7232/3/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs-rbf.txt) |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 55s |  |  hadoop-fs2img in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 12s |  |  The patch does not generate ASF License warnings.  |
|  |   | 556m 29s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestRollingUpgrade |
|   | hadoop.hdfs.server.federation.router.TestRouterAllResolver |
|   | hadoop.hdfs.server.federation.router.TestRouterClientRejectOverload |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7232/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/7232 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 579b343ece60 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | HDFS-17384 / 59a665903a1a2fced871e5242b9ed07a70ed22a2 |
| Default Java | Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7232/3/testReport/ |
| Max. process+thread count | 3305 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-rbf hadoop-tools/hadoop-fs2img U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7232/3/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ZanderXu** [comment]
```
hadoop.hdfs.TestRollingUpgrade
hadoop.hdfs.server.federation.router.TestRouterAllResolver
hadoop.hdfs.server.federation.router.TestRouterClientRejectOverload
```
These failed UTs work well locally.

**Review by haiyang1987 — APPROVED** [review]
LGTM. +1.

**Comment by ferhui** [comment]
@ZanderXu Thanks for contribution. @haiyang1987 Thanks for review. merged

**Pull request merged**
