### PR TITLE
Fixed location of service provider configuration file on Azure Data lake Filesystem.

### PR DESCRIPTION
**Pull request by jinhyukchang**
Currently, the provider configuration file is in wrong location -- should be under services folder -- and ADL file system cannot be loaded without registering manually into the configuration.
https://docs.oracle.com/javase/tutorial/ext/basics/spi.html#register-service-providers

### CODE REVIEW

**Comment by liuml07** [comment]
Can you file a JIRA and link this to it?

**Comment by jinhyukchang** [comment]
Sure, just created Jira [ticket](HADOOP-14149)

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by aajisaka** [comment]
https://issues.apache.org/jira/browse/HADOOP-14149 is closed as duplicate. Closing this pull request as well.

**Pull request closed without merging**
