### PR TITLE
HADOOP-17571 : Bump up woodstox-core to 5.3.0 due to security concerns

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Comment by virajjasani** [comment]
@liuml07 Could you please take a look? The build failure doesn't seem relevant.
The fix for not-relevant broken build issue: #2759

**Comment by steveloughran** [comment]
can you do a rebase and resubmit? builds are working again. thanks

**Review by liuml07 — APPROVED** [review]
+1 after a clear Jenkins run.

**Comment by liuml07** [comment]
According to the test results in the Jenkins job, the report is clean: https://ci-hadoop.apache.org/blue/organizations/jenkins/hadoop-multibranch/detail/PR-2757/2/pipeline

However, it failed to generate report and post in this PR. I'll merge this after 24 hours if no objection.

**Review by aajisaka — APPROVED** [review]

**Pull request merged**
