### PR TITLE
HADOOP-18782 upgrade to snappy-java 1.1.10.1 due to CVEs

### PR DESCRIPTION
**Pull request by pjfanning**
### Description of PR

upgrade to snappy-java 1.1.10.1 due to CVEs

### How was this patch tested?

CI build

### For code changes:

- [X] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [X] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Review by slfan1989 — APPROVED** [review]

**Comment by slfan1989** [comment]
+1（binding) wait jenkins compilation result.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 58s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  2s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  2s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  2s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  2s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  18m  1s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  24m 33s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  19m  6s |  |  trunk passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1  |
| +1 :green_heart: |  compile  |  16m 51s |  |  trunk passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09  |
| +1 :green_heart: |  mvnsite  |  21m 37s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   9m  2s |  |  trunk passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1  |
| +1 :green_heart: |  javadoc  |   7m 33s |  |  trunk passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09  |
| +1 :green_heart: |  shadedclient  |  40m 35s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 33s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  20m 11s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m  6s |  |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1  |
| +1 :green_heart: |  javac  |  18m  6s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 56s |  |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09  |
| +1 :green_heart: |  javac  |  16m 56s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  15m  9s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  1s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   8m 48s |  |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1  |
| +1 :green_heart: |  javadoc  |   7m 30s |  |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09  |
| +1 :green_heart: |  shadedclient  |  40m 50s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 775m 30s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5773/1/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 40s |  |  The patch does not generate ASF License warnings.  |
|  |   | 1036m 15s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.mapreduce.v2.TestMRJobsWithProfiler |
|   | hadoop.mapreduce.v2.TestMRJobs |
|   | hadoop.mapreduce.v2.TestUberAM |
|   | hadoop.yarn.server.timelineservice.security.TestTimelineAuthFilterForV2 |
|   | hadoop.hdfs.server.namenode.ha.TestObserverNode |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5773/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5773 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint shellcheck shelldocs |
| uname | Linux 33a7ae8dcf6a 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 0f8ed617cf87ecd866d2eda2d926c8e5648e9119 |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5773/1/testReport/ |
| Max. process+thread count | 3094 (vs. ulimit of 5500) |
| modules | C: hadoop-project . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5773/1/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by ayushtkn — APPROVED** [review]
LGTM,
failing tests are failing continuously, can ignore for now, need to fix them soon....

**Comment by steveloughran** [comment]
> failing tests are failing continuously, can ignore for now, need to fix them soon....

any underlying cause?

**Review by steveloughran — COMMENTED** [review]
LGTM
+1

**Comment by ayushtkn** [comment]
broken in the daily build, since months
https://ci-hadoop.apache.org/view/Hadoop/job/hadoop-qbt-trunk-java8-linux-x86_64/1268/#showFailuresLink
they are broken since 3-4 months, I chased some earlier MR related they were Junit upgrade related, but these are different.

it is expecting to log the thread dump in the file, but that isn't getting dumped now
```
java.lang.AssertionError: No thread dump
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.apache.hadoop.mapreduce.v2.TestMRJobs.testThreadDumpOnTaskTimeout(TestMRJobs.java:1273)
```
someone removed it or something broke in that logic, haven't got chance to debug yet....

**Comment by steveloughran** [comment]
looks like a really brittle test, including comments that don't match the code, and a text file scan which (a) doesn't log the output and (b) could well be brittle against Java versions changing the format of the output.

**Comment by steveloughran** [comment]
btw, tried a cherrypick to branch-3.3 and the build failed as there's no explicit jettison import in that branch
```
[WARNING]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project hadoop-yarn-common: Compilation failure: Compilation failure:
[ERROR] /Users/stevel/hadoop/commit/apache-hadoop/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/webapp/util/YarnWebServiceUtils.java:[30,34] package org.codehaus.jettison.json does not exist
[ERROR] /Users/stevel/hadoop/commit/apache-hadoop/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/webapp/util/YarnWebServiceUtils.java:[53,17] cannot find symbol
[ERROR]   symbol:   class JSONObject
[ERROR]   location: class org.apache.hadoop.yarn.webapp.util.YarnWebServiceUtils
[ERROR] /Users/stevel/hadoop/commit/apache-hadoop/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/webapp/util/YarnWebServiceUtils.java:[70,18] cannot find symbol
[ERROR]   symbol:   class JSONObject
[ERROR]   location: class org.apache.hadoop.yarn.webapp.util.YarnWebServiceUtils
[ERROR] /Users/stevel/hadoop/commit/apache-hadoop/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/webapp/util/YarnWebServiceUtils.java:[79,33] cannot find symbol
[ERROR]   symbol:   class JSONObject
[ERROR]   location: class org.apache.hadoop.yarn.webapp.util.YarnWebServiceUtils
[ERROR] -> [Help 1]
[ERROR]
```

**Comment by ayushtkn** [comment]
These tests are fixed now: https://ci-hadoop.apache.org/view/Hadoop/job/hadoop-qbt-trunk-java8-linux-x86_64/1367/testReport/junit/org.apache.hadoop.mapreduce.v2/TestMRJobs/testThreadDumpOnTaskTimeout/

The culprit was:
[HADOOP-18649](https://issues.apache.org/jira/browse/HADOOP-18649)

And this was committed in march & these tests were also failing since 4-5 months, now post revert they are passing, so hopefully we are sorted :-)

**Pull request merged**
