### PR TITLE
HADOOP-17138. Fix spotbugs warnings surfaced after upgrade to 4.0.6. …

### PR DESCRIPTION
**Pull request by aajisaka**
…(#2155)

(cherry picked from commit 1b29c9bfeee0035dd042357038b963843169d44c)

Backport HADOOP-17138 to branch-3.3 to fix the findbugs warnings in hadoop-cos.

### CODE REVIEW

**Comment by aajisaka** [comment]
I create a PR for running the unit tests in branch-3.3. If the result is fine, I'll cherry-pick it to branch-3.3.

**Review by sunchao — APPROVED** [review]
LGTM on pending CI - thanks @aajisaka

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  32m 16s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 52s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  33m 47s |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  23m  9s |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m 38s |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  13m 59s |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  38m 36s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   6m 49s |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   0m 54s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| -1 :x: |  findbugs  |  15m  5s |  hadoop-yarn-project/hadoop-yarn in branch-3.3 has 2 extant findbugs warnings.  |
| -1 :x: |  findbugs  |   0m 43s |  hadoop-cloud-storage-project/hadoop-cos in branch-3.3 has 1 extant findbugs warnings.  |
| -1 :x: |  findbugs  |   0m 53s |  hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests in branch-3.3 has 2 extant findbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  12m  2s |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 43s |  the patch passed  |
| +1 :green_heart: |  javac  |  19m 43s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m 58s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  12m 35s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  4s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  16m 57s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   5m 37s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   2m 17s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  findbugs  |   3m 29s |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  findbugs  |  13m 18s |  hadoop-yarn-project/hadoop-yarn generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2)  |
| +1 :green_heart: |  findbugs  |   0m 51s |  hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2)  |
| +1 :green_heart: |  findbugs  |   4m 17s |  hadoop-mapreduce-project in the patch passed.  |
| +1 :green_heart: |  findbugs  |   0m 54s |  hadoop-sls in the patch passed.  |
| +1 :green_heart: |  findbugs  |   0m 42s |  hadoop-cloud-storage-project/hadoop-cos generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   9m 58s |  hadoop-common in the patch passed.  |
| -1 :x: |  unit  | 116m 11s |  hadoop-hdfs in the patch passed.  |
| -1 :x: |  unit  | 223m 21s |  hadoop-yarn in the patch passed.  |
| +1 :green_heart: |  unit  |  15m 57s |  hadoop-yarn-server-timelineservice-hbase-tests in the patch passed.  |
| +1 :green_heart: |  unit  | 152m 59s |  hadoop-mapreduce-project in the patch passed.  |
| -1 :x: |  unit  |  12m 40s |  hadoop-sls in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 45s |  hadoop-cos in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 10s |  The patch does not generate ASF License warnings.  |
|  |   | 802m  1s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.fs.ftp.TestFTPFileSystem |
|   | hadoop.hdfs.TestDecommissionWithStripedBackoffMonitor |
|   | hadoop.hdfs.server.datanode.TestBPOfferService |
|   | hadoop.hdfs.TestDistributedFileSystem |
|   | hadoop.hdfs.server.datanode.TestNNHandlesCombinedBlockReport |
|   | hadoop.yarn.applications.distributedshell.TestDistributedShell |
|   | hadoop.yarn.client.api.impl.TestAMRMClient |
|   | hadoop.yarn.server.resourcemanager.TestRMHATimelineCollectors |
|   | hadoop.yarn.server.resourcemanager.security.TestDelegationTokenRenewer |
|   | hadoop.yarn.server.resourcemanager.scheduler.fair.TestFairSchedulerPreemption |
|   | hadoop.yarn.sls.appmaster.TestAMSimulator |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2538/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2538 |
| Optional Tests | dupname asflicense xml compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux eb91fce54196 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / e4cab4b |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~16.04-b01 |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2538/1/artifact/out/branch-findbugs-hadoop-yarn-project_hadoop-yarn-warnings.html |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2538/1/artifact/out/branch-findbugs-hadoop-cloud-storage-project_hadoop-cos-warnings.html |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2538/1/artifact/out/branch-findbugs-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-timelineservice-hbase-tests-warnings.html |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2538/1/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2538/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2538/1/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn.txt |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2538/1/artifact/out/patch-unit-hadoop-tools_hadoop-sls.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2538/1/testReport/ |
| Max. process+thread count | 3243 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs hadoop-yarn-project/hadoop-yarn hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests hadoop-mapreduce-project hadoop-tools/hadoop-sls hadoop-cloud-storage-project/hadoop-cos U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2538/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
Merged. Thank you @sunchao for your review.

**Pull request merged**
