### PR TITLE
HADOOP-17152. Provide Hadoop's own Lists utility to reduce dependency on Guava

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 49s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  32m 56s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  22m 43s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |  19m 14s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  checkstyle  |   1m  1s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 30s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   1m  1s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   1m 34s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |   2m 22s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  18m 14s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 56s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  21m 56s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |  21m 56s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  19m  9s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |  19m  9s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 59s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 28s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m  0s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   1m 30s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |   2m 33s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  18m 14s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  16m 50s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 49s |  |  The patch does not generate ASF License warnings.  |
|  |   | 186m 44s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3061/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3061 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 437b75a81723 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 7c4887cb1083814a9218cbbe03991d3c408d5468 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3061/1/testReport/ |
| Max. process+thread count | 1234 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3061/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by bogthe — APPROVED** [review]
Checked it against what's currently in `master` for Guava and LGTM!

I have one comment about the mention of mutability in the classes' comments. Is there an immutable alternative that we can point to? I think from Guava's point of view it makes sense to mention that in the comments since they do offer an immutable alternative, if Hadoop does/doesn't maybe worth specifying?

**Comment by virajjasani** [comment]
Thanks for the review @bogthe. I understand about providing comments for immutable alternatives but specifically in the case of `List`, Hadoop does not require any. I have checked code in all modules and hence decided to remove info about immutable lists in comments.

**Review by jojochuang — COMMENTED** [review]
I myself is not the best reviewer since I seldom to pay attention to helper methods and syntactic sugar, but the PR looks good to me. 

Question: now that we have guava shaded and relocated in trunk and branch-3.3, classpath conflict with downstream applications will no longer be an issue. I'm curious if the benefit of maintaining our own Lists utility outweights using Guava

**Comment by virajjasani** [comment]
@jojochuang HADOOP-17098 provides best reasons for this.

Shading Guava in HADOOP-17288 solves the conflicts of Guava library in Hadoop upstream, downstreams, and the other projects (hbase,etc..).
The Guava byte code will still be loaded and be part of the runtime.
This Jira (when complete) gets rid of the Guava byte code which has the following benefits:

- Reduce memory fooprint. (less classes to load)
- Better code management: Guava will likely has security updates that forces Hadoop to adopt new releases and dealing with compatibilities.
- Avoid struggles analyzing guava performance

**Review by jojochuang — APPROVED** [review]
LGTM

**Review by tasanuma — APPROVED** [review]
LGTM.

**Comment by tasanuma** [comment]
Merged it. Thanks for your contribution, @virajjasani. Thanks for your reviews, @bogthe and @jojochuang.

**Pull request merged**
