### PR TITLE
YARN-11312: [UI2] Refresh buttons don't work after EmberJS upgrade

### PR DESCRIPTION
**Pull request by susheel-gupta**
Change-Id: Iffd45222b073cc1bc35bbb3153ffe6583aefaa74

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 35s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  jshint  |   0m  0s |  |  jshint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  32m 41s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  52m  3s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 15s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  shadedclient  |  19m 19s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 39s |  |  The patch does not generate ASF License warnings.  |
|  |   |  75m 41s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5649/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5649 |
| Optional Tests | dupname asflicense shadedclient codespell detsecrets jshint |
| uname | Linux dd2d17917ec9 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 9f4230d781ac976f8245e0c6eb76c40fb9178e08 |
| Max. process+thread count | 555 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui U: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5649/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by p-szucs — APPROVED** [review]

**Comment by brumi1024** [comment]
Thanks @susheel-gupta for the patch, and @p-szucs for the review, merged to trunk. Can you please check if branch-3.3 and/or 3.2 has the same EmberJS version?

**Comment by susheel-gupta** [comment]
@brumi1024  Yes, the emberJS version in branch-3.2 (https://github.com/apache/hadoop/blob/branch-3.2/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/bower.json#L4) and branch-3.3 (https://github.com/apache/hadoop/blob/branch-3.3/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/bower.json#L4) is same as trunk.

Do we need to fix this issue in branch-3.2 and branch-3.3 ?.
If yes, Question: I'm unable to fetch this branch-3.2 and branch-3.3 locally, how to ensure these fix is compatible with branch-3.2 and branch-3.3 ?.

**Comment by szilard-nemeth** [comment]
@susheel-gupta 
How do you mean you can't fetch those branches?
If you do git fetch and git branch -r you should see branch-3.2 and branch-3.3 in the list.
You can also see these branches on the GitHub UI.

**Pull request merged**
