### PR TITLE
HADOOP-17370. Upgrade commons-compress to 1.20

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to upgrade commons-compress to 1.20 to bring the following fix.

- https://commons.apache.org/proper/commons-compress/security-reports.html

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @sunchao

**Review by sunchao — APPROVED** [review]
thanks @dongjoon-hyun . +1 pending CI

**Comment by dongjoon-hyun** [comment]
Thank you so much, @sunchao .

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m 11s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 35s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  23m  7s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  21m 44s |  |  trunk passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  compile  |  19m 52s |  |  trunk passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  mvnsite  |  27m 55s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  17m  3s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   7m 50s |  |  trunk passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javadoc  |   7m 56s |  |  trunk passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 32s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  23m 57s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  25m  9s |  |  the patch passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javac  |  25m  9s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  23m  2s |  |  the patch passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  javac  |  23m  2s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  25m 27s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 14s |  |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  3s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  18m 33s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   8m 36s |  |  the patch passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javadoc  |  10m 11s |  |  the patch passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 559m 30s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/1/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| -1 :x: |  asflicense  |   1m 23s | [/patch-asflicense-problems.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/1/artifact/out/patch-asflicense-problems.txt) |  The patch generated 17 ASF License warnings.  |
|  |   | 843m  5s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.fs.azure.TestNativeAzureFileSystemConcurrency |
|   | hadoop.fs.azure.TestNativeAzureFileSystemMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemFileNameCheck |
|   | hadoop.fs.azure.TestNativeAzureFileSystemOperationsMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemContractMocked |
|   | hadoop.fs.azure.TestOutOfBandAzureBlobOperations |
|   | hadoop.fs.azure.TestWasbFsck |
|   | hadoop.fs.azure.TestBlobMetadata |
|   | hadoop.tools.dynamometer.TestDynamometerInfra |
|   | hadoop.yarn.applications.distributedshell.TestDistributedShell |
|   | hadoop.yarn.server.timelineservice.storage.TestTimelineReaderHBaseDown |
|   | hadoop.yarn.server.timelineservice.storage.TestTimelineWriterHBaseDown |
|   | hadoop.yarn.server.resourcemanager.security.TestDelegationTokenRenewer |
|   | hadoop.metrics2.source.TestJvmMetrics |
|   | hadoop.hdfs.server.federation.router.TestRouterRpc |
|   | hadoop.hdfs.server.datanode.TestDataNodeMXBean |
|   | hadoop.hdfs.server.datanode.checker.TestDatasetVolumeCheckerFailures |
|   | hadoop.hdfs.server.datanode.TestIncrementalBlockReports |
|   | hadoop.hdfs.server.mover.TestMover |
|   | hadoop.hdfs.server.mover.TestStorageMover |
|   | hadoop.hdfs.server.namenode.TestNameNodeRecovery |
|   | hadoop.hdfs.server.namenode.TestListCorruptFileBlocks |
|   | hadoop.hdfs.server.datanode.checker.TestDatasetVolumeChecker |
|   | hadoop.hdfs.server.datanode.TestDirectoryScanner |
|   | hadoop.hdfs.server.namenode.TestTransferFsImage |
|   | hadoop.hdfs.server.datanode.TestDataNodeMetricsLogger |
|   | hadoop.hdfs.server.namenode.TestCacheDirectives |
|   | hadoop.hdfs.server.datanode.TestBatchIbr |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2452 |
| Optional Tests | dupname asflicense shellcheck shelldocs compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 54ff60f629c2 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 9a9ab5b48e3 |
| Default Java | Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/1/testReport/ |
| Max. process+thread count | 3343 (vs. ulimit of 5500) |
| modules | C: hadoop-project . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/1/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by sunchao** [comment]
There're quite a few UT failures with the message: "java.lang.OutOfMemoryError: unable to create new native thread". While I think it is not related, I kicked out the CI again just to be sure.

**Comment by steveloughran** [comment]
wasb failures are unrelated (http client upgrade); unsure about the others

**Comment by sunchao** [comment]
seems triggering the CI manually didn't work

Screen Shot 2020-11-12 at 9 56 31 AM

@dongjoon-hyun can you re-trigger the CI with an empty commit? thanks.

**Comment by dongjoon-hyun** [comment]
Sure!

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  2s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  15m  4s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  24m 53s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  23m  3s |  |  trunk passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  compile  |  19m  7s |  |  trunk passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  mvnsite  |  27m 40s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  17m 28s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   7m 18s |  |  trunk passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javadoc  |   7m 25s |  |  trunk passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 32s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  23m  4s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  22m 14s |  |  the patch passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javac  |  22m 14s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 16s |  |  the patch passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
| +1 :green_heart: |  javac  |  19m 16s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  22m  6s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 14s |  |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  17m 14s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   7m 40s |  |  the patch passed with JDK Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1  |
| +1 :green_heart: |  javadoc  |   8m  2s |  |  the patch passed with JDK Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 600m 22s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/3/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 36s |  |  The patch does not generate ASF License warnings.  |
|  |   | 869m 12s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.fs.azure.TestNativeAzureFileSystemConcurrency |
|   | hadoop.fs.azure.TestNativeAzureFileSystemMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemFileNameCheck |
|   | hadoop.fs.azure.TestNativeAzureFileSystemOperationsMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemContractMocked |
|   | hadoop.fs.azure.TestOutOfBandAzureBlobOperations |
|   | hadoop.fs.azure.TestWasbFsck |
|   | hadoop.fs.azure.TestBlobMetadata |
|   | hadoop.tools.dynamometer.TestDynamometerInfra |
|   | hadoop.yarn.applications.distributedshell.TestDistributedShell |
|   | hadoop.yarn.server.router.webapp.TestRouterWebServicesREST |
|   | hadoop.yarn.server.resourcemanager.scheduler.capacity.TestCapacitySchedulerAutoQueueCreation |
|   | hadoop.yarn.server.resourcemanager.security.TestDelegationTokenRenewer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2452 |
| Optional Tests | dupname asflicense shellcheck shelldocs compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux ee1027a0767a 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / fc961b63d14 |
| Default Java | Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9+11-Ubuntu-0ubuntu1.18.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/3/testReport/ |
| Max. process+thread count | 3396 (vs. ulimit of 5500) |
| modules | C: hadoop-project . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/3/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by dongjoon-hyun** [comment]
Although it fails again, it gives smaller number of failures than before.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  31m 20s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  15m  2s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  23m 16s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  21m 23s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  compile  |  18m  6s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  mvnsite  |  26m 36s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  17m 15s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   7m 40s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   7m 25s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 32s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  23m  7s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  23m 16s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javac  |  23m 16s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 10s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
| +1 :green_heart: |  javac  |  19m 10s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  22m 28s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 13s |  |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  16m 53s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   7m 28s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04  |
| +1 :green_heart: |  javadoc  |   7m 28s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 602m 20s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/4/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m 11s |  |  The patch does not generate ASF License warnings.  |
|  |   | 897m 16s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.fs.azure.TestNativeAzureFileSystemConcurrency |
|   | hadoop.fs.azure.TestNativeAzureFileSystemMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemFileNameCheck |
|   | hadoop.fs.azure.TestNativeAzureFileSystemOperationsMocked |
|   | hadoop.fs.azure.TestNativeAzureFileSystemContractMocked |
|   | hadoop.fs.azure.TestOutOfBandAzureBlobOperations |
|   | hadoop.fs.azure.TestWasbFsck |
|   | hadoop.fs.azure.TestBlobMetadata |
|   | hadoop.tools.dynamometer.TestDynamometerInfra |
|   | hadoop.yarn.applications.distributedshell.TestDistributedShell |
|   | hadoop.yarn.server.router.webapp.TestRouterWebServicesREST |
|   | hadoop.yarn.server.resourcemanager.security.TestDelegationTokenRenewer |
|   | hadoop.security.TestRaceWhenRelogin |
|   | hadoop.hdfs.server.federation.router.TestRouterRpcMultiDestination |
|   | hadoop.hdfs.TestGetFileChecksum |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2452 |
| Optional Tests | dupname asflicense shellcheck shelldocs compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 8b4cf6fe7f3f 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / ebe1d1fbf7a |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.18.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/4/testReport/ |
| Max. process+thread count | 3286 (vs. ulimit of 5500) |
| modules | C: hadoop-project . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2452/4/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by dongjoon-hyun** [comment]
Thank you for review guys. For now, I'll close this PR due to the consistent failures.

Since the downstream projects (like Apache Spark) are able to override this dependency in any ways, this is not that urgent.

**Pull request closed without merging**
