### PR TITLE
HDDS-1490. Support configurable container placement policy through 'o…

### PR DESCRIPTION
**Pull request by ChenSammi**
…zone.scm.container.placement.classname'

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 31 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 9 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 22 | Maven dependency ordering for branch |
| +1 | mvninstall | 515 | trunk passed |
| +1 | compile | 279 | trunk passed |
| +1 | checkstyle | 71 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 827 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 177 | trunk passed |
| 0 | spotbugs | 335 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 527 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 36 | Maven dependency ordering for patch |
| +1 | mvninstall | 505 | the patch passed |
| +1 | compile | 283 | the patch passed |
| +1 | javac | 283 | the patch passed |
| -0 | checkstyle | 35 | hadoop-hdds: The patch generated 4 new + 0 unchanged - 0 fixed = 4 total (was 0) |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 1 | The patch has no whitespace issues. |
| +1 | xml | 9 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 625 | patch has no errors when building and testing our client artifacts. |
| -1 | javadoc | 71 | hadoop-hdds generated 9 new + 14 unchanged - 0 fixed = 23 total (was 14) |
| +1 | findbugs | 523 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 240 | hadoop-hdds in the patch passed. |
| -1 | unit | 133 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 39 | The patch does not generate ASF License warnings. |
| | | 5253 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.om.request.bucket.TestOMBucketDeleteRequest |
|   | hadoop.ozone.om.request.bucket.TestOMBucketCreateRequest |
|   | hadoop.ozone.om.ratis.TestOzoneManagerRatisServer |
|   | hadoop.ozone.om.ratis.TestOzoneManagerStateMachine |
|   | hadoop.ozone.om.request.bucket.TestOMBucketSetPropertyRequest |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-903/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/903 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml |
| uname | Linux f128fa432a0c 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 7991159 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-903/1/artifact/out/diff-checkstyle-hadoop-hdds.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-903/1/artifact/out/diff-javadoc-javadoc-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-903/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-903/1/testReport/ |
| Max. process+thread count | 1346 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-hdds/server-scm hadoop-ozone/integration-test hadoop-ozone/ozone-manager U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-903/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by ChenSammi** [comment]
Double checked all failed UT. Two failure reasons,
1. Cannot mock/spy class org.apache.hadoop.ozone.om.OzoneManager
Mockito cannot mock/spy because :
 - final class
2.  collateral damage, failure triggerred by failure 1
java.lang.NullPointerException
	at org.apache.hadoop.ozone.om.request.bucket.TestOMBucketCreateRequest.stop(TestOMBucketCreateRequest.java:82)

@xiaoyuyao  Do you have a moment to review this latest 04.patch?

**Comment by xiaoyuyao** [comment]
bq. Cannot mock/spy class org.apache.hadoop.ozone.om.OzoneManager
Mockito cannot mock/spy because :final class

I think this is related to the change in the pom.xml where we only add the topology related xml files to testResources explicitly. In this case, I think we will need to add the mokito-extensions from the test/resources as well explicitly. This is need to surpress the warning above. 

     <testResource>
       <directory>${basedir}/src/test/resources</directory>
     </testResource>

Also, please fix the checkstyle issue in the next commit.

**Comment by ChenSammi** [comment]
@xiaoyuyao, thanks for the information. I didn't releasize that it's because I explicitely added the testResouces to the pom.xml, then the resources under ${basedir}/src/test/resources get ignored.  I will upload a new commit shortly.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 32 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 9 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for branch |
| +1 | mvninstall | 492 | trunk passed |
| +1 | compile | 293 | trunk passed |
| +1 | checkstyle | 88 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 875 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 154 | trunk passed |
| 0 | spotbugs | 334 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 521 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 28 | Maven dependency ordering for patch |
| +1 | mvninstall | 441 | the patch passed |
| +1 | compile | 274 | the patch passed |
| +1 | javac | 274 | the patch passed |
| +1 | checkstyle | 64 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 5 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 626 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 156 | the patch passed |
| +1 | findbugs | 523 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 233 | hadoop-hdds in the patch passed. |
| -1 | unit | 1357 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 40 | The patch does not generate ASF License warnings. |
| | | 6380 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.client.rpc.TestCommitWatcher |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestFailureHandlingByClient |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-903/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/903 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml |
| uname | Linux 20e99d05d7c3 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 73954c1 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-903/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-903/2/testReport/ |
| Max. process+thread count | 4953 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-hdds/server-scm hadoop-ozone/integration-test hadoop-ozone/ozone-manager U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-903/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by ChenSammi** [comment]
Cannot reproduce failed test cases locally.

**Pull request merged**
