### PR TITLE
Use print() function in both Python 2 and Python 3

### PR DESCRIPTION
**Pull request by cclauss**
__print()__ is a function in Python 3.

Also, the builtin file() was removed in Python 3
* This PR recommends replacing it with __open()__ which works in both Python 2 and Python 3.

And,  Declare __global error_count__
* The global __error_count__ can not be incremented on line 126 unless it is declared as global beforehand.  Without this change, it is an _undefined name_ that has the potential to raise __NameError__ at runtime.

[flake8](http://flake8.pycqa.org) testing of https://github.com/apache/hadoop on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./hadoop-mapreduce-project/hadoop-mapreduce-examples/src/main/java/org/apache/hadoop/examples/terasort/job_history_summary.py:73:61: E999 SyntaxError: invalid syntax
print "Name reduce-output-bytes shuffle-finish reduce-finish"
                                                            ^
./dev-support/determine-flaky-tests-hadoop.py:125:5: F823 local variable 'error_count' (defined in enclosing scope on line 76) referenced before assignment
    error_count += 1
    ^
./dev-support/bin/checkcompatibility.py:195:10: F821 undefined name 'file'
    with file(annotations_path, "w") as f:
         ^
1     E999 SyntaxError: invalid syntax
1     F821 undefined name 'file'
1     F823 local variable 'error_count' (defined in enclosing scope on line 76) referenced before assignment
3
```

### CODE REVIEW

**Comment by cclauss** [comment]
[flake8](http://flake8.pycqa.org) testing of https://github.com/apache/hadoop on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./hadoop-mapreduce-project/hadoop-mapreduce-examples/src/main/java/org/apache/hadoop/examples/terasort/job_history_summary.py:73:61: E999 SyntaxError: invalid syntax
print "Name reduce-output-bytes shuffle-finish reduce-finish"
                                                            ^
./dev-support/determine-flaky-tests-hadoop.py:125:5: F823 local variable 'error_count' (defined in enclosing scope on line 76) referenced before assignment
    error_count += 1
    ^
./dev-support/bin/checkcompatibility.py:195:10: F821 undefined name 'file'
    with file(annotations_path, "w") as f:
         ^
1     E999 SyntaxError: invalid syntax
1     F821 undefined name 'file'
1     F823 local variable 'error_count' (defined in enclosing scope on line 76) referenced before assignment
3
```

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for branch |
| +1 | mvninstall | 1055 | trunk passed |
| +1 | compile | 1095 | trunk passed |
| +1 | mvnsite | 871 | trunk passed |
| -1 | pylint | 2 | Error running pylint. Please check pylint stderr files. |
| +1 | shadedclient | 652 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 329 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for patch |
| +1 | mvninstall | 1062 | the patch passed |
| +1 | compile | 998 | the patch passed |
| +1 | javac | 998 | the patch passed |
| +1 | mvnsite | 832 | the patch passed |
| -1 | pylint | 3 | Error running pylint. Please check pylint stderr files. |
| +1 | pylint | 3 | There were no new pylint issues. |
| -1 | whitespace | 0 | The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| +1 | shadedclient | 621 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 339 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 8629 | root in the patch failed. |
| +1 | asflicense | 48 | The patch does not generate ASF License warnings. |
| | | 16767 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.TestAddStripedBlocks |
|   | hadoop.hdfs.server.namenode.ha.TestQuotasWithHA |
|   | hadoop.hdfs.TestDatanodeDeath |
|   | hadoop.hdfs.TestSetrepIncreasing |
|   | hadoop.hdfs.TestDecommissionWithStriped |
|   | hadoop.hdfs.server.namenode.ha.TestRetryCacheWithHA |
|   | hadoop.hdfs.server.namenode.TestFSImage |
|   | hadoop.hdfs.TestErasureCodingPolicies |
|   | hadoop.hdfs.TestErasureCodingPoliciesWithRandomECPolicy |
|   | hadoop.hdfs.web.TestWebHDFSAcl |
|   | hadoop.hdfs.TestDataStream |
|   | hadoop.hdfs.TestFileCorruption |
|   | hadoop.hdfs.TestReconstructStripedFileWithRandomECPolicy |
|   | hadoop.hdfs.server.namenode.TestDiskspaceQuotaUpdate |
|   | hadoop.hdfs.TestClientProtocolForPipelineRecovery |
|   | hadoop.hdfs.server.namenode.TestAuditLogs |
|   | hadoop.hdfs.TestDFSStorageStateRecovery |
|   | hadoop.hdfs.server.namenode.ha.TestPipelinesFailover |
|   | hadoop.hdfs.TestReplaceDatanodeFailureReplication |
|   | hadoop.hdfs.TestDFSStripedOutputStream |
|   | hadoop.hdfs.web.TestWebHdfsWithMultipleNameNodes |
|   | hadoop.hdfs.TestErasureCodingMultipleRacks |
|   | hadoop.hdfs.web.TestWebHdfsTimeouts |
|   | hadoop.hdfs.server.datanode.TestDirectoryScanner |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-436/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/436 |
| Optional Tests | dupname asflicense pylint compile javac javadoc mvninstall mvnsite unit shadedclient |
| uname | Linux 8267278c4572 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / cd967c7 |
| Default Java | 1.8.0_212 |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/1/artifact/out/branch-pylint-stderr.txt |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/1/artifact/out/patch-pylint-stderr.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/1/artifact/out/whitespace-eol.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/1/testReport/ |
| Max. process+thread count | 4073 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-examples . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/1/console |
| versions | git=2.7.4 maven=3.3.9 pylint=1.9.2 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 38 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 22 | Maven dependency ordering for branch |
| +1 | mvninstall | 1039 | trunk passed |
| +1 | compile | 1003 | trunk passed |
| +1 | mvnsite | 877 | trunk passed |
| -1 | pylint | 2 | Error running pylint. Please check pylint stderr files. |
| +1 | shadedclient | 630 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 338 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 26 | Maven dependency ordering for patch |
| +1 | mvninstall | 1063 | the patch passed |
| +1 | compile | 982 | the patch passed |
| +1 | javac | 982 | the patch passed |
| +1 | mvnsite | 845 | the patch passed |
| -1 | pylint | 3 | Error running pylint. Please check pylint stderr files. |
| +1 | pylint | 3 | There were no new pylint issues. |
| -1 | whitespace | 0 | The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| +1 | shadedclient | 620 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 332 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 8314 | root in the patch failed. |
| +1 | asflicense | 51 | The patch does not generate ASF License warnings. |
| | | 16332 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestDFSStripedOutputStream |
|   | hadoop.hdfs.TestErasureCodingPolicies |
|   | hadoop.hdfs.server.namenode.ha.TestBootstrapAliasmap |
|   | hadoop.hdfs.TestEncryptedTransfer |
|   | hadoop.hdfs.server.blockmanagement.TestBlockTokenWithDFSStriped |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-436/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/436 |
| Optional Tests | dupname asflicense pylint compile javac javadoc mvninstall mvnsite unit shadedclient |
| uname | Linux 1ff1bf1afcbe 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c7c7a88 |
| Default Java | 1.8.0_212 |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/2/artifact/out/branch-pylint-stderr.txt |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/2/artifact/out/patch-pylint-stderr.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/2/artifact/out/whitespace-eol.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/2/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/2/testReport/ |
| Max. process+thread count | 4233 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-examples . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/2/console |
| versions | git=2.7.4 maven=3.3.9 pylint=1.9.2 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for branch |
| +1 | mvninstall | 1035 | trunk passed |
| +1 | compile | 1043 | trunk passed |
| +1 | mvnsite | 871 | trunk passed |
| -1 | pylint | 1 | Error running pylint. Please check pylint stderr files. |
| +1 | shadedclient | 627 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 335 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for patch |
| +1 | mvninstall | 1049 | the patch passed |
| +1 | compile | 1028 | the patch passed |
| +1 | javac | 1028 | the patch passed |
| +1 | mvnsite | 834 | the patch passed |
| -1 | pylint | 2 | Error running pylint. Please check pylint stderr files. |
| +1 | pylint | 2 | There were no new pylint issues. |
| -1 | whitespace | 0 | The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| +1 | shadedclient | 637 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 358 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 8353 | root in the patch failed. |
| +1 | asflicense | 44 | The patch does not generate ASF License warnings. |
| | | 16448 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.datanode.TestLargeBlockReport |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-436/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/436 |
| Optional Tests | dupname asflicense pylint compile javac javadoc mvninstall mvnsite unit shadedclient |
| uname | Linux deb45512da14 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c2d00c8 |
| Default Java | 1.8.0_212 |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/3/artifact/out/branch-pylint-stderr.txt |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/3/artifact/out/patch-pylint-stderr.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/3/artifact/out/whitespace-eol.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/3/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/3/testReport/ |
| Max. process+thread count | 4206 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-examples . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/3/console |
| versions | git=2.7.4 maven=3.3.9 pylint=1.9.2 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 46 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 29 | Maven dependency ordering for branch |
| +1 | mvninstall | 1091 | trunk passed |
| +1 | compile | 1063 | trunk passed |
| +1 | mvnsite | 865 | trunk passed |
| -1 | pylint | 2 | Error running pylint. Please check pylint stderr files. |
| +1 | shadedclient | 620 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 344 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for patch |
| +1 | mvninstall | 1070 | the patch passed |
| +1 | compile | 1031 | the patch passed |
| +1 | javac | 1031 | the patch passed |
| +1 | mvnsite | 881 | the patch passed |
| -1 | pylint | 4 | Error running pylint. Please check pylint stderr files. |
| +1 | pylint | 4 | There were no new pylint issues. |
| -1 | whitespace | 0 | The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| +1 | shadedclient | 616 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 326 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 8282 | root in the patch failed. |
| +1 | asflicense | 56 | The patch does not generate ASF License warnings. |
| | | 16487 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.ha.TestBootstrapAliasmap |
|   | hadoop.hdfs.server.datanode.TestLargeBlockReport |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-436/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/436 |
| Optional Tests | dupname asflicense pylint compile javac javadoc mvninstall mvnsite unit shadedclient |
| uname | Linux 803eba3f0097 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 00b5a27 |
| Default Java | 1.8.0_212 |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/4/artifact/out/branch-pylint-stderr.txt |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/4/artifact/out/patch-pylint-stderr.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/4/artifact/out/whitespace-eol.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/4/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/4/testReport/ |
| Max. process+thread count | 3863 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-examples . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/4/console |
| versions | git=2.7.4 maven=3.3.9 pylint=1.9.2 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 21 | Maven dependency ordering for branch |
| +1 | mvninstall | 1045 | trunk passed |
| +1 | compile | 1041 | trunk passed |
| +1 | mvnsite | 858 | trunk passed |
| -1 | pylint | 2 | Error running pylint. Please check pylint stderr files. |
| +1 | shadedclient | 618 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 343 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 22 | Maven dependency ordering for patch |
| +1 | mvninstall | 1061 | the patch passed |
| +1 | compile | 1019 | the patch passed |
| +1 | javac | 1019 | the patch passed |
| +1 | mvnsite | 885 | the patch passed |
| -1 | pylint | 3 | Error running pylint. Please check pylint stderr files. |
| +1 | pylint | 4 | There were no new pylint issues. |
| -1 | whitespace | 0 | The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| +1 | shadedclient | 614 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 346 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 8281 | root in the patch failed. |
| +1 | asflicense | 44 | The patch does not generate ASF License warnings. |
| | | 16382 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.datanode.TestDirectoryScanner |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-436/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/436 |
| Optional Tests | dupname asflicense pylint compile javac javadoc mvninstall mvnsite unit shadedclient |
| uname | Linux 863f788176ee 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e356e4f |
| Default Java | 1.8.0_222 |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/5/artifact/out/branch-pylint-stderr.txt |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/5/artifact/out/patch-pylint-stderr.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/5/artifact/out/whitespace-eol.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/5/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/5/testReport/ |
| Max. process+thread count | 4489 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-examples . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/5/console |
| versions | git=2.7.4 maven=3.3.9 pylint=1.9.2 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 38 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 21 | Maven dependency ordering for branch |
| +1 | mvninstall | 1048 | trunk passed |
| +1 | compile | 1096 | trunk passed |
| +1 | mvnsite | 841 | trunk passed |
| -1 | pylint | 2 | Error running pylint. Please check pylint stderr files. |
| +1 | shadedclient | 616 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 330 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 20 | Maven dependency ordering for patch |
| +1 | mvninstall | 1079 | the patch passed |
| +1 | compile | 1023 | the patch passed |
| +1 | javac | 1023 | the patch passed |
| +1 | mvnsite | 885 | the patch passed |
| -1 | pylint | 4 | Error running pylint. Please check pylint stderr files. |
| +1 | pylint | 4 | There were no new pylint issues. |
| -1 | whitespace | 0 | The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| +1 | shadedclient | 598 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 344 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 8385 | root in the patch failed. |
| +1 | asflicense | 52 | The patch does not generate ASF License warnings. |
| | | 16514 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.TestFsck |
|   | hadoop.hdfs.server.namenode.TestNameNodeMetadataConsistency |
|   | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-436/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/436 |
| Optional Tests | dupname asflicense pylint compile javac javadoc mvninstall mvnsite unit shadedclient |
| uname | Linux be129facd38c 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 094d736 |
| Default Java | 1.8.0_222 |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/6/artifact/out/branch-pylint-stderr.txt |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/6/artifact/out/patch-pylint-stderr.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/6/artifact/out/whitespace-eol.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/6/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/6/testReport/ |
| Max. process+thread count | 5190 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-examples . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/6/console |
| versions | git=2.7.4 maven=3.3.9 pylint=1.9.2 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by cclauss** [comment]
DO ACTUAL HUMANS WORK ON THIS PROJECT??  THE BOT DOES NOT SEEM TO UNDERSTAND THAT FIXING A SYNTAX ERROR IS A GOOD THING!!!

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 25 | Maven dependency ordering for branch |
| +1 | mvninstall | 1125 | trunk passed |
| +1 | compile | 1050 | trunk passed |
| +1 | mvnsite | 1003 | trunk passed |
| -1 | pylint | 2 | Error running pylint. Please check pylint stderr files. |
| +1 | shadedclient | 695 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 383 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 29 | Maven dependency ordering for patch |
| +1 | mvninstall | 1148 | the patch passed |
| +1 | compile | 991 | the patch passed |
| +1 | javac | 991 | the patch passed |
| +1 | mvnsite | 936 | the patch passed |
| -1 | pylint | 3 | Error running pylint. Please check pylint stderr files. |
| +1 | pylint | 3 | There were no new pylint issues. |
| -1 | whitespace | 0 | The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| +1 | shadedclient | 703 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 357 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 8830 | root in the patch failed. |
| +1 | asflicense | 61 | The patch does not generate ASF License warnings. |
| | | 17541 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.tools.TestDFSZKFailoverController |
|   | hadoop.hdfs.server.balancer.TestBalancer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-436/8/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/436 |
| Optional Tests | dupname asflicense pylint compile javac javadoc mvninstall mvnsite unit shadedclient |
| uname | Linux 669c1261dc41 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3329257 |
| Default Java | 1.8.0_222 |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/8/artifact/out/branch-pylint-stderr.txt |
| pylint | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/8/artifact/out/patch-pylint-stderr.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/8/artifact/out/whitespace-eol.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/8/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/8/testReport/ |
| Max. process+thread count | 3770 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-examples . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-436/8/console |
| versions | git=2.7.4 maven=3.3.9 pylint=1.9.2 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by cclauss** [comment]
NONSENSE!!!

**Pull request closed without merging**
