### PR TITLE
HADOOP-16515. Update the link to compatibility guide

### PR DESCRIPTION
**Pull request by hotcodemacha**
### Description of PR
HADOOP-16515. Update the link to compatibility guide

* JIRA: HADOOP-16515

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 42s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  buf  |   0m  0s |  |  buf was not available.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 53s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  28m 39s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  26m 22s |  |  trunk passed with JDK Ubuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  compile  |  22m 49s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  mvnsite  |   8m 43s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  | 125m  4s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 32s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 11s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  24m 59s |  |  the patch passed with JDK Ubuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04  |
| -1 :x: |  cc  |  24m 59s | [/results-compile-cc-root-jdkUbuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4226/1/artifact/out/results-compile-cc-root-jdkUbuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04.txt) |  root-jdkUbuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04 with JDK Ubuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04 generated 12 new + 311 unchanged - 12 fixed = 323 total (was 323)  |
| +1 :green_heart: |  javac  |  24m 59s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  24m 14s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| -1 :x: |  cc  |  24m 14s | [/results-compile-cc-root-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4226/1/artifact/out/results-compile-cc-root-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt) |  root-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 generated 10 new + 313 unchanged - 10 fixed = 323 total (was 323)  |
| +1 :green_heart: |  javac  |  24m 14s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   9m 15s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  30m 47s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  19m  3s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 12s |  |  hadoop-hdfs-client in the patch passed.  |
| +1 :green_heart: |  unit  | 253m  1s |  |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 11s |  |  hadoop-yarn-api in the patch passed.  |
| +1 :green_heart: |  unit  |   4m  0s |  |  hadoop-yarn-server-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m  0s |  |  The patch does not generate ASF License warnings.  |
|  |   | 497m 21s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4226/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4226 |
| Optional Tests | dupname asflicense compile cc mvnsite javac unit buflint bufcompat codespell |
| uname | Linux 27a1747c6abb 4.15.0-169-generic #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 4ac9808354469b2bb821e1a93d2a005f0f5f46b2 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4226/1/testReport/ |
| Max. process+thread count | 3477 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4226/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hotcodemacha** [comment]
@aajisaka, @tomscut - Can you please review this. Thanks.

**Review by aajisaka — CHANGES_REQUESTED** [review]
Hi @ashutoshcipher - thank you for your PR. Would you use `https` instead of `http`?

**Comment by hotcodemacha** [comment]
> Hi @ashutoshcipher - thank you for your PR. Would you use `https` instead of `http`?

@aajisaka - Thanks for the review. I have addressed your comment.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 44s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  buf  |   0m  0s |  |  buf was not available.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 58s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  27m 23s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  25m 39s |  |  trunk passed with JDK Ubuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  compile  |  22m 49s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  mvnsite  |   8m 31s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  | 122m  4s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 52s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  24m 36s |  |  the patch passed with JDK Ubuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04  |
| -1 :x: |  cc  |  24m 36s | [/results-compile-cc-root-jdkUbuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4226/2/artifact/out/results-compile-cc-root-jdkUbuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04.txt) |  root-jdkUbuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04 with JDK Ubuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04 generated 19 new + 304 unchanged - 19 fixed = 323 total (was 323)  |
| +1 :green_heart: |  javac  |  24m 36s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  21m 20s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| -1 :x: |  cc  |  21m 20s | [/results-compile-cc-root-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4226/2/artifact/out/results-compile-cc-root-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt) |  root-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 generated 37 new + 286 unchanged - 37 fixed = 323 total (was 323)  |
| +1 :green_heart: |  javac  |  21m 20s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   7m 50s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  29m 29s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  18m 42s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   3m  5s |  |  hadoop-hdfs-client in the patch passed.  |
| +1 :green_heart: |  unit  | 265m 23s |  |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  7s |  |  hadoop-yarn-api in the patch passed.  |
| +1 :green_heart: |  unit  |   4m  0s |  |  hadoop-yarn-server-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 57s |  |  The patch does not generate ASF License warnings.  |
|  |   | 500m 54s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4226/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4226 |
| Optional Tests | dupname asflicense compile cc mvnsite javac unit buflint bufcompat codespell |
| uname | Linux 010098b15223 4.15.0-169-generic #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / b862b5289e96f87d3c1f6b2d9b613388a4f65b99 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.14.1+1-Ubuntu-0ubuntu1.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4226/2/testReport/ |
| Max. process+thread count | 3776 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4226/2/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hotcodemacha** [comment]
@aajisaka - Can you please look at this? Thanks

**Review by aajisaka — APPROVED** [review]
+1

**Comment by aajisaka** [comment]
Merged. Thank you @ashutoshcipher

**Pull request merged**
