### PR TITLE
HDFS-15883. Add a metric BlockReportQueueFullCount

### PR DESCRIPTION
**Pull request by tomscut**
JIRA: [HDFS-15883](https://issues.apache.org/jira/browse/HDFS-15883)

Add a metric that reflects the number of times the block report queue is full

### CODE REVIEW

**Comment by tomscut** [comment]
Failed junit tests:
hadoop.hdfs.server.datanode.fsdataset.impl.TestFsDatasetImpl 
hadoop.hdfs.server.balancer.TestBalancer 

Those failed unit tests were unrelated to the change, and they worked fine locally.

**Comment by Hexiaoqiao** [comment]
Thanks @tomscut for your work. IIUC, there has been one metric for number of blockReports and blockReceivedAndDeleted queued, please refer to `org.apache.hadoop.hdfs.server.namenode.metrics.NameNodeMetrics#blockOpsQueued`, is it helpful for you?

**Comment by tomscut** [comment]
Thanks @Hexiaoqiao for your advice. This metric org.apache.hadoop.hdfs.server.namenode.metrics.NameNodeMetrics#blockOpsQueued can reflect the length of the block report queue.

**Comment by Hexiaoqiao** [comment]
Close this PR since there is another metric which can solve this issues. Please feel free to reopen it if any other consideration. Thanks.

**Comment by tomscut** [comment]
> Close this PR since there is another metric which can solve this issues. Please feel free to reopen it if any other consideration. Thanks.

Thanks @Hexiaoqiao .

**Pull request closed without merging**
