### PR TITLE
HDFS-16317 : Backport HDFS-14729 for branch-3.2

### PR DESCRIPTION
**Pull request by AnanyaSingh2121**
### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by AnanyaSingh2121** [comment]
This patch updates the Bootstrap and jQuery versions used by different HDFS UIs like Namenode web UI, Datanode web UI etc. for branch-3,2

Bootstrap 3.3.7 -> 3.4.1
jQuery 3.3.1 -> 3.4.1

Testing done:
I tested the patch locally by bringing up HDFS in a pseudo distributed mode and manually browsing through UI components in localhost and made sure that there are no compatibility issues or errors thrown in the browser console. And I did not see any major change in the UI presentation as well.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  12m 21s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  jshint  |   0m  1s |  |  jshint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 35s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  29m 56s |  |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |  19m 55s |  |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |  20m 11s |  |  branch-3.2 passed  |
| +1 :green_heart: |  javadoc  |   7m 40s |  |  branch-3.2 passed  |
| +1 :green_heart: |  shadedclient  |  98m 34s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  27m 50s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  19m  4s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  19m  4s |  |  the patch passed  |
| -1 :x: |  blanks  |   0m  0s | [/blanks-tabs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3692/1/artifact/out/blanks-tabs.txt) |  The patch 2 line(s) with tabs.  |
| +1 :green_heart: |  mvnsite  |  17m 13s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  2s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   7m 36s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  25m  1s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 295m 37s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3692/1/artifact/out/patch-unit-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m  3s |  |  The patch does not generate ASF License warnings.  |
|  |   | 499m 36s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.TestAddOverReplicatedStripedBlocks |
|   | hadoop.hdfs.TestLeaseRecovery2 |
|   | hadoop.hdfs.server.namenode.TestFsck |
|   | hadoop.hdfs.server.blockmanagement.TestBlockTokenWithShortCircuitRead |
|   | hadoop.hdfs.qjournal.server.TestJournalNodeSync |
|   | hadoop.hdfs.TestBlockStoragePolicy |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3692/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3692 |
| Optional Tests | dupname asflicense codespell shadedclient compile javac javadoc mvninstall mvnsite unit xml jshint |
| uname | Linux ab7694e0918f 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / 0cfafb8bba15d7794498d4f7c7f1b7b34ab56c9d |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3692/1/testReport/ |
| Max. process+thread count | 2060 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-rbf . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3692/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by brahmareddybattula** [comment]
@AnanyaSingh2121  Can you add the jira id in the commit message.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  16m 12s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  jshint  |   0m  1s |  |  jshint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 29s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  26m  7s |  |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |  16m 42s |  |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |  17m 17s |  |  branch-3.2 passed  |
| +1 :green_heart: |  javadoc  |   6m 59s |  |  branch-3.2 passed  |
| +1 :green_heart: |  shadedclient  |  86m 26s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  22m 45s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  15m 37s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  15m 37s |  |  the patch passed  |
| -1 :x: |  blanks  |   0m  0s | [/blanks-tabs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3692/2/artifact/out/blanks-tabs.txt) |  The patch 2 line(s) with tabs.  |
| +1 :green_heart: |  mvnsite  |  13m 33s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   6m  2s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  20m 54s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 291m 13s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3692/2/artifact/out/patch-unit-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 59s |  |  The patch does not generate ASF License warnings.  |
|  |   | 470m 17s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestRollingUpgrade |
|   | hadoop.hdfs.TestBlockStoragePolicy |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3692/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3692 |
| Optional Tests | dupname asflicense codespell shadedclient compile javac javadoc mvninstall mvnsite unit xml jshint |
| uname | Linux 767f73910b96 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / 96559de29e1ba7f4161194a68d2ad7d93b3df95e |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3692/2/testReport/ |
| Max. process+thread count | 2635 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-rbf . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3692/2/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by brahmareddybattula** [comment]
lgtm..thanks @AnanyaSingh2121 for contribution.

**Comment by brahmareddybattula** [comment]
+1

**Pull request merged**
