### PR TITLE
MAPREDUCE-7234. Fixed typo in isSplitable methods

### PR DESCRIPTION
**Pull request by HorizonNet**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 69 | Maven dependency ordering for branch |
| +1 | mvninstall | 1043 | trunk passed |
| +1 | compile | 984 | trunk passed |
| +1 | checkstyle | 191 | trunk passed |
| +1 | mvnsite | 183 | trunk passed |
| +1 | shadedclient | 1117 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 145 | trunk passed |
| 0 | spotbugs | 47 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 228 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 27 | Maven dependency ordering for patch |
| +1 | mvninstall | 114 | the patch passed |
| +1 | compile | 933 | the patch passed |
| +1 | javac | 933 | the patch passed |
| -0 | checkstyle | 153 | root: The patch generated 16 new + 264 unchanged - 4 fixed = 280 total (was 268) |
| +1 | mvnsite | 177 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 696 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 146 | the patch passed |
| +1 | findbugs | 261 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 334 | hadoop-mapreduce-client-core in the patch passed. |
| -1 | unit | 7178 | hadoop-mapreduce-client-jobclient in the patch failed. |
| +1 | unit | 81 | hadoop-dynamometer-workload in the patch passed. |
| +1 | unit | 66 | hadoop-dynamometer-blockgen in the patch passed. |
| -1 | asflicense | 68 | The patch generated 1 ASF License warnings. |
| | | 14182 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1450/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1450 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux a2072548055d 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e04b8a4 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1450/1/artifact/out/diff-checkstyle-root.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1450/1/artifact/out/patch-unit-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-jobclient.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1450/1/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-1450/1/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 1585 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-workload hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-blockgen U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1450/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 25 | Maven dependency ordering for branch |
| +1 | mvninstall | 1030 | trunk passed |
| +1 | compile | 973 | trunk passed |
| +1 | checkstyle | 150 | trunk passed |
| +1 | mvnsite | 176 | trunk passed |
| +1 | shadedclient | 1054 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 141 | trunk passed |
| 0 | spotbugs | 46 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 224 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 24 | Maven dependency ordering for patch |
| +1 | mvninstall | 114 | the patch passed |
| +1 | compile | 939 | the patch passed |
| +1 | javac | 939 | the patch passed |
| +1 | checkstyle | 149 | root: The patch generated 0 new + 264 unchanged - 4 fixed = 264 total (was 268) |
| +1 | mvnsite | 179 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 685 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 144 | the patch passed |
| +1 | findbugs | 259 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 336 | hadoop-mapreduce-client-core in the patch passed. |
| -1 | unit | 7227 | hadoop-mapreduce-client-jobclient in the patch failed. |
| +1 | unit | 82 | hadoop-dynamometer-workload in the patch passed. |
| +1 | unit | 62 | hadoop-dynamometer-blockgen in the patch passed. |
| -1 | asflicense | 67 | The patch generated 1 ASF License warnings. |
| | | 14079 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1450/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1450 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 23ead62b7169 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 85b1c72 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1450/2/artifact/out/patch-unit-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-jobclient.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1450/2/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-1450/2/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 1557 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-workload hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-blockgen U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1450/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by HorizonNet** [comment]
According to Jenkins there are no failing tests. The license problems seems to be in a generated build file.

**Comment by steveloughran** [comment]
-1, with the reason being "yes, we agree its wrong, but its out in the wild and we are trapped"

FileInputFormat is tagged as public/stable and we just can't change it. Not without breaking every custom input format which overrides it, or every application which also looks at the values (spark, hive, tez, ...)

Sorry. We feel your pain, it irritates us all too much. But it's like most of the windows APIs: once you ship something broadly used, you are stuck with it.

**Comment by HorizonNet** [comment]
@steveloughran Totally understand it. How about closing this PR, as well as the underlying Jira ticket?

**Comment by steveloughran** [comment]
yeah, just wanted to bear the bad news. Moral: have an IDE with spell checking

**Pull request closed without merging**
