### PR TITLE
HDDS-1455. Inconsistent naming convention with Ozone Kerberos configu…

### PR DESCRIPTION
**Pull request by xiaoyuyao**

### CODE REVIEW

**Comment by anuengineer** [comment]
+1, pending jenkins. Thanks for fixing this.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 26 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 26 | Maven dependency ordering for branch |
| +1 | mvninstall | 1028 | trunk passed |
| +1 | compile | 1067 | trunk passed |
| +1 | checkstyle | 137 | trunk passed |
| +1 | mvnsite | 164 | trunk passed |
| +1 | shadedclient | 669 | branch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-hdds/docs hadoop-ozone/dist |
| +1 | findbugs | 83 | trunk passed |
| +1 | javadoc | 105 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 26 | Maven dependency ordering for patch |
| -1 | mvninstall | 19 | dist in the patch failed. |
| +1 | compile | 1083 | the patch passed |
| +1 | javac | 1083 | the patch passed |
| +1 | checkstyle | 143 | the patch passed |
| +1 | mvnsite | 123 | the patch passed |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 31 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 668 | patch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-hdds/docs hadoop-ozone/dist |
| +1 | findbugs | 91 | the patch passed |
| +1 | javadoc | 108 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 94 | common in the patch failed. |
| +1 | unit | 32 | docs in the patch passed. |
| +1 | unit | 34 | dist in the patch passed. |
| +1 | asflicense | 43 | The patch does not generate ASF License warnings. |
| | | 6160 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.scm.net.TestNodeSchemaManager |
|   | hadoop.hdds.scm.net.TestNetworkTopologyImpl |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-762/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/762 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  xml  shellcheck  shelldocs  |
| uname | Linux a10b4104e3e5 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 59ded76 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
| findbugs | v3.1.0-RC1 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-762/1/artifact/out/patch-mvninstall-hadoop-ozone_dist.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-762/1/artifact/out/patch-unit-hadoop-hdds_common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-762/1/testReport/ |
| Max. process+thread count | 446 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-hdds/docs hadoop-ozone/dist U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-762/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by xiaoyuyao** [comment]
The unit test failure does not seem right. ozone.scm.network.topology.schema.file.type has been removed last week. Not sure why this is still being reported.

**Pull request merged**
