### PR TITLE
HADOOP-16146. Make start-build-env.sh safe in case of misusage of DOCKER_INTERACTIVE_RUN.

### PR DESCRIPTION
**Pull request by elek**
See: https://issues.apache.org/jira/browse/HADOOP-16146

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 26 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1007 | trunk passed |
| +1 | mvnsite | 781 | trunk passed |
| +1 | shadedclient | 647 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 998 | the patch passed |
| +1 | mvnsite | 758 | the patch passed |
| +1 | shellcheck | 0 | The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
| +1 | shelldocs | 17 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 616 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 1058 | root in the patch passed. |
| +1 | asflicense | 48 | The patch does not generate ASF License warnings. |
| | | 6070 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-516/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/516 |
| Optional Tests |  dupname  asflicense  mvnsite  unit  shellcheck  shelldocs  |
| uname | Linux 3d9c839900b3 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 6cec906 |
| maven | version: Apache Maven 3.3.9 |
| shellcheck | v0.4.6 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/1/testReport/ |
| Max. process+thread count | 445 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 86 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 0 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1148 | trunk passed |
| +1 | mvnsite | 949 | trunk passed |
| +1 | shadedclient | 719 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 1353 | the patch passed |
| +1 | mvnsite | 1048 | the patch passed |
| +1 | shellcheck | 0 | The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 845 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 1346 | root in the patch passed. |
| +1 | asflicense | 65 | The patch does not generate ASF License warnings. |
| | | 7686 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-516/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/516 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux 0825e3214ee6 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / cd967c7 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/2/testReport/ |
| Max. process+thread count | 306 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 1 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1124 | trunk passed |
| +1 | mvnsite | 932 | trunk passed |
| +1 | shadedclient | 653 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 1075 | the patch passed |
| +1 | mvnsite | 924 | the patch passed |
| +1 | shellcheck | 0 | The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 641 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 1156 | root in the patch passed. |
| +1 | asflicense | 51 | The patch does not generate ASF License warnings. |
| | | 6714 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-516/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/516 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux 2242d02a02d1 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c7c7a88 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/3/testReport/ |
| Max. process+thread count | 412 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/3/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 46 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 1 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1058 | trunk passed |
| +1 | mvnsite | 875 | trunk passed |
| +1 | shadedclient | 693 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 1094 | the patch passed |
| +1 | mvnsite | 843 | the patch passed |
| +1 | shellcheck | 1 | The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
| +1 | whitespace | 1 | The patch has no whitespace issues. |
| +1 | shadedclient | 630 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 1197 | root in the patch passed. |
| +1 | asflicense | 43 | The patch does not generate ASF License warnings. |
| | | 6596 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-516/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/516 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux 57c191835861 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e20b195 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/4/testReport/ |
| Max. process+thread count | 414 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/4/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 64 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 0 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1076 | trunk passed |
| +1 | mvnsite | 866 | trunk passed |
| +1 | shadedclient | 630 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 1049 | the patch passed |
| +1 | mvnsite | 849 | the patch passed |
| +1 | shellcheck | 0 | The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 642 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 1212 | root in the patch passed. |
| +1 | asflicense | 48 | The patch does not generate ASF License warnings. |
| | | 6549 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-516/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/516 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux cb1a71d91950 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / b0131bc |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/5/testReport/ |
| Max. process+thread count | 442 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/5/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 0 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1083 | trunk passed |
| +1 | mvnsite | 832 | trunk passed |
| +1 | shadedclient | 599 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 1093 | the patch passed |
| +1 | mvnsite | 884 | the patch passed |
| +1 | shellcheck | 0 | The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 648 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 1275 | root in the patch passed. |
| +1 | asflicense | 48 | The patch does not generate ASF License warnings. |
| | | 6615 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-516/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/516 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux a19d924aedb4 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e356e4f |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/6/testReport/ |
| Max. process+thread count | 445 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/6/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 0 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1144 | trunk passed |
| +1 | mvnsite | 965 | trunk passed |
| +1 | shadedclient | 663 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 1120 | the patch passed |
| +1 | mvnsite | 890 | the patch passed |
| +1 | shellcheck | 0 | The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 689 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 1191 | root in the patch passed. |
| +1 | asflicense | 62 | The patch does not generate ASF License warnings. |
| | | 6877 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-516/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/516 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux 622740445ffc 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 094d736 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/7/testReport/ |
| Max. process+thread count | 412 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/7/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 44 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 1 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1077 | trunk passed |
| +1 | mvnsite | 864 | trunk passed |
| +1 | shadedclient | 647 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 1084 | the patch passed |
| +1 | mvnsite | 892 | the patch passed |
| +1 | shellcheck | 1 | The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 672 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 1152 | root in the patch passed. |
| +1 | asflicense | 44 | The patch does not generate ASF License warnings. |
| | | 6595 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-516/8/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/516 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux 34de98c5f5d5 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 69ddb36 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/8/testReport/ |
| Max. process+thread count | 448 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/8/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 43 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 0 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1070 | trunk passed |
| +1 | mvnsite | 909 | trunk passed |
| +1 | shadedclient | 711 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 1261 | the patch passed |
| +1 | mvnsite | 943 | the patch passed |
| +1 | shellcheck | 0 | The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 681 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 1153 | root in the patch passed. |
| +1 | asflicense | 58 | The patch does not generate ASF License warnings. |
| | | 6960 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-516/9/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/516 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux 9bda1ae23b06 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3329257 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/9/testReport/ |
| Max. process+thread count | 444 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/9/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 40 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 0 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1097 | trunk passed |
| +1 | mvnsite | 861 | trunk passed |
| +1 | shadedclient | 701 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 1081 | the patch passed |
| +1 | mvnsite | 874 | the patch passed |
| +1 | shellcheck | 0 | The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 683 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 1147 | root in the patch passed. |
| +1 | asflicense | 53 | The patch does not generate ASF License warnings. |
| | | 6670 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-516/10/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/516 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux ed18027806cf 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 915cbc9 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/10/testReport/ |
| Max. process+thread count | 446 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-516/10/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by elek** [comment]
Looks like nobody is interested about this change.

**Pull request closed without merging**
