### PR TITLE
HADOOP-16938. Make non-HA proxy providers pluggable

### PR DESCRIPTION
**Pull request by RogPodge**
Adds the following improvements: 
https://issues.apache.org/jira/browse/HADOOP-16938

### CODE REVIEW

**Comment by goiri** [comment]
This is the refactor needed for HADOOP-16543.
That was already reviewed.
I'll wait for the Yetus results and merge once that's +1.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  24m 32s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   1m 10s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  19m 26s |  trunk passed  |
| +1 :green_heart: |  compile  |   8m  1s |  trunk passed  |
| +1 :green_heart: |  checkstyle  |   1m 35s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 28s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  18m 43s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 14s |  trunk passed  |
| +0 :ok: |  spotbugs  |   0m 34s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   0m 33s |  branch/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site no findbugs output file (findbugsXml.xml)  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 31s |  the patch passed  |
| +1 :green_heart: |  compile  |   7m 27s |  the patch passed  |
| +1 :green_heart: |  javac  |   7m 27s |  the patch passed  |
| -0 :warning: |  checkstyle  |   1m 32s |  hadoop-yarn-project/hadoop-yarn: The patch generated 4 new + 208 unchanged - 0 fixed = 212 total (was 208)  |
| +1 :green_heart: |  mvnsite  |   2m 16s |  the patch passed  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  14m 24s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 13s |  the patch passed  |
| +0 :ok: |  findbugs  |   0m 30s |  hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site has no data from findbugs  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 12s |  hadoop-yarn-api in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 48s |  hadoop-yarn-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 27s |  hadoop-yarn-site in the patch passed.  |
| -1 :x: |  asflicense  |   0m 53s |  The patch generated 1 ASF License warnings.  |
|  |   | 121m 39s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1913/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1913 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml markdownlint |
| uname | Linux 079fbb0b2611 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / d353b30 |
| Default Java | 1.8.0_242 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1913/1/artifact/out/diff-checkstyle-hadoop-yarn-project_hadoop-yarn.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-1913/1/artifact/out/whitespace-eol.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1913/1/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-1913/1/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 422 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site U: hadoop-yarn-project/hadoop-yarn |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1913/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 59s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   1m 18s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  20m 51s |  trunk passed  |
| -1 :x: |  compile  |   1m 38s |  hadoop-yarn in trunk failed.  |
| +1 :green_heart: |  checkstyle  |   1m 23s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 57s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  19m  8s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 41s |  trunk passed  |
| +0 :ok: |  spotbugs  |   0m 20s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   0m 20s |  branch/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site no findbugs output file (findbugsXml.xml)  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 35s |  the patch passed  |
| +1 :green_heart: |  compile  |   8m 32s |  the patch passed  |
| -1 :x: |  javac  |   8m 32s |  hadoop-yarn-project_hadoop-yarn generated 99 new + 233 unchanged - 0 fixed = 332 total (was 233)  |
| -0 :warning: |  checkstyle  |   1m 28s |  hadoop-yarn-project/hadoop-yarn: The patch generated 4 new + 208 unchanged - 0 fixed = 212 total (was 208)  |
| +1 :green_heart: |  mvnsite  |   2m 16s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  14m 48s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m  8s |  the patch passed  |
| +0 :ok: |  findbugs  |   0m 27s |  hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site has no data from findbugs  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 59s |  hadoop-yarn-api in the patch passed.  |
| +1 :green_heart: |  unit  |   4m  3s |  hadoop-yarn-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 21s |  hadoop-yarn-site in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 41s |  The patch does not generate ASF License warnings.  |
|  |   |  95m 47s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1913/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1913 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml markdownlint |
| uname | Linux 7b727ea62350 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / d353b30 |
| Default Java | 1.8.0_242 |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1913/2/artifact/out/branch-compile-hadoop-yarn-project_hadoop-yarn.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-1913/2/artifact/out/diff-compile-javac-hadoop-yarn-project_hadoop-yarn.txt |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1913/2/artifact/out/diff-checkstyle-hadoop-yarn-project_hadoop-yarn.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1913/2/testReport/ |
| Max. process+thread count | 94 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site U: hadoop-yarn-project/hadoop-yarn |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1913/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by goiri** [comment]
I'll ignore the 4 left checkstyle issues as they are the same as in ConfiguredRMFailoverProxyProvider, so let's keep it as is for consistency.

**Pull request merged**
