### PR TITLE
Fix see also links to point at markdown files and not html files

### PR DESCRIPTION
**Pull request by AndrewLane**
https://issues.apache.org/jira/browse/HADOOP-16799

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 34s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  18m 12s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 38s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  31m 15s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 32s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 32s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  13m 20s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 31s |  The patch does not generate ASF License warnings.  |
|  |   |  48m 28s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1802/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1802 |
| Optional Tests | dupname asflicense mvnsite markdownlint |
| uname | Linux 0bf1d741de76 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 93233a7 |
| Max. process+thread count | 412 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-aws U: hadoop-tools/hadoop-aws |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1802/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by n-marion** [comment]
Hello @AndrewLane , although I am not the one to review your code changes; Find information for contributing to the Apache Hadoop project at this [link](https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute). Additionally, ASF JIRA is the Apache Software Foundation JIRA, which the Hadoop Project can be found [here](https://issues.apache.org/jira/projects/HADOOP). 

_Just a little helpful information from one new contributor to another._

**Comment by AndrewLane** [comment]
> Hello @AndrewLane , although I am not the one to review your code changes; Find information for contributing to the Apache Hadoop project at this [link](https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute). Additionally, ASF JIRA is the Apache Software Foundation JIRA, which the Hadoop Project can be found [here](https://issues.apache.org/jira/projects/HADOOP).
> 
> _Just a little helpful information from one new contributor to another._

Thanks, seems obvious now that you've linked me.  Thanks!  I've created a ticket here: https://issues.apache.org/jira/browse/HADOOP-16799

**Comment by iwasakims** [comment]
@AndrewLane, docs are expected to be built by `mvn site`.  Those links looks valid on [built documentation](https://hadoop.apache.org/docs/r3.2.1/hadoop-aws/tools/hadoop-aws/index.html).

**Comment by AndrewLane** [comment]
@iwasakims so it is expected that internet users that stumble upon the GitHub repo first would have a less-than-desirable experience?

**Comment by iwasakims** [comment]
I think most of users could find built docs (having auto-generated in-page TOC) by googling "hadoop documentation". While rendering on github (made available after format migration from APT to Markdown) is useful for developers, those *.md are source files optimised for compilation by maven-site-plugin.

**Comment by AndrewLane** [comment]
Thank you for the explanation.  I will close this PR.

**Pull request closed without merging**
