### PR TITLE
YARN-11734. [BackPort] Fix spotbugs in ServiceScheduler#load.

### PR DESCRIPTION
**Pull request by zhtttylz**
JIRA: YARN-11734. Fix spotbugs in ServiceScheduler#load. (#7088)

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  12m 47s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ branch-3.4 Compile Tests _ |
| +1 :green_heart: |  shadedclient  |  41m 13s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  shadedclient  |  34m 41s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 37s |  |  The patch does not generate ASF License warnings.  |
|  |   |  91m  2s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7204/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/7204 |
| Optional Tests | dupname asflicense codespell detsecrets xmllint |
| uname | Linux 3c829ecfa052 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.4 / e49f11e1a1ac067d5546b78d89e5a6c9cf80452f |
| Max. process+thread count | 553 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services U: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7204/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by slfan1989** [comment]
LGTM.

**Review by slfan1989 — APPROVED** [review]

**Review by slfan1989 — APPROVED** [review]

**Comment by slfan1989** [comment]
@zhtttylz Thank you for your contribution! The pr has been merged into branch-3.4. If this is a backport pr, it's recommended to include the Git link to the related pr in the description.

**Comment by zhtttylz** [comment]
Thanks @slfan1989 help review and merged.

**Pull request merged**
