### PR TITLE
HADOOP-17776. The java agent args should be passed as the VM arguments

### PR DESCRIPTION
**Pull request by jiwq**
Some java agents or maven plugins want works well, must pass the agent arguments as the VM arguments, such as JaCoCo etc.

PS. Use the JaCoco to generate the code coverage data and put into SonarQube.

See also: https://issues.apache.org/jira/browse/HADOOP-17776

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  8s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  12m 41s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  22m 48s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  22m 34s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |  19m  6s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  mvnsite  |   8m 32s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   6m 30s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   7m 48s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  shadedclient  | 116m 22s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 22s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 51s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  21m 57s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |  21m 57s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  19m  5s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |  19m  5s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   8m 31s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m 13s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   6m 28s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   7m 51s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  shadedclient  |  31m 55s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 26s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 21s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 36s |  |  hadoop-registry in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 27s |  |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 40s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 34s |  |  hadoop-federation-balance in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 53s |  |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 50s |  |  hadoop-yarn-applications-catalog-webapp in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 49s |  |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 46s |  |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 47s |  |  The patch does not generate ASF License warnings.  |
|  |   | 218m 32s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3147/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3147 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml |
| uname | Linux 481436f7f671 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 42bc5acc3808c907348a3d052a5d3ef90ae2fa64 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3147/1/testReport/ |
| Max. process+thread count | 529 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-hdfs-project/hadoop-hdfs hadoop-tools/hadoop-distcp hadoop-tools/hadoop-federation-balance hadoop-hdfs-project/hadoop-hdfs-rbf hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-catalog/hadoop-yarn-applications-catalog-webapp hadoop-tools/hadoop-aws hadoop-tools/hadoop-azure U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3147/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by jiwq** [comment]
@aajisaka @jojochuang Could u help to review this patch? In some systems select the JaCoCo to generate the code coverage report, so I think this patch is needed.

**Comment by aajisaka** [comment]
Thank you @jiwq. I'm +1 for adding `@{argLine}`.

I prefer adding `@{argLine}` to `maven-surefire-plugin.argLine` and use them rather than adding it in every setting. That way the change can be smaller. However, the parameter `maven-surefire-plugin.argLine` is not honored in some modules, so we can create a separate jira to use the parameter everywhere.

**Comment by jiwq** [comment]
@aajisaka Thanks for your review. I agree with your opinion and I can try to refactor the `maven-surefire-plugin.argLine` in a separate jira.

**Pull request closed without merging**
