### PR TITLE
HADOOP-18026. Fix default value of Magic committer

### PR DESCRIPTION
**Pull request by GuoPhilipse**
`fs.s3a.committer.magic.enabled` was set to true by default after HADOOP-17483, we can improve the doc

### CODE REVIEW

**Review by steveloughran — APPROVED** [review]
+1

**Comment by steveloughran** [comment]
merging to trunk; will pull into 3.3 once I've got that building locally

**Comment by steveloughran** [comment]
oh, before I merge, what do you want as your name in the "contributed by" line?

**Comment by GuoPhilipse** [comment]
> oh, before I merge, what do you want as your name in the "contributed by" line?

 Thanks @steveloughran for your review, you can call me `guophilipse` as the jira username :)

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 49s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  33m 12s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 50s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  54m 56s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 41s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 37s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  22m 17s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 34s |  |  The patch does not generate ASF License warnings.  |
|  |   |  80m 57s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3723/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3723 |
| Optional Tests | dupname asflicense mvnsite codespell markdownlint |
| uname | Linux 23c7a1bbe834 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / eeada777d0562a9996a58336aad9b5eeee1d718c |
| Max. process+thread count | 671 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-aws U: hadoop-tools/hadoop-aws |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3723/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by GuoPhilipse** [comment]
@steveloughran need i now close the JIRA or will you operate?

**Comment by steveloughran** [comment]
I've closed it and pulled it into 3.3.3; for some reason I can't assign it to you even though I've tried to add you to the contributors group. Sorry. I'm having a hard time with JIRA right now.

**Comment by GuoPhilipse** [comment]
> I've closed it and pulled it into 3.3.3; for some reason I can't assign it to you even though I've tried to add you to the contributors group. Sorry. I'm having a hard time with JIRA right now.

Thanks @steveloughran  for your merge, i just reopened the JIRA trying to assign to myself, it seems still not working with me , anyway ,it does not matter ,Could you help resolve the JIRA again ?

**Comment by steveloughran** [comment]
i've broken a collar bone and can only type by setting my keyboard up to have left hand qwerty keys on the right when i press ALT. this and dictation is ok for email, slack and JIRA messages-but not any complex JIRA work, eg autocompleting fields, admin etc. 

ask again in january when my left hand should be working again.I'm going off-line now until then anyway.

**Comment by GuoPhilipse** [comment]
I‘am so sorry to hear that, Thanks for your notice me the info . really hope you are getting well soon.

**Pull request merged**
