### PR TITLE
HADOOP-17182. Remove breadcrumbs from web site

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/HADOOP-17182

After:
Screen Shot 2020-08-04 at 18 07 29

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  3s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 15s |  root in trunk failed.  |
| +1 :green_heart: |  mvnsite  |   0m 12s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  16m 13s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 11s |  hadoop-project in the patch failed.  |
| +1 :green_heart: |  mvnsite  |   0m 12s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  15m 22s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 27s |  The patch does not generate ASF License warnings.  |
|  |   |  35m 10s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2190/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2190 |
| Optional Tests | dupname asflicense mvnsite xml |
| uname | Linux a652c0b47b3f 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e072d33327b |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2190/1/artifact/out/branch-mvninstall-root.txt |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2190/1/artifact/out/patch-mvninstall-hadoop-project.txt |
| Max. process+thread count | 296 (vs. ulimit of 5500) |
| modules | C: hadoop-project U: hadoop-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2190/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by ayushtkn** [comment]
`After removing it, when we click one left menu, is it straightforward to tell the current version from the page/header?`
Do you mean to say, the Hadoop Version? If so, It would be still there on the right side.
![image](https://user-images.githubusercontent.com/25608848/89677414-092c7e80-d90b-11ea-8b08-0c7d9fe27691.png

Can't say how much prominent it is....

**Comment by liuml07** [comment]
Thank you @ayushtkn Yes that's what I was asking. Since we still have the information clearly in the page, I guess the change to remove the dead link makes more sense.

**Comment by aajisaka** [comment]
Thank you @liuml07 and @ayushtkn

**Pull request merged**
