### PR TITLE
HADOOP-17297. Use Yetus before YETUS-994 to enable adding comments to GitHub

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/HADOOP-17297

Use https://github.com/apache/yetus/tree/6ab19e71eaf3234863424c6f684b34c1d3dcc0ce

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  29m 46s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  shadedclient  |  20m 40s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 16s |  |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  14m 25s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 39s |  |  The patch does not generate ASF License warnings.  |
|  |   |  67m 33s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2359/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2359 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 8e11be4b792d 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / d0d10f7e8f9 |
| Max. process+thread count | 442 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2359/1/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by tasanuma — APPROVED** [review]
Thanks for investigating the issue, @aajisaka.
Considering JDK11, I think this is the best way for now. +1.

**Comment by aajisaka** [comment]
Thank you @tasanuma for your review.

**Comment by aajisaka** [comment]
Ping @ayushtkn @iwasakims

**Review by ayushtkn — APPROVED** [review]
Thanx @aajisaka for fixing this.
+1

**Review by iwasakims — APPROVED** [review]
+1

**Comment by aajisaka** [comment]
Thank you @ayushtkn and @iwasakims

**Pull request merged**
