### PR TITLE
HDDS-2348.Remove log4j properties for org.apache.hadoop.ozone

### PR DESCRIPTION
**Pull request by chimney-lee**

### CODE REVIEW

**Comment by dineshchitlangia** [comment]
@chimney-lee Thank you for filing the jira and the PR.
Could you please share more details as per this template so it will help the reviewers to understand your proposed change?

What changes were proposed in this pull request?
What is the link to the Apache JIRA?
How was this patch tested?

For an example, you can refer: https://github.com/apache/hadoop-ozone/pull/59#issue-329722893

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| -1 | mvninstall | 42 | hadoop-hdds in trunk failed. |
| -1 | mvninstall | 44 | hadoop-ozone in trunk failed. |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 921 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 34 | hadoop-hdds in the patch failed. |
| -1 | mvninstall | 39 | hadoop-ozone in the patch failed. |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 748 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| -1 | unit | 26 | hadoop-hdds in the patch failed. |
| -1 | unit | 25 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 33 | The patch does not generate ASF License warnings. |
| | | 1995 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1666/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1666 |
| Optional Tests | dupname asflicense mvnsite unit |
| uname | Linux 94c7d0dc0be0 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 19f35cf |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1666/1/artifact/out/branch-mvninstall-hadoop-hdds.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1666/1/artifact/out/branch-mvninstall-hadoop-ozone.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1666/1/artifact/out/patch-mvninstall-hadoop-hdds.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1666/1/artifact/out/patch-mvninstall-hadoop-ozone.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1666/1/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1666/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1666/1/testReport/ |
| Max. process+thread count | 464 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/dist U: hadoop-ozone/dist |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1666/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
Hi @chimney-lee 
Would you create a PR for https://github.com/apache/hadoop-ozone instead of this repository?

**Comment by chimney-lee** [comment]
> Hi @chimney-lee
> Would you create a PR for https://github.com/apache/hadoop-ozone instead of this repository?
@dineshchitlangia  @aajisaka  https://github.com/apache/hadoop-ozone/pull/74 new PR created and details are attached. Thanks for advice;   By the way , @aajisaka  Could you help me have a look at this PR for MAPREDUCE https://github.com/apache/hadoop/pull/1618 ,thanks a lot.

**Comment by aajisaka** [comment]
Thanks @chimney-lee for creating a PR for hadoop-ozone repo. Closing this.

**Pull request closed without merging**
