### PR TITLE
HADOOP-18773. Upgrade maven-shade-plugin to 3.4.1

### PR DESCRIPTION
**Pull request by rohit-kb**
### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 41s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  37m  3s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   0m 24s |  |  trunk passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1  |
| +1 :green_heart: |  compile  |   0m 27s |  |  trunk passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09  |
| +1 :green_heart: |  mvnsite  |   0m 32s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   0m 37s |  |  trunk passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1  |
| +1 :green_heart: |  javadoc  |   0m 29s |  |  trunk passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09  |
| +1 :green_heart: |  shadedclient  |  60m 59s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 17s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 16s |  |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1  |
| +1 :green_heart: |  javac  |   0m 16s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 15s |  |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09  |
| +1 :green_heart: |  javac  |   0m 15s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 18s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 17s |  |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1  |
| +1 :green_heart: |  javadoc  |   0m 18s |  |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09  |
| +1 :green_heart: |  shadedclient  |  34m 42s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 21s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 43s |  |  The patch does not generate ASF License warnings.  |
|  |   | 101m 52s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5750/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5750 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint |
| uname | Linux f9a55b35e206 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / fb5d0f2c6c1fbe8578edceebdd97307e450e0719 |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu120.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5750/1/testReport/ |
| Max. process+thread count | 700 (vs. ulimit of 5500) |
| modules | C: hadoop-project U: hadoop-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5750/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by rohit-kb** [comment]
@ayushtkn thanks for the review, Please merge this PR too if possible as I don't have the write access for this repo.

**Comment by pan3793** [comment]
I found another issue related to the shade plugin. Not sure if the upgrading helps.

The shaded client's generated source jar is incorrect, making it hard to debug on IDE.

hadoop-client-api:3.3.5 as example

image

**Comment by pan3793** [comment]
cc @jojochuang @sunchao

**Comment by rohit-kb** [comment]
@pan3793 I am not sure how to verify if the issue is resolved with this upgrade. I think we can merge this PR since there are no blockers. 
If the issue is still there after the upgrade, we can raise a new jira for the same.

**Comment by ayushtkn** [comment]
whats the plan here? anyone has any comments? or should we merge this, I don't think this induces any new bugs or issues? Let me know your thoughts, if anyone wants me to hold merging this

**Comment by steveloughran** [comment]
+1 for the merge. 

Regarding the problem is about source mismatch with the generated jars, AFAIK shaded binaries have that problem as the published source doesn't get rewritten. Any large shaded artifact (hello aws-sdk.jar) has this issue, at least in my experience.

@pan3793 sorry about this, but I don't know how to fix it. I normally actually have the source trees of big projects, though that has its own problems.

**Review by steveloughran — APPROVED** [review]

**Comment by steveloughran** [comment]
merged to trunk.

@rohit-kb can you do a PR against branch 3.3 so we can merge it there too. thanks

**Comment by pan3793** [comment]
@steveloughran How do you think reverting HADOOP-16822? IMO, a wrong generated source jar is worse than none, at least the IDEA can jump correctly with de-compile when no source jar is associated.

**Comment by rohit-kb** [comment]
Thanks @steveloughran for the merge!. We can continue the remainder of the discussion initiated by pan3793 here. Meanwhile, I will try to create a PR for branch-3.3 too. Thanks again, Everyone!

**Comment by steveloughran** [comment]
> How do you think reverting [HADOOP-16822](https://issues.apache.org/jira/browse/HADOOP-16822)? IMO, a wrong generated source jar is worse than none, at least the IDEA can jump correctly with de-compile when no source jar is associated.

best to have that discussion on the jira, not a PR which hasn't caused the problem.

**Pull request merged**
