### PR TITLE
HADOOP-18779. Improve hadoop-function.sh#status script.

### PR DESCRIPTION
**Pull request by slfan1989**
### Description of PR
JIRA: HADOOP-18779. Improve hadoop-function.sh#status script.

When We use `yarn --daemon status router/nodemanager`, I found that no information can be displayed. I checked the script and modified the script of `hadoop-functions.sh#status` to increase the output information.

`yarn --daemon status router`

- If the service is started, the following information will be printed.

```
router is running as process 47626.
```

- If the service is stop, the following information will be printed.

```
router is stopped.
```

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  0s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| -1 :x: |  mvninstall  |  12m 14s | [/branch-mvninstall-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5762/1/artifact/out/branch-mvninstall-root.txt) |  root in trunk failed.  |
| +1 :green_heart: |  mvnsite  |   1m 33s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  30m 53s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 30s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   1m 56s |  |  the patch passed  |
| -1 :x: |  shellcheck  |   0m  5s | [/results-shellcheck.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5762/1/artifact/out/results-shellcheck.txt) |  The patch generated 1 new + 26 unchanged - 0 fixed = 27 total (was 26)  |
| +1 :green_heart: |  shadedclient  |  24m 14s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 35s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 39s |  |  The patch does not generate ASF License warnings.  |
|  |   |  79m 58s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5762/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5762 |
| Optional Tests | dupname asflicense mvnsite unit codespell detsecrets shellcheck shelldocs |
| uname | Linux 3402a667840c 4.15.0-212-generic #223-Ubuntu SMP Tue May 23 13:09:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / d9d95b402d352152729df8c33585d6d07765dd75 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5762/1/testReport/ |
| Max. process+thread count | 536 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5762/1/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by goiri** [comment]
I wonder if not outputting anything was done by design.
I can see the case for a daemon not outputting anything.

**Comment by slfan1989** [comment]
> I wonder if not outputting anything was done by design.
> I can see the case for a daemon not outputting anything.

Thanks for your explanation! I will use this command again in the test environment.

**Comment by slfan1989** [comment]
@goiri I have carefully read the code related to the `--daemon` and conducted experiments in a testing environment.

The daemon of hdfs/yarn contains 3 operations, namely start|status|stop

- hdfs --daemon start namenode

When starting the namenode, we can use the command `hdfs --daemon start namenode`, which initiates the namenode without generating any output information. I believe this behavior is appropriate.

image

- hdfs --daemon status namenode

When utilizing the `hdfs --daemon status namenode` command, I still expect it to provide some information regarding the namenode's status. Nevertheless, I have noticed that executing this command does not yield any output.

image

I have added some output information for the `status` command.

 - If the service is in a running state.
image

- If the service is in a stopped state.

image

This modification only affects the `status` command of the daemon and does not have any impact on the `start` or `stop` commands.

**Review by goiri — APPROVED** [review]

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  7s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  52m 31s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 30s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  37m 19s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 59s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   1m 18s |  |  the patch passed  |
| -1 :x: |  shellcheck  |   0m  4s | [/results-shellcheck.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5762/2/artifact/out/results-shellcheck.txt) |  The patch generated 1 new + 26 unchanged - 0 fixed = 27 total (was 26)  |
| +1 :green_heart: |  shadedclient  |  37m 37s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 35s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 36s |  |  The patch does not generate ASF License warnings.  |
|  |   | 138m 57s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5762/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5762 |
| Optional Tests | dupname asflicense mvnsite unit codespell detsecrets shellcheck shelldocs |
| uname | Linux 2bea028ff82b 4.15.0-212-generic #223-Ubuntu SMP Tue May 23 13:09:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / b1ce3d5bc81ad17b8dcd2e6d250b4c0127ee5642 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5762/2/testReport/ |
| Max. process+thread count | 530 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5762/2/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by goiri — APPROVED** [review]

**Comment by slfan1989** [comment]
@goiri Thank you very much for your help in reviewing the code!

**Pull request merged**
