### PR TITLE
HADOOP-16109. Parquet reading S3AFileSystem causes EOF

### PR DESCRIPTION
**Pull request by steveloughran**
Nobody gets seek right. No matter how many times they think they have.

Reproducible test from: Dave Christianson
Fixed seek() logic: Steve Loughran

Change-Id: I268bfcb39ed2626b7281c793d8123f62d8d30caa

### CODE REVIEW

**Comment by steveloughran** [comment]
branch-2 variant; hadoop-aws tests all happy exccept for: all the S3n tests which were upset at the lack of a test field and the DDB lifecycle one failing when the container is pay-per-request. Unrelated.

```
 testDynamoDBInitDestroyCycle(org.apache.hadoop.fs.s3a.s3guard.ITestS3GuardToolDynamoDB)  Time elapsed: 18.179 s  <<< ERROR!
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: One or more parameter values were invalid: Neither ReadCapacityUnits nor WriteCapacityUnits can be specified when BillingMode is PAY_PER_REQUEST (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: J4B2L7CSQAGEF9LD028G4T8ACVVV4KQNSO5AEMVJF66Q9ASUAAJG)
```

Main change from the branch-3.0 patch is the move from lambda to java-7 lang callable & marking more things as final

**Comment by steveloughran** [comment]
Interesting: Yetus isn't seeing these. Any suggestions Mr @aw-was-here ? Some special keyword I can use to kick-off a build?

**Comment by aw-was-here** [comment]
> Yetus isn't seeing these. 

Nope, Jenkins isn't seeing this branch because it doesn't have a Jenkinsfile:

https://builds.apache.org/view/H-L/view/Hadoop/job/hadoop-multibranch/view/change-requests/

Rebase, rebase, rebase.

**Comment by steveloughran** [comment]
this was only a cherry pick, so I fixed by rerunning tests locally till I was happy.

**Pull request closed without merging**
