### PR TITLE
Rebase Access Point feature onto branch-3.3

### PR DESCRIPTION
**Pull request by bogthe**
Rebased Access Point feature (the 2 new commits `648a7ff329d7458d97e8b04461ccdf56eab3456a` and `e234d31af24a375f3942e5ac147ed54e6587dc0f`) onto `branch-3.3` right before the AWS SDK upgrade. Was hoping for a quick `cherry-pick` but there's changes that come into effect with removal S3 guard which conflict so placed it before that. 

Apologies if this isn't the right way to do it! Let me know if there's anything else I can do.

Also created a PR that picks this AcessPoint feature straight into 3.3.2, which might be of help https://github.com/apache/hadoop/pull/3955 

@sunchao @steveloughran

### CODE REVIEW

**Comment by sunchao** [comment]
This seems too disruptive. @bogthe is there anyway we can resolve the conflicts due to the removal of s3guard?

**Comment by bogthe** [comment]
@sunchao not really. Whatever you resolve you can't then pick onto 3.3.2 since the changes you apply onto `3.3` need to be modified because of the S3 Guard removal.

The only non-distruptive way is to pick straight into 3.3.2 like this PR is trying to do https://github.com/apache/hadoop/pull/3955

**Comment by sunchao** [comment]
I see. I'm slightly in favor of putting this in branch-3.3 for now, and then release it in Hadoop 3.3.3. What do you think?

My apologies that I didn't realize the matter is a bit complex due to the difference between branch-3.3 and branch-3.3.2. Since at this point we're wrapping up the release of 3.3.2, I'd prefer to avoid extra complexities which could delay the release further.

**Comment by steveloughran** [comment]
the 3.3.2 fix isn't that big, it's that because the s3guard removal is in branch-3.3, there's a bit more toe stepping going on there

**Comment by bogthe** [comment]
> the 3.3.2 fix isn't that big, it's that because the s3guard removal is in branch-3.3, there's a bit more toe stepping going on there

@sunchao would like to close this PR and use Steve's new one (basically does the thing this one intended to 😄 )

**Comment by steveloughran** [comment]
closing this.

**Comment by sunchao** [comment]
Oh cool, thanks @steveloughran !

**Comment by steveloughran** [comment]
merged the other one in

**Pull request closed without merging**
