### PR TITLE
HADOOP-16453. Remove useless trace log in NetUtils.java

### PR DESCRIPTION
**Pull request by leosunli**
Signed-off-by: sunlisheng <sunlisheng@xiaomi.com>

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1186 | trunk passed |
| +1 | compile | 1045 | trunk passed |
| +1 | checkstyle | 40 | trunk passed |
| +1 | mvnsite | 69 | trunk passed |
| +1 | shadedclient | 728 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 55 | trunk passed |
| 0 | spotbugs | 120 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 118 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 47 | the patch passed |
| +1 | compile | 998 | the patch passed |
| +1 | javac | 998 | the patch passed |
| +1 | checkstyle | 37 | the patch passed |
| +1 | mvnsite | 74 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 621 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 55 | the patch passed |
| +1 | findbugs | 117 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 520 | hadoop-common in the patch passed. |
| +1 | asflicense | 39 | The patch does not generate ASF License warnings. |
| | | 5853 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1149/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1149 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux f207b3afca04 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / aebac6d |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1149/1/testReport/ |
| Max. process+thread count | 1471 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1149/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 137 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1434 | trunk passed |
| +1 | compile | 1083 | trunk passed |
| +1 | checkstyle | 43 | trunk passed |
| +1 | mvnsite | 83 | trunk passed |
| +1 | shadedclient | 879 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 65 | trunk passed |
| 0 | spotbugs | 129 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 127 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 51 | the patch passed |
| +1 | compile | 1050 | the patch passed |
| +1 | javac | 1050 | the patch passed |
| +1 | checkstyle | 43 | the patch passed |
| +1 | mvnsite | 80 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 743 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 66 | the patch passed |
| +1 | findbugs | 139 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 606 | hadoop-common in the patch passed. |
| +1 | asflicense | 45 | The patch does not generate ASF License warnings. |
| | | 6748 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1149/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1149 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux db12c9c8eeae 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / b94eba9 |
| Default Java | 1.8.0_222 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1149/2/testReport/ |
| Max. process+thread count | 1375 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1149/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 53 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1112 | trunk passed |
| +1 | compile | 1181 | trunk passed |
| +1 | checkstyle | 41 | trunk passed |
| +1 | mvnsite | 70 | trunk passed |
| +1 | shadedclient | 753 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 61 | trunk passed |
| 0 | spotbugs | 114 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 113 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 44 | the patch passed |
| +1 | compile | 1018 | the patch passed |
| +1 | javac | 1018 | the patch passed |
| +1 | checkstyle | 36 | the patch passed |
| +1 | mvnsite | 66 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 653 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 59 | the patch passed |
| +1 | findbugs | 128 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 558 | hadoop-common in the patch passed. |
| +1 | asflicense | 44 | The patch does not generate ASF License warnings. |
| | | 6053 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1149/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1149 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 6a5b907901b3 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 70b4617 |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1149/3/testReport/ |
| Max. process+thread count | 1407 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1149/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
Looks like this one is abandoned, superseded by PR #1231

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 86 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1191 | trunk passed |
| +1 | compile | 1198 | trunk passed |
| +1 | checkstyle | 49 | trunk passed |
| +1 | mvnsite | 93 | trunk passed |
| +1 | shadedclient | 979 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 81 | trunk passed |
| 0 | spotbugs | 146 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 144 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 59 | the patch passed |
| +1 | compile | 1107 | the patch passed |
| +1 | javac | 1107 | the patch passed |
| +1 | checkstyle | 49 | the patch passed |
| +1 | mvnsite | 84 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 755 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 67 | the patch passed |
| +1 | findbugs | 137 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 632 | hadoop-common in the patch passed. |
| +1 | asflicense | 67 | The patch does not generate ASF License warnings. |
| | | 6855 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1149/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1149 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux c94a1a209e7a 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 397a563 |
| Default Java | 1.8.0_222 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1149/4/testReport/ |
| Max. process+thread count | 1378 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1149/4/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
