### PR TITLE
HADOOP-18178. Upgrade jackson to 2.13.2 and jackson-databind to 2.13.…

### PR DESCRIPTION
**Pull request by aajisaka**
### Description of PR

Backport HADOOP-18178 to branch-3.3 to upgrade jackson

### How was this patch tested?

No manual testing

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- n/a Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- n/a If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  12m  2s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |   5m  7s |  |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |  36m 17s | [/branch-mvninstall-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/1/artifact/out/branch-mvninstall-root.txt) |  root in branch-3.3 failed.  |
| +1 :green_heart: |  compile  |  20m 37s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  26m 11s |  |  branch-3.3 passed  |
| -1 :x: |  javadoc  |   6m 27s | [/branch-javadoc-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/1/artifact/out/branch-javadoc-root.txt) |  root in branch-3.3 failed.  |
| +1 :green_heart: |  shadedclient  |  30m 56s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 35s |  |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |  24m 31s | [/patch-mvninstall-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/1/artifact/out/patch-mvninstall-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  compile  |  17m 45s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  17m 45s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  20m 55s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   7m 28s | [/patch-javadoc-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/1/artifact/out/patch-javadoc-root.txt) |  root in the patch failed.  |
| -1 :x: |  shadedclient  |  32m 32s |  |  patch has errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 701m  1s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/1/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 20s |  |  The patch does not generate ASF License warnings.  |
|  |   | 932m 45s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.yarn.applications.distributedshell.TestDistributedShell |
|   | hadoop.hdfs.server.balancer.TestBalancer |
|   | hadoop.hdfs.tools.offlineImageViewer.TestOfflineImageViewer |
|   | hadoop.hdfs.TestReconstructStripedFileWithRandomECPolicy |
|   | hadoop.hdfs.TestRollingUpgrade |
|   | hadoop.hdfs.TestReconstructStripedFileWithValidator |
|   | hadoop.hdfs.server.federation.router.TestRouterRpcMultiDestination |
|   | hadoop.hdfs.server.federation.router.TestRouterRpc |
|   | hadoop.yarn.sls.appmaster.TestAMSimulator |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4147 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml shellcheck shelldocs |
| uname | Linux 03a40102482c 4.15.0-153-generic #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 65b25b842990fa1af292bd1ae6ff3772258f30a8 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/1/testReport/ |
| Max. process+thread count | 2302 (vs. ulimit of 5500) |
| modules | C: hadoop-project . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/1/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
mvninstall is failing. https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/1/artifact/out/patch-mvninstall-root.txt
```
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-banned-dependencies) @ hadoop-client-check-test-invariants ---
[INFO] Adding ignorable dependency: org.apache.hadoop:hadoop-annotations:null
[INFO]   Adding ignore: *
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
Duplicate classes found:

  Found in:
    org.apache.hadoop:hadoop-client-minicluster:jar:3.3.3-SNAPSHOT:compile
    org.apache.hadoop:hadoop-client-runtime:jar:3.3.3-SNAPSHOT:compile
  Duplicate classes:
    META-INF/versions/9/module-info.class
```
We need to update the exclusion https://github.com/apache/hadoop/blob/160b6d106d501ee5c8ab1d2a0b3c1975c9a53839/hadoop-client-modules/hadoop-client-runtime/pom.xml#L249 because Jackson databind moved the module-info.class under `versions/9` instead of `versions/11`.

Reference: https://github.com/FasterXML/jackson-bom/pull/47

**Comment by aajisaka** [comment]
I'm not sure why the check passed in the PR for trunk: https://github.com/apache/hadoop/pull/4111

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 53s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |   5m  5s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  34m 50s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m  6s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  25m 21s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   7m 49s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  32m 31s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 35s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  33m 45s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 47s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  17m 47s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  21m  1s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  xml  |   0m  4s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   7m 32s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  32m 13s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 701m  8s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/2/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 22s |  |  The patch does not generate ASF License warnings.  |
|  |   | 927m  1s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.yarn.applications.distributedshell.TestDistributedShell |
|   | hadoop.yarn.server.nodemanager.amrmproxy.TestFederationInterceptor |
|   | hadoop.hdfs.tools.offlineImageViewer.TestOfflineImageViewer |
|   | hadoop.hdfs.server.balancer.TestBalancerWithHANameNodes |
|   | hadoop.hdfs.TestDecommissionWithStriped |
|   | hadoop.hdfs.server.federation.router.TestRouterRpcMultiDestination |
|   | hadoop.hdfs.server.federation.router.TestRouterRpc |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4147 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml shellcheck shelldocs |
| uname | Linux 7910a8799762 4.15.0-153-generic #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 1c026946e3e94ce3f4cdb83a727a78d2c16d2c38 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/2/testReport/ |
| Max. process+thread count | 2620 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-client-modules/hadoop-client-runtime hadoop-client-modules/hadoop-client-minicluster . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4147/2/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
Failed tests

### Ran successfully in my local
hadoop.yarn.server.nodemanager.amrmproxy.TestFederationInterceptor
hadoop.hdfs.server.balancer.TestBalancerWithHANameNodes
hadoop.hdfs.TestDecommissionWithStriped

### Reproduced even without the patch
hadoop.yarn.applications.distributedshell.TestDistributedShell
hadoop.hdfs.tools.offlineImageViewer.TestOfflineImageViewer -> Filed HDFS-16536
hadoop.hdfs.server.federation.router.TestRouterRpcMultiDestination
hadoop.hdfs.server.federation.router.TestRouterRpc

**Pull request merged**
