### PR TITLE
HADOOP-18912. Upgrade snappy-java to 1.1.10.4

### PR DESCRIPTION
**Pull request by rohit-kb**
### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m 18s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 35s |  |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |  38m  6s | [/branch-mvninstall-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/1/artifact/out/branch-mvninstall-root.txt) |  root in branch-3.3 failed.  |
| +1 :green_heart: |  compile  |  19m 11s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  26m 25s |  |  branch-3.3 passed  |
| -1 :x: |  javadoc  |   7m 11s | [/branch-javadoc-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/1/artifact/out/branch-javadoc-root.txt) |  root in branch-3.3 failed.  |
| -1 :x: |  shadedclient  |  42m 14s |  |  branch has errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 36s |  |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |  34m 57s | [/patch-mvninstall-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/1/artifact/out/patch-mvninstall-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  compile  |  18m  6s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  18m  6s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  22m 40s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| -1 :x: |  javadoc  |   7m  5s | [/patch-javadoc-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/1/artifact/out/patch-javadoc-root.txt) |  root in the patch failed.  |
| -1 :x: |  shadedclient  |  43m 50s |  |  patch has errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 312m 56s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/1/artifact/out/patch-unit-root.txt) |  root in the patch failed.  |
| -1 :x: |  asflicense  |   1m  2s | [/results-asflicense.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/1/artifact/out/results-asflicense.txt) |  The patch generated 25 ASF License warnings.  |
|  |   | 581m 35s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.fs.contract.router.web.TestRouterWebHDFSContractDelete |
|   | hadoop.fs.contract.router.TestRouterHDFSContractOpenSecure |
|   | hadoop.fs.contract.router.web.TestRouterWebHDFSContractAppend |
|   | hadoop.fs.contract.router.web.TestRouterWebHDFSContractRename |
|   | hadoop.fs.contract.router.TestRouterHDFSContractDelete |
|   | hadoop.fs.contract.router.TestRouterHDFSContractRootDirectory |
|   | hadoop.fs.contract.router.web.TestRouterWebHDFSContractConcat |
|   | hadoop.fs.contract.router.TestRouterHDFSContractConcat |
|   | hadoop.fs.contract.router.web.TestRouterWebHDFSContractRootDirectory |
|   | hadoop.fs.contract.router.TestRouterHDFSContractRename |
|   | hadoop.fs.contract.router.web.TestRouterWebHDFSContractSeek |
|   | hadoop.fs.contract.router.web.TestRouterWebHDFSContractCreate |
|   | hadoop.fs.contract.router.TestRouterHDFSContractRootDirectorySecure |
|   | hadoop.fs.contract.router.TestRouterHDFSContractAppendSecure |
|   | hadoop.fs.contract.router.web.TestRouterWebHDFSContractOpen |
|   | hadoop.fs.contract.router.TestRouterHDFSContractSetTimesSecure |
|   | hadoop.fs.contract.router.web.TestRouterWebHDFSContractMkdir |
|   | hadoop.fs.contract.router.TestRouterHDFSContractCreateSecure |
|   | hadoop.hdfs.server.balancer.TestBalancerWithHANameNodes |
|   | hadoop.hdfs.server.mover.TestMover |
|   | hadoop.yarn.util.resource.TestResourceCalculator |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6160 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint shellcheck shelldocs |
| uname | Linux ae99e61a7d51 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 01f4741bc3fda52cc4c19a0d9fbd56043e63f32c |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~18.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/1/testReport/ |
| Max. process+thread count | 3251 (vs. ulimit of 5500) |
| modules | C: hadoop-project . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/1/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m  0s |  |  Docker mode activated.  |
| -1 :x: |  patch  |   0m 22s |  |  https://github.com/apache/hadoop/pull/6160 does not apply to branch-3.3. Rebase required? Wrong Branch? See https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/6160 |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch-windows-10/job/PR-6160/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by pjfanning** [comment]
@rohit-kb your branch for this PR is missing a number of recent commits from the branch-3.3. Could you rebase to the latest  branch-3.3 code?

**Comment by pjfanning** [comment]
> @rohit-kb your branch for this PR is missing a number of recent commits from the branch-3.3. Could you rebase to the latest branch-3.3 code?

The missing commits include the one to fix the module-info.class issue (invariants testing).

**Comment by rohit-kb** [comment]
@pjfanning, sure, will do. Just give me sometime please and sorry for the delayed response as I was away. Thanks

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   7m 25s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 51s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  37m 50s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  19m 28s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  28m  9s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   7m 35s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  48m 17s |  |  branch has no errors when building and testing our client artifacts.  |
| -0 :warning: |  patch  |  48m 41s |  |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 36s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  37m 48s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 54s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  18m 54s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  23m 52s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   7m 34s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  47m  6s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 431m 37s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/2/artifact/out/patch-unit-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m 19s |  |  The patch does not generate ASF License warnings.  |
|  |   | 724m 42s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestLeaseRecoveryStriped |
|   | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |
|   | hadoop.hdfs.server.balancer.TestBalancerWithHANameNodes |
|   | hadoop.hdfs.server.sps.TestExternalStoragePolicySatisfier |
|   | hadoop.hdfs.tools.TestDFSAdmin |
|   | hadoop.hdfs.server.datanode.fsdataset.impl.TestFsDatasetImpl |
|   | hadoop.hdfs.server.namenode.ha.TestStandbyCheckpoints |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6160 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint shellcheck shelldocs |
| uname | Linux bc8507a74948 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 53e4660d3ede18eecacce1da7acb66bcc71449a3 |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~18.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/2/testReport/ |
| Max. process+thread count | 3731 (vs. ulimit of 5500) |
| modules | C: hadoop-project . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6160/2/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by aajisaka — APPROVED** [review]
Thank you for the backport

**Comment by rohit-kb** [comment]
Thanks for reviewing and merging this PR.

**Pull request merged**
