### PR TITLE
HDDS-1639. Restructure documentation pages for better understanding

### PR DESCRIPTION
**Pull request by elek**
Documentation page should be updated according to the recent changes:

In the uploaded PR I modified the following:

  *  Pages are restructured to use a similar structure what is intruced on the wiki by [~anu]. (Getting started guides are separated for different environments)
  * The width of the menu is increased (to make it more readable)
  * The logo is moved from the main page from the menu (to get more space for the menu items)
  * 'Requirements' section is added to each 'Getting started' page
  * Test tools / docker image / kubernetes pages are imported from the wiki. 

See: https://issues.apache.org/jira/browse/HDDS-1639

### CODE REVIEW

**Comment by elek** [comment]
> In ozone-usage.png , we use Aws logo. I am not sure we can legally use that logo in Apache Hadoop Ozone Documentation. Would it be possible to replace the logo with just normal words say "AWS", so it is text AWS S3 Protocol.

Sure, I replaced it with simple aws text (with using local fonts from linux)

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 904 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 2 | No case conflicting files found. |
| 0 | yamllint | 2 | yamllint was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 550 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1377 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 479 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 693 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 65 | The patch does not generate ASF License warnings. |
| | | 3709 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-901/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/901 |
| Optional Tests | dupname asflicense yamllint mvnsite |
| uname | Linux a62e3ff170a1 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 433e97c |
| Max. process+thread count | 411 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/docs U: hadoop-hdds/docs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-901/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 12 | https://github.com/apache/hadoop/pull/901 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/901 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-901/2/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 13 | https://github.com/apache/hadoop/pull/901 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/901 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-901/3/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 13 | https://github.com/apache/hadoop/pull/901 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/901 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-901/4/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 13 | https://github.com/apache/hadoop/pull/901 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/901 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-901/5/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 13 | https://github.com/apache/hadoop/pull/901 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/901 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-901/6/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by elek** [comment]
@anuengineer I merged your structure suggestions to the original PR.

I started to use short codes and generated breadcrumbs and "next" links based on the Hugo docs. 

The patch is ready to review.

**Comment by anuengineer** [comment]
There is also a Rat Check failure in the todo file, that is the only thing we should fix before committing this. Thx

**Comment by elek** [comment]
Thanks the review @anuengineer 

1. todo file is added accidentally, I will commit the patch without the todo

2. I started to use generated next buttons with the help of the `.NextSection` page variable (see https://gohugo.io/variables/page/) Which means that there is no next button at the last page of one section (one section = one subdirectory, eg. the security).

But, I agree, we can improve it further. As the content is restructured here, it will be easier to work on further improvements side by side (For example, I would like to write more k8s pages like csi/customization/persistence).

**Pull request closed without merging**
