### PR TITLE
Backport HADOOP-16830 to branch-3.3

### PR DESCRIPTION
**Pull request by steveloughran**
This a backport of the HADOOP-16830 chain of commits; getting yetus to do the some of the testing. Once I'm happy I'll merge this branch in locally

* 99d08a19ba5 G - HADOOP-17450. Add Public IOStatistics API. (#2577) (12 days ago)
* 0a6ddfa145b G - HADOOP-17272. ABFS Streams to support IOStatistics API (#2604)
* 9b2956e254d G - MAPREDUCE-7315. LocatedFileStatusFetcher to collect/publish IOStatistics. (#2579)
* 617af28e807 G - HADOOP-17271. S3A connector to support IOStatistics. (#2580)
* 724edb03544 G - HADOOP-17451. IOStatistics test failures in S3A code. (#2594)

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  24m 26s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 11 new or modified test files.  |
||| _ branch-3.3 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  34m 57s |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  15m 53s |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   0m 55s |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   1m 31s |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  17m 44s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  4s |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   2m 14s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 12s |  branch-3.3 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 53s |  the patch passed  |
| +1 :green_heart: |  compile  |  15m  7s |  the patch passed  |
| -1 :x: |  javac  |  15m  7s |  root generated 20 new + 1871 unchanged - 0 fixed = 1891 total (was 1871)  |
| -0 :warning: |  checkstyle  |   0m 53s |  hadoop-common-project/hadoop-common: The patch generated 4 new + 140 unchanged - 4 fixed = 144 total (was 144)  |
| +1 :green_heart: |  mvnsite  |   1m 28s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 14s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  3s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   2m 21s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   9m 30s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 54s |  The patch does not generate ASF License warnings.  |
|  |   | 147m 37s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2616 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle markdownlint |
| uname | Linux c54d19369b77 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 8204ad9 |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~16.04-b01 |
| javac | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/1/artifact/out/diff-compile-javac-root.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/1/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/1/testReport/ |
| Max. process+thread count | 1966 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
OK, patch #1 is in; this only has yetus tests

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  25m  1s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  3s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 11 new or modified test files.  |
||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m  1s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  29m 13s |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  16m  0s |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m 33s |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   2m 38s |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  25m 21s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 41s |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   1m 40s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   4m 18s |  branch-3.3 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 47s |  the patch passed  |
| +1 :green_heart: |  compile  |  20m 42s |  the patch passed  |
| -1 :x: |  javac  |  20m 42s |  root generated 20 new + 1871 unchanged - 0 fixed = 1891 total (was 1871)  |
| -0 :warning: |  checkstyle  |   3m 58s |  root: The patch generated 4 new + 143 unchanged - 4 fixed = 147 total (was 147)  |
| +1 :green_heart: |  mvnsite  |   2m 19s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 33s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 32s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   3m 43s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   9m 36s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 41s |  hadoop-mapreduce-client-core in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 51s |  The patch does not generate ASF License warnings.  |
|  |   | 177m 21s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2616 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle markdownlint |
| uname | Linux b5adb906aaa1 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 75f34a1 |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~16.04-b01 |
| javac | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/2/artifact/out/diff-compile-javac-root.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/2/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/2/testReport/ |
| Max. process+thread count | 1655 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
Local test runs of the last two patch
*  after HADOOP-17271: only the expected failures surfaced
*  add HADOOP-17451 and those go away

**Comment by steveloughran** [comment]
Test s3 london with `-Dparallel-tests -DtestsThreadCount=6 -Dscale -Dmarkers=keep -Ds3guard -Ddynamo -Dscale`

all good apart from that unbuffer intermittent failures, which I think are network related

```
[ERROR] testUnbufferBeforeRead(org.apache.hadoop.fs.contract.s3a.ITestS3AContractUnbuffer)  Time elapsed: 3.277 s  <<< FAILURE!
java.lang.AssertionError: failed to read expected number of bytes from stream. This may be transient expected:<1024> but was:<515>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
```

Unless yetus blows up, I will merge as is

**Comment by steveloughran** [comment]
build will fail until I commit a change that I had locally but not pushed up. hold on

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 45s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  6s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 55 new or modified test files.  |
||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 59s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  28m 56s |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  15m 46s |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   2m 45s |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   3m 18s |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  22m 35s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m  9s |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   1m 15s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   4m 40s |  branch-3.3 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 24s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   0m 20s |  hadoop-aws in the patch failed.  |
| -1 :x: |  compile  |  16m 18s |  root in the patch failed.  |
| -1 :x: |  javac  |  16m 18s |  root in the patch failed.  |
| -0 :warning: |  checkstyle  |   3m 15s |  root: The patch generated 5 new + 271 unchanged - 26 fixed = 276 total (was 297)  |
| -1 :x: |  mvnsite  |   0m 35s |  hadoop-aws in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  3s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  17m 43s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m  1s |  the patch passed  |
| -1 :x: |  findbugs  |   0m 33s |  hadoop-aws in the patch failed.  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  10m 14s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   6m  5s |  hadoop-mapreduce-client-core in the patch passed.  |
| -1 :x: |  unit  |   0m 33s |  hadoop-aws in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 45s |  The patch does not generate ASF License warnings.  |
|  |   | 151m 24s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2616 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle markdownlint xml |
| uname | Linux 31f9cad42156 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 75f34a1 |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~16.04-b01 |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/3/artifact/out/patch-mvninstall-hadoop-tools_hadoop-aws.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/3/artifact/out/patch-compile-root.txt |
| javac | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/3/artifact/out/patch-compile-root.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/3/artifact/out/diff-checkstyle-root.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/3/artifact/out/patch-mvnsite-hadoop-tools_hadoop-aws.txt |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/3/artifact/out/patch-findbugs-hadoop-tools_hadoop-aws.txt |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/3/artifact/out/patch-unit-hadoop-tools_hadoop-aws.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/3/testReport/ |
| Max. process+thread count | 2057 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core hadoop-tools/hadoop-aws U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 17s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  6s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 55 new or modified test files.  |
||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 59s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  29m 48s |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  16m  7s |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   2m 41s |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   3m  2s |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  22m  0s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m  1s |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   1m 11s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   4m 32s |  branch-3.3 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 59s |  the patch passed  |
| +1 :green_heart: |  compile  |  15m 23s |  the patch passed  |
| +1 :green_heart: |  javac  |  15m 23s |  root generated 0 new + 1870 unchanged - 1 fixed = 1870 total (was 1871)  |
| -0 :warning: |  checkstyle  |   2m 43s |  root: The patch generated 5 new + 271 unchanged - 26 fixed = 276 total (was 297)  |
| +1 :green_heart: |  mvnsite  |   2m 57s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  15m 33s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m  0s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   5m  2s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  10m 11s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 51s |  hadoop-mapreduce-client-core in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 43s |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 55s |  The patch does not generate ASF License warnings.  |
|  |   | 150m 33s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2616 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle markdownlint xml |
| uname | Linux 1d9a9b45b56d 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 75f34a1 |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~16.04-b01 |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/4/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/4/testReport/ |
| Max. process+thread count | 1519 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core hadoop-tools/hadoop-aws U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2616/4/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
manually merged each commit one by one, signing, pushed up.

**Comment by steveloughran** [comment]
so somehow we are missing changes to SemaphoredDelegatingExecutor which were in the base patch. joy

**Pull request closed without merging**
