### PR TITLE
Backport HDFS-16315 for branch-3.3

### PR DESCRIPTION
**Pull request by tomscut**
Backport [HDFS-16315](https://issues.apache.org/jira/browse/HDFS-16315) for branch-3.3.

### CODE REVIEW

**Comment by tasanuma** [comment]
@tomscut Thanks for creating the PR. +1, pending Jenkins.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   6m 36s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  markdownlint  |   0m  1s |  |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  12m 17s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  21m 25s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  17m 31s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   2m 42s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   3m 13s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   3m 28s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   5m 40s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  26m 17s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 11s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 45s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  17m 45s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   3m  6s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   3m 14s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   3m 27s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   6m 44s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  30m 23s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  18m 30s |  |  hadoop-common in the patch passed.  |
| -1 :x: |  unit  | 184m 31s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3666/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 12s |  |  The patch does not generate ASF License warnings.  |
|  |   | 368m 45s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3666/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3666 |
| Optional Tests | dupname asflicense mvnsite codespell markdownlint compile javac javadoc mvninstall unit shadedclient spotbugs checkstyle |
| uname | Linux 490befe54ee7 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 74e4360dca877cd823656c4ef9aafaffe1b73fd8 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3666/1/testReport/ |
| Max. process+thread count | 3192 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3666/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by tasanuma — APPROVED** [review]
The failed test is not related. +1.

**Comment by tasanuma** [comment]
Thanks for your contribution, @tomscut.

**Comment by tomscut** [comment]
> Thanks for your contribution, @tomscut.

Thanks for the merge.

**Comment by tasanuma** [comment]
Cherry-picked it to branch-3.2 with fixing a minor conflict.

**Comment by tomscut** [comment]
> Cherry-picked it to branch-3.2 with fixing a minor conflict.

Thanks for your help.

**Pull request merged**
