### PR TITLE
HADOOP-19065. Update Protocol Buffers installation to 3.21.12

### PR DESCRIPTION
**Pull request by huangzhaobo99**
### Description of PR
JIRA: https://issues.apache.org/jira/browse/HADOOP-19065

Instructions and docker script for installing protobuf updated from 3.7.1 to 3.21.12

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6576/1/console in case of problems.

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6576/2/console in case of problems.

**Comment by huangzhaobo99** [comment]
Message error, pushed twice, ignored.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   6m 52s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.4 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  32m  4s |  |  branch-3.4 passed  |
| +1 :green_heart: |  mvnsite  |  12m 56s |  |  branch-3.4 passed  |
| +1 :green_heart: |  shadedclient  |  18m 54s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  16m 54s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  hadolint  |   0m  6s |  |  No new issues.  |
| +1 :green_heart: |  mvnsite  |   8m  5s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  1s |  |  No new issues.  |
| +1 :green_heart: |  shadedclient  |  19m  0s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   8m 46s |  |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 40s |  |  The patch does not generate ASF License warnings.  |
|  |   | 127m 37s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6576/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6576 |
| Optional Tests | dupname asflicense codespell detsecrets hadolint shellcheck shelldocs mvnsite unit |
| uname | Linux 36fc733834eb 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.4 / 6015e99bf73c9c3815d1dd63050c08aa4ccc5494 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6576/2/testReport/ |
| Max. process+thread count | 559 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6576/2/console |
| versions | git=2.25.1 maven=3.6.3 hadolint=1.11.1-0-g0e692dd shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   6m 57s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  shelldocs  |   0m  1s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.4 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  32m 58s |  |  branch-3.4 passed  |
| +1 :green_heart: |  mvnsite  |  13m  8s |  |  branch-3.4 passed  |
| +1 :green_heart: |  shadedclient  |  19m 36s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  18m 27s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  hadolint  |   0m  7s |  |  No new issues.  |
| +1 :green_heart: |  mvnsite  |   8m 37s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  shadedclient  |  20m 47s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   9m  7s |  |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 35s |  |  The patch does not generate ASF License warnings.  |
|  |   | 133m 47s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6576/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6576 |
| Optional Tests | dupname asflicense codespell detsecrets hadolint shellcheck shelldocs mvnsite unit |
| uname | Linux decb70a57092 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.4 / 6015e99bf73c9c3815d1dd63050c08aa4ccc5494 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6576/1/testReport/ |
| Max. process+thread count | 675 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6576/1/console |
| versions | git=2.25.1 maven=3.6.3 hadolint=1.11.1-0-g0e692dd shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by slfan1989** [comment]
-1 

You don't need to submit such changes. After the release of hadoop-3.4.0, I will uniformly adjust the release compilation script.

**Comment by huangzhaobo99** [comment]
> -1
> 
> You don't need to submit such changes. After the release of [hadoop-3](https://issues.apache.org/jira/browse/HADOOP-3).4.0, I will uniformly adjust the release compilation script.

@slfan1989 Discussed in JIRA: https://issues.apache.org/jira/browse/HADOOP-19065 cc @steveloughran

**Comment by slfan1989** [comment]
> @slfan1989 Discussed in JIRA: https://issues.apache.org/jira/browse/HADOOP-19065 cc @steveloughran

I temporarily don't support porting this to the hadoop-3.4.0 branch. I've spent a lot of time setting up the compilation environment, and I don't want to introduce any additional issues.

**Comment by huangzhaobo99** [comment]
> > @slfan1989 Discussed in JIRA: https://issues.apache.org/jira/browse/HADOOP-19065 cc @steveloughran
> 
> I temporarily don't support porting this to the [hadoop-3](https://issues.apache.org/jira/browse/HADOOP-3).4.0 branch. I've spent a lot of time setting up the compilation environment, and I don't want to introduce any additional issues.

OK, understand.

**Comment by slfan1989** [comment]
> I temporarily don't support porting this to the [hadoop-3](https://issues.apache.org/jira/browse/HADOOP-3).4.0 branch. I've spent a lot of time setting up the compilation environment, and I don't want to introduce any additional issues.

I will try to use this change on the Centos 7.9 I prepared, including x86 & arm, and hope it goes well.

I will +1 if it passes.

**Comment by slfan1989** [comment]
While I'd like to do this after releasing hadoop-3.4.0,  @tasanuma makes a valid point. Since we already support protobuf 3.21.12 in hadoop-thirdparty 1.2.0, we should try to make this change now.

cc: @steveloughran

**Comment by steveloughran** [comment]
I concur

**Comment by steveloughran** [comment]
I've created https://issues.apache.org/jira/browse/HADOOP-19087 as the JIRA for follow-on stuff for 3.4.1, which is going to mainly be packaging/jar changes. let's target that one with this

**Review by slfan1989 — APPROVED** [review]

**Comment by slfan1989** [comment]
@huangzhaobo99 Thanks for the contribution! @steveloughran Thanks for the review!

**Comment by huangzhaobo99** [comment]
> @huangzhaobo99 Thanks for the contribution! @steveloughran Thanks for the review!

@slfan1989 Thanks for your verification and merging work, @steveloughran Thanks for your review.

**Pull request merged**
