### PR TITLE
HADOOP-17496. Install a supported version of pip

### PR DESCRIPTION
**Pull request by GauthamBanasandra**
* pip version 21 ended support for
  python 2.7. Thus we need to install
  a version of pip that supports
  python 2.7.

### CODE REVIEW

**Comment by GauthamBanasandra** [comment]
End of python2.7 support for pip 21 - https://github.com/pypa/pip/issues/9500.

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2653/1/console in case of problems.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  35m  1s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 15s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  shadedclient  |  19m 58s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 31s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  hadolint  |   0m  5s |  |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 13s |  |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  19m 35s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 38s |  |  The patch does not generate ASF License warnings.  |
|  |   |  92m 30s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2653/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2653 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs |
| uname | Linux 2228dcf032b9 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / e40f99f6d55 |
| Max. process+thread count | 514 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2653/1/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.0 hadolint=1.11.1-0-g0e692dd |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by GauthamBanasandra** [comment]
@aajisaka could you please review this PR?

**Review by aajisaka — APPROVED** [review]
+1

**Pull request merged**
