### PR TITLE
HDFS-15219. DFS Client will stuck when ResponseProcessor.run throw Error

### PR DESCRIPTION
**Pull request by esahekmat**

### CODE REVIEW

**Comment by ayushtkn** [comment]
Can we extend a UT for the issue?

**Comment by esahekmat** [comment]
I tried, but as ResponseProcessor class is a private inner class it's almost impossible to mock its behavior ( throw Error in the middle of run() method)
even I tried to mock block field to throw an Error when calling setNumBytes(), but as it's final and ExtendedBlock and BlockToWrite classes are very cautious to not expose their internal object it is impossible to inject my mock instead of their Block object.
can you help me to find a way to write its unit test?

**Comment by ayushtkn** [comment]
If there is no easy way out for the UT. I think it is Ok then.
Yetus isn't behaving the way it should, Let me check, if there aren't any complains for Jenkins.
This should be fair enough..

**Comment by ayushtkn** [comment]
> -1 overall
04:08:57  
04:08:57  | Vote |        Subsystem |  Runtime   | Comment
04:08:57  ============================================================================
04:08:57  |   0  |          reexec  |   0m 34s   | Docker mode activated. 
04:08:57  |      |                  |            | Prechecks 
04:08:57  |  +1  |         dupname  |   0m  0s   | No case conflicting files found. 
04:08:57  |  +1  |         @author  |   0m  0s   | The patch does not contain any @author 
04:08:57  |      |                  |            | tags.
04:08:57  |  -1  |      test4tests  |   0m  0s   | The patch doesn't appear to include 
04:08:57  |      |                  |            | any new or modified tests. Please
04:08:57  |      |                  |            | justify why no new tests are needed for
04:08:57  |      |                  |            | this patch. Also please list what
04:08:57  |      |                  |            | manual steps were performed to verify
04:08:57  |      |                  |            | this patch.
04:08:57  |      |                  |            | trunk Compile Tests 
04:08:57  |  +1  |      mvninstall  |  20m 13s   | trunk passed 
04:08:57  |  +1  |         compile  |   0m 48s   | trunk passed 
04:08:57  |  +1  |      checkstyle  |   0m 25s   | trunk passed 
04:08:57  |  +1  |         mvnsite  |   0m 51s   | trunk passed 
04:08:57  |  +1  |    shadedclient  |  14m 24s   | branch has no errors when building and 
04:08:57  |      |                  |            | testing our client artifacts.
04:08:57  |  +1  |         javadoc  |   0m 35s   | trunk passed 
04:08:57  |   0  |        spotbugs  |   2m 20s   | Used deprecated FindBugs config; 
04:08:57  |      |                  |            | considering switching to SpotBugs.
04:08:57  |  +1  |        findbugs  |   2m 18s   | trunk passed 
04:08:57  |      |                  |            | Patch Compile Tests 
04:08:57  |  +1  |      mvninstall  |   0m 46s   | the patch passed 
04:08:57  |  +1  |         compile  |   0m 43s   | the patch passed 
04:08:57  |  +1  |           javac  |   0m 43s   | the patch passed 
04:08:57  |  +1  |      checkstyle  |   0m 19s   | the patch passed 
04:08:57  |  +1  |         mvnsite  |   0m 45s   | the patch passed 
04:08:57  |  +1  |      whitespace  |   0m  0s   | The patch has no whitespace issues. 
04:08:57  |  +1  |    shadedclient  |  13m  9s   | patch has no errors when building and 
04:08:57  |      |                  |            | testing our client artifacts.
04:08:57  |  +1  |         javadoc  |   0m 29s   | the patch passed 
04:08:57  |  +1  |        findbugs  |   2m 17s   | the patch passed 
04:08:57  |      |                  |            | Other Tests 
04:08:57  |  +1  |            unit  |   2m  2s   | hadoop-hdfs-client in the patch 
04:08:57  |      |                  |            | passed.
04:08:57  |  +1  |      asflicense  |   0m 29s   | The patch does not generate ASF 
04:08:57  |      |                  |            | License warnings.
04:08:57  |      |                  |  63m 11s   | 
04:08:57  
04:08:57  
04:08:57  || Subsystem || Report/Notes ||
04:08:57  ============================================================================
04:08:57  | Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1902/1/artifact/out/Dockerfile |
04:08:57  | GITHUB PR | https://github.com/apache/hadoop/pull/1902 |
04:08:57  | Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
04:08:57  | uname | Linux 24c38dc308fc 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
04:08:57  | Build tool | maven |
04:08:57  | Personality | personality/hadoop.sh |
04:08:57  | git revision | trunk / f9bb2a8cc58 |
04:08:57  | Default Java | 1.8.0_242 |
04:08:57  |  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1902/1/testReport/ |
04:08:57  | Max. process+thread count | 424 (vs. ulimit of 5500) |
04:08:57  | modules | C: hadoop-hdfs-project/hadoop-hdfs-client U: hadoop-hdfs-project/hadoop-hdfs-client |
04:08:57  | Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1902/1/console |
04:08:57  | versions | git=2.17.1 maven=3.6.0[m findbugs=3.1.0-RC1 |
04:08:57  | Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |

**Pull request merged**
