### PR TITLE
HADOOP-17097. start-buid-env.sh fails in branch-3.1

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/HADOOP-17097

Backported from HADOOP-14671.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/hadoop-multibranch/job/PR-2105/1/console in case of problems.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  10m 27s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  hadolint  |   0m  0s |  hadolint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ branch-3.1 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 31s |  Maven dependency ordering for branch  |
| -1 :x: |  shadedclient  |   1m 25s |  branch has errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 15s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedclient  |   1m 11s |  patch has errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   |  16m 32s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-2105/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2105 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs |
| uname | Linux 0fa2aa941452 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | branch-3.1 / d26dcf6 |
| Max. process+thread count | 68 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-2105/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.3.7 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
Closing as dup of #2108

**Comment by iwasakims** [comment]
Sorry, I missed this PR...

**Comment by aajisaka** [comment]
No problem. Your patch looks better.

**Pull request closed without merging**
