### PR TITLE
HDFS-15977. Call explicit_bzero only if it is available.

### PR DESCRIPTION
**Pull request by aajisaka**
Manually tested with CentOS 7.9.

JIRA: HDFS-15977

### CODE REVIEW

**Comment by aajisaka** [comment]
@GauthamBanasandra @goiri Would you review this?

**Review by GauthamBanasandra — APPROVED** [review]

**Comment by GauthamBanasandra** [comment]
Thanks @aajisaka for the fix. Is there a list of OS that we need to support? I'll compile my PRs against them to avoid these issues in the future.

**Comment by aajisaka** [comment]
IMO, it would be better for Hadoop to support the list in Apache Bigtop:
- centos7
- centos8
- debian9
- debian10
- fedora31
- ubuntu16 (soon EoL at the end of 2021/4, I'm okay to drop the support)
- ubuntu18

I think @iwasakims has more context.

**Comment by aajisaka** [comment]
I found the latest list: https://ci.bigtop.apache.org/job/Bigtop-trunk-repos/
- centos 7, 8
- debian 10
- fedora 33
- ubuntu 18, 20

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 51s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  37m  1s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   2m 58s |  |  trunk passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  compile  |   2m 49s |  |  trunk passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  mvnsite  |   0m 22s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  59m  6s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 14s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 43s |  |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  cc  |   2m 43s |  |  the patch passed  |
| +1 :green_heart: |  golang  |   2m 43s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 43s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 50s |  |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  cc  |   2m 50s |  |  the patch passed  |
| +1 :green_heart: |  golang  |   2m 50s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 50s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 15s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  15m 43s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 104m 53s |  |  hadoop-hdfs-native-client in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 31s |  |  The patch does not generate ASF License warnings.  |
|  |   | 189m 10s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2914/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2914 |
| Optional Tests | dupname asflicense compile cc mvnsite javac unit codespell golang |
| uname | Linux 0bc1e9739f1a 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / b316e640ef4ca2aa26001a42b653ddde7438f68c |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2914/1/testReport/ |
| Max. process+thread count | 522 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-native-client U: hadoop-hdfs-project/hadoop-hdfs-native-client |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2914/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by iwasakims** [comment]
> I found the latest list: https://ci.bigtop.apache.org/job/Bigtop-trunk-repos/

Yeah. You can see the discussion on [BIGTOP-3471](https://issues.apache.org/jira/browse/BIGTOP-3471). Ubuntu 16.04 and Debian 9 will be dropped in the next release of Bigtop. Debian 11 might be added.

**Review by iwasakims — APPROVED** [review]
+1. I got no issue on CentOS 7, CentOS 8 and Fedora 33.

**Review by goiri — APPROVED** [review]

**Comment by aajisaka** [comment]
Merged. Thank you @GauthamBanasandra, @iwasakims, and @goiri.

**Pull request merged**
