### PR TITLE
HDFS-16072. TestBlockRecovery is failing consistently on branch-2.10

### PR DESCRIPTION
**Pull request by amahussein**
HDFS-16072 TestBlockRecovery fails consistently on Branch-2.10

`TestBlockRecovery` was failing because of the side effects of the unit tests especially when the `DN.recover()` is being called.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  10m 51s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-2.10 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  14m 25s |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |   0m 58s |  branch-2.10 passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  compile  |   0m 51s |  branch-2.10 passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10  |
| +1 :green_heart: |  checkstyle  |   0m 33s |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |   1m  0s |  branch-2.10 passed  |
| +1 :green_heart: |  javadoc  |   1m 16s |  branch-2.10 passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javadoc  |   0m 52s |  branch-2.10 passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10  |
| +0 :ok: |  spotbugs  |   6m 16s |  Both FindBugs and SpotBugs are enabled, using SpotBugs.  |
| -1 :x: |  spotbugs  |   2m 27s |  hadoop-hdfs-project/hadoop-hdfs in branch-2.10 has 1 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 51s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 51s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javac  |   0m 51s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 44s |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10  |
| +1 :green_heart: |  javac  |   0m 44s |  the patch passed  |
| -0 :warning: |  checkstyle  |   0m 29s |  hadoop-hdfs-project/hadoop-hdfs: The patch generated 1 new + 49 unchanged - 5 fixed = 50 total (was 54)  |
| +1 :green_heart: |  mvnsite  |   0m 54s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   1m  6s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javadoc  |   0m 45s |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10  |
| +1 :green_heart: |  spotbugs  |   2m 30s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  64m 49s |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   | 110m 59s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.qjournal.server.TestJournalNodeRespectsBindHostKeys |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3112 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle |
| uname | Linux 14c1fc3b3098 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / ab6b568 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_262-b10 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10 |
| spotbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/1/artifact/out/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-warnings.html |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/1/artifact/out/diff-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/1/testReport/ |
| Max. process+thread count | 2172 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 41s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-2.10 Compile Tests _ |
| -1 :x: |  mvninstall  |   1m 42s |  root in branch-2.10 failed.  |
| -1 :x: |  compile  |   1m  4s |  hadoop-hdfs in branch-2.10 failed with JDK Azul Systems, Inc.-1.7.0_262-b10.  |
| -1 :x: |  compile  |   0m 11s |  hadoop-hdfs in branch-2.10 failed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10.  |
| -0 :warning: |  checkstyle  |   0m 11s |  The patch fails to run checkstyle in hadoop-hdfs  |
| -1 :x: |  mvnsite  |   0m 11s |  hadoop-hdfs in branch-2.10 failed.  |
| -1 :x: |  javadoc  |   0m 15s |  hadoop-hdfs in branch-2.10 failed with JDK Azul Systems, Inc.-1.7.0_262-b10.  |
| -1 :x: |  javadoc  |   0m 12s |  hadoop-hdfs in branch-2.10 failed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10.  |
| +0 :ok: |  spotbugs  |   1m  7s |  Both FindBugs and SpotBugs are enabled, using SpotBugs.  |
| -1 :x: |  spotbugs  |   0m 13s |  hadoop-hdfs in branch-2.10 failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 11s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  compile  |   0m 13s |  hadoop-hdfs in the patch failed with JDK Azul Systems, Inc.-1.7.0_262-b10.  |
| -1 :x: |  javac  |   0m 13s |  hadoop-hdfs in the patch failed with JDK Azul Systems, Inc.-1.7.0_262-b10.  |
| -1 :x: |  compile  |   0m 11s |  hadoop-hdfs in the patch failed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10.  |
| -1 :x: |  javac  |   0m 11s |  hadoop-hdfs in the patch failed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10.  |
| -0 :warning: |  checkstyle  |   0m  8s |  The patch fails to run checkstyle in hadoop-hdfs  |
| -1 :x: |  mvnsite  |   0m 11s |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  javadoc  |   0m 12s |  hadoop-hdfs in the patch failed with JDK Azul Systems, Inc.-1.7.0_262-b10.  |
| -1 :x: |  javadoc  |   0m 12s |  hadoop-hdfs in the patch failed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10.  |
| -1 :x: |  spotbugs  |   0m 12s |  hadoop-hdfs in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 11s |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 27s |  The patch does not generate ASF License warnings.  |
|  |   |  10m 41s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3112 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle |
| uname | Linux c21768bf054d 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / ab6b568 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_262-b10 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10 |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/branch-compile-hadoop-hdfs-project_hadoop-hdfs-jdkAzulSystems,Inc.-1.7.0_262-b10.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/branch-compile-hadoop-hdfs-project_hadoop-hdfs-jdkPrivateBuild-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/buildtool-branch-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/branch-mvnsite-hadoop-hdfs-project_hadoop-hdfs.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/branch-javadoc-hadoop-hdfs-project_hadoop-hdfs-jdkAzulSystems,Inc.-1.7.0_262-b10.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/branch-javadoc-hadoop-hdfs-project_hadoop-hdfs-jdkPrivateBuild-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10.txt |
| spotbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/patch-mvninstall-hadoop-hdfs-project_hadoop-hdfs.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/patch-compile-hadoop-hdfs-project_hadoop-hdfs-jdkAzulSystems,Inc.-1.7.0_262-b10.txt |
| javac | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/patch-compile-hadoop-hdfs-project_hadoop-hdfs-jdkAzulSystems,Inc.-1.7.0_262-b10.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/patch-compile-hadoop-hdfs-project_hadoop-hdfs-jdkPrivateBuild-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10.txt |
| javac | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/patch-compile-hadoop-hdfs-project_hadoop-hdfs-jdkPrivateBuild-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/buildtool-patch-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/patch-mvnsite-hadoop-hdfs-project_hadoop-hdfs.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/patch-javadoc-hadoop-hdfs-project_hadoop-hdfs-jdkAzulSystems,Inc.-1.7.0_262-b10.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/patch-javadoc-hadoop-hdfs-project_hadoop-hdfs-jdkPrivateBuild-1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10.txt |
| spotbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/patch-spotbugs-hadoop-hdfs-project_hadoop-hdfs.txt |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/testReport/ |
| Max. process+thread count | 88 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3112/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by amahussein** [comment]
The problem seemed to be caused by trying to start a thread that has been already started. This happens when a new miniDFSCluster is starting datanodes that have not stopped yet.
I do not see this to be a bug rather than problem between Mocks, tearing down tests and MiniDFSCluster implementation.

One modification I did:
The legacy code would start a DN during the test startUp. Then som unit tests call `tearDown()` at the beginning to stop the DN.
Clearly, this is not very practical. So, I changed the startup to start the DN only for the unit test that need it.

- I fixed the checkstyle issue reported earlier.
- the spotbugs error is irrelevant to the changes.
- there is still problem with yetus building branch-2.10. I reported that in HADOOP-17762
- the failing unit-test  TestJournalNodeRespectsBindHostKeys is unrelated to the changes. I have filed a jira HDFS-16071

@jbrennan333 can you please take a look at the changes?

**Comment by amahussein** [comment]
closing this as there is a better fix to the problem.

**Pull request closed without merging**
