### PR TITLE
HDDS-2001. Update Ratis version to 0.4.0.

### PR DESCRIPTION
**Pull request by nandakumar131**
Updating Ratis version to 0.4.0

### CODE REVIEW

**Comment by anuengineer** [comment]
+1. I looked at the unit test failures. They are in the Ratis space, but I am not sure it is due to the upgrade. Some of these tests are unstable. I see that integration tests have passed. So I am going to commit this. Thanks for the contribution.

**Comment by anuengineer** [comment]
Thank you for the contribution. I have committed this patch to the trunk branch. Please cherry-pick when you get a chance.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 76 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 72 | Maven dependency ordering for branch |
| +1 | mvninstall | 1851 | trunk passed |
| +1 | compile | 1286 | trunk passed |
| -1 | mvnsite | 1368 | root in trunk failed. |
| -1 | shadedclient | 4648 | branch has errors when building and testing our client artifacts. |
| +1 | javadoc | 548 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 30 | Maven dependency ordering for patch |
| -1 | mvninstall | 45 | hadoop-ozone in the patch failed. |
| +1 | compile | 1253 | the patch passed |
| +1 | javac | 1253 | the patch passed |
| -1 | mvnsite | 1524 | root in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 4 | The patch has no ill-formed XML file. |
| -1 | shadedclient | 60 | patch has errors when building and testing our client artifacts. |
| +1 | javadoc | 629 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 3368 | root in the patch failed. |
| +1 | asflicense | 57 | The patch does not generate ASF License warnings. |
| | | 14337 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.client.rpc.TestMultiBlockWritesWithDnFailures |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |
|   | hadoop.ozone.client.rpc.Test2WayCommitInRatis |
|   | hadoop.ozone.client.rpc.TestCommitWatcher |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.security.TestRaceWhenRelogin |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1483/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1483 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 4123f1346cac 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 1654497 |
| Default Java | 1.8.0_222 |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-1483/1/artifact/out/branch-mvnsite-root.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1483/1/artifact/out/patch-mvninstall-hadoop-ozone.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-1483/1/artifact/out/patch-mvnsite-root.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1483/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1483/1/testReport/ |
| Max. process+thread count | 4416 (vs. ulimit of 5500) |
| modules | C: . hadoop-hdds hadoop-ozone U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1483/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by nandakumar131** [comment]
@anuengineer Thanks for the review. There are conflicts while backporting this to ozone-0.4.1, created #1497

**Pull request closed without merging**
