### PR TITLE
HADOOP-15983. Use jersey-json that is built to use jackson2 (branch 3.3)

### PR DESCRIPTION
**Pull request by pjfanning**
### Description of PR

This PR also backports changes for
* HADOOP-16908
* HADOOP-18219

These are need for the HADOOP-15983 changes to build ok.

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  10m 13s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  16m 37s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  28m 52s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  20m 15s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  23m 10s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   7m 30s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  33m 55s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   0m 19s | [/patch-mvninstall-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/artifact/out/patch-mvninstall-root.txt) |  root in the patch failed.  |
| -1 :x: |  mvninstall  |   0m 39s | [/patch-mvninstall-hadoop-client-modules_hadoop-client.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/artifact/out/patch-mvninstall-hadoop-client-modules_hadoop-client.txt) |  hadoop-client in the patch failed.  |
| -1 :x: |  mvninstall  |   6m 39s | [/patch-mvninstall-hadoop-client-modules_hadoop-client-minicluster.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/artifact/out/patch-mvninstall-hadoop-client-modules_hadoop-client-minicluster.txt) |  hadoop-client-minicluster in the patch failed.  |
| -1 :x: |  mvninstall  |   0m 23s | [/patch-mvninstall-hadoop-tools_hadoop-resourceestimator.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/artifact/out/patch-mvninstall-hadoop-tools_hadoop-resourceestimator.txt) |  hadoop-resourceestimator in the patch failed.  |
| -1 :x: |  mvninstall  |   0m 18s | [/patch-mvninstall-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-applicationhistoryservice.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/artifact/out/patch-mvninstall-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-applicationhistoryservice.txt) |  hadoop-yarn-server-applicationhistoryservice in the patch failed.  |
| -1 :x: |  compile  |   0m 22s | [/patch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/artifact/out/patch-compile-root.txt) |  root in the patch failed.  |
| -1 :x: |  javac  |   0m 22s | [/patch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/artifact/out/patch-compile-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  blanks  |   0m  1s |  |  The patch has no blanks issues.  |
| -1 :x: |  mvnsite  |   0m 22s | [/patch-mvnsite-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/artifact/out/patch-mvnsite-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| -1 :x: |  javadoc  |   0m 24s | [/patch-javadoc-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/artifact/out/patch-javadoc-root.txt) |  root in the patch failed.  |
| -1 :x: |  shadedclient  |   1m 52s |  |  patch has errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 23s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/artifact/out/patch-unit-root.txt) |  root in the patch failed.  |
| +0 :ok: |  asflicense  |   0m 24s |  |  ASF License check generated no output?  |
|  |   | 153m 30s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5048 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint shellcheck shelldocs |
| uname | Linux 8aa58e689768 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / b7416a5f32b6453ebc76085caf6effed4a4d1d57 |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/testReport/ |
| Max. process+thread count | 553 (vs. ulimit of 5500) |
| modules | C: . hadoop-client-modules/hadoop-client hadoop-client-modules/hadoop-client-minicluster hadoop-common-project/hadoop-common hadoop-project hadoop-tools/hadoop-resourceestimator hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-catalog/hadoop-yarn-applications-catalog-webapp hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/1/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 43s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  1s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  1s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  1s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 49s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  24m 17s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m 22s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m  0s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  21m 37s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   7m 24s |  |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   0m 28s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 26s |  |  branch/hadoop-client-modules/hadoop-client no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 26s |  |  branch/hadoop-client-modules/hadoop-client-minicluster no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  57m 28s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 47s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  34m 50s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 39s |  |  the patch passed  |
| -1 :x: |  javac  |  17m 39s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/2/artifact/out/results-compile-javac-root.txt) |  root generated 2 new + 1856 unchanged - 0 fixed = 1858 total (was 1856)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m 54s |  |  root: The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  mvnsite  |  19m 57s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   6m 58s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 28s |  |  hadoop-project has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 34s |  |  hadoop-client-modules/hadoop-client has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 37s |  |  hadoop-client-modules/hadoop-client-minicluster has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  56m 25s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 107m  7s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/2/artifact/out/patch-unit-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m 15s |  |  The patch does not generate ASF License warnings.  |
|  |   | 432m 34s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestDecommissionWithStripedBackoffMonitor |
|   | hadoop.hdfs.TestDFSInputStream |
|   | hadoop.hdfs.TestReplication |
|   | hadoop.hdfs.TestErasureCodingMultipleRacks |
|   | hadoop.hdfs.TestDFSStripedOutputStreamWithRandomECPolicy |
|   | hadoop.hdfs.TestReadStripedFileWithDecoding |
|   | hadoop.hdfs.TestReadStripedFileWithDecodingDeletedData |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5048 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint spotbugs checkstyle shellcheck shelldocs |
| uname | Linux a90e2c60fcb3 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 617386287809b35a35caf58887c99c4a9eda6d46 |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/2/testReport/ |
| Max. process+thread count | 2940 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-catalog/hadoop-yarn-applications-catalog-webapp hadoop-client-modules/hadoop-client hadoop-tools/hadoop-azure hadoop-tools/hadoop-resourceestimator hadoop-client-modules/hadoop-client-minicluster . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5048/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by steveloughran — APPROVED** [review]
+1

**Comment by steveloughran** [comment]
thanks; pushing through again for a 3.3.5 release in #5053

**Pull request merged**
