### PR TITLE
HADOOP-16376. ABFS: Override access() to no-op.

### PR DESCRIPTION
**Pull request by DadanielZ**
Contributed by Da Zhou.

Change-Id: Ia0024bba32250189a87eb6247808b2473c331ed0

### CODE REVIEW

**Comment by DadanielZ** [comment]
@steveloughran 
cherry picked from trunk
All tests passed for my west us account:
non-xns account
Tests run: 35, Failures: 0, Errors: 0, Skipped: 0
Tests run: 383, Failures: 0, Errors: 0, Skipped: 207
Tests run: 168, Failures: 0, Errors: 0, Skipped: 15

xns account
Tests run: 35, Failures: 0, Errors: 0, Skipped: 0
Tests run: 383, Failures: 0, Errors: 0, Skipped: 23
Tests run: 168, Failures: 0, Errors: 0, Skipped: 21

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 16 | https://github.com/apache/hadoop/pull/988 does not apply to branch-3.2. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/988 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-988/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
missed this

+1

**Comment by steveloughran** [comment]
@DadanielZ I'm happy with this PR if you can rebase it to trunk and reapply.

**Comment by DadanielZ** [comment]
Actually this is no longer needed and has been updated already, I will close this comment.
@steveloughran Thanks anyway :)

**Pull request closed without merging**
