### PR TITLE
HDFS-15814. Make some parameters configurable for DataNodeDiskMetrics…

### PR DESCRIPTION
**Pull request by tomscut**
JIRA: [HDFS-15814](https://issues.apache.org/jira/browse/HDFS-15814)

This change was fixed in trunk (3.4.0). The commit does not apply cleanly to branch-3.3, so I create a new PR.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  21m 15s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  30m 44s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |   1m 18s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   1m  7s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   1m 45s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   1m 42s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   4m  7s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  24m  3s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 29s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 17s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 17s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 51s |  |  hadoop-hdfs-project/hadoop-hdfs: The patch generated 0 new + 610 unchanged - 2 fixed = 610 total (was 612)  |
| +1 :green_heart: |  mvnsite  |   1m 24s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  2s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 37s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   4m  5s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  23m 43s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 197m 59s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3021/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 46s |  |  The patch does not generate ASF License warnings.  |
|  |   | 315m  8s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestStripedFileAppend |
|   | hadoop.hdfs.TestGetFileChecksum |
|   | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3021/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3021 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell xml |
| uname | Linux 6f0b6552be6d 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / dec9a7cfd5508b712126bc8e6a2d898da971cb5f |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3021/1/testReport/ |
| Max. process+thread count | 2948 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3021/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by tomscut** [comment]
Hi @jojochuang @dineshchitlangia , I created a new PR for branch-3.3, could you please help to review the code? The failed tests are not related.

**Review by jojochuang — APPROVED** [review]

**Comment by jojochuang** [comment]
Thanks @tomscut

**Comment by tomscut** [comment]
> Thanks @tomscut

Thanks @jojochuang for the merge.

**Pull request merged**
