### PR TITLE
HADOOP-16744. Fix building instruction to enable zstd.

### PR DESCRIPTION
**Pull request by iwasakims**

### CODE REVIEW

**Comment by aajisaka** [comment]
@iwasakims Thank you for your patch.
In the Dockerfile (dev-support/docker/Dockerfile), should we change `libzstd1-dev` to `libzstd-dev` (virtual package) as well?

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  30m 42s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  shadedclient  |  15m 25s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  14m 59s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 30s |  The patch does not generate ASF License warnings.  |
|  |   |  63m 18s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1736/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1736 |
| Optional Tests | dupname asflicense |
| uname | Linux 8d05070a1e39 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c48de9a |
| Max. process+thread count | 307 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1736/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by iwasakims** [comment]
> In the Dockerfile (dev-support/docker/Dockerfile), should we change `libzstd1-dev` to `libzstd-dev` (virtual package) as well?

Sure. While we have the same result by using transitional package name (ibzstd1-dev), it would be better that the Dockerfile and documentation are consistent.

**Comment by iwasakims** [comment]
The Dockerfile is based on xenial (16.04) in which libzstd-dev points to older version (0.5.1). We whould use libzstd1-dev pointing to newer version. Since libzstd1-dev is still available on bioinic (18.04) as transitional package, libzstd1-dev would be better in BUILDING.txt too. I will update the code.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 21s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  shadedclient  |  14m 58s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 15s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 28s |  The patch does not generate ASF License warnings.  |
|  |   |  33m 43s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1736/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1736 |
| Optional Tests | dupname asflicense |
| uname | Linux c473327d73f5 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 682e6fd |
| Max. process+thread count | 306 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1736/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
+1, make sense. Thank you @iwasakims

**Comment by iwasakims** [comment]
Thanks, @aajisaka .

**Pull request merged**
