### PR TITLE
HADOOP-17570. Apply YETUS-1102 to re-enable GitHub comments

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/HADOOP-17570

### CODE REVIEW

**Comment by aajisaka** [comment]
The comment works as espected. I'm not sure why the vote is "💔 -1 overall"

**Comment by ayushtkn** [comment]
Hey @aajisaka 
This looks good :-)
Mind raising a jira for the same, so as to get this in, or are we blocked on something?

**Comment by aajisaka** [comment]
YETUS-1102 is not merged into Yetus main branch. I'll push this.

**Comment by aajisaka** [comment]
Filed https://issues.apache.org/jira/browse/HADOOP-17570.

We need to merge https://github.com/apache/hadoop/pull/2753 before this PR because Yetus dropped findbugs support before YETUS-1102.

**Comment by ayushtkn** [comment]
Seems it is throwing some error
```
Unprocessed flag(s): --findbugs-strict-precheck
```

**Comment by aajisaka** [comment]
bq. Seems it is throwing some error

It is as expected before #2753

**Comment by ayushtkn** [comment]
#2753 is merged right? Then why this problem is coming now?
Like here as well:
https://issues.apache.org/jira/browse/HDFS-15848?focusedCommentId=17299300&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17299300

**Comment by aajisaka** [comment]
> #2753 is merged right? Then why this problem is coming now?
> Like here as well:
https://issues.apache.org/jira/browse/HDFS-15848?focusedCommentId=17299300&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17299300

Sorry I forgot to update the config in precommit-HDFS-build job after merging #2753. We have to sync the yetus options among Jenkinsfile and Precommit-HADOOP/HDFS/MAPREDUCE/YARN-Build jobs.

**Review by ayushtkn — APPROVED** [review]
Thanx @aajisaka for fix,
We can see, the comments on the PR, so this fix is working.
+1 for this PR.

Try if you can get a comment without the yetus failure before merging.

**Comment by zhuqi-lucas** [comment]
Thanx @aajisaka for fix,
+1 for this PR.

**Comment by aajisaka** [comment]
Merged. Thank you @ayushtkn and @qizhu-lucas

**Pull request merged**
