### PR TITLE
HADOOP-17283. Hadoop - Upgrade to jQuery 3.5.1

### PR DESCRIPTION
**Pull request by aryangupta1998**
jQuery version is being upgraded from jquery-3.4.1.min.js to jquery-3.5.1.min.js
Jira Link - [https://issues.apache.org/jira/browse/HDFS-15593
](https://issues.apache.org/jira/browse/HDFS-15593)

Tested Manually. Also, NN UI is working fine.
Screenshot 2020-09-23 at 8 35 49 PM

### CODE REVIEW

**Comment by tasanuma** [comment]
Thanks for working on this, @aryangupta1998.

There are still some codes using jquery-3.4.1. Could you also fix them?
```
$ find . -type f | grep -v target | xargs grep 'jquery-3.4' 2> /dev/null
./hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/pom.xml:            <exclude>src/main/resources/webapps/static/jquery/jquery-3.4.1.min.js</exclude>
./hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/webapp/view/JQueryUI.java:        .script(root_url("static/jquery/jquery-3.4.1.min.js"))
./LICENSE-binary:hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/static/jquery-3.4.1.min.js
./hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/journal/index.html:<script type="text/javascript" src="/static/jquery-3.4.1.min.js">
./hadoop-hdfs-project/hadoop-hdfs-rbf/src/main/webapps/router/explorer.html:    <script type="text/javascript" src="/static/jquery-3.4.1.min.js">
```

**Comment by aryangupta1998** [comment]
Thanks, @tasanuma for the review. I have addressed the comments.

**Review by tasanuma — APPROVED** [review]
LGTM. +1.

**Comment by tasanuma** [comment]
Merged to trunk. Thanks for your contribution, @aryangupta1998.

**Pull request merged**
