### PR TITLE
HADOOP-17514. Remove trace subcommand from hadoop CLI.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/HADOOP-17514

TraceAdmin protocol and utility class were removed by [HADOOP-17424](https://issues.apache.org/jira/browse/HADOOP-17424).

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 34s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  1s |  |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  32m 52s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 22s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  13m 22s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 58s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 17s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  9s |  |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 15s |  |  The patch generated 0 new + 104 unchanged - 132 fixed = 104 total (was 236)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  13m 14s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 45s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 38s |  |  The patch does not generate ASF License warnings.  |
|  |   |  68m 25s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2680/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2680 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs markdownlint |
| uname | Linux ebb0068ee774 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 15a1f7adfc0 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2680/1/testReport/ |
| Max. process+thread count | 534 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2680/1/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 31s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  34m 39s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 33s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  13m 37s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 56s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 11s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  8s |  |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 15s |  |  The patch generated 0 new + 104 unchanged - 132 fixed = 104 total (was 236)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  13m  5s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 43s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 38s |  |  The patch does not generate ASF License warnings.  |
|  |   |  70m  1s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2680/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2680 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs markdownlint |
| uname | Linux a8d07bd0385b 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 19ae0faacc5 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2680/2/testReport/ |
| Max. process+thread count | 694 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2680/2/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by jojochuang — COMMENTED** [review]
Assuming we will ultimately switch to OpenTracing/OpenTelemetry, we still want a trace subcommand?

**Comment by iwasakims** [comment]
@jojochuang TraceAdmin protocol was removed by @smengcl because it is not needed for alternative tracer impl.
https://github.com/apache/hadoop/pull/2645#issuecomment-768251870

If it turned out to be needed, we can add it back again. Since trace subcommand was actually dynamic reconfiguration functionality, adding generic protocol which can be used for other purposes could be an option.

**Comment by smengcl** [comment]
Good catch. Actually because `TraceAdmin` is removed, the `trace` subcommand is referencing a non-existent class now:
```
$ ./bin/hadoop trace
Error: Could not find or load main class org.apache.hadoop.tracing.TraceAdmin
```
 I'm +1 on removing this right now.

**Review by smengcl — APPROVED** [review]

**Comment by iwasakims** [comment]
Thanks, @smengcl. I'm merging this.

**Pull request merged**
