### PR TITLE
YARN-11125. Backport YARN-6483 to branch-2.10

### PR DESCRIPTION
**Pull request by hotcodemacha**
### Description of PR
Backport YARN-6483 to branch-2.10
* JIRA: YARN-11125

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  12m 33s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  buf  |   0m  0s |  |  buf was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 10 new or modified test files.  |
|||| _ branch-2.10 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 12s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  14m 16s |  |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |   7m 28s |  |  branch-2.10 passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  compile  |   6m 37s |  |  branch-2.10 passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  checkstyle  |   1m 37s |  |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |   6m 12s |  |  branch-2.10 passed  |
| +1 :green_heart: |  javadoc  |   5m 49s |  |  branch-2.10 passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javadoc  |   5m  9s |  |  branch-2.10 passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  spotbugs  |   9m 26s |  |  branch-2.10 passed  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m 10s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   6m 42s |  |  the patch passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  cc  |   6m 42s |  |  the patch passed  |
| -1 :x: |  javac  |   6m 42s | [/results-compile-javac-hadoop-yarn-project_hadoop-yarn-jdkAzulSystems,Inc.-1.7.0_262-b10.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4258/1/artifact/out/results-compile-javac-hadoop-yarn-project_hadoop-yarn-jdkAzulSystems,Inc.-1.7.0_262-b10.txt) |  hadoop-yarn-project_hadoop-yarn-jdkAzulSystems,Inc.-1.7.0_262-b10 with JDK Azul Systems, Inc.-1.7.0_262-b10 generated 4 new + 141 unchanged - 0 fixed = 145 total (was 141)  |
| +1 :green_heart: |  compile  |   6m 32s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  cc  |   6m 32s |  |  the patch passed  |
| -1 :x: |  javac  |   6m 32s | [/results-compile-javac-hadoop-yarn-project_hadoop-yarn-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4258/1/artifact/out/results-compile-javac-hadoop-yarn-project_hadoop-yarn-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07.txt) |  hadoop-yarn-project_hadoop-yarn-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 generated 4 new + 130 unchanged - 0 fixed = 134 total (was 130)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m 23s |  |  hadoop-yarn-project/hadoop-yarn: The patch generated 0 new + 487 unchanged - 19 fixed = 487 total (was 506)  |
| +1 :green_heart: |  mvnsite  |   5m 26s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   5m  5s |  |  the patch passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javadoc  |   4m 38s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  spotbugs  |   9m 23s |  |  the patch passed  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 11s |  |  hadoop-yarn-api in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 49s |  |  hadoop-yarn-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 56s |  |  hadoop-yarn-server-common in the patch passed.  |
| -1 :x: |  unit  |  68m 57s | [/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4258/1/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt) |  hadoop-yarn-server-resourcemanager in the patch passed.  |
| +1 :green_heart: |  unit  |  24m  9s |  |  hadoop-yarn-client in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 13s |  |  The patch does not generate ASF License warnings.  |
|  |   | 226m  6s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.yarn.server.resourcemanager.TestResourceTrackerService |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4258/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4258 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell cc buflint bufcompat |
| uname | Linux 76b7d5e175ee 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / 7e81bd07f62c945e1c5317ce5cef5e7455eea797 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_262-b10 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4258/1/testReport/ |
| Max. process+thread count | 847 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client U: hadoop-yarn-project/hadoop-yarn |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4258/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hotcodemacha** [comment]
@aajisaka - Can you have look at this? Thanks

**Review by aajisaka — CHANGES_REQUESTED** [review]
Thank you @ashutoshcipher for your backport PR. Would you apply  https://issues.apache.org/jira/secure/attachment/12900787/YARN-6483.branch-3.0.addendum.patch to ignore the test failure? I'm +1 if that is addressed.

**Review by aajisaka — APPROVED** [review]
+1

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 55s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  buf  |   0m  1s |  |  buf was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 10 new or modified test files.  |
|||| _ branch-2.10 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 11s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  14m 19s |  |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |   7m 30s |  |  branch-2.10 passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  compile  |   6m 34s |  |  branch-2.10 passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  checkstyle  |   1m 36s |  |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |   6m 10s |  |  branch-2.10 passed  |
| +1 :green_heart: |  javadoc  |   5m 45s |  |  branch-2.10 passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javadoc  |   5m 13s |  |  branch-2.10 passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  spotbugs  |   9m 31s |  |  branch-2.10 passed  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m 11s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   6m 44s |  |  the patch passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  cc  |   6m 44s |  |  the patch passed  |
| -1 :x: |  javac  |   6m 44s | [/results-compile-javac-hadoop-yarn-project_hadoop-yarn-jdkAzulSystems,Inc.-1.7.0_262-b10.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4258/2/artifact/out/results-compile-javac-hadoop-yarn-project_hadoop-yarn-jdkAzulSystems,Inc.-1.7.0_262-b10.txt) |  hadoop-yarn-project_hadoop-yarn-jdkAzulSystems,Inc.-1.7.0_262-b10 with JDK Azul Systems, Inc.-1.7.0_262-b10 generated 4 new + 141 unchanged - 0 fixed = 145 total (was 141)  |
| +1 :green_heart: |  compile  |   6m 30s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  cc  |   6m 30s |  |  the patch passed  |
| -1 :x: |  javac  |   6m 30s | [/results-compile-javac-hadoop-yarn-project_hadoop-yarn-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4258/2/artifact/out/results-compile-javac-hadoop-yarn-project_hadoop-yarn-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07.txt) |  hadoop-yarn-project_hadoop-yarn-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 generated 4 new + 130 unchanged - 0 fixed = 134 total (was 130)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m 23s |  |  hadoop-yarn-project/hadoop-yarn: The patch generated 0 new + 487 unchanged - 19 fixed = 487 total (was 506)  |
| +1 :green_heart: |  mvnsite  |   5m 27s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   5m  8s |  |  the patch passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javadoc  |   4m 40s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  spotbugs  |   9m 23s |  |  the patch passed  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 12s |  |  hadoop-yarn-api in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 50s |  |  hadoop-yarn-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 55s |  |  hadoop-yarn-server-common in the patch passed.  |
| +1 :green_heart: |  unit  |  68m 10s |  |  hadoop-yarn-server-resourcemanager in the patch passed.  |
| +1 :green_heart: |  unit  |  24m  8s |  |  hadoop-yarn-client in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 12s |  |  The patch does not generate ASF License warnings.  |
|  |   | 213m 28s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4258/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4258 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell cc buflint bufcompat |
| uname | Linux 4f6342c11a47 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / 1bf8edd848e28c983dd4d432d3cbc601826b725f |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_262-b10 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4258/2/testReport/ |
| Max. process+thread count | 874 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client U: hadoop-yarn-project/hadoop-yarn |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4258/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hotcodemacha** [comment]
@aajisaka Thanks for the review. Once this is merged, I will make changes here as well -https://github.com/apache/hadoop/pull/4244

**Comment by aajisaka** [comment]
Merged. Thank you @ashutoshcipher

**Pull request merged**
