### PR TITLE
HDFS-15911 : Provide blocks moved count in Balancer iteration result

### PR DESCRIPTION
**Pull request by virajjasani**
branch-3.1 backport PR of #2794

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  13m  8s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-3.1 Compile Tests _ |
| -1 :x: |  mvninstall  |   4m 39s |  root in branch-3.1 failed.  |
| -1 :x: |  compile  |   0m 29s |  hadoop-hdfs in branch-3.1 failed.  |
| -0 :warning: |  checkstyle  |   0m 18s |  The patch fails to run checkstyle in hadoop-hdfs  |
| -1 :x: |  mvnsite  |   0m 13s |  hadoop-hdfs in branch-3.1 failed.  |
| -1 :x: |  shadedclient  |   1m 20s |  branch has errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 22s |  hadoop-hdfs in branch-3.1 failed.  |
| +0 :ok: |  spotbugs  |   1m 56s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| -1 :x: |  findbugs  |   0m 13s |  hadoop-hdfs in branch-3.1 failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  compile  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  javac  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| -0 :warning: |  checkstyle  |   0m 10s |  The patch fails to run checkstyle in hadoop-hdfs  |
| -1 :x: |  mvnsite  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedclient  |   0m 50s |  patch has errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  findbugs  |   0m 13s |  hadoop-hdfs in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 13s |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 31s |  The patch does not generate ASF License warnings.  |
|  |   |  25m 56s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2799 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux bbbfed1f0615 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.1 / c9c471e |
| Default Java | Oracle Corporation-9-internal+0-2016-04-14-195246.buildd.src |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/branch-compile-hadoop-hdfs-project_hadoop-hdfs.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/buildtool-branch-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/branch-mvnsite-hadoop-hdfs-project_hadoop-hdfs.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/branch-javadoc-hadoop-hdfs-project_hadoop-hdfs.txt |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/branch-findbugs-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/patch-mvninstall-hadoop-hdfs-project_hadoop-hdfs.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/patch-compile-hadoop-hdfs-project_hadoop-hdfs.txt |
| javac | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/patch-compile-hadoop-hdfs-project_hadoop-hdfs.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/buildtool-patch-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/patch-mvnsite-hadoop-hdfs-project_hadoop-hdfs.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/patch-javadoc-hadoop-hdfs-project_hadoop-hdfs.txt |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/patch-findbugs-hadoop-hdfs-project_hadoop-hdfs.txt |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/testReport/ |
| Max. process+thread count | 150 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  18m 29s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-3.1 Compile Tests _ |
| -1 :x: |  mvninstall  |   4m 41s |  root in branch-3.1 failed.  |
| -1 :x: |  compile  |   0m 29s |  hadoop-hdfs in branch-3.1 failed.  |
| -0 :warning: |  checkstyle  |   0m 17s |  The patch fails to run checkstyle in hadoop-hdfs  |
| -1 :x: |  mvnsite  |   0m 12s |  hadoop-hdfs in branch-3.1 failed.  |
| -1 :x: |  shadedclient  |   1m 17s |  branch has errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 21s |  hadoop-hdfs in branch-3.1 failed.  |
| +0 :ok: |  spotbugs  |   1m 52s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| -1 :x: |  findbugs  |   0m 13s |  hadoop-hdfs in branch-3.1 failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  compile  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  javac  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| -0 :warning: |  checkstyle  |   0m 10s |  The patch fails to run checkstyle in hadoop-hdfs  |
| -1 :x: |  mvnsite  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedclient  |   0m 49s |  patch has errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 13s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  findbugs  |   0m 13s |  hadoop-hdfs in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 29s |  The patch does not generate ASF License warnings.  |
|  |   |  31m 15s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2799 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 33a9860df7b5 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.1 / c9c471e |
| Default Java | Oracle Corporation-9-internal+0-2016-04-14-195246.buildd.src |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/branch-compile-hadoop-hdfs-project_hadoop-hdfs.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/buildtool-branch-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/branch-mvnsite-hadoop-hdfs-project_hadoop-hdfs.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/branch-javadoc-hadoop-hdfs-project_hadoop-hdfs.txt |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/branch-findbugs-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/patch-mvninstall-hadoop-hdfs-project_hadoop-hdfs.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/patch-compile-hadoop-hdfs-project_hadoop-hdfs.txt |
| javac | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/patch-compile-hadoop-hdfs-project_hadoop-hdfs.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/buildtool-patch-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/patch-mvnsite-hadoop-hdfs-project_hadoop-hdfs.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/patch-javadoc-hadoop-hdfs-project_hadoop-hdfs.txt |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/patch-findbugs-hadoop-hdfs-project_hadoop-hdfs.txt |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/testReport/ |
| Max. process+thread count | 150 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  22m  8s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-3.1 Compile Tests _ |
| -1 :x: |  mvninstall  |   4m 44s |  root in branch-3.1 failed.  |
| -1 :x: |  compile  |   0m 29s |  hadoop-hdfs in branch-3.1 failed.  |
| -0 :warning: |  checkstyle  |   0m 14s |  The patch fails to run checkstyle in hadoop-hdfs  |
| -1 :x: |  mvnsite  |   0m 10s |  hadoop-hdfs in branch-3.1 failed.  |
| -1 :x: |  shadedclient  |   1m 15s |  branch has errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 18s |  hadoop-hdfs in branch-3.1 failed.  |
| +0 :ok: |  spotbugs  |   1m 45s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| -1 :x: |  findbugs  |   0m 10s |  hadoop-hdfs in branch-3.1 failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 11s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  compile  |   0m 10s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  javac  |   0m 10s |  hadoop-hdfs in the patch failed.  |
| -0 :warning: |  checkstyle  |   0m  8s |  The patch fails to run checkstyle in hadoop-hdfs  |
| -1 :x: |  mvnsite  |   0m 10s |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedclient  |   0m 55s |  patch has errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  findbugs  |   0m 10s |  hadoop-hdfs in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 30s |  The patch does not generate ASF License warnings.  |
|  |   |  34m 50s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2799 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 754b90d93b18 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.1 / c9c471e |
| Default Java | Oracle Corporation-9-internal+0-2016-04-14-195246.buildd.src |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/branch-compile-hadoop-hdfs-project_hadoop-hdfs.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/buildtool-branch-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/branch-mvnsite-hadoop-hdfs-project_hadoop-hdfs.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/branch-javadoc-hadoop-hdfs-project_hadoop-hdfs.txt |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/branch-findbugs-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/patch-mvninstall-hadoop-hdfs-project_hadoop-hdfs.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/patch-compile-hadoop-hdfs-project_hadoop-hdfs.txt |
| javac | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/patch-compile-hadoop-hdfs-project_hadoop-hdfs.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/buildtool-patch-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/patch-mvnsite-hadoop-hdfs-project_hadoop-hdfs.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/patch-javadoc-hadoop-hdfs-project_hadoop-hdfs.txt |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/patch-findbugs-hadoop-hdfs-project_hadoop-hdfs.txt |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/testReport/ |
| Max. process+thread count | 126 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/3/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
Build failure doesn't seem related to PR changes for branch-3.1

**Comment by liuml07** [comment]
Jenkins fails with unrelated problems. Maybe you can rebase and trigger the Jenkins again. Thanks,

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 43s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-3.1 Compile Tests _ |
| -1 :x: |  mvninstall  |   4m 39s |  root in branch-3.1 failed.  |
| -1 :x: |  compile  |   0m 31s |  hadoop-hdfs in branch-3.1 failed.  |
| -0 :warning: |  checkstyle  |   0m 18s |  The patch fails to run checkstyle in hadoop-hdfs  |
| -1 :x: |  mvnsite  |   0m 13s |  hadoop-hdfs in branch-3.1 failed.  |
| -1 :x: |  shadedclient  |   1m 22s |  branch has errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 21s |  hadoop-hdfs in branch-3.1 failed.  |
| +0 :ok: |  spotbugs  |   1m 58s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| -1 :x: |  findbugs  |   0m 14s |  hadoop-hdfs in branch-3.1 failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  compile  |   0m 13s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  javac  |   0m 13s |  hadoop-hdfs in the patch failed.  |
| -0 :warning: |  checkstyle  |   0m 11s |  The patch fails to run checkstyle in hadoop-hdfs  |
| -1 :x: |  mvnsite  |   0m 12s |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedclient  |   0m 49s |  patch has errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 13s |  hadoop-hdfs in the patch failed.  |
| -1 :x: |  findbugs  |   0m 14s |  hadoop-hdfs in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 14s |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 30s |  The patch does not generate ASF License warnings.  |
|  |   |  13m 21s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2799 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 9bbc2caea67b 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.1 / 34e507c |
| Default Java | Oracle Corporation-9-internal+0-2016-04-14-195246.buildd.src |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/branch-compile-hadoop-hdfs-project_hadoop-hdfs.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/buildtool-branch-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/branch-mvnsite-hadoop-hdfs-project_hadoop-hdfs.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/branch-javadoc-hadoop-hdfs-project_hadoop-hdfs.txt |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/branch-findbugs-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvninstall | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/patch-mvninstall-hadoop-hdfs-project_hadoop-hdfs.txt |
| compile | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/patch-compile-hadoop-hdfs-project_hadoop-hdfs.txt |
| javac | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/patch-compile-hadoop-hdfs-project_hadoop-hdfs.txt |
| checkstyle | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/buildtool-patch-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| mvnsite | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/patch-mvnsite-hadoop-hdfs-project_hadoop-hdfs.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/patch-javadoc-hadoop-hdfs-project_hadoop-hdfs.txt |
| findbugs | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/patch-findbugs-hadoop-hdfs-project_hadoop-hdfs.txt |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/testReport/ |
| Max. process+thread count | 150 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/4/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  11m 18s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-3.1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  27m 53s |  branch-3.1 passed  |
| +1 :green_heart: |  compile  |   1m  7s |  branch-3.1 passed  |
| +1 :green_heart: |  checkstyle  |   0m 50s |  branch-3.1 passed  |
| +1 :green_heart: |  mvnsite  |   1m 11s |  branch-3.1 passed  |
| +1 :green_heart: |  shadedclient  |  14m 21s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  0s |  branch-3.1 passed  |
| +0 :ok: |  spotbugs  |   2m 50s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 48s |  branch-3.1 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 10s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 59s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 59s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 49s |  hadoop-hdfs-project/hadoop-hdfs: The patch generated 0 new + 229 unchanged - 4 fixed = 229 total (was 233)  |
| +1 :green_heart: |  mvnsite  |   1m  6s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  13m  9s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 52s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   2m 51s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 169m 46s |  hadoop-hdfs in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 42s |  The patch does not generate ASF License warnings.  |
|  |   | 253m  2s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |
|   | hadoop.fs.TestHdfsNativeCodeLoader |
|   | hadoop.hdfs.server.namenode.TestEditLogRace |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2799 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 40fa88644a2b 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.1 / 332c2a6 |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~16.04-b08 |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/5/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/5/testReport/ |
| Max. process+thread count | 2919 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2799/5/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by liuml07 — APPROVED** [review]

**Pull request merged**
