### PR TITLE
HDDS-2063. Integration tests create untracked file audit.log

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

`audit.log` is only tested by `TestOzoneRpcClientForAclAuditLog`, but its `log4j2.properties` is being picked up by other tests, too.  This change renames the test config file to some custom one to avoid that.

https://issues.apache.org/jira/browse/HDDS-2063

## How was this patch tested?

```
$ mvn -Phdds -pl :hadoop-ozone-integration-test test -Dtest=TestOzoneRpcClientForAclAuditLog
...
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.81 s - in org.apache.hadoop.ozone.client.rpc.TestOzoneRpcClientForAclAuditLog
...
$ git status
On branch HDDS-2063
nothing to commit, working tree clean

$ mvn -Phdds -pl :hadoop-ozone-integration-test test -Dtest=Test2WayCommitInRatis
...
$ git status
On branch HDDS-2063
nothing to commit, working tree clean
```

### CODE REVIEW

**Comment by dineshchitlangia** [comment]
@adoroszlai Thanks for filing the jira and posting a patch. +1 LGTM (pending CI)

**Comment by adoroszlai** [comment]
Thanks for the review @dineshchitlangia.

Integration test failures are unrelated (one of them is being fixed in HDDS-2061, the rest are the usual flaky ones).

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 46 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 646 | trunk passed |
| +1 | compile | 398 | trunk passed |
| +1 | checkstyle | 85 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 929 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 185 | trunk passed |
| 0 | spotbugs | 440 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 648 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 610 | the patch passed |
| +1 | compile | 407 | the patch passed |
| +1 | javac | 407 | the patch passed |
| +1 | checkstyle | 86 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 724 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 185 | the patch passed |
| +1 | findbugs | 699 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 310 | hadoop-hdds in the patch passed. |
| -1 | unit | 2637 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 54 | The patch does not generate ASF License warnings. |
| | | 8848 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.container.common.statemachine.commandhandler.TestBlockDeletion |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.TestMiniChaosOzoneCluster |
|   | hadoop.ozone.client.rpc.TestDeleteWithSlowFollower |
|   | hadoop.ozone.TestOzoneConfigurationFields |
|   | hadoop.ozone.client.rpc.TestCommitWatcher |
|   | hadoop.ozone.client.rpc.TestReadRetries |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1384/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1384 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux de74e9eacd93 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c929b38 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1384/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1384/1/testReport/ |
| Max. process+thread count | 3364 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/integration-test U: hadoop-ozone/integration-test |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1384/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by dineshchitlangia** [comment]
Confirmed. Integration test failures are unrelated to the patch 👍

**Comment by bharatviswa504** [comment]
Thank You @adoroszlai for the fix.
It really helps, as after running tests, this file will be created, and to commit if I use `git add .`, this untracked file also gets added.

**Comment by adoroszlai** [comment]
Thanks @bharatviswa504 for committing it.

**Pull request merged**
