### PR TITLE
HADOOP-16949. pylint fails in the build environment

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/HADOOP-16949

### CODE REVIEW

**Comment by aajisaka** [comment]
OK
```
$ ./start-build-env.sh
(snip)
aajisaka@e768084b5f53:~/hadoop$ pylint --version
No config file found, using default configuration
pylint 1.9.2, 
astroid 1.6.6
Python 2.7.12 (default, Oct  8 2019, 14:14:10) 
[GCC 5.4.0 20160609]
```

**Comment by aajisaka** [comment]
Hi @vinayakumarb , would you check this in the ARM environment?

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/hadoop-multibranch/job/PR-1926/1/console in case of problems.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   4m 13s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 23s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  shadedclient  |  14m 19s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| -1 :x: |  hadolint  |   0m  6s |  The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  13m 58s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   |  35m 54s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1926/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1926 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs |
| uname | Linux 3d36fb0b124a 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 960c9eb |
| hadolint | https://builds.apache.org/job/hadoop-multibranch/job/PR-1926/1/artifact/out/diff-patch-hadolint.txt |
| Max. process+thread count | 420 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1926/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.3.7 hadolint=1.11.1-0-g0e692dd |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/hadoop-multibranch/job/PR-1926/2/console in case of problems.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   4m 19s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  1s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 31s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  shadedclient  |  16m 21s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  hadolint  |   0m  5s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 20s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 30s |  The patch does not generate ASF License warnings.  |
|  |   |  39m 14s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1926/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1926 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs |
| uname | Linux 4a42660aeb5e 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 80b877a |
| Max. process+thread count | 311 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1926/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.3.7 hadolint=1.11.1-0-g0e692dd |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
Thank you, @iwasakims !

**Pull request merged**
