### PR TITLE
HADOOP-16905. Update jackson-databind to 2.10.3 to relieve us from the endless CVE patches.

### PR DESCRIPTION
**Pull request by jojochuang**

### CODE REVIEW

**Comment by jojochuang** [comment]
This is a clean backport.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  10m 37s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  22m 25s |  branch-3.2 passed  |
| -1 :x: |  compile  |   6m  6s |  root in branch-3.2 failed.  |
| +1 :green_heart: |  mvnsite  |   0m 35s |  branch-3.2 passed  |
| +1 :green_heart: |  shadedclient  |  43m 34s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 35s |  branch-3.2 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 36s |  the patch passed  |
| -1 :x: |  compile  |   5m 39s |  root in the patch failed.  |
| -1 :x: |  javac  |   5m 39s |  root in the patch failed.  |
| +1 :green_heart: |  mvnsite  |   0m 31s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  5s |  The patch has no ill-formed XML file.  |
| -1 :x: |  shadedclient  |  13m 57s |  patch has errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 32s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 13s |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 18s |  hadoop-client-runtime in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 30s |  The patch does not generate ASF License warnings.  |
|  |   |  81m 50s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1973/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1973 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux da057da96707 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | branch-3.2 / e154d9d |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1973/1/artifact/out/branch-compile-root.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1973/1/artifact/out/patch-compile-root.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-1973/1/artifact/out/patch-compile-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1973/1/testReport/ |
| Max. process+thread count | 304 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-client-modules/hadoop-client-runtime U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1973/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
Triggered rebuild. The failure is unrelated, due to YARN-10063 which I reverted.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 25s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  21m 11s |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |  16m 27s |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |   0m 52s |  branch-3.2 passed  |
| +1 :green_heart: |  shadedclient  |  52m 43s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 50s |  branch-3.2 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 33s |  the patch passed  |
| +1 :green_heart: |  compile  |  15m 42s |  the patch passed  |
| +1 :green_heart: |  javac  |  15m 42s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 53s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| -1 :x: |  shadedclient  |  13m 35s |  patch has errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 52s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 23s |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 26s |  hadoop-client-runtime in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 44s |  The patch does not generate ASF License warnings.  |
|  |   |  93m 11s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1973/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1973 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 5f8b1a87dbe7 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | branch-3.2 / 48f1c8f |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1973/2/testReport/ |
| Max. process+thread count | 309 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-client-modules/hadoop-client-runtime U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1973/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
In the branch-3.2, this PR fails with:

[ERROR] Found artifact with unexpected contents: '/Users/weichiu/sandbox/hadoop/hadoop-client-modules/hadoop-client-api/target/hadoop-client-api-3.2.2-SNAPSHOT.jar'
    Please check the following and either correct the build or update
    the allowed list with reasoning.

    javax/
    javax/activation/
    javax/activation/CommandInfo$Beans$1.class
    javax/activation/MimeTypeParseException.class
    javax/activation/CommandObject.class
    javax/activation/MailcapCommandMap$1.class
    javax/activation/DataSourceDataContentHandler.class
    javax/activation/FileDataSource.class
    javax/activation/CommandMap.class
    javax/activation/SecuritySupport$5.class
    javax/activation/CommandInfo.class
    javax/activation/MimeTypeParameterList.class
    javax/activation/SecuritySupport$3.class
    javax/activation/MimetypesFileTypeMap$1.class
    javax/activation/UnsupportedDataTypeException.class
    javax/activation/CommandInfo$Beans.class
    javax/activation/FileTypeMap.class
    javax/activation/MimetypesFileTypeMap.class
    javax/activation/DataHandlerDataSource.class
    javax/activation/DataSource.class
    javax/activation/MailcapCommandMap.class
    javax/activation/SecuritySupport$1.class
    javax/activation/ActivationDataFlavor.class
    javax/activation/SecuritySupport$2.class
    javax/activation/DataHandler.class
    javax/activation/SecuritySupport$4.class
    javax/activation/ObjectDataContentHandler.class
    javax/activation/SecuritySupport.class
    javax/activation/DataContentHandlerFactory.class
    javax/activation/MimeType.class
    javax/activation/DataContentHandler.class
    javax/activation/URLDataSource.class
    javax/activation/DataHandler$1.class

We probably need HADOOP-15775 too.

**Comment by jojochuang** [comment]
Hm adding HADOOP-15775 did pass the build. However that's not right since we don't actually use javax.activation so we shouldn't add it as a runtime dependency. Instead I should update this patch to relocate javax.activation classes.

Note, I couldn't find the source of the javax activation classes. They are not in the dependency tree, nor are they shaded into the jackson-*-2.10.3.jar.

**Comment by AnanyaSingh2121** [comment]
Hi, I am able to build Hadoop v3.2.2 successfully by ignoring the changes in "hadoop-client-modules/hadoop-client-runtime/pom.xml" and just changing the jackson-databind version to 2.10.3 in "hadoop-project/pom.xml"

**Comment by brahmareddybattula** [comment]
@AnanyaSingh2121 thanks .. @jojochuang can you please check once..?

**Comment by brahmareddybattula** [comment]
@jojochuang  let @AnanyaSingh2121  raise jira to handle this..? what's your opinion on this..?

**Pull request closed without merging**
