### PR TITLE
HDDS-1998. TestSecureContainerServer#testClientServerRatisGrpc is fai…

### PR DESCRIPTION
**Pull request by pingsutw**
…ling

### CODE REVIEW

**Comment by bshashikant** [comment]
Thanks @pingsutw for working on this. The test while asserting the exception type to be of type IOException also needs to validate the underlying exception is StorageContainerException with code BLOCK_TOKEN_VERIFICATION_FAILURE. Can you please add this as well?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 82 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 665 | trunk passed |
| +1 | compile | 380 | trunk passed |
| +1 | checkstyle | 82 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 960 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 183 | trunk passed |
| 0 | spotbugs | 449 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 659 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 606 | the patch passed |
| +1 | compile | 389 | the patch passed |
| +1 | javac | 389 | the patch passed |
| +1 | checkstyle | 73 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 760 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 163 | the patch passed |
| +1 | findbugs | 715 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 360 | hadoop-hdds in the patch passed. |
| -1 | unit | 2533 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 48 | The patch does not generate ASF License warnings. |
| | | 8797 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures |
|   | hadoop.ozone.client.rpc.Test2WayCommitInRatis |
|   | hadoop.hdds.scm.pipeline.TestRatisPipelineCreateAndDestory |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1328/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1328 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 092dd9822f55 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / ee7c261 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1328/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1328/1/testReport/ |
| Max. process+thread count | 5227 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/integration-test U: hadoop-ozone/integration-test |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1328/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by pingsutw** [comment]
@bshashikant thanks for the reply,
we can't get **_ContainerCommandResponseProto response_** from _**finalClient.sendCommand(request)**_ due to IOException.

but we can know StorageContainerException from ex.getMessage()
how could I get StorageContainerException instance from IOException

**Comment by adoroszlai** [comment]
@pingsutw unfortunately it's not available from the `IOException`; `rootCause` is a `StateMachineException` and only its message refers to the `StorageContainerException`.

```java
        IOException e = LambdaTestUtils.intercept(IOException.class,
            () -> finalClient.sendCommand(request));
        Throwable rootCause = ExceptionUtils.getRootCause(e);
        String msg = rootCause.getMessage();
        assertTrue(msg, msg.contains("Block token verification failed"));
```

**Comment by pingsutw** [comment]
@adoroszlai Thanks for your help
Updated the patch

**Comment by adoroszlai** [comment]
@bshashikant can you please review the updated patch?

```
[INFO] Running org.apache.hadoop.ozone.container.server.TestSecureContainerServer
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 15.943 s - in org.apache.hadoop.ozone.container.server.TestSecureContainerServer
```

**Comment by bshashikant** [comment]
Thanks @pingsutw for working on this. The change looks good to me. I am +1 on the change.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 10 | https://github.com/apache/hadoop/pull/1328 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/1328 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1328/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
