### PR TITLE
HDFS-15232. Fix libhdfspp test failures with GCC 7.

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/HDFS-15232

### CODE REVIEW

**Comment by smengcl** [comment]
lgtm. +1

**Comment by aajisaka** [comment]
The precommit job report:

https://builds.apache.org/job/hadoop-multibranch/view/change-requests/job/PR-1906/lastBuild/artifact/out/gitcommentfile.1

---

:broken_heart: **-1 overall**

| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 80 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1306 | trunk passed |
| +1 | compile | 109 | trunk passed |
| +1 | mvnsite | 21 | trunk passed |
| +1 | shadedclient | 2368 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 14 | the patch passed |
| +1 | compile | 105 | the patch passed |
| +1 | cc | 105 | the patch passed |
| +1 | golang | 105 | the patch passed |
| +1 | javac | 105 | the patch passed |
| +1 | mvnsite | 14 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 913 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 420 | hadoop-hdfs-native-client in the patch passed. |
| +1 | asflicense | 30 | The patch does not generate ASF License warnings. |
| | | 4095 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1906/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1906 |
| Optional Tests | dupname asflicense compile cc mvnsite javac unit golang |
| uname | Linux 175de3261623 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 62c80156833 |
| Default Java | 1.8.0_242 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1906/1/testReport/ |
| Max. process+thread count | 307 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-native-client U: hadoop-hdfs-project/hadoop-hdfs-native-client |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1906/1/console |
| versions | git=2.17.1 maven=3.6.0[m |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
Thank you, @smengcl

**Comment by smengcl** [comment]
Thanks for the patch, @aajisaka !

**Pull request merged**
