### PR TITLE
HADOOP-16472. findbugs warning on LocalMetadataStore.ttlTimeProvider sync

### PR DESCRIPTION
**Pull request by steveloughran**
Moved the setter and addAncestors to synchronized

Untested! Let's see what findbugs says first

### CODE REVIEW

**Comment by bgaborg** [comment]
I wanted to do the same fix, so if findbugs is happy I'll commit.

**Comment by steveloughran** [comment]
thx. somehow we missed this earlier

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 45 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1051 | trunk passed |
| +1 | compile | 34 | trunk passed |
| +1 | checkstyle | 20 | trunk passed |
| +1 | mvnsite | 39 | trunk passed |
| +1 | shadedclient | 670 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 25 | trunk passed |
| 0 | spotbugs | 58 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| -1 | findbugs | 55 | hadoop-tools/hadoop-aws in trunk has 1 extant findbugs warnings. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 32 | the patch passed |
| +1 | compile | 27 | the patch passed |
| +1 | javac | 27 | the patch passed |
| -0 | checkstyle | 16 | hadoop-tools/hadoop-aws: The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0) |
| +1 | mvnsite | 32 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 696 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 21 | the patch passed |
| +1 | findbugs | 63 | hadoop-tools/hadoop-aws generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
||| _ Other Tests _ |
| +1 | unit | 280 | hadoop-aws in the patch passed. |
| +1 | asflicense | 25 | The patch does not generate ASF License warnings. |
| | | 3192 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1186/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1186 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 2983e3b0c642 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c75f16d |
| Default Java | 1.8.0_212 |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-1186/1/artifact/out/branch-findbugs-hadoop-tools_hadoop-aws-warnings.html |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1186/1/artifact/out/diff-checkstyle-hadoop-tools_hadoop-aws.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1186/1/testReport/ |
| Max. process+thread count | 412 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-aws U: hadoop-tools/hadoop-aws |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1186/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 130 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1327 | trunk passed |
| +1 | compile | 34 | trunk passed |
| +1 | checkstyle | 25 | trunk passed |
| +1 | mvnsite | 46 | trunk passed |
| +1 | shadedclient | 813 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 28 | trunk passed |
| 0 | spotbugs | 73 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| -1 | findbugs | 70 | hadoop-tools/hadoop-aws in trunk has 1 extant findbugs warnings. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 31 | the patch passed |
| +1 | compile | 30 | the patch passed |
| +1 | javac | 30 | the patch passed |
| -0 | checkstyle | 17 | hadoop-tools/hadoop-aws: The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0) |
| +1 | mvnsite | 39 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 836 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 23 | the patch passed |
| +1 | findbugs | 67 | hadoop-tools/hadoop-aws generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1) |
||| _ Other Tests _ |
| +1 | unit | 283 | hadoop-aws in the patch passed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 3904 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1186/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1186 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 685fa65c9da9 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / f86de6f |
| Default Java | 1.8.0_212 |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-1186/2/artifact/out/branch-findbugs-hadoop-tools_hadoop-aws-warnings.html |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1186/2/artifact/out/diff-checkstyle-hadoop-tools_hadoop-aws.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1186/2/testReport/ |
| Max. process+thread count | 323 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-aws U: hadoop-tools/hadoop-aws |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1186/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
That's the same sync problem; I'm going to merge this one in.

I don't care about a line length of 81; we are allowed to ignore that 81 char width rule if we think it would be worse for the code visibility to chop things...the last time there was a vote on it the consensus was "not widen because it makes side-by-side review harder". Once the move to github reviews is complete, we can explore that decision again. After all, monitors have got bigger...

**Pull request merged**
