### PR TITLE
HADOOP-18044. Hadoop - Upgrade to jQuery 3.6.0

### PR DESCRIPTION
**Pull request by luoyuan3471**
jQuery 3.6.0 has been released few months ago - http://blog.jquery.com/2021/03/02/jquery-3-6-0-released/ 

We can upgrade jquery-3.5.1.min.js to jquery-3.6.0.min.js in hadoop project.

### CODE REVIEW

**Comment by brahmareddybattula** [comment]
@luoyuan3471 thanks for reporting.. Did you get chance verify with version..? It'll be good if you can verify and update the status.

**Comment by luoyuan3471** [comment]
@brahmareddybattula Thanks for your reply. In our YARN cluster contains thousands of nodes, we upgraded jquery version from 3.5.1->3.6.0. It has been running for more than a month and no problems have been found.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  44m 51s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  shellcheck  |   0m  0s |  |  Shellcheck was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +0 :ok: |  jshint  |   0m  0s |  |  jshint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  12m 32s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  25m 21s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  20m 51s |  |  trunk passed  |
| +1 :green_heart: |  checkstyle  |   4m  3s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |  27m  4s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   8m 42s |  |  trunk passed  |
| +1 :green_heart: |  spotbugs  |  41m 58s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  57m 58s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 24s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  27m 40s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  20m 16s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  20m 16s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   3m 54s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  26m 11s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  4s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   9m 12s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |  42m 59s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  58m 14s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 1039m 33s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3791/2/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 45s |  |  The patch does not generate ASF License warnings.  |
|  |   | 1406m 17s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.rbfbalance.TestRouterDistCpProcedure |
|   | hadoop.hdfs.server.federation.router.TestRouterRPCMultipleDestinationMountTableResolver |
|   | hadoop.hdfs.server.diskbalancer.command.TestDiskBalancerCommand |
|   | hadoop.tools.dynamometer.TestDynamometerInfra |
|   | hadoop.yarn.csi.client.TestCsiClient |
|   | hadoop.ipc.TestIPC |
|   | hadoop.crypto.TestCryptoStreamsWithOpensslSm4CtrCryptoCodec |
|   | hadoop.crypto.TestCryptoCodec |
|   | hadoop.service.launcher.TestServiceInterruptHandling |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3791/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3791 |
| Optional Tests | dupname asflicense codespell shellcheck shelldocs shadedclient compile javac javadoc mvninstall mvnsite unit xml jshint spotbugs checkstyle |
| uname | Linux 8fae8b6cfd9e 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 88552f2f2175956a25a728dd6b1c69b0c718b116 |
| Default Java | Red Hat, Inc.-1.8.0_312-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3791/2/testReport/ |
| Max. process+thread count | 2256 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-hdfs-project/hadoop-hdfs-rbf . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3791/2/console |
| versions | git=2.9.5 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by jojochuang — APPROVED** [review]
looking at PR #2330 and #2340, this is all we need assuming no backward incompatible changes in jQuery itself.

**Comment by luoyuan3471** [comment]
Any concern about this PR?

**Comment by jojochuang** [comment]
Merged to trunk. I think we can have this in the next 3.3.x release, which is 3.3.3.

**Comment by brahmareddybattula** [comment]
@jojochuang Can we merge this other branches also..? Specifically for branch-3.2.3 also..?

**Comment by jojochuang** [comment]
The commit applies cleanly against branch-3.3. branch-3.2 has some conflicts because the jQuery 3.5.1 updates were not cherrypicked to branch-3.2. So you'd need to backport them too (not clean).

**Pull request merged**
