### PR TITLE
HADOOP-18169. getDelegationTokens in ViewFs should also fetch the token from fallback FS

### PR DESCRIPTION
**Pull request by xinglin**
### Description of PR

cherry-pick of 15a5ea2c955a7d1b89aea0cb127727a57db76c76 from trunk to branch-2.10 and created TestViewFsLinkFallback.java file with one test case included.

All other test cases in TestViewFsLinkFallback.java from trunk are removed, as the implementation of InternalDirOfViewFs (createInternal function) is out of date and these test cases won't pass. Leave the fix and the inclusion of these other unit tests as a future pull request.

### How was this patch tested?

mvn test -Dtest="TestViewFsLinkFallback"

### CODE REVIEW

**Comment by xinglin** [comment]
@omalley, 

Here is the backport for DelegationToken for 2.10. Could you take a look? Thanks,

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 35s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-2.10 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 21s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  12m 12s |  |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |  13m  8s |  |  branch-2.10 passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  compile  |  10m 45s |  |  branch-2.10 passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  checkstyle  |   1m 50s |  |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |   2m 30s |  |  branch-2.10 passed  |
| +1 :green_heart: |  javadoc  |   2m 43s |  |  branch-2.10 passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javadoc  |   2m  2s |  |  branch-2.10 passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| -1 :x: |  spotbugs  |   2m  2s | [/branch-spotbugs-hadoop-common-project_hadoop-common-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/1/artifact/out/branch-spotbugs-hadoop-common-project_hadoop-common-warnings.html) |  hadoop-common-project/hadoop-common in branch-2.10 has 2 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   2m 31s | [/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/1/artifact/out/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-warnings.html) |  hadoop-hdfs-project/hadoop-hdfs in branch-2.10 has 1 extant spotbugs warnings.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 20s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 37s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  12m 21s |  |  the patch passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javac  |  12m 21s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  10m 46s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  javac  |  10m 46s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m 50s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m 28s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 40s |  |  the patch passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javadoc  |   2m  4s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  spotbugs  |   4m 51s |  |  the patch passed  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |   8m 24s | [/patch-unit-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/1/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt) |  hadoop-common in the patch passed.  |
| -1 :x: |  unit  |  62m 56s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 56s |  |  The patch does not generate ASF License warnings.  |
|  |   | 169m 34s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.io.compress.snappy.TestSnappyCompressorDecompressor |
|   | hadoop.io.compress.TestCompressorDecompressor |
|   | hadoop.fs.sftp.TestSFTPFileSystem |
|   | hadoop.hdfs.qjournal.server.TestJournalNodeRespectsBindHostKeys |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4128 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 2d6802dd4aa1 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / 88a556b79fdc6952d10a6c771f7b436349830a5c |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_262-b10 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/1/testReport/ |
| Max. process+thread count | 2709 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by mccormickt12 — APPROVED** [review]
This change alone seems fine. 
It would be good and helpful for others reviewing to identify the differences in viewfs to explain why the rest of the tests couldn't be backported, but thats more of a nice to have, not required to ship it

**Comment by xinglin** [comment]
> This change alone seems fine. It would be good and helpful for others reviewing to identify the differences in viewfs to explain why the rest of the tests couldn't be backported, but thats more of a nice to have, not required to ship it

@mccormickt12 thanks for taking a quick review. 

create() method in InternalDirOfViewFs diverged between trunk and branch-2.10. In trunk, when fallbackFS is configured, we can create a file but in branch-2.10, it does not do the check whether fallbackFS exists and simply throws "read-only fs" exception, thus failing these unit tests.

**Comment by xinglin** [comment]
InternalDirOfViewFs class in trunk has two more members than in branch-2.10. Without access to fsState, we can not check whether a fallbackFS is set or not. Does not seem trivial to bring InternalDirOfViewFs in branch-2.10 to be in sync with trunk. Leave it as a separate patch for future. 

```
    private final boolean showMountLinksAsSymlinks;
    private InodeTree<FileSystem> fsState;
```

**Comment by virajith** [comment]
Thanks for backporting this @xinglin and explaining what's not present in 2.10. As the rest of the functionality doesn't exist, I am good with having the required test backported. Can you please rebase your branch and push it again so Yetus gives a positive run? I am +1 on merging this PR after that.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   8m 12s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-2.10 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m  3s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  13m 58s |  |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |  13m 12s |  |  branch-2.10 passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  compile  |  10m 50s |  |  branch-2.10 passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  checkstyle  |   2m  6s |  |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |   2m 36s |  |  branch-2.10 passed  |
| +1 :green_heart: |  javadoc  |   2m 47s |  |  branch-2.10 passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javadoc  |   2m  9s |  |  branch-2.10 passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| -1 :x: |  spotbugs  |   2m 28s | [/branch-spotbugs-hadoop-common-project_hadoop-common-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/2/artifact/out/branch-spotbugs-hadoop-common-project_hadoop-common-warnings.html) |  hadoop-common-project/hadoop-common in branch-2.10 has 2 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   2m 33s | [/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-warnings.html](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/2/artifact/out/branch-spotbugs-hadoop-hdfs-project_hadoop-hdfs-warnings.html) |  hadoop-hdfs-project/hadoop-hdfs in branch-2.10 has 1 extant spotbugs warnings.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 24s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 38s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  12m 23s |  |  the patch passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javac  |  12m 23s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  10m 46s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  javac  |  10m 46s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m  2s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m 30s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 39s |  |  the patch passed with JDK Azul Systems, Inc.-1.7.0_262-b10  |
| +1 :green_heart: |  javadoc  |   2m 10s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07  |
| +1 :green_heart: |  spotbugs  |   4m 56s |  |  the patch passed  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |   8m 30s | [/patch-unit-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/2/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt) |  hadoop-common in the patch passed.  |
| -1 :x: |  unit  |  63m 37s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/2/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  0s |  |  The patch does not generate ASF License warnings.  |
|  |   | 183m 18s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.io.compress.snappy.TestSnappyCompressorDecompressor |
|   | hadoop.io.compress.TestCompressorDecompressor |
|   | hadoop.fs.sftp.TestSFTPFileSystem |
|   | hadoop.hdfs.server.namenode.ha.TestEditLogTailer |
|   | hadoop.hdfs.qjournal.server.TestJournalNodeRespectsBindHostKeys |
|   | hadoop.hdfs.TestDataTransferKeepalive |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4128 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux c9dcbe54b6da 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / 17b677c42e1dcd5b4236389e1e6735133f698c7e |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_262-b10 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/2/testReport/ |
| Max. process+thread count | 2364 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4128/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by xinglin** [comment]
@virajith rebased last night but I guess we are seeing the same set of unit test failures. these tests have been failing before and don't seem to be related with our patch. Please see another example, where we see the same set of unit test failures for another backport to branch-2.10. I think we can commit this PR.

https://github.com/apache/hadoop/pull/4124

**Comment by virajith** [comment]
The failures in Yetus in the last run are unrelated to the changes in this PR. I will be merging this. Thanks for the backport @xinglin !

**Pull request merged**
