### PR TITLE
YARN-10367. Failed to get nodejs 10.21.0 when building docker image

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/YARN-10367

Install the latest 10.x version of nodejs in the docker image.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/hadoop-multibranch/job/PR-2171/1/console in case of problems.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  30m 46s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   1m 11s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  shadedclient  |  15m 36s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 29s |  Maven dependency ordering for patch  |
| -1 :x: |  hadolint  |   0m  4s |  The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0)  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 14s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 25s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 29s |  The patch does not generate ASF License warnings.  |
|  |   |  65m 53s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-2171/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2171 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs |
| uname | Linux 54e6f5c1751c 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / ac5f21dbef0 |
| hadolint | https://builds.apache.org/job/hadoop-multibranch/job/PR-2171/1/artifact/out/diff-patch-hadolint.txt |
| Max. process+thread count | 338 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-2171/1/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 hadolint=1.11.1-0-g0e692dd |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/hadoop-multibranch/job/PR-2171/2/console in case of problems.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  4s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |   1m 13s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  shadedclient  |  15m 59s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 28s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  hadolint  |   0m  5s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m 14s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 37s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   |  36m 52s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-2171/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2171 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs |
| uname | Linux 1e36fe6cdc45 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 4b1816c7d01 |
| Max. process+thread count | 307 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-2171/2/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 hadolint=1.11.1-0-g0e692dd |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
Thank you @iwasakims for your review! Merged.

**Pull request merged**
