### PR TITLE
HDFS-14638. [Dynamometer] Fix scripts to refer to current build structure.

### PR DESCRIPTION
**Pull request by tasanuma**
## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by jojochuang** [comment]
@smengcl would you like to review this?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 77 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 0 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 34 | Maven dependency ordering for branch |
| +1 | mvninstall | 1234 | trunk passed |
| +1 | mvnsite | 80 | trunk passed |
| +1 | shadedclient | 808 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for patch |
| +1 | mvninstall | 72 | the patch passed |
| +1 | mvnsite | 61 | the patch passed |
| +1 | shellcheck | 1 | There were no new shellcheck issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 896 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 21 | hadoop-dynamometer-workload in the patch passed. |
| +1 | unit | 22 | hadoop-dynamometer-infra in the patch passed. |
| +1 | unit | 21 | hadoop-dynamometer-blockgen in the patch passed. |
| +1 | asflicense | 32 | The patch does not generate ASF License warnings. |
| | | 3497 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1673/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1673 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux 22665cb4a1c6 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / fd84ca5 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1673/1/testReport/ |
| Max. process+thread count | 342 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-workload hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-infra hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-blockgen U: hadoop-tools/hadoop-dynamometer |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1673/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by smengcl** [comment]
Thanks @jojochuang for pinging.

Thanks @tasanuma for the patch. I tested this locally. Those scripts correctly points to the jars now:
```bash
$ mvn install -Pdist -DskipTests -e -Dmaven.javadoc.skip=true
$ cd hadoop-dist/target/hadoop-3.3.0-SNAPSHOT
$ ./share/hadoop/tools/dynamometer/dynamometer-blockgen/bin/generate-block-lists.sh
Exception in thread "main" org.apache.commons.cli.MissingOptionException: Missing required options: fsimage_input_path, block_image_output_dir, num_datanodes
...
$ ./share/hadoop/tools/dynamometer/dynamometer-infra/bin/start-dynamometer-cluster.sh
2019-10-24 09:16:16,098 INFO dynamometer.Client: Initializing Client
2019-10-24 09:16:16,099 ERROR dynamometer.Client: Error running Client
org.apache.commons.cli.MissingOptionException: Missing required option: ...
$ ./share/hadoop/tools/dynamometer/dynamometer-workload/bin/start-workload.sh
Exception in thread "main" org.apache.commons.cli.MissingOptionException: Missing required options: nn_uri, mapper_class_name
...
```

Before the patch is was complaining:
```bash
$ ./share/hadoop/tools/dynamometer/dynamometer-blockgen/bin/generate-block-lists.sh
JAR does not exist or is not a normal file: /Users/smeng/repo/trunk/hadoop-dist/target/hadoop-3.3.0-SNAPSHOT/share/hadoop/tools/dynamometer/dynamometer-blockgen/lib/dynamometer-blockgen-*.jar
```

LGTM +1

**Comment by jojochuang** [comment]
+1 will merge the PR shortly.

**Comment by tasanuma** [comment]
Thanks for reviewing and committing it, @smengcl and @jojochuang!

**Pull request merged**
