### PR TITLE
YARN-11142.Remove unused Imports in Hadoop YARN project

### PR DESCRIPTION
**Pull request by hotcodemacha**
### Description of PR
Remove unused Imports in Hadoop YARN project
* JIRA: YARN-11142

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?

### CODE REVIEW

**Comment by ayushtkn** [comment]
Do you plan to backport this as well? Would be good if you do so, else cherry-picking other commits will be painful because of this causing conflicts.
BTW. can you assign the jira on your name, if it isn't. I saw some other name. else someone like me will commit this giving credits to the guy assigned to the jira. :-)

**Comment by hotcodemacha** [comment]
@ayushtkn - Thanks for checking

>Do you plan to backport this as well? Would be good if you do so, else cherry-picking other commits will be painful because of this causing conflicts.

I can create a separate PR for backport after the trunk is done. 

>BTW. can you assign the jira on your name, if it isn't. I saw some other name. else someone like me will commit this giving credits to the guy assigned to the jira. :-)

The Jira is assigned on my name only :)

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 45s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  1s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 31 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 16s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  25m 11s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   9m 56s |  |  trunk passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  compile  |   8m 52s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  checkstyle  |   2m 28s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |  17m 39s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |  16m 37s |  |  trunk passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |  15m 22s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +0 :ok: |  spotbugs  |   1m 13s |  |  branch/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-tests no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  21m 53s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 31s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   8m 39s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   9m 13s |  |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javac  |   9m 13s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   8m 46s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |   8m 46s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m 11s |  |  hadoop-yarn-project/hadoop-yarn: The patch generated 0 new + 772 unchanged - 92 fixed = 772 total (was 864)  |
| +1 :green_heart: |  mvnsite  |  15m 34s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |  14m 19s |  |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |  13m 26s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +0 :ok: |  spotbugs  |   1m  4s |  |  hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-tests has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  22m  9s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 41s |  |  hadoop-yarn-api in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 31s |  |  hadoop-yarn-common in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 20s |  |  hadoop-yarn-server-applicationhistoryservice in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 52s |  |  hadoop-yarn-server-web-proxy in the patch passed.  |
| +1 :green_heart: |  unit  |  98m  9s |  |  hadoop-yarn-server-resourcemanager in the patch passed.  |
| +1 :green_heart: |  unit  |  24m 27s |  |  hadoop-yarn-server-nodemanager in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 58s |  |  hadoop-yarn-server-tests in the patch passed.  |
| +1 :green_heart: |  unit  |  28m 47s |  |  hadoop-yarn-client in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 18s |  |  hadoop-yarn-server-timeline-pluginstorage in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 28s |  |  hadoop-yarn-server-timelineservice-hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |  23m 30s |  |  hadoop-yarn-applications-distributedshell in the patch passed.  |
| +1 :green_heart: |  unit  |  21m 40s |  |  hadoop-yarn-services-core in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 56s |  |  hadoop-yarn-applications-catalog-webapp in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 40s |  |  The patch does not generate ASF License warnings.  |
|  |   | 504m 35s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4381/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4381 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 161993848dfa 4.15.0-169-generic #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 1ae51333aec6006f17a79bd8e5b2501eed811c16 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4381/1/testReport/ |
| Max. process+thread count | 995 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-web-proxy hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-tests hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timeline-pluginstorage hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase/hadoop-yarn-server-timelineservice-hbase-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services/hadoop-yarn-services-core hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-catalog/hadoop-yarn-applications-catalog-webapp U: hadoop-yarn-project/hadoop-yarn |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4381/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by ayushtkn — APPROVED** [review]
+1

**Pull request merged**
