### PR TITLE
HDDS-1471. Update ratis dependency to 0.3.0. Contributed by Ajay Kumar.

### PR DESCRIPTION
**Pull request by ajayydv**

### CODE REVIEW

**Comment by anuengineer** [comment]
+1, Thanks for getting this done. Appreciate it.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 90 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 332 | Maven dependency ordering for branch |
| +1 | mvninstall | 1097 | trunk passed |
| +1 | compile | 1063 | trunk passed |
| -1 | mvnsite | 68 | hadoop-ozone in trunk failed. |
| +1 | shadedclient | 3374 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 231 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for patch |
| +1 | mvninstall | 392 | the patch passed |
| +1 | compile | 965 | the patch passed |
| +1 | javac | 965 | the patch passed |
| +1 | mvnsite | 246 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 3 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 684 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 153 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 274 | hadoop-hdds in the patch failed. |
| -1 | unit | 1683 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 52 | The patch does not generate ASF License warnings. |
| | | 8375 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.scm.block.TestBlockManager |
|   | hadoop.ozone.ozShell.TestOzoneShell |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestCommitWatcher |
|   | hadoop.hdds.scm.pipeline.TestNode2PipelineMap |
|   | hadoop.ozone.om.TestOzoneManager |
|   | hadoop.ozone.container.TestContainerReplication |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-777/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/777 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  xml  |
| uname | Linux 6392affc92e1 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3758270 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-777/1/artifact/out/branch-mvnsite-hadoop-ozone.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-777/1/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-777/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-777/1/testReport/ |
| Max. process+thread count | 3632 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds hadoop-ozone U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-777/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by ajayydv** [comment]
@anuengineer thanks for review, committed to trunk and 0.4

**Pull request merged**
