### PR TITLE
HDDS-1959. Decrement purge interval for Ratis logs in datanode

### PR DESCRIPTION
**Pull request by pingsutw**

### CODE REVIEW

**Comment by lokeshj1703** [comment]
@pingsutw Thanks for working on the PR! The changes look good to me. +1. Pending jenkins.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 91 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 633 | trunk passed |
| +1 | compile | 410 | trunk passed |
| +1 | checkstyle | 75 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 955 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 189 | trunk passed |
| 0 | spotbugs | 497 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 742 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 589 | the patch passed |
| +1 | compile | 405 | the patch passed |
| +1 | javac | 405 | the patch passed |
| +1 | checkstyle | 81 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 745 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 189 | the patch passed |
| +1 | findbugs | 773 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 359 | hadoop-hdds in the patch passed. |
| -1 | unit | 3260 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 44 | The patch does not generate ASF License warnings. |
| | | 9705 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.scm.pipeline.TestRatisPipelineCreateAndDestory |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.ozone.om.TestSecureOzoneManager |
|   | hadoop.ozone.client.rpc.TestReadRetries |
|   | hadoop.ozone.TestContainerStateMachineIdempotency |
|   | hadoop.ozone.client.rpc.TestBCSID |
|   | hadoop.ozone.client.rpc.TestCloseContainerHandlingByClient |
|   | hadoop.ozone.client.rpc.TestCommitWatcher |
|   | hadoop.ozone.TestMiniChaosOzoneCluster |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1301/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1301 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml |
| uname | Linux 48570151af7a 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 9b8359b |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1301/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1301/1/testReport/ |
| Max. process+thread count | 2975 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common U: hadoop-hdds/common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1301/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by lokeshj1703** [comment]
@pingsutw Thanks for the contribution! The test failures do not seem related. I have merged the PR with trunk branch.

**Comment by pingsutw** [comment]
@lokeshj1703  Thank you so much

**Pull request merged**
