### PR TITLE
HDDS-1710. Fix checkstyle errors

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Fix [checkstyle errors](https://ci.anzix.net/job/ozone-nightly/182/checkstyle/) related to [HDDS-1710](https://issues.apache.org/jira/browse/HDDS-1710).

## How was this patch tested?

```
$ mvn -Phdds -DskipTests -DskipShade -am -pl :hadoop-ozone-dist clean package
$ hadoop-ozone/dev-support/checks/checkstyle.sh
...
[INFO] BUILD SUCCESS
```

### CODE REVIEW

**Comment by adoroszlai** [comment]
@anuengineer @elek please review

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 36 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 79 | Maven dependency ordering for branch |
| +1 | mvninstall | 596 | trunk passed |
| +1 | compile | 343 | trunk passed |
| +1 | checkstyle | 72 | trunk passed |
| +1 | mvnsite | 1 | trunk passed |
| +1 | shadedclient | 857 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 146 | trunk passed |
| 0 | spotbugs | 412 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 600 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 30 | Maven dependency ordering for patch |
| +1 | mvninstall | 532 | the patch passed |
| +1 | compile | 380 | the patch passed |
| +1 | javac | 380 | the patch passed |
| +1 | checkstyle | 29 | hadoop-hdds: The patch generated 0 new + 0 unchanged - 5 fixed = 0 total (was 5) |
| +1 | checkstyle | 35 | hadoop-ozone: The patch generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2) |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 647 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 151 | the patch passed |
| +1 | findbugs | 636 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 278 | hadoop-hdds in the patch passed. |
| -1 | unit | 159 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 32 | The patch does not generate ASF License warnings. |
| | | 5791 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.om.ratis.TestOzoneManagerDoubleBufferWithOMResponse |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1144/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1144 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 643d465c322c 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / eb36b09 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1144/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1144/1/testReport/ |
| Max. process+thread count | 558 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-hdds/container-service hadoop-hdds/server-scm hadoop-ozone/ozone-manager U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1144/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by anuengineer** [comment]
Thanks for your contribution. I have committed this patch to trunk and ozone-0.4.1 branches.

**Pull request closed without merging**
