### PR TITLE
YARN-9093. Remove commented code block from the beginning of TestDefa…

### PR DESCRIPTION
**Pull request by vbmudalige**
…ultContainerExecutor

### CODE REVIEW

**Comment by szilard-nemeth** [comment]
Hi @vbmudalige !
Thanks for this patch.
LGTM + 1 (non-binding)

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 81 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1218 | trunk passed |
| +1 | compile | 66 | trunk passed |
| +1 | checkstyle | 26 | trunk passed |
| +1 | mvnsite | 43 | trunk passed |
| +1 | shadedclient | 817 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 26 | trunk passed |
| 0 | spotbugs | 81 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 80 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 38 | the patch passed |
| +1 | compile | 63 | the patch passed |
| +1 | javac | 63 | the patch passed |
| +1 | checkstyle | 21 | the patch passed |
| +1 | mvnsite | 39 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 834 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 25 | the patch passed |
| +1 | findbugs | 92 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 1339 | hadoop-yarn-server-nodemanager in the patch passed. |
| +1 | asflicense | 28 | The patch does not generate ASF License warnings. |
| | | 4912 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-444/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/444 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 9b72f97d6078 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / cd967c7 |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-444/1/testReport/ |
| Max. process+thread count | 306 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager U: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-444/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 91 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1217 | trunk passed |
| +1 | compile | 65 | trunk passed |
| +1 | checkstyle | 25 | trunk passed |
| +1 | mvnsite | 41 | trunk passed |
| +1 | shadedclient | 763 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 30 | trunk passed |
| 0 | spotbugs | 91 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 90 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 51 | the patch passed |
| +1 | compile | 74 | the patch passed |
| +1 | javac | 74 | the patch passed |
| +1 | checkstyle | 25 | the patch passed |
| +1 | mvnsite | 39 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 817 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 24 | the patch passed |
| +1 | findbugs | 88 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 1289 | hadoop-yarn-server-nodemanager in the patch passed. |
| +1 | asflicense | 26 | The patch does not generate ASF License warnings. |
| | | 4835 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-444/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/444 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 1d565a981cfa 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c7c7a88 |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-444/2/testReport/ |
| Max. process+thread count | 306 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager U: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-444/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 76 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1350 | trunk passed |
| +1 | compile | 70 | trunk passed |
| +1 | checkstyle | 22 | trunk passed |
| +1 | mvnsite | 40 | trunk passed |
| +1 | shadedclient | 806 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 28 | trunk passed |
| 0 | spotbugs | 94 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 91 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 45 | the patch passed |
| +1 | compile | 71 | the patch passed |
| +1 | javac | 71 | the patch passed |
| +1 | checkstyle | 24 | the patch passed |
| +1 | mvnsite | 44 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 886 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 28 | the patch passed |
| +1 | findbugs | 103 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 1376 | hadoop-yarn-server-nodemanager in the patch passed. |
| +1 | asflicense | 32 | The patch does not generate ASF License warnings. |
| | | 5180 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-444/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/444 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 7cccbf26d084 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c2d00c8 |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-444/3/testReport/ |
| Max. process+thread count | 414 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager U: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-444/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by szilard-nemeth** [comment]
Hi @vbmudalige 	
Thanks for this patch, change looks good. +1 on this.
Committing now.

**Pull request merged**
