### PR TITLE
HDFS-14678. Allow triggerBlockReport to a specific namenode.

### PR DESCRIPTION
**Pull request by LeonGao91**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 60 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for branch |
| +1 | mvninstall | 1079 | trunk passed |
| +1 | compile | 221 | trunk passed |
| +1 | checkstyle | 59 | trunk passed |
| +1 | mvnsite | 107 | trunk passed |
| +1 | shadedclient | 802 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 78 | trunk passed |
| 0 | spotbugs | 160 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 278 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 9 | Maven dependency ordering for patch |
| +1 | mvninstall | 102 | the patch passed |
| +1 | compile | 184 | the patch passed |
| +1 | cc | 184 | the patch passed |
| +1 | javac | 184 | the patch passed |
| -0 | checkstyle | 45 | hadoop-hdfs-project: The patch generated 19 new + 337 unchanged - 2 fixed = 356 total (was 339) |
| +1 | mvnsite | 93 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 676 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 74 | the patch passed |
| +1 | findbugs | 292 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 108 | hadoop-hdfs-client in the patch failed. |
| -1 | unit | 59 | hadoop-hdfs in the patch failed. |
| -1 | asflicense | 26 | The patch generated 1 ASF License warnings. |
| | | 4373 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1252 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle cc |
| uname | Linux 60c44c9912d4 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3cc0ace |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/1/artifact/out/diff-checkstyle-hadoop-hdfs-project.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs-client.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/1/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/1/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 447 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 117 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for branch |
| +1 | mvninstall | 1366 | trunk passed |
| +1 | compile | 214 | trunk passed |
| +1 | checkstyle | 57 | trunk passed |
| +1 | mvnsite | 115 | trunk passed |
| +1 | shadedclient | 909 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 89 | trunk passed |
| 0 | spotbugs | 175 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 316 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 11 | Maven dependency ordering for patch |
| +1 | mvninstall | 120 | the patch passed |
| +1 | compile | 209 | the patch passed |
| +1 | cc | 209 | the patch passed |
| +1 | javac | 209 | the patch passed |
| -0 | checkstyle | 58 | hadoop-hdfs-project: The patch generated 19 new + 337 unchanged - 2 fixed = 356 total (was 339) |
| +1 | mvnsite | 114 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 798 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 87 | the patch passed |
| -1 | findbugs | 26 | hadoop-hdfs-client in the patch failed. |
||| _ Other Tests _ |
| +1 | unit | 128 | hadoop-hdfs-client in the patch passed. |
| -1 | unit | 6562 | hadoop-hdfs in the patch failed. |
| +1 | asflicense | 37 | The patch does not generate ASF License warnings. |
| | | 11602 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure |
|   | hadoop.hdfs.server.datanode.TestLargeBlockReport |
|   | hadoop.hdfs.server.datanode.fsdataset.impl.TestLazyWriter |
|   | hadoop.hdfs.TestDatanodeRegistration |
|   | hadoop.hdfs.server.datanode.fsdataset.impl.TestSpaceReservation |
|   | hadoop.hdfs.server.datanode.TestDataNodeLifeline |
|   | hadoop.hdfs.server.datanode.fsdataset.impl.TestCacheByPmemMappableBlockLoader |
|   | hadoop.hdfs.server.datanode.TestDataNodeHotSwapVolumes |
|   | hadoop.hdfs.qjournal.server.TestJournalNodeSync |
|   | hadoop.hdfs.server.datanode.fsdataset.impl.TestLazyPersistFiles |
|   | hadoop.hdfs.server.datanode.TestBlockCountersInPendingIBR |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1252 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle cc |
| uname | Linux 9b2791f78c83 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 00b5a27 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/2/artifact/out/diff-checkstyle-hadoop-hdfs-project.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/2/artifact/out/patch-findbugs-hadoop-hdfs-project_hadoop-hdfs-client.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/2/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/2/testReport/ |
| Max. process+thread count | 2772 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by LeonGao91** [comment]
Checking failed tests ^

**Comment by LeonGao91** [comment]
@jojochuang  @goiri  
Looking at all test failures, they are complaining:
```
java.lang.NoSuchMethodError: org.apache.hadoop.hdfs.client.BlockReportOptions.getNamenodeAddr()Ljava/net/InetSocketAddress;
```
Which is the method I added as part of the patch.
Tests are complaining this at runtime (`BlockReportOptions` is in HDFS-client), Also the failed tests were passed on my local unit test.

Do you have any idea about this? Could it be some build related issue? Thanks ^

**Comment by jojochuang** [comment]
Triggering the build manually. https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/3/

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 70 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 22 | Maven dependency ordering for branch |
| +1 | mvninstall | 1195 | trunk passed |
| +1 | compile | 238 | trunk passed |
| +1 | checkstyle | 67 | trunk passed |
| +1 | mvnsite | 124 | trunk passed |
| +1 | shadedclient | 948 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 87 | trunk passed |
| 0 | spotbugs | 190 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 337 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 10 | Maven dependency ordering for patch |
| +1 | mvninstall | 113 | the patch passed |
| +1 | compile | 209 | the patch passed |
| +1 | cc | 209 | the patch passed |
| +1 | javac | 209 | the patch passed |
| -0 | checkstyle | 48 | hadoop-hdfs-project: The patch generated 19 new + 337 unchanged - 2 fixed = 356 total (was 339) |
| +1 | mvnsite | 103 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 727 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 75 | the patch passed |
| +1 | findbugs | 327 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 113 | hadoop-hdfs-client in the patch passed. |
| -1 | unit | 7524 | hadoop-hdfs in the patch failed. |
| +1 | asflicense | 44 | The patch does not generate ASF License warnings. |
| | | 12391 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.datanode.TestLargeBlockReport |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1252 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle cc |
| uname | Linux 9c34c6f45817 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c92b498 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/3/artifact/out/diff-checkstyle-hadoop-hdfs-project.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/3/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/3/testReport/ |
| Max. process+thread count | 3901 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by LeonGao91** [comment]
Thanks @jojochuang ! looks like the # of test failures reduced to 1 with re-run, and it is not related, could you take a look?

**Comment by jojochuang** [comment]
I gave it a quick review and from that quick look it looks good. Thanks. I'll try to look at it harder, especially the test code.

**Comment by LeonGao91** [comment]
> I gave it a quick review and from that quick look it looks good. Thanks. I'll try to look at it harder, especially the test code.

Thanks @jojochuang !

**Comment by jojochuang** [comment]
+1

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 120 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for branch |
| +1 | mvninstall | 1207 | trunk passed |
| +1 | compile | 236 | trunk passed |
| +1 | checkstyle | 62 | trunk passed |
| +1 | mvnsite | 121 | trunk passed |
| +1 | shadedclient | 889 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 87 | trunk passed |
| 0 | spotbugs | 178 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 301 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 10 | Maven dependency ordering for patch |
| +1 | mvninstall | 109 | the patch passed |
| +1 | compile | 219 | the patch passed |
| +1 | cc | 219 | the patch passed |
| +1 | javac | 219 | the patch passed |
| -0 | checkstyle | 54 | hadoop-hdfs-project: The patch generated 19 new + 337 unchanged - 2 fixed = 356 total (was 339) |
| +1 | mvnsite | 105 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 794 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 76 | the patch passed |
| +1 | findbugs | 305 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 115 | hadoop-hdfs-client in the patch passed. |
| -1 | unit | 8003 | hadoop-hdfs in the patch failed. |
| +1 | asflicense | 35 | The patch does not generate ASF License warnings. |
| | | 12878 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.TestCommitBlockWithInvalidGenStamp |
|   | hadoop.hdfs.server.namenode.TestFSImage |
|   | hadoop.hdfs.server.namenode.TestNameNodeMetadataConsistency |
|   | hadoop.hdfs.server.blockmanagement.TestNodeCount |
|   | hadoop.hdfs.TestDecommission |
|   | hadoop.hdfs.server.namenode.ha.TestBootstrapStandby |
|   | hadoop.hdfs.server.namenode.TestBlockPlacementPolicyRackFaultTolerant |
|   | hadoop.hdfs.server.namenode.TestCheckpoint |
|   | hadoop.hdfs.server.namenode.metrics.TestNameNodeMetrics |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1252 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle cc |
| uname | Linux 6e267a98ed82 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 77d102c |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/4/artifact/out/diff-checkstyle-hadoop-hdfs-project.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/4/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/4/testReport/ |
| Max. process+thread count | 3635 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/4/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 40 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 16 | Maven dependency ordering for branch |
| +1 | mvninstall | 1078 | trunk passed |
| +1 | compile | 202 | trunk passed |
| +1 | checkstyle | 52 | trunk passed |
| +1 | mvnsite | 108 | trunk passed |
| +1 | shadedclient | 812 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 75 | trunk passed |
| 0 | spotbugs | 164 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 284 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 10 | Maven dependency ordering for patch |
| +1 | mvninstall | 101 | the patch passed |
| +1 | compile | 199 | the patch passed |
| +1 | cc | 199 | the patch passed |
| +1 | javac | 199 | the patch passed |
| -0 | checkstyle | 47 | hadoop-hdfs-project: The patch generated 19 new + 337 unchanged - 2 fixed = 356 total (was 339) |
| +1 | mvnsite | 98 | the patch passed |
| +1 | whitespace | 1 | The patch has no whitespace issues. |
| +1 | shadedclient | 682 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 71 | the patch passed |
| +1 | findbugs | 297 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 109 | hadoop-hdfs-client in the patch passed. |
| -1 | unit | 5024 | hadoop-hdfs in the patch failed. |
| -1 | asflicense | 30 | The patch generated 2 ASF License warnings. |
| | | 9343 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.TestReconstructStripedBlocks |
|   | hadoop.hdfs.server.namenode.snapshot.TestSnapshotDeletion |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1252 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle cc |
| uname | Linux 0183e6164a7e 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 9b8359b |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/5/artifact/out/diff-checkstyle-hadoop-hdfs-project.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/5/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/5/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/5/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 4053 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1252/5/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
