### PR TITLE
HDDS-1175. Serve read requests directly from RocksDB.

### PR DESCRIPTION
**Pull request by hanishakoneru**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 47 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 47 | Maven dependency ordering for branch |
| +1 | mvninstall | 1097 | trunk passed |
| -1 | compile | 592 | root in trunk failed. |
| +1 | checkstyle | 203 | trunk passed |
| -1 | mvnsite | 40 | common in trunk failed. |
| -1 | mvnsite | 43 | integration-test in trunk failed. |
| -1 | mvnsite | 28 | ozone-manager in trunk failed. |
| +1 | shadedclient | 1084 | branch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| -1 | findbugs | 24 | common in trunk failed. |
| -1 | findbugs | 25 | ozone-manager in trunk failed. |
| +1 | javadoc | 119 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 22 | Maven dependency ordering for patch |
| -1 | mvninstall | 27 | common in the patch failed. |
| -1 | mvninstall | 25 | integration-test in the patch failed. |
| -1 | mvninstall | 20 | ozone-manager in the patch failed. |
| -1 | compile | 571 | root in the patch failed. |
| -1 | javac | 571 | root in the patch failed. |
| +1 | checkstyle | 196 | the patch passed |
| -1 | mvnsite | 35 | common in the patch failed. |
| -1 | mvnsite | 28 | integration-test in the patch failed. |
| -1 | mvnsite | 25 | ozone-manager in the patch failed. |
| -1 | whitespace | 0 | The patch has 75 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| -1 | whitespace | 1 | The patch 19849  line(s) with tabs. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 729 | patch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| -1 | findbugs | 31 | common in the patch failed. |
| -1 | findbugs | 29 | ozone-manager in the patch failed. |
| -1 | javadoc | 31 | hadoop-ozone_ozone-manager generated 3 new + 2 unchanged - 0 fixed = 5 total (was 2) |
||| _ Other Tests _ |
| -1 | unit | 121 | common in the patch failed. |
| -1 | unit | 43 | common in the patch failed. |
| -1 | unit | 34 | integration-test in the patch failed. |
| -1 | unit | 32 | ozone-manager in the patch failed. |
| +1 | asflicense | 41 | The patch does not generate ASF License warnings. |
| | | 5946 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.security.x509.certificate.client.TestDefaultCertificateClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/557 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  xml  findbugs  checkstyle  |
| uname | Linux 96f0f7240798 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 313e8b9 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/branch-compile-root.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/branch-mvnsite-hadoop-ozone_common.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/branch-mvnsite-hadoop-ozone_integration-test.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/branch-mvnsite-hadoop-ozone_ozone-manager.txt |
| findbugs | v3.1.0-RC1 |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/branch-findbugs-hadoop-ozone_common.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/branch-findbugs-hadoop-ozone_ozone-manager.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-mvninstall-hadoop-ozone_common.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-mvninstall-hadoop-ozone_integration-test.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-mvninstall-hadoop-ozone_ozone-manager.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-compile-root.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-compile-root.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-mvnsite-hadoop-ozone_common.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-mvnsite-hadoop-ozone_integration-test.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-mvnsite-hadoop-ozone_ozone-manager.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/whitespace-eol.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/whitespace-tabs.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-findbugs-hadoop-ozone_common.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-findbugs-hadoop-ozone_ozone-manager.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/diff-javadoc-javadoc-hadoop-ozone_ozone-manager.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-unit-hadoop-hdds_common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-unit-hadoop-ozone_common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-unit-hadoop-ozone_integration-test.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/artifact/out/patch-unit-hadoop-ozone_ozone-manager.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/testReport/ |
| Max. process+thread count | 333 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-ozone/common hadoop-ozone/integration-test hadoop-ozone/ozone-manager U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 66 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 84 | Maven dependency ordering for branch |
| +1 | mvninstall | 1257 | trunk passed |
| -1 | compile | 568 | root in trunk failed. |
| +1 | checkstyle | 198 | trunk passed |
| -1 | mvnsite | 41 | common in trunk failed. |
| -1 | mvnsite | 45 | integration-test in trunk failed. |
| -1 | mvnsite | 26 | ozone-manager in trunk failed. |
| +1 | shadedclient | 1103 | branch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| -1 | findbugs | 41 | common in trunk failed. |
| -1 | findbugs | 29 | ozone-manager in trunk failed. |
| +1 | javadoc | 128 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 65 | Maven dependency ordering for patch |
| -1 | mvninstall | 29 | integration-test in the patch failed. |
| -1 | compile | 605 | root in the patch failed. |
| -1 | javac | 605 | root in the patch failed. |
| +1 | checkstyle | 192 | the patch passed |
| -1 | mvnsite | 32 | integration-test in the patch failed. |
| -1 | whitespace | 1 | The patch has 75 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| -1 | whitespace | 1 | The patch 19849  line(s) with tabs. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 691 | patch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 233 | the patch passed |
| +1 | javadoc | 45 | common in the patch passed. |
| +1 | javadoc | 39 | common in the patch passed. |
| +1 | javadoc | 18 | integration-test in the patch passed. |
| +1 | javadoc | 24 | hadoop-ozone_ozone-manager generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2) |
||| _ Other Tests _ |
| -1 | unit | 87 | common in the patch failed. |
| -1 | unit | 43 | common in the patch failed. |
| -1 | unit | 36 | integration-test in the patch failed. |
| +1 | unit | 49 | ozone-manager in the patch passed. |
| +1 | asflicense | 33 | The patch does not generate ASF License warnings. |
| | | 6313 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.security.x509.certificate.client.TestDefaultCertificateClient |
|   | hadoop.ozone.security.TestOzoneDelegationTokenSecretManager |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/557 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  xml  findbugs  checkstyle  |
| uname | Linux 298573dbba86 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 7f636b4 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/branch-compile-root.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/branch-mvnsite-hadoop-ozone_common.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/branch-mvnsite-hadoop-ozone_integration-test.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/branch-mvnsite-hadoop-ozone_ozone-manager.txt |
| findbugs | v3.1.0-RC1 |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/branch-findbugs-hadoop-ozone_common.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/branch-findbugs-hadoop-ozone_ozone-manager.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/patch-mvninstall-hadoop-ozone_integration-test.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/patch-compile-root.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/patch-compile-root.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/patch-mvnsite-hadoop-ozone_integration-test.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/whitespace-eol.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/whitespace-tabs.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/patch-unit-hadoop-hdds_common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/patch-unit-hadoop-ozone_common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/artifact/out/patch-unit-hadoop-ozone_integration-test.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/testReport/ |
| Max. process+thread count | 342 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-ozone/common hadoop-ozone/integration-test hadoop-ozone/ozone-manager U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 143 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 66 | Maven dependency ordering for branch |
| +1 | mvninstall | 1060 | trunk passed |
| -1 | compile | 556 | root in trunk failed. |
| +1 | checkstyle | 184 | trunk passed |
| -1 | mvnsite | 40 | common in trunk failed. |
| -1 | mvnsite | 37 | integration-test in trunk failed. |
| -1 | mvnsite | 32 | ozone-manager in trunk failed. |
| +1 | shadedclient | 1056 | branch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| -1 | findbugs | 29 | common in trunk failed. |
| -1 | findbugs | 26 | ozone-manager in trunk failed. |
| +1 | javadoc | 127 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 25 | Maven dependency ordering for patch |
| -1 | mvninstall | 26 | integration-test in the patch failed. |
| -1 | compile | 515 | root in the patch failed. |
| -1 | javac | 515 | root in the patch failed. |
| +1 | checkstyle | 176 | the patch passed |
| -1 | mvnsite | 32 | integration-test in the patch failed. |
| -1 | whitespace | 0 | The patch has 75 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| -1 | whitespace | 1 | The patch 19849  line(s) with tabs. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 664 | patch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 194 | the patch passed |
| +1 | javadoc | 42 | common in the patch passed. |
| +1 | javadoc | 38 | common in the patch passed. |
| +1 | javadoc | 22 | integration-test in the patch passed. |
| +1 | javadoc | 22 | hadoop-ozone_ozone-manager generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2) |
||| _ Other Tests _ |
| -1 | unit | 62 | common in the patch failed. |
| +1 | unit | 42 | common in the patch passed. |
| -1 | unit | 31 | integration-test in the patch failed. |
| +1 | unit | 40 | ozone-manager in the patch passed. |
| +1 | asflicense | 36 | The patch does not generate ASF License warnings. |
| | | 5904 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.security.x509.certificate.client.TestDefaultCertificateClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/557 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  xml  findbugs  checkstyle  |
| uname | Linux b47069714bda 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 62e89dc |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/branch-compile-root.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/branch-mvnsite-hadoop-ozone_common.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/branch-mvnsite-hadoop-ozone_integration-test.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/branch-mvnsite-hadoop-ozone_ozone-manager.txt |
| findbugs | v3.1.0-RC1 |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/branch-findbugs-hadoop-ozone_common.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/branch-findbugs-hadoop-ozone_ozone-manager.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/patch-mvninstall-hadoop-ozone_integration-test.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/patch-compile-root.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/patch-compile-root.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/patch-mvnsite-hadoop-ozone_integration-test.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/whitespace-eol.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/whitespace-tabs.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/patch-unit-hadoop-hdds_common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/artifact/out/patch-unit-hadoop-ozone_integration-test.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/testReport/ |
| Max. process+thread count | 443 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-ozone/common hadoop-ozone/integration-test hadoop-ozone/ozone-manager U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 28 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 112 | Maven dependency ordering for branch |
| +1 | mvninstall | 1085 | trunk passed |
| -1 | compile | 608 | root in trunk failed. |
| +1 | checkstyle | 177 | trunk passed |
| -1 | mvnsite | 44 | integration-test in trunk failed. |
| +1 | shadedclient | 997 | branch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 174 | trunk passed |
| +1 | javadoc | 131 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 24 | Maven dependency ordering for patch |
| -1 | mvninstall | 27 | integration-test in the patch failed. |
| -1 | compile | 524 | root in the patch failed. |
| -1 | javac | 524 | root in the patch failed. |
| +1 | checkstyle | 172 | the patch passed |
| -1 | mvnsite | 34 | integration-test in the patch failed. |
| -1 | whitespace | 0 | The patch has 75 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| -1 | whitespace | 1 | The patch 19849  line(s) with tabs. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 630 | patch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 179 | the patch passed |
| +1 | javadoc | 97 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 74 | common in the patch failed. |
| +1 | unit | 36 | common in the patch passed. |
| -1 | unit | 28 | integration-test in the patch failed. |
| +1 | unit | 34 | ozone-manager in the patch passed. |
| +1 | asflicense | 27 | The patch does not generate ASF License warnings. |
| | | 5763 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.security.x509.certificate.client.TestDefaultCertificateClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/557 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  xml  findbugs  checkstyle  |
| uname | Linux a0e5bebbec85 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 2c3ec37 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/artifact/out/branch-compile-root.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/artifact/out/branch-mvnsite-hadoop-ozone_integration-test.txt |
| findbugs | v3.1.0-RC1 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/artifact/out/patch-mvninstall-hadoop-ozone_integration-test.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/artifact/out/patch-compile-root.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/artifact/out/patch-compile-root.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/artifact/out/patch-mvnsite-hadoop-ozone_integration-test.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/artifact/out/whitespace-eol.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/artifact/out/whitespace-tabs.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/artifact/out/patch-unit-hadoop-hdds_common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/artifact/out/patch-unit-hadoop-ozone_integration-test.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/testReport/ |
| Max. process+thread count | 445 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-ozone/common hadoop-ozone/integration-test hadoop-ozone/ozone-manager U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-557/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hanishakoneru** [comment]
The test failures are unrelated and pass locally. I will merge the PR shortly.

**Pull request merged**
