### PR TITLE
HADOOP-16470 IAMInstanceCredentialsProvider to use EC2ContainerCredentialsProviderWrapper

### PR DESCRIPTION
**Pull request by steveloughran**
* contains HADOOP-16471 -restoration of SharedInstanceProfileCredentialsProvider

Change-Id: I6ec2c3585ad1966d6664465a2b3fbfa25fbda46f

### CODE REVIEW

**Comment by steveloughran** [comment]
Tested: S3 ireland: -Dparallel-tests -DtestsThreadCount=6 -Ds3guard -Ddynamodb -Dnonauth

*I am really happy all these tests are working*

**Comment by steveloughran** [comment]
+sid, gabor, be good to get your reviews here.

**Comment by bgaborg** [comment]
I'll try this locally from my machine, but we can't simply add an integration test for this, right?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 47 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 72 | Maven dependency ordering for branch |
| +1 | mvninstall | 1175 | trunk passed |
| +1 | compile | 1141 | trunk passed |
| +1 | checkstyle | 147 | trunk passed |
| +1 | mvnsite | 121 | trunk passed |
| +1 | shadedclient | 958 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 93 | trunk passed |
| 0 | spotbugs | 67 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| -1 | findbugs | 65 | hadoop-tools/hadoop-aws in trunk has 1 extant findbugs warnings. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 26 | Maven dependency ordering for patch |
| +1 | mvninstall | 80 | the patch passed |
| +1 | compile | 1053 | the patch passed |
| +1 | javac | 1053 | the patch passed |
| -0 | checkstyle | 142 | root: The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0) |
| +1 | mvnsite | 117 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 662 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 99 | the patch passed |
| +1 | findbugs | 202 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 554 | hadoop-common in the patch passed. |
| +1 | unit | 293 | hadoop-aws in the patch passed. |
| +1 | asflicense | 48 | The patch does not generate ASF License warnings. |
| | | 7230 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1185 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml findbugs checkstyle |
| uname | Linux 78484c0bc297 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c75f16d |
| Default Java | 1.8.0_212 |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/1/artifact/out/branch-findbugs-hadoop-tools_hadoop-aws-warnings.html |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/1/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/1/testReport/ |
| Max. process+thread count | 1423 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
no, no way to test

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 45 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 24 | Maven dependency ordering for branch |
| +1 | mvninstall | 1087 | trunk passed |
| +1 | compile | 1066 | trunk passed |
| +1 | checkstyle | 134 | trunk passed |
| +1 | mvnsite | 119 | trunk passed |
| +1 | shadedclient | 946 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 88 | trunk passed |
| 0 | spotbugs | 65 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| -1 | findbugs | 63 | hadoop-tools/hadoop-aws in trunk has 1 extant findbugs warnings. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 28 | Maven dependency ordering for patch |
| +1 | mvninstall | 81 | the patch passed |
| +1 | compile | 1011 | the patch passed |
| +1 | javac | 1011 | the patch passed |
| -0 | checkstyle | 137 | root: The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0) |
| +1 | mvnsite | 115 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 643 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 105 | the patch passed |
| +1 | findbugs | 193 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 533 | hadoop-common in the patch passed. |
| -1 | unit | 292 | hadoop-aws in the patch failed. |
| -1 | asflicense | 41 | The patch generated 1 ASF License warnings. |
| | | 6878 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.fs.s3a.commit.staging.TestStagingCommitter |
|   | hadoop.fs.s3a.TestS3AUnbuffer |
|   | hadoop.fs.s3a.TestListing |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1185 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml findbugs checkstyle |
| uname | Linux 0194ab49e1d7 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / f86de6f |
| Default Java | 1.8.0_212 |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/2/artifact/out/branch-findbugs-hadoop-tools_hadoop-aws-warnings.html |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/2/artifact/out/diff-checkstyle-root.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/2/artifact/out/patch-unit-hadoop-tools_hadoop-aws.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/2/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/2/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 1655 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 80 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for branch |
| +1 | mvninstall | 1228 | trunk passed |
| +1 | compile | 1140 | trunk passed |
| +1 | checkstyle | 162 | trunk passed |
| +1 | mvnsite | 130 | trunk passed |
| +1 | shadedclient | 1108 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 105 | trunk passed |
| 0 | spotbugs | 78 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 219 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 27 | Maven dependency ordering for patch |
| +1 | mvninstall | 81 | the patch passed |
| +1 | compile | 1169 | the patch passed |
| +1 | javac | 1169 | the patch passed |
| -0 | checkstyle | 179 | root: The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0) |
| +1 | mvnsite | 146 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 848 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 108 | the patch passed |
| +1 | findbugs | 217 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 594 | hadoop-common in the patch passed. |
| +1 | unit | 298 | hadoop-aws in the patch passed. |
| +1 | asflicense | 49 | The patch does not generate ASF License warnings. |
| | | 7906 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1185 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml findbugs checkstyle |
| uname | Linux 8cb4f90826f8 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 70b4617 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/3/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/3/testReport/ |
| Max. process+thread count | 1570 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 49 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 27 | Maven dependency ordering for branch |
| -1 | mvninstall | 107 | root in trunk failed. |
| -1 | compile | 17 | root in trunk failed. |
| +1 | checkstyle | 129 | trunk passed |
| -1 | mvnsite | 17 | hadoop-aws in trunk failed. |
| -1 | shadedclient | 437 | branch has errors when building and testing our client artifacts. |
| -1 | javadoc | 23 | hadoop-common in trunk failed. |
| -1 | javadoc | 26 | hadoop-aws in trunk failed. |
| 0 | spotbugs | 545 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| -1 | findbugs | 23 | hadoop-common in trunk failed. |
| -1 | findbugs | 23 | hadoop-aws in trunk failed. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 21 | Maven dependency ordering for patch |
| -1 | mvninstall | 23 | hadoop-common in the patch failed. |
| -1 | mvninstall | 22 | hadoop-aws in the patch failed. |
| -1 | compile | 23 | root in the patch failed. |
| -1 | javac | 23 | root in the patch failed. |
| -0 | checkstyle | 130 | root: The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0) |
| +1 | mvnsite | 98 | the patch passed |
| -1 | whitespace | 0 | The patch has 49 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| -1 | whitespace | 1 | The patch 600  line(s) with tabs. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 687 | patch has no errors when building and testing our client artifacts. |
| -1 | javadoc | 22 | hadoop-tools_hadoop-aws generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0) |
| +1 | findbugs | 176 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 572 | hadoop-common in the patch passed. |
| +1 | unit | 276 | hadoop-aws in the patch passed. |
| -1 | asflicense | 27 | The patch generated 1 ASF License warnings. |
| | | 3104 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1185 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml findbugs checkstyle |
| uname | Linux d868750d7228 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 00b5a27 |
| Default Java | 1.8.0_222 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/branch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/branch-compile-root.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/branch-mvnsite-hadoop-tools_hadoop-aws.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/branch-javadoc-hadoop-common-project_hadoop-common.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/branch-javadoc-hadoop-tools_hadoop-aws.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/branch-findbugs-hadoop-common-project_hadoop-common.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/branch-findbugs-hadoop-tools_hadoop-aws.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/patch-mvninstall-hadoop-common-project_hadoop-common.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/patch-mvninstall-hadoop-tools_hadoop-aws.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/patch-compile-root.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/patch-compile-root.txt |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/diff-checkstyle-root.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/whitespace-eol.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/whitespace-tabs.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/diff-javadoc-javadoc-hadoop-tools_hadoop-aws.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/testReport/ |
| asflicense | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 1401 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/4/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 40 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 21 | Maven dependency ordering for branch |
| +1 | mvninstall | 1104 | trunk passed |
| +1 | compile | 1190 | trunk passed |
| +1 | checkstyle | 138 | trunk passed |
| +1 | mvnsite | 111 | trunk passed |
| +1 | shadedclient | 939 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 90 | trunk passed |
| 0 | spotbugs | 63 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 182 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for patch |
| +1 | mvninstall | 82 | the patch passed |
| +1 | compile | 1107 | the patch passed |
| +1 | javac | 1107 | the patch passed |
| -0 | checkstyle | 145 | root: The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0) |
| +1 | mvnsite | 116 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 645 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 88 | the patch passed |
| +1 | findbugs | 193 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 550 | hadoop-common in the patch passed. |
| +1 | unit | 75 | hadoop-aws in the patch passed. |
| +1 | asflicense | 38 | The patch does not generate ASF License warnings. |
| | | 6874 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1185 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml findbugs checkstyle |
| uname | Linux 2e6254af1428 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 9a1d8cf |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/5/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/5/testReport/ |
| Max. process+thread count | 1361 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/5/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 43 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 21 | Maven dependency ordering for branch |
| -1 | mvninstall | 1103 | root in trunk failed. |
| +1 | compile | 1098 | trunk passed |
| +1 | checkstyle | 126 | trunk passed |
| +1 | mvnsite | 106 | trunk passed |
| +1 | shadedclient | 913 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 82 | trunk passed |
| 0 | spotbugs | 59 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 167 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 22 | Maven dependency ordering for patch |
| +1 | mvninstall | 71 | the patch passed |
| +1 | compile | 1027 | the patch passed |
| +1 | javac | 1027 | the patch passed |
| -0 | checkstyle | 138 | root: The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0) |
| +1 | mvnsite | 110 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 614 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 91 | the patch passed |
| +1 | findbugs | 197 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 543 | hadoop-common in the patch passed. |
| +1 | unit | 76 | hadoop-aws in the patch passed. |
| +1 | asflicense | 46 | The patch does not generate ASF License warnings. |
| | | 6611 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1185 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml findbugs checkstyle |
| uname | Linux 12341290ca39 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 6244502 |
| Default Java | 1.8.0_222 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/6/artifact/out/branch-mvninstall-root.txt |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/6/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/6/testReport/ |
| Max. process+thread count | 1378 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/6/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 21 | Maven dependency ordering for branch |
| +1 | mvninstall | 1091 | trunk passed |
| +1 | compile | 1045 | trunk passed |
| +1 | checkstyle | 129 | trunk passed |
| +1 | mvnsite | 110 | trunk passed |
| +1 | shadedclient | 910 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 90 | trunk passed |
| 0 | spotbugs | 66 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 178 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for patch |
| +1 | mvninstall | 80 | the patch passed |
| +1 | compile | 1099 | the patch passed |
| +1 | javac | 1099 | the patch passed |
| -0 | checkstyle | 139 | root: The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0) |
| +1 | mvnsite | 110 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 650 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 88 | the patch passed |
| +1 | findbugs | 191 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 511 | hadoop-common in the patch passed. |
| +1 | unit | 65 | hadoop-aws in the patch passed. |
| +1 | asflicense | 45 | The patch does not generate ASF License warnings. |
| | | 6634 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1185 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml findbugs checkstyle |
| uname | Linux 8b38e9c26ea1 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 69ddb36 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/7/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/7/testReport/ |
| Max. process+thread count | 1383 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1185/7/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
thanks, fixed

**Pull request closed without merging**
