### PR TITLE
HADOOP-18433. Fix main thread name.

### PR DESCRIPTION
**Pull request by zhengchenyu**
https://issues.apache.org/jira/browse/HADOOP-18433

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 52s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  41m  8s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  25m 23s |  |  trunk passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  compile  |  21m 55s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  checkstyle  |   1m 25s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 54s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   1m 25s |  |  trunk passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |   0m 57s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  spotbugs  |   2m 59s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  25m 55s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m  4s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  24m 57s |  |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javac  |  24m 57s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  30m 25s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |  30m 25s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m 14s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m 39s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 16s |  |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |   0m 57s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  spotbugs  |   3m  1s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  25m 37s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  18m 27s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  9s |  |  The patch does not generate ASF License warnings.  |
|  |   | 235m 55s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4838/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4838 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 74d31c5d8852 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 6d9c854c410c520bcfcb61e7aa58bcb70776bccd |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4838/1/testReport/ |
| Max. process+thread count | 2466 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4838/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by ZanderXu — COMMENTED** [review]
Thanks @zhengchenyu for you report. 

Maybe we want to set this name to the Listener thread, but this PR just remove it. 
Can you fix it?

**Comment by zhengchenyu** [comment]
> https://issues.apache.org/jira/browse/HADOOP-18433

@ZanderXu Thanks for review this PR. This code is called in main thread to initialize Listener. After HDFS-13566 the main thread name is rename as "Listener at ${hostname}/9000". When I jstack, it is confused.
You can see jstack info after HDFS-13566, the thread "Listener at ${hostname}/9000" is the main thread.

**Comment by ZanderXu** [comment]
@zhengchenyu I got what you want to do. But I think we should correct the thread name of the `Listener` instead of deleting it.

**Comment by zhengchenyu** [comment]
> @zhengchenyu I got what you want to do. But I think we should correct the thread name of the `Listener` instead of deleting it.
Yes, but is it necessary to correct the name? If just delete it, the thread name is main, I think it is reasonable.

**Comment by ZanderXu** [comment]
How about moving line1397 to line 1513? Correct it, not delete

**Comment by zhengchenyu** [comment]
> How about moving line1397 to line 1513? Correct it, not delete

@ZanderXu  Line 1410 has already set thread name,  I think just delete is ok.

```
      this.setName("IPC Server listener on " + port);
```

**Comment by ZanderXu** [comment]
> > How about moving line1397 to line 1513? Correct it, not delete
> 
> @ZanderXu Line 1410 has already set thread name, I think just delete is ok.
> 
> ```
>       this.setName("IPC Server listener on " + port);
> ```

Oh, I see.  LGTM.

**Review by ZanderXu — APPROVED** [review]

**Comment by ZanderXu** [comment]
Merged. @zhengchenyu Thanks for your contribution.

**Pull request merged**
