### PR TITLE
HDDS-1450. Fix nightly run failures after HDDS-976. Contributed by Xi…

### PR DESCRIPTION
**Pull request by xiaoyuyao**

### CODE REVIEW

**Comment by xiaoyuyao** [comment]
Remove the unnecessary configuration key "ozone.scm.network.topology.schema.file.type" and determine the type of schema based on the file extension of existing key "ozone.scm.network.topology.schema.file".

cc: @cjjnjust

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 26 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1023 | trunk passed |
| +1 | compile | 44 | trunk passed |
| +1 | checkstyle | 23 | trunk passed |
| +1 | mvnsite | 41 | trunk passed |
| +1 | shadedclient | 748 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 69 | trunk passed |
| +1 | javadoc | 44 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 40 | the patch passed |
| +1 | compile | 33 | the patch passed |
| +1 | javac | 33 | the patch passed |
| +1 | checkstyle | 16 | the patch passed |
| +1 | mvnsite | 34 | the patch passed |
| +1 | whitespace | 1 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 751 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 77 | the patch passed |
| +1 | javadoc | 37 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 67 | common in the patch passed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 3187 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-757/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/757 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  xml  |
| uname | Linux 4814bfbb092b 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 96e3027 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-757/1/testReport/ |
| Max. process+thread count | 444 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common U: hadoop-hdds/common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-757/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by cjjnjust** [comment]
Thanks @xiaoyuyao, Does this fix the nightly build? It seems not fix "the good.xml file not found" issue, how does it work?

**Comment by xiaoyuyao** [comment]
bq. Does this fix the nightly build? It seems not fix "the good.xml file not found" issue, how does it work?

The reason of the failure I guess is that ozone.scm.network.topology.schema.file.type does not have a default value. By removing this key, init() loading will be based on file extension directly. It seems to be working based on the result here: https://ci.anzix.net/job/ozone/16691/testReport/

**Comment by ajayydv** [comment]
+1

**Comment by xiaoyuyao** [comment]
@cjjnjust Sorry I was not very clear on the previous comment. 

conf.get() without a default value will return null for schemaFileType when the key is not defined, which is the case for some tests. This will cause NPE but was caught by catch (Throwable e) and rethrow as RTE with log message "Fail to load schema file...".

**Pull request merged**
