### PR TITLE
HDFS-16384. Upgrade Netty to 4.1.72.Final

### PR DESCRIPTION
**Pull request by tamaashu**
### Description of PR
Upgrade Netty to newest available version

### How was this patch tested?
Ran unit tests

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 42s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  12m 41s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  22m 56s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  23m 14s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |  19m 57s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  mvnsite  |   1m 49s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   1m 35s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   1m 29s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  shadedclient  | 104m  9s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 59s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m  4s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  22m 58s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |  22m 58s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  20m 33s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |  20m 33s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   1m 44s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  7s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 28s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   1m 17s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  shadedclient  |  25m 31s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 27s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 35s |  |  hadoop-hdfs-client in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 52s |  |  The patch does not generate ASF License warnings.  |
|  |   | 185m  8s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3798/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3798 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml |
| uname | Linux 10b021359098 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / a632a17750320f0c27a7496942971171554577b5 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3798/1/testReport/ |
| Max. process+thread count | 547 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-hdfs-project/hadoop-hdfs-client U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3798/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by jojochuang — COMMENTED** [review]
can you also update the version here? https://github.com/apache/hadoop/blob/trunk/LICENSE-binary#L264
that way, it triggers the full build which is needed to verify a thirdparty update.

**Comment by tamaashu** [comment]
Thanks @jojochuang, I've updated the License file.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 44s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  shelldocs  |   0m  1s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  12m 51s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  28m 40s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  29m 28s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |  24m 43s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  mvnsite  |  31m 49s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   9m 30s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   8m  7s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  shadedclient  |  36m 44s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 59s |  |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |  21m 12s | [/patch-mvninstall-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3798/2/artifact/out/patch-mvninstall-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  compile  |  21m 51s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |  21m 51s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  20m 46s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |  20m 46s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |  22m 29s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  xml  |   0m  3s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   7m 51s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   8m 11s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  shadedclient  |  36m 43s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 189m 41s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3798/2/artifact/out/patch-unit-root.txt) |  root in the patch failed.  |
| +0 :ok: |  asflicense  |   0m 42s |  |  ASF License check generated no output?  |
|  |   | 483m 14s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ipc.TestIPC |
|   | hadoop.hdfs.server.namenode.TestProcessCorruptBlocks |
|   | hadoop.hdfs.server.namenode.ha.TestRetryCacheWithHA |
|   | hadoop.hdfs.server.namenode.TestFileLimit |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3798/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3798 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml shellcheck shelldocs |
| uname | Linux a66edb137fc3 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / c9ab716aa355bd682310301f1c5dfe74976cd4d6 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3798/2/testReport/ |
| Max. process+thread count | 3152 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-hdfs-project/hadoop-hdfs-client . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3798/2/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by tamaashu** [comment]
@jojochuang to me these test failures look unrelated but still would be good to have a green test. Do you have any special command to restart the testing or should I push an empty commit?

**Comment by jojochuang** [comment]
No this is good. We don't use netty for those sub-components so I think we're good here. Will merge later.

**Comment by virajjasani** [comment]
This seems to be breaking trunk:

```
Dependency convergence error for io.netty:netty-resolver:4.1.50.Final paths to dependency are:
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-solrj:8.8.2
    +-io.netty:netty-resolver:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-core:8.8.2
    +-io.netty:netty-resolver:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-test-framework:8.8.2
    +-io.netty:netty-resolver:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-resolver:4.1.72.Final

[WARNING] 
Dependency convergence error for io.netty:netty-handler:4.1.50.Final paths to dependency are:
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-solrj:8.8.2
    +-io.netty:netty-handler:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-core:8.8.2
    +-io.netty:netty-handler:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-test-framework:8.8.2
    +-io.netty:netty-handler:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-handler:4.1.72.Final

[WARNING] 
Dependency convergence error for io.netty:netty-buffer:4.1.50.Final paths to dependency are:
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-solrj:8.8.2
    +-io.netty:netty-buffer:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-core:8.8.2
    +-io.netty:netty-buffer:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-test-framework:8.8.2
    +-io.netty:netty-buffer:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-buffer:4.1.72.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-transport-native-kqueue:4.1.72.Final
          +-io.netty:netty-buffer:4.1.72.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-transport-native-kqueue:4.1.72.Final
          +-io.netty:netty-buffer:4.1.72.Final

[WARNING] 
Dependency convergence error for io.netty:netty-transport:4.1.50.Final paths to dependency are:
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-solrj:8.8.2
    +-io.netty:netty-transport:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-core:8.8.2
    +-io.netty:netty-transport:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-test-framework:8.8.2
    +-io.netty:netty-transport:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-transport:4.1.72.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-transport-native-kqueue:4.1.72.Final
          +-io.netty:netty-transport:4.1.72.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-transport-native-kqueue:4.1.72.Final
          +-io.netty:netty-transport:4.1.72.Final

[WARNING] 
Dependency convergence error for io.netty:netty-transport-native-epoll:4.1.50.Final paths to dependency are:
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-solrj:8.8.2
    +-io.netty:netty-transport-native-epoll:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-core:8.8.2
    +-io.netty:netty-transport-native-epoll:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-test-framework:8.8.2
    +-io.netty:netty-transport-native-epoll:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-transport-native-epoll:4.1.72.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-transport-native-epoll:4.1.72.Final

[WARNING] 
Dependency convergence error for io.netty:netty-codec:4.1.50.Final paths to dependency are:
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-solrj:8.8.2
    +-io.netty:netty-codec:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-core:8.8.2
    +-io.netty:netty-codec:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-test-framework:8.8.2
    +-io.netty:netty-codec:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-codec:4.1.72.Final

[WARNING] 
Dependency convergence error for io.netty:netty-transport-native-unix-common:4.1.50.Final paths to dependency are:
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-solrj:8.8.2
    +-io.netty:netty-transport-native-unix-common:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-core:8.8.2
    +-io.netty:netty-transport-native-unix-common:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-test-framework:8.8.2
    +-io.netty:netty-transport-native-unix-common:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-transport-native-unix-common:4.1.72.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-transport-native-kqueue:4.1.72.Final
          +-io.netty:netty-transport-native-unix-common:4.1.72.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-transport-native-kqueue:4.1.72.Final
          +-io.netty:netty-transport-native-unix-common:4.1.72.Final

[WARNING] 
Dependency convergence error for io.netty:netty-common:4.1.50.Final paths to dependency are:
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-solrj:8.8.2
    +-io.netty:netty-common:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-core:8.8.2
    +-io.netty:netty-common:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.solr:solr-test-framework:8.8.2
    +-io.netty:netty-common:4.1.50.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-common:4.1.72.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-transport-native-kqueue:4.1.72.Final
          +-io.netty:netty-common:4.1.72.Final
and
+-org.apache.hadoop:hadoop-yarn-applications-catalog-webapp:3.4.0-SNAPSHOT
  +-org.apache.hadoop:hadoop-yarn-services-core:3.4.0-SNAPSHOT
    +-org.apache.hadoop:hadoop-hdfs:3.4.0-SNAPSHOT
      +-io.netty:netty-all:4.1.72.Final
        +-io.netty:netty-transport-native-kqueue:4.1.72.Final
          +-io.netty:netty-common:4.1.72.Final

```

**Comment by jojochuang** [comment]
sorry didn't notice it. reverting it now.

**Pull request merged**
