### PR TITLE
HDFS-16670. Improve Code With Lambda in EditLogTailer class

### PR DESCRIPTION
**Pull request by ZanderXu**
### Description of PR

Improve Code With Lambda in EditLogTailer class

### CODE REVIEW

**Comment by slfan1989** [comment]
Lambda is a very important feature and should indeed be used in the project, but should PRs be submitted at the moudle level?

Lambda optimization should be done for hadoop-hdfs module.

Expect you to get this done, but don't fix it 1 by 1, so that the backport job isn't easily done.

**Comment by ZanderXu** [comment]
Thanks @slfan1989 for your suggestion. I can create a new PR to optimize lambda in hadoop-hdfs moudle, but it will be a huge PR. It will be  difficult for reviewing and merging. In addition to lambda optimization, there are some modifications about typo.

@goiri do you have some good ideas?

**Comment by ZanderXu** [comment]
I can create an issue to optimize lambda in hadoop-hdfs module. And create some sub tasks to fix one by one. We can review sub PRs and merge them into the big issue first, then merge it to the trunk.

How about this? @slfan1989 @goiri

**Comment by slfan1989** [comment]
> I can create an issue to optimize lambda in hadoop-hdfs module. And create some sub tasks to fix one by one. We can review sub PRs and merge them into the big issue first, then merge it to the trunk.
> 
> How about this? @slfan1989 @goiri

I don't think 1 by 1 submits pr, which is really unreasonable. But hadoop-hdfs is indeed relatively large. Can it be submitted according to functional categories, such as HDFS-NN, HDFS-DN, HDFS-JN? Do not submit 1 class by 1 class.

Need some advice from @goiri.

I suggest to create a draft pr first, find all the places to be optimized in hadoop-hdfs (with Lambda), let's see how many changes are there? If it is really a lot, split multiple prs. If the number is not too many, it is best to complete it in one pr, so that it will be easier for others to backport your code.

thanks for your contribution.

The optimization of lambda is relatively small and does not change the main logic, and this optimization should be a whole, it is best not to split.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 50s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  38m 42s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   1m 43s |  |  trunk passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  compile  |   1m 38s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  checkstyle  |   1m 23s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 45s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   1m 24s |  |  trunk passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |   1m 47s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  spotbugs  |   3m 41s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  22m 57s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 24s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 26s |  |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javac  |   1m 26s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 17s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |   1m 17s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m  0s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 28s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 58s |  |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |   1m 33s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  spotbugs  |   3m 21s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  22m 23s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 239m 21s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4596/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 57s |  |  The patch does not generate ASF License warnings.  |
|  |   | 349m 23s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.ha.TestHAAppend |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4596/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4596 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux e69c6b62e0b4 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / a256d53000663c8fdab5a144f9275180211bd271 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4596/1/testReport/ |
| Max. process+thread count | 2979 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4596/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by slfan1989** [comment]
@ZanderXu  I suggest to create a draft pr first, find all the places to be optimized in hadoop-hdfs (with Lambda), let's see how many changes are there? If it is really a lot, split multiple prs. If the number is not too many, it is best to complete it in one pr, so that it will be easier for others to backport your code.

thanks for your contribution.

**Comment by ZanderXu** [comment]
@slfan1989 Thanks for your suggestion, I will create a draft PR to found all places of Hadoop-Hdfs module. After I completed it, I'm asking for your help to review it.

**Comment by ZanderXu** [comment]
Thanks @slfan1989 for you review and nice suggestion. I will close this PR and accomplish it in HDFS-16695.

**Pull request closed without merging**
