### PR TITLE
HADOOP-19097. S3A: Set fs.s3a.connection.establish.timeout to 30s

### PR DESCRIPTION
**Pull request by steveloughran**
This is consistent with the java value.

I had thought of cutting all the fs.s3a settings from core-default, but think we maybe need to review our public docs before doing that. having to look at Constants.java shouldn't be the default way to learn about an option.

### How was this patch tested?

commented out my timeout from my auth-keys file (so it wasn't stamping on this default) and running the tests. The used ripgrep to look for the "is too low" message; only found in test cases where we explicitly created the problem.

```
2:2024-02-29 10:48:03,153 [JUnit-testMinimumDurationWins] WARN  impl.ConfigurationHelper (LogExactlyOnce.java:warn(39)) - Option fs.s3a.connection.acquisition.timeout is too low (1,000 ms). Setting to 15,000 ms instead
3:2024-02-29 10:48:03,153 [JUnit-testMinimumDurationWins] DEBUG impl.ConfigurationHelper (ConfigurationHelper.java:enforceMinimumDuration(127)) - Option fs.s3a.connection.acquisition.timeout is too low (1,000 ms). Setting to 15,000 ms instead
6:2024-02-29 10:48:03,153 [JUnit-testMinimumDurationWins] DEBUG impl.ConfigurationHelper (ConfigurationHelper.java:enforceMinimumDuration(127)) - Option fs.s3a.connection.establish.timeout is too low (1,000 ms). Setting to 15,000 ms instead
9:2024-02-29 10:48:03,154 [JUnit-testMinimumDurationWins] DEBUG impl.ConfigurationHelper (ConfigurationHelper.java:enforceMinimumDuration(127)) - Option fs.s3a.connection.timeout is too low (1,000 ms). Setting to 15,000 ms instead
22:2024-02-29 10:48:03,310 [JUnit-testEnforceMinDuration] DEBUG impl.ConfigurationHelper (ConfigurationHelper.java:enforceMinimumDuration(127)) - Option key is too low (1,000 ms). Setting to 10,000 ms instead

```

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [x] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 19s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  31m 48s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   8m 52s |  |  trunk passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  compile  |   8m  8s |  |  trunk passed with JDK Private Build-1.8.0_392-8u392-ga-1~20.04-b08  |
| +1 :green_heart: |  mvnsite  |   0m 54s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   0m 50s |  |  trunk passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   0m 33s |  |  trunk passed with JDK Private Build-1.8.0_392-8u392-ga-1~20.04-b08  |
| +1 :green_heart: |  shadedclient  |  70m 50s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 30s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   8m 27s |  |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javac  |   8m 27s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   8m  5s |  |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~20.04-b08  |
| +1 :green_heart: |  javac  |   8m  5s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 52s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 43s |  |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   0m 35s |  |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~20.04-b08  |
| +1 :green_heart: |  shadedclient  |  22m 53s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  16m 21s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 40s |  |  The patch does not generate ASF License warnings.  |
|  |   | 130m 58s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6601/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6601 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint |
| uname | Linux d18f3c0f77bc 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 02ca7f4cd15e2017e3920146a8c14c1aaf8beea4 |
| Default Java | Private Build-1.8.0_392-8u392-ga-1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_392-8u392-ga-1~20.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6601/1/testReport/ |
| Max. process+thread count | 2791 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6601/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
@HarshitGupta11 @mukund-thakur @ahmarsuhail reviews, please? targeting 3.4.1

**Comment by virajjasani** [comment]
Change looks good, until we remove fs.s3a settings from core-default, i wonder if we should do one round of comparison b/ s3a/Contants and core-default (as a followup jira)?

**Review by ayushtkn — APPROVED** [review]

**Review by ahmarsuhail — APPROVED** [review]
+1, LGTM.

**Comment by steveloughran** [comment]
@virajjasani I did a scan. Now, the clever thing would be to have a test suite which compared values so there is never a regression. e.g

assertDurationEqual(conf, CONNECTION_TIMEOUT, CONNECTION_TIMEOUT_DEFAULT)

**Pull request merged**
