### PR TITLE
HADOOP-15230. fixes GraphiteSink to support point tags in correct format.

### PR DESCRIPTION
**Pull request by howardyoo**
Fixed GraphiteSink to support point tags in correct format, having appeared at the end and also having no space as its name and value pair.
[JIRA Ticket](https://issues.apache.org/jira/browse/HADOOP-15230)

### CODE REVIEW

**Comment by howardyoo** [comment]
Now, the code is ready to be merged. Patch passed all the tests and without any serious conflicts. I hope the apache hadoop team would review this simple fix and merge it into the trunk branch soon.

**Comment by bak12** [comment]
😁

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by jojochuang** [comment]
@howardyoo appreciate your patch and bug report.
Please refrain from changing existing code style. This makes it impossible to review effectively.

**Comment by howardyoo** [comment]
I'm not sure whether I have changed any code style - I really didn't change anything from the existing codes - only added some fixes.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1115 | trunk passed |
| +1 | compile | 1050 | trunk passed |
| +1 | checkstyle | 39 | trunk passed |
| +1 | mvnsite | 65 | trunk passed |
| +1 | shadedclient | 719 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 60 | trunk passed |
| 0 | spotbugs | 117 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 115 | trunk passed |
| -0 | patch | 146 | Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 43 | the patch passed |
| +1 | compile | 1037 | the patch passed |
| -1 | javac | 1037 | root generated 5 new + 1458 unchanged - 5 fixed = 1463 total (was 1463) |
| +1 | checkstyle | 41 | hadoop-common-project/hadoop-common: The patch generated 0 new + 2 unchanged - 251 fixed = 2 total (was 253) |
| +1 | mvnsite | 77 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 654 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 62 | the patch passed |
| +1 | findbugs | 124 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 542 | hadoop-common in the patch passed. |
| +1 | asflicense | 42 | The patch does not generate ASF License warnings. |
| | | 5890 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-340/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/340 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 31157b2d7e8e 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 094d736 |
| Default Java | 1.8.0_222 |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-340/1/artifact/out/diff-compile-javac-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-340/1/testReport/ |
| Max. process+thread count | 1381 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-340/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1145 | trunk passed |
| +1 | compile | 1019 | trunk passed |
| +1 | checkstyle | 39 | trunk passed |
| +1 | mvnsite | 68 | trunk passed |
| +1 | shadedclient | 765 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 59 | trunk passed |
| 0 | spotbugs | 112 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 109 | trunk passed |
| -0 | patch | 139 | Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 49 | the patch passed |
| +1 | compile | 1015 | the patch passed |
| +1 | javac | 1015 | root generated 0 new + 1458 unchanged - 5 fixed = 1458 total (was 1463) |
| +1 | checkstyle | 36 | hadoop-common-project/hadoop-common: The patch generated 0 new + 2 unchanged - 251 fixed = 2 total (was 253) |
| +1 | mvnsite | 70 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 650 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 66 | the patch passed |
| +1 | findbugs | 128 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 512 | hadoop-common in the patch passed. |
| +1 | asflicense | 38 | The patch does not generate ASF License warnings. |
| | | 5875 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-340/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/340 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 86f8e93e12f6 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 61b2df2 |
| Default Java | 1.8.0_222 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-340/2/testReport/ |
| Max. process+thread count | 1380 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-340/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1102 | trunk passed |
| +1 | compile | 1020 | trunk passed |
| +1 | checkstyle | 54 | trunk passed |
| +1 | mvnsite | 81 | trunk passed |
| +1 | shadedclient | 820 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 70 | trunk passed |
| 0 | spotbugs | 125 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 122 | trunk passed |
| -0 | patch | 161 | Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 50 | the patch passed |
| +1 | compile | 1005 | the patch passed |
| +1 | javac | 1005 | root generated 0 new + 1458 unchanged - 5 fixed = 1458 total (was 1463) |
| +1 | checkstyle | 46 | hadoop-common-project/hadoop-common: The patch generated 0 new + 2 unchanged - 251 fixed = 2 total (was 253) |
| +1 | mvnsite | 76 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 702 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 68 | the patch passed |
| +1 | findbugs | 126 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 571 | hadoop-common in the patch passed. |
| +1 | asflicense | 53 | The patch does not generate ASF License warnings. |
| | | 6075 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-340/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/340 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 8d114f7e54b7 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3329257 |
| Default Java | 1.8.0_222 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-340/3/testReport/ |
| Max. process+thread count | 1396 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-340/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 35 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1212 | trunk passed |
| +1 | compile | 1242 | trunk passed |
| +1 | checkstyle | 51 | trunk passed |
| +1 | mvnsite | 83 | trunk passed |
| +1 | shadedclient | 930 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 79 | trunk passed |
| 0 | spotbugs | 145 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 143 | trunk passed |
| -0 | patch | 185 | Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 55 | the patch passed |
| +1 | compile | 1180 | the patch passed |
| +1 | javac | 1180 | root generated 0 new + 1458 unchanged - 5 fixed = 1458 total (was 1463) |
| +1 | checkstyle | 50 | hadoop-common-project/hadoop-common: The patch generated 0 new + 2 unchanged - 251 fixed = 2 total (was 253) |
| +1 | mvnsite | 95 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 822 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 73 | the patch passed |
| +1 | findbugs | 167 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 647 | hadoop-common in the patch failed. |
| +1 | asflicense | 49 | The patch does not generate ASF License warnings. |
| | | 6995 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ha.TestZKFailoverController |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-340/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/340 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 67061cf725af 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 915cbc9 |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-340/4/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-340/4/testReport/ |
| Max. process+thread count | 1495 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-340/4/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 21s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  20m  4s |  trunk passed  |
| +1 :green_heart: |  compile  |  20m 23s |  trunk passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  compile  |  17m 25s |  trunk passed with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09  |
| +1 :green_heart: |  checkstyle  |   0m 58s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 26s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  16m 51s |  branch has no errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 45s |  hadoop-common in trunk failed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.  |
| +1 :green_heart: |  javadoc  |   1m  2s |  trunk passed with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09  |
| +0 :ok: |  spotbugs  |   2m 10s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m  8s |  trunk passed  |
| -0 :warning: |  patch  |   2m 30s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 49s |  the patch passed  |
| +1 :green_heart: |  compile  |  19m  3s |  the patch passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  javac  |  19m  3s |  root-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1 with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1 generated 0 new + 2046 unchanged - 5 fixed = 2046 total (was 2051)  |
| +1 :green_heart: |  compile  |  19m 53s |  the patch passed with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09  |
| +1 :green_heart: |  javac  |  19m 53s |  root-jdkPrivateBuild-1.8.0_252-8u252-b09-1~18.04-b09 with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09 generated 0 new + 1940 unchanged - 5 fixed = 1940 total (was 1945)  |
| +1 :green_heart: |  checkstyle  |   0m 52s |  hadoop-common-project/hadoop-common: The patch generated 0 new + 1 unchanged - 250 fixed = 1 total (was 251)  |
| +1 :green_heart: |  mvnsite  |   1m 31s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 12s |  patch has no errors when building and testing our client artifacts.  |
| -1 :x: |  javadoc  |   0m 47s |  hadoop-common in the patch failed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.  |
| +1 :green_heart: |  javadoc  |   1m  4s |  the patch passed with JDK Private Build-1.8.0_252-8u252-b09-1~18.04-b09  |
| +1 :green_heart: |  findbugs  |   2m 34s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  10m 27s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 50s |  The patch does not generate ASF License warnings.  |
|  |   | 157m 41s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-340/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/340 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux cb95bc3049f9 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 5d8600e80ad |
| Default Java | Private Build-1.8.0_252-8u252-b09-1~18.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_252-8u252-b09-1~18.04-b09 |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-340/2/artifact/out/branch-javadoc-hadoop-common-project_hadoop-common-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-340/2/artifact/out/patch-javadoc-hadoop-common-project_hadoop-common-jdkUbuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-340/2/testReport/ |
| Max. process+thread count | 3021 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-340/2/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.0.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 31s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |   |   0m  0s | [test4tests](test4tests) |  The patch appears to include 1 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  32m 21s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  20m 41s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  compile  |  17m 53s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~20.04-b01  |
| +1 :green_heart: |  checkstyle  |   1m 12s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 32s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  16m  6s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  5s |  |  trunk passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   1m 33s |  |  trunk passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~20.04-b01  |
| +0 :ok: |  spotbugs  |   2m 19s |  |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 17s |  |  trunk passed  |
| -0 :warning: |  patch  |   2m 39s |  |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 53s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  19m 53s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javac  |  19m 53s |  |  root-jdkUbuntu-11.0.9.1+1-Ubuntu-0ubuntu1.20.04 with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.20.04 generated 0 new + 2021 unchanged - 5 fixed = 2021 total (was 2026)  |
| +1 :green_heart: |  compile  |  17m 51s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~20.04-b01  |
| +1 :green_heart: |  javac  |  17m 51s |  |  root-jdkPrivateBuild-1.8.0_275-8u275-b01-0ubuntu1~20.04-b01 with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~20.04-b01 generated 0 new + 1916 unchanged - 5 fixed = 1916 total (was 1921)  |
| +1 :green_heart: |  checkstyle  |   1m  4s |  |  hadoop-common-project/hadoop-common: The patch generated 0 new + 1 unchanged - 250 fixed = 1 total (was 251)  |
| +1 :green_heart: |  mvnsite  |   1m 30s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  13m 21s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  2s |  |  the patch passed with JDK Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   1m 35s |  |  the patch passed with JDK Private Build-1.8.0_275-8u275-b01-0ubuntu1~20.04-b01  |
| +1 :green_heart: |  findbugs  |   2m 23s |  |  the patch passed  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  17m 13s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 55s |  |  The patch does not generate ASF License warnings.  |
|  |   | 174m 53s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-340/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/340 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux ac11421f88fa 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / c4918fb2986 |
| Default Java | Private Build-1.8.0_275-8u275-b01-0ubuntu1~20.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.9.1+1-Ubuntu-0ubuntu1.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_275-8u275-b01-0ubuntu1~20.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-340/1/testReport/ |
| Max. process+thread count | 1296 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-340/1/console |
| versions | git=2.25.1 maven=3.6.3 findbugs=4.0.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by howardyoo** [comment]
This PR is going nowhere, so I'm closing it, after waiting for more than 2 years now. I first thought this would get merged pretty easily, but somehow this never worked. Maybe I have not done this correctly, but it's hard to know by now. I've been getting email notifications about this sporadically, and was getting annoyed more and more. Now, I guess I can finally say it was a nice try, and good experience. Anyway, I am ready to let this go and forget about it. Good bye!

**Pull request closed without merging**
