### PR TITLE
HADOOP-16495. Fix invalid metric types in PrometheusMetricsSink

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/HADOOP-16495

### CODE REVIEW

**Comment by adoroszlai** [comment]
You might also want to adopt f4df97fd899.

**Comment by aajisaka** [comment]
> You might also want to adopt [f4df97f](https://github.com/apache/hadoop/commit/f4df97fd899eaf0a2e6829827dc9056645555a8c).

Thank you for your information. I'll adopt this in a separate jira.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 46 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 1 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1082 | trunk passed |
| +1 | compile | 1043 | trunk passed |
| +1 | checkstyle | 45 | trunk passed |
| +1 | mvnsite | 68 | trunk passed |
| +1 | shadedclient | 731 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 64 | trunk passed |
| 0 | spotbugs | 123 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 121 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 46 | the patch passed |
| +1 | compile | 996 | the patch passed |
| +1 | javac | 996 | the patch passed |
| -0 | checkstyle | 43 | hadoop-common-project/hadoop-common: The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0) |
| +1 | mvnsite | 73 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 655 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 70 | the patch passed |
| +1 | findbugs | 125 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 540 | hadoop-common in the patch passed. |
| +1 | asflicense | 52 | The patch does not generate ASF License warnings. |
| | | 5889 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1244 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 6c5add12d11e 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 9cd211a |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/1/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/1/testReport/ |
| Max. process+thread count | 1362 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1091 | trunk passed |
| +1 | compile | 1064 | trunk passed |
| +1 | checkstyle | 43 | trunk passed |
| +1 | mvnsite | 76 | trunk passed |
| +1 | shadedclient | 788 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 55 | trunk passed |
| 0 | spotbugs | 123 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 120 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 51 | the patch passed |
| +1 | compile | 1131 | the patch passed |
| +1 | javac | 1131 | the patch passed |
| -0 | checkstyle | 41 | hadoop-common-project/hadoop-common: The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0) |
| +1 | mvnsite | 71 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 682 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 61 | the patch passed |
| +1 | findbugs | 131 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 536 | hadoop-common in the patch failed. |
| +1 | asflicense | 42 | The patch does not generate ASF License warnings. |
| | | 6073 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.util.TestDiskChecker |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1244 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 130ea74477e7 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3cc0ace |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/2/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/2/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/2/testReport/ |
| Max. process+thread count | 1598 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 83 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1224 | trunk passed |
| +1 | compile | 1128 | trunk passed |
| +1 | checkstyle | 50 | trunk passed |
| +1 | mvnsite | 84 | trunk passed |
| +1 | shadedclient | 879 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 63 | trunk passed |
| 0 | spotbugs | 131 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 128 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 54 | the patch passed |
| +1 | compile | 1306 | the patch passed |
| +1 | javac | 1306 | the patch passed |
| -0 | checkstyle | 60 | hadoop-common-project/hadoop-common: The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0) |
| +1 | mvnsite | 98 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 899 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 84 | the patch passed |
| +1 | findbugs | 168 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 632 | hadoop-common in the patch passed. |
| +1 | asflicense | 58 | The patch does not generate ASF License warnings. |
| | | 7084 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1244 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux b4c08c3d87eb 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 00b5a27 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/3/artifact/out/diff-checkstyle-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/3/testReport/ |
| Max. process+thread count | 1779 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1244/3/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
Merged. Thanks @anuengineer and @adoroszlai !

**Pull request merged**
