### PR TITLE
HADOOP-19031. Enhance access control for RunJar.

### PR DESCRIPTION
**Pull request by Shashank-T**
Change backported from v3.4.0

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   4m 51s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.2.4 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  23m 19s |  |  branch-3.2.4 passed  |
| +1 :green_heart: |  compile  |   9m 51s |  |  branch-3.2.4 passed  |
| +1 :green_heart: |  checkstyle  |   0m 37s |  |  branch-3.2.4 passed  |
| +1 :green_heart: |  mvnsite  |   0m 54s |  |  branch-3.2.4 passed  |
| +1 :green_heart: |  javadoc  |   0m 58s |  |  branch-3.2.4 passed  |
| +1 :green_heart: |  spotbugs  |   1m 38s |  |  branch-3.2.4 passed  |
| +1 :green_heart: |  shadedclient  |  11m  5s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 36s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   9m 18s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   9m 18s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 27s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 54s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 46s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   1m 21s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  10m  5s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  14m 44s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 37s |  |  The patch does not generate ASF License warnings.  |
|  |   |  92m 12s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7181/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/7181 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 2863d517b4b8 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2.4 / 22424f9459e8b750d11d4fb05f15b413b092e9a5 |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~18.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7181/1/testReport/ |
| Max. process+thread count | 1266 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7181/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by zeekling — APPROVED** [review]

**Review by zeekling — COMMENTED** [review]
> Change backported from v3.4.0

why pr is mege to [branch-3.2.4](https://github.com/apache/hadoop/tree/branch-3.2.4) ?

**Comment by Shashank-T** [comment]
Looking to backport the changes to v3.2.4 and v3.3.6.
So first raised PR to branch-3.2.4

**Comment by Hexiaoqiao** [comment]
Hi @Shashank-T Thanks for your report. But branch-3.2 is EOL. We do not plan to backport to these branches anymore. Please reference to the active branches, https://cwiki.apache.org/confluence/display/HADOOP/Hadoop+Active+Release+Lines

Will close this PR, please feel free to reopen it if any more addendum. Thanks again.

**Comment by Shashank-T** [comment]
@Hexiaoqiao , is it fine if we expect the change to be back-ported to v3.3.6
In that case, should I raise PR to branch-3.3 or branch-3.3.6 ?

**Pull request closed without merging**
