### PR TITLE
Backport HADOOP-18546: ABFS: Disable purging list of in progress reads in abfs stream closed in 3.3.4

### PR DESCRIPTION
**Pull request by anujmodi2021**
### Description of PR
Jira Ticket: https://issues.apache.org/jira/browse/HADOOP-18546

This task is to cherry pick the fixes to all the branches where the data corruption fix has gone in.

More details on the task and issue: [HADOOP-18521](https://issues.apache.org/jira/browse/HADOOP-18521) ABFS ReadBufferManager buffer sharing across concurrent HTTP requests - ASF JIRA (apache.org)

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  10m 40s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 5 new or modified test files.  |
|||| _ branch-3.3.4 Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 37s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  23m 23s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  compile  |  17m 39s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  checkstyle  |   2m 49s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  mvnsite  |   2m 28s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  javadoc  |   2m 33s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  spotbugs  |   3m 52s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  shadedclient  |  24m 31s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 29s |  |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   0m 28s | [/patch-mvninstall-hadoop-tools_hadoop-azure.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/1/artifact/out/patch-mvninstall-hadoop-tools_hadoop-azure.txt) |  hadoop-azure in the patch failed.  |
| -1 :x: |  compile  |  16m 21s | [/patch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/1/artifact/out/patch-compile-root.txt) |  root in the patch failed.  |
| -1 :x: |  javac  |  16m 21s | [/patch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/1/artifact/out/patch-compile-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   2m 42s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/1/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 2 new + 4 unchanged - 0 fixed = 6 total (was 4)  |
| -1 :x: |  mvnsite  |   0m 51s | [/patch-mvnsite-hadoop-tools_hadoop-azure.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/1/artifact/out/patch-mvnsite-hadoop-tools_hadoop-azure.txt) |  hadoop-azure in the patch failed.  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 43s | [/patch-javadoc-hadoop-tools_hadoop-azure.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/1/artifact/out/patch-javadoc-hadoop-tools_hadoop-azure.txt) |  hadoop-azure in the patch failed.  |
| -1 :x: |  spotbugs  |   0m 49s | [/patch-spotbugs-hadoop-tools_hadoop-azure.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/1/artifact/out/patch-spotbugs-hadoop-tools_hadoop-azure.txt) |  hadoop-azure in the patch failed.  |
| +1 :green_heart: |  shadedclient  |  25m 19s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  17m 16s |  |  hadoop-common in the patch passed.  |
| -1 :x: |  unit  |   0m 39s | [/patch-unit-hadoop-tools_hadoop-azure.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/1/artifact/out/patch-unit-hadoop-tools_hadoop-azure.txt) |  hadoop-azure in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 55s |  |  The patch does not generate ASF License warnings.  |
|  |   | 177m 55s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5531 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux 502eb0648744 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3.4 / 227db1d66ade79313259b023e4d21d84bc7a852b |
| Default Java | Private Build-1.8.0_362-8u362-ga-0ubuntu1~18.04.1-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/1/testReport/ |
| Max. process+thread count | 3158 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-azure U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 56s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 5 new or modified test files.  |
|||| _ branch-3.3.4 Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 24s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  25m 25s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  compile  |  17m 30s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  checkstyle  |   2m 45s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  mvnsite  |   2m 28s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  javadoc  |   2m 30s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  spotbugs  |   3m 54s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  shadedclient  |  24m 23s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 28s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 55s |  |  the patch passed  |
| -1 :x: |  javac  |  16m 55s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/2/artifact/out/results-compile-javac-root.txt) |  root generated 2 new + 1970 unchanged - 2 fixed = 1972 total (was 1972)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   2m 33s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/2/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 2 new + 4 unchanged - 0 fixed = 6 total (was 4)  |
| +1 :green_heart: |  mvnsite  |   2m 27s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 44s | [/patch-javadoc-hadoop-tools_hadoop-azure.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/2/artifact/out/patch-javadoc-hadoop-tools_hadoop-azure.txt) |  hadoop-azure in the patch failed.  |
| +1 :green_heart: |  spotbugs  |   4m  0s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  26m 12s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  18m 20s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 17s |  |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 55s |  |  The patch does not generate ASF License warnings.  |
|  |   | 175m 27s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5531 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux 8fcb8240187a 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3.4 / c7e19bc54acd38b59487a207cbcece9a34f2623d |
| Default Java | Private Build-1.8.0_362-8u362-ga-0ubuntu1~18.04.1-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/2/testReport/ |
| Max. process+thread count | 1265 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-azure U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  10m 14s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 5 new or modified test files.  |
|||| _ branch-3.3.4 Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 27s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  26m 49s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  compile  |  18m 24s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  checkstyle  |   2m 57s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  mvnsite  |   2m 13s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  javadoc  |   2m 14s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  spotbugs  |   3m 42s |  |  branch-3.3.4 passed  |
| +1 :green_heart: |  shadedclient  |  25m 40s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 23s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 25s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 38s |  |  the patch passed  |
| -1 :x: |  javac  |  17m 38s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/3/artifact/out/results-compile-javac-root.txt) |  root generated 1 new + 1977 unchanged - 1 fixed = 1978 total (was 1978)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   2m 44s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/3/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 2 new + 4 unchanged - 0 fixed = 6 total (was 4)  |
| +1 :green_heart: |  mvnsite  |   2m 12s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  2s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m  7s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 46s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  26m  4s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  16m 59s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  2s |  |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 51s |  |  The patch does not generate ASF License warnings.  |
|  |   | 185m 34s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5531 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux 73842b351f51 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3.4 / a139ae7d9abf528100be79b3164f312ff1e685b7 |
| Default Java | Private Build-1.8.0_362-8u362-ga-0ubuntu1~18.04.1-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/3/testReport/ |
| Max. process+thread count | 2220 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-azure U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5531/3/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by ayushtkn — COMMENTED** [review]
your target branch is wrong, 3.3.4 is already released, if you want this in next 3.3.x release, raise a PR to branch-3 and it would be in 3.3.6, before that all are released in the 3.3.x, you can't get anything new included in those released versions

**Pull request closed without merging**
