### PR TITLE
HADOOP-16328: ClassCastException in S3GuardTool.checkMetadataStoreUri

### PR DESCRIPTION
**Pull request by steveloughran**
This does not fix the problem; all it does is provide better diagnostics on a failure (and let someone with a debugger set a breakpoint)

Change-Id: Ife1da9135567fed60f69d7c628a8214e98064243

### CODE REVIEW

**Comment by steveloughran** [comment]
Testing: S3 Ireland + S3guard in PAYG table.

* Saw and filed: HADOOP-16329: "Wrong Billing mode" test failure in ITestS3GuardToolDynamoDB	
* Saw known issue: ITestS3GuardToolDynamoDB>AbstractS3GuardToolTestBase.testBucketInfoUnguarded:342 » FileNotFound

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 77 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1455 | trunk passed |
| +1 | compile | 46 | trunk passed |
| +1 | checkstyle | 33 | trunk passed |
| +1 | mvnsite | 48 | trunk passed |
| +1 | shadedclient | 869 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 32 | trunk passed |
| 0 | spotbugs | 77 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 74 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 39 | the patch passed |
| +1 | compile | 32 | the patch passed |
| +1 | javac | 32 | the patch passed |
| +1 | checkstyle | 18 | the patch passed |
| +1 | mvnsite | 35 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 889 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 27 | the patch passed |
| +1 | findbugs | 79 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 281 | hadoop-aws in the patch passed. |
| +1 | asflicense | 33 | The patch does not generate ASF License warnings. |
| | | 4173 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-849/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/849 |
| JIRA Issue | HADOOP-16328 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 066c27447a52 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 460ba7f |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-849/1/testReport/ |
| Max. process+thread count | 315 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-aws U: hadoop-tools/hadoop-aws |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-849/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
thanks. FWIW once I'd backported some more arg checking code in the S3Guard tool this exception went away, so I'm not quite so sure how critical it is..

**Comment by steveloughran** [comment]
made this go away when I brought my branch up to sync with trunk: there's enough arg checking there that this problem doesn't surface. Closing

**Pull request closed without merging**
