### PR TITLE
HDFS-16551. CryptoInputStream#close() should be syncronized

### PR DESCRIPTION
**Pull request by prasad-acit**
### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  12m 27s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.2 Compile Tests _ |
| -1 :x: |  mvninstall  |  14m 33s | [/branch-mvninstall-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4227/1/artifact/out/branch-mvninstall-root.txt) |  root in branch-3.2 failed.  |
| -1 :x: |  compile  |   2m 46s | [/branch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4227/1/artifact/out/branch-compile-root.txt) |  root in branch-3.2 failed.  |
| +1 :green_heart: |  checkstyle  |   0m 49s |  |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |   1m 25s |  |  branch-3.2 passed  |
| +1 :green_heart: |  javadoc  |   1m 15s |  |  branch-3.2 passed  |
| +1 :green_heart: |  spotbugs  |   2m 23s |  |  branch-3.2 passed  |
| -1 :x: |  shadedclient  |   6m 53s |  |  branch has errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 56s |  |  the patch passed  |
| -1 :x: |  compile  |   2m 40s | [/patch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4227/1/artifact/out/patch-compile-root.txt) |  root in the patch failed.  |
| -1 :x: |  javac  |   2m 40s | [/patch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4227/1/artifact/out/patch-compile-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 40s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 11s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m  2s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   2m  7s |  |  the patch passed  |
| -1 :x: |  shadedclient  |   7m  3s |  |  patch has errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  16m 21s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 44s |  |  The patch does not generate ASF License warnings.  |
|  |   |  73m 54s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4227/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4227 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 3d8c338e391d 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / 784173ffdd3ec127651222d5c39a7100f9734fdb |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4227/1/testReport/ |
| Max. process+thread count | 1261 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4227/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by jojochuang — APPROVED** [review]

**Comment by jojochuang** [comment]
In fact we should cherrypick it to all active branches.

**Comment by prasad-acit** [comment]
Thanks @jojochuang, failures not related to the changes done. 
Also, i dont see any issue with the branch also. I can compile locally successfully. Issue is something related to build environment.
Separate PR to be raised for branch 2.10? Or same can be cherry-picked?

**Comment by jojochuang** [comment]
I was able to cherrypick the commit to branch-2.10 without conflicts so you're all done. Thanks!

**Pull request merged**
