### PR TITLE
HADOOP-18276. Rename CHANGES to CHANGELOG in branch-2.10.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/HADOOP-18276

The file names of changelog generated by releasedocmaker of Yetus was changed from CHANGES.md to CHANGELOG.md. Hyperlinks in the generated index.html of "Changelog and Release Notes" page were also affected. The CHANGES*.md generated in previous releases must be renamed to avoid 404.

### CODE REVIEW

**Comment by iwasakims** [comment]
The diff was simply created by the following command:

```
$ for f in `find . -name 'CHANGES*.md'` ; do git mv $f ${f//CHANGES/CHANGELOG} ; done
```

I verified that the hyperlinks to CHANGELOGs work by building site docs with `-Preleasedocs` profile then seeing built "Changelog and Release Notes" page by browser.

```
$ mvn site site:stage -Preleasedocs -DstagingDirectory=/var/www/html/hadoop-site/branch-2.10
```

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  12m  2s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  4s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  4s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  4s |  |  detect-secrets was not available.  |
| +0 :ok: |  markdownlint  |   0m  4s |  |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ branch-2.10 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  16m 44s |  |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |   1m 19s |  |  branch-2.10 passed  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 49s |  |  the patch passed  |
| -1 :x: |  blanks  |   0m  1s | [/blanks-tabs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4401/1/artifact/out/blanks-tabs.txt) |  The patch 1 line(s) with tabs.  |
| +1 :green_heart: |  mvnsite  |   1m  7s |  |  the patch passed  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 31s |  |  The patch does not generate ASF License warnings.  |
|  |   |  35m 41s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4401/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4401 |
| Optional Tests | dupname asflicense mvnsite codespell detsecrets markdownlint |
| uname | Linux 95031ff9ec86 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / 6d1a1bf8a0fea5f9415951d6588f3a3586c7c378 |
| Max. process+thread count | 83 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4401/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by Hexiaoqiao — APPROVED** [review]
LGTM. +1.
`blanks warning` yetus reported seems related one historical version. It is not a blocker issue for this PR IMO.
Thanks @iwasakims for your works.

**Review by hotcodemacha — APPROVED** [review]

**Comment by hotcodemacha** [comment]
LGTM +1

**Review by steveloughran — APPROVED** [review]
+1

**Comment by iwasakims** [comment]
I merged this. Thanks.

**Pull request merged**
