### PR TITLE
HDFS-17241. avoid doing checkpoint and triggering roll edit log at the same time.

### PR DESCRIPTION
**Pull request by shuaiqig**
### Description of PR
when standby NN triggering log roll on active NN and sending fsimage to active NN at the same time, the active NN will have a long write lock, which blocks almost all requests. like:

```
INFO org.apache.hadoop.hdfs.server.namenode.FSNamesystem: FSNamesystem write lock held for 27179 ms via java.lang.Thread.getStackTrace(Thread.java:1559)
org.apache.hadoop.util.StringUtils.getStackTrace(StringUtils.java:1032)
org.apache.hadoop.hdfs.server.namenode.FSNamesystemLock.writeUnlock(FSNamesystemLock.java:273)
org.apache.hadoop.hdfs.server.namenode.FSNamesystemLock.writeUnlock(FSNamesystemLock.java:235)
org.apache.hadoop.hdfs.server.namenode.FSNamesystem.writeUnlock(FSNamesystem.java:1617)
org.apache.hadoop.hdfs.server.namenode.FSNamesystem.rollEditLog(FSNamesystem.java:4663)
org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.rollEditLog(NameNodeRpcServer.java:1292)
org.apache.hadoop.hdfs.protocolPB.NamenodeProtocolServerSideTranslatorPB.rollEditLog(NamenodeProtocolServerSideTranslatorPB.java:146)
org.apache.hadoop.hdfs.protocol.proto.NamenodeProtocolProtos$NamenodeProtocolService$2.callBlockingMethod(NamenodeProtocolProtos.java:12974)
org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
java.security.AccessController.doPrivileged(Native Method)
javax.security.auth.Subject.doAs(Subject.java:422)
org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
```
 

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 32s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  1s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  35m 50s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   0m 59s |  |  trunk passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  compile  |   0m 50s |  |  trunk passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  checkstyle  |   0m 49s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 56s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   0m 53s |  |  trunk passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 13s |  |  trunk passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  spotbugs  |   1m 57s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  22m 20s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 42s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 43s |  |  the patch passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javac  |   0m 43s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 39s |  |  the patch passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  javac  |   0m 39s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  1s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 32s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 44s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 38s |  |  the patch passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m  2s |  |  the patch passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  spotbugs  |   1m 49s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  23m 22s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 201m 25s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6236/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 38s |  |  The patch does not generate ASF License warnings.  |
|  |   | 300m 33s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.sps.TestExternalStoragePolicySatisfier |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6236/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6236 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux be34bc6c1e15 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 5ab9371669c86b7a42bf2fca221e87713b04a482 |
| Default Java | Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6236/1/testReport/ |
| Max. process+thread count | 3978 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6236/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Hexiaoqiao** [comment]
@shuaiqig Thanks for your report. But I am confused why upload fsimage from standby could hold write lock at active NameNode side? any stack do you print? Thanks again.
BTW, update description which copy from JIRA.

**Comment by tomscut** [comment]
> @shuaiqig Thanks for your report. But I am confused why upload fsimage from standby could hold write lock at active NameNode side? any stack do you print? Thanks again. BTW, update description which copy from JIRA.

Thanks @shuaiqig for your report. And Thanks @Hexiaoqiao for your comments.

There are some real problems here. When SNN does `checkpoint`, it uploads a `fsimage`, which may be tens of gigabytes, which will make the disk where the ANN metadata is stored very busy. 

When `rollEditLog()` is called, ANN writes to `seen_txid` in both the `dfs.namenode.name.dir` and the `dfs.namenode.edits.dir` (regardless of whether they are isolated or not), using a` write lock` . If the ioutil is high, it will take a long time to write the small file `seen_txid`, so indirectly cause ANN to hold the write lock for a long time.

we added a separate lock to achieve mutual exclusion.

**Comment by Hexiaoqiao** [comment]
> it uploads a fsimage, which may be tens of gigabytes, which will make the disk where the ANN metadata is stored very busy

This makes sense to me. I don't know if the case @shuaiqig reported is same as mentioned here. If true, I don't think it could be prevented only avoid do checkpoint and roll editlog at same time from Standby, because sometimes Active could trigger roll editlog by itself. Another side, if not roll editlog in time, it will involve more load for Standby when replay it because there will overstock much more transaction to process. Right? 
IMO, we should improve the local storage performance or limit the throughput when upload fsimage such as decrease `dfs.image.transfer.chunksize`. FYI.

**Comment by shuaiqig** [comment]
> > @shuaiqig Thanks for your report. But I am confused why upload fsimage from standby could hold write lock at active NameNode side? any stack do you print? Thanks again. BTW, update description which copy from JIRA.
> 
> Thanks @shuaiqig for your report. And Thanks @Hexiaoqiao for your comments.
> 
> There are some real problems here. When SNN does `checkpoint`, it uploads a `fsimage`, which may be tens of gigabytes, which will make the disk where the ANN metadata is stored very busy.
> 
> When `rollEditLog()` is called, ANN writes to `seen_txid` in both the `dfs.namenode.name.dir` and the `dfs.namenode.edits.dir` (regardless of whether they are isolated or not), using a` write lock` . If the ioutil is high, it will take a long time to write the small file `seen_txid`, so indirectly cause ANN to hold the write lock for a long time.
> 
> we added a separate lock to achieve mutual exclusion.

Thanks for your answer@tomscut. The reason for this problem has puzzled me for a long time, so I did a lot of debugging and couldn't find it.
And you mentioned "we added a separate lock to achieve mutual exclusion", could you tell me where I can find this patch?

**Comment by shuaiqig** [comment]
> > it uploads a fsimage, which may be tens of gigabytes, which will make the disk where the ANN metadata is stored very busy
> 
> This makes sense to me. I don't know if the case @shuaiqig reported is same as mentioned here. If true, I don't think it could be prevented only avoid do checkpoint and roll editlog at same time from Standby, because sometimes Active could trigger roll editlog by itself. Another side, if not roll editlog in time, it will involve more load for Standby when replay it because there will overstock much more transaction to process. Right? IMO, we should improve the local storage performance or limit the throughput when upload fsimage such as decrease `dfs.image.transfer.chunksize`. FYI.

@Hexiaoqiao Yes, you are right. As I mentioned in jira, this PR is not the best way to solve this problem, it is just the fastest and most convenient way that I can think of temporarily. And thank you for your review.

**Comment by Hexiaoqiao** [comment]
> When rollEditLog() is called, ANN writes to seen_txid in both the dfs.namenode.name.dir and the dfs.namenode.edits.dir (regardless of whether they are isolated or not), using a write lock . If the ioutil is high, it will take a long time to write the small file seen_txid, so indirectly cause ANN to hold the write lock for a long time.

Back to this PR. For HA-mode cluster, if we set the same storage device for both `dfs.namenode.name.dir` and  `dfs.namenode.edits.dir`, it could lead high load of this storage, especially for large cluster and impact performance of ANN. [HDFS-12733](https://issues.apache.org/jira/browse/HDFS-12733) try to disable local edit for HA-mode with shared edit dirs, which proposed years ago. (NOTE: this is draft patch and not checkin to trunk, could not checkin smoothy now, it need to review carefully if reference.) Hope it could solve this issue. Thanks.

**Comment by shuaiqig** [comment]
> > When rollEditLog() is called, ANN writes to seen_txid in both the dfs.namenode.name.dir and the dfs.namenode.edits.dir (regardless of whether they are isolated or not), using a write lock . If the ioutil is high, it will take a long time to write the small file seen_txid, so indirectly cause ANN to hold the write lock for a long time.
> 
> Back to this PR. For HA-mode cluster, if we set the same storage device for both `dfs.namenode.name.dir` and `dfs.namenode.edits.dir`, it could lead high load of this storage, especially for large cluster and impact performance of ANN. [HDFS-12733](https://issues.apache.org/jira/browse/HDFS-12733) try to disable local edit for HA-mode with shared edit dirs, which proposed years ago. (NOTE: this is draft patch and not checkin to trunk, could not checkin smoothy now, it need to review carefully if reference.) Hope it could solve this issue. Thanks.
I have set the different path for `dfs.namenode.name.dir` and `dfs.namenode.edits.dir`, but they are still on the same storage device. I will try to set different storage devices for them later. Thanks for your help.

**Comment by shuaiqig** [comment]
> > When rollEditLog() is called, ANN writes to seen_txid in both the dfs.namenode.name.dir and the dfs.namenode.edits.dir (regardless of whether they are isolated or not), using a write lock . If the ioutil is high, it will take a long time to write the small file seen_txid, so indirectly cause ANN to hold the write lock for a long time.
> 
> Back to this PR. For HA-mode cluster, if we set the same storage device for both `dfs.namenode.name.dir` and `dfs.namenode.edits.dir`, it could lead high load of this storage, especially for large cluster and impact performance of ANN. [HDFS-12733](https://issues.apache.org/jira/browse/HDFS-12733) try to disable local edit for HA-mode with shared edit dirs, which proposed years ago. (NOTE: this is draft patch and not checkin to trunk, could not checkin smoothy now, it need to review carefully if reference.) Hope it could solve this issue. Thanks.

I have set different path for `dfs.namenode.name.dir` and `dfs.namenode.edits.dir`, but they are still on the same storage device. I will try to set different storage devices for them later. Thanks for your help.

**Pull request closed without merging**
