### PR TITLE
HADOOP-16555. Update commons-compress to 1.19.

### PR DESCRIPTION
**Pull request by cxorm**
## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by jojochuang** [comment]
+1
Now I just need to find a way to trigger the precommit build

**Comment by jojochuang** [comment]
Looks like precommit is triggered for non-comitters now. Let's monitor this job: https://builds.apache.org/job/hadoop-multibranch/job/PR-1425/

**Comment by cxorm** [comment]
> Looks like precommit is triggered for non-comitters now. Let's monitor this job: https://builds.apache.org/job/hadoop-multibranch/job/PR-1425/

Thanks !
May I help the work ?

**Comment by jojochuang** [comment]
+1
The precommit had two test failures, both looks unrelated.

However, it didn't report back to GitHub:

> Could not update commit status, please check if your scan credentials belong to a member of the organization or a collaborator of the repository and repo:status scope is selected
>
> GitHub has been notified of this commit’s build result

**Comment by jojochuang** [comment]
For the record, here are the two failed tests:
> org.apache.hadoop.hdfs.TestReconstructStripedFileWithRandomECPolicy.testNNSendsErasureCodingTasks
> org.apache.hadoop.hdfs.qjournal.client.TestQJMWithFaults.testRecoverAfterDoubleFailures

**Pull request merged**
