### PR TITLE
HADOOP-18333. Upgrade jetty version to 9.4.48.v20220622

### PR DESCRIPTION
**Pull request by jojochuang**
Cherry picked #4553 to branch-3.3

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 51s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 41s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  27m  0s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m 51s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m 18s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  21m  1s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   7m  4s |  |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   0m 27s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  59m 31s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 56s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  25m 42s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 12s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  18m 12s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   3m 12s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  20m 33s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   6m 57s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 25s |  |  hadoop-project has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  60m  6s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 773m 58s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4600/1/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m 14s |  |  The patch does not generate ASF License warnings.  |
|  |   | 1074m 26s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.federation.router.TestRouterRpc |
|   | hadoop.hdfs.server.federation.router.TestRouterRpcMultiDestination |
|   | hadoop.hdfs.server.namenode.snapshot.TestRandomOpsWithSnapshots |
|   | hadoop.hdfs.server.namenode.snapshot.TestSnapshot |
|   | hadoop.hdfs.server.blockmanagement.TestBlockStatsMXBean |
|   | hadoop.hdfs.server.namenode.snapshot.TestSnapshotRename |
|   | hadoop.hdfs.tools.TestDFSAdmin |
|   | hadoop.hdfs.server.namenode.TestSecureNameNode |
|   | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |
|   | hadoop.hdfs.server.namenode.TestSecurityTokenEditLog |
|   | hadoop.hdfs.server.namenode.TestFileTruncate |
|   | hadoop.hdfs.server.namenode.TestFSImage |
|   | hadoop.hdfs.server.namenode.TestFsck |
|   | hadoop.hdfs.server.namenode.TestBlockPlacementPolicyRackFaultTolerant |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4600/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4600 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets xmllint shellcheck shelldocs |
| uname | Linux 498b721f9712 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 9d6326071acb9e4859a0be5d5bccb0bce2948ffd |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4600/1/testReport/ |
| Max. process+thread count | 2227 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4600/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
@jojochuang can you do a rebase and push this up so we can see what yetus says now?

**Comment by jojochuang** [comment]
Let's see what it says.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  14m 12s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  1s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  1s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 40s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  29m 22s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m 53s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m 22s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  21m 35s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   7m 12s |  |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   0m 28s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  60m 40s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 58s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  26m 10s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 33s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  18m 33s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   3m 11s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  21m 10s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   7m  1s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 26s |  |  hadoop-project has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  60m 12s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 572m 32s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4600/2/artifact/out/patch-unit-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   2m 27s |  |  The patch does not generate ASF License warnings.  |
|  |   | 893m 45s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.mapred.TestMRTimelineEventHandling |
|   | hadoop.mapred.TestMiniMRClasspath |
|   | hadoop.yarn.client.api.impl.TestAMRMClient |
|   | hadoop.hdfs.server.datanode.TestDataNodeRollingUpgrade |
|   | hadoop.hdfs.tools.TestDFSAdmin |
|   | hadoop.hdfs.server.datanode.fsdataset.impl.TestLazyPersistReplicaRecovery |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4600/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4600 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets xmllint shellcheck shelldocs |
| uname | Linux 541fee4d4af3 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 207f5df1760a0882959105b36dd5645263bb3286 |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4600/2/testReport/ |
| Max. process+thread count | 2216 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4600/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hotcodemacha** [comment]
@jojochuang  I ran the following tests which are failing in Yetus Run and they are passing in local.

```
hadoop.mapred.TestMRTimelineEventHandling
hadoop.mapred.TestMiniMRClasspath
hadoop.yarn.client.api.impl.TestAMRMClient
hadoop.hdfs.server.datanode.TestDataNodeRollingUpgrade
hadoop.hdfs.tools.TestDFSAdmin
hadoop.hdfs.server.datanode.fsdataset.impl.TestLazyPersistReplicaRecovery
```

**Review by hotcodemacha — APPROVED** [review]

**Comment by jojochuang** [comment]
Thanks for verifying the test for me. Merged.

**Comment by hotcodemacha** [comment]
No issues. You are most welcome.

**Pull request merged**
