### PR TITLE
HDFS-16566 Erasure Coding: Recovery may causes excess replicas when b…

### PR DESCRIPTION
**Pull request by tasanuma**
Cherry-pick #4252 to branch-3.3.

### CODE REVIEW

**Review by hotcodemacha — APPROVED** [review]
+1, As its a cherry-pick; Jenkins pending

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 54s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  buf  |   0m  0s |  |  buf was not available.  |
| +0 :ok: |  buf  |   0m  0s |  |  buf was not available.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  1s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 4 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 35s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  24m 14s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |   3m 55s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   1m 21s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   2m 41s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   2m 48s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   6m  6s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  26m 47s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 13s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 40s |  |  the patch passed  |
| +1 :green_heart: |  cc  |   3m 40s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   3m 40s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   1m  0s | [/results-checkstyle-hadoop-hdfs-project.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5059/1/artifact/out/results-checkstyle-hadoop-hdfs-project.txt) |  hadoop-hdfs-project: The patch generated 3 new + 212 unchanged - 0 fixed = 215 total (was 212)  |
| +1 :green_heart: |  mvnsite  |   2m 20s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m  7s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   5m 51s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  26m 37s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 24s |  |  hadoop-hdfs-client in the patch passed.  |
| -1 :x: |  unit  | 239m 31s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5059/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  2s |  |  The patch does not generate ASF License warnings.  |
|  |   | 370m  9s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestDFSInotifyEventInputStreamKerberized |
|   | hadoop.hdfs.server.datanode.TestBPOfferService |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5059/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5059 |
| Optional Tests | dupname asflicense compile cc mvnsite javac unit buflint bufcompat codespell detsecrets javadoc mvninstall shadedclient spotbugs checkstyle |
| uname | Linux 7444298a9bca 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 5d8ed7f67849606856ba988c16d10c9f35272a8c |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5059/1/testReport/ |
| Max. process+thread count | 2953 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5059/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hotcodemacha** [comment]
@tasanuma 

1. Test failed in Jenkins are passing in local during multiple runs. 
2. Checkstyle not related and can be ignored

Screenshot 2022-10-21 at 19 45 33

image

**Comment by tasanuma** [comment]
@ashutoshcipher Thanks for your detailed review! I will merge it.

**Pull request merged**
