### PR TITLE
HDFS-15836. RBF: Fix contract tests after HADOOP-13327

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/HDFS-15836

Fix the following tests:
- TestRouterHDFSContractCreate
- TestRouterHDFSContractCreateSecure
- TestRouterWebHDFSContractCreate

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 38s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |   |   0m  0s | [test4tests](test4tests) |  The patch appears to include 2 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  34m 17s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  47m 48s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 34s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedclient  |  13m 42s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 37s |  |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 35s |  |  The patch does not generate ASF License warnings.  |
|  |   |  66m 35s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2702/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2702 |
| Optional Tests | dupname asflicense unit xml |
| uname | Linux 87c21ab0f2b7 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / c3134ab3a99 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2702/1/testReport/ |
| Max. process+thread count | 667 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-rbf U: hadoop-hdfs-project/hadoop-hdfs-rbf |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2702/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by fengnanli — APPROVED** [review]
Thanks @aajisaka  for the fix! Run into this while working on HDFS-15423.

**Comment by aajisaka** [comment]
Thank you @fengnanli

**Review by ayushtkn — APPROVED** [review]
Thanx @aajisaka for the fix.
+1

**Comment by aajisaka** [comment]
Merged. Thank you @ayushtkn

**Comment by steveloughran** [comment]
doesn't webhdfs support any of the hflush stuff? So it's not 1:1 consistent with HDFS?

**Comment by aajisaka** [comment]
> doesn't webhdfs support any of the hflush stuff? So it's not 1:1 consistent with HDFS?

Yes, it doesn't. There is no documentation for hflush or hsync: https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/WebHDFS.html

**Comment by steveloughran** [comment]
I'm sorry. I thought I'd tested everything, at least through the IDE, but was wrong. The new test really tries to determine what supports hflush/hsync and what just pretends to by not raising an exception in hflush() but which doesn't actually update the output. Apparently the HBase team care about durable storage of their WAL. I've given them the probes, the validation *and the ability to use a RAID-5 local FS as the WAL destination*

**Pull request merged**
