### PR TITLE
HDFS-15815. if required storageType are unavailable, log the failed reason during choosing Datanode. Contributed by Yang Yun.

### PR DESCRIPTION
**Pull request by jojochuang**
(cherry picked from commit e391844e8e414abf8c94f7bd4719053efa3b538a)

### CODE REVIEW

**Comment by jojochuang** [comment]
Only a trivial missing symbol due to HDFS-15355. Replaced that with HdfsConstants.COLD_STORAGE_POLICY_ID.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  22m 57s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  41m 13s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |   1m 32s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   1m  0s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   2m  1s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   1m 58s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   4m  1s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  23m 57s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 21s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 24s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 24s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 49s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 30s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 31s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   4m 14s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  23m 32s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 235m 12s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2882/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 42s |  |  The patch does not generate ASF License warnings.  |
|  |   | 364m 43s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.blockmanagement.TestBlockTokenWithDFS |
|   | hadoop.hdfs.qjournal.server.TestJournalNodeRespectsBindHostKeys |
|   | hadoop.hdfs.TestReconstructStripedFile |
|   | hadoop.hdfs.TestReconstructStripedFileWithValidator |
|   | hadoop.hdfs.TestSafeModeWithStripedFileWithRandomECPolicy |
|   | hadoop.hdfs.TestReconstructStripedFileWithRandomECPolicy |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2882/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2882 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 3ba287a43482 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / e0f095449b960bd1835dfb8b02cb9a4163b38c08 |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~18.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2882/1/testReport/ |
| Max. process+thread count | 2083 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2882/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
@ayushtkn fyi will merge later if no objections.

**Comment by ayushtkn** [comment]
Sure @jojochuang, Thanx

**Comment by tomasbanet** [comment]
Just upgraded our cluster from 3.1.x to 3.3.x, and seeing this log line printed hundreds of times per minute:

```
INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicy: Not enough replicas was chosen. Reason:{NO_REQUIRED_STORAGE_TYPE=1}
```

We have a single rack topology, with replication factor of 3.

For now working around this issue by setting log level of BlockPlacementPolicy to WARN in log4j.properties:

```
log4j.logger.org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicy=WARN
```

**Comment by zlokomatic** [comment]
> Just upgraded our cluster from 3.1.x to 3.3.x, and seeing this log line printed hundreds of times per minute:
> 
> ```
> INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicy: Not enough replicas was chosen. Reason:{NO_REQUIRED_STORAGE_TYPE=1}
> ```
> 
> We have a single rack topology, with replication factor of 3.
> 
> For now working around this issue by setting log level of BlockPlacementPolicy to WARN in log4j.properties:
> 
> ```
> log4j.logger.org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicy=WARN
> ```

We got the same problem. 
Replication factor is 3
dfs.use.dfs.network.topology is set to false

**Pull request merged**
