### PR TITLE
HADOOP-18244. Fix Hadoop-Common JavaDoc Error on branch-3.3

### PR DESCRIPTION
**Pull request by slfan1989**
### Description of PR
JIRA : [HADOOP-18244. Fix Hadoop-Common JavaDoc Error on branch-3.3](https://issues.apache.org/jira/browse/HADOOP-18244)

### For code changes:

In the PR(https://github.com/apache/hadoop/pull/4267) of HADOOP-18224. Upgrade maven compiler plugin to 3.10.1, I found that hadoop-common has a lot of javadoc compilation errors. I fixed it on the trunk, hoping to backport these changes to branch 3.3. These changes will ensure that javadoc will pass in JDK11 compilation.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   7m 40s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  8s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  35m 56s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m 49s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   2m  7s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   2m  3s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   2m 19s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   3m  9s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  27m 32s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m  2s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m  4s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  17m  4s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m 58s |  |  hadoop-common-project/hadoop-common: The patch generated 0 new + 4017 unchanged - 153 fixed = 4017 total (was 4170)  |
| +1 :green_heart: |  mvnsite  |   2m  2s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 19s |  |  hadoop-common-project_hadoop-common generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  spotbugs  |   3m  5s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  27m  8s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  17m 59s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 30s |  |  The patch does not generate ASF License warnings.  |
|  |   | 174m  4s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4327/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4327 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux c41086da0196 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 342e938219b10a11ed64dc859243c354d1946947 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4327/1/testReport/ |
| Max. process+thread count | 2797 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4327/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   4m  2s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  9s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  37m 52s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  19m 26s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   2m  8s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   2m  7s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   2m 20s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   3m 13s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  28m 21s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 10s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 33s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  18m 33s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m  3s |  |  hadoop-common-project/hadoop-common: The patch generated 0 new + 4195 unchanged - 170 fixed = 4195 total (was 4365)  |
| +1 :green_heart: |  mvnsite  |   2m 14s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  2s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m  7s |  |  hadoop-common-project_hadoop-common generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  spotbugs  |   3m 10s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  28m  3s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  18m 11s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 29s |  |  The patch does not generate ASF License warnings.  |
|  |   | 176m  5s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4327/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4327 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux ba320be6661c 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 749749bfe0c482beec285ca2be34ecdcd6317afb |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4327/2/testReport/ |
| Max. process+thread count | 1290 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4327/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by slfan1989** [comment]
Hi, @steveloughran, I have fixed the java-doc of the hadoop-common module of branch-3.3, please help to review the code, I will continue to fix the java doc of other modules, I hope to get your support.

**Comment by slfan1989** [comment]
Hi, @steveloughran, please help to review the code, thank you very match!

**Comment by slfan1989** [comment]
Hi, @steveloughran, please help to review the code, thank you very much!

**Comment by slfan1989** [comment]
Hi, @virajjasani,  please help to review the code, these changes have been merged into trunk to fix java doc issues.

**Comment by virajjasani** [comment]
+1 (non-binding), the backport changes look good, and Jenkins QA results are also good.
Thank you @slfan1989 for your work here. @steveloughran / @aajisaka could help review/merge the PR.

**Comment by slfan1989** [comment]
@ayushtkn, please help to review the code, these changes have been merged into trunk(https://github.com/apache/hadoop/pull/4292). I want to backport these changes to branch-3.3.

**Comment by ayushtkn** [comment]
@slfan1989 can you link the original trunk jira as well in your jira, can you point out what all has changed from trunk to this PR, if there is anything major there....

**Comment by slfan1989** [comment]
> @slfan1989 can you link the original trunk jira as well in your jira, can you point out what all has changed from trunk to this PR, if there is anything major there....

@ayushtkn Thanks for the suggestion, I have linked the original jira（HADOOP-18229）In HADOOP-18244.

In the PR(https://github.com/apache/hadoop/pull/4267) of [HADOOP-18224](https://issues.apache.org/jira/browse/HADOOP-18224). Upgrade maven compiler plugin to 3.10.1, I found that hadoop-common has a lot of javadoc compilation errors. I fixed it on the trunk(https://github.com/apache/hadoop/pull/4292), hoping to backport these changes to branch 3.3. These changes will ensure that  hadoop common moudle javadoc will pass in JDK11 compilation.

**Review by ayushtkn — APPROVED** [review]
LGTM

**Pull request merged**
