### PR TITLE
HDFS-14894. Add balancer parameter to balance top used nodes.

### PR DESCRIPTION
**Pull request by LeonGao91**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 40 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1100 | trunk passed |
| +1 | compile | 65 | trunk passed |
| +1 | checkstyle | 51 | trunk passed |
| +1 | mvnsite | 70 | trunk passed |
| +1 | shadedclient | 837 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 85 | trunk passed |
| 0 | spotbugs | 170 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 169 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 65 | the patch passed |
| +1 | compile | 59 | the patch passed |
| +1 | javac | 59 | the patch passed |
| -0 | checkstyle | 46 | hadoop-hdfs-project/hadoop-hdfs: The patch generated 9 new + 232 unchanged - 0 fixed = 241 total (was 232) |
| +1 | mvnsite | 63 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 764 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 75 | the patch passed |
| +1 | findbugs | 172 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 5251 | hadoop-hdfs in the patch failed. |
| +1 | asflicense | 43 | The patch does not generate ASF License warnings. |
| | | 9025 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.snapshot.TestRenameWithSnapshots |
|   | hadoop.hdfs.server.balancer.TestBalancer |
|   | hadoop.hdfs.tools.TestDFSZKFailoverController |
|   | hadoop.hdfs.TestSafeModeWithStripedFileWithRandomECPolicy |
|   | hadoop.hdfs.server.namenode.TestStartup |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.3 Server=19.03.3 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1636/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1636 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 0ca7dcd3b1f9 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / eeb58a0 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1636/1/artifact/out/diff-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1636/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1636/1/testReport/ |
| Max. process+thread count | 4433 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1636/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by LeonGao91** [comment]
Fixing UT

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 35 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1190 | trunk passed |
| +1 | compile | 62 | trunk passed |
| +1 | checkstyle | 48 | trunk passed |
| +1 | mvnsite | 68 | trunk passed |
| +1 | shadedclient | 906 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 76 | trunk passed |
| 0 | spotbugs | 176 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 174 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 65 | the patch passed |
| +1 | compile | 57 | the patch passed |
| +1 | javac | 57 | the patch passed |
| -0 | checkstyle | 43 | hadoop-hdfs-project/hadoop-hdfs: The patch generated 9 new + 232 unchanged - 0 fixed = 241 total (was 232) |
| +1 | mvnsite | 66 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 838 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 91 | the patch passed |
| +1 | findbugs | 201 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 5006 | hadoop-hdfs in the patch failed. |
| +1 | asflicense | 35 | The patch does not generate ASF License warnings. |
| | | 9030 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.snapshot.TestRenameWithSnapshots |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1636/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1636 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 696b92a7796b 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 9c72bf4 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1636/2/artifact/out/diff-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1636/2/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1636/2/testReport/ |
| Max. process+thread count | 3473 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1636/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by LeonGao91** [comment]
@fapifta @jojochuang Just check back on this : ) Could you please take a look
https://issues.apache.org/jira/browse/HDFS-14894

**Pull request closed without merging**
