### PR TITLE
HDFS-16413. Reconfig dfs usage parameters for datanode (#3863)

### PR DESCRIPTION
**Pull request by tomscut**
Cherry-pick #3863 to branch-3.3.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   4m  0s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 4 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 27s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  29m 12s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m 44s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   2m 49s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   3m 13s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   3m 32s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   6m  0s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  26m 51s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m  6s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 43s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  16m 43s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m 35s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   3m  6s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   3m 23s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   6m  1s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  26m 25s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  17m 28s |  |  hadoop-common in the patch passed.  |
| -1 :x: |  unit  | 195m 31s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4125/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  9s |  |  The patch does not generate ASF License warnings.  |
|  |   | 371m 16s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.datanode.TestDataNodeRollingUpgrade |
|   | hadoop.hdfs.tools.offlineImageViewer.TestOfflineImageViewer |
|   | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4125/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4125 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux cfc353b1f8fc 4.15.0-161-generic #169-Ubuntu SMP Fri Oct 15 13:41:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 2a74effd1ff2eb535731ce8d754eed1adf80287a |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4125/1/testReport/ |
| Max. process+thread count | 3714 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-hdfs-project/hadoop-hdfs U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4125/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by tasanuma — APPROVED** [review]
The failed tests seem not to be related. +1.

**Comment by tasanuma** [comment]
Thanks for the work, @tomscut!

**Comment by tomscut** [comment]
Thank you @tasanuma .

**Pull request merged**
