### PR TITLE
HADOOP-17962. Replace Guava VisibleForTesting by Hadoop's own annotation in hadoop-tools modules

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 45s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  12m 59s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  20m 54s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   3m  6s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |   2m 21s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  checkstyle  |   0m 46s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   5m 32s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   4m 37s |  |  trunk passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   4m 34s |  |  trunk passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |   7m 51s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  18m 42s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 28s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 22s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 59s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |   2m 59s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 14s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |   2m 14s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 38s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   4m 18s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m 13s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   3m 26s |  |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   3m 21s |  |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  spotbugs  |   8m 31s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  18m 31s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  21m  0s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  unit  |   6m 47s |  |  hadoop-federation-balance in the patch passed.  |
| -1 :x: |  unit  |   0m 28s | [/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-infra.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3540/1/artifact/out/patch-unit-hadoop-tools_hadoop-dynamometer_hadoop-dynamometer-infra.txt) |  hadoop-dynamometer-infra in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 58s |  |  hadoop-archive-logs in the patch passed.  |
| +1 :green_heart: |  unit  |  16m  8s |  |  hadoop-gridmix in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 23s |  |  hadoop-aws in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  0s |  |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  unit  |  12m 26s |  |  hadoop-sls in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 59s |  |  hadoop-azure-datalake in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 35s |  |  hadoop-fs2img in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 38s |  |  The patch does not generate ASF License warnings.  |
|  |   | 199m 32s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.tools.dynamometer.TestDynamometerInfra |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3540/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3540 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux 8c7a5724e421 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / d09b31fc96bfa6b2791ba27a9b511cc1032e32c7 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3540/1/testReport/ |
| Max. process+thread count | 1069 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-distcp hadoop-tools/hadoop-federation-balance hadoop-tools/hadoop-dynamometer/hadoop-dynamometer-infra hadoop-tools/hadoop-archive-logs hadoop-tools/hadoop-gridmix hadoop-tools/hadoop-aws hadoop-tools/hadoop-azure hadoop-tools/hadoop-sls hadoop-tools/hadoop-azure-datalake hadoop-tools/hadoop-fs2img U: hadoop-tools |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3540/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
`TestDynamometerInfra` failure doesn't seem relevant.

**Review by tasanuma — APPROVED** [review]
LGTM.

**Comment by tasanuma** [comment]
Merged. Thanks for your contribution, @virajjasani.

**Pull request merged**
