### PR TITLE
HADOOP-18892 fix Catalog Webapp module compile errors due to low nodejs version

### PR DESCRIPTION
**Pull request by AuthurWang2009**
### Description of PR
update nodejs to latest stable version to resolve compile failure

### How was this patch tested?
compile in local

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by slfan1989** [comment]
@AuthurWang2009 Thanks for your contribution! This issue already has a solution (YARN-11528) pr: #5827.

Upgrading node to the latest version may cause other incompatibilities. From my personal point of view, this is not recommended. We can refer to YARN-11528 to temporarily solve this issue.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   9m 41s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3.6 Compile Tests _ |
| -1 :x: |  mvninstall  |  35m 19s | [/branch-mvninstall-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6059/1/artifact/out/branch-mvninstall-root.txt) |  root in branch-3.3.6 failed.  |
| +1 :green_heart: |  compile  |   0m 24s |  |  branch-3.3.6 passed  |
| +1 :green_heart: |  mvnsite  |   0m 35s |  |  branch-3.3.6 passed  |
| +1 :green_heart: |  javadoc  |   0m 29s |  |  branch-3.3.6 passed  |
| -1 :x: |  shadedclient  |  38m 49s |  |  branch has errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 17s |  |  the patch passed  |
| -1 :x: |  compile  |   0m 10s | [/patch-compile-hadoop-project.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6059/1/artifact/out/patch-compile-hadoop-project.txt) |  hadoop-project in the patch failed.  |
| -1 :x: |  javac  |   0m 10s | [/patch-compile-hadoop-project.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6059/1/artifact/out/patch-compile-hadoop-project.txt) |  hadoop-project in the patch failed.  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 20s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 17s |  |  the patch passed  |
| -1 :x: |  shadedclient  |  10m 36s |  |  patch has errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 17s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 36s |  |  The patch does not generate ASF License warnings.  |
|  |   |  65m 42s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6059/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6059 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint |
| uname | Linux 90272e67f1a2 4.15.0-212-generic #223-Ubuntu SMP Tue May 23 13:09:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3.6 / 06dbcb9f6e7cd1796195ed44a2b7b0818b94a420 |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~18.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6059/1/testReport/ |
| Max. process+thread count | 94 (vs. ulimit of 5500) |
| modules | C: hadoop-project U: hadoop-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6059/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
- moved to be a yarn pr; please change title and commit jira to YARN-11569
- the yarn team will need to review (not me)
- all PRs need to be against hadoop `trunk` branch, then backported to branch-3.3, branch-3.2 as appropriate.

**Comment by AuthurWang2009** [comment]
@slfan1989 Thank you for your answer. Indeed, the 
[YARN-11528](https://issues.apache.org/jira/browse/YARN-11528) ,PR: (https://github.com/apache/hadoop/pull/5827) seems to be a better solution.

I will close it later.

**Pull request closed without merging**
