### PR TITLE
HDFS-14318:dn cannot be recognized and must be restarted to recognize the Repaired disk

### PR DESCRIPTION
**Pull request by hunshenshi**
dn detected that disk a has failed. After disk a is repaired, dn cannot be recognized and must be restarted to recognize

 

I make a patch to dn for recognize the repaired disk without restart dn

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 25 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1056 | trunk passed |
| +1 | compile | 60 | trunk passed |
| +1 | checkstyle | 51 | trunk passed |
| +1 | mvnsite | 73 | trunk passed |
| +1 | shadedclient | 761 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 126 | trunk passed |
| +1 | javadoc | 50 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 59 | the patch passed |
| +1 | compile | 56 | the patch passed |
| +1 | javac | 56 | the patch passed |
| -0 | checkstyle | 49 | hadoop-hdfs-project/hadoop-hdfs: The patch generated 8 new + 154 unchanged - 0 fixed = 162 total (was 154) |
| +1 | mvnsite | 59 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 706 | patch has no errors when building and testing our client artifacts. |
| -1 | findbugs | 139 | hadoop-hdfs-project/hadoop-hdfs generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0) |
| +1 | javadoc | 49 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 4735 | hadoop-hdfs in the patch failed. |
| +1 | asflicense | 39 | The patch does not generate ASF License warnings. |
| | | 8128 | |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:hadoop-hdfs-project/hadoop-hdfs |
|  |  Possible doublecheck on org.apache.hadoop.hdfs.server.datanode.DataNode.checkDiskThread in org.apache.hadoop.hdfs.server.datanode.DataNode.startCheckDiskThread()  At DataNode.java:org.apache.hadoop.hdfs.server.datanode.DataNode.startCheckDiskThread()  At DataNode.java:[lines 2161-2163] |
| Failed junit tests | hadoop.hdfs.server.datanode.TestDataNodeHotSwapVolumes |
|   | hadoop.hdfs.qjournal.server.TestJournalNodeSync |
|   | hadoop.hdfs.TestErasureCodingExerciseAPIs |
|   | hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting |
|   | hadoop.hdfs.TestUnsetAndChangeDirectoryEcPolicy |
|   | hadoop.hdfs.server.datanode.TestDataNodeLifeline |
|   | hadoop.hdfs.server.datanode.fsdataset.impl.TestFsDatasetImpl |
|   | hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure |
|   | hadoop.hdfs.TestFileChecksum |
|   | hadoop.hdfs.TestHdfsAdmin |
|   | hadoop.hdfs.TestReconstructStripedFile |
|   | hadoop.hdfs.server.balancer.TestBalancerRPCDelay |
|   | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |
|   | hadoop.tools.TestJMXGet |
|   | hadoop.hdfs.server.namenode.ha.TestRetryCacheWithHA |
|   | hadoop.hdfs.TestFileChecksumCompositeCrc |
|   | hadoop.hdfs.web.TestWebHdfsTimeouts |
|   | hadoop.hdfs.tools.TestDFSAdmin |
|   | hadoop.hdfs.TestDFSStripedOutputStreamWithFailureWithRandomECPolicy |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-538/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/538 |
| JIRA Issue | HDFS-14318 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux e04acdee8463 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / eae3db9 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-538/1/artifact/out/diff-checkstyle-hadoop-hdfs-project_hadoop-hdfs.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-538/1/artifact/out/new-findbugs-hadoop-hdfs-project_hadoop-hdfs.html |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-538/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-538/1/testReport/ |
| Max. process+thread count | 4363 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-538/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by ayushtkn** [comment]
Thanx @hunshenshi for the patch.
* I guess the test failures seems related, can you give a check to them.
* Moreover can you extend a UT for this too.

**Comment by hunshenshi** [comment]
sure. I will update.
Thanks @ayushtkn

**Comment by hunshenshi** [comment]
@ayushtkn  The new PR is [1104](https://github.com/apache/hadoop/pull/1104)
I will close this PR.

**Pull request closed without merging**
