### PR TITLE
HADOOP-17750. Fix asf license errors in newly added files by HADOOP-17727

### PR DESCRIPTION
**Pull request by tasanuma**
JIRA: HADOOP-17750

### CODE REVIEW

**Review by virajjasani — APPROVED** [review]
+1 (non-binding)

**Review by iwasakims — APPROVED** [review]
+1

**Review by aajisaka — APPROVED** [review]

**Review by GauthamBanasandra — APPROVED** [review]

**Comment by tasanuma** [comment]
Thanks for reviewing it, all.
Unfortunately, CI had run over 20h and failed due to timeout. I confirmed `mvn clean apache-rat:check` succeeds with this PR. I will merge it.

**Comment by GauthamBanasandra** [comment]
>I confirmed mvn clean apache-rat:check succeeds with this PR. I will merge it.

No worries @tasanuma. I too created this PR just a couple of hours after you did - https://github.com/apache/hadoop/pull/3082. The CI ran fully and didn't report any ASF license warnings.

**Comment by tasanuma** [comment]
@GauthamBanasandra Oh, I didn't realize the PR. Thanks for the information.

**Pull request merged**
