### PR TITLE
HDDS-2250. Generated configs missing from ozone-filesystem-lib jars

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Concatenate `ozone-default-generated.xml` files using Maven Shade Plugin's built-in XML transformer.

https://issues.apache.org/jira/browse/HDDS-2250

## How was this patch tested?

Ran Hadoop 3.1 and 3.2 acceptance tests:

```
$ cd hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-mr/hadoop32
$ ./test.sh
...
hadoop32-hadoopo3fs :: Test ozone fs with hadoopfs                    | PASS |
...
hadoop32-mapreduce :: Execute MR jobs                                 | PASS |
...

$ cd ../hadoop31
$ ./test.sh
...
hadoop31-hadoopo3fs :: Test ozone fs with hadoopfs                    | PASS |
...
hadoop31-mapreduce :: Execute MR jobs                                 | PASS |
...
```

Checked the concatenated XML:

```
$ unzip hadoop-ozone/ozonefs-lib-current/target/hadoop-ozone-filesystem-lib-current-0.5.0-SNAPSHOT.jar ozone-default-generated.xml
$ grep '<name>' ozone-default-generated.xml| sort -u
    <name>hadoop.hdds.db.rocksdb.logging.enabled</name>
    <name>hadoop.hdds.db.rocksdb.logging.level</name>
    <name>hdds.containerscrub.enabled</name>
    <name>hdds.containerscrub.metadata.scan.interval</name>
    <name>hdds.containerscrub.volume.bytes.per.second</name>
    <name>hdds.ratis.server.num.snapshots.retained</name>
    <name>ozone.om.group.rights</name>
    <name>ozone.om.user.rights</name>
    <name>scm.container.client.idle.threshold</name>
    <name>scm.container.client.max.outstanding.requests</name>
    <name>scm.container.client.max.size</name>
```

CSI and SCM configs are missing, but I think that's because Ozone FS does not depend on CSI and depends on SCM only with test scope.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 82 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| -1 | mvninstall | 30 | hadoop-hdds in trunk failed. |
| -1 | mvninstall | 32 | hadoop-ozone in trunk failed. |
| -1 | compile | 18 | hadoop-hdds in trunk failed. |
| -1 | compile | 13 | hadoop-ozone in trunk failed. |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 969 | branch has no errors when building and testing our client artifacts. |
| -1 | javadoc | 20 | hadoop-hdds in trunk failed. |
| -1 | javadoc | 18 | hadoop-ozone in trunk failed. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 35 | hadoop-hdds in the patch failed. |
| -1 | mvninstall | 40 | hadoop-ozone in the patch failed. |
| -1 | compile | 22 | hadoop-hdds in the patch failed. |
| -1 | compile | 16 | hadoop-ozone in the patch failed. |
| -1 | javac | 22 | hadoop-hdds in the patch failed. |
| -1 | javac | 16 | hadoop-ozone in the patch failed. |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 811 | patch has no errors when building and testing our client artifacts. |
| -1 | javadoc | 18 | hadoop-hdds in the patch failed. |
| -1 | javadoc | 16 | hadoop-ozone in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 25 | hadoop-hdds in the patch failed. |
| -1 | unit | 21 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 2272 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1597 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 03569846e5a9 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 6171a41 |
| Default Java | 1.8.0_222 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/branch-mvninstall-hadoop-hdds.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/branch-mvninstall-hadoop-ozone.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/branch-compile-hadoop-hdds.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/branch-compile-hadoop-ozone.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/branch-javadoc-hadoop-hdds.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/branch-javadoc-hadoop-ozone.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/patch-mvninstall-hadoop-hdds.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/patch-mvninstall-hadoop-ozone.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/patch-compile-hadoop-hdds.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/patch-compile-hadoop-ozone.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/patch-compile-hadoop-hdds.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/patch-compile-hadoop-ozone.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/patch-javadoc-hadoop-hdds.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/patch-javadoc-hadoop-ozone.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/testReport/ |
| Max. process+thread count | 306 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/ozonefs-lib-current U: hadoop-ozone/ozonefs-lib-current |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 35 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| -1 | mvninstall | 38 | hadoop-hdds in trunk failed. |
| -1 | mvninstall | 36 | hadoop-ozone in trunk failed. |
| -1 | compile | 18 | hadoop-hdds in trunk failed. |
| -1 | compile | 13 | hadoop-ozone in trunk failed. |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 974 | branch has no errors when building and testing our client artifacts. |
| -1 | javadoc | 19 | hadoop-hdds in trunk failed. |
| -1 | javadoc | 16 | hadoop-ozone in trunk failed. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 31 | hadoop-hdds in the patch failed. |
| -1 | mvninstall | 34 | hadoop-ozone in the patch failed. |
| -1 | compile | 22 | hadoop-hdds in the patch failed. |
| -1 | compile | 14 | hadoop-ozone in the patch failed. |
| -1 | javac | 22 | hadoop-hdds in the patch failed. |
| -1 | javac | 14 | hadoop-ozone in the patch failed. |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 810 | patch has no errors when building and testing our client artifacts. |
| -1 | javadoc | 19 | hadoop-hdds in the patch failed. |
| -1 | javadoc | 17 | hadoop-ozone in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 29 | hadoop-hdds in the patch failed. |
| -1 | unit | 26 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 32 | The patch does not generate ASF License warnings. |
| | | 2227 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1597 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux d86e32ee678d 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / f826420 |
| Default Java | 1.8.0_222 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/branch-mvninstall-hadoop-hdds.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/branch-mvninstall-hadoop-ozone.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/branch-compile-hadoop-hdds.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/branch-compile-hadoop-ozone.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/branch-javadoc-hadoop-hdds.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/branch-javadoc-hadoop-ozone.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/patch-mvninstall-hadoop-hdds.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/patch-mvninstall-hadoop-ozone.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/patch-compile-hadoop-hdds.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/patch-compile-hadoop-ozone.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/patch-compile-hadoop-hdds.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/patch-compile-hadoop-ozone.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/patch-javadoc-hadoop-hdds.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/patch-javadoc-hadoop-ozone.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/testReport/ |
| Max. process+thread count | 305 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/ozonefs-lib-current U: hadoop-ozone/ozonefs-lib-current |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1597/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by elek** [comment]
+1 thank you very much the fix. And the continuous work to resolve all the acceptance test failures.

**Comment by adoroszlai** [comment]
Thanks @elek for help in finding the root cause.

**Pull request closed without merging**
