### PR TITLE
MAPREDUCE-6973. Appropriate comments on creating _SUCCESS file.

### PR DESCRIPTION
**Pull request by mgarnara**
@jlowe

### CODE REVIEW

**Comment by mgarnara** [comment]
Since Jenkins isn't picking up and commenting on the pull request, reopening again

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 35 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1030 | trunk passed |
| +1 | compile | 30 | trunk passed |
| +1 | checkstyle | 26 | trunk passed |
| +1 | mvnsite | 33 | trunk passed |
| +1 | shadedclient | 690 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 16 | trunk passed |
| 0 | spotbugs | 71 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 68 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 29 | the patch passed |
| +1 | compile | 26 | the patch passed |
| +1 | javac | 26 | the patch passed |
| +1 | checkstyle | 16 | the patch passed |
| +1 | mvnsite | 32 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 696 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 12 | the patch passed |
| +1 | findbugs | 74 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 316 | hadoop-mapreduce-client-core in the patch passed. |
| +1 | asflicense | 24 | The patch does not generate ASF License warnings. |
| | | 3221 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-280/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/280 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 34c1bb0857f4 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 7f1b76c |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-280/1/testReport/ |
| Max. process+thread count | 1613 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core U: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-280/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 12 | https://github.com/apache/hadoop/pull/280 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/280 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-280/2/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
