### PR TITLE
HDDS-1225. Provide docker-compose for OM HA.

### PR DESCRIPTION
**Pull request by hanishakoneru**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 60 | Docker mode activated. |
||| _ Prechecks _ |
| 0 | yamllint | 0 | yamllint was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1143 | trunk passed |
| +1 | compile | 66 | trunk passed |
| +1 | mvnsite | 28 | trunk passed |
| +1 | shadedclient | 720 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 22 | trunk passed |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 20 | dist in the patch failed. |
| +1 | compile | 18 | the patch passed |
| +1 | javac | 18 | the patch passed |
| +1 | mvnsite | 21 | the patch passed |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 17 | The patch generated 0 new + 104 unchanged - 136 fixed = 104 total (was 240) |
| -1 | whitespace | 4 | The patch has 75 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| -1 | whitespace | 5 | The patch 19849  line(s) with tabs. |
| +1 | shadedclient | 1070 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 18 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 23 | dist in the patch passed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 3425 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-562/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/562 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  yamllint  shellcheck  shelldocs  |
| uname | Linux 0b5bb784f557 4.4.0-138-generic #164~14.04.1-Ubuntu SMP Fri Oct 5 08:56:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 62e89dc |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-562/1/artifact/out/patch-mvninstall-hadoop-ozone_dist.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-562/1/artifact/out/whitespace-eol.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-562/1/artifact/out/whitespace-tabs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-562/1/testReport/ |
| Max. process+thread count | 304 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/dist U: hadoop-ozone/dist |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-562/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by elek** [comment]
Thanks the patch @hanishakoneru . It looks good to me.

One comment: please note that @ajayydv proposed to rename ozoneManager everywhere to om in HDDS-1216 

It's not yet committed but it could be useful to switch to that convention (but it also can be done later...)

**Comment by hanishakoneru** [comment]
Thanks for the review @elek . I renamed ozoneManager to om.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 20 | Docker mode activated. |
||| _ Prechecks _ |
| 0 | yamllint | 0 | yamllint was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1243 | trunk passed |
| +1 | compile | 66 | trunk passed |
| +1 | mvnsite | 28 | trunk passed |
| +1 | shadedclient | 692 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 28 | trunk passed |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 19 | dist in the patch failed. |
| +1 | compile | 19 | the patch passed |
| +1 | javac | 19 | the patch passed |
| +1 | mvnsite | 24 | the patch passed |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 14 | The patch generated 0 new + 104 unchanged - 136 fixed = 104 total (was 240) |
| -1 | whitespace | 4 | The patch has 75 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply |
| -1 | whitespace | 5 | The patch 19849  line(s) with tabs. |
| +1 | shadedclient | 1016 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 17 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 24 | dist in the patch passed. |
| +1 | asflicense | 27 | The patch does not generate ASF License warnings. |
| | | 3398 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-562/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/562 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  yamllint  shellcheck  shelldocs  |
| uname | Linux db61dcbb1e8a 4.4.0-138-generic #164~14.04.1-Ubuntu SMP Fri Oct 5 08:56:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 2c3ec37 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-562/2/artifact/out/patch-mvninstall-hadoop-ozone_dist.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-562/2/artifact/out/whitespace-eol.txt |
| whitespace | https://builds.apache.org/job/hadoop-multibranch/job/PR-562/2/artifact/out/whitespace-tabs.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-562/2/testReport/ |
| Max. process+thread count | 309 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/dist U: hadoop-ozone/dist |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-562/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hanishakoneru** [comment]
The unit test failure is unrelated and fails on trunk too.

**Pull request closed without merging**
