### PR TITLE
HDDS-2021. Upgrade Guava library to v26 in hdds project

### PR DESCRIPTION
**Pull request by dineshchitlangia**

### CODE REVIEW

**Comment by anuengineer** [comment]
@dineshchitlangia  I think we have a build issue, can you please check? 

`[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (depcheck) @ hadoop-hdds-common ---
[WARNING] 
Dependency convergence error for com.google.errorprone:error_prone_annotations:2.2.0 paths to dependency are:
+-org.apache.hadoop:hadoop-hdds-common:0.5.0-SNAPSHOT
  +-com.google.errorprone:error_prone_annotations:2.2.0
and
+-org.apache.hadoop:hadoop-hdds-common:0.5.0-SNAPSHOT
  +-com.google.guava:guava:26.0-android
    +-com.google.errorprone:error_prone_annotations:2.1.3`

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 50 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 715 | trunk passed |
| +1 | compile | 456 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 2110 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 190 | trunk passed |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 78 | hadoop-hdds in the patch failed. |
| -1 | compile | 93 | hadoop-hdds in the patch failed. |
| -1 | javac | 93 | hadoop-hdds in the patch failed. |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 807 | patch has no errors when building and testing our client artifacts. |
| -1 | javadoc | 76 | hadoop-hdds in the patch failed. |
| -1 | javadoc | 57 | hadoop-ozone in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 139 | hadoop-hdds in the patch failed. |
| -1 | unit | 2707 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 46 | The patch does not generate ASF License warnings. |
| | | 7406 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.container.server.TestSecureContainerServer |
|   | hadoop.ozone.client.rpc.Test2WayCommitInRatis |
|   | hadoop.ozone.client.rpc.TestCloseContainerHandlingByClient |
|   | hadoop.ozone.client.rpc.TestReadRetries |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1340 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 1d087b3a7d51 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / b69ac57 |
| Default Java | 1.8.0_222 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/1/artifact/out/patch-mvninstall-hadoop-hdds.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/1/artifact/out/patch-compile-hadoop-hdds.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/1/artifact/out/patch-compile-hadoop-hdds.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/1/artifact/out/patch-javadoc-hadoop-hdds.txt |
| javadoc | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/1/artifact/out/patch-javadoc-hadoop-ozone.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/1/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/1/testReport/ |
| Max. process+thread count | 3729 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds U: hadoop-hdds |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 73 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 714 | trunk passed |
| +1 | compile | 406 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 2044 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 180 | trunk passed |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 63 | hadoop-hdds in the patch failed. |
| -1 | compile | 83 | hadoop-hdds in the patch failed. |
| -1 | javac | 83 | hadoop-hdds in the patch failed. |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 672 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 199 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 145 | hadoop-hdds in the patch failed. |
| -1 | unit | 1900 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 46 | The patch does not generate ASF License warnings. |
| | | 6357 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.om.TestOzoneManagerHA |
|   | hadoop.ozone.container.common.statemachine.commandhandler.TestBlockDeletion |
|   | hadoop.ozone.om.TestSecureOzoneManager |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1340 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux 772874d84e0d 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 915cbc9 |
| Default Java | 1.8.0_222 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/2/artifact/out/patch-mvninstall-hadoop-hdds.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/2/artifact/out/patch-compile-hadoop-hdds.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/2/artifact/out/patch-compile-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/2/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/2/testReport/ |
| Max. process+thread count | 5324 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds U: hadoop-hdds |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1340/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by dineshchitlangia** [comment]
No longer an issue and the version was bumped by another jira. Closing PR. Thanks all for reviewing.

**Pull request closed without merging**
