### PR TITLE
HADOOP-18114. Documentation Correction

### PR DESCRIPTION
**Pull request by KraFusion**
Changed reference of s.s3a.assumed.role.credentials.provider to fs.s3a.assumed.role.credentials.provider

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   2m 46s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  33m  5s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   0m 47s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  53m 29s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 35s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 36s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  19m 56s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 35s |  |  The patch does not generate ASF License warnings.  |
|  |   |  79m  2s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3949/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3949 |
| Optional Tests | dupname asflicense mvnsite codespell markdownlint |
| uname | Linux cc73bbfd6344 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / bbd42dd6c71722a55cbbe7556d7750f5c78e6337 |
| Max. process+thread count | 692 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-aws U: hadoop-tools/hadoop-aws |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3949/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by ayushtkn — COMMENTED** [review]
hmm, the change looks correct to me.
But you need to create a Hadoop-Common jira
eg.
https://issues.apache.org/jira/browse/HADOOP-17198

Can go through:
https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

**Comment by KraFusion** [comment]
[HADOOP-18114](https://issues.apache.org/jira/browse/HADOOP-18114)

**Review by ayushtkn — APPROVED** [review]
LGTM

**Review by dannycjones — APPROVED** [review]

**Comment by steveloughran** [comment]
+1 from me, merging

**Pull request merged**
