### PR TITLE
HADOOP-16589. [pb-upgrade] Update docker image to make 3.7.1 protoc as default

### PR DESCRIPTION
**Pull request by vinayakumarb**
Make protoc 3.7.1 as default in Dockerfile.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/hadoop-multibranch/job/PR-1482/2/console in case of problems.

**Comment by ayushtkn** [comment]
The build seems to have failed weirdly :

> Error when executing cleanup post condition:
org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
	at org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution.cancel(TimeoutStepExecution.java:160)
	at org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution.access$100(TimeoutStepExecution.java:38)
	at org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution$1.run(TimeoutStepExecution.java:134)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I guess you need to retriger once again.

**Comment by vinayakumarb** [comment]
Since changes are detected to be in parent module, unit tests were triggered for all modules.
 Jenkins run was aborted  after 5 hrs.

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/hadoop-multibranch/job/PR-1482/3/console in case of problems.

**Comment by vinayakumarb** [comment]
> Well I found the test results to be available
> https://builds.apache.org/job/hadoop-multibranch/job/PR-1482/2/testReport/
> Seems nothing to worry.
> 
> I guess you need to change comment in L109 too.
> Other then that LGTM

Updated the comment. Thanks @ayushtkn .

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 1381 | Docker mode activated. |
| -1 | patch | 13 | https://github.com/apache/hadoop/pull/1482 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1482/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1482 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1482/3/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
