### PR TITLE
YARN-11123. ResourceManager webapps test failures due to org.apache.hadoop.metrics2.MetricsException and subsequent java.net.BindException: Address already in use

### PR DESCRIPTION
**Pull request by szilard-nemeth**
…stem.setMiniClusterMode(true) in setup to prevent throwing an exception when registering the metrics source more than once

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by slfan1989** [comment]
Hi，@[szilard-nemeth](https://github.com/szilard-nemeth) I would like to ask, how do you usually deal with this kind of error report? When I encounter this situation, I need to close the PR first, remove the branch, and submit the PR after re-creating the branch.

**Comment by szilard-nemeth** [comment]
> Hi，@[szilard-nemeth](https://github.com/szilard-nemeth) I would like to ask, how do you usually deal with this kind of error report? When I encounter this situation, I need to close the PR first, remove the branch, and submit the PR after re-creating the branch.

Hi,
What kind of error report do you mean?

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 53s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 33s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  28m  2s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  10m 40s |  |  trunk passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  compile  |   9m 12s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  checkstyle  |   2m  8s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 45s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   2m 44s |  |  trunk passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |   2m 27s |  |  trunk passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  spotbugs  |   4m 49s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  25m 19s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 39s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   9m 56s |  |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javac  |   9m 56s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   8m 59s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |   8m 59s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m 56s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m 31s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 17s |  |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |   2m 12s |  |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  spotbugs  |   4m 45s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  25m 18s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   5m  6s |  |  hadoop-yarn-common in the patch passed.  |
| +1 :green_heart: |  unit  | 101m 42s |  |  hadoop-yarn-server-resourcemanager in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 10s |  |  The patch does not generate ASF License warnings.  |
|  |   | 272m 47s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4289/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4289 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux dba48e8ec410 4.15.0-166-generic #174-Ubuntu SMP Wed Dec 8 19:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 08897ad737a81c394421cbdfd4068b030ab6c413 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4289/3/testReport/ |
| Max. process+thread count | 921 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager U: hadoop-yarn-project/hadoop-yarn |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4289/3/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by slfan1989** [comment]
> > Hi，@[szilard-nemeth](https://github.com/szilard-nemeth) I would like to ask, how do you usually deal with this kind of error report? When I encounter this situation, I need to close the PR first, remove the branch, and submit the PR after re-creating the branch.
> 
> Hi, What kind of error report do you mean?

Hi，@szilard-nemeth，I would like to know the solution to the following error
https://ci-hadoop.apache.org/blue/organizations/jenkins/hadoop-multibranch/detail/PR-4289/1/pipeline

**Comment by zhengchenyu** [comment]
Very expect to merge this PR, my PR https://github.com/apache/hadoop/pull/4270 stuck here.

**Comment by brumi1024** [comment]
Thanks @szilard-nemeth for the patch, looks good to me, merged to trunk.

**Pull request closed without merging**
