### PR TITLE
HDFS-16652. Upgrade jquery datatable version references to v1.10.19

### PR DESCRIPTION
**Pull request by dmmkr**
### Description of PR
Upgrade jquery datatable version references to v1.10.19

### How was this patch tested?
Verified NameNode dfshealth.html and explorer.html
image
image

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by brahmareddybattula** [comment]
@dmmkr  thanks for reporting. changes lgtm.. can raise PR for branch-3.2 also..?

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 36s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  1s |  |  detect-secrets was not available.  |
| +0 :ok: |  jshint  |   0m  1s |  |  jshint was not available.  |
| +0 :ok: |  shelldocs  |   0m  1s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 38s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  25m 10s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  19m 35s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 34s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  22m 39s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  shadedclient  |  19m  8s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m  1s |  |  The patch does not generate ASF License warnings.  |
|  |   | 105m 44s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4562/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4562 |
| Optional Tests | dupname asflicense shadedclient codespell detsecrets jshint shellcheck shelldocs |
| uname | Linux 869da9c8e579 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 931c6d4c9fdcc535c0b7f503f49755e6bd6c7c69 |
| Max. process+thread count | 723 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4562/1/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by hotcodemacha — APPROVED** [review]
+1 (non-binding). LGTM

**Comment by brahmareddybattula** [comment]
+1

**Pull request merged**
