### PR TITLE
HADOOP-16230. Correct findbug ignores for unjustified issues during u…

### PR DESCRIPTION
**Pull request by bgaborg**
…pdate to guava to 27.0-jre in hadoop-project

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| +1 | shadedclient | 838 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 802 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 27 | The patch does not generate ASF License warnings. |
| | | 1811 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-679/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/679 |
| Optional Tests |  dupname  asflicense  xml  |
| uname | Linux c6ca56c5a6ce 4.4.0-138-generic #164~14.04.1-Ubuntu SMP Fri Oct 5 08:56:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / aeb43df |
| maven | version: Apache Maven 3.3.9 |
| Max. process+thread count | 315 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-679/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by bgaborg** [comment]
I will run another round of test locally with https://github.com/apache/hadoop/pull/674 just to be really sure this will solve all remaining findbugs issues

**Comment by bgaborg** [comment]
seems like we have to add both, persistPaxosData AND getPersistedPaxosData. I'll update this PR once I have results.

**Comment by bgaborg** [comment]
Ok, so looking into the logs again this should fix the issue. So this should be OK from my side.

**Comment by mackrorysd** [comment]
Per our offline discussion, I was seeing errors indicating you need to ignore the stream-closing issue and the null reference issue for both persistPaxosData and getPersistedPaxosData. I thought you'd be uploading another patch but I don't see it yet. Am I just not getting the Github PR workflow yet? :)

**Comment by bgaborg** [comment]
there are further findbug issues. I'm going to close this and start fixing those.
https://builds.apache.org/job/PreCommit-HADOOP-Build/16105/artifact/out/new-findbugs-hadoop-hdfs-project_hadoop-hdfs.html
https://builds.apache.org/job/PreCommit-HADOOP-Build/16105/artifact/out/new-findbugs-hadoop-common-project_hadoop-common.html

I want a clean run before we commit this.

**Pull request closed without merging**
