### PR TITLE
HADOOP-16927. Update hadoop-thirdparty dependency version to 1.0.0

### PR DESCRIPTION
**Pull request by vinayakumarb**
## CHANGES
Upgrades the hadoop-thirdparty shaded-protobuf_3.7 artifact to 1.0.0 released version

### CODE REVIEW

**Comment by vinayakumarb** [comment]
> +1
> Give a check, if Jenkins results, may be it would be timeout, since the changes are at project root...
> Thanx @vinayakumarb for the update..

Thanks @ayushtkn .
Here is the run https://builds.apache.org/view/H-L/view/Hadoop/job/hadoop-multibranch/view/change-requests/job/PR-1900/1/console
Not sure why comment didnt come here.

**Comment by ayushtkn** [comment]
Thanx @vinayakumarb  for checking. Seems comment isn't coming, some problem, will check. it isn't coming for patches too.

Anyway the build seems cleans.

**Comment by ayushtkn** [comment]
http://10.18.16.74:8080/view/Hadoop3.1.1_FI_HD_8.0.0_MergeRequest_Build/job/Hadoop3.1.1_HDFSUT_MR/591/#showFailuresLink

Test Failures Seems not related

**Comment by vinayakumarb** [comment]
Thanks @ayushtkn  for review. Merged to trunk.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m  4s |  https://github.com/apache/hadoop/pull/1900 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/1900 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1900/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
