### PR TITLE
HDFS-14670: RBF: Create secret manager instance using FederationUtil#newInstance

### PR DESCRIPTION
**Pull request by chittshota**

### CODE REVIEW

**Comment by goiri** [comment]
The code looks good.
I think that Yatus used to run by itself but it got disabled?
In Spark there is a way to run it, is anybody aware of how to trigger it?

**Comment by chittshota** [comment]
@goiri  Thanks for the review.
@steveloughran Could you help us know how to kick trigger the build ? I saw that you were trying to trigger yetus in some of the recent PRs.

**Comment by ayushtkn** [comment]
Thanx @chittshota, On a quick look, the code looks good.
Regarding the yetus I tried to trigger manually too from Jenkins page but I guess that works only for patches, It gave error no patch available. Well I will try to find a solution today

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 49 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1084 | trunk passed |
| +1 | compile | 35 | trunk passed |
| +1 | checkstyle | 24 | trunk passed |
| +1 | mvnsite | 40 | trunk passed |
| +1 | shadedclient | 732 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 37 | trunk passed |
| 0 | spotbugs | 69 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 67 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 31 | the patch passed |
| +1 | compile | 29 | the patch passed |
| +1 | javac | 29 | the patch passed |
| +1 | checkstyle | 17 | the patch passed |
| +1 | mvnsite | 31 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 758 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 31 | the patch passed |
| +1 | findbugs | 76 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 1315 | hadoop-hdfs-rbf in the patch failed. |
| +1 | asflicense | 26 | The patch does not generate ASF License warnings. |
| | | 4487 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.federation.router.TestRouterWithSecureStartup |
|   | hadoop.hdfs.server.federation.security.TestRouterHttpDelegationToken |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1162/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1162 |
| JIRA Issue | HDFS-14670 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux ee1bfb6f79f0 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / aebac6d |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1162/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs-rbf.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1162/1/testReport/ |
| Max. process+thread count | 1634 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-rbf U: hadoop-hdfs-project/hadoop-hdfs-rbf |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1162/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by goiri** [comment]
It looks like Yetus kicked in.
Not sure if it just triggered everything or what but it works for me.
LGTM +1

**Comment by chittshota** [comment]
@ayushtkn @goiri  Thanks again for the review. Once merged, I can mark the ticket fixed and resolved.

**Comment by chittshota** [comment]
@goiri @ayushtkn Can we merge this? Will update jira once done.

**Comment by goiri** [comment]
https://issues.apache.org/jira/browse/HDFS-14670

**Comment by chittshota** [comment]
@goiri Thanks for merging this.

**Pull request merged**
