### PR TITLE
HADOOP-19342. SaslRpcServer.AuthMethod print INFO messages in client side

### PR DESCRIPTION
**Pull request by szetszwo**
### Description of PR

HADOOP-19342

After [HADOOP-19306](https://issues.apache.org/jira/browse/HADOOP-19306), the following INFO messages are printed in client side. Thanks @steveloughran  for reporting it in https://github.com/apache/hadoop/pull/7140#issuecomment-2483881941 .

We also change `SaslMechanismFactory` in order to lazily loading the conf.  Otherwise, the conf path may not be set up correctly.
```
2024-11-18 18:53:37,645 [setup] INFO  security.SaslRpcServer (SaslRpcServer.java:<init>(239)) - AuthMethod SIMPLE: code=80, mechanism=""
2024-11-18 18:53:37,645 [setup] INFO  security.SaslRpcServer (SaslRpcServer.java:<init>(239)) - AuthMethod KERBEROS: code=81, mechanism="GSSAPI"
2024-11-18 18:53:37,646 [setup] INFO  security.SaslRpcServer (SaslRpcServer.java:<init>(239)) - AuthMethod DIGEST: code=82, mechanism="DIGEST-MD5"
2024-11-18 18:53:37,646 [setup] INFO  security.SaslRpcServer (SaslRpcServer.java:<init>(239)) - AuthMethod TOKEN: code=82, mechanism="DIGEST-MD5"
2024-11-18 18:53:37,646 [setup] INFO  security.SaslRpcServer (SaslRpcServer.java:<init>(239)) - AuthMethod PLAIN: code=83, mechanism="PLAIN"
```

### How was this patch tested?

Manual test.

### For code changes:

- [X] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [NA] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [NA] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [NA] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 34s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  1s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  48m 31s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  19m 13s |  |  trunk passed with JDK Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04  |
| +1 :green_heart: |  compile  |  17m 30s |  |  trunk passed with JDK Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga  |
| +1 :green_heart: |  checkstyle  |   1m 20s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 52s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   1m 17s |  |  trunk passed with JDK Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   0m 59s |  |  trunk passed with JDK Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga  |
| +1 :green_heart: |  spotbugs  |   2m 45s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  39m 50s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m  0s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 49s |  |  the patch passed with JDK Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04  |
| +1 :green_heart: |  javac  |  16m 49s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 13s |  |  the patch passed with JDK Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga  |
| +1 :green_heart: |  javac  |  16m 13s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m 16s |  |  hadoop-common-project/hadoop-common: The patch generated 0 new + 48 unchanged - 1 fixed = 48 total (was 49)  |
| +1 :green_heart: |  mvnsite  |   1m 43s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 15s |  |  the patch passed with JDK Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   0m 55s |  |  the patch passed with JDK Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga  |
| +1 :green_heart: |  spotbugs  |   2m 46s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  37m 12s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  20m 44s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  5s |  |  The patch does not generate ASF License warnings.  |
|  |   | 235m 42s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7174/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/7174 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 563006313dfd 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / bf515f96cad0efa0ae366b74b71b8289c64d3e42 |
| Default Java | Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.25+9-post-Ubuntu-1ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_432-8u432-ga~us1-0ubuntu2~20.04-ga |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7174/1/testReport/ |
| Max. process+thread count | 3109 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7174/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
that test is gone?

**Comment by szetszwo** [comment]
@steveloughran , yes, removed the test since it affects other tests as you mentioned.  Tried multiple things but not working very well. One problem is that `Configuration` has addDefaultResource but not removeDefaultResource. Let skip the test.

**Comment by steveloughran** [comment]
>  Tried multiple things but not working very well. One problem is that Configuration has addDefaultResource but not removeDefaultResource. Let skip the test.

ok. something for the future

I'd thought the trick would be to write an empty config file to the destination, but there's still risk

**Review by steveloughran — APPROVED** [review]
+1

**Comment by szetszwo** [comment]
@steveloughran , @stoty, thanks a lot for reviewing this!

**Pull request merged**
