### PR TITLE
HDFS-16588.Backport HDFS-16584 to branch-3.3.

### PR DESCRIPTION
**Pull request by jianghuazhu**
### Description of PR
This issue has been dealt with in trunk and needs to be backported again to branch 3.3 or another active branch. This is the purpose of this pr.
Details: HDFS-16588

### How was this patch tested?
This can be based on the tests of branch-3.3.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   5m 37s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  38m  3s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |   1m 27s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   1m  7s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   1m 38s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   1m 44s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   3m 44s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  28m 48s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 20s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 14s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 14s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 48s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 21s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 26s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 31s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  27m 58s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 212m  1s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4342/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 57s |  |  The patch does not generate ASF License warnings.  |
|  |   | 329m 59s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestDFSUpgradeFromImage |
|   | hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks |
|   | hadoop.hdfs.TestBlockStoragePolicy |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4342/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4342 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 7add28a902ec 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / c7be6e7e03291acc92b8cf96ea0989a08f6e8a83 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4342/1/testReport/ |
| Max. process+thread count | 2284 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4342/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by jianghuazhu** [comment]
Here are some failing unit tests such as:
org.apache.hadoop.hdfs.TestDFSUpgradeFromImage
org.apache.hadoop.hdfs.server.blockmanagement.TestUnderReplicatedBlocks
org.apache.hadoop.hdfs.TestBlockStoragePolicy

It looks like these failures have little to do with the code I submitted.
@Hexiaoqiao  @tomscut , can you help review this pr?
Thank you very much.

**Review by tomscut — APPROVED** [review]
LGTM.

**Comment by jianghuazhu** [comment]
Thanks @tomscut .

**Review by Hexiaoqiao — APPROVED** [review]
+1

**Comment by Hexiaoqiao** [comment]
Committed to branch-3.3. Thanks @jianghuazhu for your contribution. Thanks @tomscut for your review.

**Pull request merged**
