### PR TITLE
HDDS-1717. Remove OMFailoverProxyProvider's dependency on hadoop-3.2

### PR DESCRIPTION
**Pull request by hanishakoneru**
Refactors OMProxyInfo to not extend FailoverProxyProvider.ProxyInfo (which is a final class before hadoop-3.2).

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 33 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 31 | Maven dependency ordering for branch |
| +1 | mvninstall | 481 | trunk passed |
| +1 | compile | 240 | trunk passed |
| +1 | checkstyle | 73 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 864 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 164 | trunk passed |
| 0 | spotbugs | 310 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 502 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 24 | Maven dependency ordering for patch |
| +1 | mvninstall | 450 | the patch passed |
| +1 | compile | 264 | the patch passed |
| +1 | javac | 264 | the patch passed |
| +1 | checkstyle | 78 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 688 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 163 | the patch passed |
| -1 | findbugs | 315 | hadoop-ozone generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0) |
||| _ Other Tests _ |
| +1 | unit | 240 | hadoop-hdds in the patch passed. |
| -1 | unit | 1166 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 50 | The patch does not generate ASF License warnings. |
| | | 6212 | |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:hadoop-ozone |
|  |  Inconsistent synchronization of org.apache.hadoop.ozone.om.ha.OMFailoverProxyProvider.currentProxyOMNodeId; locked 87% of time  Unsynchronized access at OMFailoverProxyProvider.java:87% of time  Unsynchronized access at OMFailoverProxyProvider.java:[line 182] |
| Failed junit tests | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.ozone.container.common.statemachine.commandhandler.TestBlockDeletion |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.hdds.scm.pipeline.TestRatisPipelineProvider |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.container.server.TestSecureContainerServer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1056/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1056 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux f83dce0d307a 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / acd2d52 |
| Default Java | 1.8.0_212 |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-1056/1/artifact/out/new-findbugs-hadoop-ozone.html |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1056/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1056/1/testReport/ |
| Max. process+thread count | 5402 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/common hadoop-ozone/client hadoop-ozone/integration-test U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1056/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by elek** [comment]
Acceptance test looks good. The reported failure will be fixed by HDDS-1764. 

The findbugs error seems to be related.

**Comment by hanishakoneru** [comment]
Thank you @elek for the review. 
Fixed the findbug error.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 31 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 43 | Maven dependency ordering for branch |
| +1 | mvninstall | 478 | trunk passed |
| +1 | compile | 260 | trunk passed |
| +1 | checkstyle | 75 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 877 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 165 | trunk passed |
| 0 | spotbugs | 313 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 506 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 25 | Maven dependency ordering for patch |
| +1 | mvninstall | 440 | the patch passed |
| +1 | compile | 270 | the patch passed |
| +1 | javac | 270 | the patch passed |
| +1 | checkstyle | 79 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 709 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 159 | the patch passed |
| +1 | findbugs | 518 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 248 | hadoop-hdds in the patch passed. |
| -1 | unit | 1404 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 54 | The patch does not generate ASF License warnings. |
| | | 6525 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.client.rpc.TestFailureHandlingByClient |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.hdds.scm.pipeline.TestSCMPipelineManager |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1056/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1056 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 373a16be14bd 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / de6b7bc |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1056/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1056/2/testReport/ |
| Max. process+thread count | 5148 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/common hadoop-ozone/client hadoop-ozone/integration-test U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1056/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by elek** [comment]
Thanks the patch and the update @hanishakoneru 
I committed it to trunk/ozone-0.4.1.

**Pull request closed without merging**
