### PR TITLE
HDDS-2252. Enable gdpr robot test in daily build

### PR DESCRIPTION
**Pull request by dineshchitlangia**
**What changes were proposed in this pull request?**
Updated test.sh script to include gdpr.robot test so that it gets triggered as part of daily build.

**Link to Apache JIRA**
https://issues.apache.org/jira/browse/HDDS-2252

**How was this patch tested?**
Started Docker
cd ~/ozone-SNAPSHOT/compose/ozone
./test.sh

### CODE REVIEW

**Comment by anuengineer** [comment]
+1, pending Jenkins.

**Comment by dineshchitlangia** [comment]
Checkstyle issue is unrelated to patch. Filed HDDS-2257 to address it.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 87 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 1 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| -1 | mvninstall | 43 | hadoop-hdds in trunk failed. |
| -1 | mvninstall | 37 | hadoop-ozone in trunk failed. |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 948 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 39 | hadoop-hdds in the patch failed. |
| -1 | mvninstall | 41 | hadoop-ozone in the patch failed. |
| +1 | mvnsite | 0 | the patch passed |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 808 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| -1 | unit | 27 | hadoop-hdds in the patch failed. |
| -1 | unit | 24 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 2223 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1602/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1602 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux 533275c9d8f3 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 8de4374 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1602/1/artifact/out/branch-mvninstall-hadoop-hdds.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1602/1/artifact/out/branch-mvninstall-hadoop-ozone.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1602/1/artifact/out/patch-mvninstall-hadoop-hdds.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1602/1/artifact/out/patch-mvninstall-hadoop-ozone.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1602/1/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1602/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1602/1/testReport/ |
| Max. process+thread count | 362 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/dist U: hadoop-ozone/dist |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1602/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by dineshchitlangia** [comment]
@anuengineer , @adoroszlai thanks for review.
@elek Thanks for commit.

**Pull request closed without merging**
