### PR TITLE
HDDS-1136 : Add metric counters to capture the RocksDB checkpointing statistics.

### PR DESCRIPTION
**Pull request by avijayanhwx**
Added metric gauges for tracking DB checkpointing statistics. The OMMetrics class will hold these guages at any instant. These can be pulled from OM by Recon. 

**Testing done**
Integration test for Servlet method that gets the OM DB checkpoint added.
Manually verified the patch on single node Ozone cluster.

### CODE REVIEW

**Comment by avijayanhwx** [comment]
cc @anuengineer @bharatviswa504 @arp7

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 23 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 68 | Maven dependency ordering for branch |
| +1 | mvninstall | 1104 | trunk passed |
| +1 | compile | 945 | trunk passed |
| +1 | checkstyle | 271 | trunk passed |
| +1 | mvnsite | 154 | trunk passed |
| +1 | shadedclient | 1198 | branch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 127 | trunk passed |
| +1 | javadoc | 97 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 20 | Maven dependency ordering for patch |
| -1 | mvninstall | 23 | integration-test in the patch failed. |
| +1 | compile | 920 | the patch passed |
| +1 | javac | 920 | the patch passed |
| +1 | checkstyle | 207 | the patch passed |
| -1 | mvnsite | 33 | integration-test in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 716 | patch has no errors when building and testing our client artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hadoop-ozone/integration-test |
| +1 | findbugs | 135 | the patch passed |
| +1 | javadoc | 97 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 83 | common in the patch failed. |
| -1 | unit | 35 | integration-test in the patch failed. |
| +1 | unit | 45 | ozone-manager in the patch passed. |
| +1 | asflicense | 40 | The patch does not generate ASF License warnings. |
| | | 6326 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.security.x509.certificate.client.TestDefaultCertificateClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-536/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/536 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux 773ed8ce5243 4.4.0-139-generic #165~14.04.1-Ubuntu SMP Wed Oct 31 10:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 0d61fac |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-536/1/artifact/out/patch-mvninstall-hadoop-ozone_integration-test.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-536/1/artifact/out/patch-mvnsite-hadoop-ozone_integration-test.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-536/1/artifact/out/patch-unit-hadoop-hdds_common.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-536/1/artifact/out/patch-unit-hadoop-ozone_integration-test.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-536/1/testReport/ |
| Max. process+thread count | 305 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-ozone/integration-test hadoop-ozone/ozone-manager U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-536/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 6 | https://github.com/apache/hadoop/pull/536 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/536 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-536/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 7 | https://github.com/apache/hadoop/pull/536 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/536 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-536/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by avijayanhwx** [comment]
I am not sure why jenkins is not able to apply my patch on trunk. I pulled from apache hadoop trunk and merged to my branch. I also verified https://github.com/apache/hadoop/pull/536.patch applies cleanly on apache hadoop trunk. @elek Is it possible jenkins is trying to apply individual commits rather than the squashed patch?

**Comment by avijayanhwx** [comment]
Closing this and opening a new one with a single commit.

**Comment by elek** [comment]
> I am not sure why jenkins is not able to apply my patch on trunk. I pulled from apache hadoop trunk and merged to my branch. I also verified https://github.com/apache/hadoop/pull/536.patch applies cleanly on apache hadoop trunk. @elek Is it possible jenkins is trying to apply individual commits rather than the squashed patch?

Don't now. Could be a yetus bug. You can ask it onthe yetus dev list / jira. Or ask @aw-was-here 

BTW, in the PR-s you can do force push. Github handles it very well, you don't need a new PR.

**Pull request closed without merging**
