### PR TITLE
[YARN-10545] Improve the readability of diagnostics log in yarn-ui2 web page.

### PR DESCRIPTION
**Pull request by kyoty**
fix this 
https://issues.apache.org/jira/browse/YARN-10545

manual test works well:
Diagnostics shows ok

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 29s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  33m 12s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  48m 22s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 13s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  14m 53s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 31s |  |  The patch does not generate ASF License warnings.  |
|  |   |  65m 58s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2540/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2540 |
| Optional Tests | dupname asflicense shadedclient |
| uname | Linux 8256f970f0e3 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / be35fa186cc |
| Max. process+thread count | 539 (vs. ulimit of 5500) |
| modules | C: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui U: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2540/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by echohlne** [comment]
@sunilgovind @tangzhankun @jiwq  This pr has heen hang for a long time, can you help to review this? thanks a lot....

**Review by jiwq — COMMENTED** [review]
Good work! LGTM @zhuqi-lucas

**Comment by zhuqi-lucas** [comment]
Thanks @kyoty for patch, @jiwq  for review.
LGTM +1.

**Pull request merged**
