### PR TITLE
HADOOP-16654:Delete hadoop-ozone and hadoop-hdds subprojects from apa…

### PR DESCRIPTION
**Pull request by snemuri**
Deleting hadoop-ozone and hadoop-hdds subprojects.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/hadoop-multibranch/job/PR-1675/1/console in case of problems.

**Comment by anuengineer** [comment]
we should probably add a git tag while committing this .. just my 2 cents.

**Comment by dineshchitlangia** [comment]
@anuengineer Does the tag name `removed-ozone` and description `Removed hadoop-hdds and hadoop-ozone from trunk`look good to you ?

**Comment by anuengineer** [comment]
> @anuengineer Does the tag name `removed-ozone` and description `Removed hadoop-hdds and hadoop-ozone from trunk`look good to you ?

+1.

**Comment by dineshchitlangia** [comment]
Closing this PR as this was merged using the patch.

**Pull request closed without merging**
