### PR TITLE
HADOOP-16665. Filesystems to be closed if they failed during initialize().

### PR DESCRIPTION
**Pull request by steveloughran**
Patches FileSystem to do this, and for S3A have it stop services
during init exception handling.

Also reviewed the mockFS subclass to make sure it gets close() right
and remove all uses of the obsolete S3AUtils.closeAll with
IOUtils.cleanupWithLogger

Change-Id: I0b9fd1aafc902a151a8cacb614058e00d475cd45

### CODE REVIEW

**Comment by steveloughran** [comment]
regression testing in progress. 

I haven't written any tests to explicitly explore the new codepaths.

I will probably add a new common test which has a mock file system that fails during init and whose close() updates a static counter.

Adding a test for S3A's explicit cleanup is a bit trickier. I could probably
add an ITest which tried to create an FS with invalid settings -encryption
ones get checked first- and then close() that after. This will at least show
that the cleanup code is re-entrant.

Trying to force a failure at a specific point after some closable items have been created (instrumentation, thread pools etc) and verifying that these are null afterwards is going to be very brittle. Avoid.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 2196 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 4 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 105 | Maven dependency ordering for branch |
| +1 | mvninstall | 2445 | trunk passed |
| +1 | compile | 2266 | trunk passed |
| +1 | checkstyle | 180 | trunk passed |
| +1 | mvnsite | 134 | trunk passed |
| +1 | shadedclient | 1453 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 370 | trunk passed |
| 0 | spotbugs | 235 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 598 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 63 | Maven dependency ordering for patch |
| +1 | mvninstall | 216 | the patch passed |
| +1 | compile | 2218 | the patch passed |
| +1 | javac | 2218 | the patch passed |
| -0 | checkstyle | 168 | root: The patch generated 1 new + 97 unchanged - 0 fixed = 98 total (was 97) |
| +1 | mvnsite | 122 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 840 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 120 | the patch passed |
| +1 | findbugs | 206 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 540 | hadoop-common in the patch failed. |
| +1 | unit | 87 | hadoop-aws in the patch passed. |
| +1 | asflicense | 46 | The patch does not generate ASF License warnings. |
| | | 14531 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.security.TestRaceWhenRelogin |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1671 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 55c616192b71 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 1d5d7d0 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/1/artifact/out/diff-checkstyle-root.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/1/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/1/testReport/ |
| Max. process+thread count | 1411 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 71 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 7 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 71 | Maven dependency ordering for branch |
| +1 | mvninstall | 1248 | trunk passed |
| +1 | compile | 1083 | trunk passed |
| +1 | checkstyle | 170 | trunk passed |
| +1 | mvnsite | 128 | trunk passed |
| +1 | shadedclient | 1191 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 119 | trunk passed |
| 0 | spotbugs | 68 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 194 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 20 | Maven dependency ordering for patch |
| +1 | mvninstall | 82 | the patch passed |
| +1 | compile | 1028 | the patch passed |
| +1 | javac | 1028 | root generated 0 new + 1884 unchanged - 1 fixed = 1884 total (was 1885) |
| -0 | checkstyle | 169 | root: The patch generated 2 new + 97 unchanged - 0 fixed = 99 total (was 97) |
| +1 | mvnsite | 124 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 842 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 120 | the patch passed |
| +1 | findbugs | 206 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 546 | hadoop-common in the patch passed. |
| +1 | unit | 88 | hadoop-aws in the patch passed. |
| +1 | asflicense | 47 | The patch does not generate ASF License warnings. |
| | | 7533 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1671 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux ee3142834074 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / ee699dc |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/2/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/2/testReport/ |
| Max. process+thread count | 1380 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
Tests exist all good. tested S3 ireland

**Comment by steveloughran** [comment]
just noticed there's a `TestFileSystemInitialization` suite. Moving everything there

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 10 | https://github.com/apache/hadoop/pull/1671 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/1671 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/3/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
Rebased

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 86 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 8 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 73 | Maven dependency ordering for branch |
| +1 | mvninstall | 1241 | trunk passed |
| +1 | compile | 1085 | trunk passed |
| +1 | checkstyle | 175 | trunk passed |
| +1 | mvnsite | 127 | trunk passed |
| +1 | shadedclient | 1184 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 122 | trunk passed |
| 0 | spotbugs | 76 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 221 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 24 | Maven dependency ordering for patch |
| +1 | mvninstall | 89 | the patch passed |
| +1 | compile | 1125 | the patch passed |
| +1 | javac | 1125 | root generated 0 new + 1884 unchanged - 1 fixed = 1884 total (was 1885) |
| -0 | checkstyle | 169 | root: The patch generated 3 new + 98 unchanged - 1 fixed = 101 total (was 99) |
| +1 | mvnsite | 122 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 821 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 116 | the patch passed |
| +1 | findbugs | 206 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 558 | hadoop-common in the patch passed. |
| +1 | unit | 79 | hadoop-aws in the patch passed. |
| +1 | asflicense | 46 | The patch does not generate ASF License warnings. |
| | | 7661 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1671 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 26ecad526057 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 42fc888 |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/4/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/4/testReport/ |
| Max. process+thread count | 1474 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-aws U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1671/4/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
@bgaborg : any final comments here? -this is needed to prevent thread leaks when S3A inits fail, and for other object stores.

**Comment by steveloughran** [comment]
what, you don't trust my code not to break your builds :)

**Comment by bgaborg** [comment]
```
[INFO] Running org.apache.hadoop.fs.contract.s3a.ITestS3AContractRootDir
[ERROR] Tests run: 9, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 48.888 s <<< FAILURE! - in org.apache.hadoop.fs.contract.s3a.ITestS3AContractRootDir
[ERROR] testListEmptyRootDirectory(org.apache.hadoop.fs.contract.s3a.ITestS3AContractRootDir)  Time elapsed: 19.578 s  <<< FAILURE!
java.lang.AssertionError:
Expected no results from listLocatedStatus(/), but got 1 elements:
S3ALocatedFileStatus{path=s3a://cloudera-dev-gabota-versioned-bucket-ireland/fork-0005; isDirectory=true; modification_time=1573489890581; access_time=0; owner=gabota; group=gabota; permission=rwxrwxrwx; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false}[eTag='', versionId='']
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.fs.contract.AbstractContractRootDirectoryTest.assertNoElements(AbstractContractRootDirectoryTest.java:218)
	at org.apache.hadoop.fs.contract.AbstractContractRootDirectoryTest.testListEmptyRootDirectory(AbstractContractRootDirectoryTest.java:202)
	at org.apache.hadoop.fs.contract.s3a.ITestS3AContractRootDir.testListEmptyRootDirectory(ITestS3AContractRootDir.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

[ERROR] testSimpleRootListing(org.apache.hadoop.fs.contract.s3a.ITestS3AContractRootDir)  Time elapsed: 1.054 s  <<< FAILURE!
java.lang.AssertionError:
listStatus(/) vs listLocatedStatus(/) with
listStatus =S3AFileStatus{path=s3a://cloudera-dev-gabota-versioned-bucket-ireland/test; isDirectory=true; modification_time=0; access_time=0; owner=gabota; group=gabota; permission=rwxrwxrwx; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=null versionId=null listLocatedStatus = S3ALocatedFileStatus{path=s3a://cloudera-dev-gabota-versioned-bucket-ireland/fork-0005; isDirectory=true; modification_time=1573489891892; access_time=0; owner=gabota; group=gabota; permission=rwxrwxrwx; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false}[eTag='', versionId='']
S3ALocatedFileStatus{path=s3a://cloudera-dev-gabota-versioned-bucket-ireland/test; isDirectory=true; modification_time=1573489891892; access_time=0; owner=gabota; group=gabota; permission=rwxrwxrwx; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false}[eTag='', versionId=''] expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.apache.hadoop.fs.contract.AbstractContractRootDirectoryTest.testSimpleRootListing(AbstractContractRootDirectoryTest.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

There were two failing sequential tests. I don't think this related, what's your opinion?

**Comment by bgaborg** [comment]
The same two tests are failing for me after the rerun.

**Comment by bgaborg** [comment]
`ITestS3AContractRootDir` is not failing when I run it separately.
I don't see how this is related to your work here, so it's a +1 from me on this because it will stabilize other things.
+1.

**Comment by steveloughran** [comment]
thanks

**Pull request closed without merging**
