### PR TITLE
HDFS-14201. Ability to disallow safemode NN to become active

### PR DESCRIPTION
**Pull request by surmountian**

### CODE REVIEW

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by goiri** [comment]
Is there a way we can trigger Yetus?

**Comment by Hexiaoqiao** [comment]
@surmountian IIUC, this issue has resolved and merged to trunk. Please ref to: https://issues.apache.org/jira/browse/HDFS-14201. This PR could be closed now. cc @goiri 
BTW 'surmountian', 'Xiao Liang' is same one at GitHub and JIRA? ^_^

**Comment by surmountian** [comment]
> @surmountian IIUC, this issue has resolved and merged to trunk. Please ref to: https://issues.apache.org/jira/browse/HDFS-14201. This PR could be closed now. cc @goiri
> BTW 'surmountian', 'Xiao Liang' is same one at GitHub and JIRA? ^_^

yes :-)

**Pull request closed without merging**
