### PR TITLE
HDDS-1180. TestRandomKeyGenerator fails with NPE

### PR DESCRIPTION
**Pull request by elek**
See: https://issues.apache.org/jira/browse/HDDS-1180

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 28 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1006 | trunk passed |
| -1 | compile | 55 | tools in trunk failed. |
| +1 | checkstyle | 15 | trunk passed |
| -1 | mvnsite | 23 | tools in trunk failed. |
| +1 | shadedclient | 648 | branch has no errors when building and testing our client artifacts. |
| -1 | findbugs | 22 | tools in trunk failed. |
| +1 | javadoc | 21 | trunk passed |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 21 | tools in the patch failed. |
| -1 | compile | 19 | tools in the patch failed. |
| -1 | javac | 19 | tools in the patch failed. |
| +1 | checkstyle | 11 | the patch passed |
| -1 | mvnsite | 19 | tools in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 704 | patch has no errors when building and testing our client artifacts. |
| -1 | findbugs | 23 | tools in the patch failed. |
| +1 | javadoc | 19 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 24 | tools in the patch failed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 2779 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-519/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/519 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  findbugs  checkstyle  |
| uname | Linux 0009452f6cdc 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 59ba355 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-519/1/artifact/out/branch-compile-hadoop-ozone_tools.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-519/1/artifact/out/branch-mvnsite-hadoop-ozone_tools.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-519/1/artifact/out/branch-findbugs-hadoop-ozone_tools.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-519/1/artifact/out/patch-mvninstall-hadoop-ozone_tools.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-519/1/artifact/out/patch-compile-hadoop-ozone_tools.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-519/1/artifact/out/patch-compile-hadoop-ozone_tools.txt |
| mvnsite | https://builds.apache.org/job/hadoop-multibranch/job/PR-519/1/artifact/out/patch-mvnsite-hadoop-ozone_tools.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-519/1/artifact/out/patch-findbugs-hadoop-ozone_tools.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-519/1/artifact/out/patch-unit-hadoop-ozone_tools.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-519/1/testReport/ |
| Max. process+thread count | 411 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/tools U: hadoop-ozone/tools |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-519/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by elek** [comment]
See the ci/ozone/unit: Only one unit tests are failed: TestRandomKeyGenerator.ratisTest3 which is not a NPE any more.

**Comment by bharatviswa504** [comment]
+1 LGTM.

**Comment by bharatviswa504** [comment]
This has been already fixed and committed by HDDS-1174.

**Pull request closed without merging**
