### PR TITLE
HADOOP-16583. Minor fixes to S3 testing instructions

### PR DESCRIPTION
**Pull request by sidseth**
Documentation update only. No tests erquired.
## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 2224 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1121 | trunk passed |
| +1 | mvnsite | 41 | trunk passed |
| +1 | shadedclient | 1828 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 34 | the patch passed |
| +1 | mvnsite | 32 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 756 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 5023 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1467/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1467 |
| Optional Tests | dupname asflicense mvnsite |
| uname | Linux 28029cf3e2a6 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 01d7924 |
| Max. process+thread count | 410 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-aws U: hadoop-tools/hadoop-aws |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1467/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
I am really confused now. Our POM does set those properties through specific profiles, s3guard and dynamo. But at the same time, when I look through my commandline history, I've been using -Ddynamodb as the profile. Maybe I've always been wrong, but the fact that my test bucket default to having s3guard and dynamo enabled has compensated
 
 What do you get from
 
 ```
 mvn verify  -Dtest=moo -Ds3guard -Dauth -Ddynamo -Dit.test=ITestS3GuardToolDynamoDB
 ```
 
 That specific ITest will only run its test cases if s3guard and dynamo are enabled.

**Comment by sidseth** [comment]
Interesting. Now I'm confused. That  command ran the tests, and skipped them when dynamo was skipped. Have been having a torrid time trying to get the S3 tests to work ... so lots of option switching on the command line, maybe something got mixed up there. I think this can be discarded. THere's a one line config change which is still valid.

**Comment by steveloughran** [comment]
-1
All the options you have documented are set by specific profiles you can enable with -Ds3guard, -Dscale etc.

But: it might be good to list all these values in a "running under an IDE" section; looking at my settings there I see mine are

```
-ea
-Dfs.s3a.s3guard.test.enabled=true
-Dfs.s3a.s3guard.test.implementation=dynamo
-Dfs.s3a.scale.test.enabled=true
-Dfs.azure.scale.test.enabled=true
-Dfs.s3a.scale.test.huge.partitionsize=5M
```

**Comment by steveloughran** [comment]
-1. this is what the profiles set

**Comment by sidseth** [comment]
Yes. I already agreed this can be discarded. The only fix worth keeping is
-  <value>fs.s3a.assumed.role.sts.endpoint</value>
 + <value>${fs.s3a.assumed.role.sts.endpoint}</value>
Will let that go in with some other patch.

**Pull request closed without merging**
