### PR TITLE
HADOOP-18661. Fix bin/hadoop usage script terminology.

### PR DESCRIPTION
**Pull request by steveloughran**
### Description of PR

Emergency followup to HADOOP-13209 before we cut RC3: s/slaves/r/workers in the usage message you get when you type "bin/hadoop"

Noticed while playing with the RC2 and needed to get in before I kick off RC3 on sunday.

pushing though github for due diligence

### For code changes:

- [X] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   7m  9s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.3.5 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  36m  8s |  |  branch-3.3.5 passed  |
| +1 :green_heart: |  mvnsite  |   1m 21s |  |  branch-3.3.5 passed  |
| +1 :green_heart: |  shadedclient  |  22m 31s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 54s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   1m 11s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m 10s |  |  No new issues.  |
| +1 :green_heart: |  shadedclient  |  22m 22s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   3m  6s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 38s |  |  The patch does not generate ASF License warnings.  |
|  |   |  97m 56s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5473/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5473 |
| Optional Tests | dupname asflicense mvnsite unit codespell detsecrets shellcheck shelldocs |
| uname | Linux 401e49d51bbd 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3.5 / 1bf18d917c0ce29ea9a5655c23b1dcacda7d4599 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5473/1/testReport/ |
| Max. process+thread count | 555 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5473/1/console |
| versions | git=2.17.1 maven=3.6.0 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by ayushtkn — APPROVED** [review]
This change is valid for trunk as well and sounds very reasonable to me. Should consider creating a separate ticket and push to all active lines.

Changes LGTM

**Comment by steveloughran** [comment]
@ayushtkn  will do; just getting it into this one and then moving up, as this is the release to come out today

**Comment by steveloughran** [comment]
+created explicit jira rather than than using the 3.3.5 release id, for better tracking

**Pull request merged**
