### PR TITLE
Backport HADOOP-18546: ABFS: Disable purging list of in progress reads in abfs stream closed in 3.3.2

### PR DESCRIPTION
**Pull request by anujmodi2021**
### Description of PR
Jira Ticket: https://issues.apache.org/jira/browse/HADOOP-18546

This task is to cherry pick the fixes to all the branches where the data corruption fix has gone in.

More details on the task and issue: [HADOOP-18521](https://issues.apache.org/jira/browse/HADOOP-18521) ABFS ReadBufferManager buffer sharing across concurrent HTTP requests - ASF JIRA (apache.org)

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m 42s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 5 new or modified test files.  |
|||| _ branch-3.3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 44s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  37m 46s |  |  branch-3.3.2 passed  |
| -1 :x: |  compile  |   5m 42s | [/branch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/branch-compile-root.txt) |  root in branch-3.3.2 failed.  |
| -0 :warning: |  checkstyle  |   0m 29s | [/buildtool-branch-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/buildtool-branch-checkstyle-root.txt) |  The patch fails to run checkstyle in root  |
| -1 :x: |  mvnsite  |   0m 21s | [/branch-mvnsite-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/branch-mvnsite-hadoop-common-project_hadoop-common.txt) |  hadoop-common in branch-3.3.2 failed.  |
| -1 :x: |  mvnsite  |   0m 39s | [/branch-mvnsite-hadoop-tools_hadoop-azure.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/branch-mvnsite-hadoop-tools_hadoop-azure.txt) |  hadoop-azure in branch-3.3.2 failed.  |
| -1 :x: |  javadoc  |   0m 30s | [/branch-javadoc-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/branch-javadoc-hadoop-common-project_hadoop-common.txt) |  hadoop-common in branch-3.3.2 failed.  |
| -1 :x: |  javadoc  |   0m 32s | [/branch-javadoc-hadoop-tools_hadoop-azure.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/branch-javadoc-hadoop-tools_hadoop-azure.txt) |  hadoop-azure in branch-3.3.2 failed.  |
| -1 :x: |  spotbugs  |   0m 28s | [/branch-spotbugs-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/branch-spotbugs-hadoop-common-project_hadoop-common.txt) |  hadoop-common in branch-3.3.2 failed.  |
| -1 :x: |  spotbugs  |   0m 28s | [/branch-spotbugs-hadoop-tools_hadoop-azure.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/branch-spotbugs-hadoop-tools_hadoop-azure.txt) |  hadoop-azure in branch-3.3.2 failed.  |
| +1 :green_heart: |  shadedclient  |  12m  4s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m  0s |  |  the patch passed  |
| -1 :x: |  compile  |   7m 56s | [/patch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/patch-compile-root.txt) |  root in the patch failed.  |
| -1 :x: |  javac  |   7m 56s | [/patch-compile-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/patch-compile-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   0m 22s | [/buildtool-patch-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/buildtool-patch-checkstyle-root.txt) |  The patch fails to run checkstyle in root  |
| +1 :green_heart: |  mvnsite  |   2m 50s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  2s |  |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   1m 51s | [/results-javadoc-javadoc-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/results-javadoc-javadoc-hadoop-common-project_hadoop-common.txt) |  hadoop-common-project_hadoop-common generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| -1 :x: |  javadoc  |   0m 32s | [/patch-javadoc-hadoop-tools_hadoop-azure.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/patch-javadoc-hadoop-tools_hadoop-azure.txt) |  hadoop-azure in the patch failed.  |
| +1 :green_heart: |  spotbugs  |   4m 56s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  25m 47s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  16m 40s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  6s |  |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 34s |  |  The patch does not generate ASF License warnings.  |
|  |   | 141m 53s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5529 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux 576ca5c5acec 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3.2 / 266225fc89c30961996fd2680ac797ca6eaa3cc4 |
| Default Java | Private Build-1.8.0_362-8u362-ga-0ubuntu1~18.04.1-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/testReport/ |
| Max. process+thread count | 2001 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-azure U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by anujmodi2021** [comment]
Test Results

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27.929 s
[INFO] Finished at: 2023-04-03T23:54:36-07:00
[INFO] ------------------------------------------------------------------------

Running the combination: AppendBlob-HNS-OAuth...
----- Test results -----
[INFO] Results:
[INFO] 
[WARNING] Tests run: 106, Failures: 0, Errors: 0, Skipped: 26
[INFO] Results:
[INFO] 
[WARNING] Tests run: 567, Failures: 0, Errors: 0, Skipped: 567
[INFO] Results:
[INFO] 
[WARNING] Tests run: 265, Failures: 0, Errors: 0, Skipped: 265

Time taken: 2 mins 31 secs.
Find test logs for the combination (AppendBlob-HNS-OAuth) in: dev-support/testlogs/2023-04-03_23-54-36/Test-Logs-AppendBlob-HNS-OAuth.txt
Find consolidated test results in: dev-support/testlogs/2023-04-03_23-54-36/Test-Results.txt
----------

Running the combination: HNS-OAuth...
----- Test results -----
[INFO] Results:
[INFO] 
[WARNING] Tests run: 106, Failures: 0, Errors: 0, Skipped: 26
[INFO] Results:
[INFO] 
[WARNING] Tests run: 567, Failures: 0, Errors: 0, Skipped: 567
[INFO] Results:
[INFO] 
[WARNING] Tests run: 265, Failures: 0, Errors: 0, Skipped: 265

Time taken: 2 mins 26 secs.
Find test logs for the combination (HNS-OAuth) in: dev-support/testlogs/2023-04-03_23-54-36/Test-Logs-HNS-OAuth.txt
Find consolidated test results in: dev-support/testlogs/2023-04-03_23-54-36/Test-Results.txt
----------

Running the combination: HNS-SharedKey...
----- Test results -----
[INFO] Results:
[INFO] 
[WARNING] Tests run: 106, Failures: 0, Errors: 0, Skipped: 26
[INFO] Results:
[INFO] 
[WARNING] Tests run: 567, Failures: 0, Errors: 0, Skipped: 567
[INFO] Results:
[INFO] 
[WARNING] Tests run: 265, Failures: 0, Errors: 0, Skipped: 265

Time taken: 2 mins 31 secs.
Find test logs for the combination (HNS-SharedKey) in: dev-support/testlogs/2023-04-03_23-54-36/Test-Logs-HNS-SharedKey.txt
Find consolidated test results in: dev-support/testlogs/2023-04-03_23-54-36/Test-Results.txt
----------

Running the combination: NonHNS-SharedKey...
----- Test results -----
[INFO] Results:
[INFO] 
[WARNING] Tests run: 106, Failures: 0, Errors: 0, Skipped: 26
[INFO] Results:
[INFO] 
[WARNING] Tests run: 567, Failures: 0, Errors: 0, Skipped: 567
[INFO] Results:
[INFO] 
[WARNING] Tests run: 265, Failures: 0, Errors: 0, Skipped: 265

Time taken: 2 mins 30 secs.
Find test logs for the combination (NonHNS-SharedKey) in: dev-support/testlogs/2023-04-03_23-54-36/Test-Logs-NonHNS-SharedKey.txt
Find consolidated test results in: dev-support/testlogs/2023-04-03_23-54-36/Test-Results.txt

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  6s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  1s |  |  The patch appears to include 5 new or modified test files.  |
|||| _ branch-3.3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 44s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  26m 27s |  |  branch-3.3.2 passed  |
| +1 :green_heart: |  compile  |  18m 16s |  |  branch-3.3.2 passed  |
| +1 :green_heart: |  checkstyle  |   2m 56s |  |  branch-3.3.2 passed  |
| +1 :green_heart: |  mvnsite  |   2m 14s |  |  branch-3.3.2 passed  |
| +1 :green_heart: |  javadoc  |   2m 13s |  |  branch-3.3.2 passed  |
| +1 :green_heart: |  spotbugs  |   3m 47s |  |  branch-3.3.2 passed  |
| +1 :green_heart: |  shadedclient  |  25m 56s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 22s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 25s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 38s |  |  the patch passed  |
| -1 :x: |  javac  |  17m 38s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/2/artifact/out/results-compile-javac-root.txt) |  root generated 1 new + 1970 unchanged - 1 fixed = 1971 total (was 1971)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   2m 53s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/2/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 1 new + 4 unchanged - 0 fixed = 5 total (was 4)  |
| +1 :green_heart: |  mvnsite  |   2m 12s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  2s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m  9s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 49s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  25m 31s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  17m 47s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 26s |  |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  9s |  |  The patch does not generate ASF License warnings.  |
|  |   | 176m 39s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5529 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux 03065f0f227a 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3.2 / 569cb3d0e33a10ded04c1948a80fac0cb0ebb002 |
| Default Java | Private Build-1.8.0_362-8u362-ga-0ubuntu1~18.04.1-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/2/testReport/ |
| Max. process+thread count | 3143 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-azure U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  5s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 5 new or modified test files.  |
|||| _ branch-3.3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 43s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  34m 58s |  |  branch-3.3.2 passed  |
| +1 :green_heart: |  compile  |  18m 22s |  |  branch-3.3.2 passed  |
| +1 :green_heart: |  checkstyle  |   3m  1s |  |  branch-3.3.2 passed  |
| +1 :green_heart: |  mvnsite  |   2m 16s |  |  branch-3.3.2 passed  |
| +1 :green_heart: |  javadoc  |   2m 11s |  |  branch-3.3.2 passed  |
| +1 :green_heart: |  spotbugs  |   3m 45s |  |  branch-3.3.2 passed  |
| +1 :green_heart: |  shadedclient  |  27m  2s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 43s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  22m 22s |  |  the patch passed  |
| -1 :x: |  javac  |  22m 22s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/3/artifact/out/results-compile-javac-root.txt) |  root generated 1 new + 1970 unchanged - 1 fixed = 1971 total (was 1971)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   2m 53s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/3/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 1 new + 4 unchanged - 0 fixed = 5 total (was 4)  |
| +1 :green_heart: |  mvnsite  |   2m 18s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m 13s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 53s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  25m 58s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  17m  0s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 17s |  |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 51s |  |  The patch does not generate ASF License warnings.  |
|  |   | 181m 56s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5529 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux 81e6acfcb679 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3.2 / bdc6fac17b0c9ab2509193e43f650eecb7632956 |
| Default Java | Private Build-1.8.0_362-8u362-ga-0ubuntu1~18.04.1-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/3/testReport/ |
| Max. process+thread count | 3132 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-tools/hadoop-azure U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5529/3/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
