### PR TITLE
HADOOP-18088. Replace log4j 1.x with reload4j.

### PR DESCRIPTION
**Pull request by iwasakims**
backporting [HADOOP-18088](https://issues.apache.org/jira/browse/HADOOP-18088) to branch-3.2.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  11m 32s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 23s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  26m  8s |  |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |  15m 40s |  |  branch-3.2 passed  |
| +1 :green_heart: |  checkstyle  |   2m 41s |  |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |  19m  9s |  |  branch-3.2 passed  |
| +1 :green_heart: |  javadoc  |  15m 52s |  |  branch-3.2 passed  |
| +0 :ok: |  spotbugs  |   0m 25s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 26s |  |  branch/hadoop-client-modules/hadoop-client no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 24s |  |  branch/hadoop-client-modules/hadoop-client-check-invariants no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 25s |  |  branch/hadoop-client-modules/hadoop-client-check-test-invariants no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 24s |  |  branch/hadoop-client-modules/hadoop-client-integration-tests no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 25s |  |  branch/hadoop-client-modules/hadoop-client-minicluster no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 25s |  |  branch/hadoop-client-modules/hadoop-client-runtime no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  15m 55s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  22m 31s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  15m  6s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  15m  6s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m 40s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  19m  2s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m 33s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |  15m 42s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 25s |  |  hadoop-project has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 28s |  |  hadoop-client-modules/hadoop-client has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 27s |  |  hadoop-client-modules/hadoop-client-runtime has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 27s |  |  hadoop-client-modules/hadoop-client-check-invariants has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 27s |  |  hadoop-client-modules/hadoop-client-minicluster has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 27s |  |  hadoop-client-modules/hadoop-client-check-test-invariants has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 26s |  |  hadoop-client-modules/hadoop-client-integration-tests has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  14m 40s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 24s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 37s |  |  hadoop-minikdc in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 18s |  |  hadoop-auth in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 27s |  |  hadoop-auth-examples in the patch passed.  |
| +1 :green_heart: |  unit  |  16m  1s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 45s |  |  hadoop-nfs in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 40s |  |  hadoop-kms in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  3s |  |  hadoop-hdfs-client in the patch passed.  |
| -1 :x: |  unit  | 217m 38s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4084/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 28s |  |  hadoop-hdfs-httpfs in the patch passed.  |
| +1 :green_heart: |  unit  |   3m  8s |  |  hadoop-hdfs-nfs in the patch passed.  |
| +1 :green_heart: |  unit  |  19m 21s |  |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 34s |  |  hadoop-yarn-common in the patch passed.  |
| -1 :x: |  unit  |  79m 34s | [/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4084/1/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-resourcemanager.txt) |  hadoop-yarn-server-resourcemanager in the patch passed.  |
| +1 :green_heart: |  unit  |  26m  1s |  |  hadoop-yarn-client in the patch passed.  |
| +1 :green_heart: |  unit  |  18m 57s |  |  hadoop-yarn-applications-distributedshell in the patch passed.  |
| +1 :green_heart: |  unit  | 155m 53s |  |  hadoop-mapreduce-client in the patch passed.  |
| +1 :green_heart: |  unit  |  18m 40s |  |  hadoop-yarn-services-core in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 12s |  |  hadoop-yarn-submarine in the patch passed.  |
| +1 :green_heart: |  unit  | 156m 13s |  |  hadoop-mapreduce-project in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  6s |  |  hadoop-azure in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 39s |  |  hadoop-client in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 41s |  |  hadoop-client-runtime in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 40s |  |  hadoop-client-check-invariants in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 41s |  |  hadoop-client-minicluster in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 40s |  |  hadoop-client-check-test-invariants in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 39s |  |  hadoop-client-integration-tests in the patch passed.  |
| -1 :x: |  asflicense  |   1m 17s | [/results-asflicense.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4084/1/artifact/out/results-asflicense.txt) |  The patch generated 1 ASF License warnings.  |
|  |   | 1015m  8s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.tools.offlineImageViewer.TestOfflineImageViewer |
|   | hadoop.hdfs.server.namenode.ha.TestStandbyCheckpoints |
|   | hadoop.hdfs.TestDFSInotifyEventInputStreamKerberized |
|   | hadoop.hdfs.server.blockmanagement.TestBlockStatsMXBean |
|   | hadoop.hdfs.TestRollingUpgrade |
|   | hadoop.hdfs.TestReconstructStripedFileWithValidator |
|   | hadoop.yarn.server.resourcemanager.reservation.TestCapacityOverTimePolicy |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4084/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4084 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux a54ff7a020d6 4.15.0-162-generic #170-Ubuntu SMP Mon Oct 18 11:38:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / 49369bd79c0d985e06db767dc72dead0f287feb3 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4084/1/testReport/ |
| Max. process+thread count | 1964 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-minikdc hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-auth-examples hadoop-common-project/hadoop-common hadoop-common-project/hadoop-nfs hadoop-common-project/hadoop-kms hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-httpfs hadoop-hdfs-project/hadoop-hdfs-nfs hadoop-hdfs-project/hadoop-hdfs-rbf hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell hadoop-mapreduce-project/hadoop-mapreduce-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services/hadoop-yarn-services-core hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-submarine hadoop-mapreduce-project hadoop-tools/hadoop-azure hadoop-client-modules/hadoop-client hadoop-client-modules/hadoop-client-runtime hadoop-client-modules/hadoop-client-check-invariants hadoop-client-modules/hadoop-client-minicluster hadoop-client-modules/hadoop-client-check-test-invariants hadoop-client-modules/hadoop-client-integration-tests U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4084/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  11m 40s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-3.2 Compile Tests _ |
| +0 :ok: |  mvndep  |   3m 19s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  26m 18s |  |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |  15m 33s |  |  branch-3.2 passed  |
| +1 :green_heart: |  checkstyle  |   2m 40s |  |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |  16m  0s |  |  branch-3.2 passed  |
| +1 :green_heart: |  javadoc  |   5m 53s |  |  branch-3.2 passed  |
| +0 :ok: |  spotbugs  |   0m 16s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 20s |  |  branch/hadoop-client-modules/hadoop-client no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 19s |  |  branch/hadoop-client-modules/hadoop-client-check-invariants no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 20s |  |  branch/hadoop-client-modules/hadoop-client-check-test-invariants no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 19s |  |  branch/hadoop-client-modules/hadoop-client-integration-tests no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 21s |  |  branch/hadoop-client-modules/hadoop-client-minicluster no spotbugs output file (spotbugsXml.xml)  |
| +0 :ok: |  spotbugs  |   0m 19s |  |  branch/hadoop-client-modules/hadoop-client-runtime no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  15m 22s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  44m 44s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  15m  3s |  |  the patch passed  |
| +1 :green_heart: |  javac  |  15m  3s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   2m 41s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  13m 33s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m 32s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   5m 49s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 15s |  |  hadoop-project has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 18s |  |  hadoop-client-modules/hadoop-client has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 17s |  |  hadoop-client-modules/hadoop-client-runtime has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 18s |  |  hadoop-client-modules/hadoop-client-check-invariants has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 18s |  |  hadoop-client-modules/hadoop-client-minicluster has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 17s |  |  hadoop-client-modules/hadoop-client-check-test-invariants has no data from spotbugs  |
| +0 :ok: |  spotbugs  |   0m 18s |  |  hadoop-client-modules/hadoop-client-integration-tests has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  40m  1s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 651m 35s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4084/2/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| -1 :x: |  asflicense  |   1m  5s | [/results-asflicense.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4084/2/artifact/out/results-asflicense.txt) |  The patch generated 1 ASF License warnings.  |
|  |   | 963m 26s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.mapred.uploader.TestFrameworkUploader |
|   | hadoop.yarn.server.timelineservice.security.TestTimelineAuthFilterForV2 |
|   | hadoop.security.TestRaceWhenRelogin |
|   | hadoop.hdfs.TestDatanodeRegistration |
|   | hadoop.hdfs.server.datanode.TestBPOfferService |
|   | hadoop.hdfs.tools.offlineImageViewer.TestOfflineImageViewer |
|   | hadoop.hdfs.TestRollingUpgrade |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4084/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/4084 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml spotbugs checkstyle |
| uname | Linux 1de7dd986b18 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / 0a357e3663026dc650d314863eeebdf3f6668516 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4084/2/testReport/ |
| Max. process+thread count | 2043 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-minikdc hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-auth-examples hadoop-common-project/hadoop-common hadoop-common-project/hadoop-nfs hadoop-common-project/hadoop-kms hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-httpfs hadoop-hdfs-project/hadoop-hdfs-nfs hadoop-hdfs-project/hadoop-hdfs-rbf hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell hadoop-mapreduce-project/hadoop-mapreduce-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-services/hadoop-yarn-services-core hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-submarine hadoop-mapreduce-project hadoop-tools/hadoop-azure hadoop-client-modules/hadoop-client hadoop-client-modules/hadoop-client-runtime hadoop-client-modules/hadoop-client-check-invariants hadoop-client-modules/hadoop-client-minicluster hadoop-client-modules/hadoop-client-check-test-invariants hadoop-client-modules/hadoop-client-integration-tests . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-4084/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by steveloughran — APPROVED** [review]
+1 from me, license warning and test failures look unrelated

**Comment by iwasakims** [comment]
Thanks, @steveloughran. merged this to branch-3.2. If I need to cut 3.2.3 RC2, cherry-picking this to branch-3.2.3 could be an option.

**Pull request merged**
