### PR TITLE
HADOOP-17612. Upgrade Zookeeper to 3.6.3 and Curator to 5.2.0 (#3241)

### PR DESCRIPTION
**Pull request by melissayou**
### Description of PR
It is a clean cherry-pick from commit `ccfa072` in trunk to upgrade zookeeper and curator. 

### How was this patch tested?
`mvn test` no extra unit test failure
`mvn clean install -Pdist -Dtar -DskipTests -Dmaven.javadoc.skip` builds successfully

### For code changes:

- [X] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [X] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Review by xinglin — APPROVED** [review]
lgtm, pending yetus

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  11m 37s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  17m 37s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  27m  4s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  19m  3s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m 11s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  21m 34s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   7m  8s |  |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   0m 23s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  59m 31s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 39s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  39m 50s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 33s |  |  the patch passed  |
| -1 :x: |  javac  |  18m 33s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/1/artifact/out/results-compile-javac-root.txt) |  root generated 10 new + 1867 unchanged - 0 fixed = 1877 total (was 1867)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   3m  6s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/1/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 1 new + 356 unchanged - 2 fixed = 357 total (was 358)  |
| +1 :green_heart: |  mvnsite  |  21m  8s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   7m  0s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 22s |  |  hadoop-project has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  60m 18s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 720m  4s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/1/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 54s |  |  The patch does not generate ASF License warnings.  |
|  |   | 1073m 18s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestRollingUpgrade |
|   | hadoop.hdfs.tools.TestDFSAdmin |
|   | hadoop.hdfs.server.datanode.TestDataNodeRollingUpgrade |
|   | hadoop.hdfs.server.namenode.ha.TestHAMetrics |
|   | hadoop.hdfs.TestFileCreation |
|   | hadoop.yarn.client.api.impl.TestAMRMClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5047 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint spotbugs checkstyle shellcheck shelldocs |
| uname | Linux e92120545992 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 679535c33e2229f16acf0917b6b99c3e73f23f69 |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/1/testReport/ |
| Max. process+thread count | 3137 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-nfs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-mawo/hadoop-yarn-applications-mawo-core . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 59s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 44s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  27m  0s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m 58s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m  9s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  21m 42s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   8m  7s |  |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   0m 27s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  66m 24s |  |  branch has no errors when building and testing our client artifacts.  |
| -0 :warning: |  patch  |  66m 50s |  |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 41s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  34m 51s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  21m 13s |  |  the patch passed  |
| -1 :x: |  javac  |  21m 13s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/2/artifact/out/results-compile-javac-root.txt) |  root generated 10 new + 1862 unchanged - 0 fixed = 1872 total (was 1862)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   3m  5s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/2/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 1 new + 356 unchanged - 2 fixed = 357 total (was 358)  |
| +1 :green_heart: |  mvnsite  |  22m 19s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   7m 59s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 25s |  |  hadoop-project has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  67m  5s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 749m  8s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/2/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m 19s |  |  The patch does not generate ASF License warnings.  |
|  |   | 1107m 46s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.namenode.TestFsck |
|   | hadoop.hdfs.qjournal.server.TestJournalNodeSync |
|   | hadoop.hdfs.server.datanode.TestDataNodeErasureCodingMetrics |
|   | hadoop.fs.http.client.TestHttpFSFWithSWebhdfsFileSystem |
|   | hadoop.yarn.server.nodemanager.containermanager.logaggregation.TestLogAggregationService |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5047 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint spotbugs checkstyle shellcheck shelldocs |
| uname | Linux 0a6a2a8ea4fd 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 97a6e29130803fcce7ea06c32454980294e8814c |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/2/testReport/ |
| Max. process+thread count | 2159 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-nfs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-mawo/hadoop-yarn-applications-mawo-core . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/2/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 51s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  1s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  1s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  1s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  15m  6s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  29m 21s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  22m 10s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m 33s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  23m 13s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   7m 33s |  |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   0m 23s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  66m 23s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 43s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  34m 55s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  21m 37s |  |  the patch passed  |
| -1 :x: |  javac  |  21m 37s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/4/artifact/out/results-compile-javac-root.txt) |  root generated 10 new + 1869 unchanged - 0 fixed = 1879 total (was 1869)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   3m 29s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/4/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 1 new + 356 unchanged - 2 fixed = 357 total (was 358)  |
| +1 :green_heart: |  mvnsite  |  23m  3s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   7m 17s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 23s |  |  hadoop-project has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  68m 33s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 739m 48s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/4/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m  1s |  |  The patch does not generate ASF License warnings.  |
|  |   | 1106m 54s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.TestReconstructStripedFileWithRandomECPolicy |
|   | hadoop.hdfs.server.datanode.TestNNHandlesCombinedBlockReport |
|   | hadoop.hdfs.server.namenode.TestReconstructStripedBlocks |
|   | hadoop.hdfs.TestFileCreation |
|   | hadoop.yarn.sls.appmaster.TestAMSimulator |
|   | hadoop.yarn.server.resourcemanager.scheduler.capacity.TestCapacitySchedulerAutoQueueCreation |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5047 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint spotbugs checkstyle shellcheck shelldocs |
| uname | Linux bb7d17fffdf1 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / f136ca0aa79442a4732c804eed4871ebae94798b |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/4/testReport/ |
| Max. process+thread count | 3137 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-nfs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-mawo/hadoop-yarn-applications-mawo-core . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/4/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 46s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 2 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +0 :ok: |  mvndep  |  17m  7s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  27m  9s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |  18m 54s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   3m 16s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |  21m 26s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   7m  9s |  |  branch-3.3 passed  |
| +0 :ok: |  spotbugs  |   0m 24s |  |  branch/hadoop-project no spotbugs output file (spotbugsXml.xml)  |
| +1 :green_heart: |  shadedclient  |  59m 59s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 45s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  31m 30s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 23s |  |  the patch passed  |
| -1 :x: |  javac  |  18m 23s | [/results-compile-javac-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/5/artifact/out/results-compile-javac-root.txt) |  root generated 10 new + 1869 unchanged - 0 fixed = 1879 total (was 1869)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| -0 :warning: |  checkstyle  |   3m  5s | [/results-checkstyle-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/5/artifact/out/results-checkstyle-root.txt) |  root: The patch generated 1 new + 356 unchanged - 2 fixed = 357 total (was 358)  |
| +1 :green_heart: |  mvnsite  |  21m  4s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   6m 55s |  |  the patch passed  |
| +0 :ok: |  spotbugs  |   0m 24s |  |  hadoop-project has no data from spotbugs  |
| +1 :green_heart: |  shadedclient  |  60m  9s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 723m  8s | [/patch-unit-root.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/5/artifact/out/patch-unit-root.txt) |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 47s |  |  The patch does not generate ASF License warnings.  |
|  |   | 1056m  5s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.datanode.TestBPOfferService |
|   | hadoop.yarn.sls.appmaster.TestAMSimulator |
|   | hadoop.yarn.service.TestYarnNativeServices |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/5047 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell detsecrets xmllint spotbugs checkstyle shellcheck shelldocs |
| uname | Linux cdab87de024f 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / f136ca0aa79442a4732c804eed4871ebae94798b |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~18.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/5/testReport/ |
| Max. process+thread count | 2233 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-auth hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-nfs hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-mawo/hadoop-yarn-applications-mawo-core . U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/5/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m  0s |  |  Docker mode activated.  |
| -1 :x: |  patch  |   0m 14s |  |  https://github.com/apache/hadoop/pull/5047 does not apply to branch-3.3. Rebase required? Wrong Branch? See https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/5047 |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-5047/6/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
