### PR TITLE
HDFS-15870. Remove unused configuration dfs.namenode.stripe.min

### PR DESCRIPTION
**Pull request by tomscut**
JIRA: https://issues.apache.org/jira/browse/HDFS-15870

Remove unused configuration dfs.namenode.stripe.min.

### CODE REVIEW

**Review by tasanuma — APPROVED** [review]
+1.

**Comment by tasanuma** [comment]
The failed tests are not related. I will file them if necessary.

**Comment by tasanuma** [comment]
Thanks for your contribution, @tomscut.

**Comment by tomscut** [comment]
Thanks @tasanuma for merging.

**Comment by tomscut** [comment]
Hi @tasanuma , I used a wrong email address in some COMMITS I submitted before. I can modify locally through rebase, but I don't have permission to push. Is there any way to modify it? Thank you for your answer!

**Comment by tomscut** [comment]
After submitting code to Hadoop, I don’t see the commits. I don’t know why. Do not know whether the email address setting error caused.

I can see contributions here:
https://github.com/apache/hadoop/pulls/@me

But cannot see here:
https://github.com/apache/hadoop/graphs/contributors?from=2021-01-01&to=2021-03-06&type=c

**Comment by tomscut** [comment]
Hi @tasanuma , I found the reason here [cannot-see-contributions-after-commit-code](https://github.community/t/cannot-see-contributions-after-commit-code/166210/3
).

I have set wrong email addresses for 1 pull requests. Can I correct it? Looking forward to your reply. Thanks a lot.

**Comment by tasanuma** [comment]
@tomscut Sorry, we cannot modify commit logs once we pushed them.

**Comment by tomscut** [comment]
> @tomscut Sorry, we cannot modify commit logs once we pushed them.

OK, thank you for your answer.

**Pull request merged**
