### PR TITLE
HDDS-2156. Fix alignment issues in HDDS doc pages

### PR DESCRIPTION
**Pull request by vivekratnavel**

### CODE REVIEW

**Comment by vivekratnavel** [comment]
@anuengineer Please review

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 2278 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| -1 | mvninstall | 33 | hadoop-ozone in trunk failed. |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1030 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 33 | hadoop-ozone in the patch failed. |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 670 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 30 | The patch does not generate ASF License warnings. |
| | | 4241 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1479/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1479 |
| Optional Tests | dupname asflicense mvnsite |
| uname | Linux 41e8f6f8a56d 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / b7ae8a9 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1479/1/artifact/out/branch-mvninstall-hadoop-ozone.txt |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1479/1/artifact/out/patch-mvninstall-hadoop-ozone.txt |
| Max. process+thread count | 412 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/docs U: hadoop-hdds/docs |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1479/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by anuengineer** [comment]
thank you for the contribution. I have committed this to the trunk.

**Pull request closed without merging**
