### PR TITLE
HDFS-17531. [Discuss] RBF: Aynchronous router RPC.

### PR DESCRIPTION
**Pull request by KeeProMise**
### Description of PR
This PR is mainly for your reference. 
Welcome to discuss it. https://issues.apache.org/jira/browse/HDFS-17531

### How was this patch tested?

Currently, I have modified these UTs to use asynchronous router for your reference.

TestNoNamenodesAvailableLongTime
TestObserverWithRouter
TestRouterFederationRename
TestRouterFederationRenamePermission
TestRouterQuota
TestRouterRefreshSuperUserGroupsConfiguration
TestRouterRpc
TestRouterRpcMultiDestination
TestRouterRPCMultipleDestinationMountTableResolver
TestRouterRpcSingleNS
TestRouterRpcStoragePolicySatisfier
TestRouterUserMappings

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

### CODE REVIEW

**Comment by ayushtkn** [comment]
passing by: discuss threads should be on hadoop dev mailing lists

**Comment by slfan1989** [comment]
@KeeProMise Thanks for the contribution! This pr is too large and it seems that it cannot be reviewed.

Let’s first follow the process and discuss it on the hadoop dev mailing list.  After the discussion is passed, we can consider splitting the pr for easier review.

**Comment by KeeProMise** [comment]
@ayushtkn @slfan1989 hi, thanks for you replay, I sent the discussion to common-dev@hadoop.apache.org.

**Comment by slfan1989** [comment]
> @ayushtkn @slfan1989 hi, thanks for you replay, I sent the discussion to [common-dev@hadoop.apache.org](mailto:common-dev@hadoop.apache.org).

@KeeProMise This pr has too many changes and affects multiple modules, causing the compilation to time out. I have seen the discussion emails, and the usual discussion process may take 5-7 days.

**Comment by KeeProMise** [comment]
Thank you again for your attention. I will split this huge PR into small PRs. You can review the PRs in the subtasks. I will close this huge PR.

**Pull request closed without merging**
