### PR TITLE
HDDS-2001. Update Ratis version to 0.4.0.

### PR DESCRIPTION
**Pull request by nandakumar131**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 157 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ ozone-0.4.1 Compile Tests _ |
| 0 | mvndep | 85 | Maven dependency ordering for branch |
| +1 | mvninstall | 732 | ozone-0.4.1 passed |
| +1 | compile | 444 | ozone-0.4.1 passed |
| +1 | checkstyle | 91 | ozone-0.4.1 passed |
| +1 | mvnsite | 0 | ozone-0.4.1 passed |
| +1 | shadedclient | 1049 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 186 | ozone-0.4.1 passed |
| 0 | spotbugs | 438 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 676 | ozone-0.4.1 passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 42 | Maven dependency ordering for patch |
| +1 | mvninstall | 567 | the patch passed |
| +1 | compile | 398 | the patch passed |
| +1 | javac | 398 | the patch passed |
| +1 | checkstyle | 82 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 3 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 648 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 174 | the patch passed |
| +1 | findbugs | 643 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 190 | hadoop-hdds in the patch failed. |
| -1 | unit | 282 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 44 | The patch does not generate ASF License warnings. |
| | | 6695 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.container.common.statemachine.commandhandler.TestCloseContainerCommandHandler |
|   | hadoop.ozone.om.ratis.TestOzoneManagerRatisServer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1497/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1497 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml |
| uname | Linux 3f9cc7b12697 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | ozone-0.4.1 / 2eb41fb |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1497/1/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1497/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1497/1/testReport/ |
| Max. process+thread count | 1150 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds hadoop-hdds/container-service hadoop-ozone hadoop-ozone/ozone-manager U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1497/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by anuengineer** [comment]
Looks like Ozone file system is not happy with this change ?

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 964 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ ozone-0.4.1 Compile Tests _ |
| 0 | mvndep | 29 | Maven dependency ordering for branch |
| +1 | mvninstall | 681 | ozone-0.4.1 passed |
| +1 | compile | 388 | ozone-0.4.1 passed |
| +1 | checkstyle | 79 | ozone-0.4.1 passed |
| +1 | mvnsite | 0 | ozone-0.4.1 passed |
| +1 | shadedclient | 879 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 176 | ozone-0.4.1 passed |
| 0 | spotbugs | 421 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 615 | ozone-0.4.1 passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 40 | Maven dependency ordering for patch |
| +1 | mvninstall | 553 | the patch passed |
| +1 | compile | 390 | the patch passed |
| +1 | javac | 390 | the patch passed |
| +1 | checkstyle | 90 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 3 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 719 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 174 | the patch passed |
| +1 | findbugs | 633 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 322 | hadoop-hdds in the patch passed. |
| -1 | unit | 2382 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 53 | The patch does not generate ASF License warnings. |
| | | 9391 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.scm.pipeline.TestRatisPipelineCreateAndDestory |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.hdds.scm.pipeline.TestRatisPipelineProvider |
|   | hadoop.ozone.client.rpc.TestContainerReplicationEndToEnd |
|   | hadoop.ozone.client.rpc.TestWatchForCommit |
|   | hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1497/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1497 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml |
| uname | Linux 006cbfc41bc7 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | ozone-0.4.1 / 2eb41fb |
| Default Java | 1.8.0_222 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1497/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1497/2/testReport/ |
| Max. process+thread count | 5361 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds hadoop-hdds/container-service hadoop-ozone hadoop-ozone/ozone-manager U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1497/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by nandakumar131** [comment]
Fixed as part of #1524

**Pull request closed without merging**
