### PR TITLE
Branched to archive the Avro RPC work. On trunk Avro RPC is removed a…

### PR DESCRIPTION
**Pull request by arif505**
…fter creating this branch.

git-svn-id: https://svn.apache.org/repos/asf/hadoop/common/branches/HADOOP-6659@1214008 13f79535-47bb-0310-9956-ffa450edef68

### CODE REVIEW

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 82 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 24 | Maven dependency ordering for branch |
| +1 | shadedclient | 884 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 26 | Maven dependency ordering for patch |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 869 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 1993 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-77/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/77 |
| Optional Tests | dupname asflicense |
| uname | Linux 6b92906aa93f 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 7f1b76c |
| Max. process+thread count | 303 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-77/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 84 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 26 | Maven dependency ordering for branch |
| +1 | shadedclient | 866 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 25 | Maven dependency ordering for patch |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 879 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 30 | The patch does not generate ASF License warnings. |
| | | 1983 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-77/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/77 |
| Optional Tests | dupname asflicense |
| uname | Linux 33cef374a2ee 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 62efb63 |
| Max. process+thread count | 304 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-77/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 45 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 24 | Maven dependency ordering for branch |
| +1 | shadedclient | 764 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for patch |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 704 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 28 | The patch does not generate ASF License warnings. |
| | | 1648 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-77/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/77 |
| Optional Tests | dupname asflicense |
| uname | Linux bbff7d7dff94 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e872ceb |
| Max. process+thread count | 447 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-77/3/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for branch |
| +1 | shadedclient | 721 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for patch |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 708 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 24 | The patch does not generate ASF License warnings. |
| | | 1601 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-77/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/77 |
| Optional Tests | dupname asflicense |
| uname | Linux ea419ef09126 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 00b5a27 |
| Max. process+thread count | 412 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-77/4/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 97 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 27 | Maven dependency ordering for branch |
| +1 | shadedclient | 974 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 29 | Maven dependency ordering for patch |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| -1 | shadedclient | 149 | patch has errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 32 | The patch does not generate ASF License warnings. |
| | | 1385 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-77/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/77 |
| Optional Tests | dupname asflicense |
| uname | Linux d77c7be4b885 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 8943e13 |
| Max. process+thread count | 294 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-77/5/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 20 | Maven dependency ordering for branch |
| +1 | shadedclient | 743 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for patch |
| +1 | whitespace | 1 | The patch has no whitespace issues. |
| +1 | shadedclient | 713 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 24 | The patch does not generate ASF License warnings. |
| | | 1632 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-77/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/77 |
| Optional Tests | dupname asflicense |
| uname | Linux 0c265d7d6b30 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 4cb22cd |
| Max. process+thread count | 447 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-77/6/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 44 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 22 | Maven dependency ordering for branch |
| +1 | shadedclient | 768 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 21 | Maven dependency ordering for patch |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 706 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 25 | The patch does not generate ASF License warnings. |
| | | 1646 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-77/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/77 |
| Optional Tests | dupname asflicense |
| uname | Linux 1319b28df3be 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e04dcfd |
| Max. process+thread count | 444 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-77/7/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 237 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 26 | Maven dependency ordering for branch |
| +1 | shadedclient | 1039 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 28 | Maven dependency ordering for patch |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 956 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 32 | The patch does not generate ASF License warnings. |
| | | 2409 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-77/8/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/77 |
| Optional Tests | dupname asflicense |
| uname | Linux dad0baf00aa2 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3329257 |
| Max. process+thread count | 307 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-77/8/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 86 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 20 | Maven dependency ordering for branch |
| +1 | shadedclient | 890 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 25 | Maven dependency ordering for patch |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 855 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | asflicense | 27 | The patch does not generate ASF License warnings. |
| | | 1986 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-77/9/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/77 |
| Optional Tests | dupname asflicense |
| uname | Linux 4b21e3fa51c4 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 915cbc9 |
| Max. process+thread count | 306 (vs. ulimit of 5500) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-77/9/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
Invalid. Closing

**Pull request closed without merging**
