### PR TITLE
HDDS-1999. Basic acceptance test and SCM/OM web UI broken by Bootstrap upgrade

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Update bootstrap/jquery version references in SCM/OM/S3G and in acceptance test.

https://issues.apache.org/jira/browse/HDDS-1999

## How was this patch tested?

Ran `basic.robot` in `ozones3` compose folder.

Checked SCM/OM/S3G web UI visually.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 101 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 68 | Maven dependency ordering for branch |
| +1 | mvninstall | 635 | trunk passed |
| +1 | compile | 362 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1809 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 164 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 28 | Maven dependency ordering for patch |
| +1 | mvninstall | 576 | the patch passed |
| +1 | compile | 372 | the patch passed |
| +1 | javac | 372 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 663 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 172 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 292 | hadoop-hdds in the patch passed. |
| -1 | unit | 1938 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 43 | The patch does not generate ASF License warnings. |
| | | 6339 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.om.TestOzoneManagerHA |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.client.rpc.TestCloseContainerHandlingByClient |
|   | hadoop.ozone.TestStorageContainerManager |
|   | hadoop.ozone.client.rpc.TestCommitWatcher |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |
|   | hadoop.ozone.ozShell.TestOzoneShell |
|   | hadoop.ozone.container.server.TestSecureContainerServer |
|   | hadoop.ozone.TestMiniChaosOzoneCluster |
|   | hadoop.hdds.scm.pipeline.TestSCMPipelineManager |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1327/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1327 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient |
| uname | Linux 82563191e4ef 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / e684b17 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1327/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1327/1/testReport/ |
| Max. process+thread count | 3843 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/server-scm hadoop-ozone/dist hadoop-ozone/ozone-manager hadoop-ozone/s3gateway U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1327/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by adoroszlai** [comment]
@vivekratnavel @elek please review

**Comment by elek** [comment]
HDDS-2000 is also related but I would like to remove the dependencies between HDFS and HDDS web pages.

**Comment by vivekratnavel** [comment]
I agree with @elek. We should have a copy of all the static dependencies inside HDDS and not depend on HDFS.

**Comment by adoroszlai** [comment]
@elek @vivekratnavel breaking the dependency is fine, but can we please get rid of the acceptance test failures?

**Comment by adoroszlai** [comment]
Thanks @bharatviswa504 for review/commit.

**Pull request merged**
