### PR TITLE
HADOOP-16612 Track Azure Blob File System client-perceived latency

### PR DESCRIPTION
**Pull request by jeeteshm**
Add instrumentation code to measure the ADLS Gen 2 API performance
Add a feature switch to optionally enable this feature
Add unit tests for correctness and performance

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 229 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1602 | trunk passed |
| +1 | compile | 40 | trunk passed |
| +1 | checkstyle | 32 | trunk passed |
| +1 | mvnsite | 42 | trunk passed |
| +1 | shadedclient | 1057 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 31 | trunk passed |
| 0 | spotbugs | 67 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 65 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 39 | the patch passed |
| +1 | compile | 40 | the patch passed |
| +1 | javac | 40 | the patch passed |
| -0 | checkstyle | 27 | hadoop-tools/hadoop-azure: The patch generated 71 new + 5 unchanged - 0 fixed = 76 total (was 5) |
| +1 | mvnsite | 45 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 1032 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 30 | the patch passed |
| +1 | findbugs | 70 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 87 | hadoop-azure in the patch passed. |
| +1 | asflicense | 32 | The patch does not generate ASF License warnings. |
| | | 4619 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1569/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1569 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml |
| uname | Linux 6c880c1b063c 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / d947ded |
| Default Java | 1.8.0_222 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-1569/1/artifact/out/diff-checkstyle-hadoop-tools_hadoop-azure.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1569/1/testReport/ |
| Max. process+thread count | 332 (vs. ulimit of 5500) |
| modules | C: hadoop-tools/hadoop-azure U: hadoop-tools/hadoop-azure |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1569/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 12 | https://github.com/apache/hadoop/pull/1569 does not apply to trunk. Rebase required? Wrong Branch? See https://wiki.apache.org/hadoop/HowToContribute for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hadoop/pull/1569 |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1569/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by jeeteshm** [comment]
Raising a new PR because this one shows changes that don't belong to me.

**Comment by virajith** [comment]
@jeeteshm -- can you clean up this PR to include only your changes?

**Comment by jeeteshm** [comment]
Duplicate of #1611

**Pull request closed without merging**
