### PR TITLE
 HADOOP-15910 Fix Javadoc for LdapAuthenticationHandler#ENABLE_START_TLS

### PR DESCRIPTION
**Pull request by drajakumar**

### CODE REVIEW

**Comment by elek** [comment]
Can one of the admins verify this patch?

**Comment by steveloughran** [comment]
+1 from me. 
Before I merge it, what name do you want to be credited by? Add it in the description field so when I press "merge" it will go in. Git will record you as the author, but with cherrypicking across branches, its easy for the original author to get lost

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 37 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1098 | trunk passed |
| +1 | compile | 1054 | trunk passed |
| +1 | checkstyle | 24 | trunk passed |
| +1 | mvnsite | 44 | trunk passed |
| +1 | shadedclient | 731 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 23 | trunk passed |
| 0 | spotbugs | 40 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 39 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 23 | the patch passed |
| +1 | compile | 996 | the patch passed |
| +1 | javac | 996 | the patch passed |
| +1 | checkstyle | 23 | the patch passed |
| +1 | mvnsite | 33 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 632 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 24 | the patch passed |
| +1 | findbugs | 46 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 185 | hadoop-auth in the patch passed. |
| +1 | asflicense | 42 | The patch does not generate ASF License warnings. |
| | | 5159 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-440/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/440 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux f32ab2372e10 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / cd967c7 |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-440/1/testReport/ |
| Max. process+thread count | 446 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-auth U: hadoop-common-project/hadoop-auth |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-440/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 1064 | trunk passed |
| +1 | compile | 1065 | trunk passed |
| +1 | checkstyle | 20 | trunk passed |
| +1 | mvnsite | 31 | trunk passed |
| +1 | shadedclient | 670 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 26 | trunk passed |
| 0 | spotbugs | 42 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 39 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 19 | the patch passed |
| +1 | compile | 967 | the patch passed |
| +1 | javac | 967 | the patch passed |
| +1 | checkstyle | 20 | the patch passed |
| +1 | mvnsite | 32 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 609 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 24 | the patch passed |
| +1 | findbugs | 48 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 190 | hadoop-auth in the patch passed. |
| +1 | asflicense | 42 | The patch does not generate ASF License warnings. |
| | | 5020 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-440/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/440 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux f6d5f292effe 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c7c7a88 |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-440/2/testReport/ |
| Max. process+thread count | 444 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-auth U: hadoop-common-project/hadoop-auth |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-440/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by steveloughran** [comment]
+1, merged to trunk.

**Pull request closed without merging**
