### PR TITLE
HADOOP-15136. Correct typos in filesystem.md

### PR DESCRIPTION
**Pull request by tucked**
https://issues.apache.org/jira/browse/HADOOP-15136

### CODE REVIEW

**Review by steveloughran — APPROVED** [review]
+1
thanks for finding these. you were clearly doing the due diligence

**Comment by steveloughran** [comment]
Merged.

David, if you are getting into rename semantics know that nobody is confident enough about it to be certain about what happens in cases, we know HDFS gets it "wrong" in some. If you have spare time a review of #743 would be wonderful.

**Comment by steveloughran** [comment]
Also: you got a login on the apache JIRA so I can assign/credit the issue there to you

**Comment by tucked** [comment]
>  If you have spare time a review of #743 would be wonderful.

Not sure if/how much I'll be able to help, but sure! I'll take a peek.

> Also: you got a login on the apache JIRA so I can assign/credit the issue there to you

Yes, I'm also [tucked on JIRA](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tucked) 😊

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 15s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  31m 20s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 16s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  48m 22s |  branch has no errors when building and testing our client artifacts.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 51s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 10s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  15m 34s |  patch has no errors when building and testing our client artifacts.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 29s |  The patch does not generate ASF License warnings.  |
|  |   |  69m 29s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2314/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2314 |
| Optional Tests | dupname asflicense mvnsite markdownlint |
| uname | Linux 81b973723627 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 2377df38ad2 |
| Max. process+thread count | 337 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2314/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
