### PR TITLE
HDDS-1928. Cannot run ozone-recon compose due to syntax error

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Add missing version tag for `datanode` service in `ozone-recon` compose.

https://issues.apache.org/jira/browse/HDDS-1928

## How was this patch tested?

```
$ docker-compose up -d --scale datanode=3
Creating network "ozone-recon_default" with the default driver
Creating ozone-recon_datanode_1 ... done
Creating ozone-recon_datanode_2 ... done
Creating ozone-recon_datanode_3 ... done
Creating ozone-recon_recon_1    ... done
Creating ozone-recon_scm_1      ... done
Creating ozone-recon_om_1       ... done
```

### CODE REVIEW

**Comment by adoroszlai** [comment]
@vivekratnavel please review

(Not labelling this PR with `ozone` because `ozone-recon` dir doesn't have `test.sh` script anyway, so test success/failure wouldn't prove anything (except maybe "author" check).)

**Comment by vivekratnavel** [comment]
+1 (non-binding) LGTM

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 124 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | yamllint | 0 | yamllint was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 663 | trunk passed |
| +1 | compile | 378 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1917 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 208 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 604 | the patch passed |
| +1 | compile | 397 | the patch passed |
| +1 | javac | 397 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 739 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 182 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 357 | hadoop-hdds in the patch passed. |
| -1 | unit | 3081 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 59 | The patch does not generate ASF License warnings. |
| | | 7859 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.scm.pipeline.TestRatisPipelineCreateAndDestory |
|   | hadoop.ozone.om.TestSecureOzoneManager |
|   | hadoop.ozone.client.rpc.Test2WayCommitInRatis |
|   | hadoop.ozone.container.common.statemachine.commandhandler.TestBlockDeletion |
|   | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.ozone.client.rpc.TestMultiBlockWritesWithDnFailures |
|   | hadoop.ozone.TestMiniOzoneCluster |
|   | hadoop.hdds.scm.pipeline.TestSCMRestart |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1249 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient yamllint |
| uname | Linux aa37201bad44 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 827dbb1 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/1/testReport/ |
| Max. process+thread count | 5338 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/dist U: hadoop-ozone/dist |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | yamllint | 0 | yamllint was not available. |
| +1 | @author | 1 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 609 | trunk passed |
| +1 | compile | 370 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1691 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 146 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 556 | the patch passed |
| +1 | compile | 362 | the patch passed |
| +1 | javac | 362 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 619 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 156 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 295 | hadoop-hdds in the patch passed. |
| -1 | unit | 2056 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 63 | The patch does not generate ASF License warnings. |
| | | 6146 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.client.rpc.TestMultiBlockWritesWithDnFailures |
|   | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1249 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient yamllint |
| uname | Linux 2ee235b6c525 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 3cc0ace |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/2/testReport/ |
| Max. process+thread count | 5379 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/dist U: hadoop-ozone/dist |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 44 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | yamllint | 0 | yamllint was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 588 | trunk passed |
| +1 | compile | 345 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1641 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 152 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 558 | the patch passed |
| +1 | compile | 358 | the patch passed |
| +1 | javac | 358 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 621 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 152 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 303 | hadoop-hdds in the patch passed. |
| -1 | unit | 3230 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 35 | The patch does not generate ASF License warnings. |
| | | 7252 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.om.TestKeyManagerImpl |
|   | hadoop.ozone.TestStorageContainerManager |
|   | hadoop.ozone.client.rpc.TestMultiBlockWritesWithDnFailures |
|   | hadoop.ozone.container.common.statemachine.commandhandler.TestCloseContainerByPipeline |
|   | hadoop.ozone.ozShell.TestOzoneShell |
|   | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.ozone.web.client.TestOzoneClient |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.Test2WayCommitInRatis |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.om.TestOzoneManagerHA |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1249 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient yamllint |
| uname | Linux c9544017f42a 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 00b5a27 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/3/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/3/testReport/ |
| Max. process+thread count | 4230 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/dist U: hadoop-ozone/dist |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/3/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 128 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | yamllint | 0 | yamllint was not available. |
| 0 | shelldocs | 0 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 815 | trunk passed |
| +1 | compile | 494 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1040 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 222 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 608 | the patch passed |
| +1 | compile | 402 | the patch passed |
| +1 | javac | 402 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 743 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 177 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 346 | hadoop-hdds in the patch passed. |
| -1 | unit | 3131 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 51 | The patch does not generate ASF License warnings. |
| | | 8411 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdds.scm.pipeline.TestRatisPipelineCreateAndDestory |
|   | hadoop.ozone.om.TestSecureOzoneManager |
|   | hadoop.ozone.client.rpc.TestCloseContainerHandlingByClient |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.om.TestScmSafeMode |
|   | hadoop.ozone.client.rpc.TestMultiBlockWritesWithDnFailures |
|   | hadoop.ozone.client.rpc.TestCommitWatcher |
|   | hadoop.ozone.om.TestKeyManagerImpl |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1249 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient yamllint shellcheck shelldocs |
| uname | Linux 0d6598a871ab 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 63161cf |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/5/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/5/testReport/ |
| Max. process+thread count | 5273 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/dist U: hadoop-ozone/dist |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1249/5/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by avijayanhwx** [comment]
LGTM +1

**Comment by adoroszlai** [comment]
Thanks @vivekratnavel, @avijayanhwx for the review, @elek for the idea to add `test.sh`, and @anuengineer for commiting it.

**Pull request closed without merging**
