### PR TITLE
HDFS-16333. fix balancer bug when transfer an EC block

### PR DESCRIPTION
**Pull request by liubingxing**
JIRA: [HDFS-16333](https://issues.apache.org/jira/browse/HDFS-16333)

### CODE REVIEW

**Comment by liubingxing** [comment]
@tasanuma this PR is for branch-3.3

**Comment by tasanuma** [comment]
Thanks for creating the PR, @liubingxing. +1, pending Jenkins.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   5m 21s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 1 new or modified test files.  |
|||| _ branch-3.3 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  31m 41s |  |  branch-3.3 passed  |
| +1 :green_heart: |  compile  |   1m 14s |  |  branch-3.3 passed  |
| +1 :green_heart: |  checkstyle  |   0m 48s |  |  branch-3.3 passed  |
| +1 :green_heart: |  mvnsite  |   1m 21s |  |  branch-3.3 passed  |
| +1 :green_heart: |  javadoc  |   1m 31s |  |  branch-3.3 passed  |
| +1 :green_heart: |  spotbugs  |   3m 11s |  |  branch-3.3 passed  |
| +1 :green_heart: |  shadedclient  |  27m 31s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 15s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 10s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 10s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 42s |  |  hadoop-hdfs-project/hadoop-hdfs: The patch generated 0 new + 150 unchanged - 1 fixed = 150 total (was 151)  |
| +1 :green_heart: |  mvnsite  |   1m 15s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 27s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 39s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  28m 30s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 191m 40s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3777/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs.txt) |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 47s |  |  The patch does not generate ASF License warnings.  |
|  |   | 300m 17s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hdfs.server.datanode.TestBPOfferService |
|   | hadoop.hdfs.TestBlockStoragePolicy |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3777/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3777 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell |
| uname | Linux 505b38f15051 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.3 / 0b360fa436f7053f92f70613bfff033893450860 |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3777/1/testReport/ |
| Max. process+thread count | 3125 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs U: hadoop-hdfs-project/hadoop-hdfs |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3777/1/console |
| versions | git=2.17.1 maven=3.6.0 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Review by tasanuma — APPROVED** [review]

**Comment by tasanuma** [comment]
Merged. Thanks again, @liubingxing!

**Comment by liubingxing** [comment]
@tasanuma Thanks for your merge.

**Pull request merged**
