### PR TITLE
HDDS-1490. Support configurable container placement policy 

### PR DESCRIPTION
**Pull request by ChenSammi**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 42 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 9 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for branch |
| +1 | mvninstall | 565 | trunk passed |
| +1 | compile | 279 | trunk passed |
| +1 | checkstyle | 70 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 820 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 159 | trunk passed |
| 0 | spotbugs | 332 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 513 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 36 | Maven dependency ordering for patch |
| +1 | mvninstall | 507 | the patch passed |
| +1 | compile | 282 | the patch passed |
| +1 | javac | 282 | the patch passed |
| -0 | checkstyle | 34 | hadoop-hdds: The patch generated 4 new + 0 unchanged - 0 fixed = 4 total (was 0) |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 4 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 626 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 166 | the patch passed |
| +1 | findbugs | 527 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 237 | hadoop-hdds in the patch passed. |
| -1 | unit | 128 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 43 | The patch does not generate ASF License warnings. |
| | | 5308 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.om.request.bucket.TestOMBucketDeleteRequest |
|   | hadoop.ozone.om.request.bucket.TestOMBucketCreateRequest |
|   | hadoop.ozone.om.ratis.TestOzoneManagerRatisServer |
|   | hadoop.ozone.om.ratis.TestOzoneManagerStateMachine |
|   | hadoop.ozone.om.request.bucket.TestOMBucketSetPropertyRequest |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-898/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/898 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle xml |
| uname | Linux 7f78114fbcbd 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 277e9a8 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/hadoop-multibranch/job/PR-898/1/artifact/out/diff-checkstyle-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-898/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-898/1/testReport/ |
| Max. process+thread count | 1330 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common hadoop-hdds/server-scm hadoop-ozone/integration-test hadoop-ozone/ozone-manager U: . |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-898/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by ChenSammi** [comment]
Failed UTs are not relevant.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 45 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 552 | trunk passed |
| +1 | compile | 293 | trunk passed |
| +1 | checkstyle | 82 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 909 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 174 | trunk passed |
| 0 | spotbugs | 491 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 705 | trunk passed |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 117 | hadoop-hdds in the patch failed. |
| -1 | compile | 95 | hadoop-hdds in the patch failed. |
| -1 | javac | 95 | hadoop-hdds in the patch failed. |
| +1 | checkstyle | 87 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 707 | patch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 172 | the patch passed |
| -1 | findbugs | 167 | hadoop-hdds in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 181 | hadoop-hdds in the patch failed. |
| -1 | unit | 1387 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 55 | The patch does not generate ASF License warnings. |
| | | 6867 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ozone.container.common.impl.TestHddsDispatcher |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClientWithRatis |
|   | hadoop.ozone.client.rpc.TestOzoneAtRestEncryption |
|   | hadoop.ozone.client.rpc.TestOzoneRpcClient |
|   | hadoop.ozone.client.rpc.TestBCSID |
|   | hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException |
|   | hadoop.ozone.client.rpc.TestSecureOzoneRpcClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-898/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/898 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 08b63b44fa1e 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / fcfe7a3 |
| Default Java | 1.8.0_212 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-898/2/artifact/out/patch-mvninstall-hadoop-hdds.txt |
| compile | https://builds.apache.org/job/hadoop-multibranch/job/PR-898/2/artifact/out/patch-compile-hadoop-hdds.txt |
| javac | https://builds.apache.org/job/hadoop-multibranch/job/PR-898/2/artifact/out/patch-compile-hadoop-hdds.txt |
| findbugs | https://builds.apache.org/job/hadoop-multibranch/job/PR-898/2/artifact/out/patch-findbugs-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-898/2/artifact/out/patch-unit-hadoop-hdds.txt |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-898/2/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-898/2/testReport/ |
| Max. process+thread count | 4640 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/server-scm U: hadoop-hdds/server-scm |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-898/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by ChenSammi** [comment]
duplicate with GitHub Pull Request #903

**Pull request closed without merging**
