### PR TITLE
HDDS-2024. Fix rat.sh problems

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Fix problems in `rat.sh`:

1. `grep: warning: recursive search of stdin` due to missing search target (which works with GNU grep, but not with some others)
2. `cat: target/rat-aggregated.txt: No such file or directory` due mismatch of `REPORT_FILE` value vs. literal
3. typo in `REPORT_FILE` value

Also: use `-s` test instead of `cat` (probably cheaper and safer).

https://issues.apache.org/jira/browse/HDDS-2024

## How was this patch tested?

```
$ ./hadoop-ozone/dev-support/checks/rat.sh
...
[INFO] Build failures were ignored.
hadoop-hdds/common/target/rat.txt: !????? hadoop-hdds/common/src/main/java/org/apache/hadoop/utils/db/cache/CacheResult.java
hadoop-ozone/dist/target/rat.txt: !????? hadoop-ozone/dist/src/main/compose/ozones3-haproxy/haproxy-conf/haproxy.cfg
hadoop-ozone/integration-test/target/rat.txt: !????? hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientForAclAuditLog.java
hadoop-ozone/common/target/rat.txt: !????? hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/util/BooleanBiFunction.java
hadoop-ozone/ozone-manager/target/rat.txt: !????? hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/bucket/TestS3BucketDeleteResponse.java
hadoop-ozone/ozone-manager/target/rat.txt: !????? hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadAbortResponse.java
hadoop-ozone/ozone-manager/target/rat.txt: !????? hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequest.java
hadoop-ozone/ozone-manager/target/rat.txt: !????? hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadAbortRequest.java
hadoop-ozone/ozone-manager/target/rat.txt: !????? hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponse.java
hadoop-ozone/ozone-manager/target/rat.txt: !????? hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyPurgeResponse.java
hadoop-ozone/ozone-manager/target/rat.txt: !????? hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerDoubleBufferHelper.java
hadoop-ozone/ozone-manager/target/rat.txt: !????? hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
hadoop-ozone/ozone-manager/target/rat.txt: !????? hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyPurgeRequest.java
hadoop-ozone/ozone-manager/target/rat.txt: !????? hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/acl/OMBucketSetAclRequest.java
hadoop-ozone/ozone-manager/target/rat.txt: !????? hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/acl/OMBucketRemoveAclRequest.java
hadoop-ozone/ozone-manager/target/rat.txt: !????? hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/acl/OMVolumeAclRequest.java

$ echo $?
1
```

### CODE REVIEW

**Comment by adoroszlai** [comment]
@elek please review

**Comment by adoroszlai** [comment]
Thanks @elek for the review and commit.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 44 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 0 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 754 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1023 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 617 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 783 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 103 | hadoop-hdds in the patch passed. |
| +1 | unit | 297 | hadoop-ozone in the patch passed. |
| +1 | asflicense | 42 | The patch does not generate ASF License warnings. |
| | | 3890 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1343/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1343 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux d8d2be37227c 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / b4a95a2 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1343/1/testReport/ |
| Max. process+thread count | 334 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1343/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 45 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| 0 | shelldocs | 1 | Shelldocs was not available. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 594 | trunk passed |
| +1 | mvnsite | 1 | trunk passed |
| +1 | shadedclient | 764 | branch has no errors when building and testing our client artifacts. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 551 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedclient | 727 | patch has no errors when building and testing our client artifacts. |
||| _ Other Tests _ |
| +1 | unit | 97 | hadoop-hdds in the patch passed. |
| +1 | unit | 278 | hadoop-ozone in the patch passed. |
| +1 | asflicense | 36 | The patch does not generate ASF License warnings. |
| | | 3281 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1343/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1343 |
| Optional Tests | dupname asflicense mvnsite unit shellcheck shelldocs |
| uname | Linux 96a2de459f81 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / d3fe993 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1343/2/testReport/ |
| Max. process+thread count | 446 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1343/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.4.6 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
