### PR TITLE
HDDS-1581. Atleast one of the metadata dir config property must be tagged as REQUIRED

### PR DESCRIPTION
**Pull request by dineshchitlangia**
Added REQUIRED tag on fallback property and updated description of other configs as needed.

### CODE REVIEW

**Comment by dineshchitlangia** [comment]
@xiaoyuyao Please help to review/commit. Thanks for guidance.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 30 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ trunk Compile Tests _ |
| +1 | mvninstall | 658 | trunk passed |
| +1 | compile | 308 | trunk passed |
| +1 | mvnsite | 0 | trunk passed |
| +1 | shadedclient | 1894 | branch has no errors when building and testing our client artifacts. |
| +1 | javadoc | 169 | trunk passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 588 | the patch passed |
| +1 | compile | 292 | the patch passed |
| +1 | javac | 292 | the patch passed |
| +1 | mvnsite | 0 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| -1 | shadedclient | 1168 | patch has errors when building and testing our client artifacts. |
| +1 | javadoc | 160 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 250 | hadoop-hdds in the patch passed. |
| -1 | unit | 1563 | hadoop-ozone in the patch failed. |
| +1 | asflicense | 80 | The patch does not generate ASF License warnings. |
| | | 6389 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-872/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/872 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux e13922c9b02a 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / c1caab4 |
| Default Java | 1.8.0_212 |
| unit | https://builds.apache.org/job/hadoop-multibranch/job/PR-872/1/artifact/out/patch-unit-hadoop-ozone.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-872/1/testReport/ |
| Max. process+thread count | 4080 (vs. ulimit of 5500) |
| modules | C: hadoop-hdds/common U: hadoop-hdds/common |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-872/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by anuengineer** [comment]
@bharatviswa504  Thanks for the review. @dineshchitlangia  Thanks for the contribution.

**Comment by dineshchitlangia** [comment]
@bharatviswa504  thanks for review, @anuengineer thanks for commit

**Pull request merged**
