### PR TITLE
YARN-10656. Parsing error in CapacityScheduler.md

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/YARN-10656

Manually tested.

### CODE REVIEW

**Comment by aajisaka** [comment]
Built locally after applying the patch. `<` and `>` are escaped as expected.
Screenshot from 2021-02-27 03-12-37

**Comment by pbacsko** [comment]
+1

**Comment by zhuqi-lucas** [comment]
+1

**Comment by aajisaka** [comment]
The mvnsite failure is in trunk compile tests (i.e. before applying the patch). Merging this.

```
04:11:53  +---------------------------------------------------------------------------
04:11:53  |      |                  |            | trunk Compile Tests 
04:11:53  +---------------------------------------------------------------------------
04:11:53  |  +1  |      mvninstall  |  32m 32s   | trunk passed 
04:11:53  |  -1  |         mvnsite  |   0m 25s   | hadoop-yarn-site in trunk failed. 
04:11:53  |  +1  |    shadedclient  |  46m 13s   | branch has no errors when building and 
04:11:53  |      |                  |            | testing our client artifacts.
04:11:53  +---------------------------------------------------------------------------
04:11:53  |      |                  |            | Patch Compile Tests 
04:11:53  +---------------------------------------------------------------------------
04:11:53  |  +1  |      mvninstall  |   0m 14s   | the patch passed 
04:11:53  |  +1  |          blanks  |   0m  0s   | The patch has no blanks issues. 
04:11:53  |  +1  |         mvnsite  |   0m 18s   | the patch passed 
04:11:53  |  +1  |    shadedclient  |  13m 15s   | patch has no errors when building and 
04:11:53  |      |                  |            | testing our client artifacts.
```
Thank you @pbacsko and @qizhu-lucas for your reviews.

**Pull request merged**
