### PR TITLE
HADOOP-17251. Upgrade netty-all to 4.1.50.Final on branch-2.10.

### PR DESCRIPTION
**Pull request by iwasakims**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  11m 41s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-2.10 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  17m  3s |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |   0m 19s |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |   0m 24s |  branch-2.10 passed  |
| +1 :green_heart: |  javadoc  |   0m 22s |  branch-2.10 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 13s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 12s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 14s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 13s |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 29s |  The patch does not generate ASF License warnings.  |
|  |   |  34m 20s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2285/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2285 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux a49ba550387b 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / 43c6c54 |
| Default Java | Oracle Corporation-1.7.0_95-b00 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2285/1/testReport/ |
| Max. process+thread count | 73 (vs. ulimit of 5500) |
| modules | C: hadoop-project U: hadoop-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2285/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by iwasakims** [comment]
TestWebHDFS passed with the patch on my local.

**Review by jojochuang — APPROVED** [review]
LGTM.
We bumped netty version from 4.0.x to 4.1.x in HADOOP-16643 for Hadoop 3. And the API appears to be compatible, so I believe it should work as well for 2.10.

**Comment by iwasakims** [comment]
Thanks, @jojochuang. I merged this.

**Pull request merged**
