### PR TITLE
HDDS-1358 : Recon Server REST API not working as expected.

### PR DESCRIPTION
**Pull request by avijayanhwx**
- Fixed the Guice Jersey-hk2 integration.
- Added blocks to KeyMetadata
- Minor fixes/improvements.

Manually tested on single node cluster.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 49 | Maven dependency ordering for branch |
| +1 | mvninstall | 1175 | trunk passed |
| +1 | compile | 100 | trunk passed |
| +1 | checkstyle | 27 | trunk passed |
| +1 | mvnsite | 61 | trunk passed |
| +1 | shadedclient | 789 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 72 | trunk passed |
| +1 | javadoc | 40 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 20 | Maven dependency ordering for patch |
| +1 | mvninstall | 61 | the patch passed |
| +1 | compile | 109 | the patch passed |
| +1 | javac | 109 | the patch passed |
| +1 | checkstyle | 26 | the patch passed |
| +1 | mvnsite | 53 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 3 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 784 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 86 | the patch passed |
| +1 | javadoc | 36 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 36 | s3gateway in the patch passed. |
| +1 | unit | 38 | ozone-recon in the patch passed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 3703 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-668/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/668 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  xml  findbugs  checkstyle  |
| uname | Linux 9d53a6099cc6 4.4.0-138-generic #164~14.04.1-Ubuntu SMP Fri Oct 5 08:56:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 56f1e13 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-668/1/testReport/ |
| Max. process+thread count | 305 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/s3gateway hadoop-ozone/ozone-recon U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-668/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 49 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ trunk Compile Tests _ |
| 0 | mvndep | 12 | Maven dependency ordering for branch |
| +1 | mvninstall | 1151 | trunk passed |
| +1 | compile | 101 | trunk passed |
| +1 | checkstyle | 27 | trunk passed |
| +1 | mvnsite | 53 | trunk passed |
| +1 | shadedclient | 798 | branch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 76 | trunk passed |
| +1 | javadoc | 39 | trunk passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 12 | Maven dependency ordering for patch |
| +1 | mvninstall | 65 | the patch passed |
| +1 | compile | 99 | the patch passed |
| +1 | javac | 99 | the patch passed |
| +1 | checkstyle | 25 | the patch passed |
| +1 | mvnsite | 47 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 4 | The patch has no ill-formed XML file. |
| +1 | shadedclient | 811 | patch has no errors when building and testing our client artifacts. |
| +1 | findbugs | 84 | the patch passed |
| +1 | javadoc | 36 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 39 | s3gateway in the patch passed. |
| +1 | unit | 43 | ozone-recon in the patch passed. |
| +1 | asflicense | 27 | The patch does not generate ASF License warnings. |
| | | 3672 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/hadoop-multibranch/job/PR-668/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/668 |
| Optional Tests |  dupname  asflicense  compile  javac  javadoc  mvninstall  mvnsite  unit  shadedclient  xml  findbugs  checkstyle  |
| uname | Linux 9e6bd80af775 4.4.0-138-generic #164~14.04.1-Ubuntu SMP Fri Oct 5 08:56:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | trunk / 56f1e13 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| findbugs | v3.1.0-RC1 |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-668/2/testReport/ |
| Max. process+thread count | 305 (vs. ulimit of 5500) |
| modules | C: hadoop-ozone/s3gateway hadoop-ozone/ozone-recon U: hadoop-ozone |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-668/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by vivekratnavel** [comment]
+1 LGTM

**Comment by arp7** [comment]
+1 lgtm.

**Pull request merged**
