### PR TITLE
MAPREDUCE-7294. Only application master should upload resource to Yarn Shared Cache.

### PR DESCRIPTION
**Pull request by JohnZZGithub**
…n Shared Cache

## NOTICE

Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  11m 16s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-2.10 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 24s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  15m 24s |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |   1m 36s |  branch-2.10 passed  |
| +1 :green_heart: |  checkstyle  |   0m 40s |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |   1m 27s |  branch-2.10 passed  |
| +1 :green_heart: |  javadoc  |   1m  3s |  branch-2.10 passed  |
| +0 :ok: |  spotbugs  |   1m 30s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 42s |  branch-2.10 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 12s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 28s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 28s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 35s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 15s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 53s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   2m 55s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   3m 30s |  hadoop-mapreduce-client-core in the patch failed.  |
| +1 :green_heart: |  unit  |   8m  3s |  hadoop-mapreduce-client-app in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 30s |  The patch does not generate ASF License warnings.  |
|  |   |  60m 43s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.mapreduce.jobhistory.TestHistoryViewerPrinter |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2319/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2319 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux ad54ca2b9b3d 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / 4885ea6 |
| Default Java | Oracle Corporation-1.7.0_95-b00 |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2319/1/artifact/out/patch-unit-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2319/1/testReport/ |
| Max. process+thread count | 484 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app U: hadoop-mapreduce-project/hadoop-mapreduce-client |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2319/1/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  18m 32s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-2.10 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 21s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  17m 53s |  branch-2.10 passed  |
| +1 :green_heart: |  compile  |   2m  2s |  branch-2.10 passed  |
| +1 :green_heart: |  checkstyle  |   0m 47s |  branch-2.10 passed  |
| +1 :green_heart: |  mvnsite  |   1m 45s |  branch-2.10 passed  |
| +1 :green_heart: |  javadoc  |   1m 16s |  branch-2.10 passed  |
| +0 :ok: |  spotbugs  |   1m 56s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m 28s |  branch-2.10 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 26s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 53s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 53s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 41s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 33s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   1m 10s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   3m 33s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   3m 50s |  hadoop-mapreduce-client-core in the patch failed.  |
| +1 :green_heart: |  unit  |   9m  7s |  hadoop-mapreduce-client-app in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   |  75m 43s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.mapreduce.jobhistory.TestHistoryViewerPrinter |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2319/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2319 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux a637780f1673 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-2.10 / 4885ea6 |
| Default Java | Oracle Corporation-1.7.0_95-b00 |
| unit | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2319/2/artifact/out/patch-unit-hadoop-mapreduce-project_hadoop-mapreduce-client_hadoop-mapreduce-client-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2319/2/testReport/ |
| Max. process+thread count | 474 (vs. ulimit of 5500) |
| modules | C: hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app U: hadoop-mapreduce-project/hadoop-mapreduce-client |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2319/2/console |
| versions | git=2.7.4 maven=3.3.9 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by liuml07 — APPROVED** [review]
+1

**Comment by liuml07** [comment]
Failing tests are not related, and can not be reproduced locally.

**Pull request merged**
