### PR TITLE
HADOOP-16772. Extract version numbers to head of pom.xml (addendum)

### PR DESCRIPTION
**Pull request by tamaashu**
Follow up task of HADOOP-16729, extract even more version numbers for branch-3.2.

Change-Id: I0546fc8ec8f68baa4bcfa9db0df4d8293b078913

### CODE REVIEW

**Comment by tamaashu** [comment]
PR for trunk in https://github.com/apache/hadoop/pull/1773

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 974 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -1 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-3.2 Compile Tests _ |
| -1 | mvninstall | 328 | root in branch-3.2 failed. |
| +1 | compile | 11 | branch-3.2 passed |
| +1 | mvnsite | 14 | branch-3.2 passed |
| -1 | shadedclient | 571 | branch has errors when building and testing our client artifacts. |
| +1 | javadoc | 13 | branch-3.2 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 13 | the patch passed |
| +1 | compile | 10 | the patch passed |
| +1 | javac | 10 | the patch passed |
| +1 | mvnsite | 12 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| -1 | shadedclient | 257 | patch has errors when building and testing our client artifacts. |
| +1 | javadoc | 12 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 12 | hadoop-project in the patch passed. |
| +1 | asflicense | 24 | The patch does not generate ASF License warnings. |
| | | 2035 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/hadoop-multibranch/job/PR-1774/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/1774 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient xml |
| uname | Linux dde9b7cd5408 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/hadoop.sh |
| git revision | branch-3.2 / 59cdf18 |
| Default Java | 1.8.0_232 |
| mvninstall | https://builds.apache.org/job/hadoop-multibranch/job/PR-1774/1/artifact/out/branch-mvninstall-root.txt |
|  Test Results | https://builds.apache.org/job/hadoop-multibranch/job/PR-1774/1/testReport/ |
| Max. process+thread count | 83 (vs. ulimit of 5500) |
| modules | C: hadoop-project U: hadoop-project |
| Console output | https://builds.apache.org/job/hadoop-multibranch/job/PR-1774/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by tamaashu** [comment]
retest

**Comment by bgaborg** [comment]
+1, compile works for me, change seems ok.

**Pull request merged**
