### PR TITLE
HDDS-1103. Fix rat/findbug/checkstyle errors in ozone/hdds projects

### PR DESCRIPTION
**Pull request by elek**
see: https://issues.apache.org/jira/browse/HDDS-1103

### CODE REVIEW

**Comment by elek** [comment]
acceptance tests are also fixed: I moved the auditlogparser to a separated directory (it calculates the number of the audit events, should be executed together with other tests) and added a sleep to be sure that the om is started.

Removed the "-it" flags from docker-compose executions to make it possible to run from docker in docker.

**Comment by xiaoyuyao** [comment]
Thanks @elek  for fixing these. +1 pending Jenkins.

**Comment by elek** [comment]
Remaining test failures are not related AFAIK.

**Comment by elek** [comment]
Only the licence header is conflicted with HDDS-1110. I rebased.

**Comment by elek** [comment]
Thanks the review and the merge.

**Pull request closed without merging**
