### PR TITLE
HADOOP-19310. (3.4) Add JPMS options required by Java 17+

### PR DESCRIPTION
**Pull request by pan3793**
JIRA: HADOOP-19310. (3.4) Add JPMS options required by Java 17+

Backport #7114 to branch-3.4

### CODE REVIEW

**Comment by pan3793** [comment]
cc @slfan1989

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   6m 52s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m  2s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  28m 47s |  |  branch-3.4 passed  |
| +1 :green_heart: |  compile  |   9m  0s |  |  branch-3.4 passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  compile  |   8m 20s |  |  branch-3.4 passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  mvnsite  |   3m 26s |  |  branch-3.4 passed  |
| +1 :green_heart: |  javadoc  |   3m  7s |  |  branch-3.4 passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javadoc  |   2m 54s |  |  branch-3.4 passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  shadedclient  |  26m  9s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 23s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 43s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   9m 17s |  |  the patch passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javac  |   9m 17s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   9m 27s |  |  the patch passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  javac  |   9m 27s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   2m 48s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  2s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   2m 14s |  |  the patch passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javadoc  |   2m 11s |  |  the patch passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| -1 :x: |  shadedclient  |  32m 14s |  |  patch has errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 19s |  |  hadoop-project in the patch passed.  |
| -1 :x: |  unit  |  10m 14s | [/patch-unit-hadoop-common-project_hadoop-common.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7118/1/artifact/out/patch-unit-hadoop-common-project_hadoop-common.txt) |  hadoop-common in the patch failed.  |
| -1 :x: |  unit  |   0m 30s | [/patch-unit-hadoop-common-project_hadoop-registry.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7118/1/artifact/out/patch-unit-hadoop-common-project_hadoop-registry.txt) |  hadoop-registry in the patch failed.  |
| -1 :x: |  unit  |   0m 31s | [/patch-unit-hadoop-tools_hadoop-distcp.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7118/1/artifact/out/patch-unit-hadoop-tools_hadoop-distcp.txt) |  hadoop-distcp in the patch failed.  |
| -1 :x: |  unit  |   0m 33s | [/patch-unit-hadoop-tools_hadoop-federation-balance.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7118/1/artifact/out/patch-unit-hadoop-tools_hadoop-federation-balance.txt) |  hadoop-federation-balance in the patch failed.  |
| -1 :x: |  unit  |   0m 33s | [/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-timelineservice-hbase-tests.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7118/1/artifact/out/patch-unit-hadoop-yarn-project_hadoop-yarn_hadoop-yarn-server_hadoop-yarn-server-timelineservice-hbase-tests.txt) |  hadoop-yarn-server-timelineservice-hbase-tests in the patch failed.  |
| +0 :ok: |  asflicense  |   0m 31s |  |  ASF License check generated no output?  |
|  |   | 157m 53s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.ipc.TestIPC |
|   | hadoop.ipc.TestAsyncIPC |
|   | hadoop.net.TestSocketIOWithTimeout |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7118/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/7118 |
| Optional Tests | dupname asflicense mvnsite unit codespell detsecrets shellcheck shelldocs compile javac javadoc mvninstall shadedclient xmllint |
| uname | Linux ba50237a8c5c 5.15.0-117-generic #127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.4 / 5a7d8900dd2d6396f87b1ab8b00e6b4d69750b9a |
| Default Java | Private Build-1.8.0_422-8u422-b05-1~20.04-b05 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_422-8u422-b05-1~20.04-b05 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7118/1/testReport/ |
| Max. process+thread count | 1285 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-tools/hadoop-distcp hadoop-tools/hadoop-federation-balance hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7118/1/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Review by slfan1989 — APPROVED** [review]

**Comment by slfan1989** [comment]
@pan3793 We need to trigger the compilation again.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 20s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +0 :ok: |  xmllint  |   0m  0s |  |  xmllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 16s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  29m  5s |  |  branch-3.4 passed  |
| +1 :green_heart: |  compile  |   9m 11s |  |  branch-3.4 passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  compile  |   8m 13s |  |  branch-3.4 passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  mvnsite  |   3m 32s |  |  branch-3.4 passed  |
| +1 :green_heart: |  javadoc  |   2m 43s |  |  branch-3.4 passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javadoc  |   2m 27s |  |  branch-3.4 passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  shadedclient  |  32m 22s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 23s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 39s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   8m 45s |  |  the patch passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javac  |   8m 45s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   8m 22s |  |  the patch passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  javac  |   8m 22s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   3m 14s |  |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  2s |  |  No new issues.  |
| +1 :green_heart: |  javadoc  |   3m  1s |  |  the patch passed with JDK Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04  |
| +1 :green_heart: |  javadoc  |   2m 57s |  |  the patch passed with JDK Private Build-1.8.0_422-8u422-b05-1~20.04-b05  |
| +1 :green_heart: |  shadedclient  |  27m 26s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 24s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  unit  |  16m 46s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  2s |  |  hadoop-registry in the patch passed.  |
| +1 :green_heart: |  unit  |  15m 25s |  |  hadoop-distcp in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 17s |  |  hadoop-federation-balance in the patch passed.  |
| +1 :green_heart: |  unit  |   9m  6s |  |  hadoop-yarn-server-timelineservice-hbase-tests in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 43s |  |  The patch does not generate ASF License warnings.  |
|  |   | 184m 40s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7118/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/7118 |
| Optional Tests | dupname asflicense mvnsite unit codespell detsecrets shellcheck shelldocs compile javac javadoc mvninstall shadedclient xmllint |
| uname | Linux ce4d77bb151c 5.15.0-117-generic #127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.4 / dc952a9d5ac9d9ac153f31ad15328755b576bd33 |
| Default Java | Private Build-1.8.0_422-8u422-b05-1~20.04-b05 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.24+8-post-Ubuntu-1ubuntu320.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_422-8u422-b05-1~20.04-b05 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7118/2/testReport/ |
| Max. process+thread count | 1318 (vs. ulimit of 5500) |
| modules | C: hadoop-project hadoop-common-project/hadoop-common hadoop-common-project/hadoop-registry hadoop-tools/hadoop-distcp hadoop-tools/hadoop-federation-balance hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests U: . |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-7118/2/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by slfan1989** [comment]
@pan3793 Thanks for the contribution! Merged into branch-3.4.

**Pull request merged**
